### ISSUE TITLE
Samsung show blank screen in Remixed

### ISSUE THREAD

**Issue by AceHack** [LibreVR/Revive#1005]
Samsung does not show anything in Remixed, works awesome in Revive, but I just get a black screen in Remixed, sometimes it just tries to launch twice and goes back to cliffs house too instead of a black screen, I can hear the sounds but there is no picture.  Also when I take the HMD off and look at the desktop I can see the app actually launched.

I've tried 1.4.0 beta and earlier builds as well.

I'm running Windows 10 Pro Insider Build 17686.rs_prerelease.180603-1447. This is part of the skip ahead ring.

**Comment by Armada651** [comment]
> I'm running Windows 10 Pro Insider Build 17686.rs_prerelease.180603-1447. This is part of the skip ahead ring.

Remixed is not tested with insider builds, these often contain tons of changes and can easily break Remixed since it is still in beta.

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
