### ISSUE TITLE
Lone echo multiple controller issues

### ISSUE THREAD

**Issue by dx3lory** [LibreVR/Revive#1010]
Hi I have a WMR Headset and whenever I try to play Lone Echo the controllers either don't register any buttons but move (If running through SteamVR/Revive) or seem to move and register buttons (Native/Remixed) but give the 2 red controllers at the bottom and can't actually select anything in the menus. Any ideas?

**Comment by Armada651** [comment]
Sounds like you downloaded the Revive beta while ignoring the warnings, please only use the stable version unless you know what you're doing: https://github.com/LibreVR/Revive/releases/latest

**Comment by dx3lory** [comment]
Hey thanks for that. I have no idea how i ended up downloading the beta version but it works now! Running it through remixed still gives the no controllers error at the bottom and this time they don't actually seem to be recognized at all (They don't move either) but SteamVR works well enough. Thank you!

**Comment by dx3lory** [comment]
Also there is heavy stuttering in revive but that's a common problem for revive+wmr right?

**Comment by Dragoboss** [comment]
Please have a look with the newer versions of both if you're still trying this.
If it's not registering buttons and showing red controllers it means it doesn't see them.
