### ISSUE TITLE
Using Rift with Revive to play Echo Arena and Lone Echo

### ISSUE THREAD

**Issue by billyisms** [LibreVR/Revive#1011]
I am unable to change the controller mappings using the Oculus software. Most games work through revive while using the Rift. 

When I launch Echo Arena or Lone Echo through Revive, the game launches on the monitor, but doesn't show up in the headset. The game even recognizes input. On the SteamVR dashboard it states that Echo Arena and Lone Echo are unresponsive.

I believe there is an error with Revive not detecting that Echo Arena and Lone Echo are working correctly.

**Comment by Armada651** [comment]
Do not use Revive with the Oculus Rift.
