### ISSUE TITLE
Echo arena help

### ISSUE THREAD

**Issue by JefeBoi** [LibreVR/Revive#1013]
I cant click on tutorial or start game using the VIVE headset, i tried clicking all the buttons, is there something im missing?

**Comment by Armada651** [comment]
Which version of Revive did you download?

**Comment by JefeBoi** [comment]
1.4.10

**Comment by JefeBoi** [comment]
I cant clikc anything in the menu

**Comment by JefeBoi** [comment]
I did put in the source code thing as well and it still didn't work

**Comment by Armada651** [comment]
You ignored the warning the installer gave you about it being a beta release, why exactly?

**Comment by JefeBoi** [comment]
Someone told me to download it, anyways if this is a bot or not maybe set
the tone to be more approaching instead of a hostile.
