### ISSUE TITLE
Echo Arena WMR inaccurate throwing

### ISSUE THREAD

**Issue by reaper317** [LibreVR/Revive#1014]
Throwing the disc ln Echo Arena is terribly inaccurate. The disc usually flies off at about an 80 to 90 degree angle from the body when trying to throw straight. Thought maybe it was just me, however multiple people agree.  This is through steam/revive 1.3 as 1.4 beta doesn't recognize controllers. Changing the controller offsets doesn't do much of anything for many of us, but has helped a few.

**Comment by Tux0Topo** [comment]
This a known issue with WMR... No fix for now.

**Comment by reaper317** [comment]
I will try it when I get home next week for sure!

**Comment by Dragoboss** [comment]
Continuation #1128
