### ISSUE TITLE
samsung crosseyed

### ISSUE THREAD

**Issue by sHANONB1** [LibreVR/Revive#1017]
View is off, adjust ipd as low as possible,  then have to cross my eyes to make the image get better

**Comment by Armada651** [comment]
This is already fixed in b996de19c6c09ecceeef16c1439e9a32752db0a1, will be part of the next release.

**Comment by Shannonb1** [comment]
When is the next release plan? I cant get this now can I?

**Comment by Armada651** [comment]
Beta version 1.4.1 is now released.
