### ISSUE TITLE
Dream Deck fails to launch under Revive 0.5.2, Rift Runtime 1.4.0.224996

### ISSUE THREAD

**Issue by DonkeyKong** [LibreVR/Revive#102]
I downloaded Revive, the Oculus Store, and Dream Deck today and followed the instructions posted here: https://github.com/LibreVR/Revive/releases/tag/0.5.2

I downloaded and finalized the installation of Dream Deck. I relaunched steam VR, clicked the Revive button in the dashboard, saw Dream Deck listed, went to launch it and got nothing. Revive dashboard closed and I was dropped back into the white Steam VR room. My log files say the following:

ReviveDashboard.log
> libpng warning: iCCP: known incorrect sRGB profile
> Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
> Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
> Oculus directory: file:///C:/Program Files/Oculus/
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-client.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-compat.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-diagnostics.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck-nux.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck_assets.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-drivers.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-home.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-librarian.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-overlays.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-redistributable-installer.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-runtime.json
> Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/playful-luckys-tale_assets.json
> Found assets bundle oculus-dreamdeck_assets
> Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-dreamdeck.json
> Found assets bundle playful-luckys-tale_assets
> Loading application manifest: file:///C:/Program Files/Oculus/Manifests/playful-luckys-tale.json
> Found application oculus-dreamdeck
> Launching application: oculus-dreamdeck
> Launching application: oculus-dreamdeck
> Failed to launch application: revive.app.oculus-dreamdeck ()
> Launching application: oculus-dreamdeck
> Failed to launch application: revive.app.oculus-dreamdeck ()
> Launching application: oculus-dreamdeck
> Failed to launch application: revive.app.oculus-dreamdeck ()

ReviveInjector.log:
> Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe"
> Creating process: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
> Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
> LoadLibrary found at address: 0xc15574d0
> Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
> LoadLibrary found at address: 0xc15574d0
> Failed to wait for LoadLibrary to exit

 I can see that DreamDeck is, in fact, installed where the log file says it's being launched from. I get no visible errors of any kind.  Any more info needed?

**Comment by LibreVR** [comment]
The DLL injection failed for some reason, probably there's a dependency that couldn't be resolved. Have you ever used Revive before? Did it work then?

**Comment by DonkeyKong** [comment]
No, I have never used Revive before. I just got my Vive 2 days ago.

**Comment by LibreVR** [comment]
Please try the latest release.

**Comment by DonkeyKong** [comment]
I have precisely the same issue in v0.6. I'm even using a fresh install of Windows and an different PC!
