### ISSUE TITLE
cant select anything in the echo vr menu. 1.2.2 no steamvr beta

### ISSUE THREAD

**Issue by tsc108** [LibreVR/Revive#1021]
the game tracks my controllers but i cant select anything, the game doesnt recognize me pulling the trigger or pressing grip buttons or the touchpad. Any fixes?

**Comment by spoonyspork** [comment]
This is also happening for me. If I look to the lower right of the screen, the 'touch controller' icons are blinking red. I was able to play last night without issue. Today it doesn't even show on my game menu on revive. It shows if I run the 'revive overlay' but the above happens when I try to run it (tried alt-tab out of and back into game as well). Happens with Lone Echo as well.

**Comment by cartoonmonkey** [comment]
Try installing openvr advanced settings: https://github.com/matzman666/OpenVR-AdvancedSettings

Change the behavior of the grip / trigger. I forget which. I play echo VR and it works fine with Samsung Odyssey.

**Comment by Armada651** [comment]
@AltVRat Please see issue #1015 for help on the EchoVR update.

**Comment by tsc108** [comment]
i tried this to no effect

**Comment by tsc108** [comment]
any fixes still?

**Comment by AltVRat** [comment]
The inject the exe has been working for me from the revive app.

**Comment by tsc108** [comment]
i wish the developer cared. but no fix btw
mm

**Comment by cartoonmonkey** [comment]
@tsc108 I wish you could code, so that you could fix it yourself, rather than just cry and complain. This is **ONE** dev, doing this work on donated time, who has had the flu. Get out of here or try donating cash to his cause if you don't like the FREE results you've been getting. Jesus.

**Comment by Dragoboss** [comment]
Issue went stale.
Feel free to try again on latest versions and re-post a new ticket if needed.

Should work fine right now.
Make sure to disable motion smoothing before attempting Echo since it breaks their engine.
