### ISSUE TITLE
Having Oculus games installed on both the C-drive and the D-drive does not work

### ISSUE THREAD

**Issue by M0rdresh** [LibreVR/Revive#1028]
I have games on my C-drive (ssd) and use the move function in Oculus Home to move some to the D-drive of my computer. All the moved drives, inside the D:\Oculus\softwarew do not show up in the ReviveOverlay since I moved them.

When I change the D-drive as my default library location (Oculus Home supports multiple paths), the situation reverses, all games on D-drive show up.

Does this mean this is not supported by Revive? Have to have them all in one location ?
If feasible, it would be a great addition. Thanks!

**Comment by Armada651** [comment]
Duplicate of issue #928.
