### ISSUE TITLE
Rock Band VR does not launch

### ISSUE THREAD

**Issue by jonnibravo** [LibreVR/Revive#1029]
Since installing I cannot get this game to launch, it starts loading and after a few seconds it goes back to steam library.  The rock band process remains running in the background but using no CPU resource.

**Comment by Danktoast** [comment]
I am having the exact same problem (had previously opened issue #1012).

**Comment by Armada651** [comment]
Duplicate of #1012

**Comment by Armada651** [comment]
Just return Rock Band VR and buy it again once the issue is fixed.
