### ISSUE TITLE
Revive 0.5.2 won't start any games

### ISSUE THREAD

**Issue by antifreak** [LibreVR/Revive#103]
Reposting from reddit:

I need help because the update wont work, no matter what i do. I reinstalled Revive, i put the new ddls to every .exe (henry, dreamdeck, farlands etc.). I tried getting it to work with the injector myself, still no luck.

Henry for example: When the .dll files are next to henry-win-shipping.exe unreal engine 4 crashes. Without them i get: unable to find HMD (1971039).

Dreamdeck doesn't even start up/ i dont get an error message.

One week with the vive now and i realy liked Henry for Show purposes. Anyone able to help me out? What am i missing/ how to get the update to work.

Also CrossVr gave me the advise to downgrade occulus home, but i dont have an proper windows rollback and i have no idea how to do so. Im not an complete idiot at troubleshooting, but I'm realy having a hard time here.

Thanks for the help and work CrossVR, hope to get this problem fixed and Occulus back to common sense.

**Comment by LibreVR** [comment]
Here's an example of people succeeding to downgrade their runtime: https://www.reddit.com/r/Vive/comments/4kd08m/revive_compatible_oculus_runtime_132_is_still_on/

**Comment by antifreak** [comment]
worked first try, thank you
