### ISSUE TITLE
Remixed Samsung Odyssey Double Vision Still Exists in older games

### ISSUE THREAD

**Issue by LuckyGoodHeart** [LibreVR/Revive#1032]
Hi, thanks for all your hard work!!! I've tested 1.4.1 beta remixed and in games like lucky's tale, heart of emberstone, double vision is still there. Also some games won't start via the Dashboard (wilson's heart, Jurassic Blue, etc.) Brass Tactics, First Contact work brilliantly - they launch, no double vision and performance is great.

Once again, thanks for all your hard work. Really appreciated it.

**Comment by Armada651** [comment]
Lucky's Tale is a game that's using an older version of the Oculus SDK. To fix the problem a new type of compositor function is needed to correct for lens orientation. This will be fixed in the next version of 1.4 when it goes out of beta.

**Comment by Armada651** [comment]
If you use Steam then you're likely using SteamVR with Revive instead of Remixed. Revive is more compatible right now and is the recommended way to play games on Mixed Reality Headsets until Remixed is completed.

**Comment by MicroClue** [comment]
Hello! Just wondering, has there been any update on this? I've been checking out The Unspoken with every Revive release, but I'm still getting double vision in remixed (but better performance) and bad performance in steamvr revive (but no double vision). I also have the Samsung Odyssey (v1). Thanks!

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
