### ISSUE TITLE
Jurassic World Blue

### ISSUE THREAD

**Issue by DarinCGrimm** [LibreVR/Revive#1033]
Game loads up fine, but the controllers don't function in the menu.  The game recognizes the vive controllers because when I turn them off the game says no controllers detected, but I cant click any of the menu options to start the experience.  It was working fine a few weeks ago.  No issues with any other games playing in Revive. I am running SteamVR beta version 1531844726 and Revive 1.3.0.3.  Let me know if you need anymore information.

**Comment by M0rdresh** [comment]
I had exactly the same issues (in other games) with Revive 1.3.x and SteamVR beta, and had better success running Revive 1.4 beta with SteamVR beta or 1.3.x with SteamVR stable release.

**Comment by DarinCGrimm** [comment]
running SteamVR stable version resolved the issue.  Thanks for the help.

**Comment by dimichelec** [comment]
I'm seeing this issue w/ Revive 1.4.2.0 and SteamVR v1533664367

**Comment by dimichelec** [comment]
This works. Both Vive controllers need to be turned on.

**Comment by bdefore** [comment]
This is 15 months later. From latest SteamVR beta, I was able to get this to select from the menu by gazing at one of the options, then clicking towards the bottom of the touchpad of one of the Vive wands - one of them will have no effect. Clicking towards the left of the same touchpad effectively goes back.
