### ISSUE TITLE
medium disappears after it is openned within steamvr/revive

### ISSUE THREAD

**Issue by RollingEggOL** [LibreVR/Revive#1034]
hi, 
thanks for your great work, I installed the latest steamvr(1527117754) and revive(1.3.0) , but medium cannot be launched,  here are logs below:

ReviveInjector.txt
Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" /library "Software\oculus-oculus-medium-retail\bin\OculusMedium.exe"
Creating process: D:\OculusApp_Win7\Software\oculus-oculus-medium-retail\bin\OculusMedium.exe 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x77026530
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x77026530
Injected dlls successfully

ReviveOverlay.txt
libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: C:\Program Files\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: D:\OculusApp_Win7\
qrc:/Overlay.qml:219:9: QML AnimatedImage: Error Reading Animated Image File file:///D:/Program Files (x86)/Steam/steamapps/common/SteamVR/tools/bin/content/vrmonitor/icons/icon_loading.gif
QSoundEffect(qaudio): Error decoding source
QSoundEffect(qaudio): Error decoding source
QSoundEffect(qaudio): Error decoding source
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///d:/OculusApp_Win7/Manifests/oculus-oculus-medium-retail.json
Found application oculus-oculus-medium-retail
Generating manifest for oculus-oculus-medium-retail
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function d2i_DHparams
QSslSocket: cannot call unresolved function DH_free
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
QSslSocket: cannot call unresolved function ERR_get_error
Adding manifest: oculus-oculus-medium-retail
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest
qrc:/Overlay.qml:84:13: QML Image: Cannot open: file:///D:/OculusApp_Win7/Software/StoreAssets/oculus-oculus-medium-retail_assets/cover_square_image.jpg

would you please give some suggestions , thanks.

**Comment by jonnibravo** [comment]
You need to download the beta 1.4.1 here https://github.com/LibreVR/Revive/releases/tag/1.4.1 there is an issue where medium crashes on shut down but it still works see issues log for now info

**Comment by jonnibravo** [comment]
see here for more info on the problem https://github.com/LibreVR/Revive/issues/1022

**Comment by RollingEggOL** [comment]
thanks, revive 1.4.1 makes medium2.0 open, but no buttons can work, I will try the latest steamvr beta, according to  the post https://github.com/LibreVR/Revive/releases/tag/1.4.1

**Comment by jonnibravo** [comment]
You might need to use advanced settings in steamvr as well

**Comment by RollingEggOL** [comment]
It works for me after steamvr beta and revive 1.4.1 beta are both reinstalled. Thanks very much. However, the app crashed after several minutes every time, I will have more tests later.
