### ISSUE TITLE
Oculus First Contact doesn't work anymore

### ISSUE THREAD

**Issue by GAMEDRIX** [LibreVR/Revive#1036]
It seems to be updated , I tried all the revive versions avaible , I stick with the 1.3.0 I'm using htc vive. Can you guys help ?

**Comment by Armada651** [comment]
It's a product offered for free, what did you expect? 24/7 live call support?

**Comment by buzztiaan** [comment]
have you tried turning it off and on again

**Comment by buzztiaan** [comment]
http://catb.org/~esr/faqs/smart-questions.html

**Comment by Armada651** [comment]
Fixed in version 1.4.2: https://github.com/LibreVR/Revive/releases/tag/1.4.2

Thanks for the report, be more patient next time.

**Comment by GAMEDRIX** [comment]
Thank you, I'm new and young that's why I'm so obnoxious. my bad.

**Comment by GAMEDRIX** [comment]
I deleted my rude comment
