### ISSUE TITLE
Lucky's Tale preview doesn't appear on Dashboard

### ISSUE THREAD

**Issue by manuelx98** [LibreVR/Revive#1037]
At first it doesn't appear on Revive Dashboard (on both Desktop and SteamVR) at all, so I reinstalled the game and it's appeared, but only the name without any image (https://puu.sh/B30xA/695113c46b.png).
Tried to reinstall both Revive (last version) and Lucky's Tale but nothing changed. What can I do (except make a custom non-steam link)?

**Comment by manuelx98** [comment]
Can't find any SupportAssets folder, neither in 'C:\Program Files\Oculus\CoreData' nor in my Oculus games folder, but I found a folder named StoreAssets in 'C:\Program Files\Oculus\CoreData\Software' with a folder for each Oculus app/game, containing the preview images, but there's no one for Lucky's Tale. I search for a folder of the same name in my Oculus games folder, but I didn't find anything.

**Comment by manuelx98** [comment]
Found. I found a "StoreAssets" folder on one of my old Oculus games installation folder, I then copypasted the folder containing all LT images from that folder into 'C:\Program Files\Oculus\CoreData\Software\StoreAssets' folder, I reopened Revive and now it shows the LT thumbnail on Dashboard. Thanks for the help.

**Comment by Armada651** [comment]
Ah yeah, it's called StoreAssets, I confused the two names.
