### ISSUE TITLE
Vive inputs don't work

### ISSUE THREAD

**Issue by ShutUpSergeant** [LibreVR/Revive#1038]
I recently downloaded the 1.4.1 Revive beta in order to use Medium, but upon launch, none of the buttons on my Vive controllers seem to do anything. The tracking still works, only the game doesn't respond to any inputs. A quick look at the Oculus avatar creator shows that the controls don't respond there either.

I have tried uninstalling and reinstalling both Revive and SteamVR, (as well as restarting my system) but the problem persists upon startup. I've tried many fixes associated with similar issues, but nothing seems to help.

**Comment by Armada651** [comment]
You need to install the SteamVR beta.
