### ISSUE TITLE
Marvel United VR

### ISSUE THREAD

**Issue by Hexxerr** [LibreVR/Revive#1039]
Not working with revive yet :((

**Comment by M0rdresh** [comment]
Same here, I get a fatal error.
Tried Revive 1.3.0 with SteamVR. Tried Revive 1.4.1 beta with SteamVR beta.

![capture](https://user-images.githubusercontent.com/40898440/43279971-de836c7e-910f-11e8-8a01-33bbc4c65d74.PNG)

**Comment by HgZ0** [comment]
im having issues as well. However, instead of a Fatal Error, i get a message saying that i have a hardware issue and need to check if oculus hardware is attached to my pc

**Comment by M0rdresh** [comment]
I get that too HgZ0, when I launch the game from the Revive Dashboard in Windows outside of SteamVR. When using Revive section within SteamVR I get the error in the screenshot.

**Comment by HgZ0** [comment]
This is the message i get. I tried with revive 1.4.1 beta and with 1.3, both on steamVR from Steam, acessing the game from Revive button on steamvr platform

![error](https://user-images.githubusercontent.com/41757903/43282102-a48515e6-90eb-11e8-81c0-f3f864c85184.png)

**Comment by Armada651** [comment]
@HgZ0 When you install new Oculus software you always get that message, reboot the Oculus Service or your PC first.

> Let's hope the guys get some time to look into this one.

@M0rdresh There's only one guy that will look at it tonight.

**Comment by M0rdresh** [comment]
@Armada651 Much appreciated!

**Comment by HgZ0** [comment]
@Armada651 Thanks! I have rebooted the PC and the Oculus (using the settings menu) and now i get the same error message as @M0rdresh when using steamVR Beta (something about D3D as in the screenshot he posted)

Will wait for a solution then

**Comment by AlexK3321** [comment]
Someone on the Reddit page said they got it working through Viveport but I tried and got the DXGI_ERROR_DEVICE_REMOVED error.
![capture](https://user-images.githubusercontent.com/41760932/43289258-546c7982-9122-11e8-8618-5dfe9830ed56.PNG)

**Comment by HgZ0** [comment]
Tried the reddit suggestion using Viveport here as well and got a different error 
![error2](https://user-images.githubusercontent.com/41757903/43292994-62852dde-910e-11e8-8a84-e4cadb3e73ec.png)

**Comment by IMightBeBoman** [comment]
Is there any word on a fix coming soon?

**Comment by Hexxerr** [comment]
anyone tried without the steambeta? idk

**Comment by Armada651** [comment]
Please test this release, works on both the Steam VR beta and the stable (non-beta):

https://github.com/LibreVR/Revive/releases/tag/1.4.2

**Comment by Hexxerr** [comment]
omg, thank you so much!

**Comment by Spiderianmonkey** [comment]
So i downloaded the new version but the games wont show up in my revive tab, also when i try to launch it from the oculus home it says i have a hardware issue
pls help

**Comment by Jonnysg001** [comment]
Doesn't work with my Samsung Odyssey

**Comment by M0rdresh** [comment]
Dankjewel @Armada651 !

Haven't been able to test it yet as been at work all-day long, and some more.
Given that Hexxerr didn't come back I assume it's fixed (for the Vive).

**Comment by Armada651** [comment]
@Jonnysg001 Are you using Revive or Remixed?

**Comment by Magowin** [comment]
I got game to load with Revive using a Vive but couldn't get past the Prologue I couldn't get Captain America to grab his shield. Will try again when I have more time tonight when I get home.

**Comment by HgZ0** [comment]
I managed to make the game load yesterday night, but didn't test much more than the calibration. Today, im trying to load the game again (didn't install anything, just turned the pc off yesterday and on today) and i keep getting that hardware pending message i had before

**Comment by Jonnysg001** [comment]
I tried both revive and Remixed

**Comment by dtdman420** [comment]
Samsung Odyssey user here. I can not open the game in remixed no matter what i do. I did manage to get it working with revive.

Steam vr and the beta are the same at the moment and on the steam forums ocolus users and others are getting error codes when launching games. So it is quite possible it is something on there end.

When i  got it to work with revive the performance was pretty choppy even at 90fps.

This is my first time posting here so i want to say thank you for this program, without it we would all miss out on all the sweet ocolus exclusives.

**Comment by HgZ0** [comment]
Managed to make it work. Had to uninstall and reinstall Oculus Home for some reason. Then install revive 1.4.2. The game sometimes drops FPS, sometimes the controller doesn't work and you have to reset the game. Managed to play both the prologue and a mission in Jotunhein as Captain America.

**Comment by Armada651** [comment]
@HgZ0 For this game you need to make sure your controllers are on and tracked or else the game will give that error. Also make sure you have both base stations on and detected.

**Comment by M0rdresh** [comment]
Plays great on my rig using 1.4.2. Thanks again.
I play it on Ultra settings, i7-6700L @4.8GHhz - GTX1080.

Although I did experience a play session where indeed some buttons on the controller did not work. The controllers were tracking fine, a restart of the game fixed it. Not sure if that's Revive or a bug in the game.

**Comment by Armada651** [comment]
> Although I did experience a play session where indeed some buttons on the controller did not work. The controllers were tracking fine, a restart of the game fixed it. Not sure if that's Revive or a bug in the game.

That seems to be some kind of rare controller detection issue, if this happens try turning off and back on one of the controllers. Let me know if that works next time you run into the problem, so I can use that information to find the real cause.

**Comment by Armada651** [comment]
Anyone running into the calibration issue, please comment in issue #1042.

**Comment by MaxCancer** [comment]
Hello all, i've buy Marvel Powers United, and i've an HP Windows Mixed reality, i've no problems with games i play HTC games and OCULUS games every days, i love robo recall :) so, i can't play MPU because give me an error about an hardware issue for the oculus, i've installed the revive 1.4.2 and the error change, i can enter in game but told me i've an old version and i can't play….. no one can play and have a solution for me?

**Comment by Magowin** [comment]
I was able to play all weekend with Revive ok. If anyone with Vive using Revive can't get game to load you should first launch Steam VR console then Revive then launch any Vive game I use Beat Saber and once that loads I close that and am then able to launch Marvel game fine and play. I really don't like the controls though so am looking into getting a used rift with touch controllers. Its really hard to get used to not pushing down on touch pad to move around and therefore I get killed somewhat fast.

**Comment by M0rdresh** [comment]
Every since Revive 1.4.2 the game starts up fine, without any trickery needed. I personally like the controls, I don't use the analogue movement, to slow a movement anyway - a super hero dashed from target to target ;)

**Comment by MaxCancer** [comment]
i've revive buy i can't play, ever the some error about hardware issue... nothing i ask refound

**Comment by FrameSkip** [comment]
Using a Lenovo Explorer WMR headset I get severe stuttering.  I get about 5% of my frames reprojected according to Advanced VR but it seems very laggy.

This is running through Revive.  I cannot get it to launch at all in Remixed.  I usually have no problems with Oculus apps and play Robo Recall fine through both Revive and Remixed.

**Comment by MaxCancer** [comment]
can u post me the Remixed dowload link plz?

**Comment by FrameSkip** [comment]
@Max Remixed is included with the release branch of Revive 1.4.2

**Comment by FrameSkip** [comment]
I could get it to launch using Revive through SteamVR but it wasn't playable due to stuttering with a WMR headset.

**Comment by SilentMosquito** [comment]
@FrameSkip I'm using a lenovo explorer as well and am experiencing the same stutter issue. @Armada651 is there a fix for this?

**Comment by FrameSkip** [comment]
@Armada651 Thanks for doing all of this, it's amazing how well everything runs at all.  I will say MPU stutters through Revive (Using it through Steam VR) and completely doesn't launch in Remixed.  I'm not sure if that was clear or not (or if it matters).

Thanks again for your hard work!

**Comment by alex121201** [comment]
I got marvel to work with 1.4.2 but when trying to play it says to hit the Y button and I tried but none of the vive buttons worked plz help

**Comment by alex121201** [comment]
never mind I got it to work

**Comment by M0rdresh** [comment]
Same issue as I described earlier @alex121201 
From time to time the Y will not work, but at the same time match-making will "hang", so I think it has more to do with the latter than a straight controller / input.

**Comment by nugg** [comment]
Hi everyone, I just recently downloaded revive and Marvel Powers United and I have a vive, and I got past the prologue but when I try to do matchmaking it won’t work I just press start matchmaking and nothing happens. Please help if someone knows a fix.

**Comment by mohamedaix2** [comment]
bonjours qu'elle qu'n pourrais m'envoyer le jeux  que je puisse l'essayer il est introuvable avec un grand merci d'avance
pour me contacté envoiler moi a mohamed.ouchnak@outlook.fr merci
