### ISSUE TITLE
1.4.2 problem

### ISSUE THREAD

**Issue by Spiderianmonkey** [LibreVR/Revive#1040]
So i need the new version of Revive to launch Marvel powers united but revive wont show my oculus games. When i try to launch them from oculus home they wont launch because of a "pending hardware issue"

**Comment by Armada651** [comment]
You're not supposed to launch it from Oculus Home, instead you need to launch it from the Revive tab on your VR Dashboard.

If you've installed Marvel United in another Oculus Library (i.e. not on your C drive) then you need to make sure you've selected that library as your default library in the Oculus Home settings.

**Comment by Spiderianmonkey** [comment]
Thank you so much! :D

**Comment by Armada651** [comment]
Was it the default library setting?
