### ISSUE TITLE
Can't calibrate in Marvel Powers United VR

### ISSUE THREAD

**Issue by 5manrocks1** [LibreVR/Revive#1042]
I can get the game working just fine, my controllers are tracked, the only issue is that I guess the game doesn't detect any button presses. I opened Touch Basics to see if it was with all Oculus games (because I had just installed both Oculus and ReVive specifically for this game, but every button worked perfectly in it.

**Comment by Armada651** [comment]
There seems to be some kind of controller detection problem in Marvel United, try turning off and turning back on one of the controllers.

**Comment by 5manrocks1** [comment]
I tried that to see if switching the right-hand controller to being the left-hand controller would work and still nothing. Just tried again, calibration wouldn't do anything, turned off the controller and turned it back on, and still nothing. Someone in a reddit thread recommended uninstalling Revive and reinstalling it, but that didn't help my case either.

**Comment by 5manrocks1** [comment]
Still no dice with the beta. Yes, it's an HTC Vive & controllers. Is there any 3rd party software I should have installed that might help? Not sure if this is at all important, but when I first opened the game and found this issue, I uninstalled both Revive and Openvr, and now I've reinstalled Revive twice but not Openvr.

**Comment by Armada651** [comment]
You mean OpenVR-AdvancedSettings, you don't need it. Are both your base stations detected?

**Comment by 5manrocks1** [comment]
[Yes, they are.](https://imgur.com/a/gOQlez6)

**Comment by Armada651** [comment]
I assume you've also tried it without the SteamVR beta?

**Comment by 5manrocks1** [comment]
Correct, every attempt to get it working until you suggested the beta were without it.

**Comment by Armada651** [comment]
I need to gather more information, so unfortunately you'll have to wait until more reports come in and I have time to look deeper into the issue.

**Comment by M0rdresh** [comment]
I have not run into any issues during calibration. The issue I experienced twice is during match-making where, 1. the A button didn't seem to register to cancel the match-making 2. I could not do a hold Y button to override match-making and to play solo. Restarting the game solves it every time.

In both cases I tried turning off the controller, and back on again. Did not change anything. The two base stations were on track, the controller movement was smooth. When you go to options in this game, your character hands are changed to the oculus controller and strangely while Y and A was not working for match-making input I did see my button presses showing up on the controller rendered in-game.

I have no other occasion in the game where I lost control of a button, once passed match-making all works fine. Only thing I see, which I find weird, is that during some brief loading times of the game (and thus when you are kicked back to the generic SteamVR space briefly, the game's logo flashes on and off, while all other games the logo is persistent.

![heu5asgic0du](https://user-images.githubusercontent.com/40898440/43365970-6b4e6ef2-9335-11e8-843c-334f97239353.jpg)

![jz5mi6lhvmuj](https://user-images.githubusercontent.com/40898440/43365971-6d71d1a6-9335-11e8-956e-425e404c6f11.jpg)

**Comment by Val-Pal** [comment]
Can confirm the above with M0rdesh. I never had issues holding Y to stop matchmaking, but I did have problems hitting A to invite the player. It just never seemed to register on that menu, though it seemed to be working everywhere else. I ended up having to get a friend to do it and invite me---which required me to take the headset off and accept the invite from the Oculus app on the PC.

**Comment by M0rdresh** [comment]
I read a conversation on the Oculus forum by Rift users they had issues with friend select in match-making, one found that using Rift Core 2.0 beta changed the friend select to working. Some even go so far saying the game is designed to more work with Core 2.0. Not sure if it's all related, just posting the information here.

**Comment by Armada651** [comment]
@Val-Pal Opening the friend list is likely a bit of Oculus Home integration. This will never work with Revive.

**Comment by Val-Pal** [comment]
@Armada651 Thanks! I figured that was the case, but I just wanted to make certain :) I wasn't sure if any other Vive users were having the issue since no one else seemed to mention it, but for all I know they're playing solo or inviting from the client.

**Comment by 5manrocks1** [comment]
Just to throw this in there, the Rift Core 2.0 beta did not fix the issue I was having previously either.

**Comment by M0rdresh** [comment]
You know, each time the button Y (to override match-making and play solo) and button A to cancel match-making does not work, matching-making did not either. What I'm saying is, when people show up in the match-making, I never experienced button Y or A not working. So I'm very sure now after lots of playing sessions, it certainly has to do with match-making and usually at first start of the game. Not sure what, if anything, is happening by Revive during that time.

**Comment by davidbhowmik** [comment]
I have revive 1.4.2 and a Dell Visor WMR headset. I can launch Marvel Powers with and without SteamVR and also with and without beta of SteamVR but what ever I do I get to the game calibration and it asks me to press the left thumb stick to calibrate. When I do this I get taken to the steam interface. How do I get round this and the thumb stick press to register in the game so it calibrates?

thanks for your help

**Comment by davidbhowmik** [comment]
I have now turned of dashboard in steamvr settings so when I press the left thumb stick it no longer calls the steam menu. However now it does nothing at all when i press not even registering a press in game to calibrate

**Comment by davidbhowmik** [comment]
I have revive 1.4.2 and a Dell Visor WMR headset. I can launch Marvel Powers with and without SteamVR and also with and without beta of SteamVR but what ever I do I get to the game calibration and it asks me to press the left thumb stick to calibrate. When I do this I get taken to the steam deshboard. So i turned off dashboard in steamvr settings. But now when i press the left thumb stick to calibtate nothing at all happens. How do I get round this and the thumb stick press to register in the game so it calibrates?

thanks in advance for your help

**Comment by davidbhowmik** [comment]
problem solved, pressing thumb stick is mapped to direction left on the touchpad

**Comment by Dragoboss** [comment]
@5manrocks1 

Please report back shortly, if this still an issue?

**Comment by Dragoboss** [comment]
#1048 
Also, haven't had a response in 11 days.
For now closing this ticket, if you return to this ever and still have this issue please just put in another comment and re-open, 5manrocks1.
