### ISSUE TITLE
Can't launch Marvel Powers United VR - timeout on renderer

### ISSUE THREAD

**Issue by darrenpye** [LibreVR/Revive#1045]
I'm getting a fatal error, Unreal enginge timeout on renderer thread of 30.0 sec or something close to that. The game starts, then stuck at a black screen, then the fatal error

**Comment by Armada651** [comment]
Please update to the latest version: https://github.com/LibreVR/Revive/releases/latest

**Comment by FrameSkip** [comment]
Using a Lenovo Explorer WMR headset I get severe stuttering.  I get about 5% of my frames reprojected according to Advanced VR but it seems very laggy.

This is running through Revive.  I cannot get it to launch at all in Remixed.  I usually have no problems with Oculus apps and play Robo Recall fine through both Revive and Remixed.
