### ISSUE TITLE
toggle/hybrid grip issue

### ISSUE THREAD

**Issue by kyle167** [LibreVR/Revive#1046]
when selecting toggle or hybrid grip, it does nothing. I still have to hold in grip. before it would stay in my hand with one click when I selected toggle/hybrid. now it does nothing

**Comment by Armada651** [comment]
This setting is deprecated in favor of changing your SteamVR input binding in the SteamVR beta. Using the SteamVR beta you can change everything about the controller binding including making the drip a toggle.

**Comment by Ylluan** [comment]
setting up as toggle is easy, but I can not set it as hybrid.
can someone explain to me how to do it?

**Comment by Blitsie** [comment]
Hi Ylluan!

I don't think you can setup hybrid grips in SteamVR Input yet, but what I did was keep the grip buttons to toggle and I made clicking anywhere on the trackpad register as gripping as well, but it registers as a button press for holding and letting go when I stop pressing. After that I just registered the b_button to the menu button of the non-dominant hand controller as none of the other buttons are used from what I've played.

This way I can quickly grab and throw robots and bullets and whatnot while still having the toggle grips for holding weapons without it being murder to my hands.

**Comment by Ylluan** [comment]
It's a good idea ... I'll try it. thank you

**Comment by Armada651** [comment]
Fixed in the latest release: https://github.com/LibreVR/Revive/releases/latest
