### ISSUE TITLE
Marvel Powers United Controllers

### ISSUE THREAD

**Issue by RealityEclipse** [LibreVR/Revive#1048]
Im using a wmr, everything is working fine I was just asking if anybody knew the calibration button for the start of the game?

**Comment by VRGuy17** [comment]
nvm got it now!

**Comment by MaxCancer** [comment]
all work fine? how pass the "hardware issue" in oculus portal? if you don't configure an oculus rift there are a pending hardware issue that not permit to start the game, how you avoid this?

**Comment by FrameSkip** [comment]
Just so everyone knows it's the up button on the left touchpad.  @VRGuy17 how is the performance for you?

**Comment by FrameSkip** [comment]
@Maxcancer you don't launch the game through the Oculus app.  Use Revive through SteamVR.  You do need the Oculus Runtime Service to be running though.

**Comment by MaxCancer** [comment]
@FrameSkip i don't lauch the game from oculus app, i use revive inside SteamVR, but before game start give me a "pending hardware issue" and game close down…. so there are a way to fix this or to avoid this?

**Comment by SamCharette** [comment]
You can restart your PC, or you may have to re-install marvel.  I did both and the error went away, so I'm not sure which it was.

**Comment by VRGuy17** [comment]
@MaxCancer I didn't get it working at first, this game is getting so annoying i am questioning about getting a refund. but if you're having hardware issue problems these are the steps I followed to bypass that: 
1: Make sure you have the latest edition of revive
2: (Don't think this is necessary but I still do) Make sure you're on SteamVR Beta
3:I open SteamVR Home then open it from the dashboard on my desktop. 
4: Make sure all equipment is on (Controllers, sensors etc.)
But when you're finished you will encounter stuttering and most games will end up in "Error ocurred with connecting to oculus platform" or thats just me. If anyone could help me with that, it would be greatly appreciated!

**Comment by MaxCancer** [comment]
@VRGuy17 tnx you so much i try all and the game start….obviously can't do it fine, there are  a problem in game, the game is "flickering" when i move my head, i can see the game's elements, buildings, cars, that tremble….It's quite annoying…..I do not know if I could explain myself well

**Comment by VRGuy17** [comment]
@MaxCancer yeah thats the reason I refunded the game, until that problem gets fixed, i'll stay of it. but you enjoy your time on it.

**Comment by MaxCancer** [comment]
have this flickering in game too? there are no way to fix it in future for you?

**Comment by Armada651** [comment]
@PaulGorokhov That sounds like you've installed Revive in multiple locations on your PC.

**Comment by PaulGorokhov** [comment]
Much appreciated @Armada651 you're a real lifesaver!

**Comment by Dragoboss** [comment]
Seems this issue and sub-issues have been fixed except one, related to flickering.
This is however totally separate from the main issue and would require some more detailed information to diagnose. If you still have flickering issues please post a new ticket within the new format @MaxCancer 
Closing this ticket.
