### ISSUE TITLE
Installation Error and Launcher not working

### ISSUE THREAD

**Issue by holyphyre** [LibreVR/Revive#105]
The app crashed when installing. and Launcher won't turn on. Help?

Launcher app crash:
Problem signature: Problem Event Name: APPCRASH Application Name: ReviveOverlay.exe Application Version: 0.0.0.0 Application Timestamp: 573ca6bd Fault Module Name: ReviveOverlay.exe Fault Module Version: 0.0.0.0 Fault Module Timestamp: 573ca6bd Exception Code: c0000005 Exception Offset: 0000000000003b2a OS Version: 6.1.7601.2.1.0.256.48 Locale ID: 1033 Additional Information 1: 28f7 Additional Information 2: 28f7588e8161581e2b7636aa4cdbf4ef Additional Information 3: a775 Additional Information 4: a7753fe3dd22641798a1e241143b9a6b
EDIT:
Also, during installation there is an error:
OVR Service Launcher: [LauncherService] Cannot start installed service: StarService failed. LastError = 0x422 (1058): The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

**Comment by kschima** [comment]
When installing Revive 0.5.2 over 0.5, ReviveOverlay.exe crashed for me, too.
I tried to reproduce that: Deinstall Revive entirely, install Revive 0.5, start a game with it, install Revive 0.5.2 over this and it worked with no problems.

Try de- and reinstalling Revive 0.5.2 may work for you.

**Comment by holyphyre** [comment]
So i followed your instruction and installed the 0.5 Revive first, and tried to open it, but it gave me the same error:

**Comment by holyphyre** [comment]
I was able to get Lucky's tale to open with the Revive injector. However, it said that the Game Failed from the Entitlement check once it loaded while in VR. So sounds like the DRM bypass didn't work. I am still on version 1.3.2 and confirmed both in the properties of the files and the oculus home. What am I missing?

**Comment by holyphyre** [comment]
Ok, i got it all to work except for the Lucky's Tale. Dreamdeck and Farlands work, but now my Lucky's Tale continues to say that Game Failed on Entitlement Check. I will try to reinstall Lucky's stale.

**Comment by vraddict** [comment]
http://www47.zippyshare.com/v/ZedJBOF1/file.html   
Try this it works !!!

**Comment by LibreVR** [comment]
Lucky's Tale is not yet supported, we're working hard on that one and it should be supported again soon.

**Comment by holyphyre** [comment]
Ok, so this ended up being a misunderstanding on my part. I thought i had to open the Revive Dashboard as if it was a desktop portal like Oculus Home. I didn't realize that it was a seperate tab within vive's VR steam dashboard. Once i went there and tried opening games, i was successful.
