### ISSUE TITLE
Controller manifest paths not properly interpreting UTF-8 paths

### ISSUE THREAD

**Issue by liamsk8rdood** [LibreVR/Revive#1050]
I have both OpenVR and Revive installed with my SteamVR and I am able to run Oculus titles. the controllers are tracking; however, the buttons seem to have no effect on the game. i can still use the menu button to exit, but no such luck with any other buttons

**Comment by liamsk8rdood** [comment]
I have tried uninstalling and reinstalling both revive and openvr advanced settings it did nothing

**Comment by mirage335** [comment]
Same problem here. Using Oculus, and real Oculus Touch Controllers, attempting to run DCS World through Revive to allow use of OVRDrop.

Seems this might have to do with the controller binding. Many of the menus are broken unless an XBox controller is attached. Even then, menu (available through VR) to actually configure controller bindings freezes unrecoverably, to the point a system reboot may not fix it.

**Comment by liamsk8rdood** [comment]
i tried messing around with the bindings, but it was extremely broken. i am using vive controllers and a htc vice headset

**Comment by hybrid11** [comment]
After testing around installing all previous versions of Revive gives me your result, controllers tracked but no buttons work.  However, 1.4.2 newest version works but there is no haptic feed back vibration on the controllers or they are broken.

**Comment by Armada651** [comment]
If your controls are broken, try going back from the SteamVR beta to the SteamVR stable.

**Comment by IceManRyder** [comment]
Same Problem with me. Tryed to downgrade to the last 3 versions but it seems the problem lies with oculus update.

**Comment by liamsk8rdood** [comment]
I have tried both SteamVr Beta and regular steam vr, no luck.

**Comment by Ylluan** [comment]
I have the same problem. both with SteamVr beta and Steamvr regular ... I tried many previous versions of the revive, but nothing: the buttons do not work.

**Comment by hybrid11** [comment]
I'll roll back to the non-beta later tonight then and see if it helps but it seems some already are reporting it doesn't? It must be something with customization of your controller options in steamVR maybe. I've notice that some of the buttons are off actually.  Press the GRIP on the wand for example used to close the fist in Robo Recall but now it was pointing the finger...I've tried a few games cause I thought it was crazy but somethings off with the controllers. :/

**Comment by liamsk8rdood** [comment]
just updated all firmware, and went back to SteamVR stable. no Change

**Comment by liamsk8rdood** [comment]
i originally downloaded revive to play Marvel powers United Vr. i originally could run the game, but the buttons would work. i just tried switching to an earlier version of revive, and it did nothing except prevent me from opening the game. i then switched back to 1.4.2. but it still says " there is a fatal hardware issue preventing you from opening this game."

**Comment by hybrid11** [comment]
It's hilarious! the opposite controller vibrates in some games that's supposed to. Fire the gun in the left hand and the right hand vibrates. lol sometimes buttons just don't work and I have to restart.  Getting off beta did not help.

**Comment by liamsk8rdood** [comment]
i am able to open other games besides marvel powers united vr, bit i can still not use the buttons at all

**Comment by Armada651** [comment]
It seems that Valve made SteamVR Input part of the stable, I wasn't ready for that yet. I'll release a new version soon that fixes these SteamVR Input issues.

For now you can switch to the 6/21/2018 hotfix beta in SteamVR as a temporary solution.

**Comment by hybrid11** [comment]
Thank you Armada651

**Comment by Ylluan** [comment]
Thank you Armada651.  now all is ok

**Comment by hybrid11** [comment]
Any ETA on fix :(

**Comment by hybrid11** [comment]
'For now you can switch to the 6/21/2018 hotfix beta in SteamVR as a temporary solution."

This doesn't work to fix haptics and rumble on the wands. None of the steam versions do.  The guns don't vibrate the controllers in the games.

**Comment by DriedUpTurd** [comment]
So when is the update to fix the problem? Or do we have to stick with the old steam update for a long while?

**Comment by MacbethAUT** [comment]
I have the same problem. switching to the hotfix didn't help so far. :-/

**Comment by JoePinapples** [comment]
Hello, I have a wmr hmd and I can inject third party oculus games via revive, however although the games will load  my controller inputs do not seem to be registering. can you advise at all? The headset is not a problem its being tracked, and so are the movement of the controllers. However any button presses on the controllers are not registering. I
 thought maybe there was a way to map the oculus controllers to the wmr ones but for the life of me i cant figure out what to do. unknown sourced oculus games will load when injected through revive, however i get to the main menu and then i cannot select start or a new game or anything as the button presses are not registering. I can point with the wmr controllers and i can see my hand movements being tracked but no joy when depressing a button....so frustrating! Can anyone shed some light please?

**Comment by Dragoboss** [comment]
@JoePinapples You shouldn't inject into games that you have on the Oculus store, and thus can launch through the Revive Dashboard (with or without SteamVR running).

If this is about any game that is NOT on the Oculus store and therefore can only be used when injecting,please post a completely separate ticket about it and add details in the format.

@MacbethAUT Sorry for the late response, try the latest SteamVR version and Revive 1.6.2, and report back with a new ticket if you still have issues.
If it works with 1.4.2 you can stick with that for now but I'd still appreciate a detailed ticket so we can diagnose what the difference is that causes it not to work on later versions.

@hybrid11 That is an entirely separate issue.
Separate issues belong in separate threads....


I am closing this ticket as the main issue was solved, should be working.
Side-issues, mostly fixed, aside from one or two, but completely unrelated.

**Comment by sopulimees** [comment]
@Dragoboss i have tried with steamVR and steamVR beta, i have tried REvive 1.7, 1.6, 1.5.
Controller tracking works just fine, but buttons wont work on any oculus game (3 test games and vader).
i just cant find a way to get the buttons to work...

**Comment by MacbethAUT** [comment]
@Sopulimees so you have any character like ö ü ß or such in your windows user name by any chance?

**Comment by JoePinapples** [comment]
Yes I do.

That has been an issue on a couple of games

**Comment by sopulimees** [comment]
@MacbethAUT yes i actually do.
Now i changed it and well, tried to change the path to c:/users/XXX and it managed to F up my user settings. So now, installing oculus and other stuff again.
Will report if this helps

**Comment by liamsk8rdood** [comment]
I started this thread almost a year ago and I can’t believe I forgot to update it once I had found a fixed. I realized that somehow I was missing a specific set of files in my revive folder that connected to controller usage. If anyone is still having this problem, I would recommend going through all of your files and confirming everything is in the right location and that revive succesly download completely. I believe all I needed to do was install that separate driver and add it to the folder, and it worked perfectly from then on.

**Comment by sopulimees** [comment]
@MacbethAUT **solved**
Creating new user without SPECIAL letters fixed it for me.

DO NOT try to change your current username, this just didnt work and i managed to make a mess on my user account. Create a new one and copy old stuff from C:\user\Xx to it.

**Comment by MacbethAUT** [comment]
That's what I thought. If I switch user it works perfectly.

**Comment by Armada651** [comment]
Should be fixed in the latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.2
