### ISSUE TITLE
ReMix Unplayable

### ISSUE THREAD

**Issue by MrNobodyX3** [LibreVR/Revive#1053]
I tried to use revive, Remix dashboard however my controls seem to do nothing, medium straight up crashes.

gtx 1070ti
intell i7 4770k
32gb ram
HMD Odyssey

**Comment by Dragoboss** [comment]
Alright, well, for controls I am not sure.
As for Medium, it's built using UE4. With Remixed that causes WMR to think a frame was skipped, which is something the software doesn't know how to deal with, therefore insta crashes.

A fix is underway but it might take a bit longer.

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
