### ISSUE TITLE
Xbox one controller not responsive in Chronos

### ISSUE THREAD

**Issue by arkage** [LibreVR/Revive#106]
So I'm using the newest versions of Revive, and trying to use a wired Xbox One controller for the games.  I can load up Dreamdeck just fine, and the buttons work (A & B buttons) for selecting a video or going back.  However this doesn't work for Chronos.  It starts up the intro videos fine, and I skip them by pushing A if I want, and also recenter the screen hitting the menu button.  After the intro videos it goes to the default Vive screen for a second, and then loads Chronos.  All it says is "Chronos" with the grey floating stuff around you, but without any start menu.  I can recenter the title screen but none of the other buttons do anything.  Any help is appreciated!

**Comment by Pluckerpluck** [comment]
I don't think this is an Xbox One controller issue, but a Chronos loading issue. Normally a menu appears instantly without pressing anything.

This is also exactly where the entitlement check occurs.

**Comment by avivgo** [comment]
i have the exact same issue. game works, no entitlement check error, but no menu. its running and all, music, grey flakes spinning round me, chronos logo spins, but no menu...

anyone got a solution for this?

**Comment by arkage** [comment]
It's a DRM issue, so make sure you have the newest versions of Revive and the Oculus Store running.
