### ISSUE TITLE
Hybrid Grip not working

### ISSUE THREAD

**Issue by Blitsie** [LibreVR/Revive#1061]
Hi!

I recently installed the latest version of Revive and the advanced settings to change the grips from normal mode to hybrid.

Unfortunately the changes never apply? I tested them in both Robo Recall and that Oculus controller testing app and the grips still function like in normal mode. I have restarted my computer and also reinstalled Revive and its still the same issue.

Would anyone kindly be able to help?

Thank you!

EDIT: So I've figured out how to change the grips to toggle in SteamVR Input, but its not exactly ideal for Robo Recall especially. Is there a way I can create a hybrid controller scheme through SteamVR Input?

**Comment by wo0ben** [comment]
Sorry I know this is irrelevant, but has "Bullet Train" worked for you using Revive, sorry im asking you this, but no one else knows a fix.

**Comment by Blitsie** [comment]
Hey wo0ben

No worries at all! I haven't tried Bullet Train yet so I can't say for sure, sorry about that :/ I can give it a go tomorrow and give you some feedback?

I know this goes against what you probably heard, but maybe download the 1.3.0 release of Revive and see if it works on that version? That's what I'm currently doing while I'm going through Robo Recall, since they dropped their input scripting for Steam's beta one and I really like the hybrid grips in the older version.

I hope you get it working!

**Comment by Armada651** [comment]
> So I've figured out how to change the grips to toggle in SteamVR Input, but its not exactly ideal for Robo Recall especially. Is there a way I can create a hybrid controller scheme through SteamVR Input?

I was hoping Valve would add a hybrid toggle before moving SteamVR Input to the stable branch. Unfortunately it seems that's not the case. I'll see if I can implement a simple fall-back while we wait for hybrid toggle to be added.

Though I'd like to eventually phase out all OpenVR-AdvancedSettings settings in favor of SteamVR Input as most of the settings for Revive are input-related and SteamVR Input provides a much richer interface for that.

**Comment by Blitsie** [comment]
Thank you so much Armada! I appreciate the response and look into the hybrid grips.

Hope the weekend has been good!

Will close this one as its sorted from my side and I'm enjoying Robo Recall tons :)
