### ISSUE TITLE
-nodashboard parameter for REVIVE

### ISSUE THREAD

**Issue by levantail** [LibreVR/Revive#1063]
Hello there,

Is this possible to run certain revive games without steam dashboard (e.g. showdown or intro to virtual reality)? Like they were running as usual steamVR with "set launch options.." parameters in it. 
If not, is there any way to do this manualy using cmd or powerShell to start revive games using               -nodashboard parameter ?

**Comment by Armada651** [comment]
What are you trying to do that requires this? All the games in the
dashboard are already listed in your Steam Library, so if you need to start
a game from the desktop you can do it there.

**Comment by Armada651** [comment]
In SteamVR there's an option in the Developer tab to disable the dashboard
entirely, I suggest you use that.

**Comment by levantail** [comment]
Unfortunately its not that function that i looking at. To be honestly i find out how to run game using REVIVE vie PowerShell, and in this way dashboard doesn't appear. But i want to know, is there additional launch parameters (i'am talking about reviveInjector)?
