### ISSUE TITLE
Xbox One controller inputs not registering

### ISSUE THREAD

**Issue by CinnaB** [LibreVR/Revive#1064]
No Oculus games through Revive are detecting xbox controller inputs on my PC. Steam games work fine with controllers, as well as native Vive games, but Oculus games act as if one isn't even connected. Oculus games work with my Vive controllers fine.

**Comment by Krylke** [comment]
Just tried KIN and I can confirm that xbox controller does not work. Steam games works fine

**Comment by RogerWoodman** [comment]
I have the same issue with Lucky's Tale.  I am using the Oculus Go with ALVR and Revive.  I can get a great picture (although trying to stream audio crashes ALVR), but none of the controllers I have used, including the Xbox One controller, works.  All the controllers I have used work with Steam.

**Comment by gaelios123** [comment]
Same issue here (for oculus go and ALVR) with lucky tale my controller doesnt work, i press A button to start but the controller not respond

**Comment by Armada651** [comment]
Fixed in commit 958cf101ad5bf69d2cc6b98978647738ee317d9c, will be part of the next release.

**Comment by Kiefy** [comment]
Gamepad in KIN still isn't working in 1.6.2.  But works fine in Chronos & Lucky's Tale.

The Vive as Touch as Gamepad thing works. but is very awkward.

One thing that is strange, is when all controllers are inactive, the game doesn't present the "No Controller" error as it should.  Having any of the gamepad/controllers active/inactive has no effect.
