### ISSUE TITLE
Just non-stop reprojection

### ISSUE THREAD

**Issue by hybrid11** [LibreVR/Revive#1079]
Anyone else have the Vive Wireless Adapter.  All Revive games just sit at no matter the super sampling setting or graphics settings losing constant frames.  Won't hold the same settings it used to what so ever. Just constant reprojection.

Vive Pro/Wireless adapter
i7 7700k 1080 ti

**Comment by flynn2k** [comment]
My Revive update to the latest version on Saturday and when I run my Vive Wireless and Revive, it just crashes constantly when playing any game and is only stable after I Quit out of Revive.

**Comment by lv426hudson** [comment]
Same here, tried Lucky's tale the other day (wireless) and it was constantly re-projecting where as when i played it wired (about a year ago) it was fine. Didn't spend much time looking into it but it looked like the CPU was being late all the time even though utilization was low.

Vive Pro/Wireless adaptor 
I7 7700k, strix z270, Titan XP, 32GB ddr4 @ 3200mhz

**Comment by hybrid11** [comment]
Turning off all Async options in beta branch with shift+A got rid of constant repro but there is something wrong with the way the adapter utilizes the CPU. Spiking it all the time.

**Comment by lv426hudson** [comment]
I have returned my wirrless. Just wasnt happy with all the bugs nd noticable degregation of image quality, revive now works fine again tethered.

**Comment by hybrid11** [comment]
I didn't notice any image quality reduction but performance is awful.

**Comment by flynn2k** [comment]
I have stuck with the wireless. I am getting slight image reduction at
times but with the updates to Revive, my issues with reprojection have went
pretty much away. From what I have read and experienced, the CPU overhead
required for wireless is the problem with the image reduction. I am on a
3rd generation i7 so it might be the bottleneck. After a month, I am happy
with the wireless aspect and with the software updates, the image quality
is getting better. The only remaining issue is the excessive heat with the
wireless adapter. It had burnt a couple of people and so I am DYI'ing a
heat barrier for it. This seems to be only an issue with the OG Vive and
not the Pro.

**Comment by Armada651** [comment]
Fixed in 93f1092d92a4f73377f850ff13b1237861f3fd61, will be part of the next release.
