### ISSUE TITLE
"Game Failed Entitlement Check" for Lucky's Tale

### ISSUE THREAD

**Issue by holyphyre** [LibreVR/Revive#108]
So i got dreamdeck and farlands to work. However, when i try to play Lucky's tale, i get the message "Game Failed Entitlement Check". 

As per the following [reddit thread](https://www.reddit.com/r/Vive/comments/4en28m/luckys_tale_patch_on_vive_failed_entitlement_check/), I have enabled unknown sources in the oculus settings, rebooting services and pc. I have even toyed with my symlink by pasting the game files back into the Program Files (x86) folder to no avail. Do any of you have any thoughts on how to get this to work?

**Comment by dafaithz** [comment]
Hey there, "Luckys Tale" is a Unity game afaik, so you cannot run it with the newest oculus runtime and the newest revive hack.
only unreal engine games works at the moment with the 1.4 runtime active.
Your only option is to downgrade to 1.3 again, then it will work without any problems.
For detailed instructions: https://www.reddit.com/r/Vive/comments/4kd08m/revive_compatible_oculus_runtime_132_is_still_on/

\Cheers

**Comment by vraddict** [comment]
You can also use this :  http://www47.zippyshare.com/v/ZedJBOF1/file.html

**Comment by holyphyre** [comment]
Ahhhh, that would explain things. I thought i saw people saying they got it to work with the new 0.5.2 Revive.

**Comment by holyphyre** [comment]
What is odd is that even with my oculus services (inbound and outbound) completely blocked, my oculus home continues to upgrade itself back to 1.4.

**Comment by Rojoyinc** [comment]
I downgraded too - 1.3.0  entitlement check still there.  I set my firewall to not update oculus stuff.
everything else works but lucky's.   Also anyone having any luck with  STEAM offerings for oculus?

SNOW?
SUBNAUTICA (it did now doesn't)

**Comment by LibreVR** [comment]
Downgrading sometimes works, but it's not a technique I actively support. I'm currently working on fully bypassing the DRM in the next release.

I will also include an improved version of the Project Cars patch you can use for Steam games.

**Comment by LibreVR** [comment]
Fixed in the latest commit, will be part of 0.6.
