### ISSUE TITLE
Knuckles support

### ISSUE THREAD

**Issue by malignfunction** [LibreVR/Revive#1080]
Is there a beta with knuckles support? I tried with ev3 earlier, and the release from July, but it wants me to set up my own mapping in steam.

**Comment by malignfunction** [comment]
Thanks. It mostly works. Having issues getting the joysticks to map to well, joysticks, but I'm guessing that's my issue.

**Comment by Armada651** [comment]
Should work as long as you don't bind the "recenter" action which you don't need.

**Comment by Armada651** [comment]
@vblanco20-1 Latest version has full Knuckles support.
