### ISSUE TITLE
TribeXR DJ gets Fatal Error during gameplay (randomly)

### ISSUE THREAD

**Issue by cappaholic** [LibreVR/Revive#1085]
Windows Mixed Reality
Steam VR (tried standard and beta builds)
ReVive 1.5.0

Some times it's within a few minutes, sometimes it's a half hour into the game. 
Fatal Error dialogue box pops-up.
Almost looks like an UnrealEngine error box?

**Comment by cappaholic** [comment]
Well, the game hasn't crashed since updating to 1.5.1
Hopefully that fixed it... or I've just been lucky.
I'll post if it happens again.

**Comment by cappaholic** [comment]
Well, it’s doing it again.
Sometimes within minutes. Other times, it doesn’t do it at all for a 45 minute session.

**Comment by Dragoboss** [comment]
Continuation #1095
