### ISSUE TITLE
Dirt Rally not working

### ISSUE THREAD

**Issue by bobeomenyeo** [LibreVR/Revive#1088]
Hi everyone!

So I played Dirt Rally for a long time about an year ago, with ReVive, and it was all good. Game launched into "the sphere", I could navigate the menu, and play.

One time it just stopped working, and I stopped playing the game. Got a new PC now, and reinstalled Dirt Rally, followed the latest ReVive instructions (Oculus Home, ReVive, Direct-X, untick home theatre, oculus enabled="true") but it's not working! The game just starts on the desktop, and even if I start a rally stage from there, it won't load in the Vive. I tried the latest ReVive; version 1.4.2; and version 1.1.2. All the same.

Am I missing something? Any help would be greatly appreciated. It drives me nuts that it used to work so good, and now I've literally spent a hundred hours to make it work, to no success.

**Comment by KenshiHH** [comment]
"Am I missing something? " looking before posting a problem which already exists :P

https://github.com/LibreVR/Revive/issues/1086

**Comment by bobeomenyeo** [comment]
Turns out I was retarded after all, I forgot I put my Steam folder to a different place than I always did on drive E, and had my old Steam folder there. I was patching the wrong folder.

After patching the correct exe, it worked the first time.
