### ISSUE TITLE
Echo VR not loading in HMD

### ISSUE THREAD

**Issue by booty156** [LibreVR/Revive#1089]
Hi all, has anyone got revive to work with Lone Echo, Echo arena etc? All mine shows is steamVR in the HMD waiting and echo running on the desktop. Tracking seems to be working on the desktop is well.

Ok, I have an Rift, but using revive to change button mapping for the game

https://cdn.discordapp.com/attachments/313285397801205761/505120967660535828/unknown.png

**Comment by kodxana** [comment]
For me is working perfectly Echo VR. Just use direct link option 😌

**Comment by booty156** [comment]
What is the direct link option?

**Comment by Dragoboss** [comment]
Sometimes it can take a while to load a game into the headset. I have had that on my set(s) in the past.
I am not sure what she meant by direct link but the steamvr bindings system can also be accessed from browser whilst steamvr is running at http://127.0.0.1:8998/dashboard/controllerbinding.html

With that said, this is not a supported headset nor intended feature and I know for a fact that using Revive with a Rift can work. (I have seen it on another echo user).

So with that said I am closing this ticket.
