### ISSUE TITLE
Having some Problems here

### ISSUE THREAD

**Issue by ZuckerSchock** [LibreVR/Revive#109]
I tried to use ReVive on Monstrum (the Steam version) i found a way that works for other people that want to play the Game using ReVive but for me it seems that ReVive isnt working.

The way to start Monstrum that seems to work is create a shortcut of the Injector and add the Target of the Monstrum.exe and -oculus so that the game is startet in oculus mode.

If i use the Injector a cmd field pops up and disappears instantly, the only text it shows is : "Failed to create process" So i downloaded a Oculus Home game for free to test it (Woofbert), it shows in the SteamVr Dashboard on the ReVive tab but as soon as i try to start it, windows tells me that the application has stopped working.
Can someone help me with this ?

**Comment by LibreVR** [comment]
We're still working on making all game compatible again. For Steam games we don't have a very reliable patch yet, though you can try to extract the old [Project Cars](https://github.com/LibreVR/Revive/releases/download/0.5.2/RevivePCars.zip) patch next to the executable.

**Comment by ZuckerSchock** [comment]
Thank you for the fast reply.
The patch made no difference.
The strange thing is i know that other people can play the Game with the Method i stated but i cant, so it should be a Problem on my side.

**Comment by ZuckerSchock** [comment]
Okay, i somehow managed to do it, i restartet my pc, installed a old Oculus Runtime, reinstalled the patch, switched from SteamVR Beta to Steam Vr and some other stuff, something shouls have worked :)
