### ISSUE TITLE
drop dead no controller tracking

### ISSUE THREAD

**Issue by Ylluan** [LibreVR/Revive#1091]
I have revive 1.51and last version of steamVr (no beta).  In Drop Dead the controller not tracking, only buttons work properly and i aim using a blanck dot in center of screen.  It seems to be detected the controllers as a normal pad.   I use Htc Vive, other games like Arktika and Robo Recall works all ok.
i try old versions of Revive, and controller tracking is ok, but all buttons not work.

After many try... with Revive 1.3 and SteamVr beta hot fix 06/21/2018, all working ok.

**Comment by Ylluan** [comment]
Steam no longer supports the Hot fix 06/21/2018, so the problem with Drop Dead reappears again... no controller tracking.  All other games are ok ( also haptics is ok).  I use SteamVR 1.1.3 and Revive 1.6.0.3.
Someone knows a method to solve this problem??

**Comment by Ylluan** [comment]
Description of the issue
No controllerer tracking in Drop Dead, only buttons work properly.  Other games work fine.
### Technical Information
  - CPU: i7 6700K 4ghz
  - GPU: geforce gtx 1080
  - RAM: 16gb
  - OS: windows 10
  - Vive
#### Versions and features
  - Revive v. 1.61
  - SteamVR version 1.2.1
  - Revive installation version: 1.61
#### What is the last working version before this issue first came up?
  - Revive installation: 1.3
  - SteamVR (unless remixed): SteamVr beta hot fix 06/21/2018
### What apps/games are you trying to run?
  - Roborecall, Edge of Nowhere, Arktica1and Luky's Tale works ok.  Only Drop Dead has problem.
## How to reproduce your issue?
just start the game

**Comment by Ylluan** [comment]
sorry. I closed the issue by mistake

**Comment by Dragoboss** [comment]
Hmmm.
So let me get this straight:
Anything above Revive 1.3 your controllers stop tracking but buttons still work.
With later versions if you copy the .dll tracking works but buttons STOP working.

Very interesting.
Please stand by I'll see what I can find out.

From what I hear, SteamVR 06/21/2018 was still before the SteamVR Binding system change... That could affect the buttons but shouldn't affect tracking.......
I'll respond within a few days with whatever I found.

**Comment by Rabbitbeam** [comment]
Hi, was this issue fixed?
I try to play drop dead today and get the same issue...

**Comment by Ylluan** [comment]
The problem has not yet been solved.  I tried today, and the problem is still present.

**Comment by Rabbitbeam** [comment]
> The problem has not yet been solved. I tried today, and the problem is still present.

Looks like the creator forgot to fix this...

**Comment by Rabbitbeam** [comment]
Sould I open another issue or keep it here?

**Comment by Ylluan** [comment]
I don't know how up this issue, there are so many problems to solve besides this. you need to be patient.

**Comment by Ylluan** [comment]
Ok, with the last beta Steam 1.4.15 and the last update of Drop Dead, all work ok.
Rabbitbeam, try it.  If you don't have problems either, close this issue
