### ISSUE TITLE
Razer Hydra buttons not working after Revive updates with steamVR input [SOLVED]

### ISSUE THREAD

**Issue by 3DCont** [LibreVR/Revive#1092]
The buttons can't be remapped  even using the new SteamVR driver for Razer Hydra beta with support for the new steamVR input. The controls in the steamVR page just disappears when trying to assign a button.

The generated .json file:

{
   "app_key" : "revive.app.epic-games-bullet-train-gdc",
   "bindings" : {
      "/actions/touch" : {
         "sources" : [
            {
               "inputs" : {},
               "mode" : "none",
               "path" : "/user/hand/left/input/trigger"
            }
         ]
      }
   },
   "controller_type" : "razer_hydra",
   "description" : "",
   "name" : "My Bullet Train configuration for razer_hydra"
}

**Comment by 3DCont** [comment]
Solution:

Revive 1.5.1
SteamVR 1539100633  Oct 9 2018
SteamVR Driver for Razer Hydra [beta]


Go to "C:\Users\####\AppData\Roaming\Revive\Input\"
edit "action_manifest.json" and add into "default_bindings": 
   {
      "controller_type": "razer_hydra",
      "binding_url": "razer_hydra_default.json"
   },

Duplicate "vive_controller_default.json" and rename to: "razer_hydra_default.json"
Change those lines at the end of the code:
   "controller_type" : "razer_hydra",
   "description" : "",
   "name" : "Revive for Razer Hydra"
(It's not necessary but if you want a default binding, you should also replace the now invalid vive default controls with valid Razer Hydra ones (check in "...steamapps\common\SteamVR Driver for Razer Hydra\hydra\resources\input\").)

You can now create Hydra bindings profiles for every Oculus game added by Revive.


My suggestions:

Left Controller:

Grip -- button_lhandtrigger (Toggle Button)
Joystick 
     Click -- touch_lthumb
     Position -- lthumbstick
Button 4 -- touch_y 
Button 2 -- touch_x
Trigger -- lindextrigger (Use as Trigger)


Right Controller:

Grip -- button_rhandtrigger (Toggle Button)
Joystick 
     Click -- touch_rthumb
     Position -- rthumbstick
Button 3 -- touch_b 
Button 1 -- touch_a
Trigger -- rindextrigger (Use as Trigger)

**Comment by Dragoboss** [comment]
User solved his problem, closing.
