### ISSUE TITLE
Oculus Avatar editor icon gone in revive dashboard

### ISSUE THREAD

**Issue by markbradley1982** [LibreVR/Revive#1097]
The Oculus Avatar editor icon is gone in the revive dashboard but the name of the app is still there. If you try to run it, nothing happens aside from steamvr making a sound. What happened to it? If it's a redundant or Oculus Home only app can it be removed? I remember that revive dashboard in steamvr would only have functioning apps in the past, and now there's this non functioning app that is a bit of an annoyance.

**Comment by Armada651** [comment]
Fixed in 9c398f23a0b3681b15e733ae1c6d0f70669bc965.

It's indeed an Oculus Home app only now.
