### ISSUE TITLE
Everything worked perfectly 2-3 hours, now getting lag and can't get rid of it

### ISSUE THREAD

**Issue by Apbror** [LibreVR/Revive#1099]
I have an asus WMR headset and installed oculus to try out some games. Installed everything and downloaded Lone Echo 2 trailer and ran it through steam/revive tab, which worked perfectly, smooth as butter, pleasantly surprised. Then I closed everything down and tried again the next day, now the LE2 trailer and all other oculus games run through stean (arktika, lone echo, robo recall) have a half a second lag that makes fast games impossible and gives me slight nausea.

- Everything is latest version (steam, revive, drivers). Tried four different nvidia drivers from latest down to 353.30
- Installed Advanced Settings, tried every combination of settings I could (reprojection, supersampling etc)
- SteamVR games work as they should
- Robo Recall works perfectly if I run Revive without steam (but I can't get anything else to work that way + I really want grip toggle...)

Even on lowest everything, the same lag, doesn't seem to be a performance issue(?). Nothing works and it's very frustrating to know that it worked yesterday. How do I "debug" this? I don't know where to start. Any ideas appreciated. Thanks.

-Windows 10
-Asus WMR
-gtx1070ti

edit: not talking about stutter or judder, just at constant, smooth lag

**Comment by Armada651** [comment]
Revive is not designed to be run through the WMR SteamVR driver, that's going through multiple compatibility layers which makes performance/timing issues *very* complex.

Try running the Revive Dashboard from the Start Menu without having SteamVR running. That way Remixed will be used which is a native WMR implementation of Revive

**Comment by Apbror** [comment]
I would, but Robo Recall is the only game that works without steamvr. Arktika1 just closes silently, other games crash back to Revive. Is Arktika1 supposed to work, for example?

**Comment by Dragoboss** [comment]
Remind me on what engine Arktika1 is built?

**Comment by Armada651** [comment]
The lag has been fixed in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
