### ISSUE TITLE
Medium has crashed

### ISSUE THREAD

**Issue by marcoleone** [LibreVR/Revive#1101]
Medium crashes at start up with Fatal Error - Medium has crashed.
I'm running latest Revive release and latest nvidia drivers, Steam NOT beta.

**Comment by negeltu** [comment]
I'm having the same issue on Steam VR Beta and non beta using latest NVidia drivers and Revive.  It has something to do with Steam as it happened after an update.

**Comment by marrable** [comment]
Same here, Steam VR non beta. It either crashes or the controller bindings are all janky.

**Comment by negeltu** [comment]
I found that it works with Steam VR stable if you roll back Steam for Windows Mixed reality to stable instead of beta.

**Comment by milos12345** [comment]
@negeltu I am not on Beta
Library>Tools>Steam VR>Properties>BETAS is already selected to None
Also in SteamVR>Settings>Account>Beta Participation it is "Not Participating"
Also Windows Mixed Reality for SteamVR is not in beta

**Comment by Armada651** [comment]
@milos12345 A white screen means Oculus Medium is loading, have you tried waiting a few minutes?

**Comment by jessebax** [comment]
Is there any plans to fix this? I mainly use revive for oculus medium and I was using it everyday until it stopped working. been unable to work on my projects for the last month :/

**Comment by milos12345** [comment]
I managed to run it by switching from Quadro K5000 to GTX 980ti card. Medium still crashes on exit but at least it run for this small test. It works only when starting from SteamVR. Other few Oculus, SteamVR or WMR games did not have issues with Quadro K5000, the performance was not great but even Fallout4VR is somewhat playable.

**Comment by highjohnconquer** [comment]
> Is there any plans to fix this? I mainly use revive for oculus medium and I was using it everyday until it stopped working. been unable to work on my projects for the last month :/

Yeah, I kinda wish I'd seen this before I bought medium thinking I had checked the compatibility list, lol.

**Comment by ylluminate** [comment]
Getting this problem here too:
![example](https://cl.ly/404cf3ef3461/Image%202019-01-05%20at%207.39.44%20PM.png)

@Armada651 no amount of waiting resolves the issue. Got a rather fast system (i7-3770, 16 GB RAM, RX 580 8GB, drives and Windows 10 up-to-date) with freshly installed Oculus Home.

This comes up for SteamVR 1.1.4:
![steamvr](https://cl.ly/aa840566bab9/Image%202019-01-05%20at%207.43.59%20PM.png)

**Comment by ylluminate** [comment]
I'd be happy to help hunt down the issue if you could let me know what we should be looking for in order to debug this / isolate the issue.  Are there some certain tools we need to enable logging and gather more debug info when digging into this?

**Comment by Armada651** [comment]
@ylluminate You can try it on a different computer. I cannot reproduce this on mine.

**Comment by ylluminate** [comment]
@Armada651 I cannot try this on any other machine given the setup and so forth.  I'm a software developer and would be happy to perform further debugging if you'd simply please direct me what may need to be done as I'm new to the Vive + Oculus.  It seems others are having the same problems so I'd very much like to dig deeper into the issue with your advisement.

**Comment by ylluminate** [comment]
Anyone who's still having this issue running an AMD Radeon RX 580 series card?

**Comment by ylluminate** [comment]
Medium is now working and should be for everyone here who was having trouble before on AMD cards.
