### ISSUE TITLE
Remixed scale way off

### ISSUE THREAD

**Issue by dtdman420** [LibreVR/Revive#1102]
Hi i am using a samsung odyssey wmr hmd and i used remixed to play dead and burried and the scale was waaaaay to big. Switching to revive fixes the problem.

Its not the first time in remixed i noticed the scale of everything was to big, for example my handgun was the size of machine gun

**Comment by Dragoboss** [comment]
#1105 
This is being looked into now.
Please go to the referenced ticket and provide more in-detail steps on how to reproduce this issue, what other games are affected, etc.
Also, another bit of info:      What are your IPD settings on your Odyssey?
Please report it in the other ticket.
