### ISSUE TITLE
Odyssey+ scale issues

### ISSUE THREAD

**Issue by rtamotorsports** [LibreVR/Revive#1105]
I have the Odyssey and now the odyssey+ in titles, especially like dirt rally, the world scale is off and causes a massive headache, the co drivers calls feel like their causing me to go cross eyed. As soon as i switch to the v1 Odyssey, no issues at all. Issues is also replicated on other titles.

**Comment by pinoepel** [comment]
Me too.

**Comment by macfly123** [comment]
You must activate the roomscale in the wmr app in Win10

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
