### ISSUE TITLE
Injecting a  Stand Alone Application on Revive - Files not found

### ISSUE THREAD

**Issue by avalonweb** [LibreVR/Revive#1106]
Hi

I've written software for the Oculus using the Oculus 1.2 SDK and all was well. When I added external files in a folder structure. The app starts ok but when it tries to access a support file required by the app it fails reporting that the files cannot be found.
I'm using Revive to play this application on a Vive. 

eg
MainApp.exe
UI (Folder) cursor.bmp
FBX (Folder) test.fbx

Further note. I can play oculus games through SteamVR with no problem and standalone apps that contain just a single executable and no extra files

Many thanks in advance for your help

**Comment by Armada651** [comment]
Revive will parse the path to the executable to try and determine the appropriate working directory.

It sounds like parsing the path failed. What does thr full path to the executable look like?

**Comment by avalonweb** [comment]
Further info. I have found if I use absolute paths eg "C:/Work/Oculus/Collision Detection" it works.
So it appears that the relative path option is failing.

**Comment by avalonweb** [comment]
I've added a path statement in my code and it reveals that revive runs the app from the  c:\programs\revive folder. The standalone app believes it is in this folder and tries to access non existant subfolders. 
Revive does not make any indirection to the location of these folders so the stand alone app fails.
I have temporarily overcome this by making absolute references in my app to the UI, images etc... folders. If you can confirm this is by design then I can live with it.

regards
Mark

**Comment by Armada651** [comment]
I've weighed the options of fixing this. The only way I see to fix this problem is to enforce that all arguments are properly escaped with quotes, making the injector less robust to input errors.

Thus I'm closing this as won't fix, please only supply full paths to the Revive Injector that's what it's intended to handle.

**Comment by avalonweb** [comment]
Many thanks Jules

I can work with that

regards Mark
