### ISSUE TITLE
Need Assistance - Oculus Store Related Issue

### ISSUE THREAD

**Issue by Zanoh** [LibreVR/Revive#111]
I managed to successfully downgrade the runtime, but my dilemma is this. I need acces to the store in order to redownload my games. Every time I do that though, I run the risk of their server updating to 1.4.

**Comment by kschima** [comment]
Thats not really Revive specific, you can ask such questions in this thread:
https://www.reddit.com/r/Vive/comments/4kd08m/revive_compatible_oculus_runtime_132_is_still_on/

But to answer it: You can just remove the firewall rules, download the games and if Oculus runtime got updated, overwrite the files again. Also: It does take some time until it updates.

Remember: After you got your game files, don't update them, they may not work on Oculus runtime < 1.4
