### ISSUE TITLE
Robo recall focus problem

### ISSUE THREAD

**Issue by adamantiumexo** [LibreVR/Revive#1112]
hi, im having issues with rr, and i can open it, but i need to focus it. once it is focused, my compositor goes red. help!

**Comment by Dragoboss** [comment]
I am going to need some more help here.

Please try to give me a more detailed description, also headset type, and if possible steps to reproduce. as detailed as you can.

**Comment by adamantiumexo** [comment]
Im on vive, and the way to do it is, open it and revive, and focus the compositor, i need to otherwise its red, and the you get focus error

**Comment by Dragoboss** [comment]
Any chance you could get a screenshot of this Phenomenon?
