### ISSUE TITLE
Special characters in username breaks revive....

### ISSUE THREAD

**Issue by MacbethAUT** [LibreVR/Revive#1118]
At least for me. 
With the start of SteamVR input I couldn't get my buttons working anymore, without reverting to a hot fix branch and using revive 1.4.2. Now that the final SteamVR has the new input method I was out of luck. On a hunch I created a new user on my PC and everything works again. 

I then used this guide https://steamcommunity.com/app/250820/discussions/3/361787186419201673/
To create a compatible username and put anything revive related in it under appdata. I need to do some more testing to find out which folders exactly are needed but I am kinda happy that it works for now.

**Comment by Armada651** [comment]
I've updated the installer with a quick fix. Can you try deleting that special folder and then re-downloading and re-installing Revive?

**Comment by MacbethAUT** [comment]
Everything seems to be working again! Thanks!
