### ISSUE TITLE
xinput1_3.dll tr/patched.gen3

### ISSUE THREAD

**Issue by milesvor** [LibreVR/Revive#1119]
after latest update, xinput1_3.dll was blocked by avira as the trojan tr/patched.gen3

**Comment by Armada651** [comment]
Solution: Update to Windows 10 and don't use Avira, your OS already has a virus scanner.

**Comment by Armada651** [comment]
To show how garbage Avira is at doing its job, here is the virus total report for that file: https://www.virustotal.com/#/file/b7250834c4f990d7e9b60a170904f38f0f6379201dd10b37d4bae9df3803897d/detection
