### ISSUE TITLE
 How to start?

### ISSUE THREAD

**Issue by emozio666** [LibreVR/Revive#112]
Good afternoon, thank you for your work. But I need help. In steamvr appeared revive section, but when I stick to the game (any button), nothing happens...(

**Comment by LibreVR** [comment]
We're still working on bypassing the DRM on all games, so it will probably not work yet for most games.

**Comment by emozio666** [comment]
this house? I kind of downgraded to an older version, or again, Oculus invented something?

**Comment by emozio666** [comment]
I do not know why, but this morning, everything that i installed in Oculus home, 
started to work.
