### ISSUE TITLE
All Oculus Games Erroring  with SteamVR 1.1.3 and Revive 1.6.0

### ISSUE THREAD

**Issue by LilMissJustine** [LibreVR/Revive#1122]
Hi All,
Ever since the new SteamVR update (1.1.3) with the latest ReVive version (1.6.0),  all Oculus games are crashing / Erroring after a couple seconds of starting them up.    Anyone else have this issue?

My last known working configuration was SteamVR Beta (v1527117754 - 6/21/2018 hotfix) and ReVive (1.3.0)

I have tried downgrading SteamVR back to the beta, but it looks Steam removed 6/21 hotfix as it is no longer available in the drop down.

I have tried re-installing Revive 1.3.0, and that fixes the crashing issue, however, the buttons won't bind/work in any of the Oculus games/apps.    I know that this was an issue that was resolved in ReVive 1.4.2, but, any version of ReVive greater than 1.3.0 with the new SteamVR 1.6.0 version also crashes every Oculus App during the first couple seconds.

Has anyone run into this issue before and quite possible know of a fix?  Either for the crashing or the button mapping?

I'm currently launching games from inside SteamVR as well as the ReVive overlay in windows 7 task tray.

Thanks in advance!

System Specs:
Win 7 x64 Ultimate with latest updates
Nvidia 1070 with latest drivers
24gb ram
Intel i7 990x
ssd storage
Vive - 1st revision with updated firmware

**Comment by LilMissJustine** [comment]
Also another note:   The Fault Module that is common with all the apps/games crashing is vrclient_x64.dll

**Comment by LilMissJustine** [comment]
Looking at the GitHub issues, this issue is also seen in #1096

**Comment by LilMissJustine** [comment]
I did some more testing, and it seems like it is the Vive Controllers / input that are causing the crashing.   When opening up games like Bullet Train and The Climb with the Vive Controllers turned off, I don't experience any crashing.  However, the moment that I turn the controllers around and start moving, I have anyways between 2-30 seconds until the applications freeze.   I have also tried this in SuperHot VR as well.

**Comment by MacbethAUT** [comment]
I had a problem with Lone Echo, disabling Motion Smoothing helped.

**Comment by LilMissJustine** [comment]
I just checked my system.   Motion Smoothing is disabled (requires Win 10) to be enabled.  However I do have re-projection enabled.  

It seems like they took out the settings to turn the Asynch and Interleaved Repro on/off out of this new release.  It used to be in Settings -> Dev, but unfortunately not there anymore.
In the Video settings, Motion Smoothing is disabled due to me running Windows 7

@MacbethAUT :  Are you running Win 10?

**Comment by MacbethAUT** [comment]
Ah, yes I am running Win10.
:-/

**Comment by LilMissJustine** [comment]
Ahhh...Thank you for the confirmation.  The search for the cure continues.

**Comment by LuisGV212** [comment]
I'm also having issues. Windows 10. No Motion Smoothing (AMD card)

Everything crashes when I open with controllers on. The games boot up if the controllers are turned off. When I turn on the controllers, they track but no button works on the controller.

**Comment by Dragoboss** [comment]
To get back to this a little late:

As of June, Oculus officially dropped support for Win7.
1.3.0 was released before June and used the old SDK still and therefore might've worked for Win7 up till a certain point.

My best advice is consider upgrading to Win 10. There is still ways to do it for free.


As for @LuisGV212 
With the newer SteamVR also came the controller binding system. First make sure keybinds are actually set for that, then if you have further issues please post a new detailed report with the new format.
