### ISSUE TITLE
WMR:  Wobbly head movement in Lone Echo and Wilsons Heart

### ISSUE THREAD

**Issue by dborosev** [LibreVR/Revive#1125]
Windows Mixed Reality.  Not quite like judder, but more like the whole world wobbles when you move your head around.  Doesn't happen on Vive.

**Comment by pinoepel** [comment]
Yes, I have that to on Odyssey+

**Comment by dborosev** [comment]
Why won't it ever be supported?  WMR is growing user base.

**Comment by Armada651** [comment]
Because it's not possible on SteamVR. Only by translating directly to the Mixed Reality API can these issues be resolved.
