### ISSUE TITLE
"Failed to initialise OnlineSubSystemOculus (-4)"

### ISSUE THREAD

**Issue by KingCharMing** [LibreVR/Revive#113]
Hey,
Love your work, thank you so much for this amazing tool!
Problem I ran into, whenever I try to start up DreamDeck through Revive in SteamVR, this is the error I get:
"Failed to initialise OnlineSubSystemOculus (-4)"

Cheers

**Comment by LibreVR** [comment]
You put the platform DLLs in the wrong location, read the instructions again.
