### ISSUE TITLE
libremixed64_1.dll missing?

### ISSUE THREAD

**Issue by sakurarozu** [LibreVR/Revive#1132]
so i got this pop up when trying to run arkita 1 with vive. anyone know what this is and how i get this file? 

ty

**Comment by Armada651** [comment]
You need to have SteamVR running when using Revive.

**Comment by sakurarozu** [comment]
Hi

I have steam vr running and that’s what I get when trying to run arkita after using patch and running exe from folder.

**Comment by Armada651** [comment]
Do not use the patch function for Oculus titles. Just use the Revive Dashboard, if that doesn't work for whatever reason use the Inject function.

To undo the patch go to the Arktika.1 folder where you installed the patch and delete xinput1_3.dll.

**Comment by Dragoboss** [comment]
@sakurarozu 
Please verify if this is still an issue after following Armada's steps.

Otherwise I'll close the ticket in a few days.

**Comment by Dragoboss** [comment]
No response in the past 8 days after my last comment.
Closing ticket, please re-open if you re-encounter this problem.
