### ISSUE TITLE
Issue with revive and echo vr

### ISSUE THREAD

**Issue by JAREKRYBAK** [LibreVR/Revive#1134]
I cannot play this game on my vive  (using revive) cause i can`t disable Motion Smoothing cause i don`t have it.
I don`t know what do i have to do .  Echovr is just crashing on a start. (I don`t have motion smoothing cause i don`t have windows 10)

**Comment by Dragoboss** [comment]
Motion Smoothing is not enabled unless you run windows 10.
There must be another reason you cannot run EchoVR.

What happens (on the desktop) when you try to launch it whilst SteamVR is running?
Does it go straight to Bugsplat, does it go to menu but bugsplat when you try to join the lobby?

What Revive and what SteamVR version are you on? Any other special circumstances for your case other than not using Windows10? I am assuming you're on 8, then?

**Comment by JAREKRYBAK** [comment]
Im using windows 7  new re vive and no its good for like 20 sec and then its crushing and opensbigsplat when i was using old version of revive it doesn t happened but i cannot press any button tho

**Comment by JAREKRYBAK** [comment]
I can play game for half a minute idk and its crushing

**Comment by Dragoboss** [comment]
Do most games work on Revive with Win7?
I'd like to see the crash .dmp if you're willing to send it to me through discord.
Dragoboss#0666

**Comment by CarrotSurvivor** [comment]
Lmao, you’d think that because the new motion smoothing technology doesn’t work with windows 7, you would realize that oculus and all rift games don’t work on windows 7 either, and require windows 10. Lol

**Comment by JAREKRYBAK** [comment]
So why does it work on latest version of revive?  But then i cannot press any button on controllers

**Comment by Dragoboss** [comment]
Well ultimately games are built for running in windows 10. Some games might work in some way in win7 but there are always issues. Most devs don't even test on windows 7 let alone build against them.

I'm happy to check out that dump file still but ultimately I'll advise upgrade.

**Comment by JAREKRYBAK** [comment]
Ok i'll add you

**Comment by JAREKRYBAK** [comment]
Sended

**Comment by FoxtrotD** [comment]
This is the solution. 

https://github.com/LibreVR/Revive/issues/1123

**Comment by Dragoboss** [comment]
@FoxtrotD
Actually, his problem had to do with Windows, he was running on Win7.
I've helped him get the free windows upgrade and setup Revive again.
He can run the game without crashing (instantly) now.

Plus, Fatal Error crashes do not always have one and the same cause therefore not always the same fix.

I'll be closing this ticket shortly, as it is solved.
