### ISSUE TITLE
echo vr not 

### ISSUE THREAD

**Issue by W0rkWarri0r** [LibreVR/Revive#1135]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU:intel 15-1600k
  - GPU:gtx 1080
  - RAM: (amount and DDR#)16g
  - OS: windows 10
  - Vive 

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher v 1.6.1
  - SteamVR version (unless Remixed):1.1.4
  - Revive installation version:v 1.6.1

#### What is the last working version before this issue first came up?
  - Revive installation:-
  - SteamVR (unless remixed):-

### What apps/games are you trying to run?
  - Echo Vr

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. I started steam vr
  2.I started up echo vr

## Error messages/codes
  - oculas not detected

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Dragoboss** [comment]
@W0rkWarri0r 
To iterate more on what Armada said:
'Oculus not detected' means that Oculus doesn't see your hardware, nor the hardware Revive tries to make it see. Usually rebooting pc or rebooting Oculus completely solves that.

Please report back within the next few days if it still doesn't work.
If no response is posted in a week I'll assume this is fixed and close the ticket.

**Comment by W0rkWarri0r** [comment]
Hello revive was working until the most recent update wich caused the game
not to even load one a clicked it

**Comment by Dragoboss** [comment]
Can you navigate to #:\Oculus Apps\Software\ready-at-dawn-echo-arena\_temp\crashes and upload one or two of your recent .dmp files for me?

**Comment by W0rkWarri0r** [comment]
You might of misunderstood it's not crashing I literally when I try and
open it nothing happens


On 17 Dec 2018 16:43, "Dragoboss" <notifications@github.com> wrote:

Can you navigate to #:\Oculus
Apps\Software\ready-at-dawn-echo-arena_temp\crashes and upload one or two
of your recent .dmp files for me?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibreVR/Revive/issues/1135#issuecomment-447912509>, or mute
the thread

**Comment by Dragoboss** [comment]
Not even a bugsplat?

Sounds to my like your software is srsly not at all set up.
If it's not even showing any screen...
Cleanly reinstall Revive, check your Oculus software......

**Comment by W0rkWarri0r** [comment]
Thanks its working again

**Comment by Dragoboss** [comment]
Glad to hear it ;)
