### ISSUE TITLE
Free Oculus Henry and Home are shown with orange colors

### ISSUE THREAD

**Issue by MrBrain27** [LibreVR/Revive#1138]
Free Oculus Henry and Home are shown with only orange colors, like some orange filter is on, other apps have normal colors, looks like the problem only with cartoons of this developer which did both of them. 

  - CPU: ryzen 5 1500X
  - GPU: 1060 3gb
  - RAM: 8gb DDR4
  - OS:  Win 10 x64
  - Lenovo Explorer

**Comment by Armada651** [comment]
This is not a light filter issue, Oculus Henry tries to detect whether you're in view of the sensors. If you're using a WMR headset then there are no external sensors and the game always thinks you're out of view.

**Comment by MrBrain27** [comment]
> 
> 
> I read a Reddit post about this a few days back.
> [Reddit](https://www.reddit.com/r/WindowsMR/comments/a6ny58/all_colors_in_free_henry_and_home_oculus_cartoons/)
> 
> There it is mentioned a restart did the trick.
> But I wouldn't be surprised if one of those blue-light filter apps was the culprit.
Actually it was my post =) Restarting not help, and I don't use any apps which can add filters, I launch cartoons via Revive Overlay.

**Comment by MrBrain27** [comment]
Looks like this problem only happens when I launch the game directly from dashboard, if I start steam vr first the cartoons work fine =)

**Comment by Armada651** [comment]
Interesting sounds like a Remixed problem then.

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
