### ISSUE TITLE
Medium 2.2 update and Oculus Software v1.33.0 not working anymore with Revive Version 1.5.1

### ISSUE THREAD

**Issue by Symbiotox** [LibreVR/Revive#1139]
Medium 2.1, Oculus Software 1.32 and Revive 1.51 worked fine. Automatic Oculus update was on which messed up my setup.
Any advice, please?

**Comment by Dragoboss** [comment]
Can you try with 1.6.2?
Medium 2.2 came with a new Oculus SDK version.
That SDK version is used to build 1.6.2 now.

**Comment by Armada651** [comment]
Actually it looks like the problem was that Oculus moved the executable. Updating Revive will fix that however since that will refresh all cached executable locations.

**Comment by Symbiotox** [comment]
Fantastic!!! Thanks so much Dragoboss and Armada651. After uninstalling Revive v1.5.1 and reinstalling Revive v1.6.2 Medium and also Quill (the 2 installed Oculus apps) worked like a charm again. Brilliant.
I switched off Oculus automatic updates now that everything works, just to be sure!
Thanks guys for the very quick response and happy holidays.
