### ISSUE TITLE
Unable to find new Revive tab on Vive in display dashboard

### ISSUE THREAD

**Issue by shijocj1978** [LibreVR/Revive#114]
Windows 10, Vive PC client 1.0.8889, Steam VR version 1463781942

I just got the Vive two days before and Installed Steam VR, Oculus home and did all as per '<> code' tab. Started Steam VR and put on head set. I looked all over the dashboard(the window that comes when I press Steam button on bottom of controller) and not able to find newly added Revive tab in dashboard. How do I resolve it?

**Comment by Bendingo** [comment]
I had this problem too, solved it by doing the following:

- Close down SteamVR
- Go to your Revive install directory
- run "ReviveOverlay.exe"
- Restart SteamVR

Hopefully should work after that

**Comment by SRombauts** [comment]
Hi, I had this too after a fresh uninstall/reinstall of this new release.
I just stopped steamvr and reinstalled it a second time (without an uninstall) and it worked.

**Comment by TrashiDawa** [comment]
Having the same issue.

Revive installed at C:\Program Files (x86)\Revive

Tried running ReviveOverlay.exe and it starts the Vive display blinks on temporarily but does not show up in the task manager as far as I can tell.

No Revive button in the Steam VR menu.

**Comment by LibreVR** [comment]
@TrashiDawa Can you post your logs from `%APPDATA%\Revive`?

**Comment by TrashiDawa** [comment]
Thanks so much for your quick reply. I reinstalled my Nvidia display driver and Revive worked flawlessly after that.

Awesome job with this, it's much appreciated!

**Comment by shijocj1978** [comment]
running ReviveOverlay solved the issue for me.!!! Kudos Bendingo!!!

**Comment by dlaroc** [comment]
Do you have the HTC Vive program installed? I noticed after reinstalling my headset, it only installed SteamVR and it wouldnt show the Revive button. I realized i didnt have the Vive program installed so i did that. Waiting for it to finish installing. Im pretty sure thats it. I remember being able to see the Oculus games in HTC Vive Home before. I think you need the HtC software for Revive to work.

**Comment by LibreVR** [comment]
@dlaroc You definitely don't need the HTC software for Revive. But if you uninstall SteamVR you will need to reinstall Revive or launch the dashboard manually from the start menu at least once.

**Comment by dlaroc** [comment]
Ok. I figured it out. I had to go into SteamVR settings on desktop and check Revive under overlays. You can also check Vive Home there too. (I think thats what it was called)
