### ISSUE TITLE
iRacing not working

### ISSUE THREAD

**Issue by nafan08** [LibreVR/Revive#1140]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
Since iRacing recently updated many users are unable to use Revive with a WMR headset just will not detect anymore. When using OpenVR with the Samsung a handful of users get a double vision issue like the screens wont align properly yet they work fine in every other game.
Revive fixed that for us it used to work perfect as a Rift but now with the new update it wont detect the headset. 
Is there a way we could possibly fix this issue?   

### Technical Information
*Tell us your specs and versions*
  - CPU: intel 5820
  - GPU: Asus 980ti
  - RAM: (amount and DDR#) 16gb
  - OS: windows 10
  -  WMR (/ Odyssey) 

### What apps/games are you trying to run?
  - iRacing

**Comment by nafan08** [comment]
> It seems the issue is that iRacing uses xinput9_1_0.dll rather than xinput1_3.dll, after patching simply renaming the later to the former seems to make it work. (Also ensuring not to overwrite the existing openvr library).

You legend that has fixed it :D Thank you.

**Comment by Brelin** [comment]
I dont have the file: xinput9_1_0.dll I only have the xinput1_3.dll and with this file it dont work.
Where to get the xinput9_1_0.dll? Maybe I can rename the file and then it will work.

**Comment by nafan08** [comment]
> I dont have the file: xinput9_1_0.dll I only have the xinput1_3.dll and with this file it dont work.
> Where to get the xinput9_1_0.dll? Maybe I can rename the file and then it will work.

yes you just Rename the file.
