### ISSUE TITLE
Lone Echo crashing

### ISSUE THREAD

**Issue by Hoshi82** [LibreVR/Revive#1143]
Game crashes ingame after a very short time or crashes on launch. Some month ago it worked fine.

**Comment by Dragoboss** [comment]
You completely ignored the formatting. 
Please give us more details. Your report right now doesn't provide us with any needs to even diagnose let alone solve your problem.

**Comment by Hoshi82** [comment]
*Tell us your specs and versions*
  - CPU: i7-4770k @3.5 GHz
  - GPU: GTX 1080
  - RAM: 16 DDR3
  - OS: Windows 10 64bit
  - Vive

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed): 1.1.4
  - Revive installation version: 1.6.2.0

#### What is the last working version before this issue first came up?
  - Revive installation: Got the game when 1.6.2.0 was already released
  - SteamVR (unless remixed): Same

### What apps/games are you trying to run?
  - Lone Echo

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Simply try to start Lone Echo via the Revive overlay inside the steam vr dashboard. Sometimes it doesn't start and give instantly a splatbug report. Sometimes during the in game main menu after 30-60 sek. Seems not related to any ingame action. Crashes while in settings menu, crashes while game loads a new game.

## Error messages/codes
  - Since I deinstalled Lone Echo and have to re download the game I can't provide any error message except the splatbug screen popped up.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by temp89** [comment]
Fix: Disable motion smoothing in SteamVR under Video

**Comment by Dragoboss** [comment]
User has reported on Discord this was fixed by disabling motion smoothing.
In the future we'll be looking at ways to not have to force that on users, but for now this is the solution.

**Comment by joeman719** [comment]
Lone Echo does not work for me at all and I keep motion smoothing off.
Ryzen 2700x
DDR4 16 gb ram
GTX 1080
windows 10
vive
