### ISSUE TITLE
VRChat (Oculus Store Version) not launching in VR though ReMixed.

### ISSUE THREAD

**Issue by yackaro** [LibreVR/Revive#1144]
### Description of the issue
VRChat, the Oculus version, does not run in VR mode when launched through the dashboard in ReMixed mode. Works fine in ReVive mode, but the buttons do not map properly.

### Technical Information
R7 1700 (OC 3.7GHz)
RTX 2070 (400A die)
2x8GB DDR4-3000
Windows 10
Windows Mixed Reality, Lenovo Explorer

#### Versions and features
*This issue is about:*
Remixed launching game in non-VR mode
ReVive 1.6.2

### What apps/games are you trying to run?
VRChat Oculus Store version

## How to reproduce your issue?
  1. Launch Windows Mixed Reality
  2. Launch ReVive without SteamVR (Regular ReMixed launch)
  3. Open VRChat
  4. It opens in desktop mode, rather than VR mode.

I followed the issue Template to a T, hopefully it gives enough insight on what might be causing it to do that. I find the lack of thumbstick support on the SteamVR version of this game very frustrating, and the hand gestures constantly interfere with the control setup.

**Comment by Armada651** [comment]
> Works fine in ReVive mode, but the buttons do not map properly.

So do none of the buttons work? Have you checked the bindings in the VR settings?

**Comment by Armada651** [comment]
Looks like something messed up the controller bindings in Revive for WMR. I'll fix it when I'm back from vacation.

You can also attempt to fix it yourself by opening the VR settings in the dashboard and select Controller Bindings.

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
