### ISSUE TITLE
Echo VR Remixed Joy Stick Turning

### ISSUE THREAD

**Issue by Porcelainfog** [LibreVR/Revive#1145]
First of all, thank you so much for fixing the disk throwing in echo vr for WMR users. It throws so much better now. I am really grateful for it. 

A new issue I've noticed in remixed is that the joysticks are fairly particular. If you want to turn left (or any direction), you need to be 100% on the correct spot with the joystick. I am using smooth turning in echo vr, samsung odyssey original, decent enough PC. 

Again, it feels like to use the joysticks you have to perfectly hit the correct spot. Dead center left, or up, or down, or right. Any diagonal input doesn't register anything. Kind of wiggling the joystick back and forth over direct left is the only way I can turn left. 

I am on the latest build. 

I am playing Echo VR

To reproduce the issue, use remixed on a WMR and enable smooth turning and the advanced turning options (in ECHO VR, there is an option that lets you do flips, or turn upside down, etc. I think it's labeled advanced turn and yaw.). With these options I am having trouble registering a turn unless I hit the specific spot with the joystick (0 degrees, 90 degrees, 180 degrees, and 270 degrees are the only spots on the joystick that will register anything)

That being said, I haven't tried any other options yet. I played for 5 minutes, noticed the bug, and now i'm reporting it before bed. 

I wish I could add more to the project in a more meaningful way. Thanks for all the hard work

**Comment by Dragoboss** [comment]
As far as I recall this has always been the case. I've never really thought about it much, myself. 
EchoVR itself on Rift doesn't respond much to diagonal positions either, however the controls are a little less precision sensitive.

It might be able to allow a broader spectrum of directions to trigger the turning actions.
Would have to take a look at it...

Thank you for the report.

**Comment by Porcelainfog** [comment]
Thank you. I'll let you know if I find any other weird bugs.

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
