### ISSUE TITLE
Dirt Rally Not Working

### ISSUE THREAD

**Issue by foodcache3** [LibreVR/Revive#1146]
### Description of the issue
Dirt Rally is only running on desktop and not on the Vive, which is on the white room thing. I have patched the game with an older stable version (1.4.2) and the latest version of Revive, and I have also tried the SteamVR beta, none of it has worked. I have the Oculus software installed and also the direct x thing.  I also unchecked the theater thing. This is my first time using Revive, so I might be doing something wrong, but I dont know what.

### Technical Information
  - CPU: i5 8600k
  - GPU: GTX 1070
  - RAM: (amount and DDR#) 16GB DDR4
  - OS: Windows 10 Home
  - Vive

**Comment by Armada651** [comment]
If the Steam version doesn't work for you can try the Oculus Store version?

**Comment by foodcache3** [comment]
Well I figured it out. All I had to do was restart apparently.
