### ISSUE TITLE
Any chance Polybius can launch this way?

### ISSUE THREAD

**Issue by axfelix** [LibreVR/Revive#1147]
Polybius, inexplicably, launched on Steam only with Oculus support only, and there doesn't seem to be a way to launch it with Revive. Can anything be done here? I know it's probably a lot of work for one title...

Thanks!

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/wiki#steam-games

**Comment by axfelix** [comment]
Thanks for the quick response! I don't seem to have a Revive tray icon; where in the Revive install folder can I find those DLLs?

**Comment by axfelix** [comment]
If it's the regular contents of Revive/Revive/x64 (LibRemixed64_1.dll and so on) looks like still no dice; the game says it doesn't support my current headset when trying to launch. Oh well!

**Comment by Armada651** [comment]
If you want to do it manually you need to copy all the DLLs (except LibRemixed)

**Comment by axfelix** [comment]
If I'm using an WMR headset, should I use both Remixed and Revive?

**Comment by Armada651** [comment]
No, Remixed is not supported this way.

**Comment by djkirsch** [comment]
It will start working and will try and start but it seems Polybius has a separate check to detect if a Rift is plugged in.

**Comment by axfelix** [comment]
Evidently the devs are planning a proper Vive port in 2019, so that might be that. Closing, thanks!
