### ISSUE TITLE
lone echo and other games not working on latest release, but working on on 1.2.1

### ISSUE THREAD

**Issue by SasukeSpirit** [LibreVR/Revive#1149]
I was on Revive 1.2.1, I bought a bunch of games on the Oculus Store yesterday (Lone Echo, Arktika1, From Other Suns, Brass Tactics, Robo Recall) and all of them worked flawlessly with the exception of From Other Suns, which was giving me a message of Failed Entitlement something like that. Then I upgraded to a newer Revive version to try From Other Suns, and then all the other mentioned games stopped working, with the exception of Brass Tactics. With similar messages like failed hardware heck, or Entitlement check failed or something like that.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 7820X
  - GPU:  Gigabyte GTX 1080 Ti Xtreme 
  - RAM: 64GB 3600Mhz
  - OS: Windows 10 Pro
  - HTC Vive

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed): 1.1.4 Non-Beta
  - Revive installation version: 1.6.2

#### What is the last working version before this issue first came up?
  - Revive installation: 1.2.1
  - SteamVR (unless remixed): 1.1.4

### What apps/games are you trying to run?
  - Lone Echo
  - Arktika1
  -From Other Suns
  -Robo Recall
  -Brass Tactics

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. I bought the Games

  2. Tried them one by one on Revive 1.2.1, all of the mentioned games worked fine, except for From Other Suns.

  3. Checked a recent version of Revive trying to get From Other Suns to work, and downloaded and installed version 1.6.2

  4. All of the games mentioned now didn't work, with the exception of Brass Tactics 

## Error messages/codes
  - I added images for all the error messages

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!
![arktika1 27_12_2018 20_16_10](https://user-images.githubusercontent.com/46200997/50491940-33227d00-0a15-11e9-8829-82d8acc84e84.png)
![lone echo 27_12_2018 20_14_29](https://user-images.githubusercontent.com/46200997/50491941-33bb1380-0a15-11e9-9a72-5e70bb6cc343.png)
![mensaje 27_12_2018 20_16_31](https://user-images.githubusercontent.com/46200997/50491942-33bb1380-0a15-11e9-81bb-19d159741d9f.png)
![message 27_12_2018 20_15_11](https://user-images.githubusercontent.com/46200997/50491943-33bb1380-0a15-11e9-8a40-fcc4b4e9e84e.png)

**Comment by Dragoboss** [comment]
If it complains about entitlement usually it's enough to restart oculus and/or log out and back into your account.
To restart, in the Oculus client you can do to Settings > Beta > restart oculus.

The hardware issue is odd. This is the exact function Revive was built for...

So just brass tactics now or lone echo now?
If lone echo please go into your SteamVR settings and disable Motion Smoothing under video settings.
Then we'll diagnose further.

**Comment by SasukeSpirit** [comment]
Today, I did what you told me but in berserk mode, instead of restarting oculus, I uninstalled all the Oculus software, uninstalled all the Revive software, and reinstalled all over again (Revive version 1.6.2 and Oculus Software) and all 5 games were working flawlessly (Brass Tactics, Lone Echo, Arktika1, RoboRecall, From Other Suns) then I continued to try other things like Oculus First Contact and Oculus Avatars and they didn't even started, the revive tab on SteamVR just got a little faded like it was going to start, but nothing happened.  

But the good news are that the more important games are working, I'll further test, and if you have some suggestion, please let me know. Thanks for answering so quickly, and the tip about restarting/reinstalling was useful at last.
