### ISSUE TITLE
pixelsPerDisplayPixel Parameter Currently Not Used

### ISSUE THREAD

**Issue by seaweeduk** [LibreVR/Revive#115]
Hi, 

Just adding this as an issue so it's not forgotten. I saw it mentioned on reddit as being on the table for the next release. It would be very welcome by all the people currently using the old project cars 0.52 revive to play the Steam release of Assetto Corsa at higher resolutions. 

Thanks

**Comment by seaweeduk** [comment]
Just saw you have already committed the change! Thankyou LibreVR can't wait to try the next release

**Comment by LibreVR** [comment]
I'll also add a slightly improved version of the Project Cars patch that I'll recommend for all Oculus Rift exclusives on Steam.
