### ISSUE TITLE
Echo Vr Doesn't even start

### ISSUE THREAD

**Issue by ColeSkory** [LibreVR/Revive#1153]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
Whenever I try and start Echo VR, it says "An unknown error has occurred" and freezes on a white screen. I get a crash report that I'll attach.
![bugsplat](https://user-images.githubusercontent.com/13986551/50552032-fb4f4b80-0c47-11e9-8dc2-9390b543e701.png)

### Technical Information
*Tell us your specs and versions*
  - CPU: Intel i5-4570 3.20 ghz
  - GPU: Nvidea Gtx 1060 12 gb
  - RAM: (amount and DDR#) 8
  - OS:  Windows 10
  - Vive Newest 
  - Revive 1.6.2.0
  - Steam VR 1.1.4

#### Versions and features
*This issue is about:*
Echo Vr Version 18.3.268902.0

#### What is the last working version before this issue first came up?
  - I haven't played in about 6 months due to room requirements

### What apps/games are you trying to run?
  - Echo VR

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Start Echo VR from Revive menu in HTC VIVE

## Error messages/codes
  - "An Unknown error has occurred"

I've attached some log 
[RAD_CRASHDUMP_ColeS_echovr_2018_12_30_15_30_28.log](https://github.com/LibreVR/Revive/files/2717560/RAD_CRASHDUMP_ColeS_echovr_2018_12_30_15_30_28.log)
[RAD_CRASHDUMP_ColeS_echovr_2018_12_30_15_36_06.log](https://github.com/LibreVR/Revive/files/2717561/RAD_CRASHDUMP_ColeS_echovr_2018_12_30_15_36_06.log)

files too

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by ColeSkory** [comment]
I just checked, there is no ColeS/AppData folder...

**Comment by Dragoboss** [comment]
Did you already disable SteamVR's motion smoothing?
The newer SteamVR's motion smoothing breaks Echo games.

Furthermore, the screenshot of a crash report doesn't provide any info.
You can find the minidumps under the EchoVR installation folder then the '_temp' folder.

**Comment by ColeSkory** [comment]
Also, other games that I downloaded through Oculus do work. It's just Echo Vr for some reason... I do notice that in the log it's referencing a drive that I no longer have. I'm not sure if that's an issue 
"- 0xC8C33E483C7A12B5: d:/projects_root/rad/dev/src/engine/libs/vr/cvr_win.cpp) on line 37.

Motion Smoothing is disabled, yes. I think I already attached those logs further down in the post.

Thanks!

**Comment by Dragoboss** [comment]
Those are the logs. I am looking for the .dmp files.

**Comment by ColeSkory** [comment]
I tried uploading those, but it said it didn't accept that file format. Is there somewhere else I should upload them?

**Comment by Dragoboss** [comment]
Add me on Discord:
Dragoboss#0666

**Comment by Armada651** [comment]
> Failed to create OVR D3D swap chain (-7000)

This is the problem, but no one else seems to encounter this issue, make sure your video drivers are up-to-date and try with the latest pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
