### ISSUE TITLE
Incorrect world positioning in iRacing with remixed

### ISSUE THREAD

**Issue by brads55** [LibreVR/Revive#1155]
### Description of the issue

When using remixed with iRacing the headset position in the world is off after recentering the headset, it is slightly too high. It's not clear to me whether this is the only issue or not, or if scaling is also off.

In addition to this, although not a problem, just an observation and probably related, the Beta UI that iRacing uses is a lot closer to the headset when using Remixed vs Revive.

### Technical Information
*Tell us your specs and versions*
  - CPU: 8086k
  - GPU: 2080Ti
  - RAM: 16GB
  - OS: Windows 10 (1809)
  - Odyssey+

#### Versions and features
*This issue is about:*
  - Remixed version: 1.6.2

#### What is the last working version before this issue first came up?
  - Not sure this ever worked

### What apps/games are you trying to run?
  - iRacing (Oculus SDK v1.26)

## How to reproduce your issue?
Nothing special here, just start a race and recenter the headset, compared with Revive you sit much higher in the vehicle. (To the point where your head starts clipping through the roof).

Some useful notes however, for iRacing to work with Remixed, the xinput library must be renamed to XInput9_1_0.dll and the Remixed library renamed to the Revive library.

I appreciate that this is probably a very unsupported setup and is probably not supposed to work, however my aim with this issue more than anything is to see if this is a known todo and if it's more than just being too high, (it's not clear to me that this is the same as #1105, but it's possible that it is). Most notably I notice that CompositorD3D::RenderTextureSwapChain has a todo mentioning taking fov into account, and I guess this is possibly the problem?

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
