### ISSUE TITLE
Nothing works /:

### ISSUE THREAD

**Issue by Harry989** [LibreVR/Revive#1156]
### Description of the issue
*Please provide us with a detailed description of the issue*

I was really bored one day, and i fancied playing some Oculus VR games seen as i was really bored of some of my SteamVR games after overplaying them a while ago, so i re downloaded revive and updated everything, i then proceeded to start SteamVR and open Echo VR which happens to have a problem that i am usure on what to do.

### Technical Information
*Tell us your specs and versions*
  - CPU: Intel i5 7th Gen
  - GPU: GEFORCE GTX 960M
  - RAM: DDR4 (Not sure about the amount, but around 4GB to 16GB)
  - OS: Windows 10
  - Windows Mixed Reality (Dell Visor)

#### Versions and features
*This issue is about:*
  - Revive - Latest
  - SteamVR - Latest
  - Steam Client - Latest

#### What is the last working version before this issue first came up?
  - After ages of leaving my VR Headset untouched

### What apps/games are you trying to run?
  - Any Oculus games that i own (even the Oculus Tutorial still doesnt  work)
  - Mostly Echo VR

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. I downloaded Oculus and Revive
  2. I opened SteamVR and checked everything was up to their latest update.
  3. I went into the Revive tab and tried to open Echo VR and said something like “Incorrect argument” and closed down.

## Error messages/codes
  - “incorrect argument”
  - “you need an Oculus to play this”

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Cannot reproduce
