### ISSUE TITLE
Lone Echo Not Responding to WMR Controller Inputs in Remixed or Revive Injector

### ISSUE THREAD

**Issue by JoePinapples** [LibreVR/Revive#1158]
# Revive/Remixed Report Template

### Description of the issue
Lone Echo will load from the revive dashboard with remixed and it will also load from the revive injector within the Steam VR compositor. However once loaded into the main menu of the game the WMR controller inputs are not registering and I cannot move passed the main menu into the game.

There is a slight difference arising between using the 2 different revive methods which I will outline below:
**Issues Experienced Launching Through Remixed**
When launching the game in remixed i.e. via the Revive Overlay, (without using SteamVR)

1. The game will load into the main menu
2. I can see that the wmr controllers are being tracked and moving correctly.
3. Pressing buttons such as the grab and the trigger buttons on the controllers will prompt grab and 
trigger animations on the in-game holographic robot hands
4. The icons for the camera and the oculus rift on the bottom right in the Lone Echo main menu are 
showing as green, i.e. connected however the touch controllers are displayed as red, i.e. not connected.
5. I can see the point of focus dot in the Lone Echo VR main menu and it corresponds to the movement of my wmr controller, however when pointing it at any of the options within the menu it is not highlighting the targeted option. The single player option is constantly highlighted and does not budge from there regardless of where I point to with the controller.
6. Pointing at the highlighted single player option and pressing trigger has no effect
7. Alt tabbing out and back in had no effect
8. Pressing the windows button to go back to the cliff house and then going back into remixed has no effect. 
9. The Samsung Odyssey plus controllers simply are not registering.
10. Whilst still in the main menu, If I remove my headset I can observe on my desk top the following Hardware error message: "_You have a pending hardware issue that is preventing you from entering VR. Please check your left touch controller is paired and powered_".  (the error message is displayed fullscreen in a bordered window with white writing on a totally black background, the message does not give me any options to select, such as okay or close).
![image](https://user-images.githubusercontent.com/46082587/50654096-a2532080-0f83-11e9-8265-608f277917d9.png)

**Issues Experienced Launching Through Revive & Injector**

1. The game will load into the main menu
2. I can see that the wmr controllers are being tracked and moving correctly.
3. Pressing buttons such as the grab and the trigger buttons on the controllers this time **DO NOT** prompt grab and trigger animations on the in-game hands
4. All the icons for the cameras, the oculus rift and the touch controllers on the bottom right in the Lone Echo main menu are showing as green, i.e. connected 
5. I can see the focus dot in the Lone Echo VR main menu and it corresponds to the movement of my wmr controller, however this time when pointing it at any of the options within the menu **IT IS** highlighting the targeted option. 
6. However pointing at the single player option and pressing trigger  or any of the main menu options has no effect
7. Alt tabbing out and back in had no effect
8. Pressing the windows button to go back to the cliff house and then going back into revive has no effect. 
9. The Samsung Odyssey plus controllers simply are not registering again.
10. Using this method however I do not get a hardware error message on the desktop.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 4770k 4.4ghz
  - GPU: EVGA GTX 1080ti ftw3 driver version 417.35
  - RAM: (16gb DDR3 1800mhz)
  - OS:  Windows 10 Pro 64 bit version 1803
  - WMR ( Samsung Odyssey Plus, not the regular Odyssey) 

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector: All
  - SteamVR version 1.1.4 & SteamVR Beta 1.2.3
  - Revive installation version: I am using the latest 1.6.2 Revive version

#### What is the last working version before this issue first came up?
n/a I just bough Lone Echo and tried it for the first time
 
### What apps/games are you trying to run?
  - Lone Echo

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

1. Try loading game with Samsung Odyssey Plus WMR headset, the controllers of the Odyssey Plus now connected differently than they did with the regular Odyssey. No separate bluetooth dongle required. The controllers now are automatically paired with the headset itself.
2. Use SteamVR Beta 1.2.3, (although I tried it with and without beta, in game results are the same for me)
3. Use Window Mixed Reality for SteamVR App and latest public beta, (again tried it with and without beta with same result)
4. The Samsung Odyssey + HMD is connected to the GPU via HDMI 2.0, the TV, which I use as a monitor, is a Samsung 4k HDR smart tv is connected to the GPU via a display port to HDMI adapter
5. No motion smoothing for WMR so should be off by default
6. Tried turning off /on reprojection no effect. 
7. Tried it with no super sampling no effect. 
8. Tried uninstalling and fresh installing Revive, SteamVR and of Windows Mixed Reality for Steam VR . 
9. Checked system file integrity for SteamVR and WMR for SteamVR apps all 100% validated.

The controller inputs  simply will not register in the menu. My hunch is that Revive is not telling the game that the controllers are connected correctly. This may be a Samsung Odyssey Plus issue in that the controllers no longer require a separate bluetooth dongle in the computer to make a connection, like the previous Samsung Odyssey did, but that they are now paired with the headset itself. Just a thought!

I just want to add a big thank you I love the software and it has helped me play Oculus games such as Robo Recall, Edge of Nowhere, Air Car and First Contact without any issues whatsoever.
I am really appreciative of any support you may offer to get Lone Echo up and running.

Discord ID
JoPineapples#3512

## Error messages/codes:
Message Received when using remixed method:
  - You have a pending hardware issue that is preventing you from entering VR. Please check your left touch controller is switched on and is connected

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Dragoboss** [comment]
Confirming Remixed controllers on Lone Echo no longer working. Looking into it.

**Comment by JoePinapples** [comment]
@Dragoboss I can confirm that running it through Revive on the SteamVR dashboard is the exact same result as running it through the manual injector

**Comment by gazcart** [comment]
I experience exactly the same issue as JoePinapples I have a Lenovo WMR headset, would love a fix for this

**Comment by gazcart** [comment]
Also, as mentioned if Lone Echo is launched via Revive dashboard directly it runs but button responses are not registered so you are unable to start the game. If I launch the Lone Echo VR (the free multiplayer game) from Revive it launches and button presses DO work and when it the game it is buttery smooth . Launching this same Lone Echo VR multiplayer game via SteamVR stutters as you turn your head, the same as the full game. So this is quite annoying that the menu and start screen work in the multiplayer aspect, seems like it would be a relatively easy fix to work out whats different :-(

**Comment by Truenox** [comment]
I've been with this problem for a few weeks, I tried to see if it was the subject of the revive and tried to update to the most current version (1.6.3) but without solving it.

With several guys who have the same problem, they give the steamvr version as a solution, they say that doing a downgrade to version 1.3.3 works correctly ...

After trying to do the downgrade, as steam always updates, I can not keep that version, so after the announcement of a user that the Lone Echo worked perfectly with SteamVR 1.2.10 and Revive 1.4.2, I decided to try the different versions of Revive and ... indeed, I have tested all versions after 1.4.2 and none of them work.

So you know, if you want to play your Oculus games with SteamVR 1.2.10, you will have to make a downgrade of its version 1.4.2 revive until further notice.

**Comment by appleguy** [comment]
I'm having this exact same issue with an Odyessy Plus. It's a shame, since I got the unit primarily for Lone Echo :). Robo Recall does not work either ("connect controllers" screen). Both games work flawlessly with the Rift.

**Comment by m0nk210** [comment]
After yesterday's remixed support update the buttons get registered again and the game works again for me!

**Comment by JoePinapples** [comment]
Okay after your message yesterday I tried again last night, the button press not registering issue still persists in Remixed and in Revive through the Steam VR compositor and through manual injection. 
The 1.6.3 update must have resolved the problem for Vive controllers but unfortunately it has not fixed it for WMR controllers.

**Comment by yd76** [comment]
Same as m0nk210.
After upgrading to 1.6.3, I was happy to see that my controllers were fully registered by the game, and I was able to play for 1 hour.
Today, I want to resume the game, and I was unable to click on any buttons...  
I really don't know what I have done...

**Comment by TimeIsFading** [comment]
I had this issue of no buttons working with injecting Lone Echo on the Vive. Recently updated to 1.6.3 and the issue still persists. Why is this happening?

**Comment by yd76** [comment]
Tonight, Lone Echo is working on my PC with my Lenovo Explorer. I don't know why, but if it could help someone, I did this:
- Launch steam (v1549129917)
- Launch Steam VR
- Kill Revive Tray Icon
- Launch Revive
- Inject LoneEcho.exe

And I'm able to click on buttons.

**Comment by JoePinapples** [comment]
@yd76 Unfortunately i cannot get it to work using your method. Perhaps I am doing something wrong. Can you describe in greater detail exactly the steps you took? I am still have the same problem. Also when you kill the revive tray icon and "launch the revive dashboard" do you mean the remixed overlay? Once you quit the revive tray icon revive no longer shows up in the steam dash board. So I am a bit confused about this step.

When launching through remixed now I no longer get the hardware error message and the controllers are tracking and the button presses are prompting the corresponding animations on the robotic hands. However, it appears that the game thinks that my HMD is not on correctly. The icon that indicates the HMD status in the start menu is in a paused state and depicts the oculus headset raised up resting on the models forehead rather than in the playing position. Perhaps this is what is preventing the buttons from registering. The game thinks that that the HMD is not down in the playing position on the head and that input is going to the desktop?

**Comment by zerong13** [comment]
> 
> 
> Tonight, Lone Echo is working on my PC with my Lenovo Explorer. I don't know why, but if it could help someone, I did this:
> 
>     * Launch steam (v1549129917)
> 
>     * Launch Steam VR
> 
>     * Revive Tray Icon - Right click - Quit
> 
>     * Launch Revive Dashboard
> 
>     * Inject LoneEcho.exe
> 
> 
> And I can click on buttons.

I dont know why but it's work for me ! thanks you very much !  Perhaps revive don't initialize correctly with steamvr and need a restart ?!?

**Comment by yd76** [comment]
@JoePinapples 
Here are my details actions. Most important thing seems to restart Revive Dashboard after SteamVR launch:
- Switch on your two VR Controllers
- Double click on Steam icon (steam is launching)
- On Steam client, on the top right end corner of the windows, clic on "VR"  (steaml VR is launching)
- On the System Tray, select Revive Dashboard, right clic, Quit.
- Start menu - Revive - Revive Dashboard, click (Revive Dashboard is launching), and a new Revive Dashboard icon appear on the System Tray.
- On the System Tray, select Revive Dashboard, right clic, Inject...
- Select the LoneEcho.exe executable from the game installation directory, and validate. Game will launch, and it will be possible to click on buttons.

I hope it could help you until this issue is fixed.

**Comment by TimeIsFading** [comment]
@yd76
Restarting Revive Dashboard after launching SteamVR totally solved the problem. Thank you!

**Comment by Truenox** [comment]
> Tonight, Lone Echo is working on my PC with my Lenovo Explorer. I don't know why, but if it could help someone, I did this:
> 
> * Launch steam (v1549129917)
> * Launch Steam VR
> * Revive Tray Icon - Right click - Quit
> * Launch Revive Dashboard
> * Inject LoneEcho.exe
> 
> And I can click on buttons.

Solved my problem. OMG. Thank you!

**Comment by JoePinapples** [comment]
No joy for me tried exactly everything as you described and i'm back to getting the hardware error message as described above.
![image](https://user-images.githubusercontent.com/46082587/52911091-2c86e800-3297-11e9-9f12-ba2892aa0a6e.png)

RANT AHEAD, DO NOT READ IF SENSITIVE TO PROFANITY!!!
Do you know what... I'm sorry, but FUCK this shit...Fuck VR and Fuck Revive... This VR shit has been buggy and a pain in my ass since I got this stupid fucking WMR headset. Its a complete load of old bollox and is just not ready for mass consumption yet. Nothing has worked perfectly since I got this stupid fucking thing, every single game requires some sort of tweaking. Its get to feel like I spend more time tweaking and adjusting things and trying to get things to work just right than I actually do playing games. Maybe in 5 years it will work and I'll come back to VR, until then my WMR headset is getting fucked into the bin!! 
Disclaimer: I know it's not the revive developer's fault and I give much kudos to him and any others who contribute to this application and for even doing something at all, but its primarily for Vive users and not WMR users. In all fairness he has never claimed that it was for WMR and has been quite open about it being a bonus if it works for WMR at all. I blame all the websites out there that claim Revive works with WMR when its simply doesn't and Oculus for having exclusives on a such a fledgling platform that needs to encourage people to adopt VR rather than segregate them. But for WMR its pot luck if Revive works or not. I'm done with this shit. VR can go and FUCK OFF, I'm not spending one more cent of my hard earned money on this bullshit until its fully cooked. See you all in five years!!
RANT OVER!!

**Comment by steffenthomas** [comment]
Hey JoePinapples,
i can understand your frustration, but give it just one more try. I also have a Samsung Odyssey+. It took a while to figure out how to get the game running, but now i can play the game without problems. Look at this video and follow my steps:

https://www.youtube.com/watch?v=MYYm9R7TXaQ

1. Connect your Samsunf Odyssey+ with the HDMI and USB3-Port and wait until the Mixed-Reality Portal opens up.
2. Now start both bluetooth controllers.
3. Start SteamVR from your Desktop and wait until the headset and the controllers are recognized correctly. If REVIVE starts automatically, please exit it before the next step.
4. Now start the REVIVE-Dashboard again as ADMINISTRATOR !!!!!
5. Rightclick on the REVIVE-Icon in your taskbar and select "inject". Navigate to your LoneEcho.exe.
6. Done. It should work now.

P.S.: My System- and Hardware-Specs are listed in the video-description.

Regards
Thomas

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0

**Comment by amstrad** [comment]
> Tonight, Lone Echo is working on my PC with my Lenovo Explorer. I don't know why, but if it could help someone, I did this:
> 
> * Launch steam (v1549129917)
> * Launch Steam VR
> * Revive Tray Icon - Right click - Quit
> * Launch Revive Dashboard
> * Inject LoneEcho.exe
> 
> And I can click on buttons.

This fixed my no button click with odyssey+
