### ISSUE TITLE
the blimb-revive "user is not entitled

### ISSUE THREAD

**Issue by narwhal2749** [LibreVR/Revive#1159]
### Description of the issue

I have oculus home installed as well as steam vr and revive, all latest vversions, I'm playing on a vive.
I injected the climb's .exe into revive and when the game starts ther e is a popup saying user is not entitled

### Technical Information
*Tell us your specs and versions*
  - CPU:8700
  - GPU:1080ti
  - RAM: (amount and DDR#) 16gb 3000mhz
  - OS: win 10
  - Vive 

#### Versions and features
*This issue is about:*
  - Revive Injector
  - SteamVR version (unless Remixed): latest
  - Revive installation version: 1.6.2

### What apps/games are you trying to run?
  - the climb

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  launch the game and wait till the popup appears in the monitor, not in the headset

## Error messages/codes
  - user is not entitled

**Comment by robfrizzy** [comment]
Same issue. Game has been patched and using the injector. The loading screens appear in the headset then they go away and a dialogue box appears on the monitor saying "user is not entitled".

**Comment by MERKinCiRi** [comment]
same issue

**Comment by Valenz68** [comment]
Exact same issue still no fix ?

**Comment by Armada651** [comment]
Works fine for me, try re-installing the Oculus software.

**Comment by gino8080** [comment]
uhmm no other fixes?

**Comment by timdonovanuk** [comment]
Does not work!
