### ISSUE TITLE
Games don't launch from Revive tab (0.6)

### ISSUE THREAD

**Issue by ikillpxls** [LibreVR/Revive#116]
Essentially what happens is I click on the game in the Revive tab, then the "Next Up" at the bottom seems to show it's loading it for a split second but quickly disappears, and then nothing happens. Sometimes instead it just closes the menu screen. Every once in a while Henry (though nothing else from what I can tell) will load up but it might be about a whole minute after I've clicked on it as well as multiple other games in the tab after it. I've actually had this problem since 0.5 but assumed a new version might fix whatever was going on. 

If the context helps: My Oculus installation is not on my C drive while Steam is. Not sure if that could be part of the problem or not.

**Comment by LibreVR** [comment]
Try restarting Steam and then try to start a game from the dashboard. Then post your logs from `%APPDATA%\Revive` here.

**Comment by ikillpxls** [comment]
Sure thing. Is this what you need?

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: H:\Programs\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///H:/Oculus/
Loading assets manifest: file:///h:/Oculus/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/colosseteam-colosse-a-story-in-virtual-reality_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/gunfire-games-llc-chronos_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/iris-vr-technolust_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/moshe-ben-zacharia-the-body-vr-rift_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/oculus-lost_assets.json
Loading assets manifest: file:///h:/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///H:/Oculus/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle colosseteam-colosse-a-story-in-virtual-reality_assets
Loading application manifest: file:///H:/Oculus/Manifests/colosseteam-colosse-a-story-in-virtual-reality.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///H:/Oculus/Manifests/epic-games-showdown.json
Found assets bundle gunfire-games-llc-chronos_assets
Loading application manifest: file:///H:/Oculus/Manifests/gunfire-games-llc-chronos.json
Found assets bundle iris-vr-technolust_assets
Loading application manifest: file:///H:/Oculus/Manifests/iris-vr-technolust.json
Found assets bundle moshe-ben-zacharia-the-body-vr-rift_assets
Loading application manifest: file:///H:/Oculus/Manifests/moshe-ben-zacharia-the-body-vr-rift.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///H:/Oculus/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///H:/Oculus/Manifests/oculus-farlands.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///H:/Oculus/Manifests/oculus-henry.json
Found assets bundle oculus-lost_assets
Loading application manifest: file:///H:/Oculus/Manifests/oculus-lost.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///H:/Oculus/Manifests/playful-luckys-tale.json
Found application baobab-studios-invasion-for-rift
Found application colosseteam-colosse-a-story-in-virtual-reality
Found application epic-games-showdown
Found application gunfire-games-llc-chronos
Found application iris-vr-technolust
Found application moshe-ben-zacharia-the-body-vr-rift
Found application oculus-dreamdeck
Found application oculus-farlands
Found application oculus-henry
Found application oculus-lost
Found application playful-luckys-tale
Launching application: gunfire-games-llc-chronos
Launching application: gunfire-games-llc-chronos
Failed to launch application: revive.app.gunfire-games-llc-chronos ()
Launching application: gunfire-games-llc-chronos
Failed to launch application: revive.app.gunfire-games-llc-chronos ()

**Comment by LibreVR** [comment]
Actually, I need the other one, the ReviveInjector log.

**Comment by ikillpxls** [comment]
Gotcha:

> Launched injector with: H:\Programs\Revive\Revive\ReviveInjector_x64.exe /base "Software/gunfire-games-llc-chronos/Chronos/Binaries/Win64/Chronos-Win64-Shipping.exe"
> Creating process: H:\Oculus\Software\gunfire-games-llc-chronos\Chronos\Binaries\Win64\Chronos-Win64-Shipping.exe
> Failed to create process
>

**Comment by LibreVR** [comment]
Well that's a clear error. Where exactly is chronos installed on your PC? Is it in a folder called `H:\Oculus\OculusGames`?

**Comment by ikillpxls** [comment]
Yeah, All my Oculus games are in: "H:\Oculus\Software"

**Comment by LibreVR** [comment]
So you can confirm that `H:\Oculus\Software\gunfire-games-llc-chronos\Chronos\Binaries\Win64\Chronos-Win64-Shipping.exe` does actually exist?

**Comment by ikillpxls** [comment]
Correct. It used to work with the Injector but fails the entitlement check when I try it that way now.

**Comment by LibreVR** [comment]
You're using the latest version of the injector?

**Comment by ikillpxls** [comment]
Correct. Just to clarify, when I use the older one (ReviveInjector), I get the entitlement check failure. When I use the newer one (ReviveInjector_x86 or ReviveInjectorx64), it just fails. To be clear though I only tried the injector since I couldn't get it working in the HMD menu.

**Comment by LibreVR** [comment]
Can you try using the `ReviveInjector_x64` on `H:\Oculus\Software\gunfire-games-llc-chronos\Chronos\Binaries\Win64\Chronos-Win64-Shipping.exe` and then send me the ReviveInjector log?

**Comment by ledbetdr** [comment]
I have what seems to be a similar error when I try to launch from the Revive tab:

> Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe"
Creating process: E:\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x295374d0
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x295374d0
Failed to wait for LoadLibrary to exit

When I attempt to run manually from powershell:

`.\ReviveInjector_x64.exe 'E:\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe`

It works fine (output from terminal):

> Launched injector with: "E:\Revive\Revive\ReviveInjector_x64.exe" E:\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
Creating process: E:\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
Injecting DLL: E:\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x295374d0
Injecting DLL: E:\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x295374d0
Injected dlls succesfully

**Comment by jdshaf** [comment]
I have the same problem trying both Henry and Lucky's Tale and get the same "Failed to wait for LoadLibrary to exit" as @ledbetdr. Also was able to run successfully from powershell.

**Comment by LibreVR** [comment]
That's strange, sounds like a permissions problem.

**Comment by ledbetdr** [comment]
Ran steam as administrator. Worked.

**Comment by LibreVR** [comment]
Interesting, I have UAC on, but haven't experienced those problems. Since the game is opened as a child process the injector should have all the permissions it needs.

What version of Windows are you running?

**Comment by ledbetdr** [comment]
Windows 10.

**Comment by LibreVR** [comment]
Same here, I don't have to run as admin.

**Comment by ledbetdr** [comment]
I can't think of anything special about my windows 10 installation. If there are any tests you want me to run just let me know.

**Comment by LibreVR** [comment]
I'll keep this ticket open, I'll look at this problem once I have time to work on bug fixes again.

**Comment by ikillpxls** [comment]
> Can you try using the ReviveInjector_x64 on H:\Oculus\Software\gunfire-games-llc-chronos\Chronos\Binaries\Win64\Chronos-Win64-Shipping.exe and then send me the ReviveInjector log?

Sorry. Finally got a chance to get back to this and actually got it working. As suggested above, I restarted Steam as administrator and Chronos now runs fine from the tab. I double checked the Injector (x64) as well and set it to run as administrator and now that works as well (totally forgot to set that).

**Comment by LibreVR** [comment]
It shouldn't require you to run as admin, but it wouldn't surprise me either since Revive is a patching things in-memory.

I'll close this issue for now, but I'll keep an eye out for similar problems.
