### ISSUE TITLE
All Oculus games stutter in Revive and don't see controllers AND zoomed in through Remixed

### ISSUE THREAD

**Issue by elnarvideo** [LibreVR/Revive#1160]
I couldn't find any issue with all the same symptoms as I have so I decided to open a new one.

### Description of the issue

Ever since SteamVR updated to 1.1.3 and now 1.1.4 it completely broke every single Oculus experience I own. All of them worked amazingly before on my Lenovo Explorer and Odyssey+, including Robo Recall, Arktika 1, Chronos, Fruit Ninja and many others. Now all of them stutter heavily on any setting. I always used Revive for those and everything worked just fine until that Steam update. I tried Remixed many times but I always got zoomed in image, like Im looking through the magnifying glass. And I got that in all games, although to a different level. So now that Revive doesnt work for me, Im trying to make Remixed work and now in addition to zoomed in image, it also doesnt see my controllers thus not letting me to run the game (game screen always says controllers not detected). Alt-Tabbing doesnt help and I've tried combinations of all possible betas, official releases, updating to 1809, downgrading to old Revive, etc. Nothing seems to help at all. Its very frustrating because I have so many games there that I used to regularly play and I cant play them anymore. Hope there is a solution somewhere out there.

### Technical Information
*Tell us your specs and versions*
  - CPU: 2014 MacBook Pro with i7 4870HQ 2.5 GHz 
  - GPU: EVGA 1060 6gb FTW+ through eGPU
  - RAM: 16 GB 1600 MHz DDR3L SDRAM 
  - OS: Windows 10 - 1809
  - Odyssey+

#### Versions and features
*This issue is about:*
  - Revive and Remixed
  - SteamVR version (unless Remixed): 1.1.4 and tried all latest betas as well
  - Revive installation version: 1.6.2 and tried previous builds as well

#### What is the last working version before this issue first came up?
  - Revive installation: 1.6.0 was working fine with older SteamVR
  - SteamVR (unless remixed): 1.1.2

### What apps/games are you trying to run?
  - Robo Recall
  - Arktika.1
  - Chronos
  - Fruit Ninja
  - First Contact

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  I'm not sure what specific steps you could take. Everything worked and now it doesnt. Im getting good framerate, it only stutters when I turn or move. And as of the Remixed, I always had the zoomed in issue since the first day I tried it and all I did was install and launch. It was like that on every single version. Controllers not connecting appeared recently but I cant figure out what exactly triggered it. It cant be steamvr because the issue is only present in Remixed. Im also getting the orange image in Dreamdeck, which appeared recently as well and I know some other people have that issue and its also a connectivity thing.

## Error messages/codes
  - No codes. Just messages that controllers are not connected. Each game has their own wording.

**Comment by Armada651** [comment]
I made a change in the latest version (1.6.3) that could potentially fix the controller detection issue in Remixed.

**Comment by jonnypanic** [comment]
I tried Lucky's Tale through Remixed on 1.6.3, and still don't have motion controllers. Works great otherwise. In Revive I get the controllers but poor performance. Unfortunately many other games get a fatal error when loading through remixed.

**Comment by Armada651** [comment]
Fixed the stutter in the pre-release and replaced Remixed with ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
