### ISSUE TITLE
Oculus software update 1.34 support

### ISSUE THREAD

**Issue by tobliug** [LibreVR/Revive#1162]
Hi,
Looks like since the last oculus soft update (~1.34), revive is no more working.
I have some "User not entitled" errors at game launch. (red matter / arktika.1)
Any clue on it ?
Thx

**Comment by Arpeggio72** [comment]
@tobliug 

I had the same issue - I had to turn off the Beta/Test option in the Oculus Software so it reverted me back to the working version.

**Comment by tobliug** [comment]
Unfortunately, I switched off beta, waiting for the Oculus software to install the previous 1.33 version, 
but I still have the "User not entitled" error....

**Comment by tobliug** [comment]
ok, So as expected..... official 1.34 version of oculus is now out, and revive is no more working at all.....
Either app crash or not entitled error. Any plan for a 1.34 oculus support ?

**Comment by Armada651** [comment]
There is no publicly available 1.34 SDK yet for Revive to support. It's highly unlikely third-party games are already using it.

**Comment by Armada651** [comment]
FYI if you want to check what the latest SDK version is you can do it here: https://developer.oculus.com/downloads/package/oculus-sdk-for-windows/
