### ISSUE TITLE
Please Add Touch to Move (without swipe) mode.

### ISSUE THREAD

**Issue by thefrozncity** [LibreVR/Revive#1166]
Hello, 
I want to have the revive work just like as robo revive.
I need touch to move without swipe. can you add this feature?
I'm afraid if I bothering you, but I really need this feature.
please allow this if possible.

Go to the ReadMe for installation instructions.
-------------------------------------------------------------------------------------------------------------
Corrected controller angles to match the gun grips
Removed deadzone on touchpad, you can now teleport without having to swipe the pad <- I need this
Added Hybrid/Toggle grip options using the same settings from Revive
Fixed application menu button not activating the menu
Added an installer to simplify mod installation
---------------------------------------------------------------------------------------------------------------

setting 0 value of deadzone on openvr advanced setting just doesn't work.
I could use just robo revive but there are problems.
1. It only work with robo recall (I want to play from other suns and marvel power united too) 
2. it has problem with robo recall free locomotion mod v5/v6
(v5 - playable but falling down after to the ground completing mission so I cannot click the go back to
hub menu, need to restart game)
(v6 - stuck into the ground everytime I teleport, openvr advanced setting height adjustment just doesn't
work because the issue persists everytime I teleport. so it is unplayable)

Kindly help me. Thank you in advance.

**Comment by Armada651** [comment]
You can do this in the SteamVR input settings, just unbind the thumb_recenter action.

**Comment by thefrozncity** [comment]
Would you kindly tell me where I can unbind thumb_recenter action ? Thank you in advance :)
