### ISSUE TITLE
Oculus Medium will not start.

### ISSUE THREAD

**Issue by miscmouse** [LibreVR/Revive#1167]
# Revive - Oculus Medium Won't Start

### Description of the issue
Oculus Medium won't start up. Tries to, and closes after 2 seconds. I followed the steps on your site, and am able to get First Contact and Touch Basics to work. Went to shut off smoothing, but it's not enabled on ATI Graphics cards. Uninstalled and reinstalled SteamVR, Revive, Oculus, and Medium today and still no luck. 

### Technical Information

  - CPU: AMD Ryzen 5 1400 Quad Core Processor - 8CPUs, 3.2GHz
  - GPU: Radeon RX 580
  - RAM: (amount and DDR#) 8GB DDR5 
  - OS: Windows 10 64Bit
  - Vive / WMR (/ Odyssey) / Other device -Using the HTC Vive

#### Versions and features
  - Revive / Remixed / Injector or Patcher: ReVive
  - SteamVR version (unless Remixed): 1.2.7
  - Revive installation version: 1.6.2

#### What is the last working version before this issue first came up?
  - Revive installation: Never. New.
  - SteamVR (unless remixed): Never. New

### What apps/games are you trying to run?
  - Oculus Medium

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. In Steam VR, click the menu button, click revive, click oculus medium.

## Error messages/codes
  - None that I see. I believe I was getting the generic one from Oculus until I told it to restart, now nothing.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Dragoboss** [comment]
Can you try with 1.6.3 and get back to me?

**Comment by miscmouse** [comment]
Works! Thank you guys!

**Comment by Dragoboss** [comment]
Perfect, closing.
