### ISSUE TITLE
Drt.exe Entry Point Not Found

### ISSUE THREAD

**Issue by KuukkeliReal** [LibreVR/Revive#1169]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU: i7-7700k
  - GPU: GTX 1060 6gb
  - RAM: (amount and DDR#) 16gb DDR4
  - OS: Windows 10
  - Vive / WMR (/ Odyssey) / Other device : HTC Vive
#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher: Injector
  - SteamVR version (unless Remixed): 1.2.7
  - Revive installation version: 1.6.2

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Dirt rally

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_ 
  1. Just trying to run the game

## Error messages/codes
  - The procedure entry point VR_InitInternal2 could not be
 located in the dynamic link library
E:\Steamlibrary\Steamapps\common\DiRT
Rally\x86\LibRevive32_dll.
![capture](https://user-images.githubusercontent.com/47057643/51787590-9d495180-217c-11e9-82f5-90a137d6fb84.JPG)
![capture](https://user-images.githubusercontent.com/47057643/51787595-a63a2300-217c-11e9-8bec-311e507a08b1.JPG)

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Looks like you're trying to use the injection **and** patching function at the same time. Do not do this, if you patched Dirt Rally simply start it from the Steam library.
