### ISSUE TITLE
Games are not working from WMR and Revive directly, Still need Steam VR

### ISSUE THREAD

**Issue by khaled3m** [LibreVR/Revive#1170]
Revive 1.6.2, games are not opening in WMR without Steam VR. If i try to run a game directly from Revive it will try to open the game but will through me back to WMR app right away 

  - CPU: Intel Core I9
  - GPU: Geforce 1080 TI
  - RAM: (amount and DDR#) 4 Modules 32GB
  - OS: Windows 10 Pro
  - WMR Oddyessy

**Comment by Dragoboss** [comment]
I'll need some more information (which you could've known if you'd just followed the format).
What games are they, what are the reproduction steps, what versions are you using, etc.
Please check-out the format and add additional information accordingly.

**Comment by khaled3m** [comment]
First please accept my apology for not sticking to the template i thought this information is enough. please find below all the details you requested. 

### Description of the issue
Revive 1.6.2 stated not to run revive from Steam Dashboard but run the games directly from Revive but games are not opening in WMR without Steam VR. If i try to run a game directly from Revive it will try to open the game but will through me back to WMR app right away
everything works and games are playable if i open them through Ateam VR and Revive tab in the dashboard. 
but it won't run with Revive only. 

### Technical Information
*Tell us your specs and versions*
  - CPU: Intel Core i9
  - GPU: Geforce GTX 1080 TI
  - RAM: (amount and DDR#) 4 Modules 32 GB
  - OS: Windows 10 Pro
  - Vive / WMR (/ Odyssey) / Other device: WMR Oddyessy

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher: Revive 1.6.2
  - SteamVR version (unless Remixed): 
  - Revive installation version: 1.6.2

#### What is the last working version before this issue first came up?
this is the first time to install it

### What apps/games are you trying to run?
  - Robo Recall, Batman Arkham, & other games

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Install Oculus Software
  2. Install Revive 1.6.2
  3. Install Steam VR
  4. Open WMR and try to run games from revive Right away. (won't run)
  5. Open Steam VR within WMR, click on Revive from the dashboard and run games. (it will run)

## Error messages/codes
  - None. it just through you back to WMR

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Dragoboss** [comment]
Sorry for the somewhat later response.

From what I gathered the games you listed are all built on Unreal Engine 4.
UE4 still causes problems for Remixed. The way Unreal handles the boot up of the game causes a frame skip for the WMR portal which is why it instantly crashes.

This is an issue that the Dev is aware of and working towards a work around for in the future. I cannot give an ETA at this point.

**Comment by khaled3m** [comment]
Thank You Dragoboss, at least i still can run the games through Steam VR and Reive. thank you for the support.
