### ISSUE TITLE
USB Joystick no seen within Injected PC app in Revive while streaming with ALVR (using Gear VR and Samsung S9)

### ISSUE THREAD

**Issue by dpluigi** [LibreVR/Revive#1171]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
Hi,
Thank you for putting together such a stable and efficient tool. I am enthusiastic about VR and AR and exploring the potential of my Gear VR mobile headset while waiting for Oculus Quest to be releas3ed. Hopefully, ALVR will be able to interface with Quest and make it a wireless Rift little brother so that the powers of PC and graphics card can be leveraged too.
Back to joystick issue:
With ALVR (version 2.3.1) I managed to get the graphics streaming to my Gear VR mobile headset fitted with a Samsung S9 over wifi. The Revive (version 1.6.2.0) inject function works well and Soaring flight simulator Condor 2.exe (version 2.0.5) starts apparently normally ( http://www.condorsoaring.com/ ).
My issue is that after starting Condor with Revive, the USB joysticks do not show up in Condor/Input menu, hence to operational while in flight sim).
Note that the joystick USB devices are detected by Windows and can be calibrated by Joy.cpl and listed in Steam/Controller.
Do you have any idea what needs to be done so that once Condor is started in VR mode I get the joystick (and second joystick for my rudder pedals) recognized and operational?
Is this a known issue with Revive?

Thank you in advance for your help,
Donat

### Technical Information
*Tell us your specs and versions*
  - CPU: I-7700K
  - GPU: RTX 2080
  - RAM: (amount and DDR#) 2x16Gb DDR4 3000MHz
  - OS: Windows 10 (64bt) Pro
  - Vive / WMR (/ Odyssey) / Other device:  Gear VR fitted with Samsung S9

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher:  Revive 1.6.2.0 / Injector Version
  - SteamVR version (unless Remixed):
  - Revive installation version: 1.6.2.0

#### What is the last working version before this issue first came up?
  - Revive installation:  NA (First time user)
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Condor 2 VFR (Version 2.0.5) Soaring flight simulator   http://www.condorsoaring.com/

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_
  1.  Launch ALVR on PC and on Gear VR/Phone in Oculus
  2.  Inject Condor.exe by right click on Revive
  3.  Condor starts and streams in Mobile Gear VR headset but not joystick response.
 Joysticks are present and detected by Windows (and can be calibrated using joy.cpl), and are also seen in Steam.

## Error messages/codes
  - None

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
This is not a supported setup.
