### ISSUE TITLE
Dirt Rally will not start with SteamVR open

### ISSUE THREAD

**Issue by hexadecatrienoic** [LibreVR/Revive#1173]
# Revive/Remixed Report Template
### Description of the issue
Dirt Rally will not start with SteamVR open. 

### Technical Information
*Tell us your specs and versions*
  - CPU: i7-6700K
  - GPU: Asus GTX1080
  - RAM: 32GB DDR4
  - OS: Win10
  - Vive

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher
  - SteamVR version (unless Remixed): Latest beta, Current content BuildID: 3513907
  - Revive installation version: 1.6.3.0

#### What is the last working version before this issue first came up?
  - Revive installation: Never worked. First installed version: 1.6.3.0
  - SteamVR (unless remixed): Never worked.

### What apps/games are you trying to run?
  - Dirt Rally

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Install Oculus Home, skip first time setup.
  2. Install Revive.
  3. Run SteamVR. Patch Dirt Rally from revive system tray icon.
  4. Turn off Desktop Game theater in game properties.
  5. Try to run the game. Steam error - "game does not support VR, will run on desktop instead". Game does not launch.
  6. Copy `LibOVRP2{32,64}_1.dll` from `C:\Program Files\Oculus\Support\oculus-runtime` to the Dirt Rally root.
  7. Repeat step 5.
  8. Reboot computer. Repeat step 5.

## Error messages/codes
  - none, game does not start.

**Comment by Armada651** [comment]
Can you try 6.2 or 6.1?

**Comment by hexadecatrienoic** [comment]
Will do this evening.

**Comment by hexadecatrienoic** [comment]
Works on 6.2.

**Comment by SnowTelevision** [comment]
Hello, my Dirt Rally also crashed on 6.3, it just shows the boot logo then crashed with no error messages.

I then tried 6.2 and it doesn't crash anymore, however it doesn't show in VR either, just show on my monitor.

**Comment by AndyLevesque** [comment]
Same symptoms here as well with Samsung Odyssey, however the issue does not occur when launching Dirt Rally with Steam VR turned off. When launching Dirt Rally with Steam VR turned off, Steam VR launches and then proceed to load into the game without issue (6.3). 

After the successful launch, I then attempted to launch Dirt Rally again with Steam VR active at the time of Dirt Rally launch. Again, I received the logo of Dirt Rally followed by the game closing without ever launching in VR. I then closed Steam VR, launched Dirt Rally, and then it loaded into VR without issue.

**Comment by SnowTelevision** [comment]
> Same symptoms here as well with Samsung Odyssey, however the issue does not occur when launching Dirt Rally with Steam VR turned off. When launching Dirt Rally with Steam VR turned off, Steam VR launches and then proceed to load into the game without issue (6.3).
> 
> After the successful launch, I then attempted to launch Dirt Rally again with Steam VR active at the time of Dirt Rally launch. Again, I received the logo of Dirt Rally followed by the game closing without ever launching in VR. I then closed Steam VR, launched Dirt Rally, and then it loaded into VR without issue.

Wow, I'll definitely try that.

**Comment by AndyLevesque** [comment]
> > Same symptoms here as well with Samsung Odyssey, however the issue does not occur when launching Dirt Rally with Steam VR turned off. When launching Dirt Rally with Steam VR turned off, Steam VR launches and then proceed to load into the game without issue (6.3).
> > After the successful launch, I then attempted to launch Dirt Rally again with Steam VR active at the time of Dirt Rally launch. Again, I received the logo of Dirt Rally followed by the game closing without ever launching in VR. I then closed Steam VR, launched Dirt Rally, and then it loaded into VR without issue.
> 
> Wow, I'll definitely try that.

Any luck? I'm getting feedback on Reddit that this approach has solved their issues.

**Comment by SnowTelevision** [comment]
> > > Same symptoms here as well with Samsung Odyssey, however the issue does not occur when launching Dirt Rally with Steam VR turned off. When launching Dirt Rally with Steam VR turned off, Steam VR launches and then proceed to load into the game without issue (6.3).
> > > After the successful launch, I then attempted to launch Dirt Rally again with Steam VR active at the time of Dirt Rally launch. Again, I received the logo of Dirt Rally followed by the game closing without ever launching in VR. I then closed Steam VR, launched Dirt Rally, and then it loaded into VR without issue.
> > 
> > 
> > Wow, I'll definitely try that.
> 
> Any luck? I'm getting feedback on Reddit that this approach has solved their issues.

Sorry, didn't get a chance to try it yet, will let you know how it goes as soon as try it.

**Comment by Armada651** [comment]
> Same symptoms here as well with Samsung Odyssey, however the issue does not occur when launching Dirt Rally with Steam VR turned off. When launching Dirt Rally with Steam VR turned off, Steam VR launches and then proceed to load into the game without issue (6.3).

Oops, looks like I made a very rookie mistake. In my attempt to support Remixed in version 6.3 I accidentally forced Revive to be used only when SteamVR is **not** running and Remixed while it is running. Obviously this should've been the other way around, will be fixed in 6.4.
