### ISSUE TITLE
Marvel powers united VR - Any chance to support the game?

### ISSUE THREAD

**Issue by Sl1ckR1ck** [LibreVR/Revive#1175]
I was wondering if there was any chance of it ever being supported?

I am not even able to start the game as it tells:
"You have a pending hardware issue that is preventing you from entering VR. Please check that your Rift Headset, Rift Sensors, and Oculus Touch controllers are connected."

**Comment by xeno3d** [comment]
I just played this game with  no problem using the latest version of Revive
