### ISSUE TITLE
Vridge Drifting issue with oculus games

### ISSUE THREAD

**Issue by ayhamo** [LibreVR/Revive#1177]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
The issue is simple, i'am playing with steam vr using Vridge, it work's flawlessly even with cracked games, but when i tried Oculus games using Revive , i had a drifting issue and head movement LAG which makes the game unplayable, using latest update of nivida update tho
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU: core i3 2100
  - GPU: gtx 750 Ti
  - RAM: (8)
  - OS: w10
  - VRidge with gear vr

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version(latest update)
  - Revive installation version: latest version

#### What is the last working version before this issue first came up?
  - Revive installation: i used it 4 or 5 month's ago and didn't have any problem...
  - SteamVR working and no issuse, as issue is with oclus games

### What apps/games are you trying to run?
  - tried 3  games with same issuse" first touch, lost, and jug space"

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  well i googled and didn't got any result tho...
i wish if u can guys help me

## Error messages/codes
  -  None

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Vridge isn't supported by Revive, do not request support for it here.

> it works flawlessly even with cracked games

Stop using my work with pirated games please.
