### ISSUE TITLE
Dirt Rally on Pimax 5k+ has a lag to tracking?

### ISSUE THREAD

**Issue by ilimo** [LibreVR/Revive#1178]
Has anyone else had a similar issue where the Pimax 5k+ worked but the tracking was lagging behind. It was smooth, but if i moved my head, the image swayed, and it causes me a massive headache. Basically the tracking is delayed for some reason.

**Comment by jonnypanic** [comment]
Yeah, I get this too on a Dell Visor. I think it started around the time Steam did their terrible motionsmoothing update. Have you tried downgrading SteamVR as mentioned on the other thread? I will attempt it later to see if it fixes this issue.

**Comment by ilimo** [comment]
> Yeah, I get this too on a Dell Visor. I think it started around the time Steam did their terrible motionsmoothing update. Have you tried downgrading SteamVR as mentioned on the other thread? I will attempt it later to see if it fixes this issue.

Yes i downgraded and it worked with SteamVR 1.1.3

**Comment by nels45** [comment]
how to downgrade steam VR?

**Comment by ilimo** [comment]
> how to downgrade steam VR?

Go to this link:" https://github.com/LibreVR/Revive/issues/1121
In the comments you'll see a link to SteamVR 1.1.3 to downgrade

**Comment by flowerdealer** [comment]
Does anyone know if this will ever get fixed? How can we get the SteamVR devs on track with this?

**Comment by ilimo** [comment]
> Does anyone know if this will ever get fixed? How can we get the SteamVR devs on track with this?

I wish they would realize that since the addition of Motion Smoothing, removing Asynch Repro options, etc., they broke alot of stuff in the process.

Using 1.1.3 is perfectly fine for me so far.

**Comment by nels45** [comment]
yep it woks fine with the 1.1.3 
thanks

**Comment by wickedmatt** [comment]
Having the same problem with Samsung Odyssey+, everything seems wobbly and jittery in oculus games, reverting back to steam 1.1.3 fixes it... damn.

**Comment by Armada651** [comment]
Lag issues have been fixed for most games in the latest pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
