### ISSUE TITLE
Robinson: The Journey in Remixed - missing overlay hints and zoomed FOV

### ISSUE THREAD

**Issue by otichy** [LibreVR/Revive#1179]
Hi,

with the new version of Revive, the controllers in Robinson: The Journey started working for me via Remixed (thanks!). The game runs very well with all settings maxed and supersampling at 1.5, which is great considering my HW (kudoz!) and the fact that it is only smooth via SteamVR on lowest settings and supers at 0.9.

The remaining problems seem to be the weirdly zoomed FOV (same for other games and issues) and what seems especially strange to me - missing game hints (windows with controller tips/help). These are visible on screen mirror or via SteamVR, but are missing in Remixed. Maybe this is connected with the zoom issue?

### Technical Information
*Tell us your specs and versions*
  - CPU: i7-3820
  - GPU: GTX 970
  - RAM: (amount and DDR#) 32
  - OS: Win 10 1803
  - Vive / WMR (/ Odyssey) / Other device: WMR Lenovo Explorer

#### Versions and features
*This issue is about:*
  - Remixed
  - Revive installation version: 1.6.3.

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
