### ISSUE TITLE
Is there a way to block revive auto start with steam vr?

### ISSUE THREAD

**Issue by LaryBenji** [LibreVR/Revive#1183]
Hi there,

Thanks for your work.

My question is not very an issue.

I just want Revive to don't auto launch when I use Steam VR. Is it possible?

**Comment by Armada651** [comment]
What exactly do you want to turn off? The dashboard?

**Comment by Armada651** [comment]
I think you might be referring to the Oculus Store opening with SteamVR? That's not caused by Revive, that's just something that SteamVR does when the Oculus software is installed. You can uninstall Revive and it will still happen.

**Comment by LaryBenji** [comment]
Yes in fact I was reffering to this and I was thinking that it's the Revive app who open the Oculus Store.
Ok thanks for your response. If it's a steam vr problem, I think I'll go ask them on their forum.
