### ISSUE TITLE
revive not recognizing all oculus games

### ISSUE THREAD

**Issue by cmdjr15** [LibreVR/Revive#1184]
Hello I originally had an oculus and sold it after a year or so due to the minium room to use it. I recently brought a vive and found out about revive so i downloaded it. I downloaded the oculus games that i wanted. At first it showed the games but i had not yet played any of them. Out of the blue most of the games stopped showing up. Most are oculus exclusives. Does it matter if i brought the games in oculus store and not on steam? I tried uninstalling revive. I am going to try and uninstall and reinstall oculus and the games and see what I get. Was hoping you might have some ideas,

Charlie D

**Comment by Armada651** [comment]
Sounds like you may be using multiple Oculus libraries, Revive will only detect games out of your default library right now.
