### ISSUE TITLE
Lone Echo and PiTool 1.0.0.109 (maybe?)

### ISSUE THREAD

**Issue by Hoshi82** [LibreVR/Revive#1188]
### Description of the issue
I am not sure if the issue is caused by revive, Lone Echo or newest PiTool. Lone Echo worked with Pitool 1.0.0.91 and revive without a problem on my pimax 5k+. No around 1-2 month have passed and I wanted to jump back into lone echo. When I start the game it shows on the desktop mirror just fine and head/handtracking seems to work. But inside the hmd I stuck at the steamvr loading area where most of the time the game icon with a loading animation shows up. But no game icon and waiting for 10 minutes didn't work. Steamvr window also says "unresponsive" but in desktop the game is running fine.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7-4770k @3,5ghz
  - GPU: GTX 1080
  - RAM: 16 DDR3
  - OS:  Win10 Pro 64bit (1809)
  - Pimax 5k+

#### Versions and features
*This issue is about:*
 - I really don't know since it could be caused from any of the listed possibilities.

#### What is the last working version before this issue first came up?
  - Revive installation: should have been 1.6.2
  - SteamVR (unless remixed): I don't know when the latest update was but the version around Dec/Jan

### What apps/games are you trying to run?
  - Lone Echo

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Starting Lighthouses
  2. connecting Pimax
  3. restart PiServiceLauncher.exe in windows services so lighthouse get tracked
  4. starting SteamVR
  5. SteamVR dashboard selecting Lone Echo and start game
  6. Stuck in SteamVR loading area but game is running on the desktop mirror with sound/music.

## Error messages/codes
  - steamvr statur "unresponsive exe file"

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Hoshi82** [comment]
Installed newest PiTool Beta Version 1.0.0.111 and reinstalled Lone Echo. Don't know if reinstall was neccesary but its working again.

**Comment by digicraft63** [comment]
I have the exact same problem only difference is I am using Pimax 8k HMD and the RTX 2080.
