### ISSUE TITLE
The Climb only renders for the left eye on WMR Remixed

### ISSUE THREAD

**Issue by otichy** [LibreVR/Revive#1189]
Since Revive 1.63, Climb only appears on the left eye display on my WMR with Remixed. The right eye screen is blank, but it shows the boundary when activated and it briefly shows the app when I exit to WMR Home and jump back in. I tried downgrading to 1.6.2 which fixed the problem, but the the head is rendered too close to the hands (everything zoomed as reported elsewhere). Updating to 1.6.3 caused the right eye issue again.
Via SteamVR with Revive 1.6.2 & .3, both eyes render fine, the head position is fine, but the performance is terrible, as reported elsewhere (interestingly, while there is a lot of frames dropped and the whole experience is extremely choppy, the GPU load is only ca. 50%).

Technical Information
Tell us your specs and versions

CPU: i7-3820
GPU: GTX 970
RAM: (amount and DDR#) 32
OS: Win 10 1803
Vive / WMR (/ Odyssey) / Other device: WMR Lenovo Explorer
Versions and features
This issue is about:

Remixed
Revive installation version: 1.6.3.

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
