### ISSUE TITLE
Non-store oculus games

### ISSUE THREAD

**Issue by SngLol** [LibreVR/Revive#1190]
### Description of the issue
When I add a 3rd party oculus game to my oculus library, Revive won't add it to it's own library thus prevents me from playing it.

### Technical Information
*Tell us your specs and versions*
  - CPU: Intel i7-6700K
  - GPU: ASUS GTX1070 DUAL
  - RAM: 16GB DDR4
  - OS: Windows 10
  - Vive

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version:
  - Revive installation version:

#### What is the last working version before this issue first came up?
  - Revive installation: 1.6.4
  - SteamVR (unless remixed): 1.2.10

### What apps/games are you trying to run?
"FreeSaber" - https://paulmario777.itch.io/freesaber-vr

## How to reproduce your issue?
add a 3rd party game to the oculus library

  1. 

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/wiki#standalone-games
