### ISSUE TITLE
PS4 Controller won't work through DS4Windows on Revive

### ISSUE THREAD

**Issue by crobock** [LibreVR/Revive#1192]
### Description of the issue
I downloaded Lucky's Tale, which should allow me to use a PS4 controller using DS4Windows.  The controller can be used in the Mixed Reality Portal, and is reponsive when I hit the PS4 button when Lucky's Tale is open, but Lucky's Tale doesn't respond to any button presses at all.

### Technical Information
*Tell us your specs and versions*
  - CPU: i5
  - GPU: GTX 1050
  - RAM: 8GB DDR3
  - OS: Windows 10
  - Using Lenovo Explorer

#### Versions and features
*This issue is about:*
  - Tried with both Revive through SteamVR, and through Remixed
  - SteamVR version (unless Remixed): 
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
No working version so far

### What apps/games are you trying to run?
  - Lucky's Tale

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  Steps used to open:
1. Connect PS4 controller using USB cable to computer.
2. Open DS4Windows (currently 1.7.1) and allow it to connect to controller.
3. Open Mixed Reality Portal
4. Open Revive Dashboard
5. Open Lucky's Tale in Revive Dashboard

## Error messages/codes
  - No error messages received

**Comment by Armada651** [comment]
This is not something that Revive is responsible for supporting.
