### ISSUE TITLE
WMR controllers not mapped correctly for Echo Arena with Remixed

### ISSUE THREAD

**Issue by cornfzd** [LibreVR/Revive#1195]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
WMR controllers not mapped correctly for Echo Arena with Remixed.  I'm using a Samsung Odyssey with Revive started from Desktop (no Steam).  When I'm in game the performance is great but the controllers map only the thrust to the trackpads, not the boost or the brake.  The left joystick doesn't do anything, while the right only rotates the player.

### Technical Information
*Tell us your specs and versions*
  - CPU: Intel i7-8700k
  - GPU: GTX 1080 
  - RAM: (amount and DDR#) 16GB (8x2)
  - OS: Windows 10 Pro
  - Windows MR - Samsung Odyssey

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Start from Desktop.  Remixed performance was great compared to SteamVR in Echo Arena,.
  - SteamVR version (unless Remixed): n/a 
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
  - Revive installation: I don't know if I tried it before, or I forget.
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Echo Arena

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  Start the WMR Portal
  2.   Start the Revive Desktop  
  3.  Start Echo Arena from menu
  4.  Play and press buttons and notice that you can only do the light thrust from each hand by pressing the trackpads.  

Note: I have a Vive and was using Revive in Steam with no problems.  When I tried Revive with Steam and WMR it was too jumpy.  

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Dragoboss** [comment]
The boost and brake are on the thumbsticks like they should be if you compare it to Oculus touch.

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
