### ISSUE TITLE
I cant get dirt rally to work, but it looks like revive doesn't even support the game?

### ISSUE THREAD

**Issue by R0sc0ep** [LibreVR/Revive#1197]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU:
  - GPU:
  - RAM: (amount and DDR#)
  - OS: 
  - Vive / WMR (/ Odyssey) / Other device

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher
  - SteamVR version (unless Remixed):
  - Revive installation version:

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - 

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. 

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Closing due to lack of information.
