### ISSUE TITLE
Revive not working in WMR

### ISSUE THREAD

**Issue by PauliePeanuts** [LibreVR/Revive#1199]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
I am using an odyssey plus headset with revive.  I downloaded some free apps like google earth and Bigscreens but when using revive the screen is very jittery and wobbly when I move my head.  It feels very unstable and unplayable. 

### Technical Information
*Tell us your specs and versions*
  - CPU: i5 3570k OC to 4.5 gigaherz
  - GPU: Gtx 1070
  - RAM: (amount and DDR#) 16 ddr3
  - OS:  windows 10 pro 
  - Odyssey plus

**Comment by PauliePeanuts** [comment]
I am using the lastest version of revive 1.64 i believe.   also i cannot run it without steam, I get a loading screen with dots but it never goes into the game.

**Comment by krillme** [comment]
Having this problem too with i7-8700k, GTX 1080, 16GB DDR4, Windows 10 Pro, Odyssey (non-plus). Moving my head makes the world wiggle. I've been trying multiple old version of Revive to see if there's one that works but haven't found one yet.

**Comment by wickedmatt** [comment]
Having the same problem with Samsung Odyssey+, everything seems wobbly and jittery in oculus games, reverting back to steam 1.1.3 fixes it... damn.

**Comment by YujieSang** [comment]
> I am using the lastest version of revive 1.64 i believe.   also i cannot run it without steam, I get a loading screen with dots but it never goes into the game.

Same problem. I have Samsung Odyssey+ and newest revive 1.64. I have motion reprojection enabled in both WMR and Steam. For most games, it doesn't load. Some games have 1/2 chance to load, but I have to use my xbox controller instead of WMR controller.

**Comment by Armada651** [comment]
Should be fixed in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
