### ISSUE TITLE
Dream Deck fails to launch under Revive 0.6, Rift Runtime 1.4.0.224996

### ISSUE THREAD

**Issue by DonkeyKong** [LibreVR/Revive#120]
I am having precisely the same issue as I had with Revive v0.52, described here: https://github.com/LibreVR/Revive/issues/102

Of note, I'm now on a new PC since that last error report. Brand new Windows 10 64 bit install. Literally only Steam, Steam VR, a couple Steam games, Oculus Home, and Revive are installed. This is as clean as it possibly gets.

I install Oculus Home, then download Dream Deck, finalize the install of dream deck, install Revivie 0.6,  open SteamVR, the revive tab is there, Dream Deck is there, I click Dream Deck" to launch it and... nothing happens. I'm dropped back into the SteamVR white wireframe void thing and nothing ever opens. My Revive log files say:

> Launching application: oculus-dreamdeck
> Launching application: oculus-dreamdeck
> Failed to launch application: revive.app.oculus-dreamdeck ()
> Launching application: oculus-dreamdeck
> Failed to launch application: revive.app.oculus-dreamdeck ()

And 

> Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe"
> Creating process: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
> Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
> LoadLibrary found at address: 0xaa1874d0
> Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
> LoadLibrary found at address: 0xaa1874d0
> Failed to wait for LoadLibrary to exit

I looked in Event Viewer and saw nothing obvious in there, aside from a ton of OVRServiceLauncher errors, one every 30 seconds that says

> [SetProcessGPUPriorityClass] Target process did not respond in time

But the internet seems to think those are meaningless and happen to people with no problems.

I really want to get this going but moreover I really want to help this project. I am a fairly experienced professional  programmer. If there's no obvious next debugging step I can get the tools to build revive and see what I can do in terms of debugging.

**Comment by LibreVR** [comment]
Try setting `ReviveInjector_x64.exe` to run as admin, that seems to help quite a few people.

**Comment by DonkeyKong** [comment]
Ok, I set `ReviveInjector_x64.exe` to run as admin using the Compatibility properties. For good measure, I did it for all users. Now when I click on Dream Deck in the revive overlay, nothing happens at all. The overlay remains open, I am not dumped back into the white void. I now get the same output in `ReviveOverlay.log` but no output of any kind in `ReviveInjector.log`

**Comment by DonkeyKong** [comment]
I found the following info in `C:\Program Files (x86)\Steam\logs\vrserver.txt`

> Sat May 28 2016 15:43:53.621 - Unable to write app config file to C:\Program Files (x86)\Steam\config\vrappconfig\revive.app.oculus-dreamdeck.vrappconfig
> Sat May 28 2016 15:43:53.622 - Tried to start binary process C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe" (working directory C:\Program Files\Revive\Revive) as app revive.app.oculus-dreamdeck but it failed
> Sat May 28 2016 15:43:56.056 - Unable to write app config file to C:\Program Files (x86)\Steam\config\vrappconfig\revive.app.oculus-dreamdeck.vrappconfig
> Sat May 28 2016 15:43:56.057 - Tried to start binary process C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe" (working directory C:\Program Files\Revive\Revive) as app revive.app.oculus-dreamdeck but it failed

A quick look shows that `revive.app.oculus-dreamdeck.vrappconfig` does exist and has contents similar to all the other vrappconfig files that sit beside it.

> {
>    "autolaunch" : false,
>    "last_launch_time" : "1464464636"
> }

If I delete it, it gets recreated but the message remains about being unable to write to it.

**Comment by LibreVR** [comment]
Ok, disable the run as admin, it probably causes a UAC prompt that Steam can't handle. Try starting Steam itself as admin.

**Comment by DonkeyKong** [comment]
Starting steam as admin worked perfectly. Looks like this whole thing is a permissions issue.

**Comment by LibreVR** [comment]
Seems so, but I have UAC on without any problems. It seems only a part of the user base is affected.
