### ISSUE TITLE
Quill stopped working after the 1.8 update.  (fixed !!! )

### ISSUE THREAD

**Issue by Estebanned** [LibreVR/Revive#1200]
# Revive/Remixed Report Template

### Description of the issue
After the 1.8 update of Quill the application wont start. 

### Technical Information
*Tell us your specs and versions*
  - CPU: Intel Core 6700K 
  - GPU: Geforce GTX 980 Ti
  - RAM: 16GB
  - OS: Windows 10 (64bit)
  - Vive 

#### Versions and features
*This issue is about:*
  - Revive 
 

#### What is the last working version before this issue first came up?
  - Revive installation:  1.6.2.0
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Occulus Quill 1.8

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Update Occulus Quill to version 1.8

## Error messages/codes
  - none

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Latest Revive release is 1.6.4, have you tried that version? https://github.com/LibreVR/Revive/releases/tag/1.6.4

**Comment by Estebanned** [comment]
I just did! Same problem. I had no issues until i updated Quill to Version1.8  
I tested oculus First Contact and Oculus dreamdeck and they are working just fine.

**Comment by Armada651** [comment]
Quill probably updated to the latest Oculus SDK, there will be a new release soon that supports it.

**Comment by Estebanned** [comment]
Thanks for the prompt response @Armada651 ! 
I will wait for the new release! :)

**Comment by vajra28** [comment]
@Armada651  Dear Jules,
I am in a tight deadline and suddenly this QUILL update(1.8) doesnt allow me to run quill anymore thru revive , How early will you guys be able to come up with a release ? Its a tricky situation for our project here.. Thanks !! let me know :)

**Comment by Armada651** [comment]
If you don't mind getting your hands dirty, copy the DLL from this zip file to `C:\Program Files\Revive\Revive\x64`.

[LibRevive64_1.zip](https://github.com/LibreVR/Revive/files/3075399/LibRevive64_1.zip)

**Comment by Estebanned** [comment]
Hello again Jules! Thanks a lot for your time!
I copied  the DLL overwriting the old one and restarted windows. 
Tried to run Quill from revive tab of SteamVR but nothing changed. Command prompt shows some messages and then ... nothing.   This is a snapshot right before command prompt window disappears.
Hope it helps.
 
![Capture_](https://user-images.githubusercontent.com/16559490/56072138-7cb48f00-5d9c-11e9-9f17-c6d3fea8d87c.JPG)

**Comment by stief300** [comment]
same problem here, iam going back to Gravity sketch, but i need quill in the next days:P

**Comment by mshimura** [comment]
Having the same issue with Quill no longer opening on Revive/Remix after the update. Attempted to open with Vive and WMR headset, but application would not launch, and did not provide any error messages, except when I tried to open a saved Quill file directly. Command prompt would also show up then disappear when I tried to launch in SteamVR Home. Also attempted to use a Rift to see if it was an issue with my computer, but Quill was able to open successfully.

**Comment by Armada651** [comment]
I'll have to look more in-depth at this update in that case. In the future if you rely on Revive I very much recommend you disable automatic updates in the Oculus configuration.

**Comment by senderpa** [comment]
i neeed quill again !!!!!
 please update revive !
 i had so much fun learning the ocolus tools with my htc vive ...

**Comment by vajra28** [comment]
@Armada651 
Dear Jules, 
Thanks for the prompt reply,
how early can u come up with a fix? it will help a big deal,
stuck in a bad deadline.
Thanks again waiting for ur response.

**Comment by Armada651** [comment]
I just finished implementing a new injection method that's compatible with Quill, you can try it out by extracting this injector in `C:\Program Files\Revive\Revive`, replace the original. You may also require the updated DLL I posted earlier.

[ReviveInjector_x64.zip](https://github.com/LibreVR/Revive/files/3100169/ReviveInjector_x64.zip)

**Comment by Estebanned** [comment]
You are the man!!!  It works like a charm !!!
Thank you!  <3 <3 <3

**Comment by Armada651** [comment]
Thanks for the feedback, I'll need to test more thoroughly whether this method works with all games before I release it in an update.

@vajra28 Did it work for you as well?

**Comment by stief300** [comment]
hm nope its not working:/ after replacing the reviveInjector also dreamdeck and so on are not working

**Comment by stief300** [comment]
> You are the man!!! It works like a charm !!!
> Thank you! <3 <3 <3

hey man what did u do to make it work,, my steam vr is on 1.3.23.. i replaced everyting like @Armada651  sad,, also tryed newstart and reinstall :/

**Comment by vajra28** [comment]
Dear Jules,
It does work now, but quill takes at least 5-7 attempts ( clicks) to start
...like the screen comes and dissapears but after doing it some 7 times it
starts.
Any fix for that?

**Comment by nicolasvanorten** [comment]
No luck here guys, plus now, with replaced that files, no revive apps are working. :(

**Comment by Estebanned** [comment]
Hello. 
I 'm posting my setup that worked. Hope it helps

I am running windows10-64bit: 
SteamVR: v. 1.3.23
Revive: v. 1.6.4.0  (replacing the 2 files provided by Armada651)
Quill: v. 1.8
Latest geforce drivers:  425.31
Also i 'm running Quill via Revive tab.
Dreamdeck and First contact worked before and after Quill update.
I deactivated automatic updates in Oculus to avoid future problems. 

![Untitledd](https://user-images.githubusercontent.com/16559490/56516493-3e109880-6543-11e9-9498-7006a6150e3c.jpg)

**Comment by angela4ever** [comment]
If you message Quill (https://www.facebook.com/QuillApp/) and give the team your email associated with Oculus Store. they can help downgrade you to Quill-1.7.

**Comment by nicolasvanorten** [comment]
So they have downgraded it to 1.7, its working but if next Revive update can deal with new versions it would be nice, thx guys :)

**Comment by Armada651** [comment]
@vajra28 Does this "multiple tries needed" with the new injector happen for other games as well or just Quill?

**Comment by vajra28** [comment]
I have only three of the occulus apps..
One is the dreamdeck and the other is some robot thingy.. both of them
takes some attempts to start..but "quill" takes the maximum clicks..almost
10-12 hitting..and sometimes lucky that it starts ..sometime it doesn't

:/ Don't know if this information helps..

**Comment by jlazzaro1** [comment]
Specs:
windows10-64bit
Steam VR 1.3.23
Revive 1.6.4.0
Quill version 1.8

Hello, I have attempted to follow the information in this thread to get quill working with revive. I've replaced LibRevive64_1.dll and ReviveInjector_x64.exe  but I get the following messages when I attempt to launch quill:
"Touch controllers not detected. Quill will now close."

"Quill was not able to start
You can find details about the error at:
c:\Users\justen\AppData\Local\Quill\Debug.txt"

"Quill has exited unexpectedly"

The data in the debug.txt file is as follows:
===================================================
date  : 18:21:0 of Fri 9/5/2019

Memory: 26756 / 32661 Megabytes 
CPU   : Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
Units : 8
Speed : 3500 Mhz
OS    : Microsoft Windows 
GPU   : Unkown, NVIDIA GeForce GTX 1070
VRam  : 0 Megabytes 
Screen: 5760 x 1080
Multitouch Integrated: 0
Monitors: 3
===================================================
Quill build ID 2019-04-11_2
Reading config file "C:\Users\Justen\AppData\Local\Quill\\settings.json"...
Gallery updated from default settings. 12 entries.
[-2]  d:\ovrsource2\arvr\apps\quill\quill\exequillapp\src\engine\settings.cpp::Quill::QuillSettings::Write (447) :Could not write config file
4 sound devices
    0: Speakers (Realtek High Definition Audio)
    1: HTC-VIVE (NVIDIA High Definition Audio)
    2: Realtek Digital Output (Realtek High Definition Audio)
    3: Speakers (2- USB Audio Device)
Sound device selected: "Speakers (Realtek High Definition Audio)", requested "Default"
Render Texture Size: 1789, 1988

-------------
It looks like it's trying to write a file on the D drive, which is a disk drive on my system.  

I'm able to launch other oculus software from revive that doesn't use oculus touch controllers, but if I try to launch something that requires touch (robo recall) it gives me an error that it can't find controllers.

**Comment by grifu** [comment]
Same problem here. Quill does not start.
windows10-64bit
Trinus PSVR 1.0
SteamVR 1.4.15
Revive 1.6.4
Quill Version?
I've replaced LibRevive64_1.dll and ReviveInjector_x64.exe

When I launch Quill from revive it open a terminal window and closes after seconds with the fowlling commands
Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" /library "Software\oculus-quill\QuillApp\Quill.exe"
Creating process: C:\Program Files\Oculus\Software\Software\oculus-quill\QuillApp\Quill.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x5f73f220
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x5f73f220

If I launch the quill app directly from program files it returns an error:
You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected.

The debug message is:


Memory: 22022 / 32586 Megabytes 
CPU   : Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Units : 8
Speed : 3600 Mhz
OS    : Microsoft Windows 
GPU   : Unkown, NVIDIA GeForce RTX 2080 Ti
VRam  : 0 Megabytes 
Screen: 4480 x 1440
Multitouch Integrated: 0
Monitors: 2
===================================================
Quill build ID 2019-04-11_2

[-2]  d:\ovrsource2\arvr\apps\quill\quill\exequillapp\src\engine\settings.cpp::Quill::QuillSettings::Write (447) :Could not write config file
[-2]  d:\ovrsource2\arvr\apps\quill\quill\exequillapp\src\engine\mymain.cpp::Quill::MainApp::Init (344) :Cannot do VR

**Comment by krupax** [comment]
I got it working by asking for the downgrade to 1.7, hopefully it'll be able to be patched properly later... does anyone know a way to map the vive wands a bit better for it?

cheers

Chris

**Comment by Armada651** [comment]
Fixed in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0

**Comment by jmeanxt** [comment]
I also had issues with Quill 1.8 on revive 1.6.4, no joy, nothing works on revive after installing pre release 1.7.0.

Anyone have the same issues with pre release?

**Comment by rgferreira** [comment]
> I just finished implementing a new injection method that's compatible with Quill, you can try it out by extracting this injector in `C:\Program Files\Revive\Revive`, replace the original. You may also require the updated DLL I posted earlier.
> 
> [ReviveInjector_x64.zip](https://github.com/LibreVR/Revive/files/3100169/ReviveInjector_x64.zip)

Thank you SO much. By the way I'm enjoying Quill on my brand new Oculus Quest and it runs decently via ALVR. Thanks again.
