### ISSUE TITLE
Zelda - VIVE UE4 Boss Fight

### ISSUE THREAD

**Issue by Noenderx** [LibreVR/Revive#1201]
### Description of the issue
There is a demo of a Zelda Boss Fight for VIVE in UE4 in here  [https://www.youtube.com/watch?v=oHx5SxXvKIg&t=94s](url) and it runs perfectly (good image, high framerate, tracking of headset and controllers, etc), except the distance between eyes is off. I can see and play with one eye, but there is no convergence in the image if I open both. Thus impossible to play in proper VR. I tried injecting and patching with no success. Any help?

### Technical Information
Ryzen 7
RTX 2080
16GB RAM
WINDOWS 10
Odyssey (1st Version)

#### Versions and features
Revive 1.6.4

#### What is the last working version before this issue first came up?
N/A

### What apps/games are you trying to run?
  Zelda Boss Demo. Unreal Engine 4.

## How to reproduce your issue?
Just running the app.

## Error messages/codes
 None

Thanks! 
H

**Comment by Armada651** [comment]
Please use Mixed Reality for SteamVR is a game supports Vive: https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/
