### ISSUE TITLE
oculus-medium cant start

### ISSUE THREAD

**Issue by wenxiao2012** [LibreVR/Revive#1202]
Oculus medium cannot be started
### Description of the issue
click icon in dashboard, nothing happend. 
Check "AppData\Roaming\Revive\ReviveInjector.txt", log like:
`Launched injector with: "E:\game\Revive\Revive\ReviveInjector_x64.exe" /library "Software\oculus-oculus-medium-retail\bin\OculusMedium.exe"
Creating process: E:\Oculus\Software\Software\oculus-oculus-medium-retail\bin\OculusMedium.exe 
Failed to create process`

using inject to run the medium exe file, game can launch. but the vive controller can be traced, and all button don't work. try to config the button mapping, no touch controller function in steam vr input config menu.

switch back to 1.6.3, things no change.

### Technical Information

  - CPU:i7-7700k
  - GPU:1080ti
  - RAM: 16 G
  - OS:win 10 
  - Vive

#### Versions and features

  - Run game with Revive dashboard and Injector
  - SteamVR version: 1.4.2 (1555714041)
  - Revive installation version: 1.6.4 and 1.6.3

#### What is the last working version before this issue first came up?
  - Revive installation: long time ago, may be Q3 of 2018
  - SteamVR: long time ago, may be Q3 of 2018

### What apps/games are you trying to run?
  - medium

## How to reproduce your issue?
  1. run form dash board, failed and nothing happend.
  2. run with injector game can be launched, but cant get vive controller mapping right.
  3. back to 1.6.3 can't fix it.
  4. First CONTACT can launch from dash board, but controller mapping need to config to get it work.

## Error messages/codes
  - Check "AppData\Roaming\Revive\ReviveInjector.txt", log like:
`Launched injector with: "E:\game\Revive\Revive\ReviveInjector_x64.exe" /library "Software\oculus-oculus-medium-retail\bin\OculusMedium.exe"
Creating process: E:\Oculus\Software\Software\oculus-oculus-medium-retail\bin\OculusMedium.exe 
Failed to create process`

## Additional question
When I use the injector to start a non-oc home game, is it not possible to automatically map the vive controller to OC touch?
When I use the injector to start the medium, the game can be started, but the mapping of the vive controller to the oc controller cannot be loaded. The configuration interface of the steam vr is manually used, and there is no way to select the touch function.
Does this mean that revive does not support non-oc home oc games?

**Comment by Armada651** [comment]
Fixed in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
