### ISSUE TITLE
Oculus game head movement lag

### ISSUE THREAD

**Issue by ayhamo** [LibreVR/Revive#1203]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
All the issue is that my head movement is lagging like 1 or 2 seconds after i move my head
despite that steam vr game's like vrchat and many other's work flawlessly, it's only oculus games

also i'am using Riftcat for straming from pc to gear vr with no issue at all like playing alot of games at 60 fps with no problem, even the pc window of the oculus game is working good with no lag it's just my phone screen
i mean it can't be that my S8+ with gear vr is having a less refresh rate or can it be?

### Technical Information
*Tell us your specs and versions*
  - CPU: i5-6500k
  - GPU: GTX 1050 TI
  - RAM: (8)
  - OS: windows 10
  - using Riftcat with S8+ gear vr

#### Versions and features
*This issue is about:*
  - Revive games
  - SteamVR version : latest
  - Revive installation version: latest

#### What is the last working version before this issue first came up?
  - Revive installation: never tried before
  - SteamVR (unless remixed): latest

### What apps/games are you trying to run?
  - Oculus dreamdeck, lost and first contract with all same issue

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. tired to switch to 5ghz internet connection for faster streaming with same issue

## Error messages/codes
  -  not at all

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by VladislavKostin** [comment]
I'm having the same lag in WMR>Steam>Oculus>Lucky's Tale. Other Oculus games have no lag but a lot of stutter (might be worth a separate issue thread). I used to have no problems most of the time with my setup.

**Comment by thehurtmaster** [comment]
Try turning off motion smoothing. Although I don't think Revive is made to work with Riftcat/ALVR, worth a shot though.

**Comment by Armada651** [comment]
Riftcat is not supported, but might be fixed in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
