### ISSUE TITLE
Robo Recall Entitlement not found

### ISSUE THREAD

**Issue by KingLazarus** [LibreVR/Revive#1204]
### Description of the issue
Robo Recall error upon startup, "entitlement not found!"
rather common issue, however neither rebooting (+oculus beta thing), running programs as administrator, disabling antivirus nor injecting the shipping.exe has solved this. used both remixed and revive 

### Technical Information
Using samsung odyssey plus
windows 10
#### Versions and features
Revive 1.6.4
SteamVR 1.3.23

#### What is the last working version before this issue first came up?
none

### What apps/games are you trying to run?
  Robo recall
first contact worked just fine

## How to reproduce your issue?
install oculus home
purchase robo recall
download and install Revive 1.6.4
download and install windows mixed reality for steamvr 
run wmr for steamVR
revive panel in steam overlay, play robo recall
try also remixed
 

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
You either don't own the game or are blocking the Oculus runtime for contacting the servers. If that's not the case try re-installing the Oculus software.
