### ISSUE TITLE
Oculus medium does not work

### ISSUE THREAD

**Issue by Jakkow** [LibreVR/Revive#1206]
### Description of the issue
First Time trying to use revive. Oculus medium is stuck in a white app window forever when launched. Other three application which were automatically installed with oculus home are working properly though. Tried launching Medium while using newest SteamVR as well as newest SteamVR Beta. I've been trying all the basic solutions too like: Steam administrator mode, etc. Tried also replacing the 2 files in Revive installation directory provided by Armada651 (in the last issue post about Quill App not initializing).
 
### Technical Information
*Tell us your specs and versions*
  - CPU: i7-4771
  - GPU: GTX 780 (3gb)
  - RAM: 16
  - OS: win 10
  - Vive

#### Versions and features
*This issue is about:*
  - Revive 1.64
  - SteamVR version: newest
  - Revive installation version: 1.64

#### What is the last working version before this issue first came up?
  - none, my first try

### What apps/games are you trying to run?
  - oculus medium

## How to reproduce your issue?
1. run form dash board, failed and nothing happend.
2. run with revive dashboard
3. medium starts -> white application window appears
4. sometimes after ~~one minute an error pops up: "unable to initialize the oculus rift", but mostly it dit not appears and the application stays white.

## Error messages/codes
  -  "unable to initialize the oculus rift"

**Comment by Armada651** [comment]
Should be fixed in the latest pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
