### ISSUE TITLE
Remixed and WMR Issues

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [LibreVR/Revive#1207]
Issue: When using Remixed, controllers do not work at all, game reports the controllers are not connected, head tracking is superb. 

Solution: Use SteamVR instead, controllers now work in the game, but new issue is now found.

New issue: When using SteamVR, the head tracking is laggy and very weird, almost instantly starts giving me motion sickness.

Solution: Quit trying to play Oculus titles and go back to Steam Games ;)

### Technical Information
*Tell us your specs and versions*
  - CPU: Ryzen1700X
  - GPU: 1080TI
  - RAM: 16GB DDR4
  - OS:  Winblows 10 Pro 64bit
  - Dell WMR

#### Versions and features
*This issue is about:*
  - Both Revive and Remixed
  - SteamVR version (unless Remixed): Beta 1.4.8
  - Revive installation version: Latest Release

#### What is the last working version before this issue first came up?
  - Revive installation: Cant remember, was last year, machine has been wiped and re-setup since
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Robo Recall

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Install everything and run

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
