### ISSUE TITLE
Support for Maere: When Lights Die?

### ISSUE THREAD

**Issue by Picardon** [LibreVR/Revive#121]
Hey there!
So, I was really into this game since it first came out, and I'd love to play it in VR. The problem is, it's only available for the Rift. I tried the Injector on the game, but nothing happens. It just runs normally in the desktop version, and the Vive stays in the main SteamVR homescreen.
I just wanted to inquire if you can take a look into why it doesn't work, and perhaps offer any assistance if possible, and if you have the time for that.
Website of the game: whenlightsdie.com

Thank you!

**Comment by LibreVR** [comment]
Can you give some more information on this game? Was it originally developed for the DK2? Did it ever get updated for the CV1? Does it use the Unity Engine?

**Comment by Picardon** [comment]
From what I remember, it existed since DK1 was released, and got updated as the new versions got out  (DK2 and CV1). So right now it's compatible with CV1, and yes, it uses the Unity Engine.

**Comment by LibreVR** [comment]
Then it really should just work, have you tried any other games with Revive?

**Comment by iamwes** [comment]
I have this game as well and it does not work with revive, I am on version 1.3 . I have Chronos that plays fine.  

Maybe itsome because there is pop up options before the game starts?

Would like to play it on the Vive if you can get it going.

**Comment by LibreVR** [comment]
This game was last updated on the 28th of January 2014, there is no way it has CV1 support as the CV1 was only released in 2016. You can try and add CV1 support yourself though, by download the [latest Unity OVRPlugin from Oculus](https://developer3.oculus.com/downloads/game-engines/1.3.2/OVRPlugin_for_Unity_5/) and putting the correct DLL for your platform in the `Maere - When Lights Die_Data\Plugins\` folder.
