### ISSUE TITLE
Detecting "finger up" for I Expect You to Die?

### ISSUE THREAD

**Issue by abliss86** [LibreVR/Revive#1212]
First off, thank you so much for making this, this is an incredible service for the Vive community.

The problem I'm having is that the tutorial for I Expect You to Die requires you to point at something, which in the Oculus world involves you taking your finger off the index trigger.  As far as I can tell, there's no way to map this to the Vive controller -- you can map touch events, but there's no way to map "not touching".  Do you know if there's any way to map the Vive controller to the Oculus Touch capacitive buttons?

Thanks so much!

**Comment by Armada651** [comment]
If you press the grip button the "not touching" events for the thumb and the index finger will activate. I highly recommend trying the touch tutorial first where it's explained that you should "make a fist and then only lift your index finger".
