### ISSUE TITLE
Games look warped when moving head

### ISSUE THREAD

**Issue by Krylke** [LibreVR/Revive#1213]
Lately, games have been looking strange in the headset (vive) I think the problem first appeared when steam VR implemented motion smoothing. When I move my head I get a strange effect on the world like the world is moving with me. It feels like I'm in a fishbowl or something. I have tried turning off motion smoothing but it does not help. This is not a problem when playing steamVR games.

**Comment by spoonyspork** [comment]
Hey: this is a problem usually only seen with WMR (Vive uses have reported disabling motion smoothing fixes it for them) -- check if the downgrading SteamVR solution found [here](https://github.com/LibreVR/Revive/issues/1121#issuecomment-449627697) works for you? (note where they say to use revive 1.5, that's not needed: works for me under the most recent version of revive)

**Comment by Annomatg** [comment]
I have the same issue with all games expect First Contact. Which version of Steam VR should solve this issue?
For me it looks like the aspect ratio of the view is wrong. Is there a way to modify/force the aspect ratio in Revive?

**Comment by Krylke** [comment]
I tried a game called cityscape VR and it was so warped I almost got motion sick and I never get motion sick. I think this would be a good example to try out to understand what I'm talking about. Interested to hear what you guys think. Something is definitely not right.

**Comment by Krylke** [comment]
so far I have tried installing revive versions as far back as 1.2.1 and nvidia derivers 418.91 but no change. I think is has something to do with steamVR now or some kind of conflict between oculus ASW and valves equivalent. I have tried turning them off though but no difference.

**Comment by Krylke** [comment]
After doing some more research I think the problem I'm having is what they call pupil swim and it happens because of the shape of the lenses. The question is, why am I seeing this now when I didn't see it for almost 3 years (same headset). Has valve accidentally deleted the distortion filter that is supposed to correct this?

**Comment by spoonyspork** [comment]
Krylke -- 1.2.1 is from December 2018... The version last known to work is from October 2018 (not sure of version number). Try using the file from the provided link in my last comment?

**Comment by Krylke** [comment]
I have now noticed this in steamVR games too so its not an issue with revive it seems

**Comment by Annomatg** [comment]
Why was this ticket closed? Is there a replacement for it or is this bug even solved?

**Comment by spoonyspork** [comment]
Annomatg -- the person who filed it realized it wasn't a revive bug so closed it. Try revive 1.7 or use the old version of steamVR linked by me above!
