### ISSUE TITLE
Getting an Error when opening Echo arena, 

### ISSUE THREAD

**Issue by Brindley360** [LibreVR/Revive#1214]
Technical Information
*Tell us your specs and versions*
  - CPU:i7 2600
  - GPU:Gigabyte RTX 2070
  - RAM: (16GB DDR3)
  - OS: Windows 10
  - Vive 

#### Versions and features
*This issue is about:*
  - Revive 
  - SteamVR version (unless Remixed):1.4.15
  - Revive installation version:Not sure, newest version
![Capture](https://user-images.githubusercontent.com/50799146/58047291-bddc5380-7b3f-11e9-91b4-389f01a19698.JPG)

#### What is the last working version before this issue first came up?
  - Revive installation: No idea just got back into VR after GPU upgrade
  - SteamVR (unless remixed):Not sure 

### What apps/games are you trying to run?
  - Echo arena 

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Turn of antivirus.
  2.Start steam VR 
  3. go into the overlay and click play.

## Error messages/codes
  - Failed to initialize Oculus VR session. Please make sure that you have the latest Oculus runtime, and that your headset is properly connected to your pc.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
This is an entitlement error, you need to restart Oculus or your PC.
