### ISSUE TITLE
Only Left Eye works in The Unspoken on Remixed

### ISSUE THREAD

**Issue by Enzdude** [LibreVR/Revive#1215]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
So far this is the only game out of the two oculus games I have with this problem. Running the Unspoken in my headset only outputs through the left eye, and the right eye remains entirely black, except when I approach a boundary.

### Technical Information
*Tell us your specs and versions*
  - CPU: AMD Ryzen 5 2600
  - GPU: EVGA GeForce GTX 1050 Ti (Manual OC)
  - RAM: 16GB DDR4 2400 MHz
  - OS: Windows 10
  - Samsung Odyssey Non-plus

#### Versions and features
*This issue is about:*
  - Remixed
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
  - Revive installation: Somewhere before 1.6.2

### What apps/games are you trying to run?
  - The Unspoken

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Run The Unspoken on Odyssey/WMR Headset

## Error messages/codes
  - N/A

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR, try the pre-release build: https://github.com/LibreVR/Revive/releases/tag/1.7.0
