### ISSUE TITLE
Oculus Medium 2.3 not working

### ISSUE THREAD

**Issue by nicolasvanorten** [LibreVR/Revive#1216]
So Medium is off after its last update. It just doesnt start, no error msges, nothing.
After same problems with Quill, problably Revive needs an update to fight this issues. Plsss guys we need new version :)
Has anyone same problem? Or solution? Thx

### Technical Information
  - CPU: i7 5820K
  - GPU: 1080ti
  - RAM: 32 DDR4
  - OS: WIN10
  - Vive Pro

#### Versions and features
  - Revive installation version: 1.6.4

### What apps/games are you trying to run?
  - Oculus Medium 2.3

**Comment by SquallAlex** [comment]
Yeah. Just signed up to confirm. I get an error though. (Can't find oculus device.) I had a backup of 2.2.5 but didn't backup 3 .json files, so 2.2.5 won't start !!!! Do you have your 2.2.5 version ? Please help if so.

**Comment by SquallAlex** [comment]
I feel like a part of my soul is missing atm...

**Comment by nicolasvanorten** [comment]
Oh geez, that didnt come to my mind to backup files. Okay, that was stupid. I have Medium and Oculus app alredy updated :( 
Yeah, i feel u bro, Im out od Medium AND Quill, so it seems all my projects are stopped for now. F**k :(

**Comment by SquallAlex** [comment]
Thanks for the reply. I feel like revive should have a donation fund or something, so we can pay our respect and love to these wonderful developers ! you have to backup your main medium folder in your library, and some .json files in the manifest folders... I can show you if you want. Here's my first ever sculpt in any 3d app. (glad it was Medium) 

https://www.facebook.com/photo.php?fbid=357281295140276&set=pcb.357281545140251&type=3&theater

**Comment by SquallAlex** [comment]
https://pasteboard.co/IfMGm6l.png

https://pasteboard.co/IfMH3AG.png

**Comment by SquallAlex** [comment]
Hey Nicolas, can we chat on Skype whenever you can ? I have a few pipeline questions related to zbrush and medium.   skype: SquallAlex freelancer

**Comment by nicolasvanorten** [comment]
Well, i have already updated :( So we need to find someone who didnt :D

**Comment by paulferrie** [comment]
that would be me i guess!

**Comment by SquallAlex** [comment]
> that would be me i guess!

You're still on 2.2.5 ? You a GOD to me then :) Any chance of an upload ?

**Comment by paulferrie** [comment]
uploading now, link incoming

**Comment by SquallAlex** [comment]
Hot damn :) you can have my first sculpt :) https://www.facebook.com/530616337464980/photos/a.555013318358615/555013508358596/?type=3&theater No retopo yet. Still new to sculpting, have to learn zbrush zremesher and tools.

**Comment by paulferrie** [comment]
I am at work currently and the upload is interfering with work, but will upload in a few hours!

**Comment by SquallAlex** [comment]
No prob. Don't matter the time.

**Comment by paulferrie** [comment]
I disabled auto-updates in the occulus store as I have been crippled by updates in the past!

**Comment by SquallAlex** [comment]
Yeah. I know. I did my research, and did the same. But I thought, hey, I made a backup... Just that I didn't backup every related file. So when i use the backup, it won't launch from revive. (closes after 2 seconds) and with the injector, it says medium can't start... If possible, could you tell me the steps to retopo a monster sculpt in zbrush ? Best practices ?

**Comment by paulferrie** [comment]
soz bud, above my paygrade, your better off asking that on the facebook group

**Comment by SquallAlex** [comment]
That's ok. Will dive into youtube and other tuts.

**Comment by paulferrie** [comment]
https://drive.google.com/open?id=12In399q8JQexwauPKo3S6m1u0vMYePrc
I could only find two manifest files, (my downloads is empty)

**Comment by SquallAlex** [comment]
One second. Let me show you. i'll download these and report back

**Comment by SquallAlex** [comment]
The other one is in the Oculus app install folder. (default is C: program files...   

https://pasteboard.co/IfMGm6l.png

**Comment by paulferrie** [comment]
weird, my file structure is not like that! 
![a](https://user-images.githubusercontent.com/50913236/58178876-ecbd0b80-7c9e-11e9-9c63-37cb42cc7b99.JPG)

**Comment by paulferrie** [comment]
sokay, got it now!

**Comment by SquallAlex** [comment]
Booting in a few seconds. Excited to see if it's working

**Comment by paulferrie** [comment]
okay, it's there for you

**Comment by SquallAlex** [comment]
Hell YES ! Working !!!!!! thanks a billion my friend :)

**Comment by paulferrie** [comment]
Excellent! we got there together! Happy sculpting!

**Comment by SquallAlex** [comment]
No need for the oculus folder json file apparently. You might be a life saver for the original poster, who hasn't backed up his app folder... Up to you if you wanna upload the whole thing. Sculpting in VR is like a drug. You're my lack of rehab, lol

**Comment by paulferrie** [comment]
I'm in the middle of a huge project, I would cry right now if medium was down! Yeah, just zipping-up the whole thing now

**Comment by SquallAlex** [comment]
Haha. A little bit of paranoia doesn't hurt. you sculpting for production ? Can I ask what company/project ? I'd love to increase my level and be part of something as well.

**Comment by paulferrie** [comment]
Occulus 2.3 for whoever needs: https://drive.google.com/open?id=1Nd57R5TeueqrA4EqBvPx0_mnHcUxjMR5       leave it 1.5hrs (from now before you try to donwload - upload in progress)  happy sculpting!

**Comment by paulferrie** [comment]
I am confident I am not commiting any piracy here right?! haha! assuming you need a strorefront liscence for it to work.  If anyone feels I am breaking a law, please let me know!!

**Comment by SquallAlex** [comment]
> Occulus 2.3 for whoever needs: https://drive.google.com/open?id=1Nd57R5TeueqrA4EqBvPx0_mnHcUxjMR5 leave it 1.5hrs (from now before you try to donwload - upload in progress) happy sculpting!

2.3 ? Not 2.2.5 ? I bought it, and frankly it's nowhere to be found outside oculus and yourself.

**Comment by paulferrie** [comment]
yeah my bad re. versions! I finished work, now slightly high ;)

**Comment by SquallAlex** [comment]
lol. Maybe we can use 2.3 and up someday with revive or Oculus goes cross platform ?

**Comment by paulferrie** [comment]
pah! I doubt they will cross over, and i will forgive them for it cos Medium is so good! Longest I have had to wait for the revive Gods to come to our aid, is probs a few weeks

**Comment by SquallAlex** [comment]
That's good news. Facebooks is like apple in many regards...greedy and hardware perverse.

**Comment by paulferrie** [comment]
upload is stalling :/ dunnoe why...

**Comment by SquallAlex** [comment]
> upload is stalling :/ dunnoe why...

No worries. Will upload now. For anyone in need.

**Comment by SquallAlex** [comment]
For anyone in need of version 2.2.5, until a magical debug happens with revive. Just install in your regular oculus library. You also need the 2 .json files up in these comments. Copy them in the manifests folder.

https://www.dropbox.com/s/1q6ri0fre0pq0oj/oculus-oculus-medium-retail-2.2.5.7z?dl=0

**Comment by Armada651** [comment]
Here's an early build of the updated DLL if you know what to do with it, will ship as part of a Revive update soon:
[LibRevive64_1.zip](https://github.com/LibreVR/Revive/files/3209865/LibRevive64_1.zip)

**Comment by cartoonmonkey** [comment]
OMG thank you for that DLL! Currently enjoying the new update in Revive on WindowsMR Odyssey!

**Comment by nicolasvanorten** [comment]
YEAH, 2.3 with dll is working! :) thx!

**Comment by SquallAlex** [comment]
WOW ! Amazing ! Can we figure out a neural-link digital interface for our brains, so we say goodbye to fleshy reality ? :)

**Comment by marcoleone** [comment]
> Here's an early build of the updated Revive DLL if you know what to do with it, will ship as part of a Revive update soon:
> 
> [LibRevive64_1.zip](https://github.com/LibreVR/Revive/files/3209865/LibRevive64_1.zip)

Thank you so much!
I'm not sure where to put the .dll 
Can anybody explain how to use it?

Thank you!

**Comment by marcoleone** [comment]
I actually figure it out.
I replaced the same file in C:\Program Files\Revive\Revive\x64
The update is working now! Thank you again!

**Comment by ivanmalvin** [comment]
I am having the same issue with Oculus Medium 2.3. Nothing happens when I launch Medium via Revive. Other games I tried from the Oculus store loaded fine via Revive.

I saw the reply with the new .dll and tried that too, unfortunately it does not fix it for me. Still does the same thing as the old dll -- nothing comes up when I try to launch Medium via Revive.

Just updated everything (after not using Revive for a while). Updated Oculus Home, Oculus Medium, auto-updated Revive when it asked me to on launch. And then after that didn't work I tried the new .dll posted in this thread.

**Comment by Calius2020** [comment]
Hi - I have latest oculus store and system processes running, got the latest revive (working with other apps for a while now) I have just got Medium and I had the same issue reported.

So I grabbed the new dll and my results are I get the same cannot find pop up window above the overlay of the app and for a few moments (which I did not get before without the new dll)  when I click ok I can hear the controller sounds and get the apps logo showing then the whole thing drops out.

So ... with all things being the same as everyone else here - and your using the dll do you ever get the oculus not detected popup with that dll anyway or does it just load in? As I still cant seem to nail it and its close but still playing me up.

**Comment by Armada651** [comment]
Fixed in the pre-release build: https://github.com/LibreVR/Revive/releases/tag/1.7.0
