### ISSUE TITLE
Games do not launch via dashboard

### ISSUE THREAD

**Issue by fs0319** [LibreVR/Revive#122]
I can get Dream Deck to run like a standalone game (drag .exe onto `ReviveInjector_x64.exe` and run as admin), but after trying a number of times to run `steam`, `steamvr `and/or `ReviveInjector_x64.exe` as admin I still could not get games to launch via dashboard.

ReviveOverlay log:

> libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: D:\Games\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/ats-kurvet-mythos-of-the-world-axis_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/felix-and-paul-studios-introduction-to-virtual-reality_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-lost_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/woofbertvr-woofbert_assets.json
Found assets bundle ats-kurvet-mythos-of-the-world-axis_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/ats-kurvet-mythos-of-the-world-axis.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/epic-games-showdown.json
Found assets bundle felix-and-paul-studios-introduction-to-virtual-reality_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-farlands.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-henry.json
Found assets bundle oculus-lost_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-lost.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/playful-luckys-tale.json
Found assets bundle woofbertvr-woofbert_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/woofbertvr-woofbert.json
Found application ats-kurvet-mythos-of-the-world-axis
Found application epic-games-showdown
Found application oculus-dreamdeck
Found application oculus-farlands
Found application oculus-oculus-video
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null

And there is no ReviveInjector log output.

I'm on windows 10 btw.

**Comment by LibreVR** [comment]
Seems like the dashboard failed to query the metadata for the application, I should do some better error checking there. Do the games show up on the dashboard?

**Comment by fs0319** [comment]
Yes the games do show up on the dashboard, but when I click on them nothing happens at all.

**Comment by LibreVR** [comment]
Can you send a log that also shows you clicking on the application? It seems like this log only shows the dashboard starting up.

**Comment by fs0319** [comment]
> libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: D:\Games\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/ats-kurvet-mythos-of-the-world-axis_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/felix-and-paul-studios-introduction-to-virtual-reality_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-lost_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/woofbertvr-woofbert_assets.json
Found assets bundle ats-kurvet-mythos-of-the-world-axis_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/ats-kurvet-mythos-of-the-world-axis.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/epic-games-showdown.json
Found assets bundle felix-and-paul-studios-introduction-to-virtual-reality_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-farlands.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-henry.json
Found assets bundle oculus-lost_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-lost.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/playful-luckys-tale.json
Found assets bundle woofbertvr-woofbert_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/woofbertvr-woofbert.json
Found application ats-kurvet-mythos-of-the-world-axis
Found application epic-games-showdown
Found application oculus-dreamdeck
Found application oculus-farlands
Found application oculus-oculus-video
Launching application: oculus-dreamdeck
Failed to launch application: revive.app.oculus-dreamdeck ()
Launching application: oculus-dreamdeck
Failed to launch application: revive.app.oculus-dreamdeck ()
Launching application: oculus-dreamdeck
Failed to launch application: revive.app.oculus-dreamdeck ()
Launching application: oculus-farlands
Failed to launch application: revive.app.oculus-farlands ()
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
Launching application: oculus-dreamdeck
Failed to launch application: revive.app.oculus-dreamdeck ()
Launching application: ats-kurvet-mythos-of-the-world-axis
Failed to launch application: revive.app.ats-kurvet-mythos-of-the-world-axis ()

**Comment by LibreVR** [comment]
You should now also have a Revive Injector log, can you post that one?

**Comment by fs0319** [comment]
Sorry I do not have Revive Injector log, unless I run games as a standalone game, then everything works fine and have this log:

> Launched injector with: "C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe"
Creating process: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
Injecting DLL: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x4ee774d0
Injecting DLL: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x4ee774d0
Injected dlls succesfully

**Comment by LibreVR** [comment]
Ok, then it seems the manifest was not correctly generated. Can you post the contents of `D:\Games\Revive\revive.vrmanifest`?

**Comment by fs0319** [comment]
> {
    "applications": [
        {
            "app_key": "revive.dashboard.overlay",
            "arguments": "",
            "binary_path_windows": "ReviveOverlay.exe",
            "image_path": "revive.png",
            "is_dashboard_overlay": true,
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "description": "Revive Dashboard overlay",
                    "name": "Revive Dashboard"
                }
            }
        }
    ]
}

**Comment by LibreVR** [comment]
Ok, now I understand what's going on, it fails to query the application title and so it doesn't generate the manifest.

Did you try and block the Oculus servers by any chance?

**Comment by fs0319** [comment]
Yes I did. Should I unblock it and reinstall revive?

**Comment by LibreVR** [comment]
You don't need to reinstall, just unblock the Oculus servers and then it should be able to generate the manifests.

The next version will have a fallback in case the Oculus servers are unreachable.

**Comment by fs0319** [comment]
After unblocking Oculus servers and changing steam language to English it works flawlessly, thanks a lot!

**Comment by LibreVR** [comment]
Why did you need to change the language to English?

**Comment by fs0319** [comment]
It might not be related, I mentioned it because I just happened to change the language.
