### ISSUE TITLE
Steam Beta 1.4.18 has restored some of the lst performance on Windows MR?

### ISSUE THREAD

**Issue by flowerdealer** [LibreVR/Revive#1220]
Not an  issue, but just to report that the bad jitter and frame rates have improved a bit after the latest Steam update. It still is not as good as it used to be, but much more playable.

**Comment by ditchmagnet** [comment]
So I assume that the Oct 2018 build of SteamVR is still best for WMR with Revive?

I wonder if the dev has any recommendations. I stop get some jitter with the Oct 2018 build, but it's mostly usable.

**Comment by Armada651** [comment]
The new pre-release build should fix the issue for most games: https://github.com/LibreVR/Revive/releases/tag/1.7.0
