### ISSUE TITLE
The Climb will not fully launch - fake base station support not working

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [LibreVR/Revive#1222]
# Revive/Remixed Report Template

### Description of the issue
I've managed to use Revive with ALVR to play a few games, as well as regular steamvr games.
Now I'm trying to open The Climb with Revive (for the first time), but it is failing to launch with a desktop popup error.

"Hardware issue: Flags: 30c3-HMD(On) Trackers(0)
You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected."

Obviously revive is working fine with other games.  Or else I wouldn't be posting about this specific game.

Anyone else able to launch this specific game successfully with current software versions (not a previous config or versions of the software)?

### Technical Information
OS - Windows 10 - all updates installed
ALVR - latest Oculus Quest alpha 3 and 4 tested (Windows client, Driver and apk)
HMD: Oculus Quest

#### Versions and features
  - Revive
  - SteamVR version (unless Remixed): latest (all updates installed)
  - Revive installation version: latest (1.6.4)

#### What is the last working version before this issue first came up?
  - Revive installation: never tested - new user
  - SteamVR (unless remixed): never tested - new user

### What apps/games are you trying to run?
The Climb

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Try to launch The Climb via Revive

## Error messages/codes
  - "Hardware issue: Flags: 30c3-HMD(On) Trackers(0)
You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected."

**Comment by lvoogdt** [comment]
Simulate a base station is an option in ALVR try it

**Comment by zxsdklfhskyrvk** [comment]
> 
> 
> Simulate a base station is an option in ALVR try it

Great idea!  That did let the game launch!  Then the game went to a screen displaying the various VR components.  They were all green except for the base station.

**Comment by zxsdklfhskyrvk** [comment]
@lvoogdt Does The Climb still work with revive if you are using a Vive or another previously supported HMD?  

I did see you make a potentially related code change about fake sensors 8 days ago,  but I'm wondering if anyone else has confirmed the current playability of The Climb via revive.

FYI,  if that code change is likely to fix my issue, I'd love to know how I could test it.  Not a coder here,  but I could certainly try a beta build.

**Comment by Armada651** [comment]
That change 8 days ago was only for ReviveXR, but I added it to regular Revive as well now.

Try the pre-release build: https://github.com/LibreVR/Revive/releases/tag/1.7.0

**Comment by zxsdklfhskyrvk** [comment]
This did indeed fix the issue!  I can get past that screen now and play the game. Thanks!

**Comment by DarkSiderssss** [comment]
please help me, The Climb doesn't want to run at all, please help🙏🙏🙏🙏🙏
