### ISSUE TITLE
WMR remixed Echo arena thumbsticks deadzone issue

### ISSUE THREAD

**Issue by dzgreka** [LibreVR/Revive#1224]
### Description of the issue
In Remixed Echo arena WMR thumbsticks have a dead zone at the edges of analog sticks, that is, not as a normal dead zone in the center. And for this reason, I basically can’t use sticks, because it’s just inconvenient to move the stick by half the radius

### Technical Information
  - WMR Lenovo explorer

#### Versions and features
  - Remixed
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Echo arena

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
