### ISSUE TITLE
Shadow Point does not work with Revive

### ISSUE THREAD

**Issue by knetterspetter** [LibreVR/Revive#1225]
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 2600K
  - GPU: GTX 1070
  - RAM: (amount and DDR#) 8GB 1866mhz
  - OS: Windows 10
  - Vive 

*This issue is about:*
  - Revive / Remixed / Injector or Patcher
  - SteamVR version: Latest version 
  - Revive installation version: Latest version 

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR (unless remixed):

### What apps/games are you trying to run? Shadow Point 
  - 

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?** Restart Steam. Restart Revive. 

  1. 

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by knetterspetter** [comment]
The game shows in the Revive menu. Also start up, but load everythings becomes white. I see the logo "Shadow Point"than It loads again. And then I't going back to the Steam Home menu. I tried it several times. But nothing works..

**Comment by Krylke** [comment]
I just played this game with revive and it worked great. Make sure you have the latest version of revive

**Comment by knetterspetter** [comment]
Thanks for your reply. I have the latest version of Revive. But it does not work. It starts, it shows the Shadow Point logo, than white screen and it's going back to Home.

**Comment by knetterspetter** [comment]
Hi, you are right. Update to latest version. It Works! The problem was that Revive dashboard says that this Revive is latest version. But that is not correct. So I download laters version manually from github. Thanks!



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Krylke <notifications@github.com>
Datum: 22-06-19 21:47 (GMT+01:00)
Aan: LibreVR/Revive <Revive@noreply.github.com>
Cc: knetterspetter <kennethdewit@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [LibreVR/Revive] Shadow Point does not work with Revive (#1225)


I just played this game with revive and it worked great. Make sure you have the latest version of revive
