### ISSUE TITLE
Dolphin VR right eye lens doesn't work

### ISSUE THREAD

**Issue by DylwinTFTW** [LibreVR/Revive#1226]
### Description of the issue
Whenever I use ReMixed for Dolphin VR, the right eye lens appears gray/black.

### Technical Information
*Tell us your specs and versions*
  - CPU: FX 6300
  - GPU: RX 560
  - RAM: 8 Gigs of DDR3
  - OS: Windows 10
  - WMR (Lenovo Explorer)

#### Versions and features
Remixed

#### What is the last working version before this issue first came up?
  - Revive installation: First installation

### What apps/games are you trying to run?
  - Dolphin VR with Oot First Person Mod

## How to reproduce your issue?
  1. Open WMR
  2. Open Oculus Home
  3. Open Revive
  4. Open Dolphin VR
  5. Inject Dolphin VR
  6. Load a game

## Error messages/codes
  - None

**Comment by Armada651** [comment]
Use SteamVR instead of Revive/Remixed.

**Comment by DylwinTFTW** [comment]
When I use SteamVR, no images show up.

**Comment by Armada651** [comment]
This is not the right place for Dolphin VR support
