### ISSUE TITLE
Oculus Quest: Controllers tilted down about 30º degrees

### ISSUE THREAD

**Issue by JuanluGC** [LibreVR/Revive#1227]
# Revive/Remixed Report Template

### Description of the issue

 When i Play games in my Oculus Quest using revive the virtual controllers are tilting down, When i play a shooter game i must aim in real life higher, about a 30º degrees more.

I can play steamvr games without revive and the tilt is ok.

Its any way to configure the tilting of the virtual controllers?

### Technical Information
*Tell us your specs and versions*
  - CPU: AMD FX 8350
  - GPU: Gforce GTX 960
  - RAM: (amount and DDR#) 16 GB DDR4
  - OS: Windows 10
  - Oculus Quest

#### Versions and features
*This issue is about:*
  - Revive: 1.6.4.0
  - SteamVR version (unless Remixed):
  - Revive installation version:

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR: 1.4.18

### What apps/games are you trying to run?
  - The problems are in all the apps and games that i try to play.

## How to reproduce your issue?

Just connect a oculus quest into a pc with ALVR and try to Play a Oculus game with REVIVE.

**Comment by Armada651** [comment]
You can adjust this with OpenVR-AdvancedSettings. However Revive does not support ALVR.
