### ISSUE TITLE
Every Oculus app crashes on 1.7

### ISSUE THREAD

**Issue by MrBrain27** [LibreVR/Revive#1229]
Since I have updated Revive to 1.7 I can't load any Oculus app, I installed everything that needed (OpenXr and compatibility pack), sent screenshot: 
![SharedScreenshot](https://user-images.githubusercontent.com/16784141/59157978-52413280-8abc-11e9-85f2-75a5fd0d657e.jpg)

CPU: ryzen 5 1500X 
GPU: 1060 3gb 
RAM: 8gb DDR4 
OS: Win 10 x64  (1903)
Lenovo Explorer

**Comment by CommercialCRAP** [comment]
Similar issue, ReviveXR doesn't work at all with 1.7.0
I cannot load any Oculus app through the dashboard: They all crash.
Please find enclosed the dump files when I try to launch lone echo for instance.

**Steps to reproduce:**
First ensure that Steam and Steam VR are not running. I even went in task manager to check that no steam process are running.
Updated windows to 1903, updated all drivers and apps. Installed openXR developer preview. But could not launch any app from the dashboard: they all crashed with some c++ error.

I then added the openXR compatibility pack. Tried again. No more c++ error but it still crashes.

I launch windows updates and Microsoft store updates to make sure that everything is up to date: there is no new update.
I reboot my laptop.
I plug the Samsung Odyssey HMD (the first one not the new plus) on the HDMI port and the USB 3 port.
I turn on the 2 VR hand controllers and they connect to the laptop via Bluetooth.

I put on the HMD to check that the MR portal is running fine and that the boundaries is properly set.

I put out the HMD and with the mouse on the laptop screen I run Revive dashboard 1.7.0 with administrator privileges.

I click on Lone Echo (or any other Oculus app in the dashboard).

I put on immediately the HMD I see that it is going out of the mixed reality portal and turns blue as if the app was launching, but then it immediately goes back to the portal home (the house). This takes about 2 seconds,

And on the desktop I get the error report as attached in screenshot.
![Crash Report Lone Echo](https://user-images.githubusercontent.com/28658946/59158983-6190a200-8af5-11e9-9a67-aea425449a6a.PNG)

Here are the files of the report, the *,xml file is not found in the temp folder.
[loneecho.exeEPC50A46.zip](https://github.com/LibreVR/Revive/files/3269498/loneecho.exeEPC50A46.zip)

See configuration and versions in screenshot attached.
![System](https://user-images.githubusercontent.com/28658946/59158841-1bd2da00-8af3-11e9-8e04-1a27ea9eb1b1.PNG)
![GeForceGTX10170](https://user-images.githubusercontent.com/28658946/59158843-1c6b7080-8af3-11e9-8981-5a35cbaf40fc.PNG)
![Mixed Reality Open XR Runtime](https://user-images.githubusercontent.com/28658946/59158842-1bd2da00-8af3-11e9-903a-87bc8f348688.PNG)
![OdysseyHMDsamsungWMR](https://user-images.githubusercontent.com/28658946/59158844-1c6b7080-8af3-11e9-93c2-91ad6095f759.PNG)
![MixedRealityPortalVersion](https://user-images.githubusercontent.com/28658946/59158845-1c6b7080-8af3-11e9-9807-73ea4849b8fd.PNG)
![OculusVersions](https://user-images.githubusercontent.com/28658946/59159017-2fcc0b00-8af6-11e9-8ffd-15f986af417b.PNG)

**Comment by Armada651** [comment]
Fixed in Revive 1.8.0
