### ISSUE TITLE
Oculus Medium doesn't launch

### ISSUE THREAD

**Issue by Ekrons** [LibreVR/Revive#1231]

**Comment by johnboyjr** [comment]
i get a run time error

**Comment by chailattevrc** [comment]
Just got a fresh install of ReVive (1.7 prerelease) and am getting this when I try to launch: 
![image](https://user-images.githubusercontent.com/51796923/59452779-7c586480-8ddc-11e9-9ccc-e8c5dfa3a197.png) I am using a Vive

**Comment by johnboyjr** [comment]
i still can not get it to launch

**Comment by Armada651** [comment]
Should work in 1.8 now
