### ISSUE TITLE
Failed to intialize libOVR (over ALVR to use Revive)

### ISSUE THREAD

**Issue by chenycallen** [LibreVR/Revive#1232]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
I use **[ALVR](https://github.com/polygraphene/ALVR/?fbclid=IwAR1Wf7pmKkUWPj3KyVL-exQ4TtRz1ZhUOsbX8HwBEKVf2Cy-LMMB_ACkQb4)** to connent **Quest** use **Revive** to open **[Gymnasia](https://www.oculus.com/experiences/rift/2825239134154718)**, but it'll show  "**Failed to intialize libOVR**"
but softewera can run and show"**The sensor is disconnected. Reconnect it to continue**"
![image](https://i.imgur.com/0vQAZoi.png)
![image](https://i.imgur.com/1LUZO52.png)

I try **Oculus Dreamdeck**& **Oculus Demo** that can run normal.

### Technical Information
*Tell us your specs and versions*
  - CPU: I9-8950HK
  - GPU:RTX 2070 Max-Q
  - RAM: 16G (amount and DDR4)
  - OS: Windows10
  - Oculus Quest

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed):1.5.8
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
  -NO

### What apps/games are you trying to run?
  - **[Gymnasia](https://www.oculus.com/experiences/rift/2825239134154718)** 

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  use **ALVR** to connent  **Quest** first, and open **Revive** to run **Gymnasia**

## Error messages/codes
  -  Failed to intialize libOVR.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by chenycallen** [comment]
I install [Version 1.7.0 pre-release](https://github.com/LibreVR/Revive/releases/tag/1.7.0) 
Fix the Failed to intialize libOVR, but there is no picture in QUEST just stay in the STEAM virtual space.

At the same time the computer is running very well without any errors.

![image](https://i.imgur.com/s7CKEla.png)

**Comment by Armada651** [comment]
ALVR is not supported.
