### ISSUE TITLE
Once installed, steamVR games will launch through revive if an oculus mode exists

### ISSUE THREAD

**Issue by kakek** [LibreVR/Revive#1233]
SteamVR games that have an oculus mode seems to favor it over steamVR mode. Even when Revive is closed, launching SteamVR games will open the oculus store and launch revive ( Even for games I don't have on oculus store ).

### Technical Information
*Tell us your specs and versions*
  - I5 3570K:
  - GTX 1060:
  - 16GO DDR3
  - Win10 pro: 
  - WMR (/ HP VR1000) 

#### Versions and features
*This issue is about:*
  - Revive / Remixed
  - SteamVR version 1.5.4:
  - Revive installation version : 1.7

### What apps/games are you trying to run?
On steamVR, beat saber. Or any other games that as an oculus mode.

**Comment by Armada651** [comment]
This is a problem with SteamVR, not with Revive.

**Comment by kakek** [comment]
Thanks for the clarification.
Does this mean that, despite launching the Oculus store, the games are actually running in SteamVR mode ?
Is there anything I can do to prevent this ?
