### ISSUE TITLE
Question more than issue : How is reprojection handled for WMR ?

### ISSUE THREAD

**Issue by kakek** [LibreVR/Revive#1234]
Hello.

Thanks a LOT for the amazing work on Revive, and thinking of WMR users as well !

I have some performance troubles, notably for the climb. You've said before that this specific titles rely heavily on interleaved reprojection, and vive user should make sure to have it activated.

What about WMR users that don't use steamVR ? Can we use any form of repro ? If yes, is there anything we should do to activate it ?

**Comment by Armada651** [comment]
VR is a fast developing tech, what I've said in the past may no longer apply now. Especially comments about reprojection no longer apply after the motion smoothing update.

I recommend WMR users use the new 1.7.0 preview: https://github.com/LibreVR/Revive/releases/tag/1.7.0

Try The Climb with SteamVR, it should preform better.

**Comment by kakek** [comment]
Once again, thanks a lot for your work. Also thanks for taking the time to answer me.
I am using 1.7.0, but I haven't tried it through steamVR, only through OpenXR.
I will try, thank you !
