### ISSUE TITLE
Supersample edge of nowhere in 2019?

### ISSUE THREAD

**Issue by Krylke** [LibreVR/Revive#1235]
I used to be able to supersample this game but now when I tried to play it again in 2019 I can't seem to make it work. Steamvr SS does not work and oculus traytool does not work. I have also tried to put in "pixelsPerDisplayPixel" : 1.5 in the steamvr settings file but uncertain where I should put it, if it even works anymore.

**Comment by cccpphil** [comment]
Same problem for me.

**Comment by Krylke** [comment]
Game now looks great again with 1.7.3 on my index. but flickering still present (old bug)

**Comment by qlyoung** [comment]
Supersampling support has been dropped from Revive for the time being, please see #1269.
