### ISSUE TITLE
Realy bad tracking(Controller/Position) in most games 

### ISSUE THREAD

**Issue by bnevr** [LibreVR/Revive#1236]
All ReVive games have a bad tracking(Controller/Position). Also the game "Robo Recall" have a realy strange look. Its like everyting is zoomed in. All the SteamVr games (for example "Beat Saber") are working fine.

### Technical Information
  - CPU: i7 4690k
  - GPU:GTX 1060 3gb
  - RAM: (8 DDR4)
  - OS: Windows
  -Headset---->MEDION ERAZER® X1000 MR Glasses:

 Version 1.6.4 (all games startet with the revive dashboard)
the game "the climb" didnt work as well(only with steam vr )

Thanks

**Comment by Armada651** [comment]
Use the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
