### ISSUE TITLE
WMR - Revive - Seated position to high

### ISSUE THREAD

**Issue by kakek** [LibreVR/Revive#1237]
Description : 
In some games (Dead and buried, dirt rally, from other suns ) the position is about 2 meter to high, making you float to the ceiling, or above the car for dirt rally. It does not happen in Robo recall and lone echo, making me think it's linked to the seated position environement.
The issue happen only when using revive and steamVR, and not when using Remixed. ( I get better performances with steamVR than with remixed. )
I only found mention of this issue for way older builds.

### Technical Information
  - CPU: I5 3570K
  - GPU: GTX 1060
  - RAM: (amount and DDR#) 16 GO
  - OS: Windows 10 pro
  - WMR HP1000

#### Versions and features
  - Revive
  - SteamVR version : 1.5.9
  - Revive installation version : 1.7.0 Preview

#### What is the last working version before this issue first came up?
No idea, Revive didn't really work before for me. Only started using it with 1.7.0

### What apps/games are you trying to run?
Issue happen in Dead and buried, dirt rally, and from other suns.
It does NOT happen in robo recall and lone echo.

## How to reproduce your issue?
Issue happen every time with one of the 3 mentioned games.

**Comment by Armada651** [comment]
Cannot reproduce in Dirt Rally, try pressing the Ctrl key to recenter.
