### ISSUE TITLE
VADER IMMORTAL / SAMSUNG ODYSSEY+

### ISSUE THREAD

**Issue by roblaplante** [LibreVR/Revive#1238]
Hello !
when you move your head the game is stuttering, but when you stay still there is no shaking.
weird isn't it ??
thanks by advance for helping on that problem !!

**Comment by mapotter99** [comment]
It isn’t just Samsung. 

It happens on Vive, also, when in-game graphics are set to HIGH. 

Until @LibreVR gets an update out, set your graphics to LOW, and the problem should go away.

**Comment by roblaplante** [comment]
> It isn’t just Samsung.
> 
> It happens on Vive, also, when in-game graphics are set to HIGH, even with an i9-9900k, an RTX 2080ti, and 32 GB of ram.
> 
> I believe the technical name for the issue is judder, but I may be wrong.
> 
> Until @LibreVR gets an update out, set your graphics to LOW, and the problem should go away.

working !! sad to play at low settings but i hope it will be fixed.
Thanks you very much !!!

**Comment by mnobrega** [comment]
Same issue over here, definitely some kind of compatibility problem with Revive.

**Comment by Armada651** [comment]
Fixed in release 1.7.3
