### ISSUE TITLE
Journey of the Gods not starting

### ISSUE THREAD

**Issue by tkapis** [LibreVR/Revive#1239]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
Can't start the game in VR

### Technical Information
*Tell us your specs and versions*
  - CPU:
  - GPU:
  - RAM: (amount and DDR#)
  - OS: 
  - Pimax 5K+

#### Versions and features
*This issue is about:*
  - Revive 1.6.4

#### What is the last working version before this issue first came up?
None

### What apps/games are you trying to run?
Journey of the Gods 

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Just try to start the game

## Error messages/codes

![JOTG error](https://user-images.githubusercontent.com/18648079/59930179-a7792e80-9442-11e9-9203-d291db906f17.jpg)

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!
[](url)

**Comment by roblaplante** [comment]
Hello !
Any luck or updates on that matter ?!?
Could buy it but i'm afraid with my O+.....

**Comment by tkapis** [comment]
CrossVR is on vacation at the moment. I hope that he will look at it when he returns net week.

**Comment by olidadda** [comment]
Maybe needs to run at 80hz

**Comment by Angeluz01** [comment]
anyone test it on revive beta 1.7.0.3?

**Comment by tkapis** [comment]
JotG uses Oculus SDK 1.38 and that SDK is implemented in Revive 1.7.0 however you then get a LowLevelFatalError.

CrossVR knows about it and thinks that it is a Revive issue but says that it is not so easy to fix so we just have to wait and see.

**Comment by Angeluz01** [comment]
> 
> 
> JotG uses Oculus SDK 1.38 and that SDK is implemented in Revive 1.7.0 so you enter VR however you then get a LowLevelFatalError.
> 
> CrossVR knows about it and thinks that it is a Revive issue but says that it is not so easy to fix so we just have to wait and see.

k, thanks /CRY

**Comment by Angeluz01** [comment]
JotG works on revive 1.7.1 ?

thankz

**Comment by olidadda** [comment]
So it works? How bad is the screen stuttering?

**Comment by Angeluz01** [comment]
> 
> 
> So it works? How bad is the screen stuttering?

https://youtu.be/Aj5pLFci_i0

its hard to capture on HMD screen...

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
