### ISSUE TITLE
Would it be possible to use this and FreePIE to emulate Razor Hydras on Oculus?

### ISSUE THREAD

**Issue by thedonquixotic** [LibreVR/Revive#124]
FreePIE (found here: https://github.com/AndersMalmgren/FreePIE) help emulates a bunch of controllers, including Razor Hydra and Oculus Touch. 

It doesn't yet support Vive controllers though. But if you used Revive and FreePIE together, would that perhaps daisychain support so that you could use a Vive to play an Oculus application that is built for Razer Hydras? 

I'm an artist/designer and I really want to try out VRClay which was developed by two grad students for Oculus and Razer, but I only have a Vive. This could be really cool though if it worked.

**Comment by LibreVR** [comment]
I don't see why not, but you will have to upgrade the application to at least Oculus SDK 1.3 first.
