### ISSUE TITLE
Vader Immortal / HTC Vive

### ISSUE THREAD

**Issue by CrimEvader** [LibreVR/Revive#1240]
### Description of the issue
*Please provide us with a detailed description of the issue*

I am running Vader Immortal and everything seems to work fine. Sometimes it will go to the loading screen for a couple seconds then resume the game. I have had it completely crash after going to the loading screen several times now. I have reinstalled Revive and still no get occasional crashes. 

### Technical Information
*Tell us your specs and versions*

  - CPU: i5-6500 @ 3.20GHz 4 core
  - GPU: NVIDIA GeForce GTX 1060 6GB
  - RAM: (amount and DDR#): 16 GB DDR4
  - OS: Windows 10 Pro x64 v.10.0.17763
  - **Vive** / WMR (/ Odyssey) / Other device

#### Versions and features
*This issue is about:*

  - Revive
  - SteamVR version (unless Remixed): 1.5.12
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
  - Revive installation: N/A
  - SteamVR (unless remixed): N/A

### What apps/games are you trying to run?
  - Vader Immortal

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. I am running Vader Immortal as normal but changed to low graphics. All other settings are default.
  2. See OpenVR-AdvancedSettings:

[AdvancedSettings.zip](https://github.com/LibreVR/Revive/files/3317471/AdvancedSettings.zip)

## Error messages/codes
  - See crash files.

[CrashReportClient.zip](https://github.com/LibreVR/Revive/files/3317464/CrashReportClient.zip)

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
