### ISSUE TITLE
vader immortal 

### ISSUE THREAD

**Issue by kyle167** [LibreVR/Revive#1242]
# Revive Report Template

### Description of the issue
I play with my frame graph open and my gpu/cpu dont come near to 11ms for repo. they both sit at 5-6 ms (tons of headroom) but the game has crazy tearing stuttering. lowering the setting to LOW helps alittle, but it shouldnt stutter at all. my gpu/cpu arent even close to being stressed

### Technical Information
*Tell us your specs and versions*
  - CPU:i7 8086k (5ghz) 
  - GPU:2080ti
  - RAM: (32 and DDR4 3200mhz)
  - OS: windows 10
  - Vive pro

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher
  - SteamVR version (unless Remixed):
  - Revive installation version:

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - 

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. 

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3

**Comment by Yxonp** [comment]
Still stutters for me on high settings.  Tried Revive 1.7.3 and 1.7.3.5.
HTC Vive
GEFORCE GTX 1070 Ti
Intel 8400
SteamVR beta 1.7.3
