### ISSUE TITLE
Oculus medium not working after newest Update(v2.3.1)

### ISSUE THREAD

**Issue by LiberateV2** [LibreVR/Revive#1244]
Hardcore Oculus medium user here, its pretty much all i use my vive for!
have been using revive for about a year now, and was working great up until lastnight when medium received a performance/feature update(v2.3.1). this happens with every update...wish they gave us the option to not update...but nope! 
but im all to sure the almighty creator of Revive probably knows this issue im talking about, as iv seen it brought up almost every update.
just here to say its happening again!
Please and thanks! -Tyler

(Oculus petition to make VR creation tools multi-platform located below)
https://oculus.uservoice.com/forums/918556-oculus-rift-s-and-rift/suggestions/38060464-make-oculus-medium-and-other-creation-tools-multi

### Technical Information
*Tell us your specs and versions*
  - CPU: 8700k
  - GPU: 2080
  - RAM: 32gb ddr4
  - OS: win10
  - HTC VIVE

#### What is the last working version before this issue first came up?
  - Revive installation: 1.70
  - SteamVR (unless remixed): newest (1.5.15)

### What apps/games are you trying to run?
  Oculus Medium

## How to reproduce your issue?
Trying to start "oculus medium" (v2.3.1)

  1. 

## Error messages/codes
  - "error unable to initialize Oculus rift"

**Comment by paulferrie** [comment]
FYI there is an option is the occulus store to disable auto updates. It's what I do, because I hate Medium downtime too!

**Comment by LiberateV2** [comment]
Damn Guess I didn’t look hard enough, I was gunna firewall it after the next revive update. Lol Thanks bud I shall find that option!

**Comment by routb3d** [comment]
Auto updates got me to! Just when I was going to see Medium through my Valve Index at 144hz for the first time.

**Comment by bungeecow** [comment]
I'm in the same boat, thought I had turned off the updates.
Back to playing with Masterpiece VR I guess....

**Comment by Harpaxia** [comment]
Might be a dumb question, but if we disable updates and then replace the updated files with a backup of the older version will the Oculus Launcher cause a fuss? I saw this listed as compatible last night and bought it not thinking to look here for issues first. My bad, but optimistic there's some solution?

**Comment by bungeecow** [comment]
Do you mean an older version of Medium? If so I believe it will work. Unfortunately I don't have a copy of 2.3.

**Comment by routb3d** [comment]
I’ve been on the Revive + Oculus Medium program since day 1. I don’t think it’s ever been more than a few days before We get a Revive fix for Medium after an update that breaks things. I hope we never reach the end of the road..

**Comment by LiberateV2** [comment]
Imma send revive creator a donation if we get one more revive update! And then I’m shutting down oculus’s online connection through my firewall! And backing everything up!
 Can’t let it happen again lol I’m now starting to take some commissions using “medium” and this is just unacceptable in my eyes!! And I refuse to cave in and buy one of oculus’s shitty HMD’s. 
Absolutely hate their exclusivity bullshit, while SteamVR puts in effort to include rift-s to the party. Dis needs to change!!!

**Comment by PapaShine78** [comment]
Just jumped in to finish a project in medium, first time I've really pushed for it to be part of my workflow and modeling pipeline for work and their update has thrown me completely!! - i should have realized the auto updates where on from a fresh install of Oculus Home app - I would seriously pay for re-vive to keep it current, didn't realize how much i would rely on it!! hope oculus do open the platform officially to other HMD users, feels like a real kick in the teeth, and a very awkward call to my client ahead...

**Comment by LiberateV2** [comment]
Yep been in that exact position!! I would totally pay as well! Haha. Today I actually started a “oculus user-voice” ticket, it’s a far reach but I’m trying! The more votes it gets the more they will listen I hope haha. Please add a vote to it! Might give us a fighting chance of making medium multi platform! 
https://oculus.uservoice.com/forums/918556-oculus-rift-s-and-rift/suggestions/38060464-make-oculus-medium-and-other-creation-tools-multi

**Comment by Nexulan** [comment]
This is very much a issue for me as well, I have been using a Oculus for over 2 years now but wanted a better quality for visuals with a index. Please keep this up to date or any information on maybe getting a older version of medium to work with revive again. Much love to all you VR artists.

**Comment by lassejh** [comment]
Is there any way to go back to the previous update? I have a deadline coming up so I'm really desperate to get into medium

**Comment by 3oxis** [comment]
Oculus....do you see what this is doing to your fans? We get that you've made this an exclusive but you have a very LARGE following from other HMD users. 
I would suggest you fix this. Doesn't really look good on you guys for not paying your community any mind.

**Comment by Jazzneo** [comment]
Hope get fix soon

**Comment by PapaShine78** [comment]
I actually went and bought a second hand rift to get my work sorted as the deadline is looming large - will sell it soon and hopefully get what i paid for it - I used to run a rift (DK1, DK2, CV1) but found the Vive Pro a better system, bar the controllers, but with the new index controllers I bought its perfect for me! The OG Rift CV1 has so many God rays and the tracking is clunky, Very happy to pay more for Medium if i had to buy it again on steam just to avoid this in future (its crazy how cheep it is anyway!) - very grateful to the Revive Devs for making it even possible to use another HMD though!!

**Comment by pgwaldock** [comment]
Same boat here...  and I'd be happy to donate too to keep Revive current!

**Comment by Dudeinparadise** [comment]
Just joining the club. Got a vive this week and I cannot wait to get into Medium. Thanks for everyone's efforts!

**Comment by Armada651** [comment]
Oculus Medium has been updated to use an unreleased SDK (1.38) I've updated the 1.7.0 release to include some stubs for it. Simply re-download and install the pre-release to fix it.

**Comment by PapaShine78** [comment]
Amazing news - really appreciated, and I'm sure many others will be grateful for the update too!

> Oculus Medium has been updated to use an unreleased SDK (1.38) I've updated the 1.7.0 release to include some stubs for it. Simply re-download and install the pre-release to fix it.

**Comment by Harpaxia** [comment]
> Amazing news - really appreciated, and I'm sure many others will be grateful for the update too!

Thank you for notifying us, much thanks!!

**Comment by LiberateV2** [comment]
> 
> 
> Amazing news - really appreciated, and I'm sure many others will be grateful for the update too!
> 
> > Oculus Medium has been updated to use an unreleased SDK (1.38) I've updated the 1.7.0 release to include some stubs for it. Simply re-download and install the pre-release to fix it.

OMG YOUR FUCKING AMAZING!! THANK YOU SOOO MUCH BUD!!! EVERYONE DISABLE YOUR UPDATES NOW!! lol

**Comment by 3oxis** [comment]
Armada 651 YOU SIR ARE A GOD!!!! THANK YOU MY FRIEND!!!!!

**Comment by Armada651** [comment]
Keeping this issue open until Oculus release the 1.38 SDK properly.

**Comment by FlynnAD** [comment]
Oculus Medium STILL doesn't launch! I have the Oculus Medium 2.3.1 auto-update. I downloaded and installed the ReVive 1.70 pre-release, along with the Mixed Reality OpenXR app and the compatibility pack, all as noted on the ReVive download page. When I open the Revive dashboard (ReVive Overlay) and click on Oculus Medium, Windows pops up the error: "The application was unable to start correctly (0xc0000005). Click OK to close the application."
Any help? It seems like others have got it working with the latest Revive patch. Thank you!

**Comment by Armada651** [comment]
@FlynnAD Make sure you have SteamVR running *before* starting a game from the dashboard.

ReviveXR is *not* compatible with Oculus Medium.

**Comment by FlynnAD** [comment]
Hmmph. Still not working. Everything else opens up fine - Windows Mixed Reality Home, Steam VR, Revive SEEMS to be working, but when I click on Oculus Medium from the menu (within the VR headset menu) or on the Oculus Touch tutorial icon on the same menu, those two apps flash instantly as if they were loading, but don't go farther than a flash screen. No error dialog box pops up on Windows desktop anymore either, so I don't have a clue what is wrong.

**Comment by Armada651** [comment]
If you're still running into issues try the latest version.

**Comment by lassejh** [comment]
I'm having the same issue, the injector flashes for a second but nothing else happens, confirmed that it worked when I plugged my friends CV1 in, but not through revive

**Comment by arhidavid** [comment]
Have the same issue, thou it might be due to win 8.
OM version 2.3.3
Revive version 2.0.0.13
