### ISSUE TITLE
Robinson: The Journey on steam defaults to Oculus version with Revive installed 

### ISSUE THREAD

**Issue by TheLordGuardian** [LibreVR/Revive#1245]
### Description of the issue
As stated in the title. When I have Revive isntalled and i want to play Robinson: the Journey steam edition, it starts as an Oculus game althought it should support my Vive natively. 
When I uninstall Revive it runs fine, performance is a tad better and Vive wands works as they should.
Reinstalling Revive did not help. 

### Technical Information
  - CPU: i7-5960X
  - GPU: GTX 1080
  - RAM: 16GB
  - OS: Windows 10
  - original Vive 

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version : 1.5.16
  - Revive installation version: 1.7.0 pre (issue was also present on older version I had installed before)

#### What is the last working version before this issue first came up?
  - Revive installation: unknown
  - SteamVR : unknown

### What apps/games are you trying to run?
  - Robinson: The Journey steam edition

**Comment by Armada651** [comment]
This is not caused by Revive, but rather by having the Oculus software installed.
