### ISSUE TITLE
Revive Crashing When Running Chronos

### ISSUE THREAD

**Issue by uwbandman** [LibreVR/Revive#1246]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
Using ReVive to play Chronos on my HP Reverb WMR headset. It works great but crashes somewhat frequently. I've noticed that the crashes occur most often during loading screens, though about 10-15% of the crashes are just randomly occurring when not in a load screen as well. Probably getting a crash every 20-30 minutes?

### Technical Information
*Tell us your specs and versions*
  - CPU: i5 7600k
  - GPU: RTX2070
  - RAM: 16GB DDR4 3000MHz
  - OS: Windows 10 version 1809
  - Other device: HP Reverb WMR

#### Versions and features
*This issue is about:*
  - Revive?
  - SteamVR version (unless Remixed): 1.5.16
  - Revive installation version: 1.6.4.0

#### What is the last working version before this issue first came up?
  - Revive installation: I've only had this version installed for 2 days, problem occurred immediately
  - SteamVR (unless remixed): Only used Revive with version 1.6.4.0

### What apps/games are you trying to run?
  - Chronos

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Play the game. Wait for the crash. :)

## Error messages/codes
  - It does pop an error message but I didnt write it down.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Fixed  in the latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
