### ISSUE TITLE
Add support for Oculus Home

### ISSUE THREAD

**Issue by kblood** [LibreVR/Revive#1247]
# Revive Report Template

### Description of the issue
I decided to run Oculus Home with the injector to see if it would work. It does... but not very well. The whole display jitters a lot. Otherwise it runs... fine. That is, I can edit the home, take new items from inventory... and such. Looks a bit strange though, not like it looked when I used my Rift. Might be unable to switch to other homes f.ex.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 6700k
  - GPU: 2080ti
  - RAM: 16gb DDR4
  - OS: Win10 64bit
  - Vive / WMR (/ Odyssey) / Other device - Valve Index

#### Versions and features
I am using the Revive Injector 64bit to run Home2-Win64-Shipping.exe directly.

SteamVR version 1.5.16

Revive version 1.6.3

#### What is the last working version before this issue first came up?
 I only just started using Revive, not aware of this ever working.

### What apps/games are you trying to run?
  - Oculus Home

## How to reproduce your issue?
I ran it like this with a custom bat file:
"C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Support\oculus-worlds\Home2\Binaries\Win64\Home2-Win64-Shipping.exe"

## Error messages/codes
  - none

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Kiefy** [comment]
Same on Vive. even though it's in the green on both gpu/cpu.  The judder makes it unusable.

![fpsVR](https://i.imgur.com/HMFFApf.png)

**Comment by Scope666** [comment]
It's the same exact judder as Vader Immortal when it's set to high, if you change the graphics quality to low its smooth... except Home doesn't have a similar setting ... just adding this if it helps to identify  (Unreal Engine version maybe?)

**Comment by Angeluz01** [comment]
work's fine with revive 1.7.3

**Comment by Scope666** [comment]
Nice, I noticed the fix worked on Vader Immortal, so whatever the Oculus SDK "feature" that was causing this stutter must have also fixed Home ... awesome!!!

**Comment by Armada651** [comment]
Since Oculus Home 2 is a lot more functionally complete than Oculus Home 1 I'll add it to the list of default apps so you can open it from the dashboard.

Of course the actual Oculus Dash is still not supported.

**Comment by kblood** [comment]
Awesome :) I do not have the Valve Index right now but might buy it again... but I am using the Oculus Quest with Revive sometimes, so I will test this and then share this news in some of the groups I am in that will likely find this relevant, and yeah, the Oculus Dash part seems pretty heavily integrated with the Oculus SDK stuff that is the backend for the Rift and Rift S, so that is probably not possible to get working. But there are now 3 types of Software for SteamVR that has some similar functionality. I am hoping they might eventually provide a functionality similar to Oculus Dash. So far they each seem lacking. Some of them have some of the important features that Dash has, but they each lack different things, but hoping in time one of them will end up having most the features of Oculus Dash.

**Comment by Armada651** [comment]
Fixed in version 1.8.0: https://github.com/LibreVR/Revive/releases/tag/1.8.0
