### ISSUE TITLE
Repeat of #50 I can't resolve

### ISSUE THREAD

**Issue by wissper** [LibreVR/Revive#125]
Hey guys - I am having the same issue with Chronos as #50 where it's loading - tracking and controllers are all active, but it still says 'please check that your headset and sensor are connected."  I am running VRidge, which might be an issue, but other unreal games have run without any trouble so it doesn't seem like that should be an issue.

I know you guys said you had it working so I know it's possible - I just can't figure out what I'm missing.

I've tried all injectors from 0.5.0 to 0.6.0, I've tried loading the injector from within steam by shortcut, loading it from the win64 directory using drag and drop to reviveinjector_X64.exe, everything seems to work exactly as expected but something is telling the game it's not hooked up properly.

All the files are running with admin privileges that I could think to check.  One side issue, that might be related or it might just be an issue with my setup not being exactly official, lol... when I load revive dashboard, it shows all my games, but I can't scroll through them.  Is this menu limited to the vive motion controllers, or should a gamepad be able to select them?  If the gamepad should work, it's not allowing me to select the game load icons for some reason.

I am running Oculus Runtime 1.4, but I downgraded the service files to 1.3.2.  What version combinations of Revive and Oculus Runtime have been working?  Should I be running all 1.4 Oculus files?

Thanks - any pointers are appreciated.

**Comment by LibreVR** [comment]
VRidge has no tracking sensors, as such games that require positional tracking will not start.
