### ISSUE TITLE
Lone Echo/Echo Arena Issues (Extremely dark/low contrast in ReMixed 1.7)

### ISSUE THREAD

**Issue by xdskyline** [LibreVR/Revive#1250]
### Description of the issue
I've been trying to get Lone Echo and Echo Arena working with various versions of Revive, using both Revive (through SteamVR) and ReMixed (launching straight from Windows). Here's the issues I've run into:

**Revive 1.7**

- Echo Arena (via SteamVR): Extreme judder/visual lag, unplayable.
- Lone Echo (via SteamVR): Extreme judder/visual lag, unplayable.
- Echo Arena (via ReMixed): Seems to run smoothly, but everything is extremely dark, as if the contrast has been turned all the way down. Noticeable even in the menu screen. Unplayable.
- Lone Echo (via ReMixed): Seems to run smoothly, but everything is extremely dark, as if the contrast has been turned all the way down. Noticeable even in the menu screen. Unplayable.

**Revive 1.6.4**

- Echo Arena (via SteamVR): Some framerate issues, but playable on low settings.
- Lone Echo (via SteamVR): Some framerate issues, but playable on low settings.
- Echo Arena (via ReMixed): Runs very smoothly, even when I start turning in-game graphic settings up.
- Lone Echo (via ReMixed): Motion controllers won't register, no motion or inputs.

Ideally, I'd like to use ReMixed 1.7 without SteamVR, and find a fix for the darkness/contrast issue.

Alternatively, I'd like to figure out how to play Lone Echo via ReMixed 1.6.4 and get the controllers working.

### Technical Information
  - CPU: i7 8700k
  - GPU: GTX 970
  - RAM: 16gb DDR4
  - OS: Windows 10, Version 1809
  - HMD: Samsung Odyssey +

#### Versions and features
  - Revive installation version: 1.7 and 1.6.4
  - SteamVR: 1.5.16

### What apps/games are you trying to run?
  - Lone Echo and Echo Arena

## How to reproduce your issue?
Installed the versions of Revive as directed - for 1.7, I installed both the Mixed Reality OpenXR app and the compatibility pack, as I believe I'm on an older version of Windows (newer version reportedly broke a lot of WMR stuff).

Playing Lone Echo through ReMixed 1.6.4: Turned controllers on before starting the game, all hardware marked as detected, tabbed in and out of the game, etc. Still can't get the hands to move.

**Comment by Armada651** [comment]
Try playing it through SteamVR on Revive version 1.8.0
