### ISSUE TITLE
Games just crash before loading.

### ISSUE THREAD

**Issue by nnhood** [LibreVR/Revive#1251]
### Description of the issue
I'm new to using Revive, installed latest Oculus Software, the 7gb download.  Are you supposed to install all the hardware drivers or not?  I have an HTC Vive gen 1.  Rebooted the machine.  Just trying some simple games like Luckeys Tale and Aircar.   Air car loaded 1 time, ever since it appears to be loading in SteamVR with the loading Bars, but if I look at my deskop it just says Game Crash or Failed to find Oculus Rift headset.

### Technical Information
*Tell us your specs and versions*
  - CPU: Core i7 3.2
  - GPU: GeForce GTX 970
  - RAM: 16GB
  - OS: Windows 7 Pro 64 Bit
  - Vive

Versions and features
*This issue is about:*
  - Revive the very latest version.
  - SteamVR version also latest version available
  - Revive installation version: Latest available as of 7/6/19

#### What is the last working version before this issue first came up?
  - Revive installation: 1st attempt never worked
  - SteamVR (unless remixed): 1st attempt never worked

### What apps/games are you trying to run?
  - Dreamdock, AirCar, Luckeys Tale, The Climb

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. I really just followed the instructions on setting up Revive, but something must be causing games to crash.  Its like Revive is not picking up the app before it errors out or tries to find the Oculus hardware.

## Error messages/codes
  - Will post.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by matthiaswatkins** [comment]
I have the same issue on a Win 10 machine. I can post specs when I get home.

**Comment by Armada651** [comment]
Can you try the latest release? https://github.com/LibreVR/Revive/releases/tag/1.7.3
