### ISSUE TITLE
Issues launching Medium after 1.7.0.2 patch

### ISSUE THREAD

**Issue by Harpaxia** [LibreVR/Revive#1252]
Hello! I think I'm just missing something painfully obvious, but I'm exasperated at this point and don't mind the humiliation. Thank you!!

### Technical Information
  - CPU: Intel i7-7700 @ 3.60GHz
  - GPU: Nvidia GeForce GTX 1070
  - RAM: 16GB DRAM
  - OS: Windows 10 64bit
  - HTC Vive

#### Versions and features
  - SteamVR version: 1.5.16
  - Revive installation version: 1.7.0.2

#### What is the last working version before this issue first came up?
  - Revive installation: 1.7.0.2
  - SteamVR: 1.5.16

### What apps/games are you trying to run?
  - Oculus Medium

## How to reproduce your issue?

1. Updated Revive to 1.7.0.2
2. Launched SteamVR + Revive
3. Launched Oculus
4. Attempt to launch Medium through Revive
5. Popup can't initialize Oculus
6. Attempt to inject .exe directly
7. Step 5 again
8. Reset Oculus to Beta, run setup & cancel after it can't find headset
9. Reboot
10. Did steps 3-7 again
11. Reset Oculus to Beta, didn't run setup this time just in case?
12. Did steps 3-7 again
13. Reset Oculus to Beta, didn't run setup again
14. Step 9 again because I forgot the first time
15. Did steps 3-7 again
16. Uninstalled everything
17. Installed latest installers for Oculus and Revive just in case?
18. Reinstalled all of it and did steps 1-15 again
19. It didn't work so I repeated step 9 again because why not?
20. Tried to update SteamVR, no updates
21. Updated graphics card out of anxiety but it probably didn't make a difference
22. Asking for help on GitHub

## Error messages/codes
  - Error: Unable to initialize the Oculus Rift

I know that it's just Medium, because all the other apps from Oculus are working fine in Revive even though I reset the Beta thing and did the Oculus setup stuff, I can't figure out which step I'm steering wrong haha. Thank you!!

**Comment by Armada651** [comment]
Download the 1.7 release again, it was updated to 1.7.0.3 to hotfix the Oculus Medium issue until the Oculus SDK 1.38 is released.
