### ISSUE TITLE
Valve Index Controller

### ISSUE THREAD

**Issue by Alexwijn** [LibreVR/Revive#1253]
### Description of the issue
I just got my new Valve Index Controllers (Knuckles) and tried to play Robo Recall. At first I thought it was working but I was unable to grab the guns.

I also tried mapping it using SteamVR but I'm unable to change anything.

### Technical Information
  - CPU: Intel 8700K
  - GPU: Nvidia Geforce GTX970
  - RAM: 16GB DDR4
  - OS: Windows 10
  - HTC Vive

#### Versions and features
  - Revive: 1.7

### What apps/games are you trying to run?
  - Robo Recall

## How to reproduce your issue?
  1. Open up the game (Robo Recall)
  2. Go to the Gun Range
  3. Try grabbing your weapons

## Error messages/codes
  - None

**Comment by bclindner** [comment]
Can confirm. I can't seem to rebind the grips, either.

**Comment by Armada651** [comment]
Should be fixed in 1.7.2, lots of Index bindings changes.

**Comment by nexxyz** [comment]
Might it be that this is again happening in 2.0.0.13? The grip is recognized as one of the face buttons for some reason.

**Comment by bennygorilla** [comment]
> @CrossVR Might it be that this is again happening in 2.0.0.13? The grip is recognized as one of the face buttons for some reason.

I'm getting the same issue as above in v 2.0.0.13 also.

**Comment by nexxyz** [comment]
Same

**Comment by nexxyz** [comment]
@CrossVR : Should this be reopened?

**Comment by bennygorilla** [comment]
i just uninstalled 2.0.0.13 and reinstalled 1.7.2, and can confirm the grip buttons are working correctly.

**Comment by nexxyz** [comment]
Thanks for the pointer, will do the same for the time being.

**Comment by markthewolf90** [comment]
Perhaps this issue should be re-opened given the circumstances.

**Comment by nexxyz** [comment]
I had success with 1.9.2.

**Comment by markthewolf90** [comment]
Did you take any additional steps to accomplish it? I've tried 2.0, 1.9.2
and 1.72 and they all had the same issue, leading me to originally conclude
that it was an issue with SteamVR's controller mappings.

**Comment by nexxyz** [comment]
Hmm. That is strange. Have you tried uninstalling it via something like Revo Uninstaller and then installing 1.9.2? There might be some remnants of the previously installed version around.
