### ISSUE TITLE
Excessive distortion on Index

### ISSUE THREAD

**Issue by cubiclestorm** [LibreVR/Revive#1255]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU:i7 8700k
  - GPU:Nvidia 2080ti
  - RAM: (amount and DDR#)DDR4 32GB
  - OS: W10
  - Vive / WMR (/ Odyssey) / Other device valve index

#### Versions and features
*This issue is about:*
  - Revive 1.6 and 1.7

#### What is the last working version before this issue first came up?
  - Revive installation: most recent at this date
  - SteamVR (unless remixed):current 

### What apps/games are you trying to run?
  - Robo Recall

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Ran game

## Error messages/codes
  - game had really bad barrel distortion as if the game was simply stretched without increasing fov

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Krylke** [comment]
I have this too but with OG Vive. It has been this way for a long time and nothing has been done to fix it I'm afraid. Don't know if it started happening when Steam VR got updated with motion smoothing or if its something that changed on oculus end. It is super annoying.

**Comment by cubiclestorm** [comment]
1.7.1 resolved the issue
