### ISSUE TITLE
Lucky's Tale

### ISSUE THREAD

**Issue by sim8t3** [LibreVR/Revive#1256]
I have simple question I have Lucky's Tale installed in Revive, I was able to play it once, after the Occulus update I get the "failed entitlement check" I tried everything suggested in the fix nothing worked, but what really is throwing me is that the games list on LibreVR shows the game as "free" but Oculus is showing it's not is the game no longer free with the bundle? If so is that why I'm getting the failed entitlement message?
Thanks

**Comment by Ylluan** [comment]
I have the same problem too. 
Win10 1903
Htc Vive
Steam Vr 1.6.3
Revive 1.6.4 and i also tried 1.7.0.3 the problem persist

**Comment by nfwatsoncom** [comment]
I had same problem.  I don't think I upgraded anything, but I made sure to open Oculus, Steam-VR, Revive apps, SteamVR (which lists VR-related devices available).  I launched Lucky's Tale from Revive and it worked.

**Comment by sim8t3** [comment]
I did that and nothing, I uninstalled it and if I want get it back I will
need to buy it, oh well

**Comment by Ylluan** [comment]
I confirm.   I tried to buy the game from the store and it works again (it didn't even need to be downloaded again).
Probably Lucky's Tale is no longer free, so to play it you have to buy it.
