### ISSUE TITLE
Defector not starting , An instance of this application is already running. (Revive 1.64 )

### ISSUE THREAD

**Issue by Angeluz01** [LibreVR/Revive#1258]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU: 9700K
  - GPU: 2080TI
  - RAM: 32G
  - OS: WIN10 1903
  - Vive Pro

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher
  - SteamVR version 1.6.3
  - Revive installation version: 1.6.4

#### What is the last working version before this issue first came up?
  - Revive installation:
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Defector

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. START THE GAME

## Error messages/codes 
  - An instance of this application is already running.

[IMG]http://i68.tinypic.com/axnryb.jpg[/IMG]

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Shadowmask72** [comment]
Same here. Apparently it loads with 1.7.0

**Comment by Angeluz01** [comment]
it works with the latest beta

**Comment by Shadowmask72** [comment]
> it works with the latest beta

Which one. Is 1.7.0 not the latest? As I said, the game loads but once you get to the headtracking nod it doesn't respond. Maybe then this is an issue with the Quest streaming rather than revive. Can you confirm please.

**Comment by compubrain3000** [comment]
Can also cinfirm that it's not working with Virtual Desktop and Oculus Quest. The game doesn't register the nod at the start of the game.

**Comment by Angeluz01** [comment]
> 
> 
> > it works with the latest beta
> 
> Which one. Is 1.7.0 not the latest? As I said, the game loads but once you get to the headtracking nod it doesn't respond. Maybe then this is an issue with the Quest streaming rather than revive. Can you confirm please.

1.7.0.3
