### ISSUE TITLE
Revive 1.7.0.3 no game works anymore

### ISSUE THREAD

**Issue by Ylluan** [LibreVR/Revive#1259]
### Description of the issue
i tried Revive 1.7 and no games work...  i tried Roborecall, Luky's Tale, Drop Dead, Arktica.1 end many more.  Tried to start from Revive Dashboard and start under steamVr revive pannel: no game starts.  No error messages.  Nothing happens.
I tried to return to revive 1.6.4 (everything worked fine before with this version) but nothing changes. It doesn't even work with this version anymore.

### Technical Information

  - CPU: i7 6700k
  - GPU: gtx 1080
  - RAM: 16gb
  - OS: win 10 pro 1903
  - htc vive with index controllers

#### Versions and features
  - Revive
  - SteamVR version (unless Remixed): 1.6.3
  - Revive installation version: 1.7.0.3 and 1.6.4

#### What is the last working version before this issue first came up?
  - Revive installation:  1.6.4
  - SteamVR (unless remixed):  1.6.3

### What apps/games are you trying to run?
  - DropDead, Roborecall, Atktika.1, Lucky's Tale, Edge of Nowhere, Witchblood

## How to reproduce your issue?
_simply try to start a game, either via dashboard or through the revive panel inside stem vr_

  1. 

## Error messages/codes
  - no error message, simply the games not start

**Comment by elnarvideo** [comment]
I had the same thing happen to me recently. Something with another Steam update that broke it. Reversing steam fixed it for me but its a pain.

**Comment by joeman719** [comment]
SAME PROBLEM PLEASE HELP

**Comment by Angeluz01** [comment]
games work on Vive Pro and Index controllers ,
but i got random cpu time frame stuttering and lagging (9700k@4.6, 32GRam@3000, 2080ti OC,Win10 1903 )

**Comment by joeman719** [comment]
[
![Screenshot [
![Screenshot (7)](https://user-images.githubusercontent.com/28658239/61100210-880e6980-a422-11e9-8701-c270adaee49c.png)
]((6)](https://user-images.githubusercontent.com/28658239/61100200-817ff200-a422-11e9-8158-4bae93339a83.png))
](url)

**Comment by joeman719** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/28658239/61100244-aa07ec00-a422-11e9-93a9-524d189e0a9b.png)
![Screenshot (7)](https://user-images.githubusercontent.com/28658239/61100251-b2602700-a422-11e9-9953-79047d1b799d.png)

**Comment by joeman719** [comment]
still not working. Any ideas? I was really looking forward to this game

**Comment by Ylluan** [comment]
After several tests I managed to make revive 1.6.4 work again.
Roborekall ok
Arktika.1 ok
DropDead starts only in desktop mode.
Defectors obviously doesn't work
Luky's Tale does not work (fail entitlement check)

I tried again with 1.7.0.3 and discovered that turning off Avast, everything works !!
Roborekall ok
Arktika.1 ok
DropDead ok
Defectors ok !!!
Luky's Tale does not work (probably depends on an Oculus update)

**Comment by kblood** [comment]
Avast? Interesting. I am using Avast and I cannot get 1.7.0.x to run anything but 1.6.x seems to work fine.

I will try disabling Avast.

In case it might be relevant. My specs are:
Windows 10 Pro 64bit 1809
Intel i7 6700K
16gb DDR4
RTX 2080Ti
Tried with both Oculus Quest using ALVR and I tried with Valve Index

**Comment by kblood** [comment]
Disabling Avast worked for me as well. It probably means this version is doing something it shouldnt do or should do differently.

**Comment by Armada651** [comment]
> Disabling Avast worked for me as well. It probably means this version is doing something it shouldnt do or should do differently.

Or it means that Avast is just a really bad virus scanner that doesn't care about false positives.

The injection method did change, it just seems like Avast doesn't like this particular injection method even though it doesn't violate any privileges or is any more dangerous than the previous injection method. Avast is being completely arbitrary here.

**Comment by kblood** [comment]
> > Disabling Avast worked for me as well. It probably means this version is doing something it shouldnt do or should do differently.
> 
> Or it means that Avast is just a really bad virus scanner that doesn't care about false positives.
> 
> The injection method did change, it just seems like Avast doesn't like this particular injection method even though it doesn't violate any privileges or is any more dangerous than the previous injection method. Avast is being completely arbitrary here.

Well, then Windows Defender has the same problem.

**Comment by Ylluan** [comment]
with Revive 1.7.1.1 everything works even with Avast turn on.  
Nice job I'm really happy, thanks. :)
Only Lucky's Tale continues to give the Entitlement Check error, probably due to Oculus updates.

**Comment by kblood** [comment]
Awesome :) Good work.
