### ISSUE TITLE
Revive beta 1.7.0.3 extreme cpu 100% frametime stuttering and lagging on Lone Echo

### ISSUE THREAD

**Issue by Angeluz01** [LibreVR/Revive#1261]
HMD : Vive Pro and Index controllers
 i got extreme cpu 100% frametime stuttering and lagging on Lone Echo
(in game setting : Graphic@High, Shadow@medium, Resolution@1.15, SteamSS@80)...
9700k@4.6, 32GRam@3000, 2080ti OC, Win10 1903, Revive Beta 1.7.0.3

**Comment by amstrad** [comment]
Same on WMR (Odyssey+). I installed OpenXR+1.7.0.3 and launching games directly from revive dashboard. The weird part is game runs smooth on any game homescreen, or oculus touch basics, the others get horrible Stuterring/ghosting when in-game..
