### ISSUE TITLE
Lone Echo not showing up in ReVive - Library question

### ISSUE THREAD

**Issue by ntblood** [LibreVR/Revive#1262]
I just re-installed the Oculus application and Lone Echo but it's not showing up in ReVive. 
I have Lone Echo installed at D:\Games\Occulus Games  although the game is actually in D:\Games\Occulus Games\Software. 
I don't really understand the following instructions. I didn't select a different Library location during setup (of the Oculus app I presume). How and where do you set your main library as default?
"If you only see the 4 default games in the Revive dashboard and you have selected a different Library location during setup, then ensure you have you have your main library set as default. Revive will only detect games from the main library."

**Comment by Angeluz01** [comment]
Here you can change the default library location for any new Rift experiences you choose to download.

    Launch the Oculus app from the Start menu, taskbar, or desktop.
    Click Settings.
    Click General.
    Click Edit in the Library Locations section.
    Click the More button next to a library location. ...
    Click Make Default.

**Comment by ntblood** [comment]
Thank you!
