### ISSUE TITLE
Defector - Nod Not Registering In Game V 1.7.0

### ISSUE THREAD

**Issue by Shadowmask72** [LibreVR/Revive#1264]
Using Revive 1.7.0 the Oculus exclusive game Defector loads and allows players to start the first mission. Hand tracking and head movement works fine. However, during a bathroom scene it asks you to nod your head to acknowledge you can hear the operator talking to you. 

For some reason if the player nods their head and even quite violently shakes their head it will not register at all. Players cannot progress any further rendering the game useless.

**Comment by Chewiethrash** [comment]
Any news of what can we make to progress in the game?¡

**Comment by Angeluz01** [comment]
1.7.0.3 works for me . Vive Pro

**Comment by Chewiethrash** [comment]
samsung odyssey, not working, have hp vr1000 and neither. It seems that the problem is with windows mixed reality.

**Comment by angel19841111** [comment]
[https://www.youtube.com/watch?v=EANbNNL--ds&feature=youtu.be](url)
Same, please fix asap, i'd like play with. I tried with 1.6.4, not start the game.

**Comment by Angeluz01** [comment]
> 
> 
> [https://www.youtube.com/watch?v=EANbNNL--ds&feature=youtu.be](url)
> Same, please fix asap, i'd like play with. I tried with 1.6.4, not start the game.

revive beta 1.7.0.3 works

**Comment by angel19841111** [comment]
i use hp vr1000, revive 1.7.0.3a and not work

**Comment by Chewiethrash** [comment]
isnt there anu new update or something?

**Comment by MadSpin** [comment]
On both ALVR and Virtual Desktop on my Quest, the head nod doesn't register. Video also jitters a lot but less on Virtual Desktop. Latest Revive and SteamVR beta, the Index worked with head nod.

**Comment by bigtroy1114** [comment]
I,m using version 1.7.0 on the Index and I can't launch any of my games. I don't see a version 1.7.0.3 to try. Defector is what I need to get working.

**Comment by Angeluz01** [comment]
> 
> 
> I,m using version 1.7.0 on the Index and I can't launch any of my games. I don't see a version 1.7.0.3 to try. Defector is what I need to get working.

https://github.com/LibreVR/Revive/releases/tag/1.7.0

Version 1.7.0 pre-release

@Armada651 Armada651 released this on Jun 5 · 6 commits to master since this release

UPDATE: This release now includes a hotfix for Oculus Medium the version number with the hotfix is 1.7.0.3

**Comment by forestgamer007** [comment]
That pre-release isn't working for me on my vive so I don't know what magic you are using.

**Comment by bigtroy1114** [comment]
I uninstalled Avast from my pc and now it works.

**Comment by pinoepel** [comment]
I have the same problem, using pimax xr and knuckles. the game works, but light jittering as @MadSpin, and no nod registering. also the complete scenes seems a little bit too dark

**Comment by forestgamer007** [comment]
I don't even have Avast so I really don't know what the problem.

**Comment by Shadowmask72** [comment]
Tried using a save file passed the head nod but somehow this gets ignored and a new file is made each time.  Any workaround?

**Comment by appstab-dave** [comment]
Using a save file worked for me... but I had to rename the downloaded save file to the name of the generated save file

**Comment by Jastool** [comment]
I have the latest version 1.7.2.  I just got the game and having the same issue with the head nod.  Can't get past tutorial.  Was this fixed yet or is there something else i am supposed to do to get this to work?

**Comment by Armada651** [comment]
This interaction probably requires the strict poses hack to be turned off. I can't do that yet because pose submission is currently broken in SteamVR. Even if Valve fixes that WMR headsets have never supported pose submission, but those headsets could use OpenXR in the future which does support it.

**Comment by Armada651** [comment]
Just tested Defector on the latest release and I can't reproduce this issue.

**Comment by Jastool** [comment]
Anything I can do to try to capture it for you since you cant recreate?

**Comment by Armada651** [comment]
Have you tried the latest version 1.7.3?

**Comment by Jastool** [comment]
Yeah that is what I was on. 1.7.3 of revive. Couldn't get past nod. Then
tried to play Vader immortal and that crashed right away and wouldn't
load.  Bought both of them recently. Then I down graded to1.7.0.3 because I
read that version worked with vader still. So after I down dreaded I
decided to try defector again. Deleted old profile. Created new game in
different save spot and tried again and still stuck at head nod. Other
people on form were stuck at nod too. That is when I posted asking if there
was fix yet. I am happy to do a recording or log something if you want to
tell me the steps you need to resolve.

**Comment by Jastool** [comment]
Just updated to 1.7.3.5.  Vader Immortal now works.  Tried defector again.  Deleted all profiles.  Started a new game.  Still stuck at head nod.

**Comment by Megaace23** [comment]
I have bought Defector and I have this problem.

The first scene of the game ask you to nod the head. I move my head in every direction, and the game is waiting the nod...

I use Revive 1.9.2.0 and Samsung Odyssey Plus.

**Comment by steve25469** [comment]
Samsung Odyssey. Same problem. :(   I'm guessing there is still no fix for this? Which is confusing, you'd think they wouldn't want to limit their audience. Hopefully I can still get a refund I guess.  That sucks.

**Comment by Cookiezero1989** [comment]
Any news from this or anyone have a save file?

**Comment by Itsmetoo9** [comment]
Same issue HP Reverb G2 with revive 2.1.1

**Comment by superkia75** [comment]
I too have an HP REverb G2 and the latest version, I too can't get past the opening nod.  Also a lot of Judder for some reason.

**Comment by RAGEdemon** [comment]
Same problem. Reverb G2. :(

**Comment by Kyogre** [comment]
> Any news from this or anyone have a save file?

Here are two save files in this archive - [Defector saves.zip](https://github.com/LibreVR/Revive/files/11251712/Defector.saves.zip):
1. after the nod
2. all chapters unlocked, so you can play any mission you want

Unpack desired save file to `C:\Users\<username>\AppData\LocalLow\Twisted Pixel\DFCTR\`
If it doesn't work try renaming my save file to the name of your own save file, but I barely think that there is different naming for different users...

Btw, I completed whole game on my Oculus Quest 2 over wifi, and had no problem with nod or anything else, except annoying jittering.
