### ISSUE TITLE
Oculus Quest through Virtual Desktop, not working with Medium

### ISSUE THREAD

**Issue by Anders0lesen** [LibreVR/Revive#1267]
**# Revive Report Template**
I have done what I can to fill out this form, hope it helps
### Description of the issue
I recently got a Oculus Quest VR headset, and was happy to see I can use all VR titles from SteamVR through Virtual Desktop, if it's sideloaded with the full version from SideQuest.

All the SteamVR titles work fine, but I wanted to get at the PCVR titles from Oculus, so it was suggested to me that Revive could help me.

This work very well for all titles, except Oculus Medium, which was the title I was really looking for. Shadow Point, First Contact, Oculus Dreamdeck and Touch Basics all work just fine.

**TLDR;** Oculus Quest through Virtual Desk, works fine for SteamVR and through Revive all Oculus titles work - Except Oculus Medium.

### Technical Information
  - CPU: Intel Core i7-7700K 4.20 GHz
  - GPU: NVIDIA GeForce GTX 1070
  - RAM: 32Gb DDR4
  - OS: Win10 - 1903
  - Oculus Quest - Connected through Wifi - Virtual Desktop

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed):
  - Revive installation version: 1.6.4.0

#### What is the last working version before this issue first came up?
  - Revive installation: I've never used any other version, where it worked
  - SteamVR (unless remixed):

### What apps/games are you trying to run?
  - Medium

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Start SteamVR
  2. Start Revive
  3. Run Installed Medium, it fails immediately

## Error messages/codes
  - Unable to initialize the Oculus Rift

[Goofy YouTube video of me failing to get it to work](https://www.youtube.com/watch?v=D8COTsSKd-8)

**Comment by avluis** [comment]
I'm assuming you tried this particular [troubleshooting step from the wiki](https://github.com/LibreVR/Revive/wiki/Troubleshooting#im-getting-an-entitlement-error-or-oculus-rift-not-found)?

**Comment by Armada651** [comment]
Oculus Medium requires at least version 1.7, try again with the latest version (1.8)

**Comment by lucasadams86** [comment]
Would this process work for the Oculus Go? or does medium need both controllers to work?

**Comment by lucasadams86** [comment]
were they able to get medium working with virtual desktop?

**Comment by Anders0lesen** [comment]
Absolutely, it's a joy to work with... It works perfectly, through my PC all the way over my Wifi to my Oculus Quest.

That being said, do not get Medium, if you do not have two touch controls as they are absolutely needed, reach out to me on Twitter if you wanna give it a look :) https://twitter.com/Anders0lesen

**Comment by Darktos** [comment]
Hi, 

Are there any updates on the Topic ? 

would absolutely love to use medium on my quest. Maybe it works with the upcomming Oculus Link.

Thanks 

Laurin

**Comment by Anders0lesen** [comment]
> Hi,
> 
> Are there any updates on the Topic ?
> 
> would absolutely love to use medium on my quest. Maybe it works with the upcomming Oculus Link.
> 
> Thanks
> 
> Laurin

It used to work and I was able to make quite a few models with it, but then it stopped working for no good reason, so now I am waiting for Oculus Link to arrive.

Hopefully before the singularity that has been hastened by Carmack.

P.S. I for one welcome our new robotics overlords
