### ISSUE TITLE
Echo VR not launching after new update to game

### ISSUE THREAD

**Issue by SmexiBilzo** [LibreVR/Revive#1268]
### Description of the issue
Echo VR not launching after update to game on 18/07/2019 
Other Oculus games still work (Tried Robo Recall and Lone Echo)

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 4790k
  - GPU: GTX 1070
  - RAM: 16gb ddr3
  - OS: Win 10 Pro 1903
  - Vive with Index controllers

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version): Beta 1.6.6
  - Revive installation version: 1.6.4.0

#### What is the last working version before this issue first came up?
  - Revive installation: Same version it was Echo VR's recent update
  - SteamVR (unless remixed): Same version it was Echo VR's recent update

### What apps/games are you trying to run?
  - Echo VR
Other Oculus games like Robo Recall and Lone Echo still work

## How to reproduce your issue?

  1. Launch Echo VR via Revive Dashboard
  2. See that it fails to launch

## Error messages/codes
  - Failed to initialize Oculus VR session. Please make sure that you have the latest Oculus Runtime, and that your headset is properly connected to your PC

![](https://i.gyazo.com/a2e2a24be2917999fa4ac6d0cc420d89.png)

**Comment by danmalloy** [comment]
Same exact issue here. Using Vive and everything worked fine until the EchoVR update.

**Comment by SmexiBilzo** [comment]
Looks like it works with the Revive 1.7 preview.
