### ISSUE TITLE
Xbox 360 controller doesn't work inside revive tab

### ISSUE THREAD

**Issue by fazo96** [LibreVR/Revive#127]
I can use my controller fine in the Steam tab from SteamVR, but inside the revive tab it just doesn't work, nothing happens and I can't select a game, so I can't play the free Oculus Home games I downloaded. maybe I'm missing something

**Comment by LibreVR** [comment]
You didn't miss anything, controllers are not yet supported in the Revive tab. I simply haven't had time for that yet. The Revive dashboard is a separate application from SteamVR so I also need to handle the controller myself, though I can possibly also get some controller information from OpenVR.

**Comment by fazo96** [comment]
Oh sorry! Since Oculus Home games are all played with a classic controller it didn't cross my mind that I'd need to use the vive controllers.

**Comment by LibreVR** [comment]
Actually, a lot of games use the Oculus Remote, which you can use your Vive Controller for. But yeah, gamepad support should definitely be added in the next version.

**Comment by nalf3in** [comment]
But if we just have a xbox 360, is there currently a way to start a vr game ?

**Comment by LibreVR** [comment]
Yes that is a workaround, Revive also adds the games to SteamVR itself. But since you don't have Vive controllers I'm assuming you're not using a Vive headset?

**Comment by nalf3in** [comment]
Exactly I do not own a Vive headset (a little bit too expensive for me now ). I'm using my phone connected by usb with the riftcat app to emulate the vive headset. The result isn't perfect (It's difficult to read in the big screen virtual reality on steam) but it is good enough for me until I get the money.

**Comment by LibreVR** [comment]
Well, you're free to do so, but I hope you understand that that's not a use case I can support. So please do note in your comment that you are using Riftcat/VRidge when reporting an issue.

**Comment by nalf3in** [comment]
I understand, it's just that I thought that it was a general issue not completely related to the headset I'm using (maybe I'm wrong ) and I wanted to provide the answers to others that don't have/can't use the steam controller for whatever reason. Anyway thanks a lot for this software that works flawlessly (at least for me) at playing rift games !

**Comment by LibreVR** [comment]
Doesn't matter, always note the headset, it could break unexpected ways and it would waste a lot of time if I assumed you are using a Vive headset.

**Comment by Kenwhite23** [comment]
So out of curiosity, I use the OSVR SteamVR plugin. So for all intents and purposes as far as SteamVR goes It sees me as having Just a Vive Headset.

I dont have any compatible motion controllers atm, so Being able to Use the 360 controller in the vive menu would be a huuuuuuuge help.  In the meantime, is there an alternate way to launch these games manually? and do you have a guess as to when the xbox controller might be supported?

**Comment by LibreVR** [comment]
All games that are detected by Revive are also added to your Steam library. So you can just use the SteamVR tab which does support your controller.

**Comment by Malcolm-d1g** [comment]
I follow the steps but when I tried to open the revive tab by pressing home button with my 360  controller  , it won't luanch ... I'm using my phone method with rift cat , please help

**Comment by nalf3in** [comment]
Make sure you aren't and windows 10 and simply triggering the windows
game's menu. Press the xbox button on your controller while on your desktop
(no vr ) and if the game's menu appear, you will have to disable it.

**Comment by LibreVR** [comment]
Latest version of Revive supports controllers in the Revive Dashboard.
