### ISSUE TITLE
Defector: flickering immage with revive 1.7.1.1

### ISSUE THREAD

**Issue by Ylluan** [LibreVR/Revive#1272]
### Description of the issue
flickering immage when i look around.  Only on Defector. Other games like Arktica.1, Dropdead and Roborecall work fine.

### Technical Information
*Tell us your specs and versions*
  
    CPU: i7 6700k
    GPU: gtx 1080
    RAM: 16gb
    OS: win 10 pro 1903
    htc vive with index controllers

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed): 1.6.7
  - Revive installation version: 1.7.1.1

#### What is the last working version before this issue first came up?
  - Revive installation: 1.7.0.3
  - SteamVR (unless remixed): 1.6.7

### What apps/games are you trying to run?
  - Defector

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  just run the game and look around

## Error messages/codes
  - nothing

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Angeluz01** [comment]
vive pro doesnt have any flickering problem

**Comment by appstab-dave** [comment]
I have the same issue with WMR headset

**Comment by mena99** [comment]
well i have the same problem , i've started issue #1287  
have anyone found a solution to it ?
iam using samsung odyssey ..

**Comment by Ylluan** [comment]
For me, Defector run well only with revive v1.7.0.3, but i have to turn off Avast.

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
