### ISSUE TITLE
Journey of the Gods with ReviveVR 1.7.1.1 - smooth in the preview window but shuttering in the HMD...

### ISSUE THREAD

**Issue by Angeluz01** [LibreVR/Revive#1274]
- CPU: 9700k
  - GPU: 2080ti
  - RAM: 32
  - OS: Win10 1903
  - Vive Pro
  - Revive 1.7.1.1

### What apps/games are you trying to run?
  - Journey of the Gods 

## How to reproduce your issue?
     Just run the game
     Journey of the Gods with ReviveVR 1.7.1.1 
     smooth in the preview window on the monitor but shuttering in the HMD...
     Steam SS@100, Motion smooth Off

## https://youtu.be/Aj5pLFci_i0

**Comment by ShinyRobotVR** [comment]
same issue, also with face your fears 2, defector is smooth but the world moves or wobbles.
with revive 1.7.0.3 low level crashes

**Comment by Angeluz01** [comment]
> 
> 
> same issue, also with face your fears 2, defector is smooth but the world moves or wobbles.
> with revive 1.7.0.3 low level crashes

i dont have any wobbles issues with defector

**Comment by Angeluz01** [comment]
Funky Ball (Free) have same issues

**Comment by Maerius3** [comment]
Same issue with Ballista and Raccoon Lagoon (and Vader Immortal, until you get into the settings and set the graphics to low). Tried with Vive and Index - same issue.

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
