### ISSUE TITLE
Inject not working on Lone Echo 1.7.1

### ISSUE THREAD

**Issue by AngelDark92** [LibreVR/Revive#1278]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 4790k
  - GPU: 1080ti
  - RAM: (amount and DDR#) 16GB
  - OS: Windows 10
  - Valve Index

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version (unless Remixed): 1.15.16
  - Revive installation version: 1.7.1

#### What is the last working version before this issue first came up?
  - Revive installation: 1.6.4
  - SteamVR (unless remixed): 1.15.16

### What apps/games are you trying to run?
  - Lone Echo

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. Right Click on revive dashboard and inject the exe of the game.

## Error messages/codes
  - None, it just does not start the game.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by nicotrial** [comment]
i have the same problem when i open with inject nothing happens.. for lone echo or any game..

**Comment by ahmanwoods** [comment]
Launch the game via cmd via ReviveInjector_x64.exe w/ the game executable as a parameter. Eg:

"C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Software\Software\ready-at-dawn-lone-echo\bin\win7\LoneEcho.exe"

Worked for me. Opening the steam VR overlay seems to crash the game though.

**Comment by Armada651** [comment]
Don't use Inject on Oculus games, use the dashboard.
