### ISSUE TITLE
Raccoon Lagoon: Jitter on old versions, doesn't open on 1.7.1

### ISSUE THREAD

**Issue by Ilseroth** [LibreVR/Revive#1279]
### Description of the issue
I originally tested the game on 1.6.4, as when I tried to update Revive, it said it was at the newest version (which was incorrect). The game launched and ran, but jittered heavily. I elected to see if there were any reports here on the github and saw there weren't, but also that there was a newer version. I tried again with 1.7.1.1 and it doesn't even start. I tried using injection and it still refuses to start. Double checked on 1.6.4 and it does open, but with significant jitters.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7 9700
  - GPU:RTX 2800
  - RAM: 16 DDR4
  - OS: Win10
  - Index

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version: 1.5.16
  - Revive installation version: 1.7.1.1

#### What is the last working version before this issue first came up?
-N/A

### What apps/games are you trying to run?
  - Raccoon Lagoon

## How to reproduce your issue?
  1. Just run the game

## Error messages/codes
  - None

**Comment by bigtroy1114** [comment]
Same here tried different versions but all are very jittery.

**Comment by chrisbraeuer411** [comment]
Jep i can confirm that too.

**Comment by Maerius3** [comment]
Same issue here using an HTC Vice. Tried versions 1.6.4, 1.7.0 and 1.7.1 (won't start at all with 1.7.1)

**Comment by pingu-99** [comment]
Jittering Fix

Go into this INI file:
Users\%username%\appdata\local\RaccoonLagoon\saved\config\WindowsNoEditor\Engine.ini

Add this string of code:
[/Script/Engine.RendererSettings]
r.ScreenPercentage=70

**Comment by Maerius3** [comment]
> This fixes the Jittering for me:
> 
> Go into this INI file:
> Users%username%\appdata\local\RaccoonLagoon\saved\config\WindowsNoEditor\Engine.ini
> 
> Add this string of code:
> [/Script/Engine.RendererSettings]
> r.ScreenPercentage=70

This worked perfect - thanks! I was hoping there'd be a similar fix for Ballista too (identical problem), but I don't see an equivalent ini file for it.

**Comment by Armada651** [comment]
@pingu-99 Good find, but you don't actually need to put it at 70, you can put it at 99 and it will work.

**Comment by Armada651** [comment]
Fixed in commit 4303b38fc85200078e8edb430489966010e42e8b. Will be part of the next release soon.
