### ISSUE TITLE
LUNAR FLIGHT  anyone? it's for oculus but I can't get it to run on revive

### ISSUE THREAD

**Issue by Rojoyinc** [LibreVR/Revive#128]
Anyone got this working yet?  really looks ideal for VR.

**Comment by LibreVR** [comment]
Please provide more details as to what you've tried. Also provide your logs from `%APPDATA%\Revive`.

**Comment by plaidpants** [comment]
They have not released a version that work with the current oculus SDK only 0.8

**Comment by LibreVR** [comment]
LibOVRWrapper is compatible with Revive, so it should not be a problem.
