### ISSUE TITLE
The Climb closes periodically (WMR)

### ISSUE THREAD

**Issue by RhythmParadox** [LibreVR/Revive#1280]
After a period of time (indiscriminate) the game closes. Whether in practice or in an actual climb (happened in both Alps and Canyon to be specific). No error messages occur, the game simply closes.

### Technical Information
  - CPU: i5-6600K (non overclocked) @ 3.5GHz
  - GPU: GTX 1080
  - RAM: 16GB (2x8), DDR4-2133 
  - OS: W10, 10.0.18362
  - Odyssey WMR

#### Versions and features
  - SteamVR version (unless Remixed): Latest beta (buildid 4049346)
  - Revive installation version: Latest (1.7.1)

#### What is the last working version before this issue first came up?
  - Revive installation: N/A
  - SteamVR (unless remixed): N/A

### What apps/games are you trying to run?
  - The Climb

## How to reproduce your issue?
We were simply playing normally, nothing special, can happen while you're holding onto something, while you look around, nothing out of the ordinary.

## Error messages/codes
  - N/A

**Comment by Foojoo** [comment]
I can confirm the same issue.  I play the Climb a lot.  Older versions of revive work perfectly, but I get random crashes with the newest  1.7.1 version.   No messages, the game just returns steamvr.
- i7 4770k  @ 4.2 Ghz (overclocked)
-Geforce 2070
-16 gb ram DDR3-1867
-Windows 10 - 18362.267
-Samsung Odyssey+
Windows Mixed Reality for SteamVR Beta  1.0.582
SteamVR beta- Version 1.6.10

**Comment by necros2k7** [comment]
try 1.9.0, if OK close issue

**Comment by RhythmParadox** [comment]
1.9 appears to have solved the issue
