### ISSUE TITLE
Ballista: Jitter on old versions, doesn't open on 1.7.1

### ISSUE THREAD

**Issue by Maerius3** [LibreVR/Revive#1281]
Description of the issue
The game "jitters" (vibrates?) whenever you move your head. Everything is steady when you hold your head still. This begins as soon as you start up the game (Logo screens, etc.). I've tried Revive versions 1.6.4, 1.7.0 and 1.7.1. Was unable to start the game at all with 1.7.1

Technical Information

  - CPU: i5 4460
  - GPU: GTX 1070
  - RAM: 16 GB DDR3
  - OS: WIN 10
  - Vive  (tried with Valve Index and got the same result)

*This issue is about:*
  - Revive 
  - SteamVR version (unless Remixed): Beta 1.6.9
  - Revive installation version: 1.6.4 1.7.0 and 1.7.1

What is the last working version before this issue first came up?
  - Revive installation: N/A
  - SteamVR (unless remixed): N/A

What apps/games are you trying to run?
  - Ballista

How to reproduce your issue?
Which steps do we take to get to the same result?**_

  1. Attempt to start game

Error messages/codes
  -  N/A

*** I don't know if this is relevant, but Vader Immortal had the exact same issue until I could get to the ingame settings and change the video setting to "low". Issue went away.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
