### ISSUE TITLE
"Patch" seems to do nothing

### ISSUE THREAD

**Issue by TBBle** [LibreVR/Revive#1284]
### Description of the issue

I installed the Oculus Software, and Revive, and am trying to patch Gal*Gun 2 VR per [Link's VR Guide for Gal*Gun 2](https://steamcommunity.com/sharedfiles/filedetails/?id=1603993136), in order to work around a problem with WMR devices and UE 4.18.

### Technical Information
  - CPU: Intel Core i7-3770
  - GPU: Radeon RX Vega 64
  - RAM: 16GB, not sure DDR#
  - OS: Windows 10 Professional 1930 (18362.267)
  - Vive / WMR (/ Odyssey) / Other device

#### Versions and features
*This issue is about:*
  - Patcher
  - SteamVR version (unless Remixed): 1.6.10
  - Revive installation version: 1.7.1.1

#### What is the last working version before this issue first came up?

N/A, fresh install

### What apps/games are you trying to run?
  - Gal*Gun 2 VR DLC

## How to reproduce your issue?

  1. Install Oculus Home
  1. Install Revive
  1. See that ReviveOverlay shows the default apps Dreamdeck, Touch Basics, and First Contact
  1. Right click on the Revive tray icon and select Patch...
  1. In the "Select File" dialog, navigate to the folder with Gal*Gun 2's executable, e.g. `C:\Games\Steam\steamapps\common\GalGun 2\GalGun2\Binaries\Win64`
  1. Double-click `GalGun2-Win64-Shipping.exe`
  1. "Select File" dialog closes, with no indication of result.
  1. Open the same directory in Explorer
  1. Observe that nothing has changed in that directory:
     - No xinput.dlls per ["Steam games" on the wiki](https://github.com/LibreVR/Revive/wiki#steam-games)
     - File timestamp on `GalGun2-Win64-Shipping.exe` has not changed.

## Error messages/codes
  - Absolutely nothing. The wiki doesn't mention any expected result apart from xinput DLLs created, so I'm not sure if I'm *expecting* any error messages or codes at this stage.

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Armada651** [comment]
Try the new version 1.7.2.

If it doesn't work you can manually copy over the DLLs in the `C:\Program Files\Revive\Revive\x64` folder and put them next to `GalGun2-Win64-Shipping.exe`.
