### ISSUE TITLE
Where is Lucky's Tale?

### ISSUE THREAD

**Issue by danylopez123** [LibreVR/Revive#1285]
To Install Oculus Home, now there is 4 type of Oculus.
I installed the "Oculus Rift" one and after installing it with the latest version of Revive 1.7.1, Lucky's Tale is not showing.

It's that game no longer bundled?

**Comment by Armada651** [comment]
It's indeed no longer bundled, it has a price tag on the Oculus store now: https://www.oculus.com/experiences/rift/909129545868758/
