### ISSUE TITLE
Killing Floor Incursion  1.7.2 not working

### ISSUE THREAD

**Issue by bakterius** [LibreVR/Revive#1289]
#485 # Technical Information
*Tell us your specs and versions*
  - CPU: I7 6700K
  - GPU: ASUS GTX 1080 STRIX
  - RAM: (amount and DDR#)  DDR4  16 GB
  - OS: W10
  - Valve INDEX

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher 172
  - SteamVR version (unless Remixed):  last beta + stable
  - Revive installation version: 172

### What apps/games are you trying to run?
  - Killing floor Incursion

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1.  All try freeze on black screen

## Error messages/codes
  - 

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

Run applikation cause freeze on black screen

**Comment by bakterius** [comment]
update spec

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3
