### ISSUE TITLE
Dashboard with 0.6

### ISSUE THREAD

**Issue by OhDawgDeBarge** [LibreVR/Revive#129]
Since upgrading to the new 6 I am unable to get the dashboard to come up, the last one worked ok and I haven't made any changes to the system.  I've looked over a few of the closed issues here that were similar to that but none of those suggestions worked.  Am I doing something wrong?

Install .6
Start Steam
(it doesn't show up in steam, so I try to run it off the start menu, doesn't load)
tried the overlay.exe with no results.  

A couple of uninstalls/reinstalls later and I can't quite seem to figure it out.  Any suggestions?

**Comment by wissper** [comment]
is the checkbox checked in the 'application' tab of steamvr settings?

**Comment by OhDawgDeBarge** [comment]
I think so, the Vive dashboard is there, and Revive used to be in the old version, it just doesn't show up anymore.  Plus, if I just try to push forward anyway with it, going with ReviveInjector and try to run say,dreamdeck for example, it just gives me the error that the HDM isn't detected.

**Comment by Brody79** [comment]
If you don't see the Revive tab, go to the start menu on your desktop and start the Revive Dashboard.
You should only have to do this once (probably until the next update).

**Comment by LibreVR** [comment]
Can you post your logs from `%APPDATA%\Revive`.?

**Comment by OhDawgDeBarge** [comment]
Sure,this is what it says:


libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Games/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-dreamdeck.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/playful-luckys-tale.json
Found application oculus-dreamdeck


The Injector had some things to say as well:

Launched injector with: "C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe"
Creating process: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
Injecting DLL: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x76b27070
Injecting DLL: C:\Program Files\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x76b27070
Injected dlls succesfully

**Comment by LibreVR** [comment]
The dashboard seems fine, no errors at all. Though it seems to not detect Lucky's Tale for some reason. Have you perhaps blocked the connection to the Oculus servers recently?

**Comment by OhDawgDeBarge** [comment]
I haven't blocked anything, this is a new build, only a few days old just for the Vive.  The only thing it has installed on it is Steam, the Oculus app and ReVive.  Now I never did get a chance to use the old version, before I went to .06 so it may have not worked either.  I do know that the dashboard showed up though.  Am I just SOL then?  Not a biggie, was just hoping to get it figured out is all.

**Comment by LibreVR** [comment]
Can you check with the task manager if `ReviveOverlay.exe` is running?

**Comment by OhDawgDeBarge** [comment]
There are three copies of it running, all around 25k memory usage.

**Comment by LibreVR** [comment]
Three copies?! That definitely shouldn't happen.

**Comment by OhDawgDeBarge** [comment]
I think it just runs a copy every time I click it.  I've closed them all manually before and just ran one, still no dashboard though. :( Maybe I'll get lucky on .7?

**Comment by OhDawgDeBarge** [comment]
Should I just give up on it for now then?  I'm not really sure what else to try.

**Comment by OhDawgDeBarge** [comment]
Just wanted to follow up, got a little help from a user on Reddit named Proxish.  He recorded a small video to assist with problems.  Works like a champ now, thanks.  I never clicked "allow" under properties, after that it worked for me.

https://www.youtube.com/watch?v=OHeUNCLUHL0&feature=youtu.be
