### ISSUE TITLE
revive 1.7.2 heavy stuttering in journey of the gods and others

### ISSUE THREAD

**Issue by ShinyRobotVR** [LibreVR/Revive#1290]
# Revive Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

### Technical Information
*Tell us your specs and versions*
  - CPU:i7 7700k
  - GPU:gtx1080
  - RAM:16gig ddr4
  - OS: 10
  - index

#### Versions and features
*This issue is about:*
  - Revive
  - Steam VR version
  - Revive installation version:1.7.2

#### What is the last working version before this issue first came up?
  - Revive installation:none
  - ,Steam VR

### What apps/games are you trying to run?
  - journey of the gods, face your fears 2 , raccoon lagoon

## How to reproduce your issue?start title using revive library
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. start title 

## Error messages/codes
  - heavy stuttering when looking around same as 1.7.1
raccoon lagoon does not start

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by Angeluz01** [comment]
https://github.com/LibreVR/Revive/issues/1274

**Comment by Maerius3** [comment]
Same issue with Ballista (and Vader Immortal, until you get into the settings and set the graphics to low). Tried with Vive and Index - same result.

**Comment by Armada651** [comment]
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3

**Comment by ShinyRobotVR** [comment]
stutter fixed which is great. just left with the scene wobble when looking around on index. its all smooth but the world does not look solid but slight delay in following movements.

**Comment by Armada651** [comment]
@ShinyRobotVR Caused by a bad hotfix on my part, sorry about that. Try re-downloading the release.

**Comment by ShinyRobotVR** [comment]
your a clever person i wish i got into programming when i got my amstrad back in the 80s lol. i check it out and report back. thanks

**Comment by ShinyRobotVR** [comment]
that did it thanks been looking forward to journey of the gods and knew it would be sorted at some point so wasnt going to refund. out of interest what needed to happen to keep the world in place?

**Comment by Armada651** [comment]
This commit undoes a bad attempt at reducing latency in Defector: 504d4e77616bae73cf53b38aa19d45f4c403dafa

This will be fixed using pose submission instead in the next update.

**Comment by ShinyRobotVR** [comment]
clever stuff. journey of the gods and face your fears 2 now run flawlessly to me.
