### ISSUE TITLE
Flashing menus in Dirt Rally

### ISSUE THREAD

**Issue by Raging-Beard** [LibreVR/Revive#1291]
Not a game breaker as once in car all runs great, but menus are now constantly flickering.

1080ti, i7 8700k, 16gb, Vive Pro

**Comment by ToRRent1812** [comment]
Video https://youtu.be/_zUPPlJNISs
Tested on 1.7.2, steamvr beta 1.7.2, in-game preview window shows no flickering, but it's flickering in vr

**Comment by ToRRent1812** [comment]
SteamVR beta 1.7.3 fixed the issue

**Comment by Armada651** [comment]
That's good news, keeping this issue open until the SteamVR stable is updated.

**Comment by yatli** [comment]
@ToRRent1812 I've installed SteamVR today and still seeing the flickering -- the UI display switches rapidly between up and down.

How do I check the SteamVR version?

**Comment by yatli** [comment]
FWIW there's a steady point if I turn my head to 10 o'clock then up for ~10 degrees the flickering images converges into one 0.0

**Comment by yatli** [comment]
@webhead2oo9 thanks for the tip! After replacing `LibRevive32_1.dll` in the game folder the problem is fixed!
