### ISSUE TITLE
Suggestion for Index grip sensor

### ISSUE THREAD

**Issue by Scope666** [LibreVR/Revive#1293]
I know you recently changed the Index bindings to "Force Sensor", but I wanted to suggest changing it to "Grab"

The reason being "Force Sensor" doesn't currently have any options to adjust grip strength.  The result is having to use a LOT of force just to keep a gun held.

With "Grip" there are two settings, one for how hard you have to hold to keep it in your hand, and another for how easy it is to drop something.

See the bottom of this guide for screen shots / better explanation:

https://steamcommunity.com/sharedfiles/filedetails/?id=1829531225

I found the file to edit to make local changes myself, but thought it might help others if they're finding it too tiring to keep something held.

**Comment by Armada651** [comment]
1. You should make per-game bindings using to UI, do not change the default files themselves as they'll be replaced every update of Revive.

2. The reason I don't use Grab is because it's a digital input while the grip trigger on the Oculus Touch is an analog input.

3. It will depend on the game how much force is needed to grip a gun, which game are you encountering problems with?

4. Use the issue template!

**Comment by Scope666** [comment]
The per-game binding system has been very wonky for me.  Sometimes it
"sticks", sometimes it simply doesn't save anything.  Also sometimes it
will let you edit outside of game, other times the game has to be running
for it to pick the right template.

ARKTIKA.1 was the one I noticed that required the most force just to keep
the guns held.  I just wish they would allow sensitivity adjustment on the
Force Sensor like they do on the Grip one.

**Comment by Armada651** [comment]
I'll test ARKTIKA.1 and see if I can make some improvements. I might apply a function that makes the force curve less linear so it grips earlier.

**Comment by Armada651** [comment]
The new 1.7.3 release has a small tweak to the grip value. Let me know if this works better for you.

**Comment by Scope666** [comment]
Awesome, I'll check it out the next time I fire up the VR.

I have to say you do AMAZING work, I've been using Revive since the OG Vive came out (paid the early adopter "tax") and it's always worked great!

**Comment by Scope666** [comment]
OK, I had a chance to test ARKTIKA.1, it's WAY better now ... thanks!

Also, I tested Vader Immortal, I can confirm that you can set the graphics settings to high now without any stutter ... nice job!!!

BTW, this hack works great on the Valve Index to fix the brightness in Vader:

https://www.reddit.com/r/oculus/comments/c8fi2y/vader_immortal_brightness_fix/
