### ISSUE TITLE
Can't start Remixed  without Steam VR.

### ISSUE THREAD

**Issue by Mrmoooz** [LibreVR/Revive#1294]
Hi guys,

I am not sure why I cannot start Remixed. I know that I have to close SteamVR and Run Revive while steam vr isnt on to start Remixed, but every time I try to start Remixed SteamVR and Steam automatically logs in. Please help. Thank you!

**Comment by Armada651** [comment]
In version 1.7 Remixed has been removed in favor of supporting WMR headsets through SteamVR.

I'm working on supporting WMR headsets through OpenXR instead, but this is still experimental.

**Comment by RowdyRocket** [comment]
Yeah SteamVR isn't working well for me with Revive not sure what happened it used to be perfect. I'm trying to play the Climb but it stutters beyond playable all of my Oculus games are that way. Not sure whats changed. 

Remixed (1.6.4) is super smooth BUT I can only see out of the right eye. Any ideas what I can do get the other eye working? No luck googling it yet.

I have high hopes for OpenXR! Keep up the good work!

**Comment by Armada651** [comment]
The Climb is unfortunately one of the games that's difficult to support on WMR. Even on 1.6.4 it appears smooth but instead suffers from latency and a "swimming" effect.

**Comment by RowdyRocket** [comment]
I was finally able to get somewhat playable results. Still stutters a bit when looking out at the scenery. I ended up disabling HPET as others had suggested. Really wish it was perfect but grateful that at least I can play it. Thanks for all your efforts! Keep up the good work!

**Comment by wotever** [comment]
i have not tried the climb in months, but i couldnt even get it to launch at the time, im also on wmr btw.
