### ISSUE TITLE
"Can't launch Oculus Medium" error

### ISSUE THREAD

**Issue by Gragax** [LibreVR/Revive#1295]
"Can't launch Oculus Medium"

1. Start SteamVR
2. Select Oculus Medium via dashboard, steam library, etc.
3. launch
4. 
![image](https://user-images.githubusercontent.com/53808807/62830602-4f4ee500-bbc6-11e9-8604-8517cd75ecb0.png)

It started this night. It was fine yesterday. 
edit 1: something to note is that when I click OK on the error window, it shows a split second of the app actually working, then closing. 

 - App: Oculus Medium
 - OS: Windows 10
 - Headset: HTC VIVE

 - Revive: 1.7.0 and 1.7.3
 - SteamVR: 1.6.10

**Comment by Angeluz01** [comment]
1.7.3 works , vive pro

**Comment by Gragax** [comment]
ok, ill try it

**Comment by Gragax** [comment]
> 1.7.3 works , vive pro

Didn't work, same error code

**Comment by Angeluz01** [comment]
it works for me lol
steam 1.7.3, revive 1.7.3, win10 1903,

**Comment by Gragax** [comment]
> it works for me lol
> steamVR beta 1.7.3, revive 1.7.3, win10 1903, Vive Pro with index controllers

Still no luck

**Comment by Armada651** [comment]
I cannot reproduce this either. Try re-installing Oculus Medium.
