### ISSUE TITLE
Lone Echo - View makes you squint - 1.7.3 to 1.7.1

### ISSUE THREAD

**Issue by Puni12345** [LibreVR/Revive#1296]
**Describe the bug**
Till 1.7.0 Lone Echo worked fine through revive -> now starting with 1.7.1 something isn´t right with the way the two displays of the headset are driven. It seems like left and right eye are swapped.

**To Reproduce**
Just open Lone Echo with steam vr.

**Expected behavior**
Normal view like pre 1.7.1

**Environment (please complete the following information):**
 - App: Lone Echo
 - OS: Win10 1903
 - Headset: Odyssey +

**Versions (please complete the following information):**
 - Revive: 1.7.3
 - SteamVR: Beta 1.7.3
- WMR: 1.0.594

**Additional context**
Thanks for your hard work - looking forward to the openxr implementation!

**Comment by Armada651** [comment]
Just pushed a hotfix, can you try redownloading the latest release to see if it's fixed?

**Comment by Puni12345** [comment]
Wow, that was quick :-) - works like a charm now - big thumbs up!

**Comment by Puni12345** [comment]
closing ticket - solved
