### ISSUE TITLE
Revive vr 1.7.3-1.7.3.3 controller bindings not saving

### ISSUE THREAD

**Issue by Angeluz01** [LibreVR/Revive#1297]
Revive vr 1.7.3-1.7.3.3 controller bindings not saving

**Comment by Armada651** [comment]
This is a SteamVR issue, if you go back to 1.6.4 you'll have the same problem.

**Comment by Angeluz01** [comment]
na, i only have problem with ver 1.7.3-.17.3.3. i tested it before create this post lol
thankz again for the quick fix^ ^
