### ISSUE TITLE
Pinball FX2 Does not load

### ISSUE THREAD

**Issue by peteostro** [LibreVR/Revive#130]
When I launch Pinball FX2 with the newest Revive it just shows the words loading and does nothing.
I've tried changing to run as administrator and same issue.

**Comment by thepotatoman23** [comment]
I have the same problem and have heard the same from others.

**Comment by LibreVR** [comment]
Will look into this at a later time.

**Comment by sjmiles** [comment]
Fwiw, it looks to me like Pinball FX2 loading spinner, so I think the target program does start execution (but gets stuck in the initial loading phase).

**Comment by bloodydrake17** [comment]
same issue

**Comment by britxpatusa** [comment]
Just loaded it up...same issue as above..let me know if you need a tester on software...happy to help.

**Comment by bloodydrake17** [comment]
BTW with .62 PinballFX2 VR now starts with Vive

**Comment by gormanj** [comment]
bloodydrake17 Is that 0.6.2 WITH the runtime updated to 1.5?

**Comment by bloodydrake17** [comment]
I did the auto update oculus home requested app version 1.5.0.240083(1.5.0.241049)then installed revive .6.2
and then when i launched pinball fx2 vr thru the steam revive tab instead of just sitting at the loading screen it went to the ingame appartment lobby

**Comment by britxpatusa** [comment]
All working now, pretty cool!
Latest version of oculus home and 6.2 revive

**Comment by gormanj** [comment]
Tested and working with Revive injector 0.8.3 and Oculus runtime 1.5. Been waiting for this one. Thanks LibreVR!

**Comment by gormanj** [comment]
BTW, if you are looking for a stand to put your arcade stick or keyboard on for pinball, try this one. I got it. It is very sturdy:
https://www.amazon.com/Seville-Classics-WEB162-Mobile-Laptop/dp/B0097GMHXG
