### ISSUE TITLE
Valve Index Knuckles Trackpad

### ISSUE THREAD

**Issue by FreezFree** [LibreVR/Revive#1300]
When I try to grab something in a game, I have to grab the trackpad of the Knuckles really hard for it to react. Is this normal?

**Games I tried (Revive 1.7.3 ; SteamVR 1.6.10):**

- Vader Immortal

- Defector

- A Fisherman's Tale

**Comment by Armada651** [comment]
Do you mean the trackpad at the top of the controller or the force sensor in your hand?

**Comment by FreezFree** [comment]
The force sensor.
I have to press it to the max for it to react.
Same problem on both knuckles.

**Comment by FreezFree** [comment]
Same behavior with Revive 1.8.0

**Comment by Armada651** [comment]
Unfortunately it's not possible to make one binding that works for every game for every user. When you go to Settings > Controller Bindings you can customize your bindings. I recommend deleting the Force Value binding and replacing it with a Trigger binding bound to Grip value.

**Comment by FreezFree** [comment]
> Unfortunately it's not possible to make one binding that works for every game for every user. When you go to Settings > Controller Bindings on your dashboard you can customize your bindings. I recommend deleting the Force Value binding and replacing it with a Trigger binding bound to Grip value.

Ah thanks for that, its working now.
I had to bind the force sensor to "grip" and set a threshold value of 0.
Now it reacts as soon as i touch the sensor.
