### ISSUE TITLE
Custom Images Broken Again in Steam Grid on Revive 1.8.0

### ISSUE THREAD

**Issue by dakodeh** [LibreVR/Revive#1302]
When 1.7.x was initially released, Oculus had added "On Oculus" descriptor to every item in their store, breaking links in Steam libraries to custom banner images for Revive titles. The dev quickly fixed this behavior with a hotfix that removed the extra verbiage from titles in Steam, restoring the links to the custom images I'd added to my library.

When I installed Revive 1.8.0 this morning, I found these image links broken again. Curiously, the titles of the games all appear correct, so I'm not sure what's going on here. I'm using the latest version of Steam (package 156565602) and Revive 1.8.0

**Comment by Armada651** [comment]
Unintended change as part of f3de0fab7252123353303f02fac91aa41bad35d9

Will revert and push a hotfix.

**Comment by Armada651** [comment]
Hotfix has been released, you can update by downloading the 1.8.0 release again or checking for updates.
