### ISSUE TITLE
Odyssey plus controller menu buttons malfunctioning

### ISSUE THREAD

**Issue by mhallst2** [LibreVR/Revive#1303]
**Describe the bug**
I'm using an Odyssey Plus headset. In the game Brass Tactics, the menu controller button is unresponsive. Also, the button acts as if it's being pressed repeatedly without any input. According to the steamVR overlay, my controllers are behaving as expected. I don't have other games to test if this bug is occurring across all games launched via revive or if this bug is game-specific.

**To Reproduce**
1. Open Windows Mixed reality portal
2. Click on launch steamVR (beta 1.75)
3. Launch Brass Tactics through revive using the steam overlay
4. Start a game. The menu buttons on the controllers keeps acting as if they are being pressed repeatedly. This may stop, but then the menu buttons do not respond to user inputs.
(update) 5. After further testing, it appears that the controller triggers are activating the menu buttons in game.

**Expected behavior**
Normally, the menu buttons should activate only when pressed by the user.  

**Environment**
 - App: Brass Tactics
 - OS: Win 10 v 1903 build 18362.239
- Headset: Odyssey plus

**Versions (please complete the following information):**
 - Revive: 1.8.0
 - SteamVR: 1.7.5 (beta)
-Oculus app 1.39.0.272909

**Comment by Armada651** [comment]
Hotfixed in 1.8.0.2 redownload the latest release or use check for updates from the tray icon.
