### ISSUE TITLE
Revive 1.8: problems in various games

### ISSUE THREAD

**Issue by Ylluan** [LibreVR/Revive#1304]
**Describe the bug**
problems in various games:
Luky's Tale: index controller no tracking and no buttons work
Robo Recall: problem with audio and hand image in-game changes quickly from the controllers to the hands of the game, no buttons work
Defector: the game run in two immages side by side mode.

**To Reproduce**
Just start the games

**Environment (please complete the following information):**
 - App: Luky's Tale, Roborecall, Defector
 - OS: Win10 Pro 1903
 - Headset: Index

**Versions (please complete the following information):**
 - Revive: 1.8
 - SteamVR: 1.7.5

**Additional context**
WitchBlood, DropDead and Arktika.1 work well
With Revive 1.7.3, all games work ok except Defector that flickering immage
With Revive 1.7.0.3 Defector work ok but must disable Avast AV

**Comment by Armada651** [comment]
Hotfixed in 1.8.0.2 redownload the latest release or use check for updates from the tray icon.
