### ISSUE TITLE
Revive 1.8.0.1 - keeps pushing start buttons on its own and Oculus Home shortcut not working... 

### ISSUE THREAD

**Issue by Angeluz01** [LibreVR/Revive#1305]
Revive 1.8.0.1 - keeps pushing start buttons on its own and Oculus Home shortcut not working... 

Revive 1.8.0.1
SteamVR 1.7.5
Vive Pro with index controllers
9700k
2080ti oc
Win10 1903

https://youtu.be/hfW7BLmbKMI

**Comment by Armada651** [comment]
Hotfixed in 1.8.0.2 redownload the latest release or use check for updates from the tray icon.

Can't reproduce the Oculus Home shortcut not working.
