### ISSUE TITLE
Vader Immortal Menu Glitch

### ISSUE THREAD

**Issue by RobertWright92** [LibreVR/Revive#1306]
**Describe the bug**
About 2-3 seconds after I start either the dojo or campaign the menu begins to flash open and closed rapidly. It can be interacted with but there is no way to stop it from opening and closing other than turning off the left controller. Once the controller is turned off the menu stops opening and closing but then you can no longer open a menu with the other controller. I have changed versions of Steam VR, both current and beta branches, as well as reinstalled pretty much everything other than my operating system. I have also rebound the menu button to see if it was an issue with the controller, no effect. On one occasion after moving the installation folder for Vader Immortal it opened and ran fine.  Once I closed and reopened it the menu issue returned. Another time I turned off my left controller while in the dojo and then turned it back on and the issue stopped. There doesn't seem to be anything I can repeat to get it to stop but it does stop sometimes. 

**To Reproduce**
Turn on the game and try to play the dojo or campaign.

**Environment (please complete the following information):**
 - App: Vader Immortal via Revive and Steam VR
 - OS: Win10
 - Headset: Valve Index

**Versions (please complete the following information):**
 - Revive: 1.8.0
 - SteamVR: 1.7.6

**Comment by Angeluz01** [comment]
latest version 1.8.0.4

**Comment by Armada651** [comment]
This was a problem in the initial 1.8.0 release, please re-download it to get the hotfix.
