### ISSUE TITLE
General tracking issues 1.8 Echo Arena

### ISSUE THREAD

**Issue by scardigne** [LibreVR/Revive#1307]
**Describe the bug**
Throwing orientation is completely off and at wrong trajectory at object let go

**To Reproduce**
Throw a disc and release...? try down swipe release, side swipe release and reverse.

**Expected behavior**
Disc throws correctly and at right angle / trajectory when thrown

**Environment (please complete the following information):**
 - App: Echo Arena
 - OS: WIN 10
 - Headset:  Index, Index controllers

**Versions (please complete the following information):**
 - Revive: 1.8
 - SteamVR: 1.7.6 beta

**Additional context**

**Comment by Armada651** [comment]
Hotfixed in 1.8.0.6, redownload the latest release or check for updates.

This is actually caused by a bug in SteamVR Input, I've added a workaround in commit 9a52325e81f0b32cc402e7057cabfd48f2b0e806
