### ISSUE TITLE
X Moon Productions - XStoryPlayer 3.5 - ReviveInjector

### ISSUE THREAD

**Issue by Skidrow68** [LibreVR/Revive#131]
Tried to use ReviveInjector_x64.exe on XStoryPlayer64 but my monitor turns black and i see only the blue screen on Revive in HTC Vive, the sound runs so i know the game started.

Found the log:
Launched injector with: ReviveInjector_x64.exe  XStoryPlayer64.exe
Creating process: XStoryPlayer64.exe
Failed to create process

When i tried to start it from CMD i get: Failed to create process.

Ps, when i tried to use ReviveInjector_x86.exe my antivrus-program removed it.

**Comment by supermanscottbristol** [comment]
I get the same message with The Climb.  @LibreVR said to me that it means it cant find required files.

**Comment by LibreVR** [comment]
To be precise, you entered an executable name which it can't find. I think you're expecting Revive to inject into a running process, which it can't. The ReviveInject is meant to be the application which starts the game as a sub-process.

**Comment by Skidrow68** [comment]
Can you explane how i should do it then? what i tried was drop the exe file on ReviveInjector_x64.exe.

**Comment by Skidrow68** [comment]
Its a standalone game that makes it own engine and you use Maya to make mods, so it dont use unreal or so. Revive is installed on D:\Revive and the game on E:\X Moon Productions\XStoryPlayer 3.5. Oculus is also installed D:\Oculus

Yes i use a Vive headset.

ReviveInjector.log
Launched injector with: ReviveInjector_x64.exe  XStoryPlayer64.exe
Creating process: XStoryPlayer64.exe
Failed to create process

ReviveOverlay.log
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: D:\Revive\revive.vrmanifest
Runtime directory: file:///E:/Steam/steamapps/common/SteamVR/
Oculus directory: file:///D:/Oculus/
Loading assets manifest: file:///d:/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///D:/Oculus/Manifests/playful-luckys-tale.json

**Comment by LibreVR** [comment]
> Launched injector with: ReviveInjector_x64.exe XStoryPlayer64.exe

You're still trying to inject into a running process, that doesn't work. You need to give ReviveInjector the full path of the executable and use the injector to start the game.

**Comment by Skidrow68** [comment]
Tried from CMD ReviveInjector_x64.exe E:\X Moon Productions\XStoryPlayer 3.5\x64\XStoryPlayer64.exe with same result.

**Comment by LibreVR** [comment]
You can't have spaces in your command-line arguments, why are you using the CMD anyway? You can just drag the executable of the game onto the injector [as mentioned in the installation instructions](https://github.com/LibreVR/Revive#standalone-games).

**Comment by Skidrow68** [comment]
Thats what i did and the game start but no picture i can only hear sound and the log is:
ReviveInjector.log
 Launched injector with: ReviveInjector_x64.exe XStoryPlayer64.exe
 Creating process: XStoryPlayer64.exe
 Failed to create process
Look here i can show you https://youtu.be/5IYrC2IEZMA

**Comment by LibreVR** [comment]
The log does not match with what you're saying at all, it clearly states the game was not started because of an incorrect command-line argument.

**Comment by Skidrow68** [comment]
Think they start the oculur thing in game maybe its becase if that it dosent work.

Now am closer, the log say:
Launched injector with: "E:\X Moon Productions\XStoryPlayer 3.5\x64\ReviveInjector_x64.exe" "E:\X Moon Productions\XStoryPlayer 3.5\x64\XStoryPlayer64.exe"
Creating process: E:\X Moon Productions\XStoryPlayer 3.5\x64\XStoryPlayer64.exe
Injecting DLL: E:\X Moon Productions\XStoryPlayer 3.5\x64\x64\openvr_api.dll
LoadLibrary found at address: 0x32aa74d0
Injecting DLL: E:\X Moon Productions\XStoryPlayer 3.5\x64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x32aa74d0
Injected dlls succesfully

But still only blue if i am at Revive and black monitor, if i press F8 it crash.

![xatory](https://cloud.githubusercontent.com/assets/19759240/15987332/042ffc60-3025-11e6-9fec-c8137142155b.jpg)
.

**Comment by Skidrow68** [comment]
Do you think there is a way to get it to work or is it a lost case?

**Comment by supermanscottbristol** [comment]
I'm hoping @LibreVR puts in some logging messages in the future that will help us track down exactly whats wrong.

**Comment by LibreVR** [comment]
@supermanscottbristol This issue was about getting the injector working for him. Problems with actually running this application should be submitted in a new issue report.

I'm currently on a break from Revive, so it will take a bit longer until the next release. But if you submit an issue I will be sure to take a look at it before the next release.

**Comment by supermanscottbristol** [comment]
@LibreVR The Climb doesnt work for me, so I'm in that issue.  I get the same error message as above.  You said something about files not being found, but I've no way of knowing which ones are in the wrong folder etc.

**Comment by LibreVR** [comment]
Please post the contents of your log.

**Comment by supermanscottbristol** [comment]
I did.  I attached 6 files and you looked at them already.

**Comment by LibreVR** [comment]
I can't find them.

**Comment by supermanscottbristol** [comment]
This was my post in issue 118

Ok, so I've 6 files here. A 0.6 and 0.5.2 overlay log. Then a revive injector log for both versions, 1 for launching from inside revive - which actually doesn't result in the error message, just nothing happens, the other is for when I drag the climb exe onto the injector.

When I installed 6 I did it to C:\ and for 52 I did it to V:\ just so I could easily differentiate between log files. I never had both versions installed at once.

Couple of things I've noticed - when you do the drag method for the first time Windows Smart Screen gets in the way and you have to tell it to allow the file to run. Once you've done it once it then doesn't ask again. I wondered if maybe that's what was happening behind the scenes when you try and launch from in VR so I tried running the injector file from in the revive install directory just in case smart screen would pop up but that didn't change anything.

When uninstalling 6 and going to 52 and vice versa, the Steam VR would complain about the compositor not running and prevent the headset from working until I rebooted.
After a reboot - all good.

**Comment by LibreVR** [comment]
Why didn't you just post in issue 118 then? I'm notified of every comment in this issue tracker.

Anyway, no idea what is going on with your Oculus Home installation, I recommend following the instructions for standalone games. Use the ReviveInjector on `Climb.exe` manually.

**Comment by supermanscottbristol** [comment]
I did!  Thats what Im telling you.  I posted in the issue, I attached these logs in the issue, you looked at them and responded in the issue.

**Comment by Skidrow68** [comment]
But its Always been how to get XStoryPlayer 3.5 to work on HTC Vive.

Were should i post then?

**Comment by LibreVR** [comment]
@supermanscottbristol Yeah, the injector logs look fine. Probably just Denuvo getting in the way. I guess you're seeing an error about not being able to connect to the oculus servers or something like that?

**Comment by LibreVR** [comment]
@Skidrow68 Make a new issue, this issue is now about 3 different issues which is very confusing.

**Comment by supermanscottbristol** [comment]
@LibreVR Correct yeh.

**Comment by LibreVR** [comment]
@supermanscottbristol So you can try downgrading to the Oculus Runtime 1.3, but I see you've already tried that. Since that doesn't work you have no other option but to wait until the next version of Revive which will hopefully be able to work around the Denuvo protection.

**Comment by supermanscottbristol** [comment]
@LibreVR That's good to hear.  I'm happy to wait.  The money is already spent after all!
