### ISSUE TITLE
Controller offset doesn't work for Index controllers

### ISSUE THREAD

**Issue by Nordomus** [LibreVR/Revive#1310]
Well not much more to say. Controllers are at a little bad angle and I wanted to correct it. It does nothing though.

- Arctica
 - OS: Windows 10
 - Headset: Valve Index

 - Revive: 1.8.0
 - SteamVR: 1.7.6

**Comment by Armada651** [comment]
What are you using to correct it? SteamVR input bindings?

**Comment by Nordomus** [comment]
I'm using revive, there are multiple options to adjust controllers angles and none of them seem to work. I have no idea how to change it in SteamVR input bindings.

**Comment by Armada651** [comment]
So you're using the Controller Bindings in the settings menu? There is indeed a known problem with poses not immediately applying. You can try saving your binding as a personal binding or restart the application after changing the binding.

Unfortunately this seems to be a SteamVR bug so I'm unable to fix it right now.

**Comment by gr3y5had0w** [comment]
I have the same issue but with OpenVR Advanced Settings.

**Comment by Armada651** [comment]
OpenVR-AdvancedSettings is no longer supported by Revive, those options
won't work.

>
