### ISSUE TITLE
Defector not accepting nod 

### ISSUE THREAD

**Issue by fkamaral** [LibreVR/Revive#1312]
**Describe the bug**
Game starts, everything looks fine, I place the ear piece and the contact lenses, operator says that I don't have to say anything, just to give him a nod.
Stuck there, it never identifies my nod....

**To Reproduce**
1. Go to 'begin the first phase of the game'
2. Click on 'follow the audio instructions'

**Expected behavior**
it should accept my nod and let the story go on.

**Environment (please complete the following information):**
 - App: Defector
 - OS: Windows 10 PRO
 - Headset: Samsung Odyssey (Original)

**Versions (please complete the following information):**
 - Revive: 1.8.0
 - SteamVR: 1.7.6

**Additional context**
Have been trying to play this since revive 1.7.1, found reports on redit and it looks like to be happening only with WMR and Pimax headsets...

**Comment by bdifferent9** [comment]
Go to cs.rin.ru and search the game. there is a save file in the downloads that you have to use. Start you right after the nod part. Just a warning, there is a lot of stutter when looking around. Really hoping it's fixed soon.

**Comment by fkamaral** [comment]
thanks, it worked... good workaround.
PS. no stutter to me at all!

**Comment by bdifferent9** [comment]
Awesome!! I wonder why I'm having so much stutter. Same headset. i6700k 1080. Do you have any special settings at all? Running steamvr or beta?

**Comment by fkamaral** [comment]
Changed all settings to max, but I'm running on a I7-8700K 2080TI 64Gb Ram, and SteamVR Beta.
Also, I've been told that they fixed the stuttering on Revive 1.8.0

**Comment by bdifferent9** [comment]
Yeh I'm using revive 1.8.0. Must be something in the settings or maybe just that graphics card difference. Either way, glad you got it going.

**Comment by Armada651** [comment]
Did you buy the game or pirate it?

**Comment by bdifferent9** [comment]
I own it. I redownloaded it and most of the stutter is gone. Some levels still have it, but it's better. I'm wondering if something in one of my saves could have been causing it. I deleted those and started fresh.

**Comment by Armada651** [comment]
It doesn't sound like you're running the game legitimately, you've downloaded a save file from a forum topic explaining how to pirate and run the game. Whether you own it or not it's highly likely you are trying to bypass the DRM and running into glitches because of it.

**Comment by bdifferent9** [comment]
Well you are completely wrong in your assumption. I do own the game. The save file is needed to be able to play it with wmr. Or else it gets stuck at the head nod. Has nothing to do with pirating. Pretty insulting especially when you simply don't understand what the save file is for... smh

**Comment by Armada651** [comment]
I do understand what the save file is for, but this is an issue I cannot reproduce. The save file you're referring to comes directly from a page devoted to piracy, hence my suspicion.

**Comment by Cookiezero1989** [comment]
Any news from this or a save file we could use?

**Comment by fkamaral** [comment]
No updates un functionality, let me paste a link for a save game fila for you in a few minutes...

**Comment by Cookiezero1989** [comment]
Thank you that will be awesome if you could as bought the game and can’t play it if I can get past the nod. Thanks again.

**Comment by fkamaral** [comment]
Sorry, my savegame is damaged... could not make it work
