### ISSUE TITLE
Can't change the angle of guns/hands anymore.

### ISSUE THREAD

**Issue by bdifferent9** [LibreVR/Revive#1313]
**Describe the bug**
Changing values in the revive tab doesn't affect the angle of hands anymore.

**To Reproduce**
1. Go to '...' Defector
2. Click on '....'Launch Defector
3. Scroll down to '....' Revive tab in advanced settings

**Expected behavior**
Everything works good, however when I open the revive tab and try to change the angle of the guns, I can change the value but it doesn't affect anything. Worked on previous versions. Is there a new way to do it?

**Environment (please complete the following information):**
 - App: [e.g. First Contact]Defector
 - OS: [e.g. Win10] Win 10
 - Headset: [e.g. Vive, Index] Samsung Odyssey

**Versions (please complete the following information):**
 - Revive:1.8
 - SteamVR: newest beta

**Additional context**

**Comment by Armada651** [comment]
This is in the release notes:

> Revive: Removed support for the Revive tab in the old versions of OpenVR-AdvancedSettings

**Comment by bdifferent9** [comment]
The tab is there. The options just don't do anything

**Comment by Armada651** [comment]
Yes, like the change notes say, support for those options were removed.
SteamVR Input allows for a few different poses by editing the action poses.
