### ISSUE TITLE
Can't play echo vr

### ISSUE THREAD

**Issue by JakobeBryant12** [LibreVR/Revive#1318]
Echo VR crashes on startup.

Specs: Nvidia GTX 1070 
            Ryzen 2700k
            32gb ddr4

I've tried: Rebooting and uninstalling revive

Any fixes?

**Comment by ntblood** [comment]
I have the same issue with Lone Echo, a related game. Crashes after the main title screen comes up. Does using an older version of Revive work?

**Comment by Armada651** [comment]
Can you try the latest 1.8.1 version? I can't reproduce it there.
