### ISSUE TITLE
Obduction Support

### ISSUE THREAD

**Issue by peteostro** [LibreVR/Revive#132]
This is going to be a big game. Made by the people who made mist. It's launching with rift support on steam July 26th. Hoping you guys can get revive working with it

**Comment by thepotatoman23** [comment]
First we have to wait until it releases and someone buys it to see if there's a problem that the devs need to work on fixing.

Most unreal engine games seem to work and that's an unreal engine game, so I wouldn't be surprised if this one will work too.

**Comment by iamwes** [comment]
I really want to be able to play this on the Vive, looks so good

**Comment by LibreVR** [comment]
This game has not been released yet.
