### ISSUE TITLE
Dirt Rally 1.0 issue with the double image

### ISSUE THREAD

**Issue by spamies1** [LibreVR/Revive#1322]
**Describe the bug**
Double image displayed. Small flickering image of the game window is overlaid in the center of the VR world image.

**To Reproduce**
Launch game and the flickering game window is displayed in the headset.

**Expected behavior**
Clear VR image without the flickering window displayed.

**Environment (please complete the following information):**
 - App: Dirt Rally
 - OS: Win10
 - Headset: Vive

**Versions (please complete the following information):**
 - Revive: 1.8.0
 - SteamVR: Latest Steam Beta

**Additional context**
Works fine with Revive 1.7.3

**Comment by oblivion2k** [comment]
Can reproduce issue with Odyssey+, Win10.

**Comment by Armada651** [comment]
Fixed in the latest version: https://github.com/LibreVR/Revive/releases/latest
