### ISSUE TITLE
OpenXR Mode not grabbing WMR Headset.

### ISSUE THREAD

**Issue by yackaro** [LibreVR/Revive#1323]
**Describe the bug**
Launched Oculus application or game opens a render window on desktop, but headset does not enter OpenXR session and app does not seem to receive tracking.

**To Reproduce**
1. Open ReVive
2. Check "Enable OpenXR support" in tray icon
3. Launch app from overlay.
4. See render window, but headset will remain in WMR Home.

**Expected behavior**
ReVive opens an OpenXR session on my Windows MR Headset.

**Environment:**
 - App: Any
 - OS: 1903
 - Headset: Samsung Oddysey+

**Versions:**
 - Revive: 1.8.0
 - Mixed Reality OpenXR Runtime: 100.1907.31001

**Additional context**
I probably have barely any idea what I'm doing, if that helps at all.
Also, default issue report template ftw.
Regular SteamVR mode works fine, I just want to go through OpenXR so that I can properly click with the joystick.

**Comment by yackaro** [comment]
Issue Persists with ReVive 1.8.1.
I have uninstalled and reinstalled both the OpenXR Runtime and Developer portal, and ensured that both work properly independantly of ReviveXR.
I hope for a fix to OpenXR mode soon; I would love to test this version of revive's functionality.
![image](https://user-images.githubusercontent.com/13648914/64587596-e47ffd80-d36d-11e9-9898-73d21df84788.png)

**Comment by Armada651** [comment]
Try this version: Can you test this version? https://github.com/LibreVR/Revive/releases/tag/1.8.2

**Comment by cegli** [comment]
I had this exact same problem on 1.8.1 and there is no change on 1.8.2.  It's not better or worse.  My setup is identical, except I'm using a newer OpenXR runtime and a Lenovo Explorer:

Environment:

App: Any
OS: 1903
OpenXR Runtime Version: 100.1910.1004
Revive 1.8.1 and 1.8.2

This is with a Nvidia 1070 GTX on the latest video driver.

**Comment by yackaro** [comment]
Came back to this and saw it finally got some attention, and after testing on Revive 1.9.1.5, as well as 1.8.2 as per comment, with all other variables consistent with my original post, this issue thread should not be marked closed. I still do not get any indicators that any game I launch through ReVive is recieving input of any sort from the headset or controllers, nor does the headset display fade from the Mixed Reality Home to the ReVive instance.

**Comment by qlyoung** [comment]
XR support is not fully baked yet, so I'm not surprised you're hitting issues. If you're super interested to try it, you might try directly running the injector with `ReviveInjector.exe /xr <path\to\app>`. Unfortunately while core development continues on XR support this issue isn't going to get much attention.

**Comment by AaronClover** [comment]
I had the same issue and was able to get it working on WMR by downgrading Revive to 1.2.1. I was able to upgrade back to 1.9.1 with no issues.

Also try launching in this order:
1. WMR Portal
2. Steam (not VR)
3. Revive (should launch steam VR)
4. Launch game from vr overlay (inject from taskbar if it's a non steam exe)

**Comment by yackaro** [comment]
> 
> 
> I had the same issue and was able to get it working on WMR by downgrading Revive to 1.2.1. I was able to upgrade back to 1.9.1 with no issues.
> 
> Also try launching in this order:
> 
>     1. WMR Portal
> 
>     2. Steam (not VR)
> 
>     3. Revive (should launch steam VR)
> 
>     4. Launch game from vr overlay (inject from taskbar if it's a non steam exe)

That's regular Revive, which works as it should.
The topic of discussion is ReviveXR, which is completely separate from SteamVR and can run Oculus Games directly into the Windows MR headset via the OpenXR standard.
But thanks.
