### ISSUE TITLE
Revive displays blurry overlapping text and a lack of depth - Valve Index

### ISSUE THREAD

**Issue by Charlster** [LibreVR/Revive#1324]
When booting into any Oculus software e.g. Lone Echo, using the latest version of revive the games image seems to overlap with one another as well as lacking much depth in the image so my steamvr chaperone bounds are right next to my face and my in game shoulders are disproportionate making it unplayable. That being said the window displayed on the desktop looks as it should.

 - App: [Any Oculus Software for example, Lone Echo]
 - OS: [Win10]
 - Headset: [Index]

 - Revive: 1.8.0
 - SteamVR: 1.6.10

**Comment by Armada651** [comment]
Can you try the latest 1.8.1 version? I can't reproduce it there.

**Comment by lionheartng** [comment]
Can confirm I am having the same issue with Oculus software and image overlap.

- OS: [Win10]

- Headset: [Valve Index]

- Revive: 1.8.1.1

- SteamVR beta: 1.7.14

- GPU: GeForce RTX 2080ti (driver version 436.15)

- CPU: Intel Core i7 6850K

**Comment by Armada651** [comment]
Please describe it in more detail, what is the problem you're seeing? "Image overlap" is too vague

**Comment by Armada651** [comment]
Also, if you added any settings manually to the stemvr.vrsettings such as enabling raw camera projection let me know.

**Comment by Charlster** [comment]
So I've actually found what the problem was. I had pseudovive installed to play Until You Fall on my Index. I simply deleted those files and it's worked fine since.

**Comment by lionheartng** [comment]
Yes, this resolved my issue too.  Thanks Charlster!
