### ISSUE TITLE
Steam hijacks game

### ISSUE THREAD

**Issue by Jdbye** [LibreVR/Revive#1325]
**Describe the bug**
Trying to use Revive, when I start a game Steam overlays the Big Picture UI on top, and I can't seem to close it. Not sure if SteamVR just doesn't like my controller (I don't have the Vive controllers) or what, but I should be able to play many Oculus games without Vive controllers, right?
Closing steam and leaving SteamVR open gets rid of the Big Picture UI, but I still have the SteamVR bar at the bottom that I can't get rid of and the game is grayed due to that.

**To Reproduce**
1. Install a game (in my case Lucky's Tale) and launch it
2. Steam Big Picture appears on top, obscuring the game and preventing input
3. Closing Steam and leaving SteamVR open gets rid of Big Picture but there is still a bar at the bottom, not accepting input and not letting it through to the game, and the game is grayed
4. Not sure where to go from here.

**Expected behavior**
Game should launch, accept input, and without Steam adding an overlay on top that can't be closed

**Environment (please complete the following information):**
 - App: Lucky's Tale
 - OS: Win10
 - Headset: Gear VR through RiftCat (this part seems to be working fine, but I will also be submitting a bug there just in case - I have used it successfully with SteamVR games however)

**Versions (please complete the following information):**
 - Revive: 1.8.0.6
 - SteamVR: How do I check?

**Additional context**
N/A

**Comment by Armada651** [comment]
That's just the regular dashboard, not a Revive issue.

Also I do not support RiftCat and will not accept any issue that doesn't reproduce on a proper VR headset.
