### ISSUE TITLE
Oculus Medium 2.3.3 not working

### ISSUE THREAD

**Issue by rufusw** [LibreVR/Revive#1326]
**Describe the bug**
The latest version of Medium (2.3.3) will not load - I see a spinning circle on the Steam dashboard Revive page, and no "loading" message at the bottom of the dashboard.

Medium 2.3.2 does still work with Revive 1.8.1.1

**To Reproduce**
1. Load SteamVR
2. Go to Revive page of dashboard
3. Click on Oculus Medium
4. Does not load

**Environment (please complete the following information):**
 - App: Oculus Medium 2.3.3
 - OS: Win10 1809
 - Headset: WMR Lenovo Explorer

**Versions (please complete the following information):**
 - Revive: 1.8.1.1
 - SteamVR: 1.7.15

**Additional context**
I also tried loading Medium 2.3.3 with Revive version 1.8 - does not load
I think I also tried Revive 1.7.3 unsuccessfully, however I can't be sure (It has been nearly a month since then)

**Comment by aphix** [comment]
Not loading for me either, Win7; latest Revive; latest OpenVR, Steam Beta (regular SteamVR did not work, either).

**Comment by aphix** [comment]
Any updates on this one?

**Comment by rufusw** [comment]
@aphix I will send you a onedrive link (via Discord) to the previous version of Medium (2.3.2), I have included instructions on where to put the files. Hopefully you can get it working!

**Comment by Armada651** [comment]
No need for that, I'm back from my vacation so I can now update Revive with support for it.

**Comment by Armada651** [comment]
@aphix Stepping through crashes is not useful, you'll need to either create a dumpfile (without heap) or post the stack trace of the first crash.

**Comment by Armada651** [comment]
Actually I just tried to run it with Revive 1.8.1.1 and Oculus Medium 2.3.3 and it works fine on Windows 10 1903. Seems to be an issue with your local setup.

I can see @rufusw is on Windows 10 1809 and @aphix is still on Windows 7. I recommend you both try to update to the latest version and then report back.

**Comment by rufusw** [comment]
Hmm, I'm not willing to update to 1903 yet, too many bugs! If that turns out to be the solution I'll stick with Medium 2.3.2 until I'm ready to go to 1903.

It seems odd that Medium 2.3.2 works fine, but not 2.3.3, especially as Medium 2.3.3 appears to only be 1 bugfix ["Fixed an occasional crash when selecting a Scene Graph node that didn't have an action menu (ie. the Grid node)"](https://forums.oculusvr.com/community/discussion/comment/699985/#Comment_699985) 

I suppose it's possible they changed something else and didn't mention it. (They never seem to mention SDK changes)

The WMR portal was updated 4 days ago, so I will try running 2.3.3 again

**Comment by Armada651** [comment]
Are you sure Revive is up-to-date?

**Comment by rufusw** [comment]
Yes Revive is up-to-date. Just to be sure I uninstalled it and downloaded a fresh copy. I tried uninstalling OpenVR Advanced settings, and tried both stable and beta of Steam, SteamVR, WMR for SteamVR. None of these permutations worked.

I tried loading Medium while looking at my desktop (by lifting my headset) - I saw a quick flash of a command prompt but nothing else.

I don't think OculusMedium.exe starts at all, or if it does it's only for a split-second.

**Comment by anothercaveman** [comment]
I have the exact same issue as @rufusw here is what I tried with:
**Valve Index
Revive 1.8.1
Medium 2.3.3
Windows 10 latest update just restarted for it.. 1903
Tried both 90 and 144hz.**
Thanks for taking the time @Armada651

**Comment by bassemprime** [comment]
I am having the same issue as @rufusw . It seems to fail to launch.

Latest Revive
Medium 2.3.3
HTC Vive
Windows 10

**Comment by Armada651** [comment]
Try this version, it still works fine for me: https://github.com/LibreVR/Revive/releases/download/1.8.2/ReviveInstaller.exe

**Comment by rufusw** [comment]
I just tried Revive 1.9 and it works! Thanks!

**Comment by anothercaveman** [comment]
Hello, I have just tried with the version you have linked (1.8.2), as well as the last one as rufusw said it worked for him, and it doesn't work.
Could it be not compatible with Valve Index :( ? Thank you.

**Comment by Armada651** [comment]
Make sure you don't have more than one Revive installation and try running the updater.
