### ISSUE TITLE
Blaze Rush does not work anymore 

### ISSUE THREAD

**Issue by cccpphil** [LibreVR/Revive#133]
Hello
Today with Revive and with Injector : Error Windows 10 "No permissions to run this game, error : Unable to find the HMD (1971039)"
This game worked perfectly yesterday...

**Comment by KLWN** [comment]
tried mine 5mins ago - still working perfectly with 360 wireless controller.

**Comment by cccpphil** [comment]
> Maybe you have accidently "configured" your not available Rift?

No. And the other games works.
I uninstalled and reinstalled Blaze Rush and Revive... but same problem.

**Comment by cccpphil** [comment]
I uninstalled and reinstalled the game, Oculus software (ccleaner, etc.), Revive, but always this error : 

Date: 2016-06-06 (Mon Jun 2016) Paris, Madrid (heure d?été) UTC+01:00

14:39:05.253        | //////////////////////////////////////////////////////////////////////////////
14:39:05.253        | //
14:39:05.253        | // Build: BlazeRush 457 (Apr  4 2016 16:21:25)
14:39:05.253        | //
14:39:05.253        | //////////////////////////////////////////////////////////////////////////////
14:39:05.253        | 
14:39:05.294   FATAL| No permissions to run this game, error: Unable to find the HMD (1971039)

**Comment by Rojoyinc** [comment]
I've never gotten this one to work

**Comment by KLWN** [comment]
strange, mine is working fine. Which OS are you using? Im on Windows 8.1

**Comment by cccpphil** [comment]
The game work again with the last Revive.

**Comment by LibreVR** [comment]
You mean version 0.6.2?

**Comment by cccpphil** [comment]
Yes

**Comment by LibreVR** [comment]
Nice, then this was a DRM issue too.
