### ISSUE TITLE
Failed to load action manifest

### ISSUE THREAD

**Issue by IngatlanForras** [LibreVR/Revive#1332]
Some games like Vader Immortal, and Defector with Revive 1.8+  wants to load Valve Index controller bindig (action manifest) from c:\Users\[USER]\AppData\Local\Revive\
It has existed only Revive version 1.8+, the bindings loads correctly on version 1.7.3
(same problem with latest Steam Vr non beta, and beta version too)
The Steam Vr controller settings wont load any previous or default binding, and I cannot create a new one in it.

Lone Echo works very well with 1.8 or later, but Defector and Vader Immortal works only with 1.7.3.

Sorry for my bad english, and many thanks to you for your help and your amazing Revive project.

I'm on:
Windows 10 1903 64 bit
Valve Index
i5-7500, 1080ti

**Comment by Armada651** [comment]
It sounds like you've patched these games explicitly with an older version of Revive when they weren't compatible yet.

You'll need to delete the xinput DLLs from the game executable folder to revert the patch.

**Comment by zwilliams0419** [comment]
> It sounds like you've patched these games explicitly with an older version of Revive when they weren't compatible yet.
> 
> You'll need to delete the xinput DLLs from the game executable folder to revert the patch.
> 
> **As a general rule you should never patch Oculus Store games**, it doesn't do anything differently from using the dashboard.

I think I may have run into the same issue by installing Asgard's Wrath prior to updating Revive. Could you tell me specifically where I'll find the xinput DLL? I've looked around in the game's install directory and I can't find anything that seems to match the description
