### ISSUE TITLE
Why does Revive seem to think I need to update every day or so

### ISSUE THREAD

**Issue by ntblood** [LibreVR/Revive#1335]
Why does Revive seem to think I need to update every day or so

**Comment by Armada651** [comment]
I assume you did try updating at least once to version 1.8.1.1? In any case I have made 1.8.1.0 the highest version number as a temporary workaround.

**Comment by ntblood** [comment]
Yes, I've updated it many times before I finally started wondering and paying attention ; )  
  Thank you

**Comment by ntblood** [comment]
Actually, this is the message I get, "Revive 1.8.1.0 is now available (you have 1.8.0.6). Would you like to download it now?"   Well, even after downloading and installing it several times I'm still getting this message. I don't know how I could be doing something wrong.

**Comment by Armada651** [comment]
It sounds like you may have multiple versions of Revive installed in
multiple locations.

>

**Comment by ntblood** [comment]
I only have one installation of Revive that I'm aware of.
