### ISSUE TITLE
Left menu button isn't working with index controllers

### ISSUE THREAD

**Issue by McBubbel** [LibreVR/Revive#1339]
The left menu button doesn't work with index controllers, while the right menu buttons works fine. 

**Environment (please complete the following information):**
 - App: Rick & Morty
 - OS: Win 10 64bit 1809
 - Headset: Index

**Versions (please complete the following information):**
 - Revive: 1.8.1
 - SteamVR: 1.7.15

**Comment by Armada651** [comment]
Fixed in the new release: https://github.com/LibreVR/Revive/releases/tag/1.8.2
