### ISSUE TITLE
touch pad rebinding

### ISSUE THREAD

**Issue by naossoan** [LibreVR/Revive#1348]
Hello. I just bought Asgard's Wrath and I am finding it extremely difficult to move around with the default touch pad bindings on the OG Vive wands. The area of the touchpad dedicated to be a "joystick" is too small for me and it's increasingly frustrating to play the game as these enemies get harder. The joystick is very janky and doesn't respond well in its default position and I am just getting wrecked by the enemies that I have to dodge their lethal attack.

Is there any way for me to adjust this? I saw in recent posts that there used to be a scripting method to change this but that it replaced now with the SteamVR controller options screen.

Well, I looked through there and I am not seeing anything related to what I am talking about. It just has the basic bindings of the Vive wands.

I'm sounding whiney, which, fair enough, but don't let it detract from how thankful I am for this software in the first place!! You're a godsend!

If it was more like this....
![image](https://user-images.githubusercontent.com/50346831/66625417-5c318a00-ebb1-11e9-87fa-adb6257cf9df.png)

**Comment by Armada651** [comment]
Actually the diagram is slightly misleading. The entire pad area is
available for joystick movement, it's only when you press down that those
areas determine which button is pressed.

In actuality the thumbstick works based on swipes. Just swipe across the
touchpad which direction you want to move in. The thumbstick will always be
centered on where you first touch the pad.

I should update the wiki to explain that more properly.

**Comment by naossoan** [comment]
Ah ok I will give this a try today. I thought only that area would work properly as the joystick so I was trying to constrain my thumb to that area which as you could imagine was a bit of a nightmare. Hopefully it improves my mobility!

**Comment by naossoan** [comment]
> 
> Actually the diagram is slightly misleading. The entire pad area is available for joystick movement, it's only when you press down that those areas determine which button is pressed. In actuality the thumbstick works based on swipes. Just swipe across the touchpad which direction you want to move in. The thumbstick will always be centered on where you first touch the pad. I should update the wiki to explain that more properly.

Is there a way to remove the dead-zone on the trackpad for movement?

**Comment by Armada651** [comment]
There isn't, but you can keep it centered on the center of the trackpad by
unbinding the recenter action from trackpad touch.

Op za 12 okt. 2019 om 03:38 schreef naossoan <notifications@github.com>:
