### ISSUE TITLE
Supports only the default directory of the oculus library

### ISSUE THREAD

**Issue by LuckMic** [LibreVR/Revive#1349]
I moved a game in my oculus library from my default storage to a different location. After that the game is not listed anymore in Revive. After changing the second one as the default path, it will be shown in Revive but all the other games are gone.

**Expected behavior**
It would be great if Revive would handle all configured library pathes.

**Environment (please complete the following information):**
 - Win10
 - Index

**Versions (please complete the following information):**
 - Revive up-to-date:
 - SteamVR up-to-date beta one

**Comment by Armada651** [comment]
Duplicate of #928
