### ISSUE TITLE
AirMech: Command entitlement error

### ISSUE THREAD

**Issue by thepotatoman23** [LibreVR/Revive#135]
It basically the same as [issue 65](https://github.com/LibreVR/Revive/issues/65) where the headset keeps at the Vive homescreen and there's no audio even though the game loads up on the desktop with working headtracking. However, this time there's an additional message saying "Failed to acquired entitlement from Oculus. Game will now exit", with it exiting when you hit the A button, which can only be seen on the desktop window.

[screenshot](https://i.imgur.com/5E4LaqV.jpg)

**Comment by LibreVR** [comment]
Fixed now that the headset check was moved out of the DRM.
