### ISSUE TITLE
Quill 2.0 not working?

### ISSUE THREAD

**Issue by MariaLiljenhjerte** [LibreVR/Revive#1351]
Hello :)

I've installed the latest version of Quill via Oculus home. 
I'm up-to date with Nvidia GFX drivers, SteamVR and Revive itself. (non-beta)
My VR kit is the Valve Index.

Sadly Quill does not seem to be opening. Is this a known issue at this time? 

My specs:
Core I7-6700K
32 GB DDR4-3200
Nvidia GTX 980TI

Thanks in advance.

**Comment by MariaLiljenhjerte** [comment]
Update: I've tried the Revive pre-release. Oddly enough it seemed to load, but then gave me:
"You have a pending hardware issue that is preventing you from entering VR "

On 2nd and 3rd retry it went back to the endless loading circle as it did before.

**Comment by Armada651** [comment]
I cannot reproduce it. Have you tried running any other Oculus apps?

**Comment by MariaLiljenhjerte** [comment]
Damn. Just my luck.
Yes, I have. The ones that come "pre-installed" work flawless. I have also tried Bullet Train. No problems there either. Only app that is refusing is Quill. Could it have something to do with there being a free and paid version (in the past). The only option I am seeing after installing Oculus Home is the free version.

**Comment by MariaLiljenhjerte** [comment]
Update: I've installed Medium to further test if problems might occur with other applications. I am able to open it without problems. So the problem seems to remain exclusive to Quill on my end.

**Comment by MariaLiljenhjerte** [comment]
Update: A clean install of Windows 10 (ver 1903) fixed the problem. I'm still unsure what initially might have caused it. I'm suspecting a combination of Adobe Creative Cloud, Autodesk or HTC Viveport. I tried uninstalling all of them beforehand. But maybe they left some "residue" behind somewhere in the registry? Thank you for your time trying to reproduce the issue.
