### ISSUE TITLE
Asgard's Wrath - stuck on 'Game Paused' screen

### ISSUE THREAD

**Issue by madpat3** [LibreVR/Revive#1356]
**Describe the bug**
After starting the game you come to a Point where it says: "look here". after that the game pauses and there is Nothing you can do to unpause it.

**To Reproduce**
1. Start the game and wait until it pauses forever.

**Expected behavior**
The game should start.

**Environment (please complete the following information):**
 - App: [Asgard's Wrath]
 - OS: [e.g. Win10]
 - Headset: [WMR]

**Versions (please complete the following information):**
 - Revive: 1.8.1 and 1.8.2 (tried both)
 - SteamVR: beta 1.8.12

**Additional context**
https://github.com/LibreVR/Revive/issues/1350#issue-505860769

**Comment by DawsSangio** [comment]
Do not use Steam beta.

**Comment by madpat3** [comment]
after returning to steam vr 1.7.15 it finally works.

**Comment by kakek** [comment]
The problem has now propagated to main branch of SteamVR.
Issue should be reopened.

**Comment by SonOaMonkey** [comment]
Having this same issue with Vader Immortal.
