### ISSUE TITLE
Can't access oculus store

### ISSUE THREAD

**Issue by avspap** [LibreVR/Revive#136]
Hi there 
I started the set up process by mistake. Know when I open the oculus app it tells me to finish in headset. I unistalled and reinstalled but does the same thing.  How do I get back to the store? All of my downloads are gone. Please help!

**Comment by wissper** [comment]
go to a command prompt and type "net stop ovrservice"

go to c:\users\<yourname>\appdata\roaming\oculus\sessions and rename the folder _oaf to _oaf.old 

type "net start ovrservice"

load home and log into the store

**Comment by avspap** [comment]
It worked! Thank you!!

**Comment by avspap** [comment]
It worked! Thank you!!

**Comment by wissper** [comment]
Cheers
