### ISSUE TITLE
Vader Immortal Episode II Menu Freeze

### ISSUE THREAD

**Issue by mapotter99** [LibreVR/Revive#1360]
**Describe the bug**
Upon clicking Start Game, the game begins to start, and then opens the menu again, but no hands are visible to select anything and audio is frozen. 

**To Reproduce**
1. Open Vader Immortal Episode II
2. Press the Start game button. 
3. Wait for game to start. 
4. Menu re-appears with no hands and frozen audio. 
5. Can sometimes workaround this by pressing the touchpad button to resume. 

**Expected behavior**
The game should begin. 

**Environment (please complete the following information):**
 - App: Vader Immortal Episode II
 - OS: Windows 10, latest updates
 - Headset: Index

**Versions (please complete the following information):**
 - Revive: 1.8.0, 1.8.1, 1.8.2 (touchpad to resume does not seem to work on 1.8.2)
 - SteamVR: 1.8.12 beta

**Additional context**

**Comment by mapotter99** [comment]
UPDATE: Switching to the release version of SteamVR resolves the issue for 1.8.0 and 1.8.1. 

1.8.2 results in an Unreal engine crash after pressing the start button.

**Comment by Armada651** [comment]
Fixed in 1.9.0
