### ISSUE TITLE
Install Occulus Home? There's no 'Occulus Home' selection.

### ISSUE THREAD

**Issue by starsentinel** [LibreVR/Revive#1361]
**Which game or application is your request about?** 
Installation Question - 'Occulus Home' isn't an option

**Is your request related to a problem? Please describe.**
Revive Installation Guide - Step 1 - Install 'Occulus Home' but there isn't a 'Occulus Home' option. Can someone please clarify this?

**Describe the solution you'd like**
Occulus Home isn't an option. Do I need to select 'Download Software' for the Occulus Rift?

**Describe alternatives you've considered**

**Additional context**
Thanks for your help!!

**Comment by starsentinel** [comment]
Thanks! Do I need to select 'Download Software' for the Occulus Rift or the Rift S?

**Comment by Armada651** [comment]
Fixed: https://github.com/LibreVR/Revive/commit/32051905a9b0c30ed706f0bf8e6941487425986e

**Comment by Armada651** [comment]
It doesn't matter which one you download, they link to the same installer.
