### ISSUE TITLE
First Contact has no haptic feedback

### ISSUE THREAD

**Issue by hundenmarvin** [LibreVR/Revive#1366]
I don't think it has ever had any haptic feedback with revive if I remember correctly. I think this has allways been the case on my Vive and now on my Index with my Index controllers there is no haptic feedback either. I assume it has to have haptic feedback on Oculus since it's their introduction to touch. I am playing on windows 10.

**Comment by Armada651** [comment]
First Contact never calls any of the haptic functions, not even the functions that query for haptics support. The only thing I can conclude is that First Contact is using some old version of the haptics functions.
