### ISSUE TITLE
Auto-update doesn't work

### ISSUE THREAD

**Issue by Xodetaetl** [LibreVR/Revive#1367]
I think for as long as I've used Revive, updating the app never worked. An update shows up, I validate the installation, it looks like it installs normally and says it's successful. But the next time I launch VR or if I check for updates, it says it's still the old version and asks if I want to update again.
And I end up dowloading & installing the new version manually.

- Win 10
- Current version: 1.9.0.1
- Version proposed to update to: 1.9.1.3
- Default install folder (Program Files\Revive)
- Regular SteamVR

**Comment by Armada651** [comment]
This was a typo in the update manifest for 1.9.1, it's fixed now so updating will work correctly.
