### ISSUE TITLE
From the Other Suns Performance degrade

### ISSUE THREAD

**Issue by optimumbox** [LibreVR/Revive#1369]
Performance on this version of this version of revive has dropped tremendously. I've dropped from 120fps with little to no reprojection to around a 70-80 fps max. 

Specs:
3900x
DDR4 3600 B-Die 18 18 18 38 56
2080ti FTW 3 
Game on SSD

**Comment by Armada651** [comment]
Should be fixed in the 1.9.1.4 hotfix, can you try downloading 1.9.1 again? https://github.com/LibreVR/Revive/releases/tag/1.9.1
