### ISSUE TITLE
Most games don't display anything in the mirror window

### ISSUE THREAD

**Issue by Glibber** [LibreVR/Revive#137]
"Farlands" is working just fine in VR but the game window on the monitor is empty/black,
Currently I'm showing my Vive to all my friends and my family and I noticed that every other Game I tried so far can be monitored on the PC monitor, but not Farlands.
Maybe its another AMD issue (Radeon R9 390, Win7, 16GB, i5 3570K @ 4.2GHz).
But let me thank you again for making it possible to play these games at all.

**Comment by LibreVR** [comment]
The mirror window has been a constant issue, for most games it doesn't work at all. Still not sure what causes it.

**Comment by CodingCanuck** [comment]
Is there any debug information we can provide to help diagnose this?

**Comment by LibreVR** [comment]
You'll have to wait until I have time to work on this issue, since it doesn't prevent you from actually playing this game it's not a very high priority to fix it.

**Comment by LibreVR** [comment]
Low priority issue, postponed until version 0.8.

**Comment by LibreVR** [comment]
Fixed in commit 004644074d20a00b17d2a5ffd5dbbfd15f125609.
