### ISSUE TITLE
Asgard's Wrath - Pending hardware error 

### ISSUE THREAD

**Issue by TheUNkilled123** [LibreVR/Revive#1373]
**Describe the bug**
Every time I try to launch Asgard's wrath(tired injecting) I get the good old message: You have a pending hadware error that is preventing you from entering VR.
When that happened for the first time, I updated my oculus software(reinstall) and my revive(reinstall), but to no avail. 
I've tried everything I know but still nothing.
And also in the oculus home software, i always get the: "Your rift was not recognised, please plug it in" and it's asking me to set it up.
I really don't know what to try anymore...

**To Reproduce**
Just trying to start Asgard's Wrath...

**Environment (please complete the following information):**
 - App: Asgard's Wrath
 - OS: Win10
 - Headset: OG HTC Vive

**Versions (please complete the following information):**
 - Revive:1.9.1.5
 - SteamVR:1.7.15(non beta)
 
**Additional context**

**Comment by TheUNkilled123** [comment]
UPDATE-FIXED: So I also tried to update steam vr to the beta version, and in the middle of updating, i notice that my headset was not plugged in the outlet... Mind you it was plugged in before I updated everything, but not after, so the solution is update everything, and remember to plug in your headset...

**Comment by doutatsu** [comment]
I have the same problem, everything updated. Try restarting SteamVR multiple times, nothing works

**Comment by thadrine** [comment]
Tried latest updates, and latest betas. Still will not work.
