### ISSUE TITLE
Reviveinjector virus warnings

### ISSUE THREAD

**Issue by MungusPlop** [LibreVR/Revive#1377]
**Which game or application is your request about?**
[e.g. First Contact]
Greenwater
**Is your request related to a problem? Please describe.**
When running Greenwater, my Avast has started giving virus warnings for IDP.GENERIC and IDP.ALEXA.51 viruses in reviveinjector. It has also given these warnings when installing revive.
**Describe the solution you'd like**
I want to know if these viruses are real or false positives.

**Describe alternatives you've considered**
I've considered allowing them, but with IDP.ALEXA.51, it is very risky

**Additional context**

**Comment by zxsdklfhskyrvk** [comment]
Have you tried submitting the relevant files to Virustotal to see what the broader view is on the files?

**Comment by qlyoung** [comment]
Revive source is freely available here on GitHub if you'd like to verify that there is no malware included. DLL injectors are frequently misclassified by AV programs. Unfortunately we cannot tell you if your antivirus program is detecting a legitimate threat in the game itself.
