### ISSUE TITLE
Pistol Whip Black Screen in headset

### ISSUE THREAD

**Issue by drowhunter** [LibreVR/Revive#1383]
**Describe the bug**
Shows on desktop, not in headset.

**To Reproduce**
Play Pistol whip

**Expected behavior**

**Environment (please complete the following information):**
 - App: Pistol Whip
 - OS: Win10
 - Headset:  Pimax 5k+

**Versions (please complete the following information):**
 - Revive:
 - SteamVR:

**Comment by mautere** [comment]
Had the same issue. Finally got it to work by reinstalling Pistol Whip on Oculus Store.

**Comment by darkuni** [comment]
> Had the same issue. Finally got it to work by reinstalling Pistol Whip on Oculus Store.

Are you suggesting that if we get this issue, we should uninstall and reinstall Pistol Whip and the problem should sort itself out?

**Comment by mautere** [comment]
> 
> 
> > Had the same issue. Finally got it to work by reinstalling Pistol Whip on Oculus Store.
> 
> Are you suggesting that if we get this issue, we should uninstall and reinstall Pistol Whip and the problem should sort itself out?
> 
> Because it didn't work for me.

Well damn. It did work for me.Though I did also try literally everything else before that, including reinstalling SteamVR, Revive and the Oculus app, but nothing seemed to help until I reinstalled Pistol Whip.

**Comment by drowhunter** [comment]
Strangely enough that worked for me too, ok well i guess its ok then..Ill close this
