### ISSUE TITLE
Can't start Medium on Revive 

### ISSUE THREAD

**Issue by anothercaveman** [LibreVR/Revive#1388]
**Describe the bug**
Hi!
So I never have been able to launch Medium through Revive, I have a Valve Index.
I followed the previous similar issue reported on Github and tried the different methods (versions, beta versions etc...) but nothing to do it just does not launch, ever.

**To Reproduce**
Launch SteamVR, Open Revive through the menu, Pick Medium. It says Next: Medium in a small window, but never launches.

 - OS: Win10 latest update
 - Headset: Index

**Versions (please complete the following information):**

    Revive: 1.9.1.5
    SteamVR: 1.8.20

thank you very much.

**Comment by anothercaveman** [comment]
Hello I have found the issue causing the problem: there is an accent in my Windows 10 user name. It worked after opening a new session without accents. Thx

**Comment by qlyoung** [comment]
@anothercaveman out of curiosity, how did you discover that that was the problem?

**Comment by rufusw** [comment]
It was mentioned by the devs on the oculus medium forum

**Comment by qlyoung** [comment]
Fascinating. Thanks for the info.

**Comment by Armada651** [comment]
Revive had this exact same problem for a while with its action manifest
until I moved those files out of the user app data. People with accents in
their username would not have working input because of that.
