### ISSUE TITLE
Revive Dashboard Loading Multiple Processes But Not Working  - OSVR via SteamVR

### ISSUE THREAD

**Issue by Proxishh** [LibreVR/Revive#139]
Using an OSVR via the latest SteamVR drivers in Direct Mode.

The Standalone Revive Injector works for War Thunder on Steam, but I cannot get the Revive Installer to work.

There is no option in the the Oculus Store for Revive.
Every time I launch the Revive Dashboard, it just loads more and more of the same background process.

Using latest Oculus Store and SteamVR Driver on Windows 10 64x, 4770k, GTX 970.

If you need any more info, please let me know.

**Comment by iamwes** [comment]
Revive doesn't load anything that shows up in the oculus store. You download the game from oculus.  Then open up steamVR put the headset on and you will see a new tab at the bottom called Revive.. where all the oculus games show up

**Comment by Proxishh** [comment]
Ah, that explains that then. Thank you for explaining. 

I'm running into another issue at the moment though. The SteamVR Dashboard is currently not working with the OSVR. Do you have another method I can use to bring up the Revive Dashboard without using the SteamVR Dashboard?

**Comment by iamwes** [comment]
Afraid I can't help with that one as I have a Vive so not tried an OSVR headset. Although the injector way should work... does load the revive injector, copy all the files into the game folder (game you want to play) then drag and drop the game.exe onto the 64x injector... there are instructions somewhere on this site.

**Comment by Proxishh** [comment]
Unfortunately the Injector doesn't seem to work, using the Standalone results in a "Cannot run this application without an Oculus Rift".

**Comment by Armada651** [comment]
Pretty sure they fixed the dashboard by now, feel free to leave a comment here if you want to reopen the issue.
