### ISSUE TITLE
After Windows update 1909, games don't launch from Revive anymore

### ISSUE THREAD

**Issue by hyperh** [LibreVR/Revive#1395]
**Describe the bug**
Updated to Windows update 1909, games don't launch from Revive anymore.

**To Reproduce**
1. Start Steam VR
2. Open Revive tab
3. Launch a game
4. It just sits there loading forever.

**Expected behavior**
Expected it to load the game eventually.

**Environment (please complete the following information):**
 - App: all Oculus games
 - OS: Win 10
 - Headset: Samsung Odyssey

**Versions (please complete the following information):**
 - Revive: 1.9.1.5
 - SteamVR: 1.8.21

**Additional context**

**Comment by hyperh** [comment]
Rolled back some of the updates and games actually start to load again.

**Comment by DanDon** [comment]
> Rolled back some of the updates and games actually start to load again.

I'm also having this issue. Did you roll back the entire of the Windows 1909 update or just some other KB numbers?

**Comment by hyperh** [comment]
@DanDon I rolled back a bunch actually, whatever I had installed that day. And I actually continued to have problems. So I reinstalled them.

I found that Windows Audio Device Graph Isolation keeps taking up a lot of CPU and RAM. If I open a Revive game, I open up the Process Manager at the same time and I manually kill the Windows Audio Device Graph Isolation process and the game loads after that.

**Comment by DanDon** [comment]
**I may have found a fix for my issue.**

I uninstalled the beta version of the Oculus Desktop app and installed the standard public release. This has made revive work fine and I'm still on the Windows 1909 and all latest updates.

This is not to say what I did will help you but this ticket is for Windows 1909 update and I can confirm its working correctly on Windows 1909.

**Comment by hyperh** [comment]
Hmm it seems to be back to normal. To be honest I'm not sure what combination of things I did to change things. Could be any number of the following:

1. Restoring the 1909 update
1. Recent Windows updates after 1909
1. [Disabling Game Mode](https://www.reddit.com/r/VRGaming/comments/e7g4lt/psa_for_windows_10_users_turn_off_game_mode/)
