### ISSUE TITLE
Steam Boundaries cause slowdown?

### ISSUE THREAD

**Issue by AverageAlexander** [LibreVR/Revive#1397]
Asgard's Wrath

**Is your request related to a problem? Please describe.**

I have a 3800x, with 16GB of 3200MHZ ram and a 2080 super. I've got the game running from the System's onboard M.2 drive and when the boundaries come up I experience a chug in framerate like I've never seen before. Gameplay otherwise seems pretty smooth aside from the tavern, but it could be for the same reason.

Not sure if this translates to other revive games as I'm running the Index. Any thoughts? Was really looking forward to this one.

**Comment by Pogman** [comment]
Currently any Steam overlay that shows onscreen causes this issue with AW. I disable the boundary using advanced settings as a workaround.

**Comment by AverageAlexander** [comment]
Ah, that's a bummer to hear. But good to know that. You're talking advanced settings via the Steam VR options?

**Comment by Pogman** [comment]
[OpenVR-AdvancedSettings](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings) is what I use and then accessed in SteamVR in the headset.

**Comment by AverageAlexander** [comment]
Ok, I'll check it out. thanks for your help!
