### ISSUE TITLE
Chronos failing entitlement check with latest Injector

### ISSUE THREAD

**Issue by kbdrand** [LibreVR/Revive#140]
In the Wiki it shows Chronos as working, but when I fire it up using the Injector 64 bit it loads but then gets further into the game and fails the Entitlement check.

**Comment by LibreVR** [comment]
Are you using the latest version of Revive? Can you post your logs from `%APPDATA%\Revive`?

**Comment by kbdrand** [comment]
I'm using the Installer and Injector from 11 days ago (pre-compiled versions). Here are the logs.

[ReviveInjector.zip](https://github.com/LibreVR/Revive/files/302688/ReviveInjector.zip)

**Comment by ProfessorS1** [comment]
I am having the same exact issue. 
I am using the Revive version required for Edge of Nowhere. Everything else works as is on the page and it worked under Oculus 1.4 using the downgrade. Then, out of nowhere, I am getting the same message.  Here is my log:
Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/insomniac-games-edge-of-nowhere/EdgeOfNowhere.exe"
Creating process: C:\Program Files\Oculus\Software\insomniac-games-edge-of-nowhere\EdgeOfNowhere.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xff6974d0
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xff6974d0
Injected dlls succesfully

and
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/gunfire-games-llc-chronos_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/insomniac-games-edge-of-nowhere_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-lost_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Manifests/vrideo-inc-vrideo-rift_assets.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/epic-games-showdown.json
Found assets bundle gunfire-games-llc-chronos_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/gunfire-games-llc-chronos.json
Found assets bundle insomniac-games-edge-of-nowhere_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/insomniac-games-edge-of-nowhere.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-lost_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-lost.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/playful-luckys-tale.json
Found assets bundle vrideo-inc-vrideo-rift_assets
Loading application manifest: file:///C:/Program Files/Oculus/Manifests/vrideo-inc-vrideo-rift.json
Found application epic-games-showdown
Found application gunfire-games-llc-chronos
Found application insomniac-games-edge-of-nowhere
Found application oculus-dreamdeck
Found application oculus-lost
Found application oculus-oculus-video
Found application playful-luckys-tale
Found application vrideo-inc-vrideo-rift


Sorry I could not get the zip to work.

**Comment by ProfessorS1** [comment]
any ideas guys>

**Comment by wissper** [comment]
Try taking the injector files from the x64 folder of revive 0.5.2 (or 0.6.0 I suppose) and put them in the win64-shipping.exe binary directory directly - (libOVRplatform64_1.dll, libRevive64_1.dll and openvr_api.dll).  Also copy the reviveinjector_x64.exe to the binary directory.  Drag and drop like normal - see if that gets you past the entitlement check (and hopefully load the game).  I am trying to figure out a hack to make the game work on VRidge unsuccessfully, but I have been able to bypass the entitlement check and hmd / sensor error this way.  If that doesn't work make sure all three of those files are in the x64 subfolder in the binary directory.

**Comment by LibreVR** [comment]
Should work now that the headset check has been removed from the DRM.
