### ISSUE TITLE
Vader Immortal Episode 3 is Show old OC controller, VIVE controller key invalid

### ISSUE THREAD

**Issue by 171753355** [LibreVR/Revive#1402]
Vader Immortal Episode 3 Crack =Oculus Rift Bypass &Vive-WMR Bypass
Contains the “ReviveInjector_x64.exe”  program，It is not valid to open through ReviveOverlay
so，”C:\Program Files\Revive\Input  ”  Change to ”\Administrator\AppData\Local\Revive\Input”
 copy json is still not recognized by the VIVE controller
Games like this come with  “ReviveInjector_x64.exe”，How to operate and set up to use the VIVE controller？  Please Help me

**Comment by Armada651** [comment]
Don't use Revive for piracy

**Comment by tompotter100** [comment]
htc cosmos the same here
