### ISSUE TITLE
Any chance on support Oculus Quest to play WMR games?

### ISSUE THREAD

**Issue by AceHack** [LibreVR/Revive#1414]
I would love to be able to play Halo Recruit with my Quest, I have a lot of WMR games from Windows Store.

**Comment by Armada651** [comment]
That would be a completely different project that has no relation at all with Revive. There is no commonality there.

**Comment by shinebacksoftware** [comment]
"I would love to be able to play Halo Recruit with my Quest," you seriously aren't missing much. Watch a youtube video and you will see why. Totally not worth it.
