### ISSUE TITLE
positionnal tracking

### ISSUE THREAD

**Issue by gaelios123** [LibreVR/Revive#142]
hello, is it normal that i have not the positionnal tracking ?

i have head tracking but not the positional, and this with every games of oculus store like
chronos,blazerush,shuffle ....
steam vr is correctly setup i think...
i use oculus rift with revive inject...
i have read all post but i cant find an answer

thank you

**Comment by SchmockLord** [comment]
No it isn't normal. I could walk forward in Oculus dreamdeck to view over the corner in the scene where you stand on top of a skyscraper.

**Comment by LibreVR** [comment]
> i use oculus rift with revive inject...

Why would you use Revive with the Oculus Rift?
