### ISSUE TITLE
Menu/Library in oculus Home

### ISSUE THREAD

**Issue by TimSundt** [LibreVR/Revive#1423]
Oculus Home on quest through revive.

To get up the library in home you need to press the left oculus button. But if I do I go to vrdesktop. If I hold the button I go to steam vr overlay. The right oculus button either centers the vr if held opens the actual quest home screen( might have mixed up the left and right if it opens vrdesktop or quest home. But you understand the problem)

**Describe the solution you'd like**
Is there a way to remap which button opens the library. Or isnt it worth the fix. Is it easier to just launch apps through the revive. 

**Describe alternatives you've considered**
Everything has been working fine or Ive been able to fix so far. Only problem is that some app(minecraft for instance) dont always actually start through the revive, thought it might help to launch through home but this might not matter at all?

Amazing app thank you for all your hard work. Got a new modem today so now I can stream wirelessly without loss or lag :)

**Comment by Armada651** [comment]
That's not possible to fix, it's simply the result of running SteamVR on top of the Oculus runtime.
