### ISSUE TITLE
Stormland dominant hand issue. 

### ISSUE THREAD

**Issue by astonishmints** [LibreVR/Revive#1424]
**Describe the bug**
After starting the game, stormland wont let me progress past the scene where you pull the trigger to select your dominant hand.

**To Reproduce**
Start stormland 

**Expected behavior**
The program will not recognize that I am pulling on the trigger of my dominant hand.

**Environment (please complete the following information):**
 - App: Stormland 
 - OS: Windows 10 64 bit
 - Headset: Index
**Versions (please complete the following information):**
 - Revive: 1.9.2
 - SteamVR: 1.9.13

**Additional context**
I have tried rolling back drivers. I have even gone as far as to format my SSD and do a fresh install of windows. The triggers actuate in game, but it wont progress. I can supply a video if needed.

**Comment by Armada651** [comment]
The proximity sensor in your headset might be badly calibrated, can you try inserting something in front of the sensor?

**Comment by astonishmints** [comment]
Thank you. It was the proximity sensor
