### ISSUE TITLE
Ive got Adrift (Steam) working on the Vive, with Revive patch

### ISSUE THREAD

**Issue by iamwes** [LibreVR/Revive#143]
People may already know how to do this but everything ive read says Adr1ft does not work with Revive... i managed to get the Steam version working anyway, i started a thread with instructions for people in case anyone is interested: http://steamcommunity.com/app/300060/discussions/0/350533172680477831/

**Comment by gormanj** [comment]
Confirmed working! Thank you very much. You have to wait a bit on the white screen. Awesome!

**Comment by LibreVR** [comment]
Nice, I guess it's because it doesn't use the Oculus DRM.
