### ISSUE TITLE
ReviveInjector.exe: Today 20 out of 71 on Virustotal give alert - Still safe?

### ISSUE THREAD

**Issue by mrshantiman** [LibreVR/Revive#1431]
**Which game or application is your request about?**
[e.g. First Contact]

**Is your request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sitte** [comment]
I am also concerned about this: https://www.virustotal.com/gui/file/3dbec76cbbdb306885fab9489c288034274145a9e463a84f00a94812c93a724c/detection

**Comment by Armada651** [comment]
It looks like more viruses started using MinHook for injection. I'm working on rewriting the injector with Detours which is used by Microsoft so that should solve the issue.

**Comment by mrshantiman** [comment]
Thank you.
