### ISSUE TITLE
Defector: I can't nod the head

### ISSUE THREAD

**Issue by Megaace23** [LibreVR/Revive#1434]
**Describe the bug**
The first scene of the game ask you to nod the head. I move my head in every direction, and the game is waiting the nod...

I use Revive 1.9.2.0 and Samsung Odyssey Plus.
**To Reproduce**
First scene of the game. I put the earpiece and a character ask me to nod the head. I nod in every direction, but the game is waiting the nod.

**Expected behavior**
The game register the nod

**Environment (please complete the following information):**
 - App: Defector
 - OS: Win 10
 - Headset: Samsung Galaxy Odyssey Plus

**Versions (please complete the following information):**
 - Revive: 1.9.2.0
 - SteamVR: 1.9.16 (the last beta)

**Comment by Megaace23** [comment]
Why the thumb down, @Foojoo? I think it is a Revive question, isn't it? With a Rift it doesn't happen...

**Comment by Foojoo** [comment]
Because if you used the search function, you would see the issue has been opened before.  Don't clutter up the board with redundant issues.

https://github.com/LibreVR/Revive/issues/1312

**Comment by Megaace23** [comment]
I searched the problem, and the two same issues are closed without a solution, and I can't write on them (I tryed).
I don'l know why they are closed without a solution, but the problem is real because it is happening to me.

**Comment by Foojoo** [comment]
"If you are really running a legit copy the only remaining explanation is a bug in the WMR SteamVR driver. In that case you'll have to take the problem to Microsoft."

They're closed because they are solved.  It's not a Revive issue, it's an issue with Windows Mixed Reality headsets.

**Comment by Megaace23** [comment]
Sorry, I didn't find that answer. And yes I am running a legit copy, bought two days ago at Oculus' Sales.

Sorry about it. I am the first who don't like to open redundant issues. :(  My fault.
