### ISSUE TITLE
Lone Echo crashes pc if hit by free flying organic material

### ISSUE THREAD

**Issue by thomasfrobieter** [LibreVR/Revive#1438]
**Describe the bug**
Everything works fine, for many hours. Now i´m in the ship which has arrived from the anomaly, my whole computer crashes if organic material hits me (so i would die/getting damaged normaly). This has worked in previous areals of the ship, i took damange on the first hit and respawned as awaited on the second.. or third hit. 
Instead of respawning it crashes in the moment the oranic material hits me. The Valve index turns off, the graphic card spinners go to full speed and i have to perform a hard reset.

**To Reproduce**
1. Enter the anomaly ship
2. Follow the story progress till you are on the atlas computer (replace the power cells and stuff..)
3. Search for the Crew. After the second door (the one you need to open with your laser), i experienced the crash multiple times after being hit by this tiny free flying oranic material.

**Expected behavior**
Take damage (or die and respawn). As i had no damage at this point, i've just expected damage.

**Environment (please complete the following information):**
 - App: Lone Echo
 - OS: Windows 10, latest updates
 - Headset: Valve Index
 - CPU: i7 9700k (not overclocked)
 - GPU: Nvidia Geforce RTX 2080 Super, latest driver
 - RAM: 16 GB DDR4

**Versions (please complete the following information):**
 - Revive: 1.9.2
 - SteamVR: 1.9.16 (no beta)

**Comment by Armada651** [comment]
There's no way this is caused by Revive, try updating your graphics driver. And if that doesn't work there's something wrong with your PC.

**Comment by thomasfrobieter** [comment]
Thank you very much for clarification!
Turns out that my PSU is very likely to weak.
