### ISSUE TITLE
Blank tab in Revive Dashboard

### ISSUE THREAD

**Issue by Jossss1841** [LibreVR/Revive#144]
Hello! I can't seem to get Revive work. I followed the instruction for the installation. When everything's done I launch steam VR, the dashboard icon is there and i can click it with the controller but when it opens it is just a blank blue tab with nothing in it. I've tried to uninstall/reinstall. I'm using the 0.6 version and I have Oculus Home installed.
I can't seem to find the problem. Any idea?

Thank you very much!

**Comment by LibreVR** [comment]
Please post your logs from `%APPDATA%\Revive`.

**Comment by Jossss1841** [comment]
Thanks for the answer, here is the log : 
libpng warning: iCCP: known incorrect sRGB profile
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///H:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///E:/Oculus/
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-client.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-compat.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-diagnostics.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-dreamdeck-nux.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-drivers.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-home.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-librarian.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-overlays.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-redistributable-installer.json
Loading assets manifest: file:///e:/Oculus/Manifests/oculus-runtime.json
Loading assets manifest: file:///e:/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///E:/Oculus/Manifests/playful-luckys-tale.json

Thanks you!

**Comment by LibreVR** [comment]
Looks like a normal log, the tab should at least contain Lucky's Tale.

**Comment by Jossss1841** [comment]
hum hum... my bad, I was expecting to see something in the tab even without any games installed. So I installed Lucky's Tail and everything worked just fine. Sorry for the inconvenience ^^.

Thanks you again!
