### ISSUE TITLE
Permission Issue causing degraded performance in VR (debugview log details inside)

### ISSUE THREAD

**Issue by dolandmac** [LibreVR/Revive#1442]
hi,

Firstly, thank you for your time. Any assistance on this topic would be greatly appreciated... i have personally ran out of ideas. 

- some games were crashing. i eventually broke down and ran debugviewer from windows sysinternals and found a repeating error "CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied"
- I removed revive and re-installed steamvr clean using the following tutorial:https://steamcommunity.com/app/250820/discussions/2/1640917625015598552/?tscn=1567730134
- It works fine again with no spamming error in debugviewer
- I eventually went back to re-install revive, and it worked briefly without complications.
- I re-launched debugview and the same repeating error was spamming perpetually when steamvr is running. 

It appears to be a permission issue.. I tried re-assigning permissions to the 'C:\Program Files (x86)\Steam\steamapps\common\SteamVR', however it has had no effect. 

here is a small snippet from the recent debugview session:
00000450	13.80870533	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000451	13.87056637	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000452	13.93242741	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000453	13.99456596	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000454	14.05661297	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000455	14.11927509	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000456	14.18163395	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000457	14.25122547	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000458	14.30563641	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	
00000459	14.37028599	[10724] CVR2DGameOverlay::CreateDesktopOverlay() failed: VROverlayError_PermissionDenied	

Thank you again for your time. Revive is great, thank you for contributing to it! I wish it was working correctly on my system.

**Comment by dolandmac** [comment]
its still happening after removing revive and re-installing steamvr... i don't think this is a revive bug. Any input on how i could possibly troubleshoot this further would be greatly appreciated though.

**Comment by CrossVR** [comment]
You're probably better off creating a new issue where you explain from the start which game is crashing and when including all the information about your setup. Simple follow the format.
