### ISSUE TITLE
Can't get Oculus Home or Asgard's Wrath to work

### ISSUE THREAD

**Issue by Skyward2019** [LibreVR/Revive#1447]
Hey I have been trying to troubleshoot revive today my problem is that I can't open the Oculus Home Environment or Asgard's Wrath however Oculus DreamDeck, Oculus Touch Basics, and First Contact all seem to work. What I noticed when I tried to run Oculus home and Asgard's Wrath I get this back: 
Creating process: C:\Program Files\Oculus\Support\oculus-worlds\Home2\Binaries\Win64\Home2-Win64-Shipping.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x8139eb60
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x8139eb60
Failed to wait for LoadLibrary to exit

I am unsure how to fix this I have tried running Steam as an administrator, as well as running Oculus as an Administrator, and I have restarted my PC a few times. I have also tried a couple of different versions of Revive here and there. Please let me know if anyone has advice on what to try or let me know what additional information would be helpful.

**Comment by CrossVR** [comment]
Your virus scanner is likely the cause of the problem.

>

**Comment by Skyward2019** [comment]
I had seen that in some other places but I havent got any other virus scanners on this PC other than anything windows would have by default. Which I had tried disabling windows defender and running it. Though I plan to scrub through all my files and make sure I'm not forgetting about any virus scanner that I could have downloaded.

**Comment by Skyward2019** [comment]
Welp I resolved my issue by completely reinstalling windows...
