### ISSUE TITLE
Hoping someone can help - On Vive - Unable to find an Oculus Rift

### ISSUE THREAD

**Issue by supermanscottbristol** [LibreVR/Revive#1449]
Hi guys

Cannot get Revive to run anything at all on my Vive
I've got SteamVR installed (Tried both beta and standard)
I've reinstalled Oculus Home
I've reinstalled Revive

The overlay starts fine.  It shows the correct games but none of them will run.

If I start Lost it says "Startup Error: Unable to find an Oculus Rift"
If I start First Contact it says "Cannot run this application without an Oculus Rift"
If I start The Climb it says "Hardware Issue: No VR Device available. You have a pending hardware issue that is preventing you from entering VR.  Please check that your headset and sensor are connected"
If I start Showdown - this starts, but comes up on my monitor but not in my Vive headset.

I've checked the OVRService is running - it is.
I've noticed thiere is an OVRLibraryService which shows as stopped, and if I try and start it, it won't.  Don't know if that's a problem or not.

I've tried running with both Oculus Home open and not.

Tried setting the injector to run as Adminstrator.

No joy.

Hope you might be able to help.

Thanks a lot

**Comment by supermanscottbristol** [comment]
Ok got there.  For anyone else who finds themselves in the same position - I went through regedit, deleted every occurrance of Revive in there.
Rebooted. 
Reinstalled - not using Admin privileges.
Rebooted.
Started Oculus Home.
Started Steam.
Started SteamVR.
Works.

**Comment by Craexz** [comment]
> Ok got there. For anyone else who finds themselves in the same position - I went through regedit, deleted every occurrance of Revive in there. Rebooted. Reinstalled - not using Admin privileges. Rebooted. Started Oculus Home. Started Steam. Started SteamVR. Works.

How do I actually find the occurrences of revive in regedit?? I have no clue how to do this

**Comment by CrossVR** [comment]
Don't mess with the registry. This person simply did not read the
instructions stating that you need to restart your PC after installing new
Oculus games.

So what actually fixed his issues was restarting the Oculus software. And
not related to anything he did in the registry.
