### ISSUE TITLE
Walking Dead: Saints and Sinners is not working

### ISSUE THREAD

**Issue by UnrealTest** [LibreVR/Revive#1451]
TWD: Saints and Sinners crashes on launch when trying to boot it through Revive. The UE4 Crash Reporter pops up after it crashes. Then it returns the user to Steam Home.

This is for the Oculus store version. 

Tested on REVIVE 1.92 and also REVIVE 1.7.0
Using the Valve Index. Running on Windows 10 latest update

**Comment by dustinward24** [comment]
Yes I am having the same exact issue, same crash report. Please figure out!?

**Comment by CrossVR** [comment]
This game has a native version for Valve Index doesn't it? You really shouldn't use Revive if a native version is available.

**Comment by MoxFr** [comment]
For all of us which use Virtual Desktop for Streaming Wifi or Shadow PC, we can't launch the game with revive, because there is a Hardware check or HMD check. Same issue from Steam or Oculus Store, Inject doesnt help. Thanks

**Comment by VampyreLegion** [comment]
Same issues, bought on the Oculus store for the crossbuy on Quest and Rift S.  Trying to launch the game. I get a blank black screen but I can hear game sounds.

game works fine with the Quest link cable, but I would like to use the Valve Index to play

**Comment by VampyreLegion** [comment]
> This game has a native version for Valve Index doesn't it? You really shouldn't use Revive if a native version is available.

The Oculus store offers a crossbuy on this title for both Quest and Rift S, so that is why I bought it on the Oculus store. The Quest version is due out Q4.  I have a Index and Quest.  so figured it would work like any other oculus title with revive

**Comment by gleep52** [comment]
Same issue trying to get this game to work via revive and Oculus Quest.

**Comment by UnrealTest** [comment]
> 
> 
> This game has a native version for Valve Index doesn't it? You really shouldn't use Revive if a native version is available.

I agree but they had a cross-buy deal on the Oculus store. Anyway, I ended up refunding it on there and purchasing on Steam last night.

**Comment by fholger** [comment]
I got it working on the Valve Index, you can try this build: https://ci.appveyor.com/project/LibreVR/revive/builds/30355407/artifacts

Unfortunately, playing through Virtual Desktop still crashes the game, but that might not be Revive's fault...

**Comment by DasNanda** [comment]
I've tried this build but can't get it to work. The Revive Dashboard shows up but the buttons don't seem to function, so I can't start a game. Any idea what the issue could be?

**Comment by gleep52** [comment]
I am having the same issue as @DasNanda - the icons in both the revive window on my desktop do not load any games now.  The revive menu inside steam home is the same way - nothing loads the games anymore.

**Comment by maucoimbra** [comment]
If you are having trouble starting and the game returns home, start it from inside the steam house and not from the hill house, it works with me, you don't need revive for those who have WMR

**Comment by zangiefjone** [comment]
hi guys Im noob how I can add games in revive program .... I just see 4 games installed in revive and now working .... I have more games for oculus but not appearing in revive App 
this is image when I lunch revive
http://fav.me/ddzoyku
