### ISSUE TITLE
Oculus Quest Right Touch Controller Issue in Zero Caliber and Hellsplit with virtual desktop/alvr

### ISSUE THREAD

**Issue by RiotEd** [LibreVR/Revive#1459]
The right Touch controller Thumpstick  is not working proper in Zero Caliber and Hellsplit with virtual desktop/alvr

**Bug:**

Zero Caliber - Can´t rotate Character in game with right thumpstick. Right Thumpstick  
is without any function. All Buttons are working right.

Hellsplit -  Can´t rotate Character in game with right thumpstick instead the 
thumpstick sends inputs thats normaly are used from the buttons.

With Oculus Link in both games the Touch Contoller works as expected

**Environment:**
 - App: Zero Caliber / Hellsplit
 - OS: Win 10 Version 10.0.18362 Build 18362
 - Headset: Oculus Quest

**Versions:**
 - Revive: 2.0.0.13
 - SteamVR: 1.9.16

**Additional context**
Any ideas to fix it?

**Comment by CrossVR** [comment]
Oculus Quest is not supported by Revive, use Oculus Link instead.
