### ISSUE TITLE
oculus game did not start in the steamvr

### ISSUE THREAD

**Issue by lanya0702** [LibreVR/Revive#146]
Hi,thanks for your works!
I install the reviveinstaller from this page,and can see a dashboard in the steamvr also the games in oculus.But when i point to the game and put the button,nothing happend.

**Comment by LibreVR** [comment]
Please post the following information:

- Which game is it?
- What is in the Revive logs found in `%APPDATA%\Revive`?
- Are you using the Vive headset?

**Comment by lanya0702** [comment]
ReviveOverlay.log：
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files (x86)\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///D:/Oculus/
Loading assets manifest: file:///d:/Oculus/Manifests/altspacevr-altspacevr-pc_assets.json
Loading assets manifest: file:///d:/Oculus/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///d:/Oculus/Manifests/colosseteam-colosse-a-story-in-virtual-reality_assets.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///d:/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle altspacevr-altspacevr-pc_assets
Loading application manifest: file:///D:/Oculus/Manifests/altspacevr-altspacevr-pc.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///D:/Oculus/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle colosseteam-colosse-a-story-in-virtual-reality_assets
Loading application manifest: file:///D:/Oculus/Manifests/colosseteam-colosse-a-story-in-virtual-reality.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///D:/Oculus/Manifests/oculus-farlands.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///D:/Oculus/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///D:/Oculus/Manifests/playful-luckys-tale.json
Found application altspacevr-altspacevr-pc
Found application baobab-studios-invasion-for-rift
Found application colosseteam-colosse-a-story-in-virtual-reality
Found application oculus-farlands
Found application playful-luckys-tale
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: oculus-farlands
Failed to launch application: revive.app.oculus-farlands ()
Launching application: oculus-farlands
Failed to launch application: revive.app.oculus-farlands ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
I use a HTCVIVE headset
game are farlands,invation,luckys tale

**Comment by LibreVR** [comment]
The ReviveDashboard does not work when you are blocking the Oculus servers, you'll have to use the ReviveInjector directly if you want to continue to block the servers.

**Comment by lanya0702** [comment]
wow!But i dont know where did i blocking the oculus servers,how to check it?

**Comment by lanya0702** [comment]
I try the reviveinjector,The Luckys tale is OK,Farlands show up an Error:cannot run this application without a oculus rift

**Comment by LibreVR** [comment]
Farlands has a different main executable, look for the executable that ends with `..-Shipping.exe`.

**Comment by lanya0702** [comment]
yeah,Farlands can start,but push the button on the VIVE controller no responds

**Comment by LibreVR** [comment]
You need to turn off one of your Vive controllers so the remaining one is detected as an Oculus Remote instead of an Oculus Touch.

**Comment by lanya0702** [comment]
Thanks a lot!Would you please tell me hoe to unblock oculus servers?

**Comment by LibreVR** [comment]
You mean you didn't block them? Your log pretty much says it can't reach the Oculus website.

**Comment by lanya0702** [comment]
No,i did not,i use shadowsocks to visit oculus servers,is that the reason?

**Comment by LibreVR** [comment]
Yes, I'm pretty sure the Revive Dashboard won't be able to work with proxies.

**Comment by lanya0702** [comment]
I see,thanks a lot!
