### ISSUE TITLE
Link with Oculus account that has 2-factor authentication

### ISSUE THREAD

**Issue by davidtwco** [LibreVR/Revive#1460]
Is there a supported mechanism for linking an Oculus account (after the 2.0.0 release) which has two-factor authentication enabled? I attempted a login with the account username and email, with the password and the password concatenated with the current two factor code. Thanks!

**Comment by CrossVR** [comment]
> I attempted a login with the account username and email, with the password and the password concatenated with the current two factor code. 

Wait, does that actually work?

**Comment by davidtwco** [comment]
> > I attempted a login with the account username and email, with the password and the password concatenated with the current two factor code.
> 
> Wait, does that actually work?

No, it definitely didn’t, but I’ve seen other services do this so thought it was worth a try.

**Comment by CrossVR** [comment]
And I assume it gives you an incorrect password message even if you don't add the 2FA token.

**Comment by davidtwco** [comment]
> And I assume it gives you an incorrect password message even if you don't add the 2FA token?

That’s correct, yes. 

> Unfortunately I don't think there's a way for Revive to support 2FA, you'll need to ensure you have a secure password and turn off 2FA.

That’s a shame, thanks for checking. I’ll close this issue.
