### ISSUE TITLE
Vader Immortal Crash

### ISSUE THREAD

**Issue by Mm0p** [LibreVR/Revive#1464]
**Which game or application is your request about?**
Vader Immortal

**Is your request related to a problem? Please describe.**
The game crashes whenever i open it, but when i cracked it it came with an older revive injector, that worked fine, it would open the app and run, except it wouldnt open in steamvr.

**Describe the solution you'd like**
Im wondering if there is a way i can get it to work in vr, it just crashes whenever i run it. sometimes i see the game load for a split second, and it crashes again

**Describe alternatives you've considered**
Ive tried older versions, and the latest, and nothing seems to work

**Comment by ahmanwoods** [comment]
You're trying to run a cracked version of Vader Immortal?

**Comment by Mm0p** [comment]
> You're trying to run a cracked version of Vader Immortal?

yeah.. im trying it out, I wanna see if its good enough, if it is, ill end up buying all 3 eps lol

**Comment by CrossVR** [comment]
Just buy the game, if you hate it after all then refund it. There's no excuse for piracy.
