### ISSUE TITLE
Vader Immortal Menu Glitch

### ISSUE THREAD

**Issue by psyko-z** [LibreVR/Revive#1481]
When starting story mode can't close the menu, it reopen immediatly
Last version of SteamVr and Revive

**To Reproduce**
1. Launch the game
2. Start a new game or continue previous one

**Expected behavior**
It was supposed to show the A long tima ago etc...

**Environment (please complete the following information):**
 - App: Vader Immortal Episode I
 - OS: Win10
 - Headset: Acer WMR

**Versions (please complete the following information):**
 - Revive: Last ONe
 - SteamVR:Last one

**Comment by wadim-al** [comment]
Please add the workaround in comments if you fixed this.
