### ISSUE TITLE
Asgards Wrath not launching with WMR and Odyssey plus

### ISSUE THREAD

**Issue by Entretoize** [LibreVR/Revive#1488]
**Describe the bug**
When launching the game by moving the WrathGame.exe onto ReviveInjector.exe like I do (and works) with LoveEcho for example, I have the little launching Asgards Wrath title image, than a black screen and then a error message "You have a pending hardware issue that is preventing you from entering VR. Please check that you Rift Headset, Rift Sensors, and Oculus Touch controllers are connected.".

**To Reproduce**
Move the WrathGame.exe onto ReviveInjector.exe

**Expected behavior**
Game launchs and is playable.

**Environment (please complete the following information):**
 - Windows 10
 - Samsung Odyssey Plus
 - WMR

**Versions (please complete the following information):**
 - Revive: 2.0.0
 - SteamVR: 1.10.25

**Additional context**
Is there special things to do for that game to work ?

**Comment by CrossVR** [comment]
Why are you using the injector and not the dashboard?

**Comment by Entretoize** [comment]
Because the game doesn't appear in the dashboard (I wanted to test the game
without buying it -even temporary-).
Doesn't it do the same thing through the dashboard ? Is there a trick to
make it appear here ?

**Comment by CrossVR** [comment]
> without buying it

There's your problem, Revive will only work with legitimate games. Reporting issues with cracked versions is a ware of everyone's time.
