### ISSUE TITLE
Stuck in SteamVR Splash Screen or Crash [FOS / Stormland]

### ISSUE THREAD

**Issue by MoxFr** [LibreVR/Revive#1489]
**Describe the bug**

Stuck on SteamVR Splash Screen "Launching..." from new Virtual Desktop 1.10.1

**Apps**: Stormland / From Other Suns
**OS**: Windows 10 1909 / RTX 2070s
**Headset**: Oculus Quest with Virtual Desktop 1.10.1

**From Other Suns (FOS) :** 
Revive: 1.9.2 : No issue run fine 
Revive 2.0.13 : Stuck in steamvr splash screen & crash Fatal error UE 4

**Stormland :** 
Revive 1.9.2 & 2.0.13 : Stuck on SteamVR splash screen and game launched behind, i have audio but stucked on steam vr splash screen 'launching..." 

Tested with Steam VR Beta & Stable same issue

**Comment by fholger** [comment]
I thought the new Virtual Desktop can launch Oculus games directly, without going through SteamVR/Revive?

**Comment by MoxFr** [comment]
yes but we have issue with Stormland in VD, we need alternative with Revive maybe

**Comment by fholger** [comment]
Better to get those fixed in VD, then. Stormland through Revive has never been a good experience on VD due to stutter, so VD would have to fix stuff, either way.

**Comment by CrossVR** [comment]
Oculus Quest is not supported by Revive, use Oculus Link instead.
