### ISSUE TITLE
Lucky Tail VR view too close

### ISSUE THREAD

**Issue by plaidpants** [LibreVR/Revive#149]
The headset view is a little closer than when I play it on the oculus CV1. Something is not quite right, I need to look straight down too far and it tends to strain my neck. This does not happen with the CV1. Hard to quantify but I think it should be a little further back or a wider field of view or something. Using Version 0.6 of revive, launched from Revive tab in SteamVR, up to date stock oculus home.

**Comment by LibreVR** [comment]
Try recentering your seated position. In Lucky's Tale you can do that simply by pressing the back button on the Xbox controller.

**Comment by plaidpants** [comment]
Seems to be acceptable after using the re-centering. Thanks.
