### ISSUE TITLE
Why should I login?

### ISSUE THREAD

**Issue by wickles** [LibreVR/Revive#1490]
**Which game or application is your request about?**
Oculus account, Echo VR?, Stormland?

**Is your request related to a problem? Please describe.**
Revive nags the user to log in to their Oculus account. This feature lacks documentation and seems unnecessary -- multiplayer seems to work fine without logging in. 

**Describe the solution you'd like**
If logging in is vital it needs to be documented better. Why do I need to login? What kind of issues/errors will I encounter if I do not login? 

**Describe alternatives you've considered**
If logging in is not vital it needs to not nag the user but keep the button on the right-click context menu in case the user has a need for it. 

**Additional context**
According to the project which this feature is based on, the author specifically [mentions](https://github.com/ahmanwoods/Oculus-Defibrillator/blob/master/oculus_heartbeat.py#L12) titles where this feature should be relevant, Echo VR and Stormland. I do not own Stormland, but I have played a multiplayer match in Echo VR through Revive without logging in and did not encounter any issues.

**Comment by ahmanwoods** [comment]
Logging in fixes issues with player made lobbies. Try playing Stormland in co-op or Echo VR in a group with friends and you'll see why you need to be signed in.

**Comment by wickles** [comment]
Nagging has been reduced or optional? so closing this. thanks.
