### ISSUE TITLE
Can't Link Oculus Account

### ISSUE THREAD

**Issue by dimichelec** [LibreVR/Revive#1491]
**Describe the bug**

On a Windows 10 machine, when trying to link Revive with my Oculus account, I just repeatedly get the Windows Security login prompt from Revive Dashboard saying that "The user name or password is incorrect" and asking me to "Please log in to your Oculus account to enable online multiplayer."

**To Reproduce**

1. Right click on "Link Oculus Account" from the Revive Dashboard tray icon
2. Enter user name and password
3. Click "OK"
4. See error described above

**Expected behavior**

I would expect a dialog saying that Revive was able to link to my Oculus account after I submit my credentials.

**Environment (please complete the following information):**
 - App: [e.g. First Contact]
 - OS: [e.g. Win10]
 - Headset: [e.g. Vive, Index]

App: Revive Dashboard
OS: Win10
Headset: Vive

**Versions (please complete the following information):**
 - Revive:
 - SteamVR:

Revive: 2.0.0.13
SteamVR: 1.10.27 

**Additional context**

**Comment by ahmanwoods** [comment]
Do you have 2FA enabled?

**Comment by dimichelec** [comment]
Yes, I have 2FA enabled using the text message (SMS) method.

**Comment by ahmanwoods** [comment]
2FA isn’t supported as there isn’t a good way to implement it atm.

**Comment by dimichelec** [comment]
Thanks. It worked after turning off 2FA. Another note, Revive asks for your Oculus "username" but only accepts the email address you have attached to your Oculus account instead.

**Comment by RayTech82** [comment]
> I turned off 2FA through facebook and it still just won't login. There is no way to disable it through oculus themselves anymore.

Yes it wont work for me and I checked and it doest say I have 2fa I tried resetting password and I also tried using my username and password Windows 10 Revive Version 2.11

**Comment by okbuggy** [comment]
i dont think i ever turned on 2fa but when i try logging into my oculus account when it gives me that prompt it says wrong password and just to make sure i wasnt getting the password wrong i reset the password and then entered it onto the prompt and it still said it was wrong
