### ISSUE TITLE
No internet access in SteamVR with Revive installed

### ISSUE THREAD

**Issue by Kedriv** [LibreVR/Revive#1496]
After the latest update of SteamVR, I no longer have internet access (wifi) after starting SteamVR. An online search indicated that this is most likely related to having Revive installed.

Is there a way or update to have Revive installed and have my wifi work? Is the only solution to uninstall Revive?

**Comment by CrossVR** [comment]
This problem has already been fixed in Revive. Try uninstalling Revive and see if that works, if it doesn't you'll know it's not Revive.

**Comment by Kedriv** [comment]
I think it may be related to the wifi. I recently switched it to 2.4 GHz and switching it back to 5 GHz looks to have solved it. Interference with the controllers perhaps with the Valve Index?

Thanks
