### ISSUE TITLE
"No Headset" error on LT

### ISSUE THREAD

**Issue by Stoppablemurph** [LibreVR/Revive#15]
Can't get Lucky's Tale to work. Keeps starting with a "No Headset" detected error. Have tried restarting and launching with and without oculus home and with and without steamvr running.

**Comment by LibreVR** [comment]
This often means you have not applied the patch correctly. Make sure you replace `OVRPlugin.dll` and that both `LibRevive64_1.dll` and openvr_api.dll are present next to `LT.exe`.

**Comment by LibreVR** [comment]
Duplicate of #12.
