### ISSUE TITLE
Get XStoryPlayer 3.5 to work with HTC Vive

### ISSUE THREAD

**Issue by Skidrow68** [LibreVR/Revive#150]
Think they start the Oculus in game maybe its because if that it doesn’t work.
![xatory](https://cloud.githubusercontent.com/assets/19759240/15987332/042ffc60-3025-11e6-9fec-c8137142155b.jpg)
This ss is starting without ReviveInjector_x64.

Missed to set allow apps that have not been reviewed by Oculus to run on my Rift so now i get more in the log, the log say:
Launched injector with: "E:\X Moon Productions\XStoryPlayer 3.5\x64\ReviveInjector_x64.exe" "E:\X Moon Productions\XStoryPlayer 3.5\x64\XStoryPlayer64.exe"
Creating process: E:\X Moon Productions\XStoryPlayer 3.5\x64\XStoryPlayer64.exe
Injecting DLL: E:\X Moon Productions\XStoryPlayer 3.5\x64\x64\openvr_api.dll
LoadLibrary found at address: 0x32aa74d0
Injecting DLL: E:\X Moon Productions\XStoryPlayer 3.5\x64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x32aa74d0
Injected dlls succesfully

Still only get blue if i am at Revive (no icons or anything) and black monitor, if i press F8 the game crash.

**Comment by LibreVR** [comment]
Low priority issue, postponed to version 0.8.

**Comment by Skidrow68** [comment]
Would be nice if you got some info why it wont be fixed? Is it because it cant be done easy or not at all?

**Comment by LibreVR** [comment]
Rift DK2 applications are not supported in Revive.

**Comment by Skidrow68** [comment]
Were do that show?
I should have SetupPatch35_CV1 installed, were they updated it to CV1.

**Comment by Skidrow68** [comment]
Maybe this helps:

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: D:\Revive\revive.vrmanifest
Runtime directory: file:///E:/Steam/steamapps/common/SteamVR/
Oculus directory: file:///D:/Oculus/
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-client.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-compat.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-diagnostics.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-dreamdeck-nux.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-drivers.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-home.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-librarian.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-overlays.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-redistributable-installer.json
Loading assets manifest: file:///d:/Oculus/Manifests/oculus-runtime.json

**Comment by LibreVR** [comment]
This application is too obscure to invest time into. Oculus Home games are the main focus right now.

Just keep an eye out for new releases, as compatibility improves eventually all applications will work.

**Comment by Skidrow68** [comment]
Okey, thx anyway :)
