### ISSUE TITLE
Quill flickering and stuttering on Quest

### ISSUE THREAD

**Issue by PhilStewart** [LibreVR/Revive#1501]
Quill launches fine, but once in the software it flickers/stutters rapidly when moving the HMD or objects inside Quill. These flickers are near enough every frame, and appear as if the head tracking has glitched - the image updates, then goes back to the previous image, then updates again (at least this is what it feels like). Occasional hard stutters where the image freezes for around 10 frames or more. Also, I feel like the eyes aren't syncing properly, maybe one image is being served at a time to each eye - although if I close one eye, the other eye image still has the stutter.

1. Oculus Quest using WiFi Virtual-Desktop to my home PC
2. Launch SteamVR from Virtual-Desktop
2. From steamVR use Revive to launch Oculus Quill (rift version)
3. Issue should present immediately

Expected behavior
Smooth image and tracking

Environment:
 - App: Quill via Virtual-Desktop
 - OS: Windows 10
 - Headset: Quest

Versions:
- Revive: 2.0.0
- Virtual Desktop: 1.10.2
- SteamVR: 1.10.32
- Quill: 2.3

**Additional context**
If I 'alt-tab' to the Virtual-Desktop UI with Quill still in the background, the Quill image displayed on the "monitor" is perfectly smooth. Also, if I remove my HMD and move it around, the Quill display on my PC monitor is perfectly smooth. If I open the Oculus or SteamVR menus during Quill, which creates an overlay, the menus are perfectly smooth while Quill stutters behind them.

**Comment by CrossVR** [comment]
Oculus Quest is not supported by Revive, use Oculus Link instead.
