### ISSUE TITLE
Add support for Oculus MFA / 2FA

### ISSUE THREAD

**Issue by spkane** [LibreVR/Revive#1502]
**Which game or application is your request about?**
Revive Dashboard

**Is your request related to a problem? Please describe.**
Dashboard authentication does not work if you have MFA enabled on your Oculus account. There are also no hints that this might be what is happening.

**Describe the solution you'd like**
Support for MFA, either by providing a second prompt for the MFA code when required, or possibly by allowing people to use the password prompt to pass in "password,mfacode" and then use that to submit the correct authentication sequence to the Oculus servers.

**Describe alternatives you've considered**
The common answer is disable MFA, but that isn't really a very valid response nowadays, sort of like saying "just remove the front door from your house, it will be fine."

**Additional context**
I realize there might be some technical challenges with implementing this, but it should remain an open feature request until there is a solution that will allow better security for everyone who wants it.

**Comment by CrossVR** [comment]
It's unfortunately simply not possible to support 2FA. The Reviv

**Comment by CrossVR** [comment]
The only thing I can do is make the notification less naggy. But ultimately users have to choose between the added security of 2FA or multiplayer lobby support in Revive.

**Comment by spkane** [comment]
Making the notification less naggy and also maybe adding a message in the dialog that having MFA enabled will cause failures would certainly improve the user experience, especially if it is likely a very long term, if not permanent issue.

**Comment by Drizzard2** [comment]
Being able to completely disable the notification when you choose to have 2FA would be great. ATM I haven't found a way to turn off the login notification once you try to login.

An added message somewhere that having 2FA prevents you from logging in would be nice too.
