### ISSUE TITLE
Has enyone achieve to run EVE VAKYRIE ??

### ISSUE THREAD

**Issue by Spawnjos** [LibreVR/Revive#151]
I try to patch the valkyrie.exe with revive injector like with the shipping.exe executables, but dont works. Is it posible to run this game on VIVE somehow???

**Comment by Rojoyinc** [comment]
They will be releasing the VIVE version with motion controllers soon.

**Comment by Opticsponge** [comment]
good point, I do wonder if will happen before Playstation release.

**Comment by noisyboyuk** [comment]
Has anything changed with this since the new Revive update?

**Comment by LibreVR** [comment]
Not yet.

**Comment by LibreVR** [comment]
One thing you could try is following the patching instructions: https://github.com/LibreVR/Revive#steam-games

It should work for games that have launchers, but I don't expect that it will work for EVE.

**Comment by LibreVR** [comment]
Fixed through commit 7e80a45eeec2cf813d13fcb67d3301f7c87986f5 and 217d806cddf7e847a1fc93f0e1b22226b7f068c2.

EVE: Valkyrie support will be part of the next release.
