### ISSUE TITLE
Nothing Works, No Games, No Inject, No Manual Patch.

### ISSUE THREAD

**Issue by allbombson** [LibreVR/Revive#1510]
**Describe the bug**
Nothing launches Nothing works.

**To Reproduce**
1. Go to Any Game/Any Way of launching a game with revive EG. Manual Patching, Injecting, Library Menu, etc
2. Launch the game
3. Game Doesn't launch at all or Gives no Rift Headset error
4. See error/Don't Play Game

**Expected behavior**
The software to actually fucking work like it did a few weeks ago.

**Environment (please complete the following information):**
 - App: Any
 - OS: Win10
 - Headset: Index

**Versions (please complete the following information):**
 - Revive: 2.0.0.13
 - SteamVR: Both Current Beta and Stable, I tested on both. 

**Additional context**
When manually trying the injector thru a bat file with pause at the end, it takes a few seconds and then it gives the error: "Failed to create process"

I have also seen other people having this issue.

**Comment by allbombson** [comment]
After restarting Oculus for the 6th time a handful of things seems to work thru the library menu

**Comment by allbombson** [comment]
Note still no manual patching or injecting working.

**Comment by CrossVR** [comment]
If you're moving games around between libraries you need to run the Revive Installer again to refresh its cache. Also if you're using Avast you'll need to disable it as it will prevent Revive from working.

Injection is currently broken (fixed in the latest nightly) and manual patching has been removed, but you shouldn't need to use those for Oculus Store games.

**Comment by allbombson** [comment]
My bad i should rephrase and give more info. I have no anti virus software other than windows defender. I'm not moving games around, as stated after a fuckton of restarts those worked thru the gui fine. I was having issues trying manual patches on games that needed it, EG og dirt rally on steam store, and random OVR games like quake2vr. How would i run this with current stable ATM if u removed manual patching?

**Comment by CrossVR** [comment]
As I've said about injection:

> Injection is currently broken (fixed in the latest nightly)

As for patching, it's still possible by copying DLL files manually, but I don't recommend it since it never worked well. If you really want to play Dirt Rally in VR I recommend getting it on the Oculus Store.
