### ISSUE TITLE
How to have just one version installed

### ISSUE THREAD

**Issue by ntblood** [LibreVR/Revive#1511]
The update detected says I have an old version of Revive installed. Even if I update it the message continues to come up when launching SteamVR. The reason I was told this was happening is because I have two versions of Revive installed. Well, I tried uninstalling Revive as well as manually removing Revive folders that were left. I don't know what to do and this is annoying. Why doesn't the patcher update the version of the Revive that is being detected?

**Comment by CrossVR** [comment]
You need to install the update in the same location, if you keep getting update messages it's likely you're not installing Revive in the correct location.

**Comment by ntblood** [comment]
It's such B.S. 
Previously, I removed the two versions I found installed then started from scratch and it happens again! One is in D:\Program Files (x86)     the other install is at D:\Program Files      I deleted the former one which is older files. See if that helps

**Comment by CrossVR** [comment]
If you don't remember where you installed the old version just run SteamVR and when you see the update message you can find out where it is by doing this:

1. Open your Task Manager
2. Open the details tab
3. Find ReviveOverlay.exe
4. Right-click it
5. Go to Properties
6. Look at the "Location" field

That should tell you where the outdated version that SteamVR is starting is located.
