### ISSUE TITLE
lies beneath crash on startup

### ISSUE THREAD

**Issue by corp12345** [LibreVR/Revive#1518]
is support for lies beneath going to be added? or am i the only one having this issue?

had one error that said the game reached a critical error and another that crashed steam vr completely. both on startup. the main game menu shows on my monitor but not in headset

**Comment by corp12345** [comment]
LoginId:**********
EpicAccountId:************

Assertion failed: [File:Unknown] [Line: 198] Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0005 - 'REMOVED')

Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
Kodiak_Win64_Shipping
kernel32
ntdll



this error was accompanied by my display driver crashing and reverting to a basic driver.

**Comment by fholger** [comment]
Hm, game works for me. What version of Revive are you on? What's your hardware?

**Comment by corp12345** [comment]
as if. version 2.0.0. actually updated from an old version unless the software automatically updates. was using the hotfix one for when stormland originally came out.

geforce rtx 2070 super 
intel i5-8400 2.80ghz (this automatically overclocks to 3.something
16GB DDR4

**Comment by corp12345** [comment]
maybe my version hasn't updated properly? to update it i just downloaded the newest version and ran it. should i have removed the original version beforehand?

**Comment by fholger** [comment]
Usually that should be sufficient, but you can try to uninstall it and delete any remnants in the Revive program folder, then reinstall.
In case you haven't, you might also try to update your Nvidia driver. Might help with driver crashes.

**Comment by corp12345** [comment]
checked asgards wrath and stormland and they're both still working just as an fyi. never struggled running a vr game before but i can see it jittering on the monitor so it's obviously struggling. can't even find minimum requirements for this game. 

thanks for trying to help btw

**Comment by corp12345** [comment]
why am i even getting an error relating to epic games? they don't have any ties to oculus do they?

**Comment by corp12345** [comment]
i hadn't updated my drivers... being a damn fool. usually get a prompt but nothing lately so slipped my mind. will update now and retest. if thats the problem then i'm sorry...

**Comment by corp12345** [comment]
nvidia drivers were already up to date. will reinstall revive

**Comment by corp12345** [comment]
uninstalled completely, rebooted, reinstalled then rebooted. fixed it. love ya. you're a diamond
