### ISSUE TITLE
Injector not working with Unity projects?

### ISSUE THREAD

**Issue by Kujako** [LibreVR/Revive#152]
Have some work being done on an Oculus product using Unity 5.4 and was hoping to use revive to test it with my Vive setup. However, the injector seems to not do anything, the application launches when I drag it into ReviveInjector_x64.exe, but it doesn't run on the HMD.

Does revive need to be installed first? Does the Oculus home need to be running? Or does it just not work under these conditions?

**Comment by LibreVR** [comment]
Revive is not intended to be used to inject into the Unity Editor.
