### ISSUE TITLE
Icons in Steam library menu

### ISSUE THREAD

**Issue by BjornGrylls** [LibreVR/Revive#1525]
**Which game or application is your request about?**
All

**Is your request related to a problem? Please describe.**
I think it would be nice to have game icons in the Steam library menu. Maybe even the background image when you click on the game if that is possible. 

**Describe the solution you'd like**
Load the same icon as displayed in Revive dashboard.

**Describe alternatives you've considered**
If the purpose of the icons is to mark out Oculus games, the icons should be another color than grey. An all orange icon would be easier to find.

**Additional context**
![image](https://user-images.githubusercontent.com/35100000/79884592-a499f200-83f5-11ea-8fa1-ef51478c0929.png)

**Comment by CrossVR** [comment]
Unfortunately as it stands it's not possible to fix this issue, SteamVR does not allow you to specify icons for OpenVR applications and this is just what happens to entries without icons.
