### ISSUE TITLE
Im using Virtual Desktop with quest and when I use revive to do OC exclusives my hands are stuck on the floor and the game crashes.

### ISSUE THREAD

**Issue by DicciusMaximus** [LibreVR/Revive#1526]
I recently got a router in my room and wanted to try VD with my quest. It works great with Steam games but the only OC games that work are VRC (I already had it downloaded from using Link) and Echo VR (but everything is suuuuper dark and the blacks are crazy). Has anyone else had the issue with their hands being on the floor or stuck in one place and the game crashes? If so how did you fix it? One example of this is in B&S. When I start the game my little pen thing that I choose my avatar with works but the moment I press play my hands get stuck and it crashes. In boneworks its the same. In Arizona Sunshine it just crashes. (also anyone know the fix with echo vr to fix the blacks?)

**To Reproduce**
1. Go to 'Revive Dashboard in VR'
2. Click on 'Basically any games with a couple exceptions'
3. See error

**Expected behavior**
Hands get stuck and game crashes or game just crashes

**Environment (please complete the following information):**
 - App: First Contact, Boneworks, Arizona Sunshine, B&S
 - OS: Win 10
 - Headset: Quest with VD

**Versions (please complete the following information):**
 - Revive:2.0.0
 - SteamVR:IDK whatever the newest one is

**Additional context**
help

**Comment by CrossVR** [comment]
Revive through Virtual Desktop is not supported.
