### ISSUE TITLE
Lies Beneath fatal error message on launch...

### ISSUE THREAD

**Issue by whyme466** [LibreVR/Revive#1528]
On game launch, using either Steam VR virtual control panel or mouse clicking Revive launcher screen, Lies Beneath launch fails every time, with message stating "Failed to open descriptor file ../../../Kodiak/Kodiak.uproject".  Removing/re-installing Revive version 2.0.0 does not eliminate this problem.  Also using latest SteamVR version and NVIDIA driver.

Windows 10 v1909, SteamVR 1.11.11, Wireless lens-modified Vive Pro, hybrid 2080Ti.

**Comment by ahmanwoods** [comment]
That game crashes instead of giving you a message about not being able to find rift hardware.

Try restarting revive and the oculus client.

**Comment by whyme466** [comment]
Sorry, restarting/uninstalling/re-installing Revive and updating Oculus client/restarting client do not eliminate this error message and immediate game termination.

Note that all other games downloaded/locally stored via the Oculus Store launch without issue...

**Comment by whyme466** [comment]
Still getting same fatal error message with SteamVR v1.11.12 (and Revive v2.0.0).

**Comment by ahmanwoods** [comment]
Can you try the latest beta version of revive?

**Comment by whyme466** [comment]
Thanks for the suggestion, ahmanwoods.

I tried 2.0.0.37 beta, but still encounter the SAME error message and failure to launch.

Note both Windows 10 Defender SmartScreen and Norton Security blocked installation of this download.  I could easily bypass Defender SmartScreen, but I could not disable Norton Security to allow installation (even with Smart Firewall and Auto Protect disabled).  I had to uninstall Norton Security completely.  This is the first time Norton has prevented a Revive installation.  It did not like file for Revive\SupportAssets\oculus-dreamdeck-nux\cover_landscape_image.jpg, at least.

**Comment by ahmanwoods** [comment]
Can you try copying `LibRevive64.dll` and `openvr_api64.dll` from `C:\Program Files\Revive` and `xinput1_3.dll` from `C:\Program Files\Revive\xinput_x64` to your game directory and try launching the .exe directly?

You'll need to downgrade back to the release version of Revive 2.0.

**Comment by whyme466** [comment]
Sorry, I received the same immediate error message and application exit, after downgrading to 2.0.0, copying 3 files to Oculus Win64 folder with .exe, and directly launching application from this .exe.

**Comment by ahmanwoods** [comment]
Are you on the latest version of the Oculus software?

**Comment by whyme466** [comment]
Oculus App Version 16.0.0.118.452

**Comment by ahmanwoods** [comment]
Have you reinstalled the game?

**Comment by whyme466** [comment]
Thanks for your many helpful suggestions - the reinstallation SOLVED the problem!
