### ISSUE TITLE
Pressure of triggers not working in oculus medium

### ISSUE THREAD

**Issue by AlekseyVoz** [LibreVR/Revive#1529]
**Describe the bug**
The Pressure of the triggers doesn't seem to be registering in oculus medium

**To Reproduce**
try to draw a clay stroke by lightly pressing the trigger, so that the stroke isn't full width.
the stroke will almost instantly become full thickness

**Expected behavior**
i expect to be able to draw thin strokes by lightly pressing the trigger. 
this video here at the 1.47 mark explains it: https://youtu.be/3sep6Hg8AqI?t=106

**Environment (please complete the following information):**
 - App: oculus medium (latest)
 - OS: Windows 10 1909
 - Headset: oculus quest

**Versions (please complete the following information):**
 - Revive: 2.0.0.13
 - SteamVR: 1.11.11

**Additional context**
I tried both Virtual desktop and ALVR. 
Virtual desktop starts with low pressure and very quickly goes to max. 
ALVR instantly goes to max

**Comment by CrossVR** [comment]
Oculus Quest is not supported by Revive, use Oculus Link instead.
