### ISSUE TITLE
Vader immortal doesn't start at all.

### ISSUE THREAD

**Issue by Gryfyt** [LibreVR/Revive#1533]
I bought Vader Immortal from the Oculus store, but it doesn't launch on the Vive. The game starts on the PC and says that the Oculus touch controllers are not detected. On the Vive it is stuck on the Vive loading screen while the music of the game plays. I've tried updating the Oculus drivers, reinstalling the games, waiting for it to start, restarting the PC, but nothing seems to work. Thanks for the feedback in advance :)

**Comment by CrossVR** [comment]
Right-click your SteamVR status window and click "Create System Report", save the result to a file and drag and drop that file into the text box below.

**Comment by Gryfyt** [comment]
Now it doesn't even launch on the PC.

[Uploading SteamVR-2020-04-30-PM_08_13_31.txt…]()

**Comment by Gryfyt** [comment]
[SteamVR-2020-04-30-PM_08_13_31.txt](https://github.com/LibreVR/Revive/files/4559949/SteamVR-2020-04-30-PM_08_13_31.txt)

**Comment by CrossVR** [comment]
You have an old version of Revive installed, please update to version 2.0
