### ISSUE TITLE
Echo VR doesn't start.

### ISSUE THREAD

**Issue by Revvilon** [LibreVR/Revive#1535]
**Describe the bug**
While starting the game an error saying that I need to either download the latest runtime or check that my headset is connected pops up.

**To Reproduce**
1. Start the game
2. See the error

**Expected behavior**
I expected the game to start.

**Environment (please complete the following information):**
 - App: Lone Echo
 - OS: Win10 pro
 - Headset: HTC Vive

**Versions (please complete the following information):**
 - Revive: 2.0.0.13
 - SteamVR: 1.11.11

**Create a system report**
[SteamVR-2020-05-01-AM_02_50_02.txt](https://github.com/LibreVR/Revive/files/4562041/SteamVR-2020-05-01-AM_02_50_02.txt)

**Additional context**
What I've tried:
Redownloading the game
Redownloading the oculus software + revive
Downloading latest drivers
Injecting manually

**Comment by CrossVR** [comment]
Have you tried restarting your PC as is recommended?

**Comment by Revvilon** [comment]
Sorry for the late response.
I restarted my pc multiple times, ran steam as administrator, etc.
Read through a lot of different posts from here and couldn't find anything that solved my issue.
At the moment I'm redownloading everything one last time to see if it will get fixed.

**Comment by Revvilon** [comment]
Issue got fixed after yet another redownload, closing this.
