### ISSUE TITLE
Only appearing on monitor with echovr

### ISSUE THREAD

**Issue by JJJSM11** [LibreVR/Revive#1537]
Hi, i am having in issue with echovr and lone echo where when i try to launch them, it launches in standard speed but only apears on my monitor, tracking of the headset and controllers is still there, but all i can see on my headet is steamvr saying starting soon and not doing anything for upwards on 10 minutes

**To Reproduce**
1. Connect an oculus quest headset to pc via Virtual Desktop
2. Open SteamVR
3. Open EchoVR with revive from the revive overlay

**Expected behavior**
I expected that it would boot up perfectly and I could see it on the headset

**Environment (please complete the following information):**
 - EchoVR or LoneEcho
 - Windows 10
 - Oculus quest

**Versions (please complete the following information):**
 - Revive: version 2
 - SteamVR: 1.11.11 (not beta)

**Comment by CrossVR** [comment]
Oculus Quest is unsupported by Revive.
