### ISSUE TITLE
"Wands" game is not launching at all

### ISSUE THREAD

**Issue by Tiergott** [LibreVR/Revive#1538]
Is there any way, that "Wands" game (https://www.wandsgame.com/, https://www.oculus.com/experiences/rift/1833318536683635/) could be added to compatibility list in near future? For now - it is not launching at all( It has fun gameplay and crossplay with oculus go, quest and gear vr.

**Comment by CrossVR** [comment]
It's a wiki, anyone can add an entry for them as "not working" if that's what you're asking.
