### ISSUE TITLE
Revive dashboard won't start

### ISSUE THREAD

**Issue by Silithas** [LibreVR/Revive#154]
I installed it and oculus home, but still the revive dashboard won't start?`I also started the steamVR, but still nothing.

**Comment by LibreVR** [comment]
There are still problems with the dashboard, in the mean time you can use the "Standalone games" instructions while I work on a solution.

Please post your logs from `%APPDATA%\Revive` so I can better diagnose this problem.

**Comment by Silithas** [comment]
Alright. I used the injector, but for some reason, nothing appears in the vive, and no motion geatures works either. The program/game starts, but only the xbox one controller works.

**Comment by Silithas** [comment]
Revive injector log:

Launched injector with: "F:\Oculus\Software\Software\woofbertvr-woofbert\ReviveInjector_x64.exe" F:\Oculus\Software\Software\woofbertvr-woofbert\WoofbertVR.exe
Creating process: F:\Oculus\Software\Software\woofbertvr-woofbert\WoofbertVR.exe
Injecting DLL: F:\Oculus\Software\Software\woofbertvr-woofbert\x64\openvr_api.dll
LoadLibrary found at address: 0x36d674d0
Injecting DLL: F:\Oculus\Software\Software\woofbertvr-woofbert\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x36d674d0
Injected dlls succesfully


Revive overlay log

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///H:/Steam/steamapps/common/OpenVR/
Oculus directory: file:///F:/Oculus/
Loading assets manifest: file:///f:/Oculus/Software/Manifests/ats-kurvet-mythos-of-the-world-axis_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/colosseteam-colosse-a-story-in-virtual-reality_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/discovery-vr-discoveryvr-rift_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json.mini
Loading assets manifest: file:///f:/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/moshe-ben-zacharia-the-body-vr-rift_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/oculus-lost_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/oculus-oculus-360-photos_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/penrose-the-rose-and-i_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/sketchfab-sketchfab-vr_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/vrse-milk-koblin_assets.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/woofbertvr-woofbert.json
Loading assets manifest: file:///f:/Oculus/Software/Manifests/woofbertvr-woofbert.json.mini
Loading assets manifest: file:///f:/Oculus/Software/Manifests/woofbertvr-woofbert_assets.json
Found assets bundle ats-kurvet-mythos-of-the-world-axis_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/ats-kurvet-mythos-of-the-world-axis.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle colosseteam-colosse-a-story-in-virtual-reality_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/colosseteam-colosse-a-story-in-virtual-reality.json
Found assets bundle discovery-vr-discoveryvr-rift_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/discovery-vr-discoveryvr-rift.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/epic-games-showdown.json
Found assets bundle felix-and-paul-studios-introduction-to-virtual-reality_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json
Found assets bundle moshe-ben-zacharia-the-body-vr-rift_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/moshe-ben-zacharia-the-body-vr-rift.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-lost_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/oculus-lost.json
Found assets bundle oculus-oculus-360-photos_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/oculus-oculus-360-photos.json
Found assets bundle penrose-the-rose-and-i_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/penrose-the-rose-and-i.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/playful-luckys-tale.json
Found assets bundle sketchfab-sketchfab-vr_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/sketchfab-sketchfab-vr.json
Found assets bundle vrse-milk-koblin_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/vrse-milk-koblin.json
Found assets bundle woofbertvr-woofbert_assets
Loading application manifest: file:///F:/Oculus/Software/Manifests/woofbertvr-woofbert.json
Found application felix-and-paul-studios-introduction-to-virtual-reality
Found application woofbertvr-woofbert

**Comment by iamwes** [comment]
I got it working by installing the newest Revive, update oculus store to newest... open steamvr (non revive tab) so double click Revive Overlay (Revive tab appears) restart steamVR and it was back... edge of nowhere even works without downgrading now :-)

**Comment by LibreVR** [comment]
The log looks good, you should see plenty of games in your dashboard.

Which game are you trying to play?

**Comment by Silithas** [comment]
Wes, where would the revive tab even be located? 

And how can i see anything from a dashboard that won't open at all? It is in the task manager, but nothing else.

**Comment by LibreVR** [comment]
It's part of the dashboard system in your headset when you press the system button. It adds a third Revive tab there.

**Comment by iamwes** [comment]
If it doesn't appear through your headset try double clicking ReviveOverlay which can be found in the installation folder for example: c:/programfiles/revive/   worked for me anyway, had to restart steamvr and oculus after though to get the games to work

**Comment by Silithas** [comment]
Found the dashboard now and everything works as it should now :)

**Comment by LibreVR** [comment]
Great! Have fun! :)

**Comment by Silithas** [comment]
Or not :/ Tested out hentry which would work much better in vive than rift dk2, but when the game was about to load the actual scene, it crashed with a "the video driver has crashed" error.

**Comment by LibreVR** [comment]
That is issue #119, there is a workaround by placing extracting RevivePatch in `C:\Program Files\Oculus\Software\Software\oculus-henry\Henry\Binaries\Win64`.
