### ISSUE TITLE
Dance Central can't be injected

### ISSUE THREAD

**Issue by Bobcorn008** [LibreVR/Revive#1550]
Latest version of Revive and Steam VR and OC Home, HTC VIVE.
STEP:
Injected Dance Central, nothing happened. Revive still have the 4 basic games.
If I started game directly without injection, game shows a  purple background and says "you have a pending hardware issue that is preventing you from entering VR“, so I think Revive doesn't injected this game correctly.

btw the other 4 games in Revive works well. Hope you can gimme some advises, I really expect to play this gameLOL.

**Comment by ahmanwoods** [comment]
Injecting via tray is broken in the release version of 2.0. If the game was purchased through the Oculus store, it should just show in the Revive dashboard.

You can try dragging the game .exe onto ReviveInjector.exe located in C:\Program Files\Revive

**Comment by Bobcorn008** [comment]
@ahmanwoods Thanks I'm going to have a try

**Comment by Bobcorn008** [comment]
@ahmanwoods Now the game was running, but after showing Dance Central's LOGO, game shows nothing but black, I can only see my controllers and a footprint on the floor center. Game should showed another two logos and started. This is confusing.
Used 1.73, 1.82, latest version of Revive. Just the same question.

**Comment by ahmanwoods** [comment]
Is this a legit copy of the game?

**Comment by Bobcorn008** [comment]
@ahmanwoods Unknown version, it's a link from TG group and I downloaded: https://drive.google.com/open?id=1YvRx3X24DcQrD7Vf1Roz95NSnld1NcYF

**Comment by ahmanwoods** [comment]
1. It probably isn't good to post pirated content in the github comments
2. Revive only supports Oculus titles purchased through the Oculus store

**Comment by Bobcorn008** [comment]
@ahmanwoods Oh sorry I didn't realize it, I deleted. After downloading from OC Store, the game runs perfectly with latest version of Revive, Thanks for help!!!
