### ISSUE TITLE
ReviveOverlay.exe is crashing since 0.6.1

### ISSUE THREAD

**Issue by Glibber** [LibreVR/Revive#156]
0.6.2 crashes also. Have tried reinstalling ReVive, no difference.
Could play Farlands and Lucky's Tale until Version 0.6 stopped working two days ago.

```
Problemsignatur:
  Problemereignisname:  APPCRASH
  Anwendungsname:   ReviveOverlay.exe
  Anwendungsversion:    0.0.0.0
  Anwendungszeitstempel:    576c8178
  Fehlermodulname:  ReviveOverlay.exe
  Fehlermodulversion:   0.0.0.0
  Fehlermodulzeitstempel:   576c8178
  Ausnahmecode: c0000005
  Ausnahmeoffset:   0000000000003b3a
  Betriebsystemversion: 6.1.7601.2.1.0.256.1
  Gebietsschema-ID: 1031
  Zusatzinformation 1:  28f7
  Zusatzinformation 2:  28f7588e8161581e2b7636aa4cdbf4ef
  Zusatzinformation 3:  7b14
  Zusatzinformation 4:  7b149801ef548e8d4cbec40902162321
```

It shouldn't be a problem but the vcredist_x64 package is not installing because there is a newer version installed: 14.0.23918   your version: 14.0.23506
Everything is installed on drive D:
D:\Revive
D:\Steam
D:\Oculus

There is only a ReviveOverlay.log with no real info in it:
`libpng warning: iCCP: known incorrect sRGB profile
`

revive.vrmanifest is empty (size is zero). Anything else you need to know?
Thanks for your effort and time

**Comment by LibreVR** [comment]
Can you take a look at your registry? There should be a key called `Base` in `HKEY_LOCAL_MACHINE\Software\Oculus VR, LLC\Oculus`.

The absence of that key is the only thing I can think of that would crash it.

**Comment by Glibber** [comment]
I think you nailed it, the key you mentioned does not exist, but there are keys:
```
HKEY_CURRENT_USER\Software\Oculus VR, LLC
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Oculus VR, LLC
```

**Comment by LibreVR** [comment]
Oh sorry, that's the one. So it is there.

Can you try the latest version (0.7)?

**Comment by Glibber** [comment]
`Base` contains the correct path `D:\Oculus\`
I installed 0.7 with uninstalling first but it is still crashing for me, sorry.

**Comment by LibreVR** [comment]
Still nothing of interest in the log file?

**Comment by Glibber** [comment]
There's still only the libpng warning in the logfile.
I got the Revive.sln to compile but all i got is "ReviveInjector_x64.exe"
I see a reviveoverlay.pro project file, how do you compile it?
Anyway, i have to go to sleep, will try more tomorrow. 
Thanks

**Comment by LibreVR** [comment]
You need Qt5 to compile the overlay.

**Comment by leandro-gracia-gil** [comment]
I'm also having what seems to be the same problem. Here's my log in case it helps. I also happen to have the most recent version for both Revive (0.7) and Oculus. My registry Base key also points to D:\Oculus.

[ReviveOverlay.log.txt](https://github.com/LibreVR/Revive/files/333986/ReviveOverlay.log.txt)

**Comment by Glibber** [comment]
Is it possible without too much trouble for you to make a Debugversion available with all symbols in it. Then i could just run it with the debugger. But i will try to compile it by myself in the evening.

**Comment by Glibber** [comment]
Maybe I'm just stupid, it's working now. I really don't know why it does work now and didn't work before. I'm not hallucinating, i have about 20 crashreports. The Ticket may be closed.

**Comment by LibreVR** [comment]
I prefer to keep it open until I find out why this is happening.

**Comment by leandro-gracia-gil** [comment]
Please ignore my comments on this thread. It turns out I was simply doing things wrong and thought ReviveOverlay was crashing without doing anything. Works for me now.

**Comment by lahesis333** [comment]
I am sorry! But the topic I did not see answer to solve this problem. User for no apparent reason and the program has earned it solved his problem had remained a mystery. Once again I apologize for breaking the rules, but I already do not have forces to fight this problem. The whole week I'm trying to solve it, but nothing so far has not helped ....

**Comment by lahesis333** [comment]
When I try to start ReviveOverlay every time I get an error. I tried to reinstall the software version to an earlier and install the latest version of the error does not disappear. Help please advice! I already tried to reinstall the operating system, but still remained an error ...

The signature of the problem:
  Event Name the problem: APPCRASH
  Application Name: ReviveOverlay.exe
  Application Version: 0.0.0.0
  Mark application time: 574885cd
  The module name with the error: ReviveOverlay.exe
  Module version with an error: 0.0.0.0
  Stamp module-time error: 574885cd
  Exception code: c0000005
  Offset exceptions: 0000000000003b3a
  OS Version: 6.1.7601.2.1.0.256.1
  Language code: 1049
  Additional Information 1: 28f7
  2 For more information: 28f7588e8161581e2b7636aa4cdbf4ef
  3 For more information: 7b14
  More information 4: 7b149801ef548e8d4cbec40902162321

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

If privacy statement is not available in the internet, check out his local version:
  C: \ Windows \ system32 \ ru-RU \ erofflps.txt

**Comment by LibreVR** [comment]
Which version of Windows are you using?

**Comment by LibreVR** [comment]
Also, for everyone who is affected by this issue, Revive is pre-release software. I am currently focusing on problems I can reproduce myself. When Revive is nearing a stable version I will add some crash dumping functionality so I can start debugging some of these corner issues.

In the mean time, please use the instructions for standalone games as a temporary solution.

**Comment by lahesis333** [comment]
I use Windows 7 Ultimate SP 1.

**Comment by lahesis333** [comment]
I apologize for my misunderstanding, but is for stand-alone games do not need to use the program ReviveOverlay.exe?

**Comment by LibreVR** [comment]
May be a Windows 7-specific bug, I only ever tested Revive on Windows 10.

ReviveOverlay is only there for convenience, it allows you to start the Oculus Games from your VR Dashboard. However you can also do it manually by following the instructions for Standalone games, which will also work for Oculus Home games.

**Comment by LibreVR** [comment]
Can anyone check if this is still a problem in the latest release?
