### ISSUE TITLE
cant get vive to run at all now

### ISSUE THREAD

**Issue by bundaberg42** [LibreVR/Revive#157]
installed software,  got edge to no where working , exited that  and than tried eve valkryie, it crashed and now cant get  vive to work at all. I try to run vr steam  it comes back with Failed to terminate "vrcompsitor.exe"

Ive reinstalled download and rebooted a number of times and tried different combinations  of stuff but now my vive doesn't work , i haven't plugged the dk2 in yet to see if tha its working yet .  

I cant see any folder  you describe for installation either .

**Comment by LibreVR** [comment]
Can you post your logs from `%APPDATA%\Revive`?

**Comment by bundaberg42** [comment]
Sorry managed to get it to work but  half the oculus stuff doesn't work
like oculus video and photos  , eve valkyrie , elite dangerous, adrift.
Interestingly  holodeck  works luckys tale
​, edge of nowhere. Vive is much better than the dk2. I  am still waiting
for the cv1 i ordered in jan so this software of yours is appreciated. I
stoped buying oculus store software because  i saw that steam had most   of
their stuff anyway. Im thinking of cancelling the oculus order now that
your software works but  holding of   because  it might not work on the
software i like ie eve valkrie and elite dangerous. Anyway  how do i get
logs , im not sure .?​



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=bundaberg42@gmail.com&idSignature=22>

Sean Sullivan

Mobile 0413892531

**Comment by LibreVR** [comment]
If it works, then I don't need the logs anymore. In any case, there are still compatibility issue with some games, we're still working on that.

I think Oculus Video should work though, maybe try following the "Standalone Games" instructions.

**Comment by bundaberg42** [comment]
thanks




Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=bundaberg42@gmail.com&idSignature=22>

Sean Sullivan

Mobile 0413892531

**Comment by thedonquixotic** [comment]
hey @bundaberg42 how'd you get it to work? I'm getting the same error.

**Comment by LibreVR** [comment]
This error happens when you start Revive Dashboard before starting SteamVR. However, since the Revive Dashboard is automatically started with SteamVR this should never happen.

You should only be manually starting the Revive Dashboard if it doesn't show up in your dashboard after you've launched SteamVR.

**Comment by bundaberg42** [comment]
yes thanks for replying.


Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=bundaberg42@gmail.com&idSignature=22>

Sean Sullivan

Mobile 0413892531
