### ISSUE TITLE
Phantom Covert Ops and The Wizards Dark Times crash when launching

### ISSUE THREAD

**Issue by securely** [LibreVR/Revive#1575]
I'm getting this kind of error:
LowLevelFatalError D3D11VertexBuffer.cpp:88 with error "E_INVALIDARG"
![errorfatal](https://user-images.githubusercontent.com/11143332/85919635-f316a300-b821-11ea-87cd-07ca18a561d6.jpg)

![error2](https://user-images.githubusercontent.com/11143332/85919675-66b8b000-b822-11ea-8a5e-2b32d05f4dcd.jpg)

This happens when I try to launch The Wizards or Phantom: Covert Ops or Moss. I'm using the StarVR One. A wide FOV headset, paired with Index controllers.

I'm using Windows 10 pro 1909 with the latest Nvidia driver 451.48. The latest windows update 2004 is not yet available for my PC.

**Comment by ahmanwoods** [comment]
Do other titles launch?

**Comment by securely** [comment]
Yes, I have no problem launching Asgard's Wrath, Racket Nx, Shadow Point, Robo Recall, Vader Immortal, Aircar, Stormland, etc.

**Comment by securely** [comment]
The latest Revive update V2.1.0 fixed the issue for me! Thank you to the developers! Phantom Covert Ops looks gorgeous on the StarVR One :)

**Comment by slikvik55** [comment]
Hey @securely Could you try Moss please? Has that been fixed too?
