### ISSUE TITLE
Version 2.1.0 is not downloadable

### ISSUE THREAD

**Issue by KrisSchier** [LibreVR/Revive#1578]
https://github.com/LibreVR/Revive/releases/tag/2.1.0

The link to the exe file brings the following error.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>55973577/df467a80-b9a2-11ea-85a6-7311b2b4e25f</Key>
<RequestId>2EE2ED7985246C2C</RequestId>
<HostId>pjli7pugUlvMorgMQkzt0FeiB60Vr3ZTJID8zeULea9nbUB4VOLQg0jS7swlOmYVne3SYlaJ6aU=</HostId>
</Error>

**Comment by iloc2000** [comment]
I'm getting the same error message.

**Comment by jbmlaird** [comment]
Same error message

**Comment by CrossVR** [comment]
This is fallout from the GitHub downtime yesterday, going to fix it today.

**Comment by CrossVR** [comment]
Fixed
