### ISSUE TITLE
Revive will not launch echo arena after logging in.

### ISSUE THREAD

**Issue by crumbface** [LibreVR/Revive#1581]
**Do not report issues when using Virtual Desktop or ALVR, this is not supported by Revive.**

**Describe the bug**
Whenever I try to launch echo arena I am prompted to log into oculus. When I do it does not launch the game, so I click to launch the game and it prompts me to log in again.

**To Reproduce**
1. Launch revive dashboard
2. Click "Echo Arena"
3. Login when prompted to

**Expected behavior**
I expected to log in and be able to launch Echo Arena, but this did not happen.

**Environment (please complete the following information):**
 - App: Echo Arena
 - OS: Windows 10
 - Headset: Index
**Versions (please complete the following information):**
 - Revive: 2.1.0
 - SteamVR: 1.12.5

**Create a system report**
Right-click your SteamVR status window and click "Create System Report",
save the result to a file and drag and drop that file into this text box.

[SteamVR-2020-07-04-AM_08_23_27.txt](https://github.com/LibreVR/Revive/files/4872821/SteamVR-2020-07-04-AM_08_23_27.txt)

**Additional context**
I am unable to play the game without logging in, so any help would be appreciated, for now I've just reverted back to version 2.0.0 and it works fine.

**Comment by CrossVR** [comment]
> Sat Jul 04 2020 08:10:20.948 - C:\Program Files\Revive\revive.vrmanifest - App revive.app.ready-at-dawn-echo-arena binary_path C:\Program Files\Revive\ReviveInjector.exe is invalid. SKipping. Skipping

Sounds like there was a problem with your installation? Something deleted the injector application.

**Comment by crumbface** [comment]
Interesting, let me see if my antivirus had something to do with it.

**Comment by crumbface** [comment]
Yep, anti virus was deleting the injector on the install. Thanks!
