### ISSUE TITLE
Can we add Oculus Home Support?

### ISSUE THREAD

**Issue by zurgeg** [LibreVR/Revive#1593]
**Which game or application is your request about?**
Oculus Home

**Is your request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to able to access the Oculus Home from my Valve Index headset.

**Describe alternatives you've considered**
Attempting to launch the Oculus Home executable

**Additional context**
None.

**Comment by zurgeg** [comment]
UPDATE: While reading through the docs it appears that it might be available, if so, this issue may be closed.

**Comment by CrossVR** [comment]
It's already supported, you can access it by clicking the top-left tile in the Revive tab on your dashboard.

**Comment by zurgeg** [comment]
Oh, thanks! Oculus Home was the one reason I didn't want to leave my Quest+Link yet!

**Comment by zurgeg** [comment]
One more question, can Oculus Dash be accessed from this?

**Comment by CrossVR** [comment]
No, you can only use your SteamVR dashboard

**Comment by zurgeg** [comment]
Okay, thanks!
