### ISSUE TITLE
The climb - Runs fine, but 3d reproduction is broken

### ISSUE THREAD

**Issue by ldjg2002** [LibreVR/Revive#160]
Hi, 

Tried to play the climb today, via the injector with the 1.5 runtime and latest version of revive. 

Using the injector as per the comparability list, but its still not working (I can see 4 hands it seems its the right eye that is causing the issue)

Any help or guidance would be appreciated!

**Comment by LibreVR** [comment]
Can you use the display mirror feature to take a screenshot? Just open the display mirror window and press S to take a screenshot.

**Comment by ldjg2002** [comment]
Hi, 

As requested, the other thing ive noticed is that I seem to be far above what the game seems to think is floor level, I can/will try to re run my room, but this is the only instance of hitting this issue. 

<img width="1920" alt="2016-06-25" src="https://cloud.githubusercontent.com/assets/20140363/16356578/490a0ce4-3ad5-11e6-8a2b-afdb63e9018d.png">

**Comment by ldjg2002** [comment]
Another final thought, the display is correct for around 1 second as soon as the training sequence opens (the menu screens are fine throughout), then it goes as per the attached picture.

**Comment by ldjg2002** [comment]
well thats 299.99 ill never see again XD 

If anyone has a suggestion id love to hear it, reinstalled everything, if someone else is actually playing this fine, could you advise?

**Comment by LibreVR** [comment]
This is just pre-release software right now, it will improve and eventually you'll be able to play it without issues.

Anyway the screenshot you provided is not the one I asked for. SteamVR has a menu you can open and there is a Display Mirror function. I want you to open that one and go to Main > Screenshot (or the S shortcut) to take a screenshot and upload all files here.

**Comment by ldjg2002** [comment]
Figured it out. 

Precision X, using the overlay was causing the issue. 

And your completley correct, your doing great work for the VR community, apologies for my comment about the money.
