### ISSUE TITLE
Stormlands stutter

### ISSUE THREAD

**Issue by karlos103** [LibreVR/Revive#1602]
Stormlands via virtual destop on oculus quest

Anyone managed to find a fix for the headtracking stutter on Stormlands ?
Running latest Virtual destop and revive.

If i use the Link cable ...then no stuutering at all ....but really want to use virtual desktop .
Any help most appreciated
Karl

**Comment by ahmanwoods** [comment]
At the top of the bug report template:

“Do not report issues when using Virtual Desktop or ALVR, this is not supported by Revive.“

VD doesn’t support pose prediction, causing the jittering. Bug the VD developer if you want stormland support.

**Comment by karlos103** [comment]
Sorry ...thought maybe revive issue ...until tried cable but that was after posted message ...then edited it

**Comment by gormanj** [comment]
I have the head tracking stutter issue while tethered.
