### ISSUE TITLE
Into The Radius

### ISSUE THREAD

**Issue by karlos103** [LibreVR/Revive#1603]
Hi all
Trying to get Into The Radius to work on my Oculus Quest via Virtual destop and Revive.
I can get game to boot ...and can look round at main title screen ...can get some sort of menu to open but thats about it.

If use the Link cable then works fine ...but really want to use virtual desktop.

Any help most appreciated
Karl

**Comment by ahmanwoods** [comment]
At the top of the bug report template:

“Do not report issues when using Virtual Desktop or ALVR, this is not supported by Revive.”
