### ISSUE TITLE
Oculus video stopped working.

### ISSUE THREAD

**Issue by noisyboyuk** [LibreVR/Revive#161]
Hi!

Just wondered if anyone else had Oculus Video stop working after the update? Both myself and a friend now have the same issue. Nothing happens in VR and the window is just a black window on the desktop.

Thanks!

**Comment by gormanj** [comment]
The Oculus Video app was updated. My older backup of Oculus Video works with Revive 0.6.2 and Oculus runtime 1.5. So it might be the Oculus Video app update.

**Comment by LibreVR** [comment]
I'll look into this one.

**Comment by LibreVR** [comment]
Found the problem, looks like they switched to an unsupported layer type. I'll add support for this layer type in the next version.

**Comment by LibreVR** [comment]
Fixed in commit 122a2ed45e3a9e40bd6a6c3b890b12c57e8ec453.
