### ISSUE TITLE
The Oculus Games can't start without Oculus Hardware (no skip option)

### ISSUE THREAD

**Issue by hgabor47** [LibreVR/Revive#1615]
**Do not report issues when using Virtual Desktop or ALVR, this is not supported by Revive.**

**Describe the bug**
-Start a Game in Revive
-The game will exit with Hardware error
-In the Oculus software I add a hardware (4 options) but no SKIP button only EXIT so no hardware selected because not detected my VICE (Pimax) hardware

**Expected behavior**
Early (about a month) oculus software contained the SKIP button and the revive worked

**Environment (please complete the following information):**
 - App: [Dead and Buried]
 - OS: [Win10]
 - Headset: [Pimax]

**Versions (please complete the following information):**
 - Revive:
 - SteamVR:1.14.16

**Comment by ahmanwoods** [comment]
I just reinstalled the oculus software last week and don't recall having any issues.

Can you provide a screenshot of what you're seeing in the client?

**Comment by CrossVR** [comment]
You can sometimes get caught in this loop when you attempt to add Oculus
Hardware and then try to go back, the skip option will no longer
be available.

You need to do a clean reset of the Oculus software, the troubleshooting
guide on the wiki has some more information.

**Comment by hgabor47** [comment]
Hi, 
Thanks CrossVR. After the Oculus reinstalled the Revive working well.
Thanks
