### ISSUE TITLE
Gamepad support in the dashboard

### ISSUE THREAD

**Issue by lawliet675** [LibreVR/Revive#162]
Can you add steam controller support for the Dashboard and games?

**Comment by LibreVR** [comment]
Unfortunately I can only do so for the dashboard.

**Comment by LibreVR** [comment]
There are some important bug fixes in version 0.8, so I'm postponing this issue until 0.9.

**Comment by vgf89** [comment]
Is it possible to make the Oculus games in the normal SteamVR menu act like normal shortcuts? Normal shortcuts for every other non-steam game I have added work fine with the Steam Controller, but the configuration menu is non-existant for ReVive games, even though they show up in Steam library while in VR.

**Comment by LibreVR** [comment]
@vgf89 This is not possible, but you don't really need per-game Steam controller settings. The only thing Revive needs is for the Steam Controller to switch to XInput mode. But if I understand correctly the only way to do that is through the Steamworks API.

**Comment by LibreVR** [comment]
Fixed in commit 2e8df448017a50eff3fef453ae429a4ecaa23365.

Will be part of the next release.

**Comment by LibreVR** [comment]
For in-game support, please keep track of issue #257.
