### ISSUE TITLE
Stormland renders on desktop but not in Quest headset

### ISSUE THREAD

**Issue by CybershoesVR** [LibreVR/Revive#1622]
**Behaviour**
Stormland opens and renders on the desktop window correctly but not inside the Quest headset using steamVR+Virtual Desktop. 
a) You can hear the sounds inside the headset.
b) When you turn your head this correctly affects the rendered perspective of the game that has opened on the desktop 
c) You see the Stormland logo in front of the steamVR background in the headset
d) does not crash
*) Quest+VD: it used to work until summer (spring?) 2020
*) Rift S or Quest+Link: same behavior but since 2019

**To Reproduce**
1. On Quest launch Virtual Desktop (sideloaded) then launch steamVR
2. Click on Revive and open Stormland
**or**
1. On SteamVR connect Rift S or Quest with Link
2. Click on Revive and open Stormland

**Expected behavior**
Stormland to be seen inside the headset

**Environment (please complete the following information):**
 - Stormland
 - Win10
 - Quest, Quest2, Rift S, Quest with link
-  Cybershoes controller: disconnected

**Versions (please complete the following information):**
 - Revive: 2.1.1
 - SteamVR: 1.14.16
-  Virtual Desktop 1.17.7 (sideloaded)

**Create a system report**
[SteamVR-2020-10-21-PM_08_30_53.txt](https://github.com/LibreVR/Revive/files/5418070/SteamVR-2020-10-21-PM_08_30_53.txt)

**Additional context**
Cybershoes is an accessory for walking in VR. https://store.steampowered.com/app/1222360/Cybershoes/
Many of our customers have the Quest (some the Rift S). In order to run a game from the Oculus store, they run it via REVIVE and SteamVR. Cybershoes need steamVR to bind the Cybershoes-controller movement to the game. Tested games https://docs.google.com/spreadsheets/d/1abO8xNzXOqAIW5O-EJfQbHoZvheeV8YmRF7aiRZV4xI/edit#gid=807610147

**We and the Cyberbuddies would appreciate your help very much.**

**Comment by CrossVR** [comment]
As mentioned in the first line of the issue template that you deleted, this is not supported so please don't submit issue tickets for it.
