### ISSUE TITLE
Echo arena refuses to output to steam vr

### ISSUE THREAD

**Issue by DangerCow** [LibreVR/Revive#1628]
**Describe the bug**
When i open echo arena in steam vr echo arena in steamvr the game launches like normal but will not output an image to my headset/steamvr instead what i see is steamvr telling me that the game is still "up next"

open steam vr
click on the revive dashboard 
open echo arena
wait until half life 3 gets released 

**Expected behavior**
open steam vr
click on the revive dashboard 
open echo arena
actually see echo arena in headset

 - App: Echo arena
 - OS: Win10
 - Headset: Quest 2

 - Revive: 2.1.1
 - SteamVR: 1.14.16

**Create a system report**
[SteamVR-2020-11-06-PM_02_10_31.txt](https://github.com/LibreVR/Revive/files/5503527/SteamVR-2020-11-06-PM_02_10_31.txt)

**Additional context**
every other game works completly normal :|

**Comment by CrossVR** [comment]
> Headset: Quest 2

> Virtual Desktop Streamer

The issue template did say that this isn't supported. Also, VD has its own method of streaming Oculus games to Oculus headsets that doesn't involve Revive.

**Comment by DangerCow** [comment]
I dont think you read the question properly im trying to play oculus games using steamvr as a middle man so i can use such programs as turn signal and xsoverlay.

**Comment by CrossVR** [comment]
This still isn't supported because it uses a different SteamVR driver. Only HTC Vive and Valve Index support all the necessary features to support all Oculus games.

**Comment by CrossVR** [comment]
I've clarified the issue template to mention that the message is about Virtual Desktop drivers for SteamVR.

**Comment by DangerCow** [comment]
Is oculus link any different? Thats the method i have been using not virtual desktop.
