### ISSUE TITLE
Airmech Command has no sound in 0.7

### ISSUE THREAD

**Issue by kjack9** [LibreVR/Revive#163]
Airmech command loads correctly but has no sound in the main menu in 0.7.  What additional information, debugging, or logs can I provide to help track down the issue?

**Comment by LibreVR** [comment]
Nothing yet, I need to carefully examine this game first. I'll let you know if I have anything you could test.

**Comment by LibreVR** [comment]
Found the problem, Airmech mutes the audio when it believes the Health-and-Safety warning is still displayed.

**Comment by LibreVR** [comment]
Fixed in commit 9fd4ee36cf49fae8ec252c5e8298736611387eb3.

Real frustrating issue, I correctly deduced that it was related to the Health-and-Safety warning. But finding exactly on which conditions it detected that was just a matter of trying everything.
