### ISSUE TITLE
Trigger Pressure with Quest 2 Controllers Please

### ISSUE THREAD

**Issue by BiteyThing** [LibreVR/Revive#1632]
**Which game or application is your request about?**
Medium and Quill

**Is your request related to a problem? Please describe.**
There is no trigger pressure sensitivity when using with Quest 2

**Describe the solution you'd like**
Ability to vary stroke width based on trigger pressure (Quest 2).

**Describe alternatives you've considered**

**Additional context**
The only way to play some games on the Quest through Virtual Desktop is by using Revive. Medium and Quill are the two that I need it for most.... Thanks for all your work on Revive! I appreciate your time 👍

**Comment by ahmanwoods** [comment]
First line of the bug report form:

**Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**

You could try loading it via the Virtual Desktop "Games" tab and see if that fixes it

**Comment by BiteyThing** [comment]
> First line of the bug report form:
> 
> **Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**
> 
> You could try loading it via the Virtual Desktop "Games" tab and see if that fixes it

They will not launch at all when trying directly through Virtual Desktop that way :(  Thanks for the quick reply and suggestion though!

**Comment by Sobollion** [comment]
I have the same problem, found few similar issues with no clear way out
https://github.com/LibreVR/Revive/issues/452
https://www.reddit.com/r/OculusQuest/comments/hqwgmo/is_anyone_using_oculus_medium_or_quill_via/

**Comment by BiteyThing** [comment]
> I have the same problem, found few similar issues with no clear way out
> #452
> #1529
> https://www.reddit.com/r/OculusQuest/comments/hqwgmo/is_anyone_using_oculus_medium_or_quill_via/

Good info in those links though... Thanks 😄

**Comment by CrossVR** [comment]
This sounds like a limitation of the Virtual Desktop driver, which can't be fixed by Revive. This is why that first line is there asking not to report such issues here.

**Comment by Sobollion** [comment]
Hey, I just found the solution! First of all you need a steam vr beta, then launch VD, go to steam vr and launch the quill or medium, after that open steam menu and click controller settings, then edit a layout profile: delete trigger settings and then add it again, but set only third of it (trigger value) And it works!

**Comment by BiteyThing** [comment]
> Hey, I just found the solution! First of all you need a steam vr beta, then launch VD, go to steam vr and launch the quill or medium, after that open steam menu and click controller settings, then edit a layout profile: delete trigger settings and then add it again, but set only third of it (trigger value) And it works!

Wow!! Thanks a BUNCH, Sobollion 👍  Will look for the trigger value setting but it seems to be working nicely in Medium and Quill as it is!

And thanks to the moderators for allowing this thread :)

**Comment by Sobollion** [comment]
I tried quill with USB link mode and recognize that buttons A/X B/Y shoud work with touch. So they didn't in VD and resetting in steam control settings doesn't help. We need to get rid of this one issue too :\

**Comment by CrossVR** [comment]
I'm happy to hear you guys found a workaround, but if you want these issues
solved you need to report them to the Virtual Desktop developers instead.

**Comment by Sobollion** [comment]
@CrossVR, thanks, but I tried to pay attention to this problem on Virtual Desktop Discord, they just ignored my message.

I completely mess. I need to know how controllers go to Quill. To get into the quill, first of all, i launch Virtual Desktop on PC and my Quest 2. Then i launch Steam VR, and inside it start Quill. I dont even know revive is used in this case or not, but it insalled.
Where i should dig?
Is it a right map?
Quest 2 > VD driver > Steam VR beta controller preset (Open VR) > Revive > Quill 

Is it a problem in the Open VR, or Virtual Desktop driver?

**Comment by BiteyThing** [comment]
I had to reassign those buttons in Quill. I think it may have had something to do with mirror mode(?)... But I dont need VD or Revive when using Link to launch Medium or Quill, fwiw.

When using VD/Revive wirelessly Quills panels jump around unless I dock them though.... Doesn't happen with Link.

**Comment by Sobollion** [comment]
@BiteyThing, Okay, i gave up, gone buying a link cable...

**Comment by Sobollion** [comment]
Well, i finally got it works properly, one more workaround for buttons
![VirtualDesktop Android-20201207-204847](https://user-images.githubusercontent.com/23660511/101359375-c4bbea00-38ce-11eb-97c4-928e23230f4e.jpg)
