### ISSUE TITLE
How can I use the "oculus button" inside Oculus Dreamdesk with my HTC Vive?

### ISSUE THREAD

**Issue by duennerd** [LibreVR/Revive#1633]
When I'm inside Oculus Dreamdesk I see the Oculus button on the virtual Oculus controller. 
I have a HTC Vive and therefore a Vive controller. But I cant push/trigger the Oculus button. 
I tried to change the button attribution but didnt find any possibilities to do so. 
Is this intended?

**Comment by CrossVR** [comment]
What do you hope to achieve by pressing it? It won't open the Oculus dashboard if that's what you're hoping for.

**Comment by duennerd** [comment]
Why not?

**Comment by CrossVR** [comment]
Because you're running the game on SteamVR. There is no Oculus dashboard for the button to open.

**Comment by duennerd** [comment]
Ok, I understand. that makes sense. Thx for you help.
