### ISSUE TITLE
Eve: Valkyrie "No Oculus Entitlement

### ISSUE THREAD

**Issue by sagejessee** [LibreVR/Revive#164]
I get an error when playing EVE: Valkyrie that says "No Oculus Entitlement". I opened from the Revive dashboard. Otherwise the game appears to start and I can switch to seated mode and see an avatar in a dark room. Only option is the press the "A" button to quit the game. Any suggestions?

**Comment by LibreVR** [comment]
For entitlement errors, please restart the Oculus service by going to `Settings > Beta > Restart Oculus` in Oculus Home.
