### ISSUE TITLE
Dirt Rally doesn't work with 2.1.1 and Valve Index

### ISSUE THREAD

**Issue by zissakos** [LibreVR/Revive#1640]
I can't get Dirt Rally to launch. No matter what I try, the drt.exe immediately stops (along with WerFault.exe pointing to an unhandled exception).

I tried using Revive 2.1.1, 2.0.0, 1.7.3, 1.4.2 etc (both 32 and 64bit versions).
With 1.4.2 (reportedly working with DR) I get this and then it crashes.

E:\games\SteamLibrary\steamapps\common\DiRT Rally>E:\gamesVR\_tools\Revive1.4.2\Revive\ReviveInjector_x86.exe drt.exe
Launched injector with: E:\gamesVR\_tools\Revive1.4.2\Revive\ReviveInjector_x86.exe  drt.exe
Creating process: drt.exe
Injecting DLL: E:\gamesVR\_tools\Revive1.4.2\Revive\x86\openvr_api.dll
LoadLibrary found at address: 0x76ef0bd0
Injecting DLL: E:\gamesVR\_tools\Revive1.4.2\Revive\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x76ef0bd0
Injected dlls successfully

**Comment by zissakos** [comment]
OK I managed to get it to work. Here are the instructions for anyone else (read carefully).
- Patching or starting Revive_Injector.exe with drt.exe as an argument DID NOT WORK.
- you have to start start normally in steam after havin copied some files into your DR folder and with SteamVR NOT RUNNING. The game will start SteamVR for you.

1. Install Revive 1.7.3 (maybe it works with a more recent version, I don't know)
2. Copy the 3 DLL files from Revive1.7.3\Revive\x86 into your DirtRally folder (where drt.exe is)
3. Copy Revive1.7.3\Revive\ReviveInjector_x86.exe into your DirtRally folder (where drt.exe is)
4. Close SteamVR and Launch DirtRally normally through steam. This should start SteamVR, activate the ValveIndex and immediately start the game in VR.

If you're stuck in the VR warning screen probably your DR window lost focus. Just click it with your mouse to regain control.

Hope that helps anyone.

**Comment by DaRkL3AD3R** [comment]
I'm really surprised to see this is still broken. I guess the devs gave up on it since it uses Oculus runtimes in a weird way. It's a shame because IMHO Dirt Rally 1 is far superior to 2.0 and when Revive works properly, it's a great experience. It's just sad to see the game abandoned both by the developers and by Revive.

**Comment by bernhardberger** [comment]
Serious question: why not play it natively through SteamVR?

**Comment by CrossVR** [comment]
Follow the 32-bit instructions here to get Dirt Rally on Steam working:
https://github.com/LibreVR/Revive/wiki#standalone--steam-games-alternative

**Comment by zissakos** [comment]
> 
> 
> Serious question: why not play it natively through SteamVR? Shouldn't it support both? Or do I need to get a refund from Steam?

It only support Oculus API although it is sold on Steam.

**Comment by DaRkL3AD3R** [comment]
> Follow the 32-bit instructions here to get Dirt Rally on Steam working: https://github.com/LibreVR/Revive/wiki#standalone--steam-games-alternative

Just want to let you know that following those instructions specifically doesn't work at all on the newest versions. On 1.9.x it causes crashing but at least functions, only 1.7.3 is crash proof and runs right. Something is broken with newer versions of Revive and this game on Steam.

**Comment by simachines** [comment]
doesn't work for me either on latest versions
