### ISSUE TITLE
Revive not starting. 

### ISSUE THREAD

**Issue by rosijer** [LibreVR/Revive#1642]
I had revive working fine on my windows computer but when i added a second hardrive and moved all my games to the new drive I could not get revive to run. I get a spinning icon for a couple of seconds but no revive menu.
I reinstalled revive and steam but still no joy.
What I did notice was that Revive was on 34 bit and Steam was on 64 bit and I was pretty sure Steam was on 32 bit before installation as well as 64 bit.
Not sure what else to try.
[e.g. First Contact]

**Is your request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zurgeg** [comment]
>...Revive was on 34 bit
Is this a typo or are 34 bit CPUs a thing now?
>...added a second hardrive and moved and moved all my games
It looks like this is your issue. Try moving your games to your original hardrive.
