### ISSUE TITLE
Is there any way to get this working on an Index in 2020?

### ISSUE THREAD

**Issue by CrumpThePenguin** [LibreVR/Revive#1649]
I've seen various posts online about using revive but the relevant links are all 404s.

**Comment by zurgeg** [comment]
https://github.com/LibreVR/Revive/releases/download/2.1.1/ReviveInstaller.exe there you go

**Comment by CrumpThePenguin** [comment]
I somehow posted this in a completely different Github issues thread. I meant to post it on the Virtual Boy emulator repository LMAO i'm very sorry for the confusion
