### ISSUE TITLE
Trouble with Oculus update

### ISSUE THREAD

**Issue by mbauer2001** [LibreVR/Revive#165]
So last week I have everything working, with Revive letting me play Lucky's Tale and Edge of Nowhere via my Vive.  Today when I got home I had a message from the Occulus software that it needs updating, but the updating won't work because it doesn't detect an Occulus. I've tried updating to the latest Revive edition, but no luck.  When I launch the Revive tab I just see a blank blue screen.

**Comment by mbauer2001** [comment]
FYI, Oculus keeps saying it cant find my headset or sensor.

**Comment by predme** [comment]
Do you get stuck in an update loop? It updates, start Oculus Home again, then prompts you to update again? I experienced this too. What I had to do was to uninstall Oculus Home and reinstall it.

**Comment by mbauer2001** [comment]
Yes! That's exactly what is going on. I'll try that. Thanks. Did you lose all of your progress on the games you had installed when you uninstalled Oculus Home?
