### ISSUE TITLE
Failed to CREATE INDEX

### ISSUE THREAD

**Issue by afahitech** [LibreVR/Revive#1656]
Failed to CREATE INDEX
![Screenshot from 2021-01-11 22-41-16](https://user-images.githubusercontent.com/57868100/104211441-479c0b80-545e-11eb-8459-2401c20d7b9d.png)
 - check your database permissions
Insufficient database permissions or incorrect database settings to install

**Comment by CrossVR** [comment]
That's the wrong Revive mate ;)
