### ISSUE TITLE
EVE: Valkyrie doesn't respond to xinput

### ISSUE THREAD

**Issue by predme** [LibreVR/Revive#166]
Just got Valkyrie after seeing that ReVive got support for it but I'm unable to use the controller in the game. The controller in question is a DS4 connected via USB. I use DS4Windows to turn it into xinput and it's running in exclusive mode. I don't have an actual Xbox controller to test with but I assume it would give similar results as both would be xinput devices. 

The HMD position in the game is also incorrect. My head is about 1 human length above my body in the game, offset a few meters to the left. I've tried resetting my HMD position via SteamVR but nothing happens. 

Edit:

Just found a Xbox One controller so can confirm that it doesn't respond to input with that either.

**Comment by LibreVR** [comment]
You need to reset your position using the back button on the Xbox controller. But since you can't use the Xbox controller you won't be able to do that.

I have no idea why the Xbox controller wouldn't work for you. Maybe EVE is using the gamepad input feature from the Oculus SDK. Perhaps I've made an implementation error there.

**Comment by robertlong** [comment]
I'm experiencing the same issue with an Xbox One controller. The controller also works fine in Lucky's Tale.

**Comment by LibreVR** [comment]
Can you try turning off your Vive controllers?

**Comment by predme** [comment]
Apologizes for replying so late to this issue, I figured out what was wrong! It appears that the game window won't always come into focus when you launch the game so of course it doesn't accept input. Quickly taking the HMD off and clicking the game will allow you to play the game!
