### ISSUE TITLE
mixed reality doesnt have mirror support for recording thru G2 VR headset

### ISSUE THREAD

**Issue by teebronson** [LibreVR/Revive#1663]
**Which game or application is your request about?**ms fltsim 2020
[e.g. First Contact]

**Is your request related to a problem? Please describe.**we need to be able to use the "nvidia experience"program , and record the screen like we see in the  HPreverb G2 hmd.    It does record the screen , But the G2 view on mixed reality screen shows google view and not full screen like mirror did for oculus

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CrossVR** [comment]
Huh? Why report issues for Microsoft Flight Simulator here? It doesn't use Revive, it's an OpenXR app!
