### ISSUE TITLE
Any chance of fixing P.O.L.L.E.N (issue #21)

### ISSUE THREAD

**Issue by iamwes** [LibreVR/Revive#167]
Is there any chance of fixing the issue #21 on POLLEN now your working on compatibility issues... as it seems they may have an exclusivity deal and haven't mentioned the Vive version for ages, plus its in the steam sale so would be nice to get now.

Thanks

**Comment by LibreVR** [comment]
Please don't post duplicate issues, I'm notified of every comment on the tracker so there is no need for that.

**Comment by iamwes** [comment]
Sorry
