### ISSUE TITLE
Revive can't connect to Oculus Account (echo vr)

### ISSUE THREAD

**Issue by TheArcader1** [LibreVR/Revive#1677]
i dont know how to fix this problem ive tryed to log in with my oculus account info and it goes away but it doesnt launch echo vr i tryed to follow the video in a different thred but that didnt work for me it let me play yesterday but it just stopped today i will give all the info i can give to fix this problem

![oculus thingy](https://user-images.githubusercontent.com/80019998/110551281-151f2f80-80ea-11eb-9b82-fc267de5280e.png)

**Comment by ahmanwoods** [comment]
This feature only works for non facebook only accounts that have 2 factor disabled, and is meant to fix issues with multiplayer parties.

Is the game not launching period or you're just having issues linking?

**Comment by TheArcader1** [comment]
its not lauching period i would click echo vr and it wouldnt launch

**Comment by MasterRedStorm** [comment]
I got the same thing, 2 weeks before i played echo vr with a facebook account just fine
since you cant create a occulous account now, is there a workaround?

**Comment by ThePiquedGeek** [comment]
Same, Prompted to link Oculus to allow Multiplayer games, but logging in returns a "incorrect username or password" but they are both correct.  This is happening for me only on 'Echo VR' while other OculusPC/Rift multiplayer games such as Population ONE are still working. I am on Win 10 with Oculus Quest 2

**Comment by trhstyle** [comment]
i got the same thing @ThePiquedGeek idk how to fix it or if there even is a fix i am on win 10 Oculus Quest 2 with valve index controllers

**Comment by MasterRedStorm** [comment]
do you guys see a way to fix this? or do i have to buy a quest if i want to keep playing echo vr :/
Iam not a cpp developer, but is there a way to support you on this?

**Comment by TheArcader1** [comment]
all i did was unistall revive and redownload the newest version of revive and it started to work again
