### ISSUE TITLE
ADR1FT no longer works with the new version of Revive

### ISSUE THREAD

**Issue by iamwes** [LibreVR/Revive#168]
ADR1FT was working fine but the new version of Revive hs stopped it, now it crashes everytime you open it. I have attached an image of the error.

![adrift error](https://cloud.githubusercontent.com/assets/19719854/16398535/f9b69636-3cc2-11e6-8b9f-a94b23ca25fb.PNG)

**Comment by LibreVR** [comment]
This is probably due to the fix for AirMech, can you confirm that version 0.6.2 works?

**Comment by iamwes** [comment]
I'm running 0.7 now so i'm not sure... i never got to try 0.6.2 i went straight from 0.6 to 0.7, it did work fine on 0.6 though.

**Comment by LibreVR** [comment]
You can still download 0.6.2 here: https://github.com/LibreVR/Revive/releases/tag/0.6.2

**Comment by LibreVR** [comment]
Just tested it, it works fine with 0.7 for me. You can also contact 505 games for an Oculus Home key. The Oculus Home version works with the Revive dashboard.

**Comment by iamwes** [comment]
i managed to get an Oculus key for it today... still does not work, crashes on initial loading still, exactly the same as the steam version...

**Comment by LibreVR** [comment]
That's very strange, I am unable to reproduce the problem. Did you use the dashboard *without* using the RevivePatch?

**Comment by iamwes** [comment]
I only tried the patch on the steam version, the oclus one is a fresh install only opened through the revive dashboard. I wonder how yours is working, on the steam forum others are having the same problem as me.

**Comment by LibreVR** [comment]
Have you tried testing 0.6.2 yet?

**Comment by LibreVR** [comment]
Please test version 0.8.1, lots of bug fixes that may affect ADR1FT.

**Comment by iamwes** [comment]
Just tried it with the newest version and i can confirm its working again! Nive one :-)

Tested with the Oculus version of ADR1DT

**Comment by LibreVR** [comment]
Looks like the code clean up was worth it, increased stability.
