### ISSUE TITLE
Zombieland Headshot fever will not open

### ISSUE THREAD

**Issue by dtdman420** [LibreVR/Revive#1687]
**Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**

**Describe the bug**

Click to open game, game just closes with no error or does not even open.

**To Reproduce**

**Expected behavior**

I would expect the game to open and play just like other games that work with revive

**Environment (please complete the following information):**
 - App: [Zombieland Headshot Fever]
 - OS: [e.g. Win10]
 - Headset: [WMR Samsung Odyssey +]

**Versions (please complete the following information):**
 - Revive: latest stable release as of March 2021
 - SteamVR: beta 1.17.2

**Create a system report**
Right-click your SteamVR status window and click "Create System Report",
save the result to a file and drag and drop that file into this text box.

**Additional context**

I also tried using the OpenXR version and restarted my computer a couple times
[SteamVR-2021-03-29-PM_01_22_38.txt](https://github.com/LibreVR/Revive/files/6224333/SteamVR-2021-03-29-PM_01_22_38.txt)

**Comment by ahmanwoods** [comment]
This game uses XR.

**Comment by dtdman420** [comment]
> This game uses XR.

What do you mean? So it should work then?

**Comment by dtdman420** [comment]
It is working now.
I downloaded the revive beta version and I got that error at first when starting the game but I ignored it and was able to play with no  problems
