### ISSUE TITLE
Games can not launched in Revive tab

### ISSUE THREAD

**Issue by legend02uwn** [LibreVR/Revive#170]
Firstly, thanks for your hard work in revive project.
I tried to installed revive several times but there are some problems, I can just see revive tab in HMD but nothing happened when I clicked the games in revive tab. Also I can not find oculus games in HTC vive Home software. I have tried to reinstalled oculus home, vive home, steam vr and steam, but if I am lucky maybe ten times only one time revive can work normally(but I can not update revive).
Because I live in China, the GFW blocked all of oculus server. So, I used VPN to download games and browse oculus home. I don't know whether there are some compatibility problems about languages or whether revive need to connect oculus server when it startup?

**Comment by LibreVR** [comment]
If the Oculus servers are blocked, then Revive will not work. The next version will address this problem.

Fixed in commit 21b37f15ccf055298793ed1625effafefb5364f5.
