### ISSUE TITLE
Seated position

### ISSUE THREAD

**Issue by masaville** [LibreVR/Revive#172]
Does anyone know how to reverse the seated position.  For example, in Edge of Nowhere, the game launches with the title screen behind me rather than in front of the Vive HMD.  While I can pivot around to play the game the sound is reversed (left/right speaker).  I can't seem to figure out how to resolve it.

**Comment by LibreVR** [comment]
A lot of games don't properly identify themselves as seated experiences. Try pressing the back button on the Xbox controller so the game triggers a recenter and is properly detected as a seated game..

**Comment by masaville** [comment]
Thanks I'll give that a try.

**Comment by masaville** [comment]
Worked.  Thank you!

**Comment by LibreVR** [comment]
Add a note about this to the compatibility list.
