### ISSUE TITLE
Subnautica World Never Loads

### ISSUE THREAD

**Issue by charlestruluck** [LibreVR/Revive#173]
Hey,
I used ReviveInjector with Subnautica. At first glance it looked great- then when I created a world the Vive headset went black (but not off) and the world never loads.

Anyone else having this issue?

**Comment by LibreVR** [comment]
Are you using the Experimental build?

**Comment by se7enred** [comment]
I too have set up experimental build and used the ReviveIinjector. The game menu starts fine but when you select a new game you get a black screen in the headset. The headset is still tracking though as the desktop shows the ship crashing with head movement but it seems to be stuck in a loop and not loading any further. Even pressing the button to bring up the steam desktop within the headset shows a black screen although you can select the buttons on it with the revive controller even though its pitch black.

**Comment by yohaskan** [comment]
It's debuged, with last experimental of Subnautica now.
You can load and save
