### ISSUE TITLE
revive 3.0.0: can't inject Condor, Oculus throwing: "this application is currently disabled on the active headset. (1971014)"

### ISSUE THREAD

**Issue by j2l** [LibreVR/Revive#1731]
Hello,

I came to Revive for Condor (https://www.condorsoaring.com/manual_en/ > VR)
Injecting Condor through Revive taskbar didn't add it to the revive dashboard.
Adding it through Oculus exposed an error:
![image](https://user-images.githubusercontent.com/65325/139588111-2cca615a-a37f-46ac-adf6-08a1d0b3ca7d.png)

**To Reproduce**
Install Condor (paid)
Install Oculus (without rift, only a Vive)
install Revive
Inject Condor (not showing in Revive Dashboard for me)
try launching Condor from Oculus (error)
try getting VR from Condor (one checkbox for Oculus), getting Video error

**Expected behavior**
Having Condor within Revive Dshboard

**Environment (please complete the following information):**
 - App: Condor2
 - OS: Win10
 - Headset: Vive

**Versions (please complete the following information):**
 - Revive: 3.0.0
 - SteamVR: 1.20.4

Thanks!

**Comment by CrossVR** [comment]
Injecting won't add it to the dashboard. Unfortunately the Dashboard will
only show Oculus Store titles

**Comment by j2l** [comment]
Thank you @CrossVR 
How could I get rid of the Oculus error then?

**Comment by lordfolken** [comment]
This is unfortunatly still an issue. All versions after 1.9.2 do not work with condor simulator 2.

**Comment by lordfolken** [comment]
I have some logs from condor:
```
CONDOR LOG STARTED AT 10:56:25
Condor version: 2180
Creating splash screen.
Loading cursors.
Loading fonts.
Creating controlers.
Creating client.
Creating replay.
Creating flighttrack.
Loading GUI skins.
Loading skin hash list.
Checking skin hash list.
Saving skin hash list.
Reading language.
Writing installdir.
Reading lastplayer.
Reading defaultlandscape.
Loading Setup.
Destroying splash screen.

STARTING REPLAY SIMULATION AT 10:56:33.
Debug mode: False, False.
Creating window.
Oculus Rift initialization started.
ovr_Initialize failed with error: ovr_Initialize never called.
Reading language.
Writing installdir.
Reading lastplayer.
Reading defaultlandscape.
Loading Setup.
Destroying splash screen.
```

**Comment by LeChat109** [comment]
the 1.9.2 version works but bad https://github.com/LibreVR/Revive/releases/tag/1.9.2

la version 1.9.2 marche mais très mal, il y a des problèmes d'antialising

**Comment by j2l** [comment]
Merci @LeChat109 
J'ai laissé tombé

**Comment by LeChat109** [comment]
Tkt, utilise la dernière version, c'est réglé
