### ISSUE TITLE
Subnautica, NO response from 360 Controller

### ISSUE THREAD

**Issue by bboydastyck** [LibreVR/Revive#174]
Hello everyone, really hoping someone has had this issue and has a solution. I have my 360 controller plugged in and it is unresponsive in the main menu of this game. It does however work in every other Oculus and Steam game. I have tried using my M&K for the main menu but no response with those either (idk if those would even work). Anyone run into this before?

**Comment by LibreVR** [comment]
Can you try turning off your Vive controllers?

**Comment by se7enred** [comment]
Hi, Run the game from the desktop with SteamVR OFF, go to the options menu and on the controller tab switch the controller on. Then exit the game, start SteamVR and the controller will work. I have that working but I do have issue #173 see below

**Comment by bboydastyck** [comment]
I dont seem to have a "Controller" tab in the options menu =(

**Comment by bboydastyck** [comment]
And under keyboard tab there is no switch or anything regarding a controller option
