### ISSUE TITLE
population one update wont allow revive to work now

### ISSUE THREAD

**Issue by sh4d0vv1** [LibreVR/Revive#1742]
**Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**

Population one from oculus just had a update and is causing the game to not be picked up by head set. the game loads but it stays on your monitor only doesnt inject into the headset 

**To Reproduce**
download population one
load game either from revive dash or steam both produce same results

**Expected behavior**
normally you load the game and it just starts like it would on a oculus headset 

**Environment (please complete the following information):**
 population one
win 10
valve index

**Versions (please complete the following information):**
 - Revive: 3.0 and prior version
 - SteamVR:  beta 1.21.4 and newest full release

**Additional context**
When i switch over to a beta test version that came out prior to thursdays release it loads perfectly fine but once changed to current version it doesnt load at all just onto monitor.

**Comment by 2115steve** [comment]
Same thing is happening to me.  Hope it gets fixed soon

**Comment by sh4d0vv1** [comment]
I have pics of what oculus debug shows error wise also

**Comment by sh4d0vv1** [comment]
Was fixed and patched

**Comment by 2115steve** [comment]
Great, thanks for reporting this.

**Comment by byancey** [comment]
> Was fixed and patched

What was fixed and how was it patched?  I see this issue is closed, but I'm still having this exact problem.  I'm running the latest version of both revive and population one.  Any more details on exactly what I need to fix this problem would be appreciated.

**Comment by byancey** [comment]
> > Was fixed and patched
> 
> What was fixed and how was it patched? I see this issue is closed, but I'm still having this exact problem. I'm running the latest version of both revive and population one. Any more details on exactly what I need to fix this problem would be appreciated.

Actually had to follow the steps in this youtube video to fix the problem...posting here so the next person who stumbles on this closed ticket will see it.

https://youtu.be/WNKfYgxJLDc
