### ISSUE TITLE
Oculus Population one support 

### ISSUE THREAD

**Issue by sh4d0vv1** [LibreVR/Revive#1744]
**Which game or application is your request about?**
Population one oculus version 

**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is. So they updated the game last Thursday and it doesn't let revive load the game properly. The game does load but only to monitor and has sound in headset. I'm guessing maybe the new oculus destinations feature may have broke it or some xr changes idk. But I'd pay someone to fix it or whatever needs to happen . 

**Describe the solution you'd like**
The game to just load and work like it has since it's release via revive 

**Describe alternatives you've considered**
There are none because you can't just transfer the data to steam version or probably can they just won't 

This is Oculus debug tool showing errors I get when loading the game with revive screen shots attached if it helps at all
**Additional context**
![20211219_193406954](https://user-images.githubusercontent.com/96320330/146701934-809d81e4-23c0-4a9d-8511-0e3d751a336a.jpg)
![20211219_193337228](https://user-images.githubusercontent.com/96320330/146701940-21056045-cd67-4368-97b0-d60c6edc7da7.jpg)
![20211219_193328425](https://user-images.githubusercontent.com/96320330/146701949-0f097954-bbda-48aa-94c0-b60e9b808e16.jpg)

**Comment by mv7945** [comment]
I am having the same issue with pop1. I uninstalled the current version of revive and installed it again. Still does not work. I checked to see if revive would work on other games such as VR chat and it did not. No other changes to my PC since pop1 update came out.

**Comment by sh4d0vv1** [comment]
I am able to still play other oculus games like contractors and saints and sinners but thinking something to either do with new oculus destinations thing or xr change idk

**Comment by vr360bln** [comment]
I already posted this issue to pop1 discord

**Comment by sh4d0vv1** [comment]
@vr360bln hey did population one quit working for you just today when it updated

**Comment by vr360bln** [comment]
@sh4d0vv1 yes....same here. I wasted two hours trying every ghetto fix of the last time back and forth. I had same behaviour with pop1 beta versions for a while, these branches stopped working on my Oculus Store/revive/SteamVR configuration, while the corresponding full releases always have done so far. Let me now if you find another stone age workaround to get access to our favourite afterwork game again 🤭😁
