### ISSUE TITLE
Population one launching stuck in full screen

### ISSUE THREAD

**Issue by samd12** [LibreVR/Revive#1750]
**Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**

**Describe the bug**
The game window launches in full screen on the PC.  You cannot minimize it or reduce its size.  It takes up the complete desktop.  There is actually no way to even access the desktop while the game is running

**To Reproduce**
Load Pop 1 using revive.  

**Expected behavior**
Game screen should launch in a window that can be moved and changed.  The windows launches and is full screen on the PC.  You cannot minimize it or reduce its size.  It takes up the complete screen and desktop.

**Environment (please complete the following information):**
 - App: population one
 - OS: Win
 - Headset: Valve Index

**Versions (please complete the following information):**
 - Revive:2.2.1 and I have to load version 1.57.0 of OVRPlugin.dll or Pop1 will not load at all
 - SteamVR: 1.20.4 (1634602223)

**Additional context**
Pop1 will not load on 3.0.  To make it run on 2.1.1 I have to replace the ovr dll manually every time
3080rtx Game Ready drivers 511.23

**Comment by ahmanwoods** [comment]
The OVRPlugin issue was fixed in https://github.com/LibreVR/Revive/pull/1745

As for the full screen issue, try pressing ALT+Enter once the game is open?

**Comment by TomFanella4** [comment]
I created a new issue here. It would be super helpful if you could vote it up! #1752
