### ISSUE TITLE
Not able to log in to Oculus Account and connect to Revive for Online VR Titles

### ISSUE THREAD

**Issue by Jlocky404** [LibreVR/Revive#1764]
So, I downloaded EchoVR which is stated working in the compatibility list. But I have a problem. I can't actually open the game because to play online titles I need to "login to my oculus account". But ever since however long ago (probably about a year) there has been absolutely no way that I know of, of creating an Oculus account on standalone. To use Oculus, you HAVE to use Facebook as your primary login, people who can log in with oculus alone with just email are people who made Oculus accounts before they made this change that only allows new users to create accounts using Facebook. One method I tried some method was running Bluestacks with an old version of an Oculus apk (v36.0.0.5.242.apk) that was supposed to allow me to make an account with only my email since this version use to allow it. But when I got about to last part of creating with my email, the app wouldn't let me continue further registration. Making me believe they possibly cut off server access to certain outdated versions of the app.

So, to sum it up in a TLDR fashion
1. You can no longer create standalone Oculus accounts using email alone, it has to be created through Facebook.
2. You are never prompted to make a password for your new Facebook/Oculus account so every login there-after has to be through Facebook.
3. Revive Dashboard for connection to online VR games REQUIRES an Oculus Account to login with standalone email and password (which is not possible anymore).
4. Since there is not option on the Revive Dashboard login prompt for Facebook account connections, I literally cannot play online Oculus VR, since Facebook will not allow you to create an Oculus account anymore without Facebook.
5. uhh pls help 
![Screenshot_162](https://user-images.githubusercontent.com/103242693/162383965-a8466749-73ae-422e-b383-3f836c180177.png)

**Expected behavior**
None, since this is my first instance of trying this. Looking for a work around

**Environment** 
App: Echo VR
OS: Win 10
Headset: Windows Mixed Reality (Lenovo Explorer)

**Versions**
Revive: 2.1.1
SteamVR: 1.22.5

**Comment by CrossVR** [comment]
You can still play Echo Arena online without logging in, you just won't be
able to join private lobbies. However joining public matches still works
fine.

**Comment by Godmorgonsverige** [comment]
https://github.com/ahmanwoods/Oculus-Defibrillator

This works in the meantime

**Comment by Jlocky404** [comment]
Issue Solved Mostly

https://github.com/LibreVR/Revive/issues/1767 // User: Fearless403
