### ISSUE TITLE
Herobound uses an old OVRUnity plugin

### ISSUE THREAD

**Issue by LibreVR** [LibreVR/Revive#177]
Herobound uses a very outdated version of the Unity Plugin. This results in a crash because it tries to make some changes to the graphics device that assumes an Oculus Rift is connected.

You can upgrade the plugin yourself by downloading [this plugin](https://developer.oculus.com/downloads/game-engines/1.3.0/OVRPlugin_for_Unity_5/) and extracting the `OVRPlugin.dll` from the win32 folder to `Oculus\Software\Software\gunfire-games-llc-herobound-spirit-champion\HeroBound2_PC_Data\Plugins`.

This works for now, but at some point we should look into making Revive compatible with older Unity plugins.

**Comment by srt23** [comment]
Herobound doesn't work with 0.9. Crashes upon start. Works great with 0.8.6 though, so not a big problem.

**Comment by LibreVR** [comment]
That crash is already fixed in the new version that will be released soon. Though Herobound still needs the updated plugin to work.

**Comment by LibreVR** [comment]
Well would you look at that, by fixing a bug in the audio API this bug is now fixed. You don't need to update the Unity plugin anymore.
