### ISSUE TITLE
Software Still here

### ISSUE THREAD

**Issue by FLOOOOOOOOOCS** [LibreVR/Revive#1779]
I Got Revive So I Could Play Echo Vr But It Was Laggy For Me And Everything But Thats Not The Problem The Problem Is That When I Uninstalled It It Was Still Lagging My Steam Vr Which Means That Theres Still Remians Of The Software

**Comment by LogMeIn-Hamachi** [comment]
I don't think there's remains of the software, what you might want to check is if steamvr is the standard openxr runtime. To do this do the following

Open steamvr settings > in the button left corner turn on advanced settings > button left corner klick developer > set steamvr as openxr runtime. While you're there you can klick on general settings again and make sure resolution is on auto.
