### ISSUE TITLE
ReVive not working in SteamVR - no menu option

### ISSUE THREAD

**Issue by Ozone72** [LibreVR/Revive#179]
I have the latest version of SteamVR, Oculus Home & ReVive installed.  I get no menu option in SteamVR, and when I manually start the ReVive Overlay, I get a crash.  Restarting Windows & SteamVR has no effect.  I had this working previously,  but this is a clean install of Windows 10 & all VR software.

**Comment by LibreVR** [comment]
Please post your logs from `%APPDATA%\Revive`.

**Comment by Ozone72** [comment]
[vrclient_ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/344723/vrclient_ReviveOverlay.txt)

Contents from ReviveOverlay.txt (would not let me attach):

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: E:\Program Files (x86)\Revive\revive.vrmanifest
Runtime directory: file:///E:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///E:/Oculus/
Loading assets manifest: file:///e:/Oculus/Software/Manifests/bulkypix-please-don-t-touch-anything-rift.json
Loading assets manifest: file:///e:/Oculus/Software/Manifests/bulkypix-please-don-t-touch-anything-rift.json.mini
Loading assets manifest: file:///e:/Oculus/Software/Manifests/bulkypix-please-don-t-touch-anything-rift_assets.json
Loading assets manifest: file:///e:/Oculus/Software/Manifests/crytek-the-climb_assets.json
Loading assets manifest: file:///e:/Oculus/Software/Manifests/oculus-henry.json
Loading assets manifest: file:///e:/Oculus/Software/Manifests/oculus-henry.json.mini
Loading assets manifest: file:///e:/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///e:/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle bulkypix-please-don-t-touch-anything-rift_assets
Loading application manifest: file:///E:/Oculus/Software/Manifests/bulkypix-please-don-t-touch-anything-rift.json
Found assets bundle crytek-the-climb_assets
Loading application manifest: file:///E:/Oculus/Software/Manifests/crytek-the-climb.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///E:/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///E:/Oculus/Software/Manifests/playful-luckys-tale.json
Found application bulkypix-please-don-t-touch-anything-rift
Found application oculus-henry


Thanks for your help.

**Comment by LibreVR** [comment]
Please update to Revive 0.7 and Oculus Home 1.5, i.e. the latest version of both.

**Comment by Ozone72** [comment]
Uinstalled & reinstalled Revive 0.7, and Oculus Home 1.5 is installed.  I don't get the ReVive menu option in SteamVR, and when I run the ReVive Overlay .exe & restart SteamVR, I get the attached error (screenshot) from VRmonitor everytime.  The headset will reboot, but I cannot get any overlay.  
Any suggestions?
![capture](https://cloud.githubusercontent.com/assets/11654039/16543001/079b6704-4074-11e6-89cd-b260b9f276bb.PNG)

**Comment by LibreVR** [comment]
You should not start Revive Dashboard before you start SteamVR. It is an application that is supposed to auto-launch when SteamVR is launched. Go to your task manager and kill all instances of `ReviveOverlay.exe` or just reboot your PC.

So just start SteamVR, then open the dashboard and check if the Revive tab is there. If it's not *then* start it manually through the start-menu *once*. After that it should automatically start on subsequent launches of SteamVR.

*Never* start the Revive Dashboard manually before launching SteamVR. In future versions I will make it impossible to do so and throw some kind of error.

**Comment by Ozone72** [comment]
Ok, got it to work - I was checking SteamVR, not seeing the ReVive option on the overlay & quitting SteamVR, starting ReviveOverlay.exe & then restarting.  After not closing SteamVR prior to running ReviveOverlay.exe it works perfectly.  Thanks.
