### ISSUE TITLE
Blaze Rush not working

### ISSUE THREAD

**Issue by MauiD** [LibreVR/Revive#1799]
Tried starting this old game to run a couple races with a friend.  Version 2.1.1 does nothing. Running version 3.0.0 the game starts but instantly crashes with the following error.

FATAL| Texture create dynamic texture: dyntexture_oculus_2d_proxy (unknown)

**Comment by MauiD** [comment]
Still fails with this error.

6:10:47.174        | Speaker mode: STEREO
16:10:47.506        | Try to setup resolution 2560x1440 1280x720 2
16:10:47.506        | reset d3d device
16:10:47.542   FATAL| Texture create dynamic texture: dyntexture_oculus_2d_proxy (unknown)

**Comment by CrossVR** [comment]
Unfortunately by not filling out the issue template I can't assist you further as it works on my end and I have no idea what your setup is.
