### ISSUE TITLE
Use the correct floor height when recentering the seated position.

### ISSUE THREAD

**Issue by gormanj** [LibreVR/Revive#18]
Great software. When launching many games, the VR universe's eye level is set to the Vive's calibrated floor thus making you way to high in the world. It would be better if there were an option to set it at runtime to match the Vive headset's height instead of the Vive's floor. This way it would not be necessary to set the Vive to standing mode. Or at least let us know where to add in an offset of our headset's height off the floor. Thank you.

**Comment by LibreVR** [comment]
Try the latest 0.3 release, it assumes a seated universe by default unless the game explicitly specifies a standing universe.

Also, please report which game you're trying to play.

**Comment by gormanj** [comment]
I tried the 0.3 release with  NewRetroArcade-4.0.0 and the same thing happens, that is regardless of where the hmd is the camera's origin is set to the floor and offset by however high off the floor the HMD is, This makes the user's position way too high. It is the same with all the games below. The workaround is to use the developer option quick setup for standing. However since the Vive does not store multiple setups to facilitate easy switching, it is a real pain to have to setup up your room every time you want to use a roomscale app.

911 Experience
Affected v1.62
AIrborneVR19441.1
Battletank VR
BoursinSensorium2
Castlecoaster
Deep_space_VR-pc
Elevator_Horror_-pc
filenames.txt
Flying Aces VR
Go For Launch Mercury Alpha Demo 2
HalloweenCoaster_V1.8.0
harvest-simulator-vr
LA2097_v0.9.0 1.3 no music
Linear Crossing
Lollihop
Negotiator-pc
Neruo-1.0.0
PushForEmor-Demo-0.1
Since They Left Chapter 0
SkyFighter
SnowCoaster-pc
Star Wars Battle of Endor
TheCaretaker-1.1
TheNightCafe
TimeMachineVR
VR Karts
VR Ski Jump
Ziran - Passage to Nature

**Comment by LibreVR** [comment]
Revive injector uses the same library as all the other patches, it is unrelated to this issue.

I suggest you follow the seated calibration instructions, see if that fixes the issue:

> If you need to recenter the headset you can do so in the Steam VR dashboard by going to Settings > VR Settings > General VR Settings > Reset Seated Position.

**Comment by gormanj** [comment]
If I set the Vive for standing mode (I use the developer quick setup), all the Unreal games work fine at as long as I am at that height (any active option to reset the HMD position only resets it horizontally). But then it becomes a pain to have to switch back to room scale if you want to calibrate your actual space instead of using a quick setup in developer options.

However, all the unity games using the patch have no problem setting up the position of the HDM properly when they launch and also the rest options in those games work well. In other words, for all unity games, I can use my room scale setup without changing anything. The unreal games require me to change my setup to standing scale or unless you are laying on the floor, the position of the HMD camera is way to high.

**Comment by LibreVR** [comment]
Please don't change the title to something that could be confusing, it is not an issue with the Injector. It's purely a coincidence that games using the injector are affected by this issue.

**Comment by LibreVR** [comment]
Fixed by commit eae09ce6c8a7f0dd641474e2c152bb87af6369f5.

**Comment by LibreVR** [comment]
Defaulting to a seated origin is correct after all, so I reverted the revert in commit 439e662895b521afea2596622cdca3212b3df4fc.

I'm still looking into why some demos can't handle a seated universe.

**Comment by LibreVR** [comment]
Fully fixed in commit f87b8995ac1e836ad4513f75a60cb7142da7326a.

I'm considering releasing 0.4.1 as this is a very important change.

**Comment by gormanj** [comment]
The issue does not appear fixed for me using 0.4.1. When I launch some games, even after resetting the came via the game or the Vive's seated position reset, the the headset needs to be placed on the physical floor to be at the proper in game height. This behavior occurs in NewRetroArcade, AIrborneVR1944 and also the free downloadable version of Time Machine VR from wearVR.com (the last example of which it is very obvious because the headset will only be in the proper position above the fully body avatar when it is placed on the playing area's actual physical floor).

**Comment by EGGroup** [comment]
Just a quick message to say that I have exactly the same problem in The Climb and BlazeRush, Lucky's Tale and Defense Grid works perfectly. Tried to sit on the floor but it still a bit too high.

**Comment by gormanj** [comment]
EG Group > If you go to the settings on the SteamVR app window when it is running and then Developer, you can find a quick setup for standing scale (in a popup among others). If you use this with the HMD in the middle of where you will stand, then when you play everything will work fine. Of course you will need to set your room scale up again later (if you are lucky like me, maybe one of the presets will work okay for you). This way RetroArcade is perfect as well. Not a solution, but a workaround.

**Comment by MasterElwood** [comment]
@EGGroup the climb has a dedicated button on the xbox controller to reset the camera. works great.

**Comment by gormanj** [comment]
In many unreal apps, the camera reset only worked horizontally for me. I do not have the Climb.

**Comment by Techy76** [comment]
I'm experiencing the same issue with apps like Airborn VR 1944.
I have to deposit my headset on the floor to be at the proper height. There's a camera reset feature in the app but like GormanJ says. it only adjusts the Horizontal position. 
I haven't purchased any Oculus titles because I fear that they might not work properly.

**Comment by gormanj** [comment]
Everything I've tried on Oculus seems to be working pretty well now (The Climb, Pinball FX 2 VR and some freebies). I recommend getting Open VR Advanced settings as it has features to reset the floor without leaving the game.

**Comment by Armada651** [comment]
@Techy76 That is indeed what I've been expecting from some other games. It seems that the Oculus SDK still has a floor offset, even in seated mode unlike OpenVR.

I plan to fix that at some point, but it's currently not a priority.

**Comment by Armada651** [comment]
This should be fixed in the latest release: https://github.com/LibreVR/Revive/releases/tag/1.1
