### ISSUE TITLE
Laggy Subnautica?

### ISSUE THREAD

**Issue by bboydastyck** [LibreVR/Revive#180]
Hello everyone, back with a separate issue. So i finally got the game running and controller working but now when im in the game i get a bit of lag, not too significant i can definitely play the game but only for so long. Whether i set the settings to high or low the lag is the same, happens in close distance areas and far distance areas (the ocean). 

Currently running a i7 4790k, 16gb ram, and an overclocked gtx1080 so i feel like i shouldnt have this issue at all.

**Comment by LibreVR** [comment]
I've tested it out, it seems likely that Subnautica relies on ATW to run smoothly. This may explain why there is no Vive support yet.

**Comment by LibreVR** [comment]
Can you try playing this game with the following option enabled: `Steam VR Settings -> Developer -> Always On Reprojection`? It should help a lot for Revive game as it turns off Late Start which is a major bottleneck for Revive right now.

**Comment by kujohn** [comment]
`Always On Reprojection` enabled seems to work better but still laggy. Turning all graphical settings to minimum and 1.0 SS barely makes it playable. 😢

**Comment by BroHawk69** [comment]
In my case, it launches fine, but lags horribly and the menu spawns below the floor. There is no immediate way to play the game or load up a save. Any fix?

**Comment by hyperseven** [comment]
Has native Vive support?  Don't use ReVive.

**Comment by Armada651** [comment]
Yeah, subnautica has native Vive support now.
