### ISSUE TITLE
DOWNLOAD LAST VERSION REVIVE 3.0.0.61

### ISSUE THREAD

**Issue by ReverquestVR** [LibreVR/Revive#1805]
Hi

In your Gifthub tell us that download the last early version 3.0.0.61, download in appveyor but inside appveyor I dont see link to download that version or new versions

Please help me

Thanks

**Comment by LogMeIn-Hamachi** [comment]
If you are willing to join revive discord you can use this message link and see that it's from NERO: https://discord.com/channels/313285397801205761/313285397801205761/997593210085974057

It has the file.

**Comment by ReverquestVR** [comment]
Hi. Link dont work

**Comment by LogMeIn-Hamachi** [comment]
> 

Yes because you need too be a member of the revive discord.

I did not want too just send the download link without any context who sent the file. It could be anything then.

If you just the discord you can click on the link and see that it's from one of tje developers.

**Comment by ReverquestVR** [comment]
OK Which is link Discord Revive? Thanks

**Comment by starlesskye** [comment]
> OK Which is link Discord Revive? Thanks

You can find their discord on their wiki: https://github.com/LibreVR/Revive/wiki
