### ISSUE TITLE
Oculus account not linking to revive

### ISSUE THREAD

**Issue by Rhyflwhyr** [LibreVR/Revive#1807]
**Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**

**Describe the bug**

**To Reproduce**
1. Go to 'Startt menu/Revive/Revive Dashboard'
2. Click on '^ (On right side of taskbar)/ '
3. Right click on 'Revive Dashboard/ Link Oculus Account'
5. See error

**Expected behavior**
Enter username and password and check the remember me box then have the oculus account link

**Environment (please complete the following information):**
 - App: Revive Dashboard
 - OS: Windows 10
 - Headset: Index

**Versions (please complete the following information):**
 - Revive: 2.1.1
 - SteamVR:
**Additional context**
I've reset my oculus password to make sure its correct when submitted to revive and I've ensured two-factor notification is turned off.

**Comment by CrossVR** [comment]
This feature no longer works due to the removal of Oculus Accounts. It has never worked with Meta accounts.
