### ISSUE TITLE
Stormland stutter / won't launch

### ISSUE THREAD

**Issue by therealcharmics** [LibreVR/Revive#1808]
I am aware that there are other similar issues but I find them to be different in notable ways, or their descriptions are wholly insufficient. Hopefully this will be more helpful.

I have a WMR Samsung Odyssey and latest SteamVR and WMR for SteamVR. I have an Nvidia 2080s with the latest drivers. Windows 10 Pro 21H2 19044.2604. I do not use virtual desktop or any other layers. I do have MSI Afterburner, FPSVR (steamapp), and OVR Advanced Settings. 

- On ReVive 2.1.1 without using OpenXR runtime, the game runs, but it seems the reprojection is not working, or isn't working correctly. Additionally, the game has produces lots of frametime spikes, which I assume is normal, but maybe caused by ReVive. Together, this causes the game to be extremely juddery. 

- On ReVive 3.1.1 without using OpenXR runtime, the game gets stuck on a black screen immediately. My framerate reporting tools show that no frames are being rendered. The game has CPU use but static ram, no disk, and no GPU usage. 

- On either ReVive version with usage of the OpenXR Runtime, the game does not appear to load at all. The blue WMR fade in occurs, but it fades out immediately, returning me to the WMR home, and nothing else happens.

**Comment by CrossVR** [comment]
Try this build once it finishes compiling: https://ci.appveyor.com/project/LibreVR/revive/builds/46504632/artifacts

**Comment by therealcharmics** [comment]
Thank you for the quick response! 

OpenXR still isn't working for me on this build, but running without it through SteamVR does work, and reprojection is operating beautifully! 

However, the performance characteristics are very unusual. According to FPSVR, the GPU frametimes are generally a bit better and more consistent than they were with ReVive 2.1.1. However, overall performance has been just about cut in half, as the CPU frametimes have gone up from about 6ms to nearly 20ms for each frame. The game is running at about 46 FPS, which is verified by MSI Afterburner on the overlay as well as by watching motion within the world.

**Comment by CrossVR** [comment]
Can you try out this build? https://ci.appveyor.com/project/LibreVR/revive/builds/46514397/artifacts

**Comment by therealcharmics** [comment]
Beautiful. Performance is better and more stable than any other version I've tried, with no strange CPU behavior and relatively stable frametimes. Reprojection is working perfectly as well. I was able to switch from running at lowest to running at ultra, and I'm still getting over 90FPS most of the time. 

Snap turning and fast movement causes longer frametimes, but I believe its safe to say that's normal game behavior, as they are not exceptionally high and reprojection smooths them over. 

On behalf of the WMR community, thank you!

**Comment by CrossVR** [comment]
That's still just a test though, but good to know that there's still some CPU optimizations to be made.

**Comment by therealcharmics** [comment]
Ah, maybe? The frametime spikes while moving and snap turning are reported as on the GPU side by FPSVR. (I failed to specific previously.)

CPU wise, the frametimes seem to be consistently under 10ms. It's possible they could be better, but I don't see evidence of it with this latest test.

**Comment by CrossVR** [comment]
Better to wait until the next proper release once I figure out the correct frame sync behavior.
