### ISSUE TITLE
"Patching option has been removed from the tray icon to avoid user confusion"

### ISSUE THREAD

**Issue by TimberAngry** [LibreVR/Revive#1809]
Hello, confused user here that just wants to patch, so that I don't need to Inject every time.

Can someone please share what files I need to copy? Thanks.

**Comment by CrossVR** [comment]
I actually implemented an alternative, if you go to the install folder of Revive (`C:\Program Files\Revive`) there's a file called `hook.cmd`. Run that file as an admin and enter the filename of the game's executable you want to hook, just the name and extension, not the full path. (i.e. `Game.exe`)

After you've done that the game will always run with Revive. If you want to undo the hook simply repeat the same process. Entering the filename of an executable that's already hooked will undo it.

**Comment by TimberAngry** [comment]
Thanks very much, that works.
FYI there was an issue though, when I tried to run my Game.exe, Windows Defender kicked in and quarantined the ReviveInjector.exe lol. Classed it as a Severe threat. Had to restore it from Defender. This is on Windows 11 Version 10.0.22622 Build 22622

**Comment by CrossVR** [comment]
The ReviveInjector has always been skirting the line of what virus scanners find acceptable. I guess this is the final straw for Windows Defender.

**Comment by CrossVR** [comment]
New release has an option to create a shortcut on the desktop that runs an executable with the injector without requiring the hooking script or the XInput DLLs: https://github.com/LibreVR/Revive/releases/tag/3.2.0
