### ISSUE TITLE
Inject doesn't work in any way

### ISSUE THREAD

**Issue by bobueno** [LibreVR/Revive#1811]
Hi guys, i made an account so i could write an issue here

Basically i have vader immortal and Asgard's wrath as external games but whenever i try injecting them, they never work no matter what i do, they never detect the 'VR mode' and always appear in normal screen mode saying they dont detect my controllers

i've tried everything, injecting via bottom menu, injecting dragging the .exe in the ReviveInjector, adding the Revive injector to Steam and using the path of the game, and everything have the same result no matter what i do, i'm starting to loose hope, if anyone could help me with a final incredible unexpected solution, it would be awesome, for now, i haven't managed to make it detect my controllers no matter what i do, thanks in advance

**Comment by CrossVR** [comment]
You're injecting into the launcher instead of the real executable. There should be a `...-Win64-Shipping.exe` executable somewhere in the game folder. I recommend using the Revive Dashboard or your Steam Library to launch the game as it will find it for you.
