### ISSUE TITLE
AirMech: Command entitlement error

### ISSUE THREAD

**Issue by HawkDriver** [LibreVR/Revive#184]
As of July 3rd, new install of Revive and new install of AirMech Commander seems to have the entitlement error. It works in headset but the entitlement screen is in front of your face and when you press A, the game exits. --Never mind, I failed to restart the Oculus home after installation (As the instructions state) Entitlement error = You need to restart Oculus home.

**Comment by LibreVR** [comment]
> new install of AirMech Command

> Newly installed games will give you an Entitlement check failed error until you reboot the Oculus service, quickest way to do that is through Oculus Home Settings > Beta > Restart Oculus.
