### ISSUE TITLE
Population One controllers wrong angle

### ISSUE THREAD

**Issue by omegakitty** [LibreVR/Revive#1843]
**Describe the bug**
controllers at wrong angle

launch game 

**Expected behavior**
hands lined up with controllers

**Environment**
 - App: Population one
 - OS: Win10
 - Headset: Index

**Versions:**
 - Revive: 3.2.0
 - SteamVR: 2.1.10

**Additional context**
![Screenshot 2023-12-04 212853](https://github.com/LibreVR/Revive/assets/103003649/e3070736-4b44-4574-852c-8d959a71db12)

**Comment by omegakitty** [comment]
experimental branch in pop1 fixes it mostly

**Comment by haydnpugs11** [comment]
It's still an issue, the experimental branch doesn't change anything.
