### ISSUE TITLE
Unable to access Oculus games from library when using Revive combined with the Dash killer

### ISSUE THREAD

**Issue by Joryho7** [LibreVR/Revive#1850]
**Describe the bug**
The title says it all, really. When using the Revive launcher in tandem with BunniKaitlyn's Dash Killer to improve Oculus headset performance and playability, not a single oculus library game can be played (presumably. Only been tried with Asgard's Wrath). It completely fails the entitlement check despite being launched from Revive. Opening the game through Oculus causes it to have issues with SteamVR and sees it as a separate app, not allowing me to open the game.

**To Reproduce**
1. Install the Dash killer and Revive, making the headset an effectively native SteamVR headset
2. Open any app (Asgard's Wrath 1 as example) via Revive
3. Get hit with an entitlement check failure

**Expected behavior**
The game should open with no issues, as it's owned in the library.

**Environment (please complete the following information):**
 - App: Asgard's Wrath
 - OS: Windows 10
 - Headset: Oculus Quest 3

**Versions (please complete the following information):**
 - Revive: 3.2.0 (latest)
 - SteamVR: 2.4 (latest)

**Additional context**
I don't at ALL expect any sort of compatibility patch to fix an issue like this, but I feel like it should be done for futureproofing reasons. My system is slightly underpowered (if an RTX 2060 TI counts as underpowered) and causes games played through the oculus dashboard to visibly hitch for a few moments at a time. The headset's view, for reasons unknown to me, will desync with the computer's view when this hitch happens, causing a very minor, but downright sickening delay.
I can't physically play PCVR without killing the Oculus dashboard (or at the very least, without having to deal with the desync).

**Comment by CrossVR** [comment]
If you're failing the entitlement check then there's not much Revive can do about that. Revive doesn't do anything special to pass the entitlement check, it relies on the Oculus software to approve the entitlement check, anything that interferes with that by killing certain Oculus services will cause it to fail.

> not a single oculus library game can be played (presumably. Only been tried with Asgard's Wrath).

Also please don't do this. Saying every game is affected when you really have no idea can cause developers to make wrong assumptions about the cause of an issue which will just result in it taking longer to resolve.
