### ISSUE TITLE
Support for standard non vr mode?

### ISSUE THREAD

**Issue by andrewpros** [LibreVR/Revive#186]
Hi.

I was thinking that it would be great if this software supports some standard non vr mode for those you want to play oculus games without having oculus/vive or any other vr headset.

Now you may as why, cuz there are some great games on oculus and vive, but you can't play them until you buy a vr set, it is a shame that there isn't non vr modes in such games.

Now revive could make this happen, just translate keyboard/mouse/controller movement/presses to compatible with what game is expecting from oculus and we are good to go.

Not sure if we can make something with vr rendering, at least i think it is doable to just display one half in fullscreen to play on tv/monitor.

What do you think about such option, maybe it could in cooperation with riftcat etc.

**Comment by LibreVR** [comment]
This is already possible by using the null driver in OpenVR. You can activate this driver by adding to following to your `steam.vrsettings` files in the `C:\Program Files (x86)\Steam\Config` folder:

```
    "driver_null" : {
		"enable": true,
		"id": "Null Driver",
		"serialNumber": "Null 4711",
		"modelNumber": "Null Model Number",
		"windowX": 100,
		"windowY": 100,
		"windowWidth": 1920,
		"windowHeight": 1080,
		"renderWidth": 1344,
		"renderHeight": 1512,
		"secondsFromVsyncToPhotons": 0.1,
		"displayFrequency": 90
   },
```

More information on the Valve wiki: https://developer.valvesoftware.com/wiki/SteamVR/steamvr.vrsettings

**Comment by andrewpros** [comment]
Didn't know that, thx.

**Comment by andrewpros** [comment]
@LibreVR 

Why this is closed? Null driver won't work at all, it will not allow me to play those games like a normal game, it doesn't emulate mouse as moving head etc.

Well, is it closed cuz there is not chance to make it like i described?

**Comment by LibreVR** [comment]
Yes, I closed it because it is completely unrelated to Revive. If you want to play VR games on a monitor then you should write an OpenVR driver that allows you to do that.

I have no interest in doing that and Revive doesn't care which driver you use, so it doesn't involve Revive in any way.

**Comment by andrewpros** [comment]
I wouldn't see it has nothing to do with revive, without it i can't run oculus games, without oculus, so it is oblivious to me that i need to find something that will work with revive somehow.

But i get it.

So thx for the driver tip, this is what i was looking for.

**Comment by LibreVR** [comment]
Revive does not care which driver you use, so it is by definition outside of the scope of this project.
