### ISSUE TITLE
Eve: Valkyrie "No Oculus Entitlement"

### ISSUE THREAD

**Issue by Epyx911** [LibreVR/Revive#187]
Hi there I tried this from issue#164:

"For entitlement errors, please restart the Oculus service by going to Settings > Beta > Restart Oculus in Oculus Home."

I tried it multiple times but each time I continue to get the "No Oculus Entitlement"  [A] RETRY. Any other things I can do or check?

THanks very much in advance!

**Comment by LibreVR** [comment]
On the front page:

> Newly installed games will give you an Entitlement check failed error until you reboot the Oculus service, quickest way to do that is through Oculus Home Settings > Beta > Restart Oculus.

**Comment by Epyx911** [comment]
Hi, LIbreVR Not sure you read my ticket but I had indicated I tried that?

**Comment by Epyx911** [comment]
Respectful tone...text sucks for conveying tone but yes I did try to restart it several times...even rebooted entire pc tried again and continue to get the entitlement error.

**Comment by LibreVR** [comment]
Are you running Oculus Home 1.5? (You can see this in the General settings tab)
