### ISSUE TITLE
Various Illusion games/tech demos don't work

### ISSUE THREAD

**Issue by billyboy12** [LibreVR/Revive#19]
Illusion (Japanese erotic game studio) have made a few Rift tech demos here and there, but I haven't been able to get them fully functional on the Vive myself. Illusion mostly uses Unity, so I've been using some of the Revive Unity plugins. This gets the demos loading, but you can't control them.

Yunalus (http://download.illusion.jp/download/dl3.cgi?dlname=Yunalus_Win.zip&count=Yunalus_Win)
A very early tech demo, can be played by running the Vive in Direct mode, exiting SteamVR and setting the game to load on the Vive's screen. Can't be controlled by the Vive.

PlayGirls (http://dl.playgirls.tokyo/dl3.cgi?dlname=PGOMtrial.zip&count=pgom)
Loads, but can't be controlled.

Sexy Beach Premium Resort 
(https://mega.nz/#!9kFjhSJD!uHAAHC8AnktHUaWjhGOC24pXnxrh83e_OtYRTA8kQ80)
Loads, but can't be controlled.

**Comment by LibreVR** [comment]
I don't think these games use the 1.3 SDK, so they're not compatible with Revive.
