### ISSUE TITLE
Mythos Of The World Axis: UE4-WorldAxis crashed

### ISSUE THREAD

**Issue by noodle1009** [LibreVR/Revive#190]
see title, log files are attached.

[logs.zip](https://github.com/LibreVR/Revive/files/348458/logs.zip)

I have never been able to successfully launch this title from Revive's overlay (or standalone with the patch or injector).

This is a crash on launch - maybe not Revive related at all - perhaps UE4 related.

Running Windows 10 x64 Insider build 14376

If I can provide more information please let me know - thanks!

**Comment by iamwes** [comment]
This has never worked for me either, same error

**Comment by ProfessorS1** [comment]
Same here

**Comment by LibreVR** [comment]
Well, that was easy. Fixed in commit da98af432f3dcfc6b9f3d2e19efa1ac4f4ed8179.

**Comment by LibreVR** [comment]
This is such a small mistake, I think I'll make this into a hotfix.

**Comment by LibreVR** [comment]
New release is out, download links on the front page are updated.

**Comment by iamwes** [comment]
Works great thanks.... that was in interesting little game...
