### ISSUE TITLE
Game is stuttering in certain areas of Lucky's Tale

### ISSUE THREAD

**Issue by simblarosh** [LibreVR/Revive#192]
I have been playing Luckys Tale and Farlands. Both have had some slight FPS drops or Stuttering in certain areas. Other times they run perfect like if I look towards a certain area.... Have you or anyone else noticed this? Could this bee from reflective surfaces? Just Guessing?

My RIG: I7 4790, GTX970

**Comment by LibreVR** [comment]
My own PC is still below the minimum spec, so I haven't done a lot of performance testing yet. I'll be sure to do some more performance testing before the first stable release of Revive.

**Comment by Rojoyinc** [comment]
Could be. No mine is smooth no stutters. Zotac 980ti. 6gb.

**Comment by simblarosh** [comment]
OK Cool, Libre what PC components are you currently running??? You do have a VIVE, right? Just curious.....

**Comment by simblarosh** [comment]
Also Im wondering if you think that some of the upcoming oculus touch games will work with the vive and roomscale?? Using vive controllers?

**Comment by LibreVR** [comment]
@simblarosh I do have a Vive, but my GPU is the GTX680, so yeah that's barely the minimum.

Revive already supports emulating the touch controllers, but there are no games to test it with yet, so it may still need some optimizations.

**Comment by simblarosh** [comment]
@LibreVR Thanks for the quick replies! I am looking forward to using your software with those controllers!! You should pickup one of those pascal cards bro, they are pretty amazing!

**Comment by nomansfry** [comment]
When do you see this issue? Can't say I have noticed it . Running AMD R9 Nano..

**Comment by openconcerto** [comment]
I was able to reproduce the problem on a GeForce 1080, Intel Core i7, 32GB of memory... on complex scenes, looking at the main caracter is causing shuttering.

**Comment by LibreVR** [comment]
I'm assuming this is fixed with the new asynchronous reprojection support.
