### ISSUE TITLE
Uninstall revive ?

### ISSUE THREAD

**Issue by Asfalt-FR** [LibreVR/Revive#194]
How uninstall revive ? installed by reviveinstaller.exe on Windows?

**Comment by LibreVR** [comment]
There's an uninstaller in the main menu, probably also in 'Programs and Features'.

Is there any reason specifically why you're uninstalling Revive?

**Comment by Asfalt-FR** [comment]
Not a problem, it is a very good work! Need to uninstall on a computer

**Comment by LibreVR** [comment]
So yeah, just go to the Start Menu, look for the Revive folder and run the uninstaller.

You can also find the uninstaller in the directory where you installed Revive.
