### ISSUE TITLE
Pinball FX2 VR no longer launches

### ISSUE THREAD

**Issue by noodle1009** [LibreVR/Revive#195]
including a screenshot of the error, not sure where I can find more diagnostic data.

This was working as recently as a couple of weeks ago (at least in 0.7 it did), not sure what would have changed between then and now?

![pfxvr](https://cloud.githubusercontent.com/assets/10852040/16660149/cd7b47e8-4432-11e6-89ec-854fe62fdb63.png)

If there is more data I can provide, please let me know!

**Comment by LibreVR** [comment]
Can you test the previous version? It's still available for download here: https://github.com/LibreVR/Revive/releases/tag/0.7

**Comment by noodle1009** [comment]
it works with the revive injector from 0.7 without issue

**Comment by LibreVR** [comment]
Found the issue, will create a hotfix.

**Comment by LibreVR** [comment]
Fixed in 11c4fec161d8d4fb2ec6fab9012535efec258c64.

Go to the frontpage to download the new release.

**Comment by noodle1009** [comment]
works perfectly - thanks!

**Comment by gormanj** [comment]
Tested and working with Revive injector 0.8.3 and Oculus runtime 1.5. Been waiting for this one. Thanks LibreVR!

**Comment by gormanj** [comment]
BTW, if you are looking for a stand to put your arcade stick or keyboard on for pinball, try this one. I got it. It is very sturdy:
https://www.amazon.com/Seville-Classics-WEB162-Mobile-Laptop/dp/B0097GMHXG
