### ISSUE TITLE
The latest 0.8.3 doesn't work with oculus-dreamdeck?

### ISSUE THREAD

**Issue by matrixcr** [LibreVR/Revive#196]
I can't bring up oculus-dreamdeck using latest ReviveInjector 0.8.3 on Oculus runtime 1.5. But it works well with the injector I previously installed for OC 1.3.2

**Comment by LibreVR** [comment]
That seems unlikely, since I specifically tested Dreamdeck before releasing that hotfix.

Can you send me your log files from `%APPDATA%\Revive`?

**Comment by matrixcr** [comment]
ReviveInjector.log:

Launched injector with: "D:\Oculus\Software\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" D:\Oculus\Software\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe
Creating process: D:\Oculus\Software\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe 
Injecting DLL: D:\Oculus\Software\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x76aa6500
Injecting DLL: D:\Oculus\Software\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x76aa6500
Injected dlls succesfully

**Comment by matrixcr** [comment]
BTW, I didn't use htc vive with steamvr, I used OSVR dk1.

**Comment by gormanj** [comment]
Dreamdeck is working for me with Revive 0.8.3 and Oculus RT 1.5 on HTC Vive hardware both the injector run on my desktop and the Revive Dash app in Steam VR.
