### ISSUE TITLE
Black Hat Cooperative

### ISSUE THREAD

**Issue by newend** [LibreVR/Revive#199]
Was just wandering if anyone has tried this game with Revive?

**Comment by Chromega** [comment]
Developer of BHC here!  I haven't actually tried out the game with Revive, but I did want to point out that native Vive support is coming to BHC in our Steam release!  I have it working, there's just one Unity bug I'm waiting on a fix for in the 5.4 beta.

**Comment by LibreVR** [comment]
@Chromega Were you able to integrate Vive support or test it with Revive?

Also, thanks for personally responding on the issue tracker.

**Comment by Chromega** [comment]
We have native Vive support in our Steam release!  We have not tested
Revive with the Oculus Store build.

We're also sending out an update on Monday with new levels and new
locomotion options (motion sickness proof options), so stay tuned!

**Comment by LibreVR** [comment]
Thanks for the quick response, I'll close this issue then.
