### ISSUE TITLE
Lucky's Tale stutters when launched through Steam

### ISSUE THREAD

**Issue by Enderzt** [LibreVR/Revive#2]
The patch worked flawlessly and I was able to boot the game without issue. But I have very bad stuttering issues when moving the camera. If I hold my head still, the game runs butter smooth. 

System Specs:
i5 6500k @ 4.5 Ghz
R9 290 Vapor X @ 1100 Mhz
16 GB GDDR4 @ 3000 Mhz

CPU, Ram, and GPU running around 30-50% during the game. The onscreen left eye copy of the video on the desktop is smooth during headtracking. Only happening in the headset. Let me know if you need anymore information.

**Comment by mcassano** [comment]
I suspect this is a computer performance issue.  The LT patch works for me, but in DCS I get tracking stuttering if I bump the graphic quality way up.  What score does your PC get in the SteamVR Performance Test?  Do you have clean tracking in SteamVR games?

**Comment by PaulKlinger** [comment]
I had the same issue when launching the game from inside steamvr (added as a non-steam game). When I closed it and directly launched LT.exe from the desktop the problem went away.

**Comment by Enderzt** [comment]
@PaulKlinger You are exactly right! When I launch directly from the LT.exe everything is perfect, no stuttering for head movement. But launching from Steam by adding it as a non-steam game causes the issue to return. That narrows down the reasoning for the issue quite a bit.

**Comment by LibreVR** [comment]
Revive now has SteamVR integration, it will be part of the next release.
