### ISSUE TITLE
Darknet only shows a 3d arrow floating in space

### ISSUE THREAD

**Issue by GreasyWeasel** [LibreVR/Revive#20]
I tried using the injector with Darknet, which is a Unity game, it allows the game to get passed the Oculus HMD check but then it just sits at the loading screen on the monitor and never continues. Nothing appears in the Vive HMD.

**Comment by LibreVR** [comment]
If it's a Unity game, try the Lucky's Tale patch or wait until the release of version 0.4 which will have an injector that's compatible with Unity.

**Comment by gormanj** [comment]
From what I can tell, the Unity hook currently requires that the developer is using the OVRPlugin.dll. That plugin is replaced with the hack. If that plugin is not used, the hack that relies on the OVRPlugin.dll plugin will not work. Perhaps they will create a hook for the older OculusPlugin.dll in another version.

**Comment by GreasyWeasel** [comment]
Darknet does use the OVRPlugin.dll, or at least it's included in the Oculus Store download. I've tried both the injector and the Lucky's Tale patch and I can't get either to work.

**Comment by gormanj** [comment]
Sorry for the confusion, I deleted my comment regarding OVRPlugin.dll because I was looking at DarknetFlavorDemo2 from darknetgame.com for DK2 that is not from the Oculus Store.

**Comment by GreasyWeasel** [comment]
Darknet will now start up with the the ReviveInjector v0.4. It comes up in the Vive but the main game screen quickly switches to a 3d arrow floating in space but I can't seem to get the game to come back.

**Comment by gormanj** [comment]
That arrow is a unity graphic indicating you are out of the p[lay area (too high, I think). I get that on a couple of games myself.

**Comment by LibreVR** [comment]
This is probably due to the base stations being oriented differently, the game probably thinks they're aimed away from you. I will fix this in the next version.

**Comment by LibreVR** [comment]
Should be fixed with 22493e1a34c6bc4f70bd5fb216e0c3d3eae5457f, please test the next version once it is released.

**Comment by gormanj** [comment]
This problem is fixed for me with TPDragons1.3 in Revive version 0.5.0

**Comment by sirkitree** [comment]
In trying this I get a message "Entitlement Check Failed" in the game. Couldn't find anything online about this. Just purchased Darknet through the Oculus Store, re-installed 0.5.0 of Revive, game boots from the Revive menu in SteamVR but then I see that message.

**Comment by sirkitree** [comment]
No matter what I do I can't seem to get past the "Entitlement Check Failed" message. I've rebooted Oculus through the settings > beta menu, restarted SteamVR, rebooted my whole machine, tried re-installing 0.5.1 - no luck.

**Comment by gormanj** [comment]
Please see issue 100. Oculus has updated their software (runtime?) which will render some games downloaded from Oculus Home inoperable with Revive for now.

**Comment by JediDiggler** [comment]
This seems to be working great here BTW.

**Comment by LibreVR** [comment]
Yeah, this has long since been fixed, I've updated the compatibility list.

**Comment by steeltoelinden** [comment]
I downloaded Darknet just now, running it on my Rift CV1. I've adjusted the Rift sensor up and down, and moved my head to face every direction. The entire UI fades out when I move my head upward, and the floating/wiggling 3D arrow right in front of my eyes never goes away.  Is there anything I can do about this?

**Comment by LibreVR** [comment]
@steeltoelinden This isn't Oculus support, you should take Oculus Rift problems up with them.

**Comment by steeltoelinden** [comment]
@LibreVR  It's a Darknet issue, not a Rift issue. The title of this thread matches the problem I'm experiencing. which is why I added a comment on this thread, hoping for constructive advice.

**Comment by LibreVR** [comment]
@steeltoelinden But this is not the Darknet issue tracker either is it? This is for Revive issues only, I don't want Revive issues being drowned out by unrelated discussions.
