### ISSUE TITLE
Dirt Rally Steam

### ISSUE THREAD

**Issue by appdevtk** [LibreVR/Revive#200]
I've tried Dirt Rally with the patch and the injector. It does not start with VR enabled using the patch. 
The injector starts Dirt Rally VR with working tracking, but the game renders only to the left eye. The UI is rendered to both eyes.

Did someone get it to work?

**Comment by mrbelowski** [comment]
Does this issue refer to the Oculus Store version of the game or the Steam version (or both)?

**Comment by LibreVR** [comment]
Is there a difference?

**Comment by mrbelowski** [comment]
I don't know - a chap on the Steam Dirt Rally forum wasn't able to get the game to launch at all using the Revive injector, which made me wonder if Steam's DRM / anti-cheat stuff is breaking things for Steam users, whereas the left-eye-only issue reported here only applies to the non-steam version.

Will do some of my own testing this evening

**Comment by Walleyed** [comment]
Just to confirm, yes Injector is working with the Steam version too, but as per above, it only renders to left eye.

**Comment by TOCA2FREAK** [comment]
Please get this working.  :)

**Comment by Layseyla** [comment]
Also looking forward to it, Good luck!  Great Job BTW with all your hard work

**Comment by mrbelowski** [comment]
Are you guys using the latest version of the nvidia driver (which has a dirt rally profile)?

**Comment by Walleyed** [comment]
Yes, using latest driver version 368.69 here (Dirt Rally VR game ready driver).

**Comment by Layseyla** [comment]
Yes im sure we all are

**Comment by Layseyla** [comment]
has anyone got this working yet?

**Comment by fruehr** [comment]
Same here, just some extra info:
- game is rendered in left eye only, as others have said
- right eye shows chaperone bounds, though
- perspective is distorted, everything stretched out forward, e.g. legs and car are super long
Compared with running on DK2 just to check, perspective is normal (as expected) there.

**Comment by LibreVR** [comment]
Fixed in commit 000ff3c568731177fad6da4ae00103f475479dd0.

I will release a hotfix very soon.

**Comment by LibreVR** [comment]
Hotfix released: https://github.com/LibreVR/Revive/releases/tag/0.8.5

**Comment by Walleyed** [comment]
Yes, this works beautifully now. Very grateful to you, thanks!
