### ISSUE TITLE
Games not launching at all :/

### ISSUE THREAD

**Issue by AlanRoberts91** [LibreVR/Revive#203]
I am trying to use the 0.8.3 version of Revive with the 1.5.0.2... version of the Oculus Runtime. I see the revive tab and will click on a game, but it doesn't load or anything. I have restarted my of multiple times as well as reinstalled software, yet nothing works. Before with the 1.3.2 RunTime, I had no problem with the injector. 
I also found a shortcut launch fail error message when launching from the SteamVR menus. However I am able to use the Revive injector to get Lucky's tale to me a HMD not found warning. 

One last thing. When running the Revive tab, I think it is causing a issue with SteamVR. I have to manually force Steam to close and open up task manager to end the vrserver. 

Here is a link to the Reddit post: https://www.reddit.com/r/Vive/comments/4s8mii/revive_not_working_for_me_at_least/

**Comment by LibreVR** [comment]
Please post the contents of your logs in `%APPDATA%\Revive`.

**Comment by AlanRoberts91** [comment]
Here is the over lay log file:
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found application oculus-henry
Found application oculus-oculus-video
Found application playful-luckys-tale
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()

**Comment by LibreVR** [comment]
Are you sure you're missing the Injector log?

**Comment by AlanRoberts91** [comment]
Oops, sorry. Here it is. I did have dreamdeck dowload, I was just trying to find a file that would work. The only thing that happened was a blank screen popped up on my desktop and nothing more.

Launched injector with: "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe"
Creating process: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe 
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x671274d0
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x671274d0
Injected dlls succesfully

**Comment by LibreVR** [comment]
I'd like to see an injector log after you try starting a game from the Revive dashboard.

**Comment by AlanRoberts91** [comment]
I tried playing Henry and Lucky's Tale from the Revive dashboard 0.8.5, 0.7, and 0.6.2 versions.
I couldn't get 0.8 to download. There was just a page not found error for it.

Revive 0.8.5
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found application oculus-henry
Found application oculus-oculus-video
Found application playful-luckys-tale
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()

Launched injector with: "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe"
Creating process: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe 
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x671274d0
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x671274d0
Injected dlls succesfully

Revive 0.7
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found application oculus-henry
Found application oculus-oculus-video
Found application playful-luckys-tale
Adding manifest: oculus-oculus-video
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Adding manifest: playful-luckys-tale
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Adding manifest: oculus-henry
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()

Launched injector with: "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe"
Creating process: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe 
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x671274d0
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x671274d0
Injected dlls succesfully


Revive 0.6.2
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found application oculus-henry
Found application oculus-oculus-video
Found application playful-luckys-tale
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()

Launched injector with: "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe"
Creating process: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\Dreamdeck-Win64-Shipping.exe 
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\openvr_api.dll
LoadLibrary found at address: 0x671274d0
Injecting DLL: C:\Program Files\Oculus\Support\oculus-dreamdeck-nux\Dreamdeck\Binaries\Win64\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x671274d0
Injected dlls succesfully

**Comment by LibreVR** [comment]
Something is clearly wrong, the injector log stays the same, which means SteamVR didn't start the injector at all.

Please send the contents of `C:\Program Files\Revive\revive.vrmanifest`. Also let me know which operating system you are using.

**Comment by AlanRoberts91** [comment]
Sorry for the delay (traveled over the weekend)
I am running windows 10 with the most current update installed.

Here is what is in the revive.vrmanifest file:
{
    "applications": [
        {
            "app_key": "revive.dashboard.overlay",
            "arguments": "",
            "binary_path_windows": "ReviveOverlay.exe",
            "image_path": "revive.png",
            "is_dashboard_overlay": true,
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "description": "Revive Dashboard overlay",
                    "name": "Revive Dashboard"
                }
            }
        },
        {
            "app_key": "revive.app.oculus-henry",
            "arguments": "/base \"Software/Software/oculus-henry/Henry/Binaries/Win64/Henry-Win64-Shipping.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/oculus-henry_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Henry"
                }
            }
        },
        {
            "app_key": "revive.app.oculus-oculus-video",
            "arguments": "/base \"Software/Software/oculus-oculus-video/Cinema.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/oculus-oculus-video_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Oculus Video"
                }
            }
        },
        {
            "app_key": "revive.app.playful-luckys-tale",
            "arguments": "/base \"Software/Software/playful-luckys-tale/LT.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/playful-luckys-tale_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Lucky’s Tale"
                }
            }
        }
    ]
}

**Comment by LibreVR** [comment]
Please try the latest version, it fixes a crucial bug that may affect you.

**Comment by AlanRoberts91** [comment]
This did help somewhat. I am still getting missing shortcut link within the Steam Overlay, but I am able to manually place the shipping file in the injector and get it working.

Here is the Overlay log:
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json.mini
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found application oculus-henry
Found application oculus-oculus-video
Found application playful-luckys-tale
Adding manifest: oculus-oculus-video
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Adding manifest: oculus-henry
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Adding manifest: playful-luckys-tale
Saved manifest to: C:\Program Files\Revive\revive.vrmanifest
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: playful-luckys-tale
Failed to launch application: revive.app.playful-luckys-tale ()
Launching application: oculus-oculus-video
Failed to launch application: revive.app.oculus-oculus-video ()
Launching application: oculus-henry
Failed to launch application: revive.app.oculus-henry ()


Here is the Injector log:
Launched injector with: "C:\Program Files\Oculus\Software\Software\playful-luckys-tale\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Software\Software\playful-luckys-tale\LT.exe"
Creating process: C:\Program Files\Oculus\Software\Software\playful-luckys-tale\LT.exe 
Injecting DLL: C:\Program Files\Oculus\Software\Software\playful-luckys-tale\x64\openvr_api.dll
LoadLibrary found at address: 0xfa5b74d0
Injecting DLL: C:\Program Files\Oculus\Software\Software\playful-luckys-tale\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xfa5b74d0
Injected dlls succesfully

**Comment by LibreVR** [comment]
Try starting Steam as admin.

**Comment by AlanRoberts91** [comment]
That completely fixed it! Thanks a bunch. I am many other appreciate the hard work that is making ReVive possible.
