### ISSUE TITLE
Elite: Dangerous

### ISSUE THREAD

**Issue by Shadaez** [LibreVR/Revive#204]
Can we get it working? I know, it has Vive support, but it's currently known as rendering at a lower quality than it should be in SteamVR. It's hard to get proof of this and if it manages to render correctly through the Oculus version with Revive, it'll help put it to rest or prove that there's an issue. The devs currently just seem to think Vive users are crazy.

**Comment by LibreVR** [comment]
I can already tell you it'd be exactly the same. The problem is that the larger field-of-view of the Vive exaggerates an issue they have with UI text rendering. I've pointed out the issue to them, though I'm not sure if they fixed it yet. I'll do another test soon.

**Comment by volley6870** [comment]
you should try to increase your supersample it makes a world of difference

http://www.roadtovr.com/how-to-improve-your-htc-vive-image-quality-with-supersampling-pixel-density-tweak/

**Comment by liuste** [comment]
I am new. I was wondering if this means elite dangerous from oculus won't work with revive? I have a copy of the oculus version of Elite Dangerous: Commander Deluxe Edition but can't seem to get it to work with vive. I read under compatibility that elite dangerous was not listed but under chronos it says: Like some other games (e.g. Elite Dangerous), you must disable Nvidia Surround or Nvidia driver will crash and reboot the PC. So does that mean elite dangerous does run in Revive?

**Comment by Shadaez** [comment]
You can sign into the Frontier website and get a Steam key for your copy
