### ISSUE TITLE
Left Ctrl doesnt recenter view

### ISSUE THREAD

**Issue by taikila** [LibreVR/Revive#207]
Hi, i am using dirt rally with the revive injector. The game is launching in VR but left CTRL doesn't recenter the view. I have a g27 wheel and using a corsair RGB keyboard (azerty cause i'm in france). All the other keyboard input works perfectly. When i try to assign left ctrl to another function, it doesn't respond. If i use right Ctrl, it responds. It's like all the keys work fine except for that damn left CTRL which prevent me to play.

**Comment by LibreVR** [comment]
Revive has nothing to do with how the game decides to trigger a re-center. You should submit a support ticket to Codemasters instead.

Alternatively you can use your Vive controller to recenter the view by keeping the system button pressed (the power button) and selecting "Recenter seated position" from the menu that pops up.

**Comment by taikila** [comment]
I switched from azerty to qwerty and problem solved. Thanks a

**Comment by LibreVR** [comment]
Good to hear you solved it. Like I said, that's all up to the game itself.
