### ISSUE TITLE
SteamVR not run

### ISSUE THREAD

**Issue by lahesis333** [LibreVR/Revive#208]
I created a new topic, because I do not understand how you can run the game through the injector if Revive does not work initially. Excuse me if that is broken again!
Please tell me how to run through stimVR Riftkat? Riftkat I run on a computer and phone (there is a connection device for wi-fi or usb). Then I run through Steam StimVR. But StimVR I have written in red "NOT READY" error and "Glasses are not connected." It does not start automatically Revive. A hand pops up an error when trying to run Revive. 
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	ReviveOverlay.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	577eb9ae
  Имя модуля с ошибкой:	ReviveOverlay.exe
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	577eb9ae
  Код исключения:	c0000005
  Смещение исключения:	0000000000003e16
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	12c1
  Дополнительные сведения 2:	12c19d85a052d80534f81399835b81ea
  Дополнительные сведения 3:	e476
  Дополнительные сведения 4:	e4761c1b7836deeab8e91a64387a8755

Ознакомьтесь с заявлением о конфиденциальности в Интернете:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

Если заявление о конфиденциальности в Интернете недоступно, ознакомьтесь с его локальным вариантом:
  C:\Windows\system32\ru-RU\erofflps.txt

I installed Vindovs 7 SP1.

**Comment by LibreVR** [comment]
This issue is a duplicate of #156.
