### ISSUE TITLE
P.O.L.L.E.N right eye funky colors display problem

### ISSUE THREAD

**Issue by CoolSpy** [LibreVR/Revive#21]
While using Revive, the game plays fine at first in the first sequence (interior in space shuttle). Then as soon as you can walk on the planet, the right eye has a weird display bug which makes the game unplayable.
![pollen](https://cloud.githubusercontent.com/assets/18576554/14677781/64400900-0713-11e6-8d94-aa98c43f5460.jpg)

**Comment by vraddict** [comment]
Tried this today and your right , Works great to start then the display go`s weird once you step outside... hope for a fix soon !!!

**Comment by vraddict** [comment]
just read the games getting vive support in the next update, so maybe best to wait .

**Comment by LibreVR** [comment]
While it would be interesting to take a look at it, I do want to focus on games that are purely Oculus-exclusives. If the developers announce OpenVR support, that lowers the priority for fixing it significantly.

Ofcourse, I still want Revive to be perfectly compatible, so I will probably get around to fixing it sometime.

**Comment by gormanj** [comment]
POLLEN 1.0.1 Update does not fix the problem.

**Comment by Armada651** [comment]
A week before the anniversary of this issue the developer has added Vive support: http://store.steampowered.com/app/393750/
