### ISSUE TITLE
HTC Vive with the Climb

### ISSUE THREAD

**Issue by ovrl00k** [LibreVR/Revive#210]
I can launch the game through my HTC Revive through the HMD.  However, the game does not go into the HMD.  I can hear the sound coming out for the game, but I do not get a picture.  Can someone help me on getting The Climb to work?  Thanks!

**Comment by Gogywan** [comment]
Won't help but I've got the same issue here.

**Comment by Gogywan** [comment]
Well, try to disable supersamling. It worked for me

**Comment by LibreVR** [comment]
I just tested it, The Climb works fine for me. Sounds like you may be running an old version, try updating.

**Comment by ovrl00k** [comment]
I was missing steamvr.vrsettings inside my Steam/config directory.  After I added it, The Climb now launches into my HMD.  Thanks everyone for the assistance.
