### ISSUE TITLE
Flickering, slow performance and computer black screen

### ISSUE THREAD

**Issue by threespoons** [LibreVR/Revive#211]
When running anything from the Oculus store through Revive either have very low performance which leads to a computer black screen which can only be saved by restarting the computer or a flicker with games such as Henry.
Normal Vr games through Steam function fine and the preview screen on my computer seems to be ok for Henry. But Dreamdeck completely crashes every time and also runs very slow in the preview on my pc screen.

Issue is the same whether using Revive overlay in Steam VR or the injector.

**Comment by threespoons** [comment]
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/moshe-ben-zacharia-the-body-vr-rift_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-lost_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/penrose-the-rose-and-i_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/starship-uk-ltd-vtime-rift_assets.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/epic-games-showdown.json
Found assets bundle felix-and-paul-studios-introduction-to-virtual-reality_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json
Found assets bundle moshe-ben-zacharia-the-body-vr-rift_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/moshe-ben-zacharia-the-body-vr-rift.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-henry_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Found assets bundle oculus-lost_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-lost.json
Found assets bundle penrose-the-rose-and-i_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/penrose-the-rose-and-i.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found assets bundle starship-uk-ltd-vtime-rift_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/starship-uk-ltd-vtime-rift.json
Found application epic-games-showdown
Found application felix-and-paul-studios-introduction-to-virtual-reality
Found application moshe-ben-zacharia-the-body-vr-rift
Found application oculus-dreamdeck
Found application oculus-henry
Found application playful-luckys-tale
Found application starship-uk-ltd-vtime-rift

**Comment by threespoons** [comment]
Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/Software/starship-uk-ltd-vtime-rift/vTime.exe"
Creating process: C:\Program Files\Oculus\Software\Software\starship-uk-ltd-vtime-rift\vTime.exe 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x271674d0
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x271674d0
Injected dlls successfully

**Comment by threespoons** [comment]
{
    "applications": [
        {
            "app_key": "revive.dashboard.overlay",
            "arguments": "",
            "binary_path_windows": "ReviveOverlay.exe",
            "image_path": "revive.png",
            "is_dashboard_overlay": true,
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "description": "Revive Dashboard overlay",
                    "name": "Revive Dashboard"
                }
            }
        },
        {
            "app_key": "revive.app.felix-and-paul-studios-introduction-to-virtual-reality",
            "arguments": "/base \"Software/Software/felix-and-paul-studios-introduction-to-virtual-reality/itvr2.exe\" -vrmode oculus",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/felix-and-paul-studios-introduction-to-virtual-reality_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Introduction to Virtual Reality"
                }
            }
        },
        {
            "app_key": "revive.app.oculus-henry",
            "arguments": "/base \"Software/Software/oculus-henry/Henry/Binaries/Win64/Henry-Win64-Shipping.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/oculus-henry_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Henry"
                }
            }
        },
        {
            "app_key": "revive.app.playful-luckys-tale",
            "arguments": "/base \"Software/Software/playful-luckys-tale/LT.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/playful-luckys-tale_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Lucky’s Tale"
                }
            }
        },
        {
            "app_key": "revive.app.starship-uk-ltd-vtime-rift",
            "arguments": "/base \"Software/Software/starship-uk-ltd-vtime-rift/vTime.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/starship-uk-ltd-vtime-rift_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "vTime"
                }
            }
        },
        {
            "app_key": "revive.app.oculus-dreamdeck",
            "arguments": "/base \"Software/Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe\" -vr",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/oculus-dreamdeck_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Oculus Dreamdeck"
                }
            }
        },
        {
            "app_key": "revive.app.epic-games-showdown",
            "arguments": "/base \"Software/Software/epic-games-showdown/Showdown/Engine/Binaries/Win64/UE4Game-Win64-Shipping.exe\" ..\\..\\..\\ShowdownVRDemo\\ShowdownVRDemo.uproject",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/epic-games-showdown_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "Showdown"
                }
            }
        },
        {
            "app_key": "revive.app.moshe-ben-zacharia-the-body-vr-rift",
            "arguments": "/base \"Software/Software/moshe-ben-zacharia-the-body-vr-rift/TheBodyVR.exe\"",
            "binary_path_windows": "Revive/ReviveInjector_x64.exe",
            "image_path": "C:/Program Files/Oculus/Software/Software/StoreAssets/moshe-ben-zacharia-the-body-vr-rift_assets/cover_landscape_image.jpg",
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "name": "The Body VR"
                }
            }
        }
    ]
}

**Comment by LibreVR** [comment]
What are your system specs? Also, make sure you are not running any in-game overlays.

**Comment by Armada651** [comment]
No reply for months, feel free to leave a comment here if you want to reopen the issue.
