### ISSUE TITLE
Dirt Rally not launching on Headset (launches on main screen)

### ISSUE THREAD

**Issue by rofltron** [LibreVR/Revive#212]
Hello 

I have the steam version of Dirt Rally. I followed the '**Steam games**' instructions - 
Downloaded the 0.8.5 injector .zip file, unzipped to xx\steamapps\common\DiRT Rally directory.

When i drag the drt.exe file over either of the injector exe's, the game launches on the main screen, but not the Vive headset. (SteamVR is running while i do this)

Headset updated to latest firmware as of today, 24/07/2016
I have unticked 'Use desktop Game Theatre while SteamVR is active'

Can you help?

Windows 10
Nvidia 980 @ 368.81 driver
Running non-beta SteamVR

Thanks

**Comment by LibreVR** [comment]
Always use the latest version, in this case [version 0.8.6](https://github.com/LibreVR/Revive/releases/tag/0.8.6). It fixes a crash that was affecting a lot of people.

**Comment by rofltron** [comment]
Thanks for getting back to me. I'll try this and let you know how it goes.

**Comment by rofltron** [comment]
Hello,

Unfortunately, still not working after updating to 0.8.6 Are there any logs i can show you? 

The game still launches on the main screen - Vive display just sits on the home screen

Do i need to install the Oculus software? I read that i don't, but would it be worth trying?

**Comment by rofltron** [comment]
I'm an idiot. For some reason i thought i didn't need the Oculus Software.

Installed that and now all ok. 

Sorry for wasting your time - and thanks :)
