### ISSUE TITLE
dirt rally flickering back to vive standard background

### ISSUE THREAD

**Issue by dom334** [LibreVR/Revive#213]
the game boots fine with latest injector and your dirt patch files but every min or less the screen flickers back to vive standard background ie the blue 1 with moon then back it only lasts a second or so but can be really annoying if you are takeing a corner just as you lose screen for that split second
on your older files dirt rally wont even boot in vr mode
ive checked things on my side ie latest firmware on everything and beta and non beta for steam vr
it only happens in this game others are fine

**Comment by LibreVR** [comment]
This is a symptom of the game freezing for more than 10 frames or so.

What are your system specs?

**Comment by dom334** [comment]
system specs are intel i7 6700k,corsair 16 gb 3000 ddr4 mem,asus maximus v111 hero mobo and a sapphire 290x 8 gb

**Comment by LibreVR** [comment]
Have you tried testing with the Ultra Low graphical setting?

**Comment by dom334** [comment]
yes ive tried ultra low runs smooth in vr no stuttering just the annoying flick back to background
oh and running windows 10 64bit

**Comment by LibreVR** [comment]
Hmmm that's strange, can you go to SteamVR Settings > Performance and click the 'Display frame timing' button? Then when you see the flick to the background quickly make a screenshot of the window.

**Comment by dom334** [comment]
tried my best looks like on frame timing its the blank part on both cpu and gpu
![stutter](https://cloud.githubusercontent.com/assets/20726780/17254072/26a320f0-55ab-11e6-95a0-f10b7ce73984.jpg)

**Comment by LibreVR** [comment]
I'm sorry, but I can't read it like that.

But it sounds like a performance problem, so you'll have to wait until I make some optimizations to Revive.
