### ISSUE TITLE
Duke Nukem 3D VR

### ISSUE THREAD

**Issue by Dukaholic1985** [LibreVR/Revive#215]
Hey Libre VR,

I have a Problem with Duke Nukem 3D in VR. There is a VR Version for the Oculus CV1 right here: http://www.malcolm-s.net/dukevr/#download
I downloaded the newest Version 2.13 and tried it with the Revive Injector. Everything works fine, until you get into the Game. Then the HUD and the weapon model is upside down means that the weapon and the HUD is at the TOP of the screen not on the Bottom. If you now press the Escape Button you see that the Menu now is upside down as well, but only from the point on you go into the actual game. The performance itself is great, but that upside down effect is very disturbing. 

I played an older Version of this a year ago on the DK2 (that i borrowed at the time) and it all worked like a charm. Can you please give me any clues where the error hides?

I would be so grateful because I love Duke 3D and playing it with the Vive would be so awesome :)

**Comment by cughin** [comment]
didnt even know this existed in vr, gave it a try and have the same problem

**Comment by LibreVR** [comment]
Fixed in commit 7d7de2c9a5406d60830531232fb513c747870a9e.

Will be part of the next release.
