### ISSUE TITLE
Subnautica, no luck at all

### ISSUE THREAD

**Issue by Raging-Beard** [LibreVR/Revive#216]
In Steam have the beta set to experimental, then with SteamVR running I drag ht exe on to the x64 injector (tried x86 too) and in the HMD the dashboard comes up a second then goes, and the game just runs on my monitor. In the HMD the usual Steam background remains.

Tried the patch, it loads but the menu is too close so you can't do anything, but can tell head tracking is working.

Any ideas please? Thanks.

**Comment by LordSyd** [comment]
Same here, with the near menu issue.

Going to try some ideas, maybe something works. Anyone else had the bug and fixed it?

**Comment by Raging-Beard** [comment]
The near menu thing only happens with the patch. From what I have read we should be using the injector, but as I described, that just does not work at all for me!

**Comment by LordSyd** [comment]
Yeah, again, same here.... as I said, will play around some more, without the patch, to see if I get it running somehow. I'll keep you posted.

**Comment by Raging-Beard** [comment]
No idea sorry!

**Comment by MarisAraneth** [comment]
This is exactly the same thing happening to me. Please if anyone can fix I really want to check this game out in VR.

**Comment by LordSyd** [comment]
Don't know what I did, but I got it running!

I opted into steam and steam vr beta client, plus opted out of subnautica experimental build.
Used revive injector + patch files: game loads without  problem, saving also works. It goes contrary do everything that was said to get subnautic running, but I am not complaining ;)

Maybe try some of the steps I took, see if that fixes it!

**Comment by yohaskan** [comment]
LordSyd do you ahve the last udpdate

I can't launch Subnautica experimental in VR now

**Comment by LordSyd** [comment]
Don't know if I unterstand you correctly. But Subnautica updated today - mini-update, around 14 mb.

Maybe they changed something?
But, as I said, I use the normal version, not the experimental build, works like a charm so far.

**Comment by MarisAraneth** [comment]
Did the steps LordSyd said, worked perfect. I did notice though and not sure if this is a known issue, when I get in the seamoth the PoV seems too far back.

**Comment by yohaskan** [comment]
ah! ok not experimental.
I'll try later

**Comment by LordSyd** [comment]
@MarisAraneth Mabe try resetting seted position - take the vive controller, hold menu button for a few seconds, then click on reset seated position.

Used it at the beginning in the menu because my viewpiont was turned 90° to the right, maybe because of that I did not get the issue?

**Comment by Raging-Beard** [comment]
Thank you LordSyd it worked :)

Couldn't read a thing on PDA until put SS up to 1.5 and still runs smooth. The pop in is somewhat ridiculous but I suppose it is work in progress and that's what you buy in to so fair enough.
