### ISSUE TITLE
Subnautica works without Oculus home ative?

### ISSUE THREAD

**Issue by LordSyd** [LibreVR/Revive#218]
Just noticed today that I have been playing Subnautica without starting Oculus home first.

Works without a problem. Is that intended/normal or interesting information, that should be added to the wiki?

Just throwing the question out there ;)

Have a nice day,
Lord Syd

**Comment by LibreVR** [comment]
Oculus Home does not need to be active, for games that use the Oculus DRM the Oculus Service is already running in the background.

For games like Subnautica which don't use any DRM you only need the Oculus Home files installed to pass an integrity check.
