### ISSUE TITLE
Oculus360Photos(1.28.0.258925) failed to start (CAPI Error: -3001)

### ISSUE THREAD

**Issue by yangjiudan** [LibreVR/Revive#219]
when I start Oculus360Photos by revive, it pop a dialog said(CAPI Error: -3001).
but when I start Oculus360Photos(1.22.0.241278), it works fine.
how to fix this?

**Comment by LibreVR** [comment]
Error -3001 means the Revive DLLs are missing. Did you use the Revive Dashboard or did you use the ReviveInjector?

**Comment by ZyonPlay** [comment]
im also getting the error:-3001. After using the ReviveInjector_x64, it says -3005 instead of -3001

**Comment by yangjiudan** [comment]
I use ReviveInjector directly.
but it works fine with old version of Oculs360Photos.

**Comment by LibreVR** [comment]
This will be fixed in the next version that will be released soon.

**Comment by LibreVR** [comment]
Closing this issue, since it is already fixed in the source code, just waiting on a new release.
