### ISSUE TITLE
Skipping animations

### ISSUE THREAD

**Issue by MarisAraneth** [LibreVR/Revive#221]
Whenever I start an animation, like opening a bulkhead, or getting in the seamoth from the moonpool one of two things happen. With the doors it seems to just skip the animation. The seamoth however will leave me walking on the ocean floor like I am in a seabase. To clarify though that is docking with the moonpool while in the seamoth.

**Comment by LibreVR** [comment]
What makes you think this is the issue tracker for Subnautica?! Please report gameplay issues to the actual developers.
