### ISSUE TITLE
Trojan: Win32/Varpes.M!cl

### ISSUE THREAD

**Issue by solidus311** [LibreVR/Revive#222]
![revivevirus](https://cloud.githubusercontent.com/assets/20877786/17458306/f722e64a-5bda-11e6-9e4f-8b2b108638ff.png)

I keep getting virus warnings with that trojan name everything I launch the injector.exe.

**Comment by LibreVR** [comment]
Make sure you've downloaded Revive from the links in this repository. If you did and you're still getting a warning, make an exception for Revive as it is almost certainly a false positive.
