### ISSUE TITLE
Help with installation!

### ISSUE THREAD

**Issue by hg1802** [LibreVR/Revive#223]
Hi All,

I just bought a HTC Vive, and while I enjoy its exclusive title I want to also check out Oculus titles.
I installed Oculus hole and created an account. I downloaded Revive installed and installed it.
After installation when I launch Revive Dashboard nothing happens.
Can someone kindly explain how to make it work? Please provide simple steps and as much detail as you can.
Please use an example of installing your favorite Oculus game.

I really appreciate that.

**Comment by LibreVR** [comment]
Put your headset on, the dashboard is a VR application that is part of your VR dashboard.
