### ISSUE TITLE
Hideous Flickering, Weird position in Dreamdeck (pic attached)

### ISSUE THREAD

**Issue by supermanscottbristol** [LibreVR/Revive#226]
i7-4770, 16gb, 1080 Amp Extreme

So I had to reinstall my VR box as the Windows anniversary update broke it.
Installed the latest SteamVR Beta, Oculus Home, and Revive 0.8.6

-- edit, now it's just Dreamdeck flickering extremely badly to the point where you can't use it.

When you start Oculus Dreamdeck you seem to be about 10 feet down into the ground from the video menu.  They're way WAY up high above you.  Picture attached. 
Also, the SteamVR dashboard doesn't disappear, Dreamdeck appears behind it.  You can then get rid of the Steam dash the normal way.

Before, the revive tab would always be there in SteamVR, now I have to manually start it every time.

All this stuff worked before.  On a fresh install of Windows this suggests it's either the latest version of Revive, latest Nvidia drivers or latest SteamVR.

Everything in SteamVR works fine, it's only Oculus programs I'm having an issue with.

-- edit -- just tried 0.8.5 and it's the same
-- edit -- tried downgrading the Nvidia drivers, no difference

![dreamdeck](https://cloud.githubusercontent.com/assets/3978083/17555550/d71104ec-5f07-11e6-8229-a2352b22d44e.png)

**Comment by supermanscottbristol** [comment]
Interestingly, in Farlands, if I set the graphics to high I get the same killer flickering.

**Comment by LibreVR** [comment]
Have you tried doing the Room Setup again in SteamVR? If you're still in the floor, try keeping the system button pressed on the Vive controller and select "Reset seated position".

If you're stilling having problems I recommend doing a clean install of SteamVR.

**Comment by supermanscottbristol** [comment]
Yeh tried resetting my seated position. The whole lot was a clean install but I'll try reinstalling steamvr again then just in case.

**Comment by LibreVR** [comment]
Also, try some older versions of Revive like Revive 0.8.

**Comment by supermanscottbristol** [comment]
Oh ok. 8.5 worked fine before the rebuild so I simply went for that but yeh I'll give that a whirl too.

**Comment by LibreVR** [comment]
There's also a version 0.8.6 you could try, but that only fixes a potential crash.

**Comment by supermanscottbristol** [comment]
That's what I started with on my rebuild then went back to 085 when I hit problems.

**Comment by supermanscottbristol** [comment]
Did all that and I'm back to having the menu in the right place, however it's still incredibly flickery.
I've put on the frame monitor and there's shed loads of missing frames in Dreamdeck, but not other Oculus titles.  
I'll start investigating hardware when I'm back from my trip on Monday in case it's that.
