### ISSUE TITLE
Crazy flickering in Chronos

### ISSUE THREAD

**Issue by niklasalkin** [LibreVR/Revive#227]
In menus, in game, wherever, I get get a crazy blinking going to black and back. It helps for a short while when I change any of the three in game settings a step or two. But when I change scene ("room" or whatever you want to call it) one or two times the blink is back. If I then change the setting BACK to where it was? Same result; good for a scene or two.

What's that about? Used a GTX 970 and yesterday I got my new 1080, same thing with both cards.

Oh also: Lucky's Tale and Farlands works without any similar issues (or any at all actually)

**Comment by LibreVR** [comment]
This is a performance problem due to the way Revive interacts with OpenVR right now. I will make optimizations to fix this before version 1.0.

**Comment by niklasalkin** [comment]
Ah, nice. Good knowing it's not on my end. Looking forward to the 1.0 release!
