### ISSUE TITLE
No way to use Revive with a Win10 App

### ISSUE THREAD

**Issue by EnolCook** [LibreVR/Revive#230]
Minecraft Windows 10 Edition has just been updated with a VR update.
As the game is not directly launched by an EXE, we can't use Revive to play.
Maybe a launcher/Revive version that inject into Win10 App or something may resolve the problem.

**Comment by EnolCook** [comment]
The Oculus Store version appears in the Revive Dashboard.
The game launch, we can see a 360 low rez image of Minecraft during 5-10 secs and the game crash.

**Comment by jimx78** [comment]
I also have the problem, I am here to encourage you to try to make it consistent play. a big thank you to you!

**Comment by LibreVR** [comment]
> The game launch, we can see a 360 low rez image of Minecraft during 5-10 secs and the game crash.

This seems like a general issue with Minecraft on the Oculus Store right now:

https://www.reddit.com/r/oculus/comments/4xyqk3/cannot_launch_minecraft_in_oculus_home/

**Comment by jimx78** [comment]
Sure we find the solution and Mojang knows. it is a language file problem. ￼

https://m.reddit.com/r/oculus/comments/4y06bb/solution_for_minecraft_vr_launch_problems/

mojang_tommo • 13h
"Great find, it's indeed a pretty stupid bug, but really hard to spot when everyone in the team is on en_US :)
We're rolling out a fix right now, it should arrive today or tomorrow."

if after updating, the bug persists, I want you to run

thank you

**Comment by jimx78** [comment]
(Google translate)
FR pour la dernière phrase:
Je vous tiens au courant

**Comment by jimx78** [comment]
Hello,
There was an update today from Mojang that corrects the problem on Rift CV1.
I uninstall minecraft minecraft on W10 and oculus and redemarer PC.
I reinstall everything but I have the same problem.

Once minecraft start, there's a blur in minecraft skybox with nothing. (This is the menu)
10 seconds later, crash the game. (This game has stopped working)
It can be a DRM?

**Comment by jimx78** [comment]
ha ok ! "Minecraft VR	Injouable	Crashes peu après montrant l'environnement à 360 degrés	Gratuit"

**Comment by brhacking** [comment]
I also still have the same problem. I am in EN_US and the behavior is exactly as jimx78 stated above.

**Comment by LibreVR** [comment]
It looks like both the Windows Store and the Oculus Store version use the UWP platform. I will have to update the injector to be compatible with UWP apps.

**Comment by LibreVR** [comment]
Ok, I got the injector working, I have a prototype that can inject into UWP apps.

Unfortunately UWP is heavily sandboxed and I can't seem to initialize OpenVR due to the error `VRInitError_Init_PathRegistryNotFound`. That likely means OpenVR uses registry functions that are not allowed by UWP.

**Comment by jimx78** [comment]
thank you for the work you do does not hesitate to say or you is, it's interesting. After oculus and Microsoft are partners, so it done expret?

**Comment by LibreVR** [comment]
Some progress, OpenVR doesn't actually use the registry it is just looking for `openvrpaths.vrpath` in the wrong location. After copying that file to the expected location I am now faced with the error `VRInitError_IPC_ServerInitFailed`.

Looks like it uses some restricted functions for inter-process communication.

@jimx78 I can't understand what you're saying.

**Comment by jimx78** [comment]
sorry I'm French and I use Google translation. I will try to make an effort. summary of my earlier message: thank you that's interesting

**Comment by swimsalot123** [comment]
Wait I'm confused... Does this mean that you are working on it and that is should be fixed soon?

**Comment by LibreVR** [comment]
@swimsalot123 I am working on it, but I am faced with problems that are outside of my control. I've reported the issue on the OpenVR issue tracker, hopefully it will be resolved soon.

**Comment by brhacking** [comment]
@LibreVR Thanks for working on it.  Maybe someday it will be possible.

**Comment by jimx78** [comment]
It is not easy what you makes. Good luck

https://github.com/ValveSoftware/openvr/issues/238

**Comment by LibreVR** [comment]
Removing the milestone, as it is extremely difficult to solve this issue without UWP support in OpenVR.

**Comment by ytdlder** [comment]
Any info @OpenVR regarding UWP injection?

Would just love to play Minecraft in VR; how does Oculus do it?

**Comment by Armada651** [comment]
@ytdlder No change, Oculus SDK is still the only VR SDK with UWP support. But from what I hear, most people prefer Vivecraft anyway.

**Comment by ytdlder** [comment]
Holy cow, first off, thanks for the ultra fast reply and secondly: thanks for this awesome tip!! I'll look into it ASAP! :-)
Thanks and keep up your great work!
Cheers!

**Comment by t3hero** [comment]
@CrossVR The latest Minecraft Win10 Beta just updated their render engine to something called "Render Dragon", including moving their VR under OpenXR. It might be worth looking at this again. 

Patch Notes:
https://feedback.minecraft.net/hc/en-us/articles/360048673272-Minecraft-Beta-1-16-100-54-Xbox-One-Windows-10-Android-

How to join Beta:
https://help.minecraft.net/hc/en-us/articles/360040841471-How-to-Join-and-leave-a-Minecraft-Beta

**Comment by CrossVR** [comment]
If an application supports OpenXR then there is no need for Revive.

**Comment by xperia64** [comment]
I've joined the MC beta, and beyond the word "OpenXR", I see no strings indicating OpenXR in the exe. Still has all the Oculus strings in it though.


Regarding the original issue, SteamVR prompted me to set up support for containers (e.g. Chrome and UWP), and they seem to be shipping OpenXR UWP support in stable now.

Did this deleted user ever post their injection method? https://github.com/LibreVR/Revive/issues/230#issuecomment-240731338
Could Revive running in OpenXR-backend mode possibly work now inside UWP containers if injected correctly?

**Comment by Iamgoofball** [comment]
@CrossVR No, there's definitely still issues. Following the instruction methods of doing "minecraft://mode/?OpenXR=true", the game pushes to SteamVR for a short few seconds, then immediately crashes. SteamVR picks it up as Minecraft Windows then dies.

I suspect Oculus/Microsoft did something to explicitly block SteamVR.

**Comment by CrossVR** [comment]
SteamVR is not yet a confomant runtime. I don't think there's any foul play involved, just early days.

**Comment by Iamgoofball** [comment]
Darn, that's a shame.
