### ISSUE TITLE
CtrlAltStudio - Second Life Viewer

### ISSUE THREAD

**Issue by holyphyre** [LibreVR/Revive#231]
Has anyone been able to get CtrlAltStudio working? I have heard reports of people having used the new oculus CV1 compatibility with the revive to port onto the Vive headset.

**Comment by Hoshi82** [comment]
That is exactly what I want to know too. I tried revive injector, setting oculus home to support non oculus games, but I always geht the oculus library could not be initialized. Would be nice if someone could look into this and make a short tutorial what to do.
