### ISSUE TITLE
Dirt Rally No Sound With Revive. 

### ISSUE THREAD

**Issue by center311** [LibreVR/Revive#232]
I used to be able to play Dirt Rally for a month with no problem. I recently tried to play and there's no audio. I tried verifying the game files and even changing different outputs. The game's audio is there when I play the game normally without the vive. Is there anything we can do about this?

**Comment by TiE23** [comment]
Suffering from the same issue here.

**Comment by LibreVR** [comment]
After verifying my local files using Steam I was able to race in Dirt Rally without issues. Please try the following:

1. Verify you local game cache by going to Properties > Local Files in Steam
2. Make sure you are running the latest version of Revive.
3. Try opting in or out of the Steam beta.

**Comment by Raging-Beard** [comment]
I have verified files, am using latest injector, and tried both in and out of the beta, all to no avail :(

**Comment by Raging-Beard** [comment]
When I try to load with the injector, a cmd window flashes up for second, and nothing happens.

**Comment by LibreVR** [comment]
Sounds like you are using the injector incorrectly. You should extract all files and keep the directory structure intact. Don't extract just the executable and don't take the DLLs out of their respective folders.

If you are stilling running into this issue, please post your injector log from `%APPDATA%\Revive`.

**Comment by Raging-Beard** [comment]
Yes that's how I am doing it, so in the dirt rally folder I have both the x64 and x86 files, plus the x64 and x86 folders.

Launched injector with: "D:\SteamLibrary\steamapps\common\DiRT Rally\ReviveInjector_x86.exe" "D:\SteamLibrary\steamapps\common\DiRT Rally\drt.exe"
Creating process: D:\SteamLibrary\steamapps\common\DiRT Rally\drt.exe 
Injecting DLL: D:\SteamLibrary\steamapps\common\DiRT Rally\x86\openvr_api.dll
LoadLibrary found at address: 0x74494bf0
Injecting DLL: D:\SteamLibrary\steamapps\common\DiRT Rally\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x74494bf0
Injected dlls successfully

**Comment by LibreVR** [comment]
Your log looks fine, I can't think of any reason why it would crash and I can't reproduce it either.

**Comment by Raging-Beard** [comment]
:( I never could use the injector and had to use the patch you had created. It behaves exactly as it did, is there any chance another patch can be made for this later version of the game? Thanks

**Comment by Raging-Beard** [comment]
Update... Got the injector to work by setting the injector file and drt.exe to run as administrator.

However there is still no sound at all from the game.

**Comment by Raging-Beard** [comment]
FIXED...

So after the game worked with the injector as stated above, I realized I hadn't copied the original bink2w32.dll back over the one from the patch, now game loads with sound via the injector!

**Comment by LibreVR** [comment]
So the rest of these people are likely also affected by leaving an old experimental patch in their game directory. I'll be sure to remove the link to that patch.

**Comment by Raging-Beard** [comment]
Well I know a number of people could not use the injector, the solution to that was administrator mode, the old patch file was just the cause of the sound issue for me.

**Comment by LibreVR** [comment]
I've also seen people who suddenly got the sound issue, but were still on version 0.8.5 which had a bug in the audio API. Updating to 0.8.6 should solve that.
