### ISSUE TITLE
Stuttering in Chronos after Nvidia driver update (fixed by rolling back driver to previous version)

### ISSUE THREAD

**Issue by jfb4497** [LibreVR/Revive#233]
I got some seriously strange stuttering tonight while playing Chronos with Revive version 0.8.1 that wasn't matching up to any issues in terms of frame rate timing/missed frames in the Vive performance tab. I tried lowering my settings both in game and in terms of the renderTargetMultiplier in SteamVR to see if that would fix the problem. It did not.  

The only thing that fixed the stuttering was rolling back the Nvidia driver update I installed earlier today (version 372.54) to the version from July (version 368.81). That seems to have fixed the problem. I'm using a GTX 1070 for reference. I figured I'd post this so that if others run into problems they could try rolling back their driver to the earlier version.

**Comment by SRombauts** [comment]
I have the same problems with Farlands since last week driver update (also an Unreal Engine 4 game).

I didn't try to revert the driver update.

Any perf logs I could post here?

**Comment by LibreVR** [comment]
Merging all the reprojection issues into issue #251.
