### ISSUE TITLE
Minecraft VR

### ISSUE THREAD

**Issue by neuhaus** [LibreVR/Revive#234]
The game crashes shortly after showing the 360-degree environment.

**Comment by jimx78** [comment]
salut ! ajoute moi sur steam ou oculus : pseudo jimx78
on a déjà un topic
https://github.com/LibreVR/Revive/issues/230

**Comment by jimx78** [comment]
Hello,
There was an update today from Mojang that corrects the problem on Rift CV1.
I uninstall minecraft minecraft on W10 and oculus and redemarer PC.
I reinstall everything but I have the same problem.

Once minecraft start, there's a blur in minecraft skybox with nothing. (This is the menu)
10 seconds later, crash the game. (This game has stopped working)
It can be a DRM?

**Comment by iamwes** [comment]
Exactly the same for me, loads up with a blurry minecraft background then shuts down after about 10 seconds.

**Comment by LibreVR** [comment]
I'll take a look at this soon.

**Comment by LibreVR** [comment]
Duplicate of issue #230.
