### ISSUE TITLE
Luckys tale keeps crashing

### ISSUE THREAD

**Issue by pearce31** [LibreVR/Revive#237]
It will load all the way to the start screen  no problems until I start a game then it crashes everytime today. Last night I played a whole level then it crashed. I am Using installer.

**Comment by LibreVR** [comment]
Are you running the SteamVR beta? If so, an update to the SteamVR beta was release a few hours ago that fixes a crash. Try opting out of the beta to be sure it's not a beta-related issue though.

If you're still having an issue, please post the crash logs here, there should be a folder named with the date of the crash. You can zip that folder and just drop it in the comment box here to upload it to this report.

**Comment by pearce31** [comment]
[New folder (6).ZIP](https://github.com/LibreVR/Revive/files/428612/New.folder.6.ZIP)
I'm not using beta. Is this right logs? Don't know where to find others.

**Comment by pearce31** [comment]
Sorry found it.
[2016-08-20_220254.zip](https://github.com/LibreVR/Revive/files/428635/2016-08-20_220254.zip)

**Comment by LibreVR** [comment]
This is a crash in one of their C# scripts, it doesn't look like Revive is involved in the crash. You might want to try re-downloading lucky's  tale to ensure you don't have any corrupted files.

**Comment by pearce31** [comment]
OK will try thanks.

**Comment by pearce31** [comment]
Deleting everything and reinstalling fixed it.

**Comment by LibreVR** [comment]
Yeah, so it looks like you had corrupted files. That is worrisome though, you may want to run memtest86 on your PC to ensure everything's okay before you get more data corruption.
