### ISSUE TITLE
Pinball FX2 VR updated with table inapp purchases. Now it fails to verify account

### ISSUE THREAD

**Issue by bloodydrake17** [LibreVR/Revive#238]
when I launch Pinball FX2 after todays update this is what you see in the headset.
http://i.imgur.com/GL9KhJH.jpg
I've tried restarting etc. but doesn't seem to help.

**Comment by LibreVR** [comment]
Make sure Oculus Home is running and that you haven't blocked any Oculus servers.

**Comment by bloodydrake17** [comment]
it was working yesterday before update..i did make sure home was running minimized.
i tested lucky's tale started up no issue

**Comment by iwillforgetthis** [comment]
I am getting the same error.  I play Pinball FX2 almost daily through Revive, but today I am getting an error on startup.  It says not able to verify license at this time.

**Comment by noodle1009** [comment]
I was getting the same errors reported here, but I was able to uninstall/reinstall via the Oculus storefront, and it works after doing so for me.   I also did a 'Restart Oculus' after reinstalling for good measure, but I'm not sure it was needed.

While I can now get into the game, I can't buy the new table pack for sale - pressing the 'A' button will start tables I already have, and allow me to select menu options as per normal, but pressing 'A' won't proceed to the in-app purchase dialogue.

I am pretty sure that Oculus users have been able to play the new tables so far - I have a feeling Revive just can't launch whatever is launched (in Oculus Home, maybe?) in order to purchase the tables.  Which is a shame really, as I am sure Vive users would love to give this developer money, but can't.

**Comment by iwillforgetthis** [comment]
@noodle1009. This did not work for me.  I Uninstalled, installed and rebooted for good measure. Same error message.

**Comment by noodle1009** [comment]
perhaps try restarting oculus home via Oculus Home Settings > Beta > Restart Oculus...or maybe even install Revive again?  Not sure what else to suggest.  

Like I said I did get the error message that was linked earlier (unable to verify the game license at this time) but I managed to get around it.

Regardless, something strange is going on since the last update of Pinball FX2 VR (do any other Oculus titles have in-app purchases?  Do they work?)

**Comment by iwillforgetthis** [comment]
Thanks @noodle1009! Reinstalling Revive did the trick. I can see the new tables that are available to purchase, but pressing A does nothing. I believe this is the same issue you are having. 

I do not have any Oculus Home games with in app purchases so I can't test other games.  

Thanks again for the help.

**Comment by noodle1009** [comment]
so I see a lot of these in my Oculus diagnostics, which I am attaching:

`=============
LOG ANALYSIS
=============

[Service_2016-08-24_11.57.04.txt] 24/08 11:57:11.006 {!ERROR!} [Registry] Failed to read selected Oculus default language tag.
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:12.081 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(1078) : Home is not ready. (OVR60915022) (1971039)
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:12.081 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(2310) : Failed to start IAP: Internal Error: OVR60915022 (OVR77152342) (1971039)
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:12.081 {!ERROR!} [IpcRouter] Command /life_cycle/iap/start caused an error: Internal Error: OVR77152342
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:13.478 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(1078) : Home is not ready. (OVR60915022) (1971039)
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:13.478 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(2310) : Failed to start IAP: Internal Error: OVR60915022 (OVR77152342) (1971039)
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:13.478 {!ERROR!} [IpcRouter] Command /life_cycle/iap/start caused an error: Internal Error: OVR77152342
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:13.980 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(1078) : Home is not ready. (OVR60915022) (1971039)
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:13.980 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(2310) : Failed to start IAP: Internal Error: OVR60915022 (OVR77152342) (1971039)
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:13.980 {!ERROR!} [IpcRouter] Command /life_cycle/iap/start caused an error: Internal Error: OVR77152342
[Service_2016-08-24_11.57.04.txt] 24/08 11:58:14.282 {!ERROR!} [OAF ERROR] ..\..\..\LifeCycle\LifeCycleManager.cpp(1078) : Home is not ready. (OVR60915022) (1971039)`

IAP = In App Purchase?

[Oculus_Logs_20160824_071415.zip](https://github.com/LibreVR/Revive/files/435910/Oculus_Logs_20160824_071415.zip)

I think there's other relevant logs regarding trying to start Pinball FX2 VR as well in there (in the autoanalysis file in the root of the zip)

hope it helps.

**Comment by bloodydrake17** [comment]
followed the advice above and uninstalled pinballfx2 vr from oculus home, reinstalled and reinstalled revive and it launches now.

**Comment by LibreVR** [comment]
> Home is not ready. (OVR60915022) (1971039)

@noodle1009 Revive starts games outside of Oculus Home, since Oculus Home is not actually running the game it can't start the In-App Purchase. There's not much I can do about it.

**Comment by noodle1009** [comment]
that makes sense - thanks for the explanation.  Until these guys release something that works with the Vive I guess we'll have to patiently wait...

**Comment by gormanj** [comment]
I've noticed that if you run the oculus debug tool and set the Debug HMD Type to CV1 you can start up pfx2vr without revive. I believe when you do this it is starting the game inside of Oculus. However I was not able to find a way in the short time I tested it to be able to navigate to the new content. I was hoping mouse or gamepad navigation would be enough. Perhaps someone else can get further using Oculus Debug.

**Comment by noodle1009** [comment]
you're right, this method does launch :)

if we only had some way to spoof rift HMD input, I could move the HMD a millimeter to the left and enter the options menu, open it, and then the xbox controller could do the rest.  Sadly, this does not appear to be possible.

**Comment by gormanj** [comment]
Yep, Pinball FX2 VR requires looking at the options, too bad mouse/keyboard input was not an option.

**Comment by gormanj** [comment]
I notice there is an oculus injector here:
http://mushroomtomatoes.com/2016/05/oculus-home-injector-v1/
However I am guessing it is nothing more than a launcher and does not actually run a game with Oculus Home. So I think this would not help. However, if anyone knows differently, I am itching to purchase those other tables for Pinball FX2 VR.

**Comment by gormanj** [comment]
Looks like freepie could possibly accomplish emulating the rift hmd. However, the Oculus runtime would probably need to be changed for a lower version like 0.8 and we would need to find or write a script. Interestingly the Oculus debug tool makes it look like a rift is present to all software including Oculus Home, though it doesn't do anything for the missing sensor.

**Comment by gormanj** [comment]
I sent an email to zen studios and got a reply that the feedback would be pass along to the team about having keyboard navigation so anyone could purchase the DLC.

**Comment by bloodydrake17** [comment]
just an FYI Zen's community manager mentioned a Vive announcement "Soon" 
I suspect their 6months exclusive deal is ending and Zen Pinball 2 VR will hit steam soon(name game seems to be a thing :)

**Comment by noodle1009** [comment]
https://blog.zenstudios.com/?p=6572

it's about time

**Comment by Armada651** [comment]
Closing this issue now that the Vive is officially supported.
