### ISSUE TITLE
Subnautica, break again after last update of game (08/24)

### ISSUE THREAD

**Issue by yohaskan** [LibreVR/Revive#239]
VR is after-break again last update of game of (08/24) for me
and in the two modes (Experimental, and no-experimental)

Impossible to launch in VR

Given regularity of this problem, and it's certainly not linked to Revive. I think, with a paranoid touch, they don't want  to see the Vive players in their game in VR.

If anyone can confirm this problem, before close it. 
Thank's

**Comment by yohaskan** [comment]
Update: VR Works

I have done another test and it's seem not working with the Revive Injector (like before) but now works with the Revive patch (i'm on experimental mode in Steam)
https://github.com/LibreVR/Revive/releases/download/0.8.6/RevivePatch.zip

**Comment by LibreVR** [comment]
They may have added Steam DRM, which doesn't allow the injector to launch correctly. If the patch works for you than I consider this issue solved.
