### ISSUE TITLE
DG2 gives "Game data files are corrupt. Please reinstall."

### ISSUE THREAD

**Issue by jmccorm** [LibreVR/Revive#24]
First time trying the injector. Unzipped files to directory, replaced DefenseGrid2_Shipping.exe just fine. When I double click, SteamVR says "unresponsive" and on Windows, an error pops up, ""Game data files are corrupt. Please reinstall." This appears to be an error from Defense Grid 2 itself. I reinstalled the software, no effect. I switched to the main SteamVR (instead of Beta) but no effect. Recentered in SteamVR, but no effect.

**Comment by LibreVR** [comment]
This is probably related to #25, closing as duplicate.

**Comment by jmccorm** [comment]
Thanks! Stay awesome, crazy injector dude!
