### ISSUE TITLE
Seemingly Random Freezes during DiRT Rally

### ISSUE THREAD

**Issue by mpgramlich** [LibreVR/Revive#240]
ReVive Injector 0.8.6
DiRT Rally V1.22 Steam Edition

Freeze can happen anywhere after game start, during a race, replay, or garage. Sometimes I can play for an hour, other times just a few minutes.
Sound works, game cache verified.

Not sure where I can obtain a crash dump or log.

What other info can I provide that can help?

ReVive is spectacular in every other circumstance :) Keep up the great work!

**Comment by LibreVR** [comment]
Can you test it with the latest version of Revive?

**Comment by mpgramlich** [comment]
Seems to be working great now! Can play for a few hours without crashing.

**Comment by LibreVR** [comment]
Always nice when bugs like these automatically get fixed during refactors.
