### ISSUE TITLE
remove Oculus title from Steam desktop client Library

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#241]
So I bought a game from the Oculus Store, showed up automatically in my desktop Steam client, which is cool, but then I uninstalled it in the Oculus Store client, and now it still shows in the Steam Library.  How can I remove it?

if the developers are reading this :  many thanks for Revive!!

**Comment by LibreVR** [comment]
You need to uninstall Revive, then they'll be removed from your Steam Library.
