### ISSUE TITLE
eve valkyre double vision

### ISSUE THREAD

**Issue by tict4c** [LibreVR/Revive#242]
Seems like the last nvidia driver update caused some problems for eve Valkyrie. If I move my head the game gets blurry / some double vision effect once I rolled back to the previous driver everything was fine again. 
Not sure if that is a general or revive problem didn't see anything on the eve forums so I thought I drop it here

**Comment by iamwes** [comment]
Same for me, i have tried 2 drivers and its still the same now, could you tell me what driver version is running it fine if possible?

**Comment by iamwes** [comment]
Dont worry found 1 that works perfect 368.81

**Comment by tict4c** [comment]
yeah I'm using the same driver

**Comment by mapotter99** [comment]
Try this with the latest nVidia drivers, and let me know if it works...

Open the SteamVR Settings, go to Performance, and UNcheck "Allow Reprojection".

After that, ALL of my double image problems went away!

Of course, you will probably want to re-enable when playing native Steam games.

**Comment by LibreVR** [comment]
Merging all the reprojection issues into issue #251.
