### ISSUE TITLE
Revive Tab in VR shows - blue empty Window

### ISSUE THREAD

**Issue by marcob2178** [LibreVR/Revive#244]
Hi, i am having  problems with revive. I click on revive and it appears a Blue screen with nothing inside.

Where do I get the logfile to post info about my problem? I do not see any txt file in %APPDATA%\Revive.

Thanks!

**Comment by sbawden77** [comment]
What drive do you have your games installed in? I had this problem too. I fixed it by uninstalling oculus home, and reinstalling everything (games included) to the c: drive.

**Comment by marcob2178** [comment]
but what do u mean by where do I have the game installed in?

Don't I have to download the game from oculus with the htc vive ?

Can you please explain to me how does it work?

How do I download the game from oculus with vive?

**Comment by LibreVR** [comment]
Duplicate of issue #228.
