### ISSUE TITLE
problem with the newesr revive

### ISSUE THREAD

**Issue by ddropski** [LibreVR/Revive#246]
i know there is a vive version of shodown demo Its not as clear as the oculus one  ,,, but i used to be able to play the oculus version ..till the latest update 6.1  now it gives a descriptor error ,,, not sure why ..if this version is not as stable .. where can i download the older version again...also you guys are doing amazing work keep it up .. U ROCK

**Comment by ddropski** [comment]
humm no reply ? ...

**Comment by gormanj** [comment]
The Showdown build here is actually BETTER than the Oculus home version. I know because I have seen both.
https://www.reddit.com/r/oculus/comments/3jh721/request_hiquality_build_of_epics_showdown_demo/

**Comment by LibreVR** [comment]
Showdown should work as normal when started through the Revive dashboard. It does not work with the Revive Injector without the proper arguments supplied by the dashboard.
