### ISSUE TITLE
Assetto Corsa, nothing on HMD

### ISSUE THREAD

**Issue by Raging-Beard** [LibreVR/Revive#248]
Writing this on behalf of my brother. I have the same setup and all works perfectly, but for no reason known to us, for him it only displays on monitor and the HMD remains in the VIVE lobby thing when gets on track.

Patch in folder, Oculus home installed (allowed unknown & restarted), unchecked desktop theatre, selected Oculus in rendering settings.

Are we missing something that I forgot or any ideas to try please?

Many thanks.

**Comment by Balderick** [comment]
Just tested latest release revive (1.0 Preview 3) with assetto corsa and had to "force 32 bit" in in game general settings and change launcher max res, select oculus device and adjust in game res's to suit hmd.

**Comment by Armada651** [comment]
Most people seem to patch the 32-bit executable and then run the 64-bit one. So yeah, try what @Balderick said if it doesn't work.
