### ISSUE TITLE
The Climb double vision

### ISSUE THREAD

**Issue by whit0r** [LibreVR/Revive#249]
Recently purchased the climb, it appears in the revive-tab, is executable and the logos at the beginning look fine. But when the menu and the game with the pov starts, its all double vision and it seems the fov on the left eye is completely f....d. Looks like some sort of clipping error but a complete different version of the right eye.

Tried to downgrade to nvidia 368.81. Same results, every other oculus-game is running as it should. 

Extreme flickering and stuttering also in the dreamdeck-demo...with the newest nvida-drivers and also the 368.81 ones. But the left/right-eye problem only in the climb

Any ideas? Apart from that - great stuff you are making - you da man!
![climb](https://cloud.githubusercontent.com/assets/21990078/18233434/931e32a2-72e7-11e6-86b1-40afee7f436f.jpg)

**Comment by mapotter99** [comment]
This doesn't sound like the double vision problem I've been having, but you can try this solution which has resolved all my double image problems, even with the latest nVidia drivers...

Open the SteamVR Settings, go to Performance, and UNcheck "Allow Reprojection".

After that, ALL of my double image problems went away!

You'll probably want to recheck it for native SteamVR games. The function creates missing frames to keep the FPS at a comfortable level.

**Comment by whit0r** [comment]
Thanks mate, but i've read a few threads ago, someone had the same problem and disabled the precision-x overlay. that did it for me, too.

But the stutters with the new nvidia-drivers remain, i'll try your method with disabling the reprojection setting.

**Comment by LibreVR** [comment]
Merging all the reprojection issues into issue #251.
