### ISSUE TITLE
Game plays on PC monitor but not on vive

### ISSUE THREAD

**Issue by marcob2178** [LibreVR/Revive#252]
Please help! I have tried everything and I can not make revive work! I have dragged the .exe on the injection file and the story is always the same : 

Game plays on PC monitor but not on vive

:-(

Please help!

**Comment by hyperseven** [comment]
-do you have Oculus home installed?  if not install.
-are you running SteamVR beta? if so opt back out and run stock.

**Comment by marcob2178** [comment]
I have oculus home installed and I have tried with both SteamVR, beta and non beta :-(

**Comment by LibreVR** [comment]
Which game are you trying to play? Can you post your logs from `%APPDATA%\Revive`?

**Comment by marcob2178** [comment]
Dying Light

The town of light

but independently by what game I try to boot in vive, there is no msg that appears saying that the game can not be plaid in vive. The game just open on the pc with no msg whatsoever. So I am not sure if the injection is working at all.

How do I get a log ?

**Comment by LibreVR** [comment]
Just press Windows Key + R and fill in `%APPDATA%\Revive`, then press enter and it should open a folder with two log files. You can drag those log files into the comment box to upload them here and attach them to your comment.

**Comment by marcob2178** [comment]
Launched injector with: "H:\PCGames installation folder\Dying Light\ReviveInjector_x64.exe" "H:\PCGames installation folder\Dying Light\DyingLightGame.exe"
Creating process: H:\PCGames installation folder\Dying Light\DyingLightGame.exe 
Injecting DLL: H:\PCGames installation folder\Dying Light\x64\openvr_api.dll
LoadLibrary found at address: 0x69004960
Injecting DLL: H:\PCGames installation folder\Dying Light\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x69004960
Injected dlls successfully



libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/arjanm2-surge_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/zynga-inc-mountain-goat-mountain_assets.json
Found assets bundle arjanm2-surge_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/arjanm2-surge.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-farlands.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found assets bundle zynga-inc-mountain-goat-mountain_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/zynga-inc-mountain-goat-mountain.json

**Comment by marcob2178** [comment]
so strange.... it says "Injected dlls successfully" but the game does not play on my vive screen :-(

If I use vorpx, the game instead plays on my vive screen

**Comment by marcob2178** [comment]
Launched injector with: "H:\PCGames installation folder\Dying Light\ReviveInjector_x64.exe" "H:\PCGames installation folder\Dying Light\DyingLightGame.exe"
Creating process: H:\PCGames installation folder\Dying Light\DyingLightGame.exe 
Injecting DLL: H:\PCGames installation folder\Dying Light\x64\openvr_api.dll
LoadLibrary found at address: 0x69004960
Injecting DLL: H:\PCGames installation folder\Dying Light\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x69004960
Injected dlls successfully




libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/arjanm2-surge_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/zynga-inc-mountain-goat-mountain_assets.json
Found assets bundle arjanm2-surge_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/arjanm2-surge.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/oculus-farlands.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Found assets bundle zynga-inc-mountain-goat-mountain_assets
Loading application manifest: file:///C:/Program Files/Oculus/Software/Manifests/zynga-inc-mountain-goat-mountain.json

**Comment by marcob2178** [comment]
Also, I have a red msg on streamvr saying :

(Unresponsive) Revive Dashboard

**Comment by LibreVR** [comment]
Are you sure Dying Light supports the Oculus Rift CV1? I only see references to DK2 support which is not supported by Revive.

Going to close this issue, leave a comment if you're absolutely certain this is a CV1-supported title.

**Comment by duig0** [comment]
*Bump* it is now supported by cv1. Revive doesn't work with it though
