### ISSUE TITLE
Oculus Video doesnt work

### ISSUE THREAD

**Issue by Villaman68** [LibreVR/Revive#253]
I cant get Oculus Video to work, I get a small box popup on the desktop with error 3001 or 1007 every time. Oculus home is installed and other games/apps work downloaded through it, I have restarted the oculus service via the beta tab but still get the same result also get the same result if I try using the standalone injector.

**Comment by LibreVR** [comment]
I think they've switched to a newer version of the Oculus SDK. I just tried the latest development version of Revive and it does work there. This will be fixed in the next release of Revive, which should be released pretty soon.

**Comment by Villaman68** [comment]
Good to hear Libre VR look forward to the next release. Awesome work BTW.

**Comment by LibreVR** [comment]
Closing this issue, since it is already fixed in the source code, just waiting on a new release.
