### ISSUE TITLE
ABE VR

### ISSUE THREAD

**Issue by hyperseven** [LibreVR/Revive#254]
get error box:

"**Failed to open descriptor file** "../../../UE4Game-Win64-Shipping/UE4Game-Win64-Shipping.uproject'"

When either through injector drag and drop of .exe or through revive plugin.

**Comment by LibreVR** [comment]
It's missing some launch parameters that are normally added by the launcher, which Revive skips so it can directly inject into the game binary.

I've added a special case in commit a6a5d56b89e778583cbb593f74731c61e77efdda. This will be fixed in the next release.

**Comment by hyperseven** [comment]
cheers fella
