### ISSUE TITLE
PCARS Causes Windows reboot

### ISSUE THREAD

**Issue by raptorpg** [LibreVR/Revive#26]
Hi,

I tried libreVR on my machine today and everything works fine in the menus but when I try to lauch a race right after the splash screen when the render of the race itself starts I get a black screen and windows reboot to the bios.

Doesn't look like a blue screen of death.
 
I am running win 10 on a core i5 2500k and a r9 390 on the friver v16.4.1.

Luckys tale works fine.

If you need any more info please let me know.

Thanks for the hard work :).

**Comment by LibreVR** [comment]
.... I don't know if I can fix *that*. Sounds like an issue with your computer.

**Comment by raptorpg** [comment]
Do you know if there is a way to get the last call stack that goes through the open_vrapi.dll or to attach a debugger so I can try to find the issue on my side. Other wise I will just wait for the next version and retry :)

**Comment by LibreVR** [comment]
`openvr_api.dll` is closed-source, you can't step through it. It's probably more useful to compile the Revive project yourself and then launch the debugger.

**Comment by raptorpg** [comment]
I re tested with0.4 and the issue doesnt happen anymore.

Thank you very much.
