### ISSUE TITLE
can someone please tell me what in doing wrong?

### ISSUE THREAD

**Issue by ddropski** [LibreVR/Revive#260]
hi i have a vive i installed the revive injector i have blaze rush .... and sub nautica but i cant get the vive to see them ... i copied the injector into the game folder and dragged the games exe to the injector exe and the game starts but it doesnt appear on the vive just my monitor

**Comment by JediDiggler** [comment]
Did you start steam VR first before running them? Also make sure you try the 64bit launcher if you didn't.

**Comment by LibreVR** [comment]
Please use the [Revive Dashboard installer](https://github.com/LibreVR/Revive#oculus-home-games) for Oculus Store titles such as blazerush.

For subnautice, which is a Steam title you should use the [Revive Patch](https://github.com/LibreVR/Revive#steam-games) instead. Though I don't reccomend playing subnautica with Revive, there are a lot of issues with it.

Please read the instructions more carefully this time.

**Comment by ddropski** [comment]
ill try the revive patch .. also i did try both versions 32/64  and had steam VR started ... also thank you guys for the reply's :)
