### ISSUE TITLE
Feral Rites - very low resolution + some flickering

### ISSUE THREAD

**Issue by JediDiggler** [LibreVR/Revive#261]
Anyone else tried this one out? It seems to be defaulting to some very low supersampling setting, perhaps 0.5 or so, making it very blocky. Not sure if it's just my setup or not.

There's also some minor flickering somewhat similar to Edge of Nowhere with the blue magic particles, but it's nowhere near as severe as in that game.

**Comment by srt23** [comment]
Yeah, I have the same issues. The resolution is very low, and supersamling in SteamVR or Oculus Debug Tool doesn't help.

**Comment by nick-ta-mere** [comment]
I have the same issue. Steam VR Super Sampling doesn't seem to affect it.

**Comment by LibreVR** [comment]
I bought Feral Rites during the sale, so I'll be sure to test it and release a hotfix.

**Comment by LibreVR** [comment]
Okay, Feral Rites enforces a render scale of about 0.7. I haven't put a lot of attention towards the scaling quality yet with the newly introduced compositor. I will fix that in the next version.

I'll probably also add an option to ignore the render scale used by Oculus.

**Comment by srt23** [comment]
Thank you, looking forward to your next release.

**Comment by LibreVR** [comment]
Fixed in commit 4fd42f9910e3410fa1ccb8fcb0810932857ffddf.

Expect a new release around the end of the week.

**Comment by LibreVR** [comment]
New release is out, it also adds a new option that allows you to override the downsampling applied by Feral Rites.

**Comment by nick-ta-mere** [comment]
awesome, thank you!
Do you know why it happened in Feral Rights? Is the rift version also downsampled?

**Comment by ytdlder** [comment]
Sorry if this is a dumb question, but as I didn't find this info anywhere: where would this "new option" be located at?
I have "Advanced Settings" installed and it's set to 2x SuperSampling, but this game looks good awefull (alias wise), so no AA and super-low resolution...

Thanks in advance! Cheers!

**Comment by Armada651** [comment]
Try checking the box next to "Render Target Override" on the Revive page in AdvancedSettings:

![RevivePage](https://github.com/matzman666/OpenVR-AdvancedSettings/blob/master/docs/screenshots/RevivePage.png)

You don't need to move the slider, checking the box should be enough. Afterwards, restart Feral Rites.

**Comment by ytdlder** [comment]
Wow, thx for the super fast reply mate!

Anywho, I guess you have to assume the "worst", but of course the box is checked^^
Just out of curiosity I tried with a value of 1.0, but unfortunately that did nothing to remedy the problem :-(

**Comment by Armada651** [comment]
Oops, you're right, I forgot to re-implement support for that option in Revive 1.2. I'll reimplement it for the next release, but I'll only support the checkbox, not the slider.

**Comment by ytdlder** [comment]
Sweet!!
Thanks :-)
_(on a side note: any timeline on that?^^)_
