### ISSUE TITLE
Subnautica

### ISSUE THREAD

**Issue by indesan** [LibreVR/Revive#264]
since last nights update 23/9/16 the game crashes when using the Revivepatch when selecting new game or load game, the injector doesn't work at all, it boots the game up in non VR mode.
latest version of revive installed, using the latest injector and patch files

**Comment by LibreVR** [comment]
Have you tried older versions of Revive?

**Comment by Keltas** [comment]
I have the same problem. I've tried versions 0.9 and 0.8.6. They both work the same. Injector starts up steam vr but boots Subnautica into a non vr version on normal display, whereas patch starts up in vr however the game crashes on new game, or load game.
 I've attached crash logs generated by the game.
[output_log.txt](https://github.com/LibreVR/Revive/files/490657/output_log.txt)
[error.log.txt](https://github.com/LibreVR/Revive/files/490659/error.log.txt)

**Comment by indesan** [comment]
I'll do some tests on older versions and update with the results

**Comment by LibreVR** [comment]
@Keltas Are those crash logs for version 0.9 or 0.8.6?

**Comment by Keltas** [comment]
They are from 9.0 .

**Comment by LibreVR** [comment]
Fixed in commit a8e2ac01e2648a4b06fd61bbc1cf3c9bdf2cdc67.

Will be part of the next release.
