### ISSUE TITLE
Can no longer play Damaged Core with version 0.9.5

### ISSUE THREAD

**Issue by jtate5** [LibreVR/Revive#266]
I'm getting a "you have a pending hardware issue that is preventing you from entering vr" error when trying to load Damaged Core.  Works fine with 0.9.0.

**Comment by LibreVR** [comment]
Oops looks like I made a mistake in the regular expression used to detect the main executable. I will release a hotfix soon.

**Comment by LibreVR** [comment]
Done, fixed in commit cdf178eac9839df6eea6bb838a6b5474a5763d6c.
