### ISSUE TITLE
 0.9.6 and Feral Rites

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#268]
Just installed 0.9.6 and rebooted the pc : everything seems to be working, except for Feral Rites : doesn't boot anymore from the Revive loader screen.

**Comment by LibreVR** [comment]
Can you post your logs from the `%APPDATA%\Revive` folder?

**Comment by LibreVR** [comment]
Just tested it, I can run Feral Rites just fine. Since I can't reproduce it I will close this issue, but feel free to leave a comment in this issue if you are still facing the problem.

**Comment by kvdv99** [comment]
Good news :  I tried once more (after rebooting again, and I also saw that an update was installed for the game). I don't know if these things were relevant, but the game works again!
