### ISSUE TITLE
Can't find pixelsPerDisplayPixel option

### ISSUE THREAD

**Issue by srt23** [LibreVR/Revive#269]
Not sure if this is an issue, or me just not understanding it right, but I do not have the pixelsPerDisplayPixel option in my steamvr.vrsettings file. No matter how high i set the targetrendermulitplier it's the same low resolution in Feral Rites.

I only have this option:
   "revive" : {
      "PerfHudMode" : 0

**Comment by LibreVR** [comment]
You need to add it to the options yourself just like `renderTargetMultiplier`. When you want to stop using the override you can remove the option again.

**Comment by srt23** [comment]
Thank you so much for the reply. Will try that. I have been using chaperone
switcher to change the renderTargetMultiplier so didn't know you had to put
that in manually. Thank you.

29. sep. 2016 13:14 skrev "LibreVR" <notifications@github.com>:

**Comment by srt23** [comment]
Ok, so now it looks like this:
 },
   "revive" : {
      "PerfHudMode" : 0
      "pixelsPerDisplayPixel" : 1.0
   },
   "steamvr" : {
      "allowReprojection" : false,
      "background" : "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\250820\\693599154\\kaermorhen.jpg",
      "basestationPowerManagement" : true,
      "directModeEdidPid" : 43521,
      "directModeEdidVid" : 53794,
      "playAreaColor" : "#FFFFFF6A",
      "renderTargetMultiplier" : 1.8

Still no change. I also tried pixelsPerDisplayPixel set to 1.8. What am I doing wrong? Sorry to waste your time.

**Comment by LibreVR** [comment]
Umm, because you forgot the comma after `"PerfHudMode" : 0`?

**Comment by srt23** [comment]
Should have seen that. Thanks again.

**Comment by srt23** [comment]
That did the trick:)
