### ISSUE TITLE
Showdown app not working

### ISSUE THREAD

**Issue by harf4ng** [LibreVR/Revive#270]
Hi,

I have no success with the showdown oculus app, that is supposed to work. If I try to launch it through revive (the steam tab) it does nothing, or sometimes the app launches, but then I have the video on the screen and not in the headset.

If I try the injector, then I have  the video on the screen and not in the headset.

Thanks

**Comment by JediDiggler** [comment]
Run it using the injector. Don't use the first .exe you find in the app's folder, drill down to the UE4 shipping exe in one of the subfolders. You also need to add this argument to the game's executable in your shortcut;  

..\\..\\..\\ShowdownVRDemo\\ShowdownVRDemo.uproject

**Comment by mapotter99** [comment]
Showdown isn't working for me in Revive 0.96, either. Reverting to Revive 0.90 resolved this for me. I'm finding Revive 0.96 to be rather buggy right now.

**Comment by LibreVR** [comment]
Fixed in commit 86b96a835f879413848bf2c412eee41e6dbfd571.

Will release a hotfix.

@mapotter99 Buggy? Are the any other regressions besides this one?

**Comment by LibreVR** [comment]
[Hotfix released](https://github.com/LibreVR/Revive/releases/tag/0.9.7).
