### ISSUE TITLE
SNOW Does Not Work?

### ISSUE THREAD

**Issue by charlestruluck** [LibreVR/Revive#271]
The free to play Steam game SNOW won't work with Vive. It has Oculus support though. Anyone got it to work or is it not work looking at?

**Comment by LibreVR** [comment]
Please upload your log files:

1. Run the game you want to see fixed
2. Press `Win Key + R`, copy `%APPDATA%\Revive` into the dialog and press enter
3. Drag the files into the comment box here and make a new comment.

**Comment by hcorion** [comment]
SNOW has Oculus DK2 support, I'm pretty sure they never added support for the CV1, I don't know if this makes a difference. It's also free, it would be cool to see if it works.

**Comment by LibreVR** [comment]
Indeed, DK2 games are not supported in Revive.
