### ISSUE TITLE
Add update checker

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#272]
I love Revive and am new to this site.  How can I tell when a new version comes out of Revive?  Is there a notification for updates?

**Comment by punttijussi** [comment]
Release-only notifications through GitHub aren't possible as far as I know, but you can subscribe to the [releases page](https://github.com/LibreVR/Revive/releases) Atom feed through [https://github.com/LibreVR/Revive/releases.atom](https://github.com/LibreVR/Revive/releases.atom) using your favourite feed reader.

**Comment by LibreVR** [comment]
An update checker has been added and will be part of the next release.
