### ISSUE TITLE
Does anyone know if Into the Dead or Feral Rites works with Revive?

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#273]
The Wiki doesn't seem to be updated that often.  I tried to add Anshar Wars 2 and it wouldn't let me edit the page.  Does anyone know if Into the Dead or Feral Rites works with Revive?

**Comment by JediDiggler** [comment]
Feral Rites works great with the latest version of Revive.

**Comment by lghtanddrk** [comment]
How do you find out what version of Revive you are using and where do you see the versions on Github? I want to make sure I always have the latest version.

**Comment by LibreVR** [comment]
Version numbers are not yet visible within Revive, if you want to make sure you're running the latest version, just install the latest version.

Once Revive goes stable we'll have things like internal version numbering and update checks.

**Comment by LibreVR** [comment]
I've added Feral Rites to the compatibility list, no idea about Into The Dead.

**Comment by lghtanddrk** [comment]
Thanks.  Anshar Wars 2 should be added too.  I have it and it works well. I tried to edit the page and it gave me errors.  I contacted Github support but never heard back.  Thanks for your help.

**Comment by KenshiHH** [comment]
Bought Feral Rites on the Sale, just got my Vive back from Repair.

Tried Feral Rites with ReVive 0.9.5 and 0.9.7 but the Player Mesh is Missing.
On the Screen where i can choose between Female and Male are the Arms missing on booth and as soon as the first Fight starts the Player Mesh is Completely Gone. everything else is there.
anyone else encountered that problem? already reinstalled the game 3 Times
