### ISSUE TITLE
Edge of Nowhere fix

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#276]
I wanted to buy this and am seeing there are some issues.  Are there any fixes planned to make it stable?

**Comment by LibreVR** [comment]
Sure, but it's a difficult problem, so far multiple attempts at fixing the issue have failed.

Also, please add these kinds of comments to the issues that already exist, I am notified of all comments on the repo so there's no need to make duplicate tickets. It doesn't make me respond any faster and only clutters things up.
