### ISSUE TITLE
Chronos (and other titles) with heavy judder

### ISSUE THREAD

**Issue by Usurper1** [LibreVR/Revive#277]
Heyyy. Any help would be appreciated. 

Ive already turned off reprojection, which got rid of the double-image effect, but I still get insane and uncomfortable judder in Chronos. Its not just Chronos though...it was also in the Oculus version of The Impossible Travel Agency, and Farlands. It happens no matter what settings that I have the games set to. Im just mentioning Chronos because its what Im currently trying to figure out. One of the devs at The Impossible Travel Agency actually gave me a Steam code, so I was able to see how it performed through native Steam....and it works flawlessly. Are there any fixes for Judder...or updates...or anything? Latency issue/fix? Im dying to play this game, and as of right now, its not really playable. Thanks.

**Comment by LibreVR** [comment]
This may be a regression, have you tried an older version such as 0.9.0?

**Comment by Usurper1** [comment]
I actually think I fixed it last night. I extracted the latest patch into the revive folder (is that right?), and things seem to work well now. I also turned reprojection back ON. I ALSO started running stuff through the Vive app itself, which may or may not have made a difference. But regardless, its seems evertyhing is running smoothly now for the most part. No matter where I run the games from. Thanks!

**Comment by LibreVR** [comment]
The correct way to update is to just download the latest version of the Revive Installer and just overwrite your existing installation.

**Comment by Usurper1** [comment]
can you give me a link to the latest update?

**Comment by LibreVR** [comment]
There's a link in the README.md
