### ISSUE TITLE
ReviveInjector is unable to inject into 32-bit applications.

### ISSUE THREAD

**Issue by LibreVR** [LibreVR/Revive#28]
The injector assumes `GetProcAddress(hModule, "LoadLibraryA")` will return the same address for this function as the process being injected into. However when injecting into 32-bit applications this assumption is invalid.

**Comment by LibreVR** [comment]
@rjoudrey Could you look into this issue?

**Comment by rjoudrey** [comment]
I'm going to need more details. LibOVR does not export LoadLibraryA...

**Comment by LibreVR** [comment]
@rjoudrey Yeah, in the injector. There's some more information here, though is solution is a bit complicated:

https://www.corsix.org/content/dll-injection-and-wow64

**Comment by rjoudrey** [comment]
Why don't we just do GetProcAddress(hModule, "GetProcAddress") and then proceed from there?

**Comment by LibreVR** [comment]
Because in a 64-bit process, GetProcAddress will return a 64-bit pointer to the function in the 64-bit variant of the module. You can't inject that into a 32-bit application.

This is necessary for compatibility with Defense Grid 2.

The simplest solution for this is to provide two separate injectors, but that's a bit confusing.

**Comment by LibreVR** [comment]
@rjoudrey I solved it using the simplest solution for now, if you have other suggestions I'm also open to different solutions.
