### ISSUE TITLE
Eagle Flight

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#282]
When starting the game, you are instructed to log in to your Uplay account.
After doing this, I receive the message :  There was a problem authenticating the ownership of this product. After this you can only press Close and the game refused to start.

**Comment by RoboLeader** [comment]
Same here.

**Comment by Rojoyinc** [comment]
I heard that Dec 10th it's released for VIVE anyway. ??? Or was it Dec
20th.
I figured I'd not buy it twice.

**Comment by LibreVR** [comment]
It seems like you need to launch from the Oculus Store to add the game to your uPlay account. If I try to launch it without a headset I'm asked to activate the CD key.

But even after activating it, Revive won't work because uPlay is a launcher and Revive doesn't support launchers yet.

I've never received the message "There was a problem authenticating the ownership of this product."

**Comment by kvdv99** [comment]
Thanks a lot!

**Comment by RoboLeader** [comment]
I have Eagle Flight working on the 1.0 preview. 

1. Remove the files "SteamworksNative, steam_api64 and openvr_api" from the plugins folder.
2. drop the patch version of revive into the "game" folder"
3. Launch the executable.

LibreVR, I'm definitely donating to the EFF right now.

**Comment by PandaMitten** [comment]
@RoboLeader: I tried these steps but still get the error "There was a problem authenticating your account," or if I launch the executable directly UPlay launches asking for my activation key. Since I bought the game on Oculus home, I don't have a key. How did you resolve the authentication issue?

**Comment by RoboLeader** [comment]
You need to talk to their support people directly. Apparently even people launching it with the Rift are running into the authentication problems.

**Comment by LibreVR** [comment]
The only way to get the activation key is to start the game through Oculus Home once. You will need a Rift headset to do so though.

Maybe if you contact Oculus support they can give you your activation key so you can activate it manually? If not we'll have to find a way to fool Oculus Home into thinking the Rift is connected. I heard that this is possible using the DebugTool from the Oculus SDK.

**Comment by PandaMitten** [comment]
@RobotLeader, does this match your experience? Did you activate by running through Home first with a Rift connected?

I don't have a Rift, and I can't seem to find any info about making it run apps without the headset. I spent a little time trying to stumble into an answer using the DebugTool, but for now it seems like I'm out of luck.

**Comment by RoboLeader** [comment]
@PandaMitten I contacted their live support in order to get the application activated on my Uplay account. I sent them a copy of my Oculus receipt and they they were more than accommodating, though it did take a while.

**Comment by PandaMitten** [comment]
Ah, I tried the same thing on launch day but was given the run around. Guess it all depends on who you happen to talk to. Seeing as how you had success now I think I'll try again.

**Comment by Rojoyinc** [comment]
Vice version dec 20

**Comment by seb86200** [comment]
Hello
Eagle flight works perfectly in the Vive, take the version
Revive 1.0 Preview 3 + Patch, not deleted all 3 files.

**Comment by Rojoyinc** [comment]
except I want the devs to know more vive people bought the game than rift
owners.  Waiting for vive release Dec 20th.

**Comment by seb86200** [comment]
Excuse me i do not understand i am french

**Comment by Armada651** [comment]
Eagle Flight has since added support for the HTC Vive.
