### ISSUE TITLE
Dirt Rally 1.23 stopped working with ReVive

### ISSUE THREAD

**Issue by michalk-k** [LibreVR/Revive#283]
After small update released today (1.23) DR doesn't even start with Revive
Log says nothing meaningful

```
Launched injector with: ReviveInjector_x86.exe /handle 152
Injecting process handle: 152
Injecting DLL: F:\_video\ReVive\x86\openvr_api.dll
LoadLibrary found at address: 0x774a4977
Injecting DLL: F:\_video\ReVive\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x774a4977
Injected dlls succesfully
```

but game doesn't start

**Comment by jj2k** [comment]
Same here.  Similar results with x86 & x64 executables.

**Comment by D3luxe** [comment]
+1, definitely broken with the patch.

**Comment by Raging-Beard** [comment]
Same for me and my brother. Only mentioning it as further evidence of the recent game update being the cause.

**Comment by 9000cats** [comment]
Stopped working for me as well. I really hope they didn't lock down the game exe so we can't launch it outside Steam...

**Comment by MasterNameless** [comment]
Yeah, this makes me very sad. I was really enjoying this game, so much more fun than Project Cars. It's definitely the update that's causing it. I'm kinda kicking myself for having auto update on, and not backing up the files!

Hopefully there's a workaround for this...

**Comment by kvdv99** [comment]
same here

**Comment by smygarn** [comment]
+1

**Comment by LibreVR** [comment]
Can anyone here try out the [RevivePatch instructions](https://github.com/LibreVR/Revive#steam-games) with DirtRally?

**Comment by MasterNameless** [comment]
I can try it out as soon as I get home, in about 5 hours, if no-one else can in the mean time.

**Comment by hyperseven** [comment]
done, get the 'game does not support VR' message and just launches into normal display mode.

**Comment by D3luxe** [comment]
@LibreVR - That no longer works. Currently the drt.exe is locked down so the game cannot be launched directly from it - whether through revive or otherwise. Christina, one of the Dirt devs, has commented though saying that they're aware of this change and that it was unintentional, so it may not be worth dedicating much resource to a workaround, assuming they can get it fixed/addressed soon.

https://www.reddit.com/r/dirtgame/comments/587dnx/vive_codemasters_removed_the_ability_to_launch/d8ynk81/?context=3

**Comment by LibreVR** [comment]
@D3luxe The intention of the RevivePatch is to launch it through Steam instead.

**Comment by D3luxe** [comment]
@LibreVR I misread your post, sorry. As hyperseven said though, nothing changes with the patch and launching through steam, it just launches in normal display mode.

**Comment by LibreVR** [comment]
I'll make a different patch that's compatible with Dirt Rally. I'd really like a good way to inject through Steam without injecting into Steam itself, but I don't really see how.

**Comment by LibreVR** [comment]
Please follow the [Steam Games instructions](https://github.com/LibreVR/Revive#steam-games), but [download this 32-bit version of the patch](https://github.com/LibreVR/Revive/releases/download/0.9.7/RevivePatch32.zip) instead.

**Comment by Raging-Beard** [comment]
Thank you so much! :)

**Comment by jj2k** [comment]
Excellent.  Submitting a donation as a thank you.

**Comment by MasterNameless** [comment]
You, sir, are fucking awesome.  Can't wait to get back into Dirt Rally. Thanks very much!

**Comment by kvdv99** [comment]
yes the 32bit patch works, but I see a lot of stuttering when looking around.  Just to be sure, I started a couple of other games and they all ran smooth like usual.  Started Dirt Rally a 2nd time, and got stuttering again.

**Comment by mrbelowski** [comment]
Thanks for fixing this fella, *really* appreciate the amazing work you're doing. 

I'm also seeing weird stuttering, regardless of the gfx settings. Looks like some weird CPU spike every couple of seconds. It does this in the menu as well as in-game and it only happens for Dirt Rally

![f1](https://cloud.githubusercontent.com/assets/840170/19576110/b0696b1a-9709-11e6-9001-f6d7fca80b82.png)
![f2](https://cloud.githubusercontent.com/assets/840170/19576114/b4f4475e-9709-11e6-9c30-25bd3c731efc.png)
![f3](https://cloud.githubusercontent.com/assets/840170/19576169/e252ff10-9709-11e6-8967-c8f02bca2f52.png)

**Comment by michalk-k** [comment]
Great response! Thank you. Donation sent.

**Comment by LibreVR** [comment]
@mrbelowski Thank you for the detailed feedback. Performance improvements is my main priority right now so I will definitely look into it.

**Comment by mrbelowski** [comment]
Tried 0.9, 0.85 and 0.8. 0.9 and 0.85 behave the same and 0.8 doesn't work properly - only 1 eye is rendered correctly in 0.8. As far as I can tell the revive version makes no difference to these pauses. I also use revive for Assetto Corsa and it works perfectly with no pauses

**Comment by LibreVR** [comment]
Well, thanks for testing, then I know it's not a regression.

**Comment by mrbelowski** [comment]
Well, after a *lot* of faffing and trouble-shooting I've found the culprit for this stutter. I disabled 'mouse menu control' and it now runs perfectly. This is after trying a million other things :(

Still, it's now running perfectly. Weird thing to cause such horrible issues

**Comment by theschubinator** [comment]
I just got my Vive this week and was excited to try out Dirt Rally. I've spent hours trying to get the injector to work with no luck. Is it broken, or what am I doing wrong? I downloaded the injector. Extracted its contents, and then copied them over to the Dirt Rally Folder. Yet when I drag drt.exe onto the x86 injector a command prompt pops of very fast (too fast to read what it says) and then nothing. Occasionally the Vive may blink; but then nothing?

**Comment by Raging-Beard** [comment]
Patch works for me, not the injector.

**Comment by Rojoyinc** [comment]
copy the files into your 32 bit dir.   into  DiRT Rally/x86    <---
 LibRevive32_1.dll and openvr_api.dll

**Comment by zoolen** [comment]
its like he said. im doing something wrong...   Yet when I drag drt.exe onto the x86 injector a command prompt pops of very fast (too fast to read what it says) and then nothing. Occasionally the Vive may blink; but then nothing?

**Comment by LibreVR** [comment]
@zoolen You do have Oculus Home installed, right?

**Comment by zoolen** [comment]
i Think i have the right one, its where you can buy stuff for oculus

**Comment by zoolen** [comment]
cant start it in VR coz i dont have a oculus headset.

**Comment by LibreVR** [comment]
You just need to install the [latest version of Revive](https://github.com/LibreVR/Revive/releases) and follow [these instructions](https://github.com/LibreVR/Revive/wiki#steam-games).

The fact that you used the injector means you were reading some old instructions. The injector doesn't work anymore for Dirt Rally.

**Comment by zoolen** [comment]
aha i need to reinstall the game now or ?

**Comment by LibreVR** [comment]
No? What made you think that?

**Comment by zoolen** [comment]
ok i will try.

**Comment by zoolen** [comment]
For these games you can right-click the Revive tray icon on your desktop (bottom-right area of you taskbar)

I must be one stupid swed... but i can't find this !!

**Comment by zoolen** [comment]
IGNORE ! found it ! :P

**Comment by LibreVR** [comment]
Did  you start it through Steam after patching it?

**Comment by zoolen** [comment]
i did as it said.  Open revive - Patch - picked tge dirt Icon and the open then start with steam.

**Comment by LibreVR** [comment]
Since a lot of people seem to be having this issue and I still can't reproduce it, I will put some extra debug logging in the next version.

**Comment by zoolen** [comment]
Onlu time i get image in the vive is when i run Theatre mode.

**Comment by LibreVR** [comment]
Ok, well keep an eye on issue #348.

**Comment by zoolen** [comment]
thx for taking the time to help me. :D

**Comment by LibreVR** [comment]
If you still feel like trying, then try this older version of the patch: https://www.reddit.com/r/Vive/comments/58i5gj/how_to_fix_revive_for_dirt_rally/

**Comment by zoolen** [comment]
yes i will try that to morrow! thx again!

**Comment by zoolen** [comment]
I just reinstalled the vive, and go it to work =) thx for the help
