### ISSUE TITLE
Eve Valkyrie Loads But Never Worked - Reports Missing Entitlement

### ISSUE THREAD

**Issue by jorgevorg** [LibreVR/Revive#284]
"Eve Valkyrie" have not worked once beyond loading and displaying a "Entitlement Error". This is happening on a Intel i& 5820K CPU @ 3.30GHz, 24GB RAM, WIndows 10 Alienware machine,

**Comment by LibreVR** [comment]
Have you tried rebooting your computer?

**Comment by frank707** [comment]
I got this error for another game. Your game may need to install additional files to run properly. You can verify this by opening the oculus app and navigating to library -> installed tab and selecting the game from the list.
