### ISSUE TITLE
updating Revive

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#286]
Hi,

- How can I check with version I'm currently running?
- Also, is it sufficient that I install Hotfix version 0.9.7 (like a rollup patch) to have the latest version, or do I have to install 0.9.6 first?  
- How can I check with version of OpenVR I'm currently running?

many thanks!
Kris

**Comment by LibreVR** [comment]
- You can't
- None of the installers are patches, you just install the latest version by overwriting your existing installation.
- You can't, the application (in this case Revive) decides which version of the API to use.
