### ISSUE TITLE
Chronos "Please connect gamepad"

### ISSUE THREAD

**Issue by rowdypowdy** [LibreVR/Revive#287]
Hi,

I downloaded Chronos to play with ReVive but it just keeps saying please connect gamepad. Is there something i need to setup in order to play? Any advice is greatly appreciated :)

**Comment by LibreVR** [comment]
Did you connect an Xbox gamepad?

**Comment by jimx78** [comment]
Hi, I have the same problem with all the games with joystick xbox one.
Only the VIVE controller works like a joystick (it should have a choice?)

**Comment by jimx78** [comment]
Hi, I have the same problem with all the games with joystick xbox one.
Only the vive controller works like a joystick (it should have a choice?)

**Comment by jimx78** [comment]
exemple : lucky tale

**Comment by jimx78** [comment]
http://support.xbox.com/fr-FR/xbox-on-windows/accessories/how-to-update-xbox-one-controller-windows-10

**Comment by LibreVR** [comment]
Make sure the application window has focus or else it won't accept gamepad input.

**Comment by Perfarator** [comment]
Didn't work for me.
