### ISSUE TITLE
Can't launch Revive Dashboard Win10 x64

### ISSUE THREAD

**Issue by RewG** [LibreVR/Revive#288]
I can't launch Revive Dashboard. There is no errors or some windows, just quickly show in Task Manager ReviveOverlay.exe and closing.

Windows 10 x64
AMD FX6300
NVIDIA GTX960
Revive 0.9.7

**Comment by LibreVR** [comment]
Please post your logs from the `%APPDATA%\Revive` folder. You can just rename them to .txt files and upload them here by dragging them into the comment box.

_Please don't eat the dashboard for lunch_

**Comment by erwunscht** [comment]
I have the same issue on Win10 x64.

My log just says:
libpng warning: iCCP: known incorrect sRGB profile
Failed to connect to OpenVR Runtime

Windows 10 x64
i5-6600k
GTX1070
Revive 0.9.7

**Comment by Vallaqan** [comment]
It's actually fine. I thought the Dashboard EXE had to stay open. The icon is there in SteamVR. Awesome app. Lucky's Tale is pretty great.
