### ISSUE TITLE
Injector & patch doesnt start Steam Dirt Rally

### ISSUE THREAD

**Issue by SergeantKid** [LibreVR/Revive#290]
Hi, i bought Dirt Rally thinking it would work with my VIVE. realised it wasnt compatible and followed a couple of forums to the revive solution. 

i have removed the "play in theatre mode" tick in steam, installed oculus software and skipped the rift setup. extracted the .zip file for injector into the root dir for dirt rally but when i drag and drop the drt.exe onto the x64 i get a dos screen (i screen dumped this to examine and all process complete successfully) but the game doesnt start at all. my fans spin up like its about to but nothing happens on screen or in VR. Steam VR is on and ready and i am at a loss

please help
[New Microsoft Word Document.docx](https://github.com/LibreVR/Revive/files/549160/New.Microsoft.Word.Document.docx)

**Comment by LibreVR** [comment]
The old injector solution stopped working recently, so you were on the right track with trying to use the patch. However you need to use the 32-bit version, you can find the instructions here: https://www.reddit.com/r/Vive/comments/58i5gj/how_to_fix_revive_for_dirt_rally/

**Comment by SergeantKid** [comment]
LOL!! im such an idiot, i should have posted this hours ago ;-) 

thank you for an incredibly quick response i will try now!!

**Comment by SergeantKid** [comment]
wow that worked perfectly thanks again

**Comment by LibreVR** [comment]
Nah, I just haven't taken the time to document it properly. That reddit post was pretty much the only way for you to find out right now.
