### ISSUE TITLE
all games used with revive injector have wrong head placement

### ISSUE THREAD

**Issue by zorochi** [LibreVR/Revive#291]
how do i change the  facing view and head height on games that use oculus when running the injector?
 lately all games ive tried to use the revive on are coming up wrong on the vive

**Comment by LibreVR** [comment]
There are many different methods, the most reliable one is to keep the system button press on the Vive controller until a menu shows up. Then press the Reset Seated Position from the menu.

**Comment by zorochi** [comment]
It's not detecting seated experience on some of the revive games that are using the injector,  I have this issue with afew unreal 4 based games and also more recent unity based ones. 
Holding the menu button isn't working for me as it's not showing reset vr position in the menu. 
I didn't have this problem when I first used revive for some games but now do.

**Comment by LibreVR** [comment]
Ah I see, yeah this is a bug introduced with the OpenVR 1.0.3 update. I fixed it in commit d6a82ff2722c74c4ba83dd88d9e04e131ea9a2af.

For now you should revert back to Revive 0.9.7.

**Comment by LibreVR** [comment]
Or alternatively you could go the your `steamvr.vrsettings` file and add `DefaultTrackingOrigin: 0` to the `revive` section.
