### ISSUE TITLE
Question about Dirt Rally compatability

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#293]
Based on your Revive 1.0 Preview it seems that Dirt Rally works if purchased through the Oculus store.  Does it work in any previous stable versions of Revive with the Oculus Store version?  It's not listed at all in the compatibility list.

**Comment by LibreVR** [comment]
I haven't tested the Oculus Store version, though it should work in theory I can't tell you with complete certainty. I haven't heard of anyone testing it either.
