### ISSUE TITLE
Town of Light

### ISSUE THREAD

**Issue by JediDiggler** [LibreVR/Revive#295]
This doesn't seem to show up in the HMD even though it looks like it injects successfully (Revive log ends with "Injected dlls successfully"). Is there any special knack to getting it to work? The devs say that loading up first then pressing CTRL-L once in game should activate the VR display, but nothing happens here. Tried a bunch of different Revive patches and injectors from 6.1 - 1.0beta.

**Comment by pearce31** [comment]
I'm having same problem with albino lullaby won't show up in headset just on monitor.

**Comment by LibreVR** [comment]
@JediDiggler Where did you buy Town of Light? Are you using a version that supports the Oculus Rift CV1?

@pearce31 This is a ticket about Town of Light, not about Albino Lullaby. The fact that it doesn't show up on the HMD can have any number of reason, so you should **create a new ticket** where you explain the situation in detail. Which versions of Revive did you try? Where did you buy Albina Lullaby? Which operating system?

**Comment by JediDiggler** [comment]
Just the latest version on Steam, it apparently works for some so am I just overlooking something? Anyone else tried this one?

**Comment by tig3rmast3r** [comment]
same here, tried both steam vr normal and beta.
using latest revive 0.9.7 (not pre-releases).
will try 1.0 pre-release soon.
a vr icon should appear on the main page, and it appears just for a fraction then it disappears, nothing changes pressing ctrl-L (this should enable vr).
tried both injector and patch, tried also older versions of injector and patch (0.6 or something like that)

**Comment by LibreVR** [comment]
@tig3rmast3r That may be due to Oculus changing their manifests, keep an eye on issue #307.

**Comment by JediDiggler** [comment]
Works great now, cheers!
