### ISSUE TITLE
Dirt Rally Won't open

### ISSUE THREAD

**Issue by dodossssssssss** [LibreVR/Revive#297]
I have tried using the ReviveInjector for dirt rally however the game will not open. The cmd screen flashes however nothing happens afterwards. I have tried with steamvr on and off along with using the revive patcher however nothing seems to get the game to launch in vr. (Revive patch made it launch in 2d, the game did not show up in the revive tab) Using drt.exe alone from the steam install of the game doesn't seem to launch the game either so that may be part of the problem. Any help would be appreciated.

**Comment by DaXod** [comment]
Same here... i bought the game extra for Vive - please help! 

THX A LOT

**Comment by DaXod** [comment]
Same here... i bought the game extra for Vive - please help! 

THX A LOT

**Comment by LibreVR** [comment]
The ReviveInjector is no longer supported for Dirt Rally, please follow the instructions for Steam Games here: https://github.com/LibreVR/Revive/releases/tag/1.0-preview

**Comment by Rojoyinc** [comment]
I had the same problem - but I copied the patch into the  x86 dir and it
started working.

**Comment by DaXod** [comment]
It works just perfect now, thanks a lot :-)
