### ISSUE TITLE
vTime

### ISSUE THREAD

**Issue by Mike4VR** [LibreVR/Revive#299]
vTime just updated to a brand new HD version on Oculus Rift. Since this update on 11/10/16, it won't load properly on Revive. I had a friend try and he wasn't able to get it to load properly either.
vTime will load to the white room (Agora Destination), but head tracking and the ability to open the menu are not available.

**Comment by LibreVR** [comment]
I see this is a free experience on the Oculus Store? Are you launching it through the Revive Dashboard?

I'll test it out myself soon.

**Comment by rquinn** [comment]
Just tried this evening 11/20, brand new install of SteamVR, revive, oculus and vtime.  Shows in the menu but starting it drops you into the white room and you're stuck.  Thanks for checking on the defect.

**Comment by rquinn** [comment]
whether you launch through steam or through the revive dashboard, behavior seems the same.  on my system it loads to the white room, sound works and the scene is displaying on my monitor but as reported by @Mike4VR no head tracking.  monitor display doesn't respond to any controller input either.

**Comment by rquinn** [comment]
worked on 12/23 after upgrading to latest revision of revive.

**Comment by LibreVR** [comment]
Thanks for letting me know, closing this issue.
