### ISSUE TITLE
Dreamdeck no longer works

### ISSUE THREAD

**Issue by xanderhd** [LibreVR/Revive#30]
Just tried it and got "Cannot run this application without an Oculus Rift." 
I think they patched it. 
Or am i doing it wrong?

**Comment by NeoToriyama** [comment]
You're doing something wrong, just tried it today and it still works. Remember to choose the .exe titled "Dreamdeck-Win64-Shipping" located in Oculus/Software/oculus-dreamdeck/WindowsNoEditor/Dreamdeck/Binaries/Win64

I made the mistake earlier of choosing the one in the normal directory and thought the same thing, hope this helps!
