### ISSUE TITLE
Touch Tutorials

### ISSUE THREAD

**Issue by darrellspivey** [LibreVR/Revive#300]
Any way we can get the new Oculus Touch Tutorials running? I want to try out Revive's Touch implementation. Tried dragging the injector onto TouchNUX-Win64-Shipping.exe with no luck.

**Comment by LibreVR** [comment]
I've never heard of any Oculus Touch experiences having shipped yet. The touch implementation in Revive is still experimental and I'm currently still working on improving it in preparation of the December release.

**Comment by darrellspivey** [comment]
Yep, there's a Touch tutorial and intro experience that are automatically downloaded and added to the bottom of your Oculus Library when the Oculus desktop app is updated to the newest version. 
I saw them today and thought "Yes, I finally get to see what Touch emulated on my Vive feels like!" Just excited to see how well it works.

**Comment by LibreVR** [comment]
Wow, they got me off-guard then, that's way earlier than I expected. I'll try and speed up my 1.0 release then.

**Comment by LibreVR** [comment]
Just tested it with an internal developer version, it does work, but I'm making some final changes to the mapping to make it more intuitive. Also, the dashboard does not support these new "Tutorial" apps yet, I'll have to update that too.

I expect I'll have it done before Monday.

**Comment by LibreVR** [comment]
These tutorials are giving me a much better idea for the mapping. Since we have render models now I can just consider the front face of the Touch controller as a big touchpad, so I'll try and put the buttons and thumbstick in the same locations.

I'm very excited about this, I think I can map nearly everything intuitively despite the absence of captivate sensors.

**Comment by LibreVR** [comment]
This will be the new mapping for the touchpad (forgive my usage of paint):

![mapping](https://cloud.githubusercontent.com/assets/18057864/20237490/bf4319b4-a8cb-11e6-8df6-767678c1b77b.png)

**Comment by darrellspivey** [comment]
Looks awesome! This is exciting

**Comment by LibreVR** [comment]
Okay, the mapping is complete, I'll work on adding these tutorial to the dashboard now.

**Comment by 3Duke** [comment]
LibreVR, you're a doing an incredible job with Revive and updating it with Oculus changes, lot of thanks from a VIve user

**Comment by LibreVR** [comment]
Here's a preview of the version that uses the new mapping and supports the Oculus Touch haptics. So this should allow you to inject into the Touch Tutorials:

[ReviveInjector-Touch.zip](https://github.com/LibreVR/Revive/files/587395/ReviveInjector-Touch.zip)

You're free to share this preview with others on /r/vive or anywhere else, I will post a proper release later that supports launching these experience through the Revive Dashboard.

As an added bonus, the new version of Oculus Home also has a demo for the Avatar Editor in `Oculus\Support\oculus-avatar-editor`.

**Comment by vraddict** [comment]
Just tried this !! Wow amazing !!

**Comment by darrellspivey** [comment]
Just tried the tutorial and the avatar editor. Fantastic work! Your new touchpad layout feels great.

**Comment by cbuchner1** [comment]
Hi! Great work with the touch emulation. I was getting the occasional stutter in the Touch tutorial, despite owning a GTX 1080. So I am wondering if ReVive does make any use of the Oculus 1.10 runtime's built-in ASW feature?

**Comment by LibreVR** [comment]
@cbuchner1 This version of Revive takes advantage of new features in the SteamVR Beta, you will need to run the SteamVR Beta to use it.

**Comment by KiwiStrider** [comment]
@LibreVR I am super excited to try this out but for some reason i am unable to get it working, the injector will load the game but nothing will happen inside of the headset and the game seems to not be detecting the headset at all.

**Comment by darrellspivey** [comment]
@KiwiStrider Are you using the tutorial app in this directory?

Oculus/Support/oculus-touch-tutorial/TouchNUX/Binaries/Win64/TouchNUX-Win64-Shipping.exe

You'll need to drag TouchNUX-Win64-Shipping.exe onto the injector

**Comment by KiwiStrider** [comment]
@darrellspivey Yes I'm dragging the correct exe onto the revive injector and its launches and load but nothing shows inside the headset except the steam vr enviroment

**Comment by KiwiStrider** [comment]
@darrellspivey It would not work with the x86 injector but it does work with the x84
