### ISSUE TITLE
Obduction through Steam...?

### ISSUE THREAD

**Issue by Usurper1** [LibreVR/Revive#303]
Hey hey...

      So I  bought Obduction through Steam a while ago, but am looking to get it working on my Vive. Its an oculus only game. I followed the instructions, but it doesnt seem to work...? Maybe Im confused about this part of the steps..."Extract the patch into the folder that opened next to the executable"...?

      Next to the executable are to txt files. The next one closest is a folder labeled, Obduction. I extracted it in there. 

Any help would be appreciated! Thanks.

**Comment by LibreVR** [comment]
You need to extract the patch into `Obduction\Win64\Obduction\Binaries\Win64`.
