### ISSUE TITLE
Review 2 tray icon not showing consistently

### ISSUE THREAD

**Issue by gormanj** [LibreVR/Revive#305]
Review 2 tray icon not showing consistently. Revive Overlay is in setting, but it doesn't show when it is set to show in customize or popup menu. It showed for me once.

**Comment by LibreVR** [comment]
I accidentally linked to the old version, can you re-download it and try again?

**Comment by gormanj** [comment]
It seems fine now. I tried a few times and it loads when SteamVR loads. Thank you!
