### ISSUE TITLE
bring back standalone patch/injector

### ISSUE THREAD

**Issue by primarydataloop** [LibreVR/Revive#306]
please bring back the standalone patch and injector. I used them easily to try oculus stuff both from the store and not. I never liked or installed the overlay, and I dont want a tray icon. tyvm.

**Comment by LibreVR** [comment]
Both the patch and the injector are still there. The injector has always installed with the installer to `C:\Program Files\Revive\Revive` and the patch is in the `x64` and `x86` directories if you copy both DLLs and rename `LibRevive64_1.dll` to `xinput1_3.dll`.

**Comment by primarydataloop** [comment]
so I have to install it first to get the dlls?

**Comment by LibreVR** [comment]
Correct, I could upload them separately for now, but I do plan to stop distributing them separately eventually.

**Comment by primarydataloop** [comment]
it would be much appreciated.

**Comment by LibreVR** [comment]
Why do you prefer to use it separately though?

**Comment by primarydataloop** [comment]
I never used the overlay (it never worked well for me). I also don't play much oculus home games (unless free) and so I use revive for endless amounts of other small demos out there I download manually, so I need to use the manual patch or injector. Finally, I want to take steam screenshots and share them, so I have to add these programs as non-steam-shortcuts linked to either the exe adjacent to the patch files, or to the injector exe. I mean I quess I can install revive, get the dls, and uninstall it, but I would find that cumbersome. ty.

**Comment by primarydataloop** [comment]
I would note that you could just ship a zip file with the injector files, and that comes with the patch files. Before it was 4(?) different zips total for 32/64 patch/injector.

**Comment by LibreVR** [comment]
I've uploaded the zip files: https://github.com/LibreVR/Revive/releases/tag/1.0-preview-2

But I do want to move towards a single auto-updating package, as the 3-different-packages-on-a-github-page is cumbersome and is kind of a bottleneck on how quickly I release new versions.

**Comment by primarydataloop** [comment]
Ok thank you.

**Comment by gormanj** [comment]
I like to have access to the standalone to be able to setup up someone else with a vive-enabled oculus app. I can just provide a standalone app folder and explain to them to drag the app to the revive icon. Really I would like it if I could provide them with an exe that launched a game with revive.

**Comment by primarydataloop** [comment]
[Revive-1.0.0-rc3-Patch.zip](https://github.com/LibreVR/Revive/files/602268/Revive-1.0.0-rc3-Patch.zip)
[Revive-1.0.0-rc3-Revive.zip](https://github.com/LibreVR/Revive/files/602269/Revive-1.0.0-rc3-Revive.zip)

updated zips for rc3

**Comment by LibreVR** [comment]
@primarydataloop There were no changes to either the patch or the injector in Preview 3.

**Comment by Wowfunhappy** [comment]
Just want to add that I also prefer using the DLL patch separately, for aesthetic reasons. Although personally, I don't have a problem extracting the dll's from the exe myself.

**Comment by LibreVR** [comment]
Well, one of the other major concerns I had with publishing them separately is that users never knew whether they needed 64-bit or 32-bit path. They also often misplaced subdirectories when using the injector and all other sorts of shenanigans.

Using the tray icon also gives me more control to automate the process for those users.

**Comment by primarydataloop** [comment]
Would it be easier to just ship a ReviveInjector.zip, with both architectures? It basically has the patch files in there, and the architectures are labeled. This sillyness must annoy you. Thank you for 1.0.

**Comment by Wowfunhappy** [comment]
I totally agree that the DLL is less user-friendly, and it should probably be unsupported. I just personally like using it (and know how).

If it makes updating the app more difficult, I can totally understand nixing it.

**Comment by LibreVR** [comment]
@primarydataloop I did ship ReviveInjector with both executable, the 64-bit one even delegates 32-bit applications to the 32-bit injector if it detect it's necessary.

**Comment by LibreVR** [comment]
Also, just to be clear, I totally understand why people would prefer DLLs and CLI utilities if you're a tech-savvy person. The problem is, VR is not just for the tech-savvy anymore.

**Comment by kvdv99** [comment]
..." I did ship ReviveInjector with both executables, the 64-bit one even delegates 32-bit applications to the 32-bit injector if it detects it's necessary.  But some people think they don't need those x86 and x64 subfolders, so the injector is left without DLLs to inject."...

Does this mean that the injectors in the  \Revive\Revive\ folder don't work anymore?

**Comment by LibreVR** [comment]
@kvdv99 They do work, what changed is that you can now only get them when you install the entire Revive Dashboard package.

**Comment by kvdv99** [comment]
Ah ok, I see, thanks

**Comment by Wowfunhappy** [comment]
> patch is in the x64 and x86 directories if you copy both DLLs and rename LibRevive64_1.dll to xinput1_3.dll.

This is being a little finicky for me for x86 games. I fully recognize that this setup is unsupported, but would appreciate clarification to make sure I'm not screwing up something really basic:
• For 64bit games, I drag both files from the x64 folder into the same directory as the game executable and rename "LibRevive64_1.dll" to "xinput1_3.dll", leaving "openvr_api.dll" with its original name.
• For 32bit games, I drag both files from the x32 folder into the same directory as the game executable and rename "LibRevive_32_1.dll to "xinput1_3.dll", leaving "openvr_api.dll" with its original name.

Can you confirm the above is correct?

**Comment by Armada651** [comment]
Closing this issue as I really don't intend to release these separately anymore.

@Wowfunhappy That is correct.

**Comment by ajsw78** [comment]
Guys pls explain to me how to inject dirt rally on my revive please....theres no patch menu and no inject menu on the updated revive pls let me know
