### ISSUE TITLE
Revive Dashboard can't start Unreal Engine games

### ISSUE THREAD

**Issue by DowJohns** [LibreVR/Revive#307]
After downloading the latest Revive installer, EVE Valkyrie no longer loads.  I reverted back to 1.0 first preview and the same thing is happening (where it worked before).  PC keeps saying fatal error in loading window.  I have uninstalled and reinstalled the game on my PC and rebooted everything but it is still happening.  Is this a Revive or Oculus issue?  Other titles for me seem OK.

**Comment by LibreVR** [comment]
Could you try a non-preview version? You can get it on the frontpage.

I'll look into this problem.

**Comment by DowJohns** [comment]
After multiple uninstalls, reinstalls, and different versions of Revive, the game simply no longer works.  Maybe it received an update that you now must use the injector (though didn't have to before)?

**Comment by LibreVR** [comment]
@DowJohns There seems to be a bug in the Dashboard, have you tried [version 0.9](https://github.com/LibreVR/Revive/releases/download/0.9.7/ReviveInstaller.exe)?

**Comment by DowJohns** [comment]
After installing version 0.9, Eve Valkyrie still does not load while producing the same Fatal Error message.  If you could keep me posted on any further developments it would be appreciated and let me know if I can help on my end.

Thanks for providing this awesome tool.

**Comment by LibreVR** [comment]
Okay I've found the issue, Oculus switched to backslashes in the new update. This means my detection of the main executable fails: https://github.com/LibreVR/Revive/blob/master/ReviveOverlay/Oculus.js#L13

I'll fix this soon.

**Comment by 994wemj** [comment]
Thanks LibreVR, your efforts are very much appreciated. I've updated the wiki until this is fixed. For info, Valkyrie came out on Steam today so those with issues may be able to switch to native.

**Comment by DowJohns** [comment]
@994wemj - is there a way to switch form an Oculus file to a Steam file without repurchasing the game?

**Comment by 994wemj** [comment]
@DowJohns Judging by this you'll need to file a ticket. http://steamcommunity.com/app/538870/discussions/0/215439774854841171/

**Comment by DowJohns** [comment]
@994wemj - Thanks!

**Comment by LibreVR** [comment]
This is fixed in 7539f83c90083a6d753284f7185b8c58f268e85f.

I'll release a hotfix tomorrow.

**Comment by seb86200** [comment]
Impatient to have this fix, thank you for this work

**Comment by DowJohns** [comment]
Thanks LibreVR!

**Comment by LibreVR** [comment]
Small delay with the hotfix, I should be able to release it tomorrow.

**Comment by seb86200** [comment]
Haa Yessss Merci merci merci

**Comment by LibreVR** [comment]
The new version is available on the [releases page](https://github.com/LibreVR/Revive/releases).

This will be the last preview release before the proper release of Revive 1.0 in December.

**Comment by seb86200** [comment]
thanks again

**Comment by badoczx** [comment]
Man, thanks very much for u support.  But the issue with Unreal Engine games is not fixed.  No with Eve Valkyrie at least.

**Comment by seb86200** [comment]
Eve Valkyrie does not work with Revive 1.0 Preview 3 + patch in return Eagle Fligt works perfectly in the Vive thank you thanks thanks
