### ISSUE TITLE
Dashboard does not load automatically + Can not boot game from Dashboard

### ISSUE THREAD

**Issue by Drocona** [LibreVR/Revive#308]
Hello!

First of all, great job on Revive! Thanks a bunch.

I got the Vive last week and just installed Revive yesterday, but I'm having some problems with running Revive Dashboard automatically on SteamVR boot. I always have to manually boot it from my desktop.
As soon as I boot it, it appears in VR. But when I reboot SteamVR, it's gone again.

Also, I can't seem to boot Farlands from the Revive Dashboard, but it works fine with the Injector.

Some logs (Dashboard):

> libpng warning: iCCP: known incorrect sRGB profile
> Loaded manifest from: D:\Programs\ReVive\revive.vrmanifest
> Runtime directory: file:///D:/Games/Steam/steamapps/common/SteamVR/
> Oculus directory: file:///D:/Games/Oculus/
> Loading assets manifest: file:///d:/Games/Oculus/Manifests/oculus-farlands_assets.json
> Loading assets manifest: file:///d:/Games/Oculus/Manifests/playful-luckys-tale_assets.json
> Found assets bundle oculus-farlands_assets
> Loading application manifest: file:///D:/Games/Oculus/Manifests/oculus-farlands.json
> Found assets bundle playful-luckys-tale_assets
> Loading application manifest: file:///D:/Games/Oculus/Manifests/playful-luckys-tale.json
> Found application oculus-farlands
> Launching application: oculus-farlands
> Failed to launch application: revive.app.oculus-farlands (VRApplicationError_LaunchFailed)

**Comment by LibreVR** [comment]
This is the same issue as #307.
