### ISSUE TITLE
Can't install oculus home - CPU faild

### ISSUE THREAD

**Issue by Christof-Eugster** [LibreVR/Revive#313]
Hi
I tryed to run Revive for Dirt Rally. But Cant install Oculus Home
because i have Phenom II CPU which is not supporting SSE 4.2.
Is there a chance Revive will ever work without Oculus Home
especially for Dirt Rally?
Thanks

**Comment by LibreVR** [comment]
Does it really refuse to install? It's enough that the files were installed, you don't need to run Oculus Home.

**Comment by Christof-Eugster** [comment]
Yes! I have only the button to quit the installation process. Others tryed to fool the program with changing the string name of the cpu but this doesent help. Ive read that the installation Programm is testing SEE 4.2 Code to see the CPU can handle it or not. So yes. no way at the moment for me to use Revive. My cpu running at 3.9 with 6 cores is well enought for most games...

**Comment by LibreVR** [comment]
Do you have any PC that can install Oculus Home? If you can get the `OVRRT64_1.dll` and `OVRRT32_1.dll` files from the `Oculus\Support\oculus-runtime` directory then you can put those next to the Dirt Rally executable. In theory that should allow it to start with Revive.

**Comment by Christof-Eugster** [comment]
No i havent a second computer. Can you send me those two files? So i can try it...
If not im sure ill find a way to get those two files...
Thanks. Would be fantastic if this solution works..

**Comment by LibreVR** [comment]
I cannot send you those files.

**Comment by Christof-Eugster** [comment]
i understand. ill try to get those and will tell you how it works.
Thank you so much for all you effort.

**Comment by Christof-Eugster** [comment]
OK. Tested it... Works Perfect!
Thanks for your help... And your Programm
Worth some money!
