### ISSUE TITLE
installed Revive 1.0 Preview 3 but no sys tray icon for injector

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#315]
Hi,
I installed Revive 1.0 Preview 3 but..
- don't see a system tray icon for injector
-  patch is still standalone and still v 0.9.7 ?
thanks
Kris

**Comment by LibreVR** [comment]
The tray icon start automatically when SteamVR is launched.

**Comment by kvdv99** [comment]
I've rebooted my pc just to be sure,  SteamVR starts up automatically, everything works, I can see the Revive button, it works.
But still no injector in the sys tray.

How can I troubleshoot?  How can I verify my current Revive/Injector version?

thanks!!

**Comment by LibreVR** [comment]
If you have the tab you should have the tray icon too, maybe it's not visible due to a black background? I've been meaning to switch to an icon with more contrast for the final release of Revive 1.0.

**Comment by kvdv99** [comment]
I checked again, saw nothing in the sys tray.  SteamVR and Reviveoverlay are running.
I checked the sys tray icon for reviveoverlay explicitly in the sys tray settings of Windows 10 (see attachment,  "aan" means "on"), but still no sys tray icon.

![image](https://cloud.githubusercontent.com/assets/21249617/20548131/1c320e34-b121-11e6-9d1b-4e1e31f7c231.png)

**Comment by LibreVR** [comment]
Very strange, I wouldn't know what the problem is in that case.

**Comment by kvdv99** [comment]
[Revive.zip](https://github.com/LibreVR/Revive/files/611561/Revive.zip)

**Comment by LibreVR** [comment]
Based on the logs it looks like you are using Revive 0.9.7, if you need the injector and patch you can find there here: https://github.com/LibreVR/Revive/releases/tag/0.9.7

Version 0.9.7 does not have a tray icon.
