### ISSUE TITLE
Dirt Rally not working for me?

### ISSUE THREAD

**Issue by Turby88** [LibreVR/Revive#317]
So, I got my vive in, already had DR downloaded, downloaded ReVive, unchecked the box on DR for theater view, patched DR with the ReVive tray icon with Steam VR running, went to fire up DR and it says play in theater mode... Tried clicking it out of curiosity, it loads up on my monitor, but not my HMD...

Help please?

**Comment by LibreVR** [comment]
Have you tried the Inject option instead? It seems that for some people the patch doesn't work, but the injector does.

**Comment by Turby88** [comment]
I just tried that and some weird stuff happened... My place space turned in to a large "orb" with a screen on it that had the game... And it kept telling me the Oculus headset wasn't on, put it back on...

**Comment by Turby88** [comment]
Ok, that is apparently actually the game lol... It works! Thanks!
