### ISSUE TITLE
Pause menu appears every 5 seconds on Edge of Nowhere and Pinball FX 2 VR

### ISSUE THREAD

**Issue by Djneo134** [LibreVR/Revive#319]
Hi, I would report a very frustrating bug which occurs on Edge of Nowhere and Pinball FX 2 VR.

These two games launch well but every five or ten seconds, the pause menu pops-up in front of the screen, making the game stop. It's very very irritating and makes the game unplayable.

It happens only on these 2 games. Lucky's Tale, Chronos, AnsharWars 2 work well.

I use an Xbox one controller, Windows 10 and Riftcat with a smartphone connected.
I also use a PSEye webcam with PSMoveService running, to pass the positionnal test for games like Chronos and Edge of Nowhere.

Have you already got the same problem ?
How can I rectify this ?

Thanks

**Comment by LibreVR** [comment]
This is a problem with Riftcat, please do not report issues here unless you can reproduce them using an HTC Vive headset.

The developers of Riftcat advertise Revive support but I am not in any way involved with them.
