### ISSUE TITLE
best way to update from 0.9.7 to 1.0 ?

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#320]
Hi,

I installed Revive 1.0 without any problems or errors/warnings in the same directory as the previous version.  However, I cannot see the ReviveInjector in my sys tray so I send you the logs and you told me that it looks like I'm still running 0.9.7.

What's the best way for me to upgrade? Can I remove the d:\revive directory and install 1.0 from scratch?  Or will I loose important stuff this way?

Thanks for the support!

**Comment by LibreVR** [comment]
I'm pretty sure you're just using the wrong link. Remember, the links on the frontpage are still 0.9.7.

You can download the latest preview version here: https://github.com/LibreVR/Revive/releases/tag/1.0-preview-3
