### ISSUE TITLE
Pause menu constantly popping up and makes edge of nowhere unplayable

### ISSUE THREAD

**Issue by pearce31** [LibreVR/Revive#324]
It does it over and over and it's unplayable. Someone also posted to reddit about this and said it happens to them on pinball fx 2 also. What would cause this? Don't know if this is a revive problem or not my mistake if it isn't. I've had the problem on latest preview and latest release before preview versions.

**Comment by LibreVR** [comment]
This is a bug with VRidge, please make a bug report to the Riftcat developers so they can fix this problem. Tell them they haven't implemented `GetTrackedDeviceActivityLevel` correctly.
