### ISSUE TITLE
Dragon Front issues (coinciding with last DF update)

### ISSUE THREAD

**Issue by paulasheville** [LibreVR/Revive#326]
I'm unable to get Dragon Front to launch with Revive.  The program (or some program) launches for a second then the window closes. I've rebooted Oculus, rebooted the vive multiple times, rebooted my machine, etc to no avail. Other new games that were installed since the last time I rebooted my Oculus are working fine such as Gary the Gull, but not Dragon Front. 

There is no error message, and after I try to launch, the revive menu acts funny and I can't scroll with the pad. It scrolls but is locked to the pointer unless I restart Steam VR.

Found this comment on Reddit so maybe it's related:
https://www.reddit.com/r/Vive/comments/5d53pn/has_anyone_been_able_to_get_dragon_front_working/

A developer mentioned that the last big update broke it (edit)

Please help! :)

**Comment by LibreVR** [comment]
I think they may have added preliminary OpenVR support, try launching the Dragon Front executable directly and see if it works.

If that doesnt work, try this development version of the injector: [ReviveInjector.zip](https://github.com/LibreVR/Revive/files/627272/ReviveInjector.zip)

If you installed Revive in the default location you can extract the injector to `C:\Program Files\Revive\Revive` to use it for the dashboard.

**Comment by euandrei** [comment]
@LibreVR It worked first time I used it. I downloaded the injector, and it worked. It was really good but after the first usage I tried again and it gives the same behaviour.

**Comment by LibreVR** [comment]
That's strange, I'll be sure to test it out before I release the next version.

**Comment by euandrei** [comment]
i found out that it works if you use injector with VR closed ( not open ) it will work. but just dragon fort

**Comment by LibreVR** [comment]
What do you mean with VR closed? Have you tried restarting SteamVR?

**Comment by euandrei** [comment]
steamVR app should be not running, when using injector in this particular situation it works.

**Comment by LibreVR** [comment]
That's very strange, I'll see if I can reproduce any of these problems. Just to confirm, you are using an HTC Vive right?

**Comment by euandrei** [comment]
Yes HTC vive,  latest softwares versions. Thank you for being so responsive.

**Comment by euandrei** [comment]
I found a fix. Seach for TEMP/ BINARIES. There is another executable that works ! not the one in the main folder.

**Comment by paulasheville** [comment]
Is there an edit we can do to a config files for Revive so we can launch that exe from within Steam Revive dash?

**Comment by LibreVR** [comment]
@euandrei The problem you are having with the dashboard is a bug in SteamVR, I have reported it here: https://github.com/ValveSoftware/openvr/issues/330#issuecomment-264608232

I also implemented a workaround: 74074c1e3201d1de1ec1bf698141688298f26e3a

@paulasheville The dashboard is already using that executable if you are running a recent version of Revive.

If you want to double-check, the config file is the `revive.vrmanifest` in the Revive installation directory.

**Comment by paulasheville** [comment]
How would we go about editing files to implement that workaround, or is there a fixed file we can download? Not sure how the workaround gets utilized. Not a programmer here so clueless about that.

**Comment by LibreVR** [comment]
@paulasheville What do you want to work around? Like I said, there is no bug with the dashboard.

**Comment by paulasheville** [comment]
Confused. . . when you said "I also implemented a workaround here" I thought you were referring with the issue of DragonFront not being able to currently launch from the SteamVR Revive dashboard. I thought there was a workaround being recommended. Maybe you were referring to a different issue euandrei was reporting? I can use the injector but didn't know if there was a way to get DragonFront to launch in the steamvr dashboard for now, as many including myself are unable to get it working.

**Comment by LibreVR** [comment]
@paulasheville I've got Dragon Front working in the latest development version, which will be released before Tuesday. Best to just wait for the update and report whether it's fixed then.

**Comment by LibreVR** [comment]
Should be fixed now.

**Comment by gitfat** [comment]
i can't play dragonfront, the last I tried i was getting problems with creating/finding servers. anyone else able to get it to work?
