### ISSUE TITLE
AirMech Command

### ISSUE THREAD

**Issue by euandrei** [LibreVR/Revive#328]
I bought the game, it boots up and the windows comes in where the controls and the headset are recognized. altough other than the window in the actual VR you still see the empty planes of Valve, the game doesn't actually boots in the vr world but just on the screen window. 

Any ideas ?

**Comment by LibreVR** [comment]
This is broken in the development version, use the latest regular release (0.9.7) to fix it.

**Comment by LibreVR** [comment]
Fixed in f8a837afedf7897156e56b46d314fe5f6a04e883.

The fix will be part of the next release.
