### ISSUE TITLE
Question About Compatibility with Oculus Touch Games

### ISSUE THREAD

**Issue by newend** [LibreVR/Revive#329]
Was just curious, I was reading some articles regarding the HTC Vive controllers to not able to do 100% of what the Oculus touch controllers can do in some games.  I was just curious what types of things the vive controller will not be able to do?

**Comment by LibreVR** [comment]
The latest preview release maps all functionality of the touch controller to a Vive controller. But due in part to a lack of a capacitive sensor for your index finger you won't have quite the same fidelity as a Touch controller.

**Comment by AerowynX** [comment]
noticed some functions don't really work well like for example in this fishing thing it wants you to touch your wrist with your index finger but how the Vive controllers are shaped you can't really do that.. i had to basically come in at a very strange angle to touch it

**Comment by LibreVR** [comment]
Same thing in toybox. I may need to offset the hands a bit upwards to compensate for it.

**Comment by LibreVR** [comment]
@AerowynX Also, please make a separate issue, it's not really related to this one.

**Comment by AerowynX** [comment]
will do!
