### ISSUE TITLE
App running from non-trusted source (1971039)

### ISSUE THREAD

**Issue by omgware** [LibreVR/Revive#33]
Tested the v0.4, it works wonderfully with Dreamdeck and Lost, but Henry shows the error OnlineSubSystemOculus Error "Unable to launch app: App running from non-trusted source (1971039) as soon as you start it up.

**Comment by LibreVR** [comment]
Try installing Henry to your C drive in your Oculus Home folder. Closing as duplicate of Issue #6.

**Comment by omgware** [comment]
Only rebooting the pc solved the issue, because everything was already installed in C drive without symlinks.

**Comment by GreenBeanMech** [comment]
Reboot solved nothing for me, have a newer version of Oculus Home so I installed it initially in my I:\ drive but reinstalled to C:\ still nothing.

**Comment by LibreVR** [comment]
@GreenBeanMech Are you using `-Shipping.exe` for the injection? That is the main executable for Henry, you can find it in `oculus-henry\Henry\Binaries\Win64`.
