### ISSUE TITLE
Dirt Rally and Revive

### ISSUE THREAD

**Issue by duckson1989** [LibreVR/Revive#330]
so i have seen ppl playing this with the vive.. how ever after speeding hours and hours on trying to get it to work i must give up and post here and hopeing that some one have a fix for this :-)

this is what i get from the %appdata% txt thing:
Launched injector with: ReviveInjector_x86.exe /handle 356
Injecting process handle: 356
Injecting DLL: C:\Program Files\Revive\Revive\x86\openvr_api.dll
LoadLibrary found at address: 0x751a8500
Injecting DLL: C:\Program Files\Revive\Revive\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x751a8500
Injected dlls succesfully

and nothing happens afte i put the drt.exe onto the reviveinjetcer x64 or the x86 version :-)
hell i cant even start the game from the drt.exe any more :-)
any one have any ide on how to fix this or is this dirt with vive thing just dead :-)

edit: i use the steam version of dirt rally
my specs: amd black edtion x64
nivda gtx 1070 stryx oc edtion
16 gb ram 
and sadly the mobo i cant rember :-)

**Comment by LibreVR** [comment]
Don't use the injector. Install the [latest version](https://github.com/LibreVR/Revive/releases) of Revive, start SteamVR, right-click the Revive trayicon, select `Patch...` and then select the Dirt Rally executable.

After you've done that you can start Dirt Rally from Steam and it will work.

**Comment by wutangasLTU** [comment]
and how to do that to start the game from library? because I cant start the game from exe files its doesn't not open the game for some reason I don't know searching 3 days still no issues. help please

**Comment by LibreVR** [comment]
If you patch the executable like I explained you can start it from Steam like I said.

**Comment by wutangasLTU** [comment]
Don't use the injector. Install the latest version of Revive, start SteamVR, right-click the Revive trayicon, select Patch... and then select the Dirt Rally executable.
After you've done that you can start Dirt Rally from Steam and it will work. I'm readed fully,but still have no idea how to patch the executable,where is Revive "trayicon" I click revive in the vive dashboard there only shows oculus games,nothing else no menu nothing,where is revive trayicon is? and how to patch the executable of dirt rally? tell that please. thank you alot

**Comment by wutangasLTU** [comment]
Yeah I did what you sayd and now its finaly working,and looks cool,but another thing I don't know why is the camera shacking when turning head around? does it must be like that? on some others HTC vive games too,then turning head the screen is shacking vibrating or something whats the issue must be that? my pc is quide fast AMD 4.7ghz 16gb ram ddr3 GTX 1070. ssd 120gb

**Comment by duckson1989** [comment]
wow such a easy thing :-) and now its works and it runs fine on my pc no problem man you are awsome :-) thank you :-)
