### ISSUE TITLE
Bullet Train is not working

### ISSUE THREAD

**Issue by LLesGTU** [LibreVR/Revive#331]
When I try to start the game, I receive the message 

Failed to open descriptor file ../../../UE4Game-Win64-Test/UE4Game-Win64-Test.uproject .

**Comment by CarrotSurvivor** [comment]
me too

**Comment by LibreVR** [comment]
Fixed in commit f03eacd845009cc4b31b25a849d815786773bbe5. Will publish a new release soon.

For now, download the latest version of Revive that includes the automatic updater so you'll be notified when a new version is release: https://github.com/LibreVR/Revive/releases/tag/1.0
