### ISSUE TITLE
Framerate drop on Touch Tutorial Demo

### ISSUE THREAD

**Issue by blgrossMS** [LibreVR/Revive#332]
On my Oculus/Vive compliant PC, there is framerate drop in the scene when facing the robot.

**Comment by LibreVR** [comment]
What are your system specifications?

**Comment by blgrossMS** [comment]
GTX 970, 16 GB RAM, Intel Core i5 6600k processor, Windows 10.

**Comment by LibreVR** [comment]
Those are the bare minimum specs, you'd be relying on ATW with Oculus too I believe. You aren't using any render target multiplier settings are you?

**Comment by blgrossMS** [comment]
I am not using any render target multiplier settings. The bare minimum specs I thought was a GTX 960, and a worse off processor.

**Comment by LibreVR** [comment]
Please refer to my comment in issue #353 to report some performance data.

Closing this as a duplicate.
