### ISSUE TITLE
DIRT RALLY drt.exe wont open at all

### ISSUE THREAD

**Issue by wutangasLTU** [LibreVR/Revive#334]
Hello,everybody behind my research searching at least 3 days for the issue for my dirt rally,still have no issues,not found anything right, to suit my problem,the main thing is I can open Dirt rally only in steam library,otherwise if I trying to open the rally from exe. file nothing happends,even no logo to start nothing,apsolutely zero,drag exe to injector x64 or x86 nothing happends again,only I can start from library stars fine strigh way,but there is no way to work in HTC VIVE isn't it,so please help me if anybody know whats the problem is that,i tried RELOADED version with injector its works,but doesn't show anything on VR "HTC VIVE"

**Comment by LibreVR** [comment]
I don't support pirated games.
