### ISSUE TITLE
OpenGL High Error:1280 while launching Oculus Medium from revive in SteamVR

### ISSUE THREAD

**Issue by routb3d** [LibreVR/Revive#335]
Exact error is as follows.

[GL} OpenGL High Error: 1280 -- GL_INVALID_ENUM error generated.
Operation is not valid from the core profile.

Medium must now exit.

**Comment by CarrotSurvivor** [comment]
Crap :(

**Comment by LibreVR** [comment]
Fixed in commit 83d32e798af29d1d2046093c9718f6b4f0cbc635.

Will release a new version soon.

**Comment by routb3d** [comment]
Sweet!! Can't wait.. if this works, I'll invest in Quill and roll the dice again..
