### ISSUE TITLE
Superhot VR crashes after the first level

### ISSUE THREAD

**Issue by LibreVR** [LibreVR/Revive#338]
Superhot VR will launch successfully, but will crash as soon as you die or complete the first level.

The cause seems to be a DirectX error within OpenVR. Possibly related to: https://github.com/ValveSoftware/openvr/issues/78

I will update that OpenVR issue as I find out more about what's causing it.

**Comment by LukeAmer** [comment]
Looking forward to playing more Superhot 👍

**Comment by LibreVR** [comment]
Moving this to the next version so I can release an update for unspoken.

**Comment by LibreVR** [comment]
@LukeAmer More Superhot? The first level wasn't enough for you?

**Comment by LukeAmer** [comment]
@LibreVR there are only so many ways of killing one guy :(

**Comment by AlexTrott** [comment]
@LukeAmer Got to get more imaginative now, or play Arizona Sunshine till then

**Comment by LibreVR** [comment]
Well some updates:

1. The log contains the error `Overlay is using an unsupported compressed pixel format.Crash!!!` even though no compressed textures have been submitted as overlays.
2. If I disable overlays Superhot will actually progress to the next level, but nothing will be visible in the HMD, however at this point the game is saved and restarting Superhot works around that problem.

In other words, with some changes it's possible to progress, but you have to restart the game after each level.

**Comment by armor3r** [comment]
How are you disabling the overlays?

**Comment by LukeAmer** [comment]
hmm, better than nothing I suppose

**Comment by LibreVR** [comment]
@armor3r That requires a custom build, it's not really a viable solution. I'm still working on a proper solution.

**Comment by srt23** [comment]
Thanks for the update. Looking forward to playing:)

**Comment by LibreVR** [comment]
Removing the milestone, because this is a bug in OpenVR so we'll need to wait for a fix.

**Comment by BoldBigflank** [comment]
Is there a more accurate Issue in the openvr repo?

**Comment by Flyingcodfish** [comment]
I couldn't find a relevant issue on OpenVR, but overlays seem to be a pretty common source of problems over there.

**Comment by armor3r** [comment]
Looks like steam VR beta has a fix up for this. Testing presently.

**Comment by BoldBigflank** [comment]
Yep, SteamVR beta doesn't have the issue.

**Comment by burninpanda** [comment]
Latest SteamVR Beta (1481163974) but Superhot appears to lock up, with white background after initial 'training sequences' ? Have gun but can't do/see anything.

**Comment by srt23** [comment]
Working great. Really cool game!

**Comment by LibreVR** [comment]
While I'm no longer getting a crash, I do still have to restart after every level to get it to display on the HMD. Anyone else encountering this?

**Comment by armor3r** [comment]
Not experiencing that here.

**Comment by LukeAmer** [comment]
Working great for me.

**Comment by jnjustus** [comment]
@LibreVR  Played for about 2 hours straight on latest Revive update and latest SteamVR beta without any issues whatsoever.

**Comment by CarrotSurvivor** [comment]
steam vr beta fixed the crash! ths is huge news... steam devs are even supporting revive now YAY! (itts in the patch notes)

**Comment by armor3r** [comment]
@CarrotSurvivor To be fair, it was an OpenVR issue causing the crash, not an issue with Revive.

**Comment by konistehrad** [comment]
Yeah smooth sailing here on the SteamVR beta. Looks like OpenVR cleaned it up on the backend.

**Comment by LibreVR** [comment]
Though I haven't thoroughly tested it myself yet, I think we have more than enough confirmations.
