### ISSUE TITLE
Access Violation when calling ovr_GetAudioDeviceInGuidStr()

### ISSUE THREAD

**Issue by NeoToriyama** [LibreVR/Revive#34]
I'm not sure if anyone else had this issue, because I couldn't find a similar one on here, but I get this when I try to inject into Unity games:

Unity Player [version: Unity 5.3.3p1_828971bd30e1]

LibRevive64_1.dll caused an Access Violation (0xc0000005)
  in module LibRevive64_1.dll at 0033:dda6495d.

Error occurred at 2016-04-24_150546.
C:\Program Files\Oculus\Software\playful-luckys-tale\LT.exe, run by NeoToriyama.
51% memory in use.
8138 MB physical memory [3943 MB free].
23138 MB paging file [17502 MB free].
134217728 MB user address space [134217124 MB free].
Read from location 00000000 caused an access violation.

Context:
RDI:    0x00000000  RSI: 0x00000000  RAX:   0x80070490
RBX:    0x0075eec0  RCX: 0x00000000  RDX:   0x0075ee60
RIP:    0xdda6495d  RBP: 0x67b73a38  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0x0075ee20  SegSs: 0x0000002b
R8:    0x0075eca8  R9: 0x0075edf0  R10:   0x00000000
R11:    0x0075edf0  R12: 0x00000000  R13:   0x67b73c38
R14:    0xffffd8e4  R15: 0x00000002

Bytes at CS:EIP:
48 8b 01 ff 50 28 85 c0 78 bd 48 8b 54 24 40 41 

There's more data going down, but it's just numbers, any help would be appreciated. 
EDIT: The weird thing is, that all the Unreal engine games and experiences I've tried, are working perfectly.

**Comment by LibreVR** [comment]
There should be a log somewhere with a stack track, often this is dumped in a folder named after the date/time of the crash next to the executable. Could you upload that log file?

**Comment by NeoToriyama** [comment]
[output_log.txt](https://github.com/LibreVR/Revive/files/233730/output_log.txt)

**Comment by LibreVR** [comment]
Somehow it crashed while trying to query your default audio device, I'm not sure why though.

**Comment by NeoToriyama** [comment]
Hmm, that's weird, maybe uninstalling and reinstalling my audio drivers might fix the issue?

**Comment by LibreVR** [comment]
Unable to reproduce this issue, postponing it until the next version.

**Comment by gembox** [comment]
I had this issue as well. I disabled all playback audio sources except for the vive headset in the sound control panel and restarted everything. Worked fine on the next launch.

**Comment by LibreVR** [comment]
Interesting, perhaps it's overflowing the string buffer for the GUID.

**Comment by rob151515** [comment]
Also having this same issue on Windows 7. Logs match almost identically with the op. Played around with my audio devices (disabling/enabling) but no joy. Crashes every time.

**Comment by gembox** [comment]
So after the disable down to a single stopped working, I enabled all of my audio playback and recording devices in the sound control panel. Now it is working again.

**Comment by LibreVR** [comment]
Still unable to reproduce this error myself.

**Comment by LibreVR** [comment]
Is this no longer an issue for you? It may be related to the fact that there is no audio in Airmech.
