### ISSUE TITLE
Hand position doesn't work right in some games

### ISSUE THREAD

**Issue by AerowynX** [LibreVR/Revive#341]
I noticed in the fishing one it wants you to touch your wrist but because of the shape of the controller it's very difficult to do

**Comment by frank707** [comment]
Just finished a sessions of this game. I found it easier to use the thumbs up gesture to tap the red button on your opposite hand / arm.

**Comment by LibreVR** [comment]
Moving this to the next version so I can release an update for unspoken.

**Comment by LibreVR** [comment]
I'm a bit reluctant to move the hand forward, as that would break the little bit of hand presence there is. What I found is that it works pretty well if you just use the side of your index finger to press the button.

So just touch your wrist with the bottom of the Vive controller ring and you should be able to reach it.

**Comment by LibreVR** [comment]
I've changed the position a bit, though I don't really like the new position much it works better in games like toybox. We'll see how it works out, it's in the new release.
