### ISSUE TITLE
Unspoken is unplayable

### ISSUE THREAD

**Issue by zorro96** [LibreVR/Revive#344]
The language can be picked first time loading in game but after that it is unresponsive.

**Comment by LibreVR** [comment]
Will look into this tomorrow.

**Comment by r00tuzr** [comment]
Can't wait for this update thank you!

**Comment by LibreVR** [comment]
This is fixed in 8d65a984ba4a3855ece5d97ac94a8be53d7577df.

However there seem to be some problems with the player height, I'm working on correcting that now.

**Comment by LibreVR** [comment]
Fixed now 0865f5150241c8cd1ab3a672c4ad801d3e2b82eb.

Update incoming.

**Comment by r00tuzr** [comment]
Great i'm going to buy it! :)
