### ISSUE TITLE
Bullet Train descriptor file 1.0.1

### ISSUE THREAD

**Issue by Deapper** [LibreVR/Revive#345]
Tried a few thing, uninstalled revive. Installed 1.0.0 installed 1.0.1 several times. Shut down restart no success.

Error is showupshowup.uproject

Thx for any help

**Comment by frank707** [comment]
No issues here. I launch the game using the revive dashboard and it works great.

**Comment by CarrotSurvivor** [comment]
works for me... make sure to restart oculus home when you install new game

**Comment by Deapper** [comment]
Done that thx. Not sure what's going on

**Comment by lovemakerz** [comment]
ullet Train descriptor file error with 1.0.1 too :/

**Comment by Deapper** [comment]
Didn't notice it in the task bar. Clicked on update and got 1.0.1.1
