### ISSUE TITLE
Ripcoil New Online Issue

### ISSUE THREAD

**Issue by BubsonHD** [LibreVR/Revive#346]
Last night and today Ripcoil worked just fine, but I just noticed oculus home do an update I think and now if I go onto Ripcoil and try to go online via Quick play I get an error stating "An Oculus platform error occured; Please try again"

**Comment by BubsonHD** [comment]
I have just now tried it again and it is working again, Ill report back if this keeps happening

**Comment by CToss** [comment]
Seems to be a persistent issue, rebooting the game temp fixes this for a little while but after a match or two the error comes back.

**Comment by BubsonHD** [comment]
Yeah I am now finding this, I guess the issue may not be revive related.

**Comment by LibreVR** [comment]
It's probably a different form of the entitlement issue: https://github.com/LibreVR/Revive/wiki/Troubleshooting#im-getting-an-entitlement-error
