### ISSUE TITLE
Bullet Train Crash 

### ISSUE THREAD

**Issue by eXifreXi** [LibreVR/Revive#347]
Using the newest release of ReVive.

Installed Oculus Home and downloaded/installed Bullet Train.
In my Vive/Steam Dashboard, I can see the ReVive button and also Bullet Train.
After starting I encounter this:

http://puu.sh/sGjTH/ab6d650d7c.png

Anything I missed?

Cheers, eXi

**Comment by LibreVR** [comment]
Can you send me your logs from `%APPDATA%\Revive`? Just rename them to .txt files and drag them into the comment box here.

**Comment by eXifreXi** [comment]
I have two files in that folder, "ReviveInjector" and "ReviveOverlay", but the data inside doesn't really look like a log.
Any other directory where that could be stored? Does it change with the installation folder?

**Comment by AlexLogin0ff** [comment]
Game failed entitlement check! :(





[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/634850/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/634849/ReviveInjector.txt)

**Comment by eXifreXi** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/634864/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/634863/ReviveOverlay.txt)

**Comment by LibreVR** [comment]
@AlexLogin0ff Please check the troubleshooting guide first and don't post in unrelated issues: https://github.com/LibreVR/Revive/wiki/Troubleshooting

**Comment by LibreVR** [comment]
@eXifreXi It looks like you started the Oculus Avatar Editor, not Bullet Train. Please send the logs after starting Bullet Train.

**Comment by eXifreXi** [comment]
@LibreVR Oh! Didn't know the log overrides itself, here are the files after starting bullet train.

[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/634904/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/634903/ReviveInjector.txt)

**Comment by AlexLogin0ff** [comment]
I want to run: rift + razer hydra, previus programs launched

06.12.2016, 23:01, "Cedric Neukirchen" <notifications@github.com>:

**Comment by eXifreXi** [comment]
@LibreVR That's totally fine. Can it be anything related to my Computer, OS, Software?
I basically followed the Readme file on GitHub and tried starting it through the in Vive Overlay (ReVive) button. I can also not really start any other of the projects that should work based on the compatibility guide. (For example Henry or DreamDeck) They start, but the Vive stays in the normal SteamVR Room and the application doesn't get the head tracking.

**Comment by LibreVR** [comment]
@eXifreXi That definitely indicates something more fundamental is broken. What are your system specs including OS?

**Comment by eXifreXi** [comment]
@LibreVR Windows 7 64Bit
i5-3450 @ 3.10Ghz
16GB Ram
970GTX

**Comment by LibreVR** [comment]
I haven't tested on Windows 7 in a while, so the issue may be specific to Windows 7.

I'll try and see if I can reproduce the crash on a Windows 7 computer when I have access to one.

Or perhaps it's time to upgrade? ;)

**Comment by eXifreXi** [comment]
@LibreVR Ha, as much as I would love to play Rift games on my Vive, I won't update to Windows 10 for that :D
Would be nice if you could test that. I can provide you logs for trying Henry tomorrow.
Maybe they give you some information.

**Comment by LibreVR** [comment]
@eXifreXi You're going to have to upgrade at some point. Or will you hold out until Windows 11?

The logs aren't useful beyond this point. I will test on a Windows 7 PC and if I still can't reproduce it we'll start looking at some crash dumps.

**Comment by eXifreXi** [comment]
@LibreVR At some point, yes. But I've currently setup my system on 7 for Unreal Engine 4 and several other software and workflows and I'm still a bit afraid of Windows 10 breaking stuff.

Thanks for trying to fix it (:

**Comment by biosmanager** [comment]
I have similar problems with Bullet Train. Most of the time the game doesn't appear in the Vive itself and just runs on the desktop. I managed to get it working one time but after a while it disappeared again.
What's odd is that the game doesn't lose focus.

**Comment by LibreVR** [comment]
@biosmanager Which operating system?

**Comment by biosmanager** [comment]
@LibreVR Windows 10 64-bit, Steam running as admin

**Comment by Adkkid** [comment]
Also having the same problem. Bullet Train shows on the desktop, but not in the headset. I don't know if it's related, but when it loads on the desktop, it loads minimized without window focus.

**Comment by LibreVR** [comment]
What's your operating system?

**Comment by Adkkid** [comment]
@LibreVR Windows 10. i7 4770, GTX 1080, 8gb ram. Also running the Advanced Settings program for the Vive, version 2.0. https://github.com/matzman666/OpenVR-AdvancedSettings/releases

**Comment by LibreVR** [comment]
Ok, so it's definitely not a Windows 7-specific problem. Could you post your logs from `%APPDATA%\Revive`? Just rename them to .txt files and drag them into the comment box here.

**Comment by Adkkid** [comment]
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/644020/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/644021/ReviveInjector.txt)

**Comment by bcbfrancis** [comment]
@LibreVR Hello. Thank you very much for your effort. 

I have the same issue as @eXifreXi. I get the same error when starting bullet train. "Fatal error"

I have attached my logfiles. 


[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/648753/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/648754/ReviveOverlay.txt)

**Comment by Vivatokyo** [comment]
I have the same issue, I get the same error when starting bullet train. "Fatal error"
Win10
1080gtx

**Comment by bcbfrancis** [comment]
Dont know how i managed it but now it works.

Here are the things I did:

1.) after reading that it worked with 1.01 reinstalled revive. Than it worked. 
2.) then I installed the newest version of revive again. Now everything works.

Maybe just try to install it again, reboot and try to open it?

**Comment by Vivatokyo** [comment]
@bcbfrancis did you uninstall the lastest version and installed the 1.01? Or u just overwrite the installation?

**Comment by bcbfrancis** [comment]
First I had installed the latest version. But it didn't work for me. 

So I installed 1.01 and this seemed to work. Then I deinstalled Revive(1.01) again, and installed the latest version. Since than everything looks fine.

**Comment by Vivatokyo** [comment]
@bcbfrancis It doesnt work for me ... I am getting 
Failed to open descriptor file ../../../UE4Game-Win64-Test/UE4Game-Win64-Test.uproject . 
when i inject  (UE4Game-Win64-Test)
or
Fatal error
when i inject  (showup)

i tried 1.01.    and.  last version

**Comment by Vivatokyo** [comment]
@eXifreXi Hi , could u fix the fatal error?

**Comment by LibreVR** [comment]
@Vivatokyo Don't inject manually, always run Oculus Home games from the Revive Dashboard.

**Comment by Vivatokyo** [comment]
@librevr , thanks for the reply 
Same effect:

Fatal Error

**Comment by eXifreXi** [comment]
@Vivatokyo I haven't fixed it, but I also haven't checked back anymore.
Don't have much time and it seems like @LibreVR might be able to fix it if he/she gets more information about it by multiple crash cases.

If I have time, I will try to reinstall everything and try it again.

**Comment by LibreVR** [comment]
@Vivatokyo There's no other information? Just Fatal Error?

**Comment by Vivatokyo** [comment]
@librevr ok, i ll make it and where are located those files:
ReviveOverlay.txt
ReviveInjector.txt 

i want attach it also

thanks for the reply

**Comment by LibreVR** [comment]
They are located in `%APPDATA%\Revive`.

**Comment by Vivatokyo** [comment]
![capture](https://cloud.githubusercontent.com/assets/24572116/21292837/0304acda-c555-11e6-914a-71b6b0fcce88.PNG)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/659343/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/659344/ReviveOverlay.txt)


@LibreVR Thanks for your time

**Comment by LibreVR** [comment]
The logs look fine. For the next version I'll keep some debug symbols around so we can make a full process dump to debug the fatal error. I'll let you know when the next version is available so we can start the debugging process.

**Comment by Vivatokyo** [comment]
Ok thanks

**Comment by thedanroddis** [comment]
For what it's worth I have this exact problem and I'm not actually using Revive - using Oculus Rift and Oculus Home version of bullet train

Windows 10
Intel I5
GTX 1080
16GB RAM

May not be a problem with Revive and just a problem with the game.

**Comment by eXifreXi** [comment]
Hey @LibreVR
My 970 broke a few weeks ago, so I ordered myself a 1080 (Palit) and also a new Motherboard and CPU.

So the current setup is:

- i7-6700 3.4GHz
- 16GB DDR3 Ram
- Palit GTX 1080 8GB Ram
- ASRock H170 Motherboard
- Windows 10 (needed to update)

Now ReVive works with Bullet Train. I was even able to inject SuperHotVR (instead of using the In-VR launcher).

I know these are a lot of changes to my rig including reinstalling Windows (7 to 10), but I just wanted to let you know that it fixed the issues for me. So in the end, it could really be an unlucky combination of hardware and software.

**Comment by Armada651** [comment]
@eXifreXi Good to hear you fixed it, but like you said, there's not a lot we can learn from that. It was already clear that this only happened on some setups. Likely because of some kind of configuration of the OS or SteamVR that crashes Revive.

**Comment by Vivatokyo** [comment]
Still fighting with the ue4 fatal error :(

**Comment by Vivatokyo** [comment]
Ok I fixed it!
If you have Fatal Error problem do this:
1-Uninstall Revive
2-Uninstall completely Oculus software
Follow this https://www.youtube.com/watch?v=2WWrQncMNqs&app=desktop

(3-Install "Vive Setup" if you don't have it) *This one I don't know if it helps but it is what I did, I had only SteamVR and basic Vive drivers installed

4-Install Oculus Setup 
Create an account/sign in

When you are asked for 
  Rift or Rift&Touch 
SELECT RIFT&TOUCH! 

When they say plug the cables, skip

Once it is installed download Bullet Train
(In Oculus settings you also check allow unknown, I don't know if it helps...)

-Download and Install Revive

-Back to Oculus check if the game is downloaded then, go to settings, beta, restart... wait
Once restart you can close Oculus.

-Launch Revive program(.exe) and It ll launch also steamvr 
Put on ur Hmd 
Select Revive tab and Lauch Bullet Train

I hope it helps

I have to check the other UE4 games that gave me Fatal Error/Crash... But I think It will work

**Comment by Dragoboss** [comment]
Issue appears solved. Any further regarding issues please re-port a new ticket.
