### ISSUE TITLE
DiRT Rally not starting + general question

### ISSUE THREAD

**Issue by awesometradeepvp** [LibreVR/Revive#348]
- I have Installed the lastest Revive Version
- I installed the latest Version of Oculus Home ( but i dont understand what it does ... please explain why i have to use it on a steam game, and how do i use it ... just start it or... ?)
- Revive tab IS visible in VR ... I see 1 game from Occulus home i think... and 3 random games. but not dirst Rallye
- used the 32-Bit Patcher from the compatibility List (and every other possible patcher  ... like x64 and the normal x86 one)
- Pull the Geme.exe on the revivepatcher
- Game does not launch
- (tried rebooting, different reinstallations of game/revive/Ocuulus Home) running out of options/knowledge

Please help me ;) I would love to race in VR

Log files here:

> libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: C:\Program Files\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: C:\Program Files\Oculus\Software\
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle playful-luckys-tale_assets

> Launched injector with: "C:\Program Files (x86)\Steam\steamapps\common\DiRT Rally\ReviveInjector_x86.exe" "C:\Program Files (x86)\Steam\steamapps\common\DiRT Rally\drt.exe"
Creating process: C:\Program Files (x86)\Steam\steamapps\common\DiRT Rally\drt.exe 
Injecting DLL: C:\Program Files (x86)\Steam\steamapps\common\DiRT Rally\x86\openvr_api.dll
LoadLibrary found at address: 0x763a4977
Injecting DLL: C:\Program Files (x86)\Steam\steamapps\common\DiRT Rally\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x763a4977
Injected dlls successfully

**Comment by ValakhP** [comment]
Hello. Same thing here. I have done all as it's described in another issue themes, but nothing helped.
When I start game from steam after patching it, it opens but only on PC. Nothing happened in glasses. Moreover version in game is 1.22 (in the top left corner). Is it because of patching? 

Here is my log:

> libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: C:\Program Files 2\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest: C:\Program Files 2\Revive\app.vrmanifest
Loaded manifest: C:\Program Files 2\Revive\support.vrmanifest
Oculus Library found: C:\Program Files 2\Oculus\

**Comment by LibreVR** [comment]
Those instructions are all outdated, install [the latest version of Revive](https://github.com/LibreVR/Revive/releases) and follow these instructions: https://github.com/LibreVR/Revive/wiki#steam-games

**Comment by ValakhP** [comment]
I followed this instruction but it do nothing. Game opens on desktop, but nothing happens in glasses.

**Comment by LibreVR** [comment]
What if you use the `Inject...` option?

**Comment by ValakhP** [comment]
Here is the log after injection:

> Launched injector with: ReviveInjector_x86.exe /handle 352
Injecting process handle: 352
Injecting DLL: C:\Program Files 2\Revive\Revive\x86\openvr_api.dll
LoadLibrary found at address: 0x75d18500
Injecting DLL: C:\Program Files 2\Revive\Revive\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x75d18500
Injected dlls succesfully
> 

Injection has no effect. Nothing happened.

**Comment by frank707** [comment]
I was able to get it to work successfully. Did you remove the files from the previous revive injector from the Dirt Rally directory?

**Comment by ValakhP** [comment]
Yes, I did. I'm worreing why the hell it writes 1.22 in the corver if I have 1.23. Well... I'll try to reinstall the game. Hope it will help somehow.

**Comment by wutangasLTU** [comment]
Dirt rally graphics on VR htc vive looks horrible like in sega mega drive,like in automats in shop with dendy drive graphics horrible even set on maximum

**Comment by Rojoyinc** [comment]
I played it last night (works on my older revive. (I don't update until
things are stable).
YES the graphics are quite poor.  I only bought it because some guy on
youtube was doing nuts over it and how good it looked.
I JUMPED ON IT... = (    I've since seen his other videos and he goes NUTS
over how good everything he reviews is. (recently bullet train).
I don't get sucked in any more.

At least I got this on steam and figure should they release VIVE support -
I'll get the update free.

**Comment by ValakhP** [comment]
Well, I'm pretty confused. I've reinstall the game and try to run it without patching just to look how it works. And it ran perfectly in vr without revive. But I'have to download 2Gb update right after installation. May be there was native suppot, I don't know. Anyway everything is ok. 

Thank you everybody.

**Comment by Rojoyinc** [comment]
ODD - it's not suppose to have VIVE support yet.  It works for me with
revive...

**Comment by rtamotorsports** [comment]
I'm having a issue with dirt as well even when I use older patches, i get a warning on my screen asking me to put my oculus headset back on when I stop moving my head. My game on any graphics setting even ultra low stutters every 3 seconds until freezing where it shows the game ghosting over the compositor. Really frustrating. I have a gtx 1070 if it helps.

**Comment by LibreVR** [comment]
@rtamotorsports Then you are not using a Vive headset.

**Comment by rtamotorsports** [comment]
I am using a vive, it's all I own, I have a YouTube channel revolving around simracing and vr, was going to post a video on this because it's got me so confused.

**Comment by LibreVR** [comment]
That's strange, the Vive headset has a proximity sensor, it should never report the headset as idle if you have it on. Make a separate issue, as this one is purely about not being able to boot Dirt Rally, which you are able to.

**Comment by rtamotorsports** [comment]
OK will do sorry

**Comment by Vemaster** [comment]
I did all these things: https://www.reddit.com/r/Vive/comments/58i5gj/how_to_fix_revive_for_dirt_rally/ 
But it just launches on desktop for me. I tried older (even <1.0) versions of the revive and still - no luck.

**Comment by eric-schleicher** [comment]
FYI.   It looks like the needed changes to support DiRT are in the normal release.  At this point (1/16/2017) if you follow the *normal* Steam install instructions (not the special patch on this page) everything should work just fine.
