### ISSUE TITLE
how do i enable auto updater? cant find it anywhere

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#349]
pls help... what do you mean by right click tray icon? how do you right click? and what is the tray icon hahaha... thanks!

**Comment by LibreVR** [comment]
The second time you start SteamVR Revive will ask whether you want to enable auto-updates.

A tray icon is an icon that's in the bottom-right of your taskbar on your desktop. Some of them are hidden, so you have to press the little arrow that points up. There you will see the Revive icon which contains some options like manually checking for updates.
