### ISSUE TITLE
War Thunder: targetting reticle bugged

### ISSUE THREAD

**Issue by JamieRoling** [LibreVR/Revive#35]
I know it's not exactly an Oculus Home game, but it is a great Oculus only (for now) game. It's really fun to play it's just a shame that the targetting reticle is very bugged out when using Revive 0.2.1-0.4.

**Comment by LibreVR** [comment]
Can you make a screenshot of that bug?

**Comment by JamieRoling** [comment]
Problem is you don't see it so not really :(. It only shows up in one position near the very center.

**Comment by gormanj** [comment]
I think this may nothing to do with revive and more either with the game's programming and convergence issues. The forum seems to have a screenshot of this problem.

http://forum.warthunder.com/index.php?/topic/238174-id0028537-080515-oculus-rift-and-buggy-patch-170/

**Comment by LibreVR** [comment]
I agree that this is likely a problem in the game itself that has nothing to do with Revive.
