### ISSUE TITLE
Revive Not Working?

### ISSUE THREAD

**Issue by TheTrillyG** [LibreVR/Revive#352]
Its Detecting only Dreamdeck and nothing else other than the demos? The other games are in the same folder. I have reinstalled Revive and Oculus home many times now and it doesn't change anything.

**Comment by LibreVR** [comment]
Can you post your logs from `%APPDATA%\Revive`, just rename them to .txt files and upload them here by dragging them into the comment box.

**Comment by TheTrillyG** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/635375/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/635377/ReviveOverlay.txt)

**Comment by LibreVR** [comment]
> Oculus Library found: D:\\

It looks like you installed your Oculus Library in the root of your D: drive. It seems Revive has a bug that doesn't allow that. Try reinstalling Oculus home and setting your library to something like: `D:\Oculus`.

**Comment by TheTrillyG** [comment]
Fixed thank you!
