### ISSUE TITLE
Single eye in Medium

### ISSUE THREAD

**Issue by jasnahk** [LibreVR/Revive#354]
Only able to see through my left eye in Oculus Medium. 

Intel i5-6402P 
AMD RX 480

**Comment by LibreVR** [comment]
This may be an AMD-specific issue, I'd like to hear from some other AMD users if they encounter this too.

**Comment by aurialLoop** [comment]
There are users on the oculus medium forum: [https://forums.oculus.com/community/discussion/comment/464337/#Comment_464337](https://forums.oculus.com/community/discussion/comment/464337/#Comment_464337) that are experiencing AMD related problems similar to what was reported above.

**Comment by jasnahk** [comment]
This is a non-Revive issue. This is AMD firmware issue and is resolved with v 16.11.5

per https://forums.oculus.com/community/discussion/44995/graphical-glitch
