### ISSUE TITLE
Entitlement check fails when using an Oculus Rift

### ISSUE THREAD

**Issue by Quetzhal** [LibreVR/Revive#360]
I realize I'm not exactly the typical use-case, here, so feel free to ignore this, heh. I doubt there are many users with my same issue. 

I decided to try ReVive with the Razer Hydra emulator to play Touch games. Complicated, I know, but I got impatient. It seems that regardless of restarting the Oculus service, I consistently fail the entitlement checks - I've also tried a full PC reboot.

In addition, Superhot does not work beyond the first level - even then, there's some very dizzying warping when you look around, Medium does not boot, and Ripcoil tells me I failed the entitlement check. First Contact and the Touch tutorial both work. Haven't tried anything else.

**Comment by LibreVR** [comment]
I will look into better compatibility with alternative setups at some point, but I think you understand that the Vive headset is the priority right now.

**Comment by LibreVR** [comment]
Also, technically someone could use the same injection method as Revive to just inject the hydra controllers instead of replacing the entire runtime.
