### ISSUE TITLE
"Revive did not start correctly , Unable to set the auto-launch flag, please report this to the Revive issue tracker"

### ISSUE THREAD

**Issue by jmkraap** [LibreVR/Revive#361]
I get the error message shown in title when starting Revive dashboard. Games seem to work despite this though (tried Bullet Train).

EDIT: I solved the error by reinstalling Revive. On next restart, Vive tab was gone for some reason but doing one more restart I had both the Vive tab and Revive tab visible in SteamVR.

**Comment by LibreVR** [comment]
Thanks for reporting it, I'll make the auto-launch flag setting a bit more aggressive in the next release.

**Comment by kvdv99** [comment]
I'm curious :  how can you toggle the auto-launch flag of Revive?

**Comment by LibreVR** [comment]
You can't, Revive turns it on during setup and checks it during launch.

**Comment by kvdv99** [comment]
Ok, good to know, thanks

**Comment by Armada651** [comment]
Fixed in commit ffc50a73ca6d87743b2fe1b4e8c2bc7ca94f01f5.
