### ISSUE TITLE
Eve Vakryie no sound on vive

### ISSUE THREAD

**Issue by sam890306** [LibreVR/Revive#362]
Hi,

I run oculus version of eve vakryie, everything works fine, except there is no sound in game. Any ideas?

**Comment by LibreVR** [comment]
Check your default audio device, is it set correctly to the Vive audio device while playing?

**Comment by sam890306** [comment]
it is the default audio, and other software run just fine and has audio in vr mode. expect this one. I try to uninstall oculus, then reinstall it, still same issue. Is there a way to perform a clean install for everything?

**Comment by LibreVR** [comment]
This seems to be an issue with the Vive version too: https://www.reddit.com/r/Vive/comments/5hiv1b/eve_valkyrie_vive_no_audio/

**Comment by sbawden77** [comment]
has anyone figured out what the cause of the no audio issue is? I'm not having any luck getting mine to work either.

**Comment by LibreVR** [comment]
Can you try clicking the EVE Valkyrie window on the desktop? It may be out-of-focus.

**Comment by sbawden77** [comment]
So my oculus version, the sound works fine. But the vive version has no sound at all. I've checked the focus on my desktop, my sound settings are correct, still nothing. I've contacted ccp for help, but they haven't figured it out yet.

**Comment by LibreVR** [comment]
@sbawden77 When you say "the vive version" you mean the one that's sold on Steam right? You're not playing the Oculus Home one?

**Comment by sbawden77** [comment]
yes. the steam store version. it lost sound. the oculus store version works fine.

**Comment by Armada651** [comment]
EVE: Valkyrie has since added support for the Vive to the Steam version.
