### ISSUE TITLE
can't start games

### ISSUE THREAD

**Issue by AbdulTh3rd** [LibreVR/Revive#363]
game say you need an Oculus Rift

**Comment by LibreVR** [comment]
Try rebooting

**Comment by AbdulTh3rd** [comment]
try rebooting what

**Comment by AbdulTh3rd** [comment]
I tried rebooting the Oculus store but nothing happened

**Comment by AbdulTh3rd** [comment]
I have another issue the body VR opens but I don't see anything on my HTC Vive it just keeps loading

**Comment by LibreVR** [comment]
I mean rebooting your PC.

**Comment by AbdulTh3rd** [comment]
okay I'll try doing that

**Comment by AbdulTh3rd** [comment]
thanks so much I never thought of rebooting my computer so can I donate

**Comment by AbdulTh3rd** [comment]
how can I donate

**Comment by LibreVR** [comment]
No need for donations, but if you want to you could donate to my favorite charity, the EFF.
