### ISSUE TITLE
Revive Not Working

### ISSUE THREAD

**Issue by gstraight** [LibreVR/Revive#364]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/642541/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/642545/ReviveOverlay.txt)

**Comment by LibreVR** [comment]
These logs look fine, what are your system specs? Are you using an HTC Vive?

**Comment by gstraight** [comment]
Windows 10 Home
i7-4770k cpu @3.5ghz
Installed memory 8 gig
EVGA 980ti
Yes using a HTC-Vive

**Comment by gstraight** [comment]
I tried moving the Revive folder into the folder for Lucky's Tale and using
Revive Injector x64 to launch the executable for Lucky's Tale. The program
ran and I was able to use an Xbox controller to play the game. I tried the
same with Bullet Train and when I did that , the game launched on my
monitor and I could control the monitor look using the mouse but the game
did not show up in the Vive headset. Uninstalled Revive and reinstalled
Revive again. As before I can see the Revive circle and open it and see the
game icons inside but I can not run any game, Using the controller pointer
I just get the "bonk" sound and no results.

**Comment by LibreVR** [comment]
Can you send me those logs again after triggering the "bonk" sound?

**Comment by gstraight** [comment]
Here ya go, thanks for helping.

**Comment by LibreVR** [comment]
Did you attach them to you e-mail? I don't think github accepts that.

**Comment by gstraight** [comment]
OK to the github

**Comment by gstraight** [comment]
OK, here ya go.
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/644673/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/644675/ReviveOverlay.txt)

**Comment by gstraight** [comment]
OK, hope I sent the files correctly.

**Comment by gstraight** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/644679/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/644680/ReviveOverlay.txt)

**Comment by LibreVR** [comment]
> Failed to launch application: revive.app.oculus-dreamdeck-nux (VRApplicationError_LaunchFailed)

These logs indicate a problem with SteamVR, I think there's a problem with your SteamVR installation. Try reinstalling SteamVR.

**Comment by gstraight** [comment]
I reinstalled Steam shift back to SteamVR -  Revive programs would not run, Shifted back to SteamVR Beta latest version and Revive programs would not run. You did see that with Lucky's Tale to run using the injector in the game folder method? Is there a way to force SteamVR beta to update to ensure have latest?
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/644817/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/644818/ReviveOverlay.txt)

**Comment by gstraight** [comment]
I decided to start Steam with admin privledges and all worked. Thanks for
your efforts in my behalf. Revive works great.
