### ISSUE TITLE
Dashboard Gray

### ISSUE THREAD

**Issue by Hardmaninc** [LibreVR/Revive#365]
HI 

I have just installed revive and the dashboard is just gray but when i use the controller i can select an app and it opens but i cant see what i am selecting please help

Thanks

**Comment by LibreVR** [comment]
Please upload your logs from `%APPDATA%\Revive` you can just rename those files to `.txt` files and drag them in the comment box here.

**Comment by Hardmaninc** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/642629/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/642628/ReviveOverlay.txt)

**Comment by Hardmaninc** [comment]
Thanks

**Comment by LibreVR** [comment]
Your logs look fine, you shouldn't be having any problems with the dashboard. Please try rebooting SteamVR or reinstalling Revive.

**Comment by Hardmaninc** [comment]
done and done and still the same :(

**Comment by Hardmaninc** [comment]
Turns out its steam vr update bug that you update stations and when you do it breaks

**Comment by Hardmaninc** [comment]
I have spoken to HTC who confirmed this
