### ISSUE TITLE
Back to Dinosaur Island not working

### ISSUE THREAD

**Issue by Sp4iK** [LibreVR/Revive#368]
Hi, I'm trying to run this demo through Revive. I know that this is supposed to only run on DK2 'cause its old sdk, but I've also installed LibOVRWrapper.

Things are that launched through Stem wont load on the hmd, then if I try to patch it same thing happens. Finally if instead of patching I inject it, it would load correctly and look okay for a moment in the menu and when the jungle scene is loaded but then the left image goes bad.

Do you think this is related to Revive or maybe does it have to do with the wrapper? Oculus people seem to play it correctly through this.

**Comment by LibreVR** [comment]
Sorry, I don't support the LibOVRWrapper, if it works then that's great, but if it doesn't I'm not going to try and fix it.

If anything is going to be done about DK2 compatibility, then Revive itself should be made DK2-compatible instead. I'm not really interested in doing that though, supporting the CV1 SDK is difficult enough for me.
