### ISSUE TITLE
several games no longer working

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#369]
It's been a while since I've tried opening these, but although many games are still working, these are not:
   airmech command
   the climb
   defense grid 2
   feral rites
   henry
   within
Too bad because I love this titles!

I have no idea how or where to start troubleshooting this?

**Comment by LibreVR** [comment]
Which version of Revive are you using? I specifically fixed airmech command.

Are you still on Revive 1.0 Preview 3?

**Comment by LibreVR** [comment]
These titles all still work for me, closing as invalid.
