### ISSUE TITLE
Cannot launch without Rift

### ISSUE THREAD

**Issue by gnguralnick** [LibreVR/Revive#370]
I recently installed revive and Oculus home, and have home running as an administrator. When I tried launching the touch tutorial from inside the Vive, I got a "cannot launch this application without an oculus rift" error. I have tried restarting the oculus software and services as the troubleshooting page said, but it did not help. Any sugggestions?

**Comment by LibreVR** [comment]
Try rebooting your PC.

**Comment by gnguralnick** [comment]
Wow. Can't believe that I didn't think of that. It works now, thank you!

**Comment by LibreVR** [comment]
I'll add that to the troubleshooting page.
