### ISSUE TITLE
Touch emulation angles are off in at least superhot VR & Super Pirate Trainer

### ISSUE THREAD

**Issue by xnurt** [LibreVR/Revive#371]
Haven't tried other games yet, but here's the issue:

If you hold the vive grip "naturally" and aim at a target, the gun tilts to the side (to the right - making me need to aim slightly to the left). I'm guessing it's due to the nature of controllers being shaped differently and oculus making different assumptions about the grip than the vive controllers.

It's really obvious in super pirate trainer since that game exists in both steam and oculus. 

Is there a way to re-calibrate or change these angles in a config somewhere?

**Comment by LibreVR** [comment]
I'm still refining the angles, but you can customize them if you want. You'll need to edit your `steamvr.vrsettings` and add a `revive` section with the following options:


     "revive" : {
        "TouchPitch" : -28.0,
        "TouchYaw" : 0.0,
        "TouchRoll" : -14.0
     },

I think you'll mainly be interested in the `TouchYaw` option.

**Comment by xnurt** [comment]
Excellent,  thanks! If I find settings I like (and ones that work for several Oculus touch games) I will post them here.

Is there anyway to make these settings dynamically update, or must I restart the game each time I adjust them?

**Comment by LibreVR** [comment]
Out of performance concerns you need to restart Oculus. I might make the dynamically update once we actually have an option panel.

**Comment by xnurt** [comment]
From your having messed with this, how likely is it that TouchX TouchY TouchZ also need to be adjusted? Do the touch & vive controllers share an anchor point or is it possible the fundamental position is off slightly?

The reason I ask is I got the settings almost perfect in space pirate trainer (adjusting roll and yaw both, actually), but when I tested in Superhot VR it's not even close, wihch makes me want to zero out everything and take it step by step. Also when I pause in the system menu, I'm able to see both the vive controller and the in-game model at the same time, and the handle of the gun doesn't match up with the shaft of the vive controller model. I think this is mostly roll settings, but maybe some slight position offset too.

Or maybe different games just require different settings.. it's unlikely game developers all use a consistent/common point of reference.

**Comment by LibreVR** [comment]
That's the same problem I've been running into. I don't have an answer ready for any of those questions, though the position should definitely not be affected.

I'm going to look into the way I'm calculating the rotation matrix, it's possible I did something wrong there.

**Comment by xnurt** [comment]
OK - that makes me feel like I'm less crazy, as I could not get settings that worked for both games -- but I did find settings that I think are almost perfect for both.

Posting them here in case they are helpful to anyone else.

**Space Pirate Trainer:**
 "revive" : {
    "TouchPitch" : -28.0,
    "TouchRoll" : 0.0,
    "TouchYaw" : -5.0
    }


**Superhot VR:**
"revive" : {
    "TouchPitch" : -40.0,
    "TouchRoll" : 0.0,
    "TouchYaw" : -11.0
    }


I'm a competitive shooter and rely on intuition a lot -- these settings felt the most natural for me, and they were also most lined-up with the SteamVR model in the system menu. Note that the roll might be slightly off, but once I found gun accuracy that I liked I stopped messing with it. The angle of the grip of the gun matched up enough with the controller in Superhot that I could't tell a difference. With space pirate trainer the difference was small, but noticable when you use the system menu to see both the vive controller and in-game model overlayed.

**Comment by xnurt** [comment]
I was testing superhot with the entry level.. but they seem to use inconsistent configuration between the shotgun, uzi, and pistol (or something else is wrong with Revive's calculations/emulation). 

After trying the other weapons, I'm using something closer to Super Pirate Trainer's yaw settings.

**Comment by calibban** [comment]
there is a way to put  touchs closer to the wrist?

**Comment by LibreVR** [comment]
Setting `TouchZ` to something like `0.056f` will do that, but you'll be unable to touch your wrist in some games that require it.

**Comment by calibban** [comment]
thanks i' ll try that

**Comment by jaorg1234** [comment]
Same issue in Dead and Buried, the following values are coming close to the normal Vive grip for guns:

>       "TouchPitch" : -55.5,
>       "TouchRoll" : 0,
>       "TouchYaw" : 0

If anyone got better tweaking values, please post it here! Maybe that should be a community effort and then everyone can change its value to their own preference in the future for each game separately.

**Comment by xnurt** [comment]
I'm currently updating settings pretty regularly between space pirate trainer, superhot, and The Unspoken.

+1 for a wishlist feature in the future to be able to store these settings per-game (unless we figure out an issue with a base calculation somewhere and somehow end up with better default settings for all oculus games).

**Comment by jaorg1234** [comment]
Would you mind posting your settings for The Unspoken? That would make my life easier before delving into that game

**Comment by xnurt** [comment]
I'm still refining them - and since this deals with "throwing" objects more often I was a bit less picky (didn't feel as "wrong" as gunplay did):

**The Unspoken**
"revive" : {
"TouchPitch" : -28.0,
"TouchRoll" : 0.0,
"TouchYaw" : -7.0
}

Pretty sure my yaw could use more adjustment, though because there's a learning/skill curve with throwing, I'm trying to not change it for a while to see if I get used to it.

**Comment by LibreVR** [comment]
Please note that I'm working together with OpenVR Advanced Settings to provide an options panel where you can edit these values on-the-fly in-game: https://github.com/matzman666/OpenVR-AdvancedSettings/issues/19#issuecomment-268292034

So you may want to wait until that is ready before you spent too much time restarting the game to change these values.

**Comment by xnurt** [comment]
Awesome, that'll help a ton.

Bit of a noob question - do I need to download or enable something to access OpenVR menus/settings you're referring to, or is it bundled with SteamVR? OpenVR is just an SDK, right?

**Comment by LibreVR** [comment]
Yes, this is a separate application. I'll explain it in detail when the Revive options tab is done.

**Comment by lghtanddrk** [comment]
Any idea when the options panel will go live?  Will it have an easy adjustment for gun angle and sticky button control?  Would love to see the ability to save and reload configs for frequently played games. By the way, what an incredible job you're doing with Revive.  Thank you so much!

**Comment by Armada651** [comment]
It's gone live an hour ago, so download the latest version of OpenVR-AdvancedSettings and be sure to install the Revive 1.0.4 update.

**Comment by lghtanddrk** [comment]
Thanks.  Just installed it and it works great.  If I create a new profile for each game and then hit apply after making my settings I see that it updates the settings globally across all profiles. Do you know if OpenVR-AdvanceSettings supports the ability to save a profile for each game or am I just doing something wrong?

**Comment by Armada651** [comment]
Now that these angles are user-configurable I'm going to close this issue.
