### ISSUE TITLE
Can't change graphic options in "the climb"

### ISSUE THREAD

**Issue by whit0r** [LibreVR/Revive#375]
the trigger issue is solved somehow - it works perfect, great game. But in the options menu i can't move any of the sliders to adjust the aliasing or ssao and all the other settings. Don't know if its a revive issue or of the game itselft, because some users in the crytek-forums seem to have the same problems.

**Comment by LorkHang** [comment]
Did you try the thumbstick to adjust the sliders?

**Comment by whit0r** [comment]
Yeah, i dont see any sliders at all. It just allows me to uncheck/check the two checkboxes. By thumbstick you mean trackpad left/right?

**Comment by LorkHang** [comment]
yes, the mapped thumbstick on the touchpad, touch that area and slide left/right to toggle option. 
You can point with right hand then use left hand thumbstick to do this.

**Comment by whit0r** [comment]
Still doesnt work, i tried pointing at the setting and sliding on the other hand. It looks like there are no sliders there

**Comment by LorkHang** [comment]
It seems reinstalling the game could solve your problem.
https://www.reddit.com/r/oculus/comments/5hcktv/graphics_options_in_the_climb_not_working/

**Comment by whit0r** [comment]
Yeah, worked. After reinstalling all options are available. Thanks bro!
