### ISSUE TITLE
Add an option to ignore the proxymity sensor

### ISSUE THREAD

**Issue by rtamotorsports** [LibreVR/Revive#376]
So with the new version of revive the updated dirt rally game and updated non-beta drivers for my HTC Vive I'm having issues of stuttering that seems to be occurring every 3 seconds while in gameplay. Also everytime I hold my head still the mirrored game window on the monitor gray's out with an error that states to Place Oculus Rift back on head to continue gameplay, and it tends to crash with half the gameplay ghosted on the compositor. I reverted back to Old revive drivers with the same result. I've been using revive with this title for a long time never had this issue before I'm using a GTX 1070 for reference. Also this occurs with all graphical settings on ultra low with no supersampling on. 

I have not tried to uninstall and reinstall game but will tomorrow. I seen this issue being brought up once more on the steam forums from a different user. 
Thank you for any help!

**Comment by rtamotorsports** [comment]
https://youtu.be/z425whz0H8k I made a video showing some of the issues I'm having for reference.

**Comment by LibreVR** [comment]
I will add an option to turn this detection off, but it should not be happening. Either you have a pre-consumer version of the Vive or there is something broken in your setup.

**Comment by rtamotorsports** [comment]
Oddly enough this is the only title I'm having poor performance in... Assetto Corsa and other oculus titles work great. Also when the released 1.0 build happened I had awesome performance. It wasn't until recently I can't use asynchronous reprojection. Any help would be awesome. Thanks!!

**Comment by LibreVR** [comment]
Also note, that the headset could potentially turn off during gameplay if you don't trigger the proximity sensor for 15 minutes.

**Comment by LibreVR** [comment]
Also, if you have performance problems, please create a new issue and follow these instructions to report performance data: https://github.com/LibreVR/Revive/issues/353#issuecomment-265434808

**Comment by Eueyj79** [comment]
I just wanted to check in on  this as well, I could use this feature. Is there any update?

**Comment by Armada651** [comment]
Not yet, this feature has been in my backlog for a while. It's not that difficult to add, just waiting until the next minor release.

**Comment by Eueyj79** [comment]
I'm happy to test it or contribute to the beer fund ;-)

**Comment by Armada651** [comment]
Like I said that's not the problem. Just waiting until the next release.

**Comment by Armada651** [comment]
Fixed in 28c610339a2545ec2ed93fc86bc8a6e6a29be069, will be part of the next release.

**Comment by Armada651** [comment]
You're in luck, I just pushed an update and it includes the option.

**Comment by rtamotorsports** [comment]
how do you access the option, i cannot find it?

**Comment by Armada651** [comment]
Add `IgnoreActivityLevel : false,` to the `revive` section of your steamvr.vrsettings.

Or wait until OpenVR-AdvancedSettings adds it to the Revive settings tab.
