### ISSUE TITLE
Haptics / Vibrations (Dead and Buried)

### ISSUE THREAD

**Issue by hel1011** [LibreVR/Revive#377]
First of all, Revive is amazing.  One quick issue/question.  I just purchased Dead and Buried and noticed there is no haptics on the Vive controller.  I am currently using the sticky/toggle grip in my steamvr.vrsettings which works great/is a must in this game. Is there another line of text I can insert that would enable haptics?

**Comment by LibreVR** [comment]
Sounds like you have an old version, haptics are already fully supported in 1.0.3. You can download the latest version here: https://github.com/LibreVR/Revive/releases

**Comment by hel1011** [comment]
I have the latest version (1.0.3). Do you think it could be that I installed it using the updater instead of uninstalling and then installing the latest version?

**Comment by LibreVR** [comment]
Nah, Any way is fine, as long as you install it in the same location.

Do you get any haptic feedback while playing the First Contact demo?

**Comment by hel1011** [comment]
I did yesterday.  I can re-confirm tonight.  I also had haptic feedback in Bullet Train yesterday.  It was just Dead and Buried that did not have it but that was this morning.

**Comment by hel1011** [comment]
I confirmed that Haptics works in all games except for Dead and Buried. Any advice?

**Comment by Dragoboss** [comment]
Sounds like this at the time was a game specific issue and not Revive related.
Since its two years old I'll close the ticket.

If you find any problems that you think are Revive related with haptics in the future please make a new ticket..
