### ISSUE TITLE
Revive dashboard covers oculus game (lucky tales)-the game loads but looks transparent while the dashboard is open.

### ISSUE THREAD

**Issue by dondimadozen** [LibreVR/Revive#378]

**Comment by LibreVR** [comment]
That title is way too long and doesn't describe the issue in enough detail.

**Comment by dondimadozen** [comment]
I downloaded Lucky Tales and when I start it from the Revive menu it loads and start but looks transparent or better yet see through on my Vive headset. It appears in full color on my computer monitor when I take my headset off. However, the Revive dashboard remains open. I'm guessing I have to close the revive dashboard but I don't see a close or minimize button. The game is functional as in I can use my gamepad to navigate the actual game menu but the dashboard remains on top of it and it still looks transparent.
