### ISSUE TITLE
Revive dashboard covers the oculus game (lucky tales) while playing.

### ISSUE THREAD

**Issue by dondimadozen** [LibreVR/Revive#379]
I downloaded Lucky Tales and when I start it from the Revive menu it loads and start but looks transparent or better yet see through on my Vive headset. It appears in full color on my computer monitor when I take my headset off. However, the Revive dashboard remains open. I'm guessing I have to close the revive dashboard but I don't see a close or minimize button. The game is functional as in I can use my gamepad to navigate the actual game menu but the dashboard remains on top of it and it still looks transparent.

**Comment by LibreVR** [comment]
I assume you're not using an HTC Vive then? If you're using an Xbox gamepad the big Home button in the middle (the Xbox logo) should close the dashboard.

**Comment by dondimadozen** [comment]
I am using the Vive. The problem only occurs through the headset but if I take it off and look at my monitor the game appears normal.

**Comment by LibreVR** [comment]
That's because the dashboard is only visible in VR. If you have a Vive headset there's a little button on the side of the HMD you can press to close it.

**Comment by dondimadozen** [comment]
Thanks, that fixed it!
