### ISSUE TITLE
Suggestion - Button Bind

### ISSUE THREAD

**Issue by SharkPolo** [LibreVR/Revive#381]
Hi.
First, awesome work the best VR app ever! Thanks!
I have tried some games and some Like Toybox and Bullet train you have to hold the grip button on the vive pushed and Arizona they bind the Menu button to teleport what is awful for me.
I would like to suggest a way to press one time the grip button on the Vive and it stays until you press again and if possible be able to bind the buttons of the Vive controller to any button on the Touch.
I hope helped with my suggestion.
Thanks again for the amazing app.

**Comment by froglegs4r** [comment]
There is already a grip toggle https://github.com/LibreVR/Revive/issues/342

**Comment by SharkPolo** [comment]
I looked for it on the menu and couldn't find, thanks!
