### ISSUE TITLE
Tray icon not showing for some users

### ISSUE THREAD

**Issue by LibreVR** [LibreVR/Revive#385]
I've moved this discussion to a separate issue, because I don't really appreciate it when people hijack other people's issue reports for their own separate problems.

@kvdv99 You can always reinstall Revive without losing anything. You can see a complete list of every application registered with SteamVR in the file `C:\Program Files (x86)\Steam\config\appconfig.json`. So please post the contents of the file here so we can see which versions of Revive are installed.

@nateev Did you ever use an older version of Revive?

**Comment by nateev** [comment]
Sorry about that.

I've the latest : 1.0.3 everything is in the default folder.
I'll uninstall everything and re-install and let you know.

**Comment by LibreVR** [comment]
Please also send your `C:\Program Files (x86)\Steam\config\appconfig.json` so we can check if any duplicates are running.

**Comment by nateev** [comment]
`{
   "manifest_paths" : [
      "J:\\jeux\\steam\\config\\steamapps.vrmanifest",
      "G:\\jeux\\steam\\config\\steamapps.vrmanifest",
      "G:\\jeux\\ViveSetup\\Updater\\App\\Dashboard\\viveoverlay.vrmanifest",
      "G:\\jeux\\ViveSetup\\Updater\\App\\Home\\home.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\1b591122-7ab7-4c27-9d31-cbaf9ef8e1e1\\1474674067\\app.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\9f28fb0c-7627-44b6-9b22-e25de6e93f50\\1474323131\\app.vrmanifest",
      "C:\\Program Files\\Revive\\app.vrmanifest",
      "C:\\Program Files\\Revive\\support.vrmanifest",
      "C:\\Program Files\\Revive\\revive.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\c7104110-33d9-4493-bc65-87d06d7efe9a\\1481015486\\app.vrmanifest"
   ]
}
`

**Comment by kvdv99** [comment]
{
   "manifest_paths" : [
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Dashboard\\viveoverlay.vrmanifest",
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Home\\home.vrmanifest",
      "C:\\Program Files (x86)\\Steam\\config\\steamapps.vrmanifest",
      "C:\\Program Files\\Revive\\revive.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\7b1b346e-c9dd-46d6-9967-63523230d2b8\\1474783151\\app.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\425befd0-fdfa-49fc-9204-4b696cfd9f3f\\1461934596\\app.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\8168e41c-b1af-41cf-9906-4e1858226f2b\\1469063138\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\01f30395-112e-49f5-ba84-70e6acebb5b0\\1476134896\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\2bbf1a52-7b88-41fc-b06b-a8a5b0ee801f\\1474918975\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\bc05b49f-a36e-44bd-a856-6b1bc45d6874\\1473203954\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\2a557b22-9ab2-4d20-9cd8-628d151e08f8\\1477092874\\app.vrmanifest",
      "D:/Users/gebruiker/Downloads/OpenVR-AdvancedSettings-v2.0/OpenVR-AdvancedSettings\\advancedsettings.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\08d6ddd4-0904-4b69-8515-e21cc1bbdfc9\\1464139686\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\7c4bdeb9-5f62-470d-a763-34e2b2a170cf\\1472666758\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\c666dd8d-e42b-403c-91d3-58693f268220\\1474640778\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\47590167-b266-41f8-a1cc-5a4b294425b1\\1478012411\\app.vrmanifest",
      "d:\\Revive\\app.vrmanifest",
      "D:\\Revive\\app.vrmanifest",
      "D:\\Revive\\support.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\608a0b5b-58e7-478f-aebb-d115098d18c2\\1480083785\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\ba299421-d9b5-4f21-9ffe-76c780edf031\\1479097654\\app.vrmanifest"
   ]
}

**Comment by kvdv99** [comment]
..." You can always reinstall Revive without losing anything"...
Do you mean run the Revive "Uninstall.exe" and then install latest version?
Or do you mean that it's always ok to reinstall ("in-place upgrade") but without first uninstalling?

**Comment by LibreVR** [comment]
> Or do you mean that it's always ok to reinstall ("in-place upgrade") but without first uninstalling?

This

**Comment by LibreVR** [comment]
@kvdv99 The appconfig shows two installations for Revive:

> "C:\Program Files\Revive\revive.vrmanifest",

and

> "D:\Revive\app.vrmanifest",

You will need to delete one of those installations. There's also this weird one:

> "d:\Revive\app.vrmanifest",

I'm not sure how that got in there, might be a good idea if you remove that line manually from the `appconfig.json` with notepad.

**Comment by LibreVR** [comment]
@nateev Yours looks normal, so you should have the tray icon *while SteamVR is running*. Double-check the little pop-up button:

![image_3](https://cloud.githubusercontent.com/assets/18057864/21247663/2e4464b8-c329-11e6-915f-bedfb42f5ea9.jpg)

**Comment by kvdv99** [comment]
Yes, it worked by removing the C: path to Revive! 
Thanks a lot for the support!

**Comment by nateev** [comment]
![no-icon](https://cloud.githubusercontent.com/assets/1006968/21254419/a06d9d7a-c365-11e6-9b3a-0e7a9131691c.JPG)

**Comment by LibreVR** [comment]
Good to hear you both solved it, I'll look into clarifying some of the documentation.
