### ISSUE TITLE
Should I enable Asynchronous/Interleave Reprojection while using Revive?

### ISSUE THREAD

**Issue by Rogway** [LibreVR/Revive#386]
Big time fan of the work you are doing with Revive.
I've always had a question regarding Asynchronous Reprojection and Interleave Reprojection with it though.
Is it better to have either, both or none enabled when using Revive?
It might be an obvious answer, but I have never been able to find a definitive answer regarding it.
If you could shed some light on the subject I would really appreciate it.

**Comment by LibreVR** [comment]
You should have it enabled as some Oculus games may rely on ATW to take care of small stutters. However in some rare cases reprojection may fail, but you should only turn it off as a last resort.
