### ISSUE TITLE
Oculus cover images not loading

### ISSUE THREAD

**Issue by jrbudda** [LibreVR/Revive#389]
Sorry if this is something dumb. Just did a fresh install of oculus home and then revive. The Revive tab isn't showing the game covers, just empty squares. ReviveOverlay.log says 

qrc:/Overlay.qml:84:13: QML Image: Error decoding: file:///E:/Oculus/Software/StoreAssets/jaunt-jaunt-vr_assets/cover_square_image.jpg: Unsupported image format
qrc:/Overlay.qml:84:13: QML Image: Error decoding: file:///E:/Oculus/Software/StoreAssets/oculus-dreamdeck_assets/cover_square_image.jpg: Unsupported image format
qrc:/Overlay.qml:84:13: QML Image: Error decoding: file:///E:/Oculus/Software/StoreAssets/oculus-lost_assets/cover_square_image.jpg: Unsupported image format
etc.

The jpgs are there and look perfectly normal to me.

**Comment by LibreVR** [comment]
Sounds like Qt is missing a dependency to decode images. Can you try re-installing Revive?

**Comment by jrbudda** [comment]
Well I fixed it. I found a QT_PLUGINS_DIRECTORY environment variable that was pointing at program files\openshot video editor\.

Deleting that solved it immediately. Not sure if that breaks openshot tho.

**Comment by LibreVR** [comment]
Oh wow, you might want to report that to the developer then, they really shouldn't be setting that environment variable system-wide.
