### ISSUE TITLE
"Showdown" and "adventure time - magic mans-headgames" are not starting

### ISSUE THREAD

**Issue by MasterElwood** [LibreVR/Revive#39]
Showdown shows an error message at start.

AT starts for about one second - and then just closes.

**Comment by o123albert** [comment]
when dragging and dropping shipping.exe to revive or revive to shipping.exe it says failed to run descriptor shipping.uproject

**Comment by LibreVR** [comment]
I'll look into it.

**Comment by gormanj** [comment]
I've fixed a few games with the failed to run descriptor error by renaming the .exe in the binaries folder to the project name.

**Comment by MasterElwood** [comment]
Now AT works - but runs at a slower speed most of the time. Like 0.5x or something.

**Comment by LibreVR** [comment]
I'm postponing this issue until a later release.

**Comment by LibreVR** [comment]
Adventure time works fine for me now by the way.

**Comment by gormanj** [comment]
Showdown is available for Vive and is a better visual quality build than the Oculus Home version. Search for "zippy" to find the three links on this reddit page:
https://www.reddit.com/r/oculus/comments/3jh721/request_hiquality_build_of_epics_showdown_demo/

**Comment by LibreVR** [comment]
I know, but these fixing these edge cases makes Revive more robust. The end goal is to have every Oculus game work out-of-the-box after all.

**Comment by LibreVR** [comment]
Fixed in e310f7352edf90db37245a06fd789245aa5fcd39.
