### ISSUE TITLE
Cant access menu in Superhot

### ISSUE THREAD

**Issue by XY01** [LibreVR/Revive#392]
In super hot none of the buttons on the vive controllers seem to bring up a menu

**Comment by LibreVR** [comment]
How is the menu accessed on the Oculus Touch? Do you have a screenshot of the menu?

**Comment by jaorg1234** [comment]
I have just finished Superhot, but I have never encountered any game "menu" in in the traditional sense. The game always starts right at the last checkpoint and only after finishing the game you will be able to select any levels.
