### ISSUE TITLE
Oculus games will not relaunch after being closed from the steam dashboard

### ISSUE THREAD

**Issue by aurialLoop** [LibreVR/Revive#393]
I've noticed that when I launch an oculus game from the revive dashboard, then close via the steam overlay, that the game can't be relaunched until steam vr is restarted. Specifically I've noticed this with Medium and Quill (the two games I use the most).

Are you able to repeat this on your side?

**Comment by LibreVR** [comment]
I have noticed that, it's a bug in OpenVR: https://github.com/ValveSoftware/openvr/issues/330

**Comment by gormanj** [comment]
Has the workaround been implemented in version 1.0.4 of Revive? I am still having this issue with 1.0.4. I launch a game and then cannot relaunch after exiting unless I restart SteamVR.

**Comment by Armada651** [comment]
The workaround was just to prevent the error from being thrown, but it seems the function I used for it is also broken. I will need to remove the workaround and that will fix a few cases of this happening.

**Comment by eikonoklastes** [comment]
Is there currently a way to restart the game, without having to restart Steam VR?

If there's some way to exit the title other than pressing Esc, or through the Steam overlay, then I'm happy to use that for now.

**Comment by Armada651** [comment]
This should be at least partially fixed in commit 91a2abc65060198eafbd3f1434980384b2ccc07e.
