### ISSUE TITLE
Looking after Revive Injector v. 0.6.2

### ISSUE THREAD

**Issue by Borgoush** [LibreVR/Revive#394]
Hello dear dev, 

first thing I´m sorry for possible off topic, but feeling kind of desparate after last night and I don´t know where else should I put it. I wanted to ask you for a little help. 

I´m looking for revive injector v. 0.6.2  for testing purposes. I´ve searched the internet for bunch hours but did not find the installer. Therefore I´d kindly like to ask you if you could send me a link for this archive version. 

Thanks in advance, 
regards,

**Comment by LibreVR** [comment]
Why do you need that specific version? I removed all other versions except for 0.9.7 as a lot of people were reporting bugs while actually they were just using a very outdated version.

**Comment by Borgoush** [comment]
Hello, at first I´d like to say thanks for answering. 
It´s just some games with 0.9.7 and later return entitlement check error, but with v. 0.6 they don´t (some that don´t work with 0.6 give me the Oculus rift error instead), so I thought that it might work with 0.6.2, but can´t find it anywhere. Would be glad if you could share the requested version.

**Comment by LibreVR** [comment]
Unfortunately I will no longer publish that release, as it broke DRM code which is no longer necessary. It sounds like you're still running an older version of Oculus Home. You should update it to the latest version.

**Comment by Borgoush** [comment]
Turned off firewall - updated oculus home - I´m back and running :-) Thanks for the advice. You can close this thread.

**Comment by LibreVR** [comment]
Great! And now you can also enjoy all the improvements that have been made since 0.6.
