### ISSUE TITLE
Bullet Train Crashes While Teleporting

### ISSUE THREAD

**Issue by laserob** [LibreVR/Revive#395]
The game launches, the first touch interaction works fine, but when asked to teleport I'm able to move to the first teleport position, the game drops a bunch of frames and quits in the HMD (but still continues on the desktop). I can continue to hear the audio in the HMD while taken back to the Steam environment.

**Comment by LibreVR** [comment]
Does the tracking still work?

**Comment by laserob** [comment]
Tracking stops. If I go to desktop view, the game continues to run but at a fixed camera angle. I can hear the game continue but pushing buttons on controllers gives no response at all.

**Comment by Armada651** [comment]
This seems to be an issue with the game rather than with Revive.
