### ISSUE TITLE
Superhot Vr will not launch

### ISSUE THREAD

**Issue by Figitz** [LibreVR/Revive#396]
Superhot Vr will not launch through revive. It just errors out and tells me an error folder has been created. The error says that superhotvr.exe caused an access violation. Does this have to do with revive or the game itself and is there a way to solve this problem?

**Comment by LibreVR** [comment]
Can you send me the contents of that error folder? I'm mainly interested in the output_log.txt, which you can just drag into the comment box here to upload it.

Next, make sure everything is up-to-date (SteamVR, Revive) and try again.

**Comment by Figitz** [comment]
[output_log.txt](https://github.com/LibreVR/Revive/files/662509/output_log.txt)

**Comment by Figitz** [comment]
[error.txt](https://github.com/LibreVR/Revive/files/662518/error.txt)

**Comment by CarrotSurvivor** [comment]
make sure ur on steam vr beta

**Comment by LibreVR** [comment]
@CarrotSurvivor That is no longer necessary, the fixes from the beta have already been added to the stable version of Steam VR.

**Comment by LibreVR** [comment]
> Failed to initialize Oculus Internal Interface.

This seems to be the problem, make sure everything is up-to-date, especially Oculus Home. I will try and see if I can reproduce it.

**Comment by Figitz** [comment]
ok ill try it out. Thanks.

**Comment by MasterNameless** [comment]
I'm getting this same issue with Superhot, and also Lucky's Tale now. I had a different issue with Superhot (sorry didn't save the crash files then!) that other people were reporting when it launched on the PC but not in the headset. I did a complete resintall of Windows 10, removing everything, and whilst noticing general performance improvements, Superhot and Lucky's Tale seem to have the same issue as others do in the thread, I keep getting access violation errors with both.

After a complete reinstall, I have fresh installs for everything, including all my usb and audio drivers etc., and haven't installed anything superfluous like advanced settings or anything like that.

My superhot crash files

[error.txt](https://github.com/LibreVR/Revive/files/679394/error.txt)
[output_log.txt](https://github.com/LibreVR/Revive/files/679393/output_log.txt)

And Luckys Tale files
[error.txt](https://github.com/LibreVR/Revive/files/679395/error.txt)
[output_log.txt](https://github.com/LibreVR/Revive/files/679396/output_log.txt)

Hope this helps get to the bottom of it - but not too soon, it being NYE tomorrow. Have a good one, and thanks for your work in VR!

**Comment by github-0** [comment]
Same thing here, "Failed to initialize Oculus Internal Interface" on output log. Worked before reinstalling Windows. Newest versions of Revive and Oculus software.

**Comment by github-0** [comment]
Solved: I had another game (Allumette) crashing at launch and while trying to run that from its exe directly, it showed an additional error dialog that Steam wouldn't: x3daudio1_7.dll was missing. Google told to install DirectX End-User Runtime to fix that, so I [did](https://www.microsoft.com/en-us/download/details.aspx?id=35) and now both games work again. No idea why I had the problem in the first place, but good riddance.

**Comment by Armada651** [comment]
I can't reproduce this issue, Superhot VR seems to work fine for most people.

@MasterNameless Make sure you're not running a virus scanner other than Windows Defender.

**Comment by MasterNameless** [comment]
@armada651 Thanks, but through no rhyme nor reason, after about five or six restarts (after I'd  given up on the game working!), it suddenly booted fine...  and it's an amazing game! 

It wasn't a clean install so I guess there was something else causing an issue in my system - glad its sorted though! It wasn't the anrivirus, as I haven't installed anything over Windows defender (it's a PC  I use only for vr), but thanks for the suggestion anyway.
