### ISSUE TITLE
remove Revive/Oculus games from Steam Library

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#397]
hi,

I uninstalled a few Oculus games from the Oculus library.
However, they still remain visible in the Steam Library.  How can I remove them there?

thanks,
Kris

**Comment by LibreVR** [comment]
You should start SteamVR, then Revive will update the installation status of Oculus games. This doesn't immediately update your Steam Library, but the games will be gone the next time you start SteamVR/

**Comment by kvdv99** [comment]
I still see the games, even after rebooting a couple of times. I still see titles that I uninstalled from the Oculus library 2 months ago.....

**Comment by LibreVR** [comment]
Might be a manifest from Revive left over from an incomplete uninstallation? Can you send your `appconfig.json` again? The list of manifests is in there.

**Comment by kvdv99** [comment]
{
   "manifest_paths" : [
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Dashboard\\viveoverlay.vrmanifest",
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Home\\home.vrmanifest",
      "C:\\Program Files (x86)\\Steam\\config\\steamapps.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\425befd0-fdfa-49fc-9204-4b696cfd9f3f\\1461934596\\app.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\8168e41c-b1af-41cf-9906-4e1858226f2b\\1469063138\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\01f30395-112e-49f5-ba84-70e6acebb5b0\\1476134896\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\2bbf1a52-7b88-41fc-b06b-a8a5b0ee801f\\1474918975\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\bc05b49f-a36e-44bd-a856-6b1bc45d6874\\1473203954\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\2a557b22-9ab2-4d20-9cd8-628d151e08f8\\1477092874\\app.vrmanifest",
      "D:/Users/gebruiker/Downloads/OpenVR-AdvancedSettings-v2.0/OpenVR-AdvancedSettings\\advancedsettings.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\08d6ddd4-0904-4b69-8515-e21cc1bbdfc9\\1464139686\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\7c4bdeb9-5f62-470d-a763-34e2b2a170cf\\1472666758\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\c666dd8d-e42b-403c-91d3-58693f268220\\1474640778\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\47590167-b266-41f8-a1cc-5a4b294425b1\\1478012411\\app.vrmanifest",
      "d:\\Revive\\app.vrmanifest",
      "D:\\Revive\\app.vrmanifest",
      "D:\\Revive\\support.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\608a0b5b-58e7-478f-aebb-d115098d18c2\\1480083785\\app.vrmanifest",
      "D:\\VivePort-Apps\\ViveApps\\ba299421-d9b5-4f21-9ffe-76c780edf031\\1479097654\\app.vrmanifest",
      "D:\\Revive\\revive.vrmanifest"
   ]
}

**Comment by LibreVR** [comment]
That looks good, no idea why the applications aren't uninstalled, can you send the logs from `%APPDATA%\Revive`?

After you've sent the log you can fix the problem by opening `"D:\Revive\revive.vrmanifest"` in notepad and simply deleting the contents (keep the file!). That will force Revive to regenerate it.

**Comment by kvdv99** [comment]
looks like it worked, thanks!

**Comment by LibreVR** [comment]
You didn't send the logs before you cleared the file though, so now we won't know what the problem was, meaning I won't be able to fix it...
