### ISSUE TITLE
Games don't show up on headset (SUPERHOT VR)

### ISSUE THREAD

**Issue by Jamster1765** [LibreVR/Revive#398]
Essentially, I've just seen SUPERHOT VR and wanted to play it before realizing it's Oculus Rift exclusive, the pricks. I download ReVive and I've got the dashboard in SteamVR, but whenever I try a start up SUPERHOT VR, an eternal loading symbol shows up on the in-headset dashboard and the game starts on my computer. It stays stuck in the SteamVR inital starting space and moving around the headset doesn't effect the onscreen game. 

I'm fairly confident I've installed it correctly because I've gone through the install process about three times now and restarted my computer several times.

Please help?

**Comment by LibreVR** [comment]
Can you post your logs here from `%APPDATA%\Revive`? Just rename the .log files to .txt files and drag them in the comment box here.

**Comment by Jamster1765** [comment]
Where exactly can I find these logs? If they're crash logs, the game never crashed; I just had to close the application via the desktop.

**Comment by Jamster1765** [comment]
Found it. 

Injector:
Launched injector with: "C:\Program Files (x86)\Revive\Revive\ReviveInjector_x64.exe" /library "Software\superhot-superhot\superhotvr.exe"
Creating process: C:\Program Files\Oculus\Software\Software\superhot-superhot\superhotvr.exe 
Injecting DLL: C:\Program Files (x86)\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xd47df610
Injecting DLL: C:\Program Files (x86)\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xd47df610
Injected dlls successfully

Overlay:
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest: C:\Program Files (x86)\Revive\revive.vrmanifest
Loaded manifest: C:\Program Files (x86)\Revive\app.vrmanifest
Loaded manifest: C:\Program Files (x86)\Revive\support.vrmanifest
Oculus Library found: C:\Program Files\Oculus\Software\
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/sanzaru-games-inc-recoil_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/superhot-superhot.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/superhot-superhot_assets.json
Found assets bundle playful-luckys-tale_assets
Found assets bundle sanzaru-games-inc-recoil_assets
Found application superhot-superhot
Found assets bundle superhot-superhot_assets

**Comment by vegost** [comment]
If it helps, I'm having the same problem. The game launches on my desktop monitor. 


Injector: 
Launched injector with: "D:\spill\Revive\Revive\ReviveInjector_x64.exe" /library "Software\superhot-superhot\superhotvr.exe"
Creating process: D:\Oculus\Software\Software\superhot-superhot\superhotvr.exe 
Injecting DLL: D:\spill\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x1d61f610
Injecting DLL: D:\spill\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x1d61f610
Injected dlls successfully



Overay:
libpng warning: iCCP: known incorrect sRGB profile
Failed to create the dashboard overlay (is it already running?)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Found assets bundle ccp-games-newcastle-eve-valkyrie_assets
Found assets bundle colosseteam-colosse-a-story-in-virtual-reality_assets
Found assets bundle oculus-dreamdeck_assets
Found assets bundle oculus-farlands_assets
Found assets bundle playful-luckys-tale_assets
Found assets bundle sanzaru-games-inc-recoil_assets
Found application superhot-superhot
Generating manifest for superhot-superhot
Found assets bundle superhot-superhot_assets
Adding manifest: superhot-superhot
Loaded manifest: D:\spill\Revive\revive.vrmanifest
Adding manifest: ccp-games-newcastle-eve-valkyrie
Loaded manifest: D:\spill\Revive\revive.vrmanifest
Launching application: superhot-superhot

**Comment by supervictorvl** [comment]
im having the same problem

**Comment by Pervezt** [comment]
Ditto, same issue

**Comment by vegost** [comment]
Just wanted to say I solved it by disabling Direct Mode. The performance is kinda laggy though (at least for me, gtx 970) so be careful if you're sensitive to motion sickness. Great game!

**Comment by Pervezt** [comment]
Thanks for reaching out. I’ll give it a go.

**Comment by Armada651** [comment]
I haven't heard from anyone running into this problem anymore and it sounds like it is related to SteamVR and not Revive.

Feel free to leave a comment here if you're still running into that issue.
