### ISSUE TITLE
Dirt Rally Revive controller issue

### ISSUE THREAD

**Issue by XanderRyan** [LibreVR/Revive#399]
I can get everything to work on my vive by patching Dirt and running it on steam. But when in game i cannot use any game pad or xbox controller and it forces me to use keyboard. I know its one of the .dlls from the patch... thats affecting it, because when i delete xinput1 dll i can use a controller again, but then it wont run on my headset. its getting really frustrating, can anyone help.

**Comment by LibreVR** [comment]
It's a known problem, something is wrong with the proxy functions.

**Comment by Rojoyinc** [comment]
I use a wheel.  cant drive well with a thumb!

**Comment by Armada651** [comment]
Going to move this one to 1.1, I've thought of a much better solution that doesn't need an XInput proxy.

**Comment by T0xicthunder** [comment]
has this been fixed or have a fix to play

**Comment by nravanelli** [comment]
I don't think this has been fixed... I just tried to use it and failed. Argh.

**Comment by ciaran036** [comment]
Any update on this one?

**Comment by Armada651** [comment]
What's your operating system?

**Comment by nlundquist** [comment]
I'm on Windows 10 and can't get my controller to work with Obduction

**Comment by Armada651** [comment]
Postponing the planned changes to the injector to version 1.2.

**Comment by UncleZeiv** [comment]
Is version 1.2 going to fix this? I tried the beta and didn't see a difference so far. Thank you for your efforts anyway!

**Comment by Dragoboss** [comment]
This has been fixed a while ago in the more recent versions.
Ticket over a year old. Closing.
