### ISSUE TITLE
Lucky's Tale - No Red Coins using Revive

### ISSUE THREAD

**Issue by Speedbreaker12** [LibreVR/Revive#40]
I wasn't able to start Level 4, because it says I don't have enough Red Coins. After checking out some Youtube walkthroughs, it seems like the Red Coins are not there when you start it over Revive. Which basically gives you a 3 Level Demo.

**Comment by LibreVR** [comment]
I'll test this myself tonight, haven't gotten a chance to play through the game anyway.

**Comment by vraddict** [comment]
it works 100% with no Issues, You need to select the red coin hunt for each level in the book at start of each level......

**Comment by Speedbreaker12** [comment]
Good thing I went with the vive, because I'm obviously too stupid to play Oculus games! Sorry! :)
