### ISSUE TITLE
Can't get Assetto Corsa to work.

### ISSUE THREAD

**Issue by Koppit** [LibreVR/Revive#406]
Assotto Corsa don't show in HMD. I have had it working before but it suddenly stopped and now I can't get it work anymore. I have reinstalled  Revive, Occulus, Vive and Assetto Corsa and patched it, but no success. 
Dirt Rally and Lucky's Tale work. Can anyone help?

**Comment by Rojoyinc** [comment]
I didnt think it needed revive.  I just run it but it's not VR until on the
track.

**Comment by Koppit** [comment]
Assetto Corsa only support Occulus so i belive Revive is needed. If there is another way please tell me. I know it only works when you race.  It worked before but not anymore.

**Comment by Rojoyinc** [comment]
I don't remember for sure, I thought I had pcars and asseto before revive.
I played it yesterday so I know it works with the old revive. I don't
update mine unless I need it to support a new title.
Else I'm using a 3 month old version.  If it works - I don't mess with it.

**Comment by Koppit** [comment]
I did not mess with either, just stopped working from one day to the other.

**Comment by Rojoyinc** [comment]
I went to test it - it shows a update pending... I'll report back after I
try it.

**Comment by Rojoyinc** [comment]
updated - works fine.

**Comment by Rojoyinc** [comment]
Librevive64_1.dll  and openvr...

you have 32 bit os or 64? I'm win10.

**Comment by Koppit** [comment]
I have 64bit Win10. I tried copying over the content from the x64 folder with LibRevive64_1.dll but no success.

**Comment by Rojoyinc** [comment]
I have no revive files in my  assettocorse/system/x64
dirs

only in the root

I don't drag and drop - I just make sure VR is running in steam and click
on the steam run game link and it loads.

**Comment by Koppit** [comment]
Sorry I meant copy from Reive/Revive/x64 folder to AC root

**Comment by Balderick** [comment]
To use osvr hdk for vr hmd I have to select "oculus" in graphics settings and then select "force 32 bit" in general settings to get ac to launch in vr mode using the latest revive version available.

**Comment by Koppit** [comment]
Got it working. I think i needed to patch the "acs.exe" file.

**Comment by LibreVR** [comment]
@Koppit That is indeed the correct method for Revive 1.0 and later, this is also mentioned on the wiki: https://github.com/LibreVR/Revive/wiki#steam-games
