### ISSUE TITLE
Can I run revive with oculus dk2?

### ISSUE THREAD

**Issue by hedtrip** [LibreVR/Revive#407]
Hello,I have a problem with oculus home and can't launch game to play with my dk2(hardwarte error,can't install the dk2 cam and have not full headtracking but want to play games).
So I'm trying to use revive injector with my dk2 but the game appears on a window in my monitor bur my dk2 are gray.If I try to play steam games on DK2 they run ok.
any suggestion to see revive games at hmd instead at the monitor?
Thanks

**Comment by unclespode** [comment]
Why would you be using revive if you have an Oculus?

**Comment by hedtrip** [comment]
Just read above...
(hardwarte error,can't install the dk2 cam and have not full headtracking but want to play games).

**Comment by Armada651** [comment]
Revive wouldn't fix that if the games themselves require a tracking camera. But I get the feeling Oculus Home is preventing you from running those games. You can try running the game executable directly instead of through Oculus Home.

**Comment by hedtrip** [comment]
I only want to play games,doesn't matters if have not tracking cam but oculus prevent play any game or watch videos if one hardware error is detected.No matter if I want to play a game that doesnt needs headtracking so for that i was trying revive.But is a thing from the past.

**Comment by Armada651** [comment]
That means Oculus Home is preventing that, running the game executable directly should get around that. No need for Revive.

**Comment by hedtrip** [comment]
Nope,is absolutely necesaty run trough oculus home any game
 so for that ever OH runs and detect the hardware error (onlu for OH platform games)
Cheers

**Comment by Armada651** [comment]
Running through Oculus Home is not necessary for any game as long as you restart the Oculus service (or your PC) after installing the game. This is something Revive relies on.

**Comment by hedtrip** [comment]
Well...my dk2 not starts if oh is down.Anyway thanks for the help.
Today theres no problem.

**Comment by danank92** [comment]
same problem :(
