### ISSUE TITLE
SuperhotVR head position is really low to the ground

### ISSUE THREAD

**Issue by JorenRapini** [LibreVR/Revive#408]
First time trying Revive, I looked everywhere but couldn't find anyone reporting an issue like this.

The game plays as if my head is about where my stomache should be. The enemies tower a full couple heads taller than me. I actually can't get past the part of the game where it asks you to put on the headset, because the headset is out of reach and too high (right after the tutorial). How do I fix this? Thanks

**Comment by LibreVR** [comment]
Sounds like you may be running an old version of Revive or you have multiple versions of Revive installed and the old one has been prioritized.

To make sure you are running the latest version, follow these steps:

1. Start SteamVR
2. Click the arrow next to the system tray in the bottom-right on your desktop to show the hidden icons.
3. There should be a white Revive logo there, right-click it and select "Check for updates".

**Comment by JorenRapini** [comment]
Unfortunately I'm already running the latest, 1.0.3.1

**Comment by LibreVR** [comment]
Try running the SteamVR room setup again.

**Comment by JorenRapini** [comment]
That was it, thanks! Weird, it didn't affect any other games non-revive games.
