### ISSUE TITLE
SuperHot Wont Start

### ISSUE THREAD

**Issue by TerrorShark17** [LibreVR/Revive#409]
everything works perfectly, just like it should, i made a folder called "Oculus" and installed it there, and i put the "revive" folder in my other disk (that COULD be the problem, i have 2 disks) but then i launched steam VR, and superhot just wont start, i can hear the sounds for like 30 secs, but nothing starts, my monitor sees it, but it is just frozen there (the game) and i have no clue what to do other than with the disk thing...

**Comment by supervictorvl** [comment]
i am having the same kind of problem i have 3 drives and installed my games on 3rd drive and my revive on first. i can see the game on the screen but my vive doesnt interact

**Comment by ziggyzerda** [comment]
This was going to be the second game I was wanting to play through Revive. Glad I saw this first as I'm having issues with The Climb as well. Seems like this software needs a lot of work before people start wasting their money on Oculus titles.

**Comment by ZombieNinjaa** [comment]
I found reinstalling SteamVR fixed this for me

**Comment by LibreVR** [comment]
Can you post the logs from `%APPDATA%\Revive`? You can just rename them to `.txt` files and drag them into the comment box here.

**Comment by supervictorvl** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/671721/ReviveInjector.txt)

[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/671722/ReviveOverlay.txt)
 and yes im using a vive

**Comment by LibreVR** [comment]
@supervictorvl You are using symbolic links to move your games to other hard drives. This could be the problem.

Try reinstalling Oculus Home, but this time use the installer to change the location of your Oculus Library.

**Comment by Armada651** [comment]
No reply for months, closing this issue. Feel free to leave a comment here if you're still running into this issue.
