### ISSUE TITLE
Chronos not starting in headset

### ISSUE THREAD

**Issue by Mapkinasekinase** [LibreVR/Revive#410]
Hello everyone,

I am encountering an issue with Chronos. If I start the game, it will play on the monitor, but not on the headset. Subsequently, I receive an error notification, claiming I have to make sure that my HMD and sensor are plugged in correctly.

I googled the issue, and found an already closed github thread:

https://github.com/LibreVR/Revive/issues/79

However, I can't quite understand the solution there. I assume, this is because I am using a newer version of revive, that no longer includes a standalone injector?

I usually just start Revive from my Steam VR dashboard. This works nicely for e.g. Lucky's Tale, but it doesn't work here. Do I need to follow additional steps to get Chronos running?

I tried restarting the Oculus software, rebooting the PC and I also copied the LibRevive64_1.dll, openvr_api.dll and ReviveInjector_x64.exe into the \Chronos\Binaries\Win64 folder. None of that changed anything.

Thanks!

**Comment by LibreVR** [comment]
Sounds like you're not using an HTC Vive headset, is this correct?

**Comment by starmandar** [comment]
I am having the exact same issue; chronos will start up but only show up on my laptop monitor, I have an htc vive as my hmd.  I am running chronos through the injector function thru revive.

**Comment by Pervezt** [comment]
This is essentially the same issue I'm having . Any word on what may fix this ?

**Comment by MalekTaus** [comment]
For me the game is stuck at the loading screen after character selection

**Comment by marcob2178** [comment]
same problem here. Anyone found a solution?

**Comment by Mapkinasekinase** [comment]
I gave it another try today and got it running!

For me the trick was to check the "Unknown Sources: Allow apps that have not been reviewed by Oculus to run on Rift" in the Oculus General Settings, as suggested in another thread about a different game.

**Comment by starmandar** [comment]
Glad it worked for you!  I tried your solution as well by enabling the unknown sources in oculus, but the game still won't appear in the headset :(

**Comment by Kyldros** [comment]
I have the same issue, any solution?

**Comment by Armada651** [comment]
I can't reproduce this issue, make sure you're not running a virus scanner other than Windows Defender as that may block Revive from working.

Feel free to leave a comment here if you're still running into this issue.

**Comment by Kyldros** [comment]
I do not have any other virus scanner, and revive works fine with all other games but not with Chronos :(

**Comment by Armada651** [comment]
Currently there's a bug in SteamVR that may prevent any Revive game from starting up.
