### ISSUE TITLE
SuperHot VR will not work at all??

### ISSUE THREAD

**Issue by MattRuggz** [LibreVR/Revive#411]
I cannot get SuperHot VR to launch in my headset.  I have installed revive dashboard and all that.  It may have to do with the fact that I have a torrented version of SHVR, but everyone on the site said it worked with Revive, so I don't know what my problem is :(

**Comment by LibreVR** [comment]
If you don't but it from the Oculus Store, you're on your own.

**Comment by MattRuggz** [comment]
Got it.
