### ISSUE TITLE
The Climb halts on boot

### ISSUE THREAD

**Issue by daveleack** [LibreVR/Revive#412]
I've been over the historic issues with The Climb, and it seems a few folks had some difficulty and then it all got worked out.
I'm having a problem loading it up though. I have the latest release of Revive and Oculus Home (downgrading doesn't look feasible at this point) and on boot The Climb gives me "You have a pending hardware issue..." which is obviously true, since I don't have a Rift. But it seems other folk have been able to run this game so I'm wondering why I'm having this problem.

Any thoughts?

Cheers

**Comment by LibreVR** [comment]
Sounds like you're trying to start it through Oculus Home, you need to start it through the Revive Dashboard after putting on the headset or through you Steam Library.

**Comment by daveleack** [comment]
Crikey, thanks for the quick response :)
Running from both the VR dashboard and steam library yield the same result unfortunately.
I have a feeling this is where I reveal that I'm trying to use RiftCat rather than an actual Vive and I end up out of luck. Although I've since gone to null driver testing because setting up riftcat every time I want to try something is a pain, and this error didn't strike me as being related to which HMD driver was being used given that it looks like Oculus Home's hardware checker getting in the way.
Sorry if that puts this out of your field.

**Comment by daveleack** [comment]
Well played on getting the Oculus titles to load up into the Steam library though. I hadn't spotted that. Really cool stuff :)

**Comment by LibreVR** [comment]
You shouldn't keep secrets like that. ;)

Anyway it should be fixed if you reboot your PC.

**Comment by daveleack** [comment]
Really? How so? (And I'm trying that now...)

**Comment by daveleack** [comment]
Nuts. Rebooting didn't help :(
Pretty painful that Steam's entire online presence is down at the moment too, but there it is.

**Comment by daveleack** [comment]
I don't know if it means anything useful but I get "HMD (on) Trackers (0)" in the header of the error message.

**Comment by daveleack** [comment]
Sorted (ish). Not withstanding that it's supposed to be playable with a pad (which I did have attached) the error was attached out of having motion controllers attached. With psmoveservice running it boots just fine.
Now my issue is getting the game to stop thinking it's lost the hmd. I have a horrible feeling that means I need freepie bridge and freepie running. 
This is getting more involved than is probably wise for showing to family at Christmas ;)

**Comment by LibreVR** [comment]
Yeah, Revive is really not intended for those kinds of setups. I'd like to support them, but I really need to keep the scope of this project as focused as possible since I'm the only developer.

**Comment by daveleack** [comment]
Understood. You're managing wonderfully and it's very important work. Many thanks.

**Comment by jjr71** [comment]
Could you explain in simple terminology how you set up psmove service to get the climb working please?

**Comment by jjr71** [comment]
Dave - I found your thread , had exactly same issues as you, but not sure how to get psmove service up and running

**Comment by daveleack** [comment]
jjr71 - I found that the problem I was having went away once I'd turned on my psmove controllers before starting up The Climb.
Every time I got the error I had riftcat and psmoveservice running, but I didn't have the move controllers turned on. I figured it'd work fine with just the pad attached, but I suspect something went wonky along the way and because I didn't have my controllers attached, Oculus didn't get properly routed around.
So, if you haven't got move controllers turned on and set up when you boot the game and you're having the same problem I did, try booting the game with the move controllers turned on.
If you've already got them turned on and are still having the same problem, I'm afraid I have no idea.

Good luck!

**Comment by jjr71** [comment]
Thank you Dave, very much appreciate your help. Actually I'm using a PSVR with revive which is working fine with steam games and most Oculus store games, just not the Climb! Then I saw your post and so Here I am. Assuming I have Revive set up correctly, is it simple to set ps move service correctly? - I did install it but think I didn't do it correctly (putting it on correct folder etc...) Where's the best place to follow installation instructions?
Thx
jjr71

**Comment by daveleack** [comment]
Oooh, I hadn't realised PSVR was working well on PC at this time. Are you using a PS Eye camera to watch the headset position? Does that work? Can you link me to a description of your setup because it sounds *really* interesting...
In any event, PSMoveService is *anything but* simple to set up. There's a number of videos available on how to do it. You'll need two PSMove controllers and between 2 and 4 PSEye cameras.
Here's one such video: https://www.youtube.com/watch?v=QEraN1r_5Nw

**Comment by daveleack** [comment]
Hmmm. From the video I just watched, the chap was using a separate head tracker for just orientation (EDTracker, which I'm familiar with) but no spatial tracking. I was hoping someone had snagged the PSVR orientation data and written a camera tracker for it. There's little benefit in me getting one in that case because my phone has the same resolution (although I know the headset is more comfortable).
I'll keep looking. Someone will crack it sooner or later I'm sure.

**Comment by jjr71** [comment]
Hi Dave, for your input. Basically I have a PSVR with two motion controllers and I bough 1 ps3 eyetoy camera for Trinus (So you can play HTC vive games on Steam) It also allows me to play Oculus Store games (I used to have a DK2) I REALLY would like to be able to play THe Climb as it was my favourite game on the DK2. Is tit that Crytek have some kind of DRM blocking software going on? Or do you think there's any other way besides using psmove service? - If not I'll bite the bullet, buy another PS3 camera (it was only £1.50 from CES!) and try and set up the move controllers.

**Comment by daveleack** [comment]
I really can't say exactly what's causing it. All I know is that having PSMove sticks attached solved it for me.
I wish I knew more, but these things are meant for smarter minds than mine.
When you say you have PSVR with two motion controllers, do you mean pads or wands? When I talk about PSMove controllers I'm talking about the sticks with the glowing bobbles on the end.
As you say, local stores have PS3Eye cameras for next to no money so as long as you have wands, getting PSMoveService set up would be relatively cheap (unless you need to put the cameras far away, then you'll need active USB extenders which can get irritatingly expensive).
If you don't have the PSMove wands and you have PS4 pads with motion control, then I've no idea whether it'll work, but I *do* know that PSMove wands are still going to cost between £40 and £60 each and if they're old devices, the batteries in them will be knackered. These are the hurdles I've jumped to get to where I am (about a tenner each on top for the replacement batteries *sigh*).

**Comment by jjr71** [comment]
I have the wands. I'm assuming that as I have a psvr I only need 2 and not 3 as that's presumably for positional head tracking (which the psvr has lights for) I'll give the video tutorial a go later I think. How is the Climb now for you with your set up?

**Comment by daveleack** [comment]
I was in a rush to get it set up in time for a particular guest coming to Christmas dinner, but in the end didn't get to show it off (turns out they likely wouldn't have been *that* interested anyhow).
I had difficulty getting through the tutorial which I put down to my inexpertly set up camera set causing some tracking problems.
What software are you using to positionally track the PSVR headset? I was under the impression that nobody had got the optical tracking working on PC yet...

**Comment by jjr71** [comment]
I'm using Trinus which enables me to play Steam vr games. It does have an option for positional tracking but its virtually unusable at the moment. Is it necessary to have positional tracking to play The Climb do you think?

**Comment by daveleack** [comment]
I'd say so, unfortunately. There are bits in the tutorial where you have to stretch to reach holds that are a little higher than normal or round a corner. On those occasions you need to lean or rise up to put your hands in reach of the holds. I suspect it's unplayable without position tracking.

**Comment by jjr71** [comment]
I'm using Trinus to play Steam vr games. The positional tracking is pretty unusable at the moment and it reccomends not using it at all. Are you using the wands on The Climb? And if so how are they?

**Comment by jjr71** [comment]
Its actually just the in "in and out' positional tracking that doesn't work properly, the 'up and down' tracking is a bit wobbly but does work, so maybe it'll be ok

**Comment by daveleack** [comment]
Up, down, left and right will be needed. I hope they work well enough for you.
I'm building up to the point where I buy a few more active USB cables and put up proper brackets for the cameras. What I have at the moment is pretty hit and miss. Once I've done that, I'm sure the tracking will work pretty well, but at the moment while I can have some success with things like Hot Dogs, Horseshoes and Hand Grenades, and I can get to level three of Brookhaven Experiment, the limitations of the tracking are clearly holding me back.
Good luck to you sir! I hope your tracking solution is sufficient!

**Comment by jjr71** [comment]
Can't wait t try it. Its just so cool that you can use the psvr with SteamVR and Oculus. I sold my DK2 and bought a psvr because I wanted something more plug n play and because I thought the psvr would be better supported software-wise. Except now I'm back to fiddling with software and peripherals so I can play The Climb!
