### ISSUE TITLE
"Damaged core" not play Issue. (Revive "1.0.3.1")

### ISSUE THREAD

**Issue by kissngift** [LibreVR/Revive#413]
I bought "Damaged core" when Oculus sale.
"Damaged core" run is OK.
But I can't use Xbox one pad.( "A" button switch is not active)
"Oculus Tracker disonnected" message is displayed.
I used Revive "1.0.3.1".

Please help me,

**Comment by LibreVR** [comment]
Are you using an HTC Vive or another headset?

**Comment by kissngift** [comment]
I use OSVR HDK2.
I normaly played "Eve valkyrie(Oculus Stroe)"," Luckys tale" to use HDK2 after install Revive.
I thought game to support Xbox pad is  same Vive and HDK2 at SteamVR.
And buy "Damaged Core".

I hope Revive support HDK2.
Thanks.
