### ISSUE TITLE
After Upgrade Revive 1.0.3.1. All Ocullus Games Can't play.

### ISSUE THREAD

**Issue by berserk7912** [LibreVR/Revive#414]
I have HTC Vive now. I use revive well one month ago. But after my business trip, I heard the news about New version of Revive. So I installed newest version of Revive. And now, All ocullus games can't work'g.
All massage is Same. "can't find Vr headset and sensor."
I uninstall Revive and Reinstalled. But can't fixed. And I delete all ocullus games and Reinstalled. But can't work'g.... I buy 4 new games on Ocul Home. climb, valkry, unspoken, damaged core. I'm very sad.. plz answer me.. .

**Comment by LorkHang** [comment]
Did you update to the latest version of Oculus Runtime too?

**Comment by berserk7912** [comment]
How I check Ocul runtime? I Can't find menu.. And What is latest version of Ocul runtime? Thanks for your answer

**Comment by LorkHang** [comment]
Open Oculus Home.
Go to Setting > "General" Tab
Scroll down, it is written in the end of page. 
Mine is 1.10.2

Also, make sure you have "Unknown Sources" checked,
Try to "Restart Oculus" too in the "Beta" Tab and see if it works.

**Comment by berserk7912** [comment]
thanks for your kindness. I want to reinstall Ocul home. But I can't find ocul home install file...LoL.

I'm too angry and delete ocul before read your answer...
