### ISSUE TITLE
Now Unreal Engine games can't working on Vive 1.0.3.1.

### ISSUE THREAD

**Issue by berserk7912** [LibreVR/Revive#416]
Yesterday, I had problem with Revive. Every games didn't working. But, I uninstall all ocul home, steam, Revive And Reinstall All. 

And now, Unreal engine games are not working. another game is working(like "lost") But If I want to start Unreal engine games. Same as Yesterday. "can't find ocul and sensor" 

On HMD, JUST Loading all day. On computer monitor, games are running..

**Comment by Pervezt** [comment]
I'm having the same issue actually . Just installed everything today and games show up in revive tab but just load forever even though they're playing on the TV monitor .

**Comment by Armada651** [comment]
Sounds like you have a virus scanner or something that is blocking Revive from working.
