### ISSUE TITLE
Games Freezing on Startup

### ISSUE THREAD

**Issue by Ardaw86** [LibreVR/Revive#419]
When I try to launch games, they immediately freeze on my monitor and do not appear in the headset display. This happens for both Dead and Burried and Superhot. Both of these games were just working yesterday morning, but stopped working a few hours later. I have tried running a .bat file with the following code: 

ReviveInjector_x64.exe /base Software\Software\ccp-games-newcastle-eve-valkyrie\Image\WindowsNoEditor\VkGame\Binaries\Win64\EVE Valkyrie.exe -oculus

This made the games work initially, but uninstalling and doing this again did not work. Is there another fix? Thanks.

**Comment by Armada651** [comment]
I can't reproduce the problem and no one else seems to run into it. Feel free to leave a comment here if you want to reopen the issue.
