### ISSUE TITLE
Does revive support ATW & ASW?

### ISSUE THREAD

**Issue by JamaicanMoose** [LibreVR/Revive#422]
Was just wondering if revive supported Asynchronous time warp and asynchronous spacewarp while playing occulus store games.

**Comment by LibreVR** [comment]
No, the Oculus Runtime is no longer involved when you use Revive, so you only get the features provided by SteamVR.

SteamVR supports asynchronous reprojection, which is the equivalent of ATW. However there is no equivalent to ASW yet. So make sure your PC is at the recommended spec before buying a game on the Oculus Store.
