### ISSUE TITLE
Games not showing up

### ISSUE THREAD

**Issue by Diphoz** [LibreVR/Revive#429]
I have followed all the install procedures and when i switch to the Revive tab in SteamVR the new games i install do not show up however some of the setup/default demos are there and they work. im not very good at this sort of thing so any help appreciated!.
![image](https://cloud.githubusercontent.com/assets/24817423/21533843/c8be3c76-cd56-11e6-811f-e3348347d27d.png)

![image](https://cloud.githubusercontent.com/assets/24817423/21533849/e08b033e-cd56-11e6-8120-9d90bac845c2.png)

**Comment by LibreVR** [comment]
Sounds like you installed your Oculus library to the root of a hard drive. There is a bug in version 1.0.3 that will be fixed in 1.0.4 that will break game detection.

A workaround is to re-install Oculus home and this time select a subdirectory for your Oculus Library like: `D:\OculusLibrary`.

**Comment by Diphoz** [comment]
Thanks but still no luck. I tried doing what you said and installing the Oculus Library in a subdirectory however this has still not solved the problem

**Comment by TheBigGing3** [comment]
I have this same problem straight from the first time I used Revive, i have only just got my HTC VIVE and i was wondering if it is a recent glitch. No matter what I install from the oculus store. I did as you suggested with the subdirectory and still no luck.

**Comment by TheBigGing3** [comment]
Since the new update i am able to see the games that are in my library thanks for the fix
