### ISSUE TITLE
Assetto Corsa won't load in 64-bit VR after Dec 20 update

### ISSUE THREAD

**Issue by torsoboy** [LibreVR/Revive#430]
Hello,

[EDIT: The game will load in 32-bit mode but now won't load in 64-bit mode.]

I've been enjoying Assetto Corsa on the Vive for quite some time now. However it looks like the Dec 20 (v1.11) update broke compatibility with Revive (1.0.3). The update specifically calls out "VR usability improvements" but does not say what was changed. The game still loads fine but when starting a race it crashes back to the main menu. 

I've attached the Revive logs for reference but there's nothing really there. Please let me know if you need additional details. Thank you.

[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/676425/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/676426/ReviveOverlay.txt)

**Comment by hyperseven** [comment]
Gamermusclevideos is live streaming it at the moment so must be you end.  It is the Steam version not the 'reloaded' copy.

**Comment by torsoboy** [comment]
So he is. I dug a little more and tried setting the "Force 32 bit" option in the Assetto Corsa settings and now the game loads. I'm going to leave the bug open for now as it used to run just fine in 64-bit mode. Thanks.

**Comment by Cadence81178** [comment]
I am having what I think to be the same issue and will try to force 32bit tonight. Should it work in 64 bit though?

**Comment by Armada651** [comment]
I'm going to overhaul the patching method in Revive 1.1, so it should be fixed in the next version.

**Comment by JoshTheNerd** [comment]
Issue confirmed here too. Really hoping the update resolves it. Love this game!

**Comment by Cadence81178** [comment]
just to confirm force 32 bit worked for me.

**Comment by torsoboy** [comment]
Upgraded to Revive 1.0.4, re-patched and am again able to load Assetto Corsa in 64-bit. Not sure what changed but it seems to be working for me again. Can others confirm?

**Comment by Balderick** [comment]
Confirmed working 64 bit with revive 1.0.4 on current steam beta client with steamvr beta with osvr server running latest runtime and steamvr-osvr drivers all on windows insider build.

**Comment by Armada651** [comment]
I'm pretty sure people are just patching the wrong executable. Closing this issue.
