### ISSUE TITLE
Medium terrible CPU performance

### ISSUE THREAD

**Issue by RocketBun** [LibreVR/Revive#433]
Just copying this from my post on reddit to stick it here: When I start to sculpt with anything above 40 size, the CPU total usage shoots up to 100% and the game starts dropping frames. I've tried disabling/enabling reprojection, cutting out all the other things that could be taking up CPU time, but it seems to just be medium itself. I have an i5 6600k and GTX 980Ti, for reference. 12GB of ram, as well. It seems to be purely a CPU bottleneck and it's quite irritating because I don't have this problem with any other program. [This](http://i.imgur.com/dlIGQmN.png) is what medium does to my CPU just sitting idle. And [this](http://i.imgur.com/gMCQKiX.png) is what happens when I start to sculpt. Anyone else having this problem? [This](http://i.imgur.com/RBfbMxk.png) is what my CPU usage looks like when I close everything VR related. I don't have issues like this in any other VR program, it seems to be just medium.

**Comment by Armada651** [comment]
Just letting you know, it's a known issue, because Medium uses Revive and OpenGL support in Revive hasn't been extensively tested or optimized.

**Comment by Armada651** [comment]
I just tested it on my i7 3770K without any problems, there is an increase in CPU usage during sculpting, but that's to be expected as it is a CPU-intensive operation.

I'll try and do some performance profiling and see if I can detect any bottlenecks.

**Comment by RocketBun** [comment]
On smaller brushes it doesn't stutter, its only when I attempt to use stuff over 30-40 that the CPU usage tops out and starts to lag. Thanks for testing it out though!

**Comment by Armada651** [comment]
Most performance issues in Oculus Medium are fixed by now. Sculpting just requires a lot of CPU power whether you're using Revive or the Oculus Runtime.
