### ISSUE TITLE
Superhot.VR not playing in vive

### ISSUE THREAD

**Issue by marcob2178** [LibreVR/Revive#437]
Help please. The game does not boot up in vive , it only boots up on my pc monitor :-(

Thanks

**Comment by Clothednblack** [comment]
Sounds like something on your setup, I just installed that yesterday and plays perfectly through vive. Maybe you missed something? Do other oculus games play through the Vive for you?

**Comment by Vexs** [comment]
Just had the same issue here- other oculus games launch just fine, but superhot seems to freeze up after the initial loading screen. (Right when it displays 6 or so black polygon things)

**Comment by AndruC** [comment]
>  superhot seems to freeze up after the initial loading screen. (Right when it displays 6 or so black polygon things)

Also experiencing this issue.

**Comment by Vexs** [comment]
Should mention that my issue went away after rebooting my desktop.

**Comment by Armada651** [comment]
Make sure you rebooted the Oculus Service or your PC. Also *many* people report Superhot not working with Revive when they're actually using the regular edition of Superhot instead of the VR edition.

**Comment by Blue283** [comment]
I got the same problem. Does someone know how to fix it ? Reboot doesn't work. I bought the Game on Oculus-Store and want to Play it. :(

**Comment by Armada651** [comment]
@Blue283 You're running into issue #478. Unfortunately the SteamVR update broke the Revive dashboard. Try starting Superhot from Steam, it should be in your library when you have SteamVR running.

**Comment by Blue283** [comment]
thanks Armada651 it is there.
But when i try to run it it says the is a problem with the 
shortcut. I dont know why this hapend i checked the 
shortcut.

**Comment by Armada651** [comment]
If you tried to launch it from the dashboard once you'll have to restart SteamVR.

**Comment by Blue283** [comment]
Yea tried that but it still start on my Desktop ? Or does i have to start it, than restart steamVR?

**Comment by Armada651** [comment]
No, that would just cause the game to exit (if Revive was loaded correctly). The last thing you can try is injecting manually. When SteamVR is running there should be a Revive tray icon. Right-click the icon, select `Inject...` and then look for the Superhot executable (by default it's located in `C:\Program Files\Oculus\Software\Software\superhot-superhot\superhotvr.exe`)

**Comment by Blue283** [comment]
Revive is correctly installed but i don't got a tray Icon. Just the Icon from SteamVR and Vive itself.
SuperhotVR is in the correct folder. I dont know what Kind of Problem this is.

**Comment by Armada651** [comment]
Look more closely, are you sure there's no white triangle icon somewhere in your system tray?

**Comment by Blue283** [comment]
only the normal Vive Icon :(

**Comment by Armada651** [comment]
Then you're probably running an old version.

**Comment by Blue283** [comment]
where can i find the new one as a Installer Version   ?

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/releases

**Comment by SgtShivers** [comment]
Superhot VR won't run anymore for me either.  I just get into a black surrounding, hand controls aren't even visible, and it sits there forever.

**Comment by CarrotSurvivor** [comment]
@sgtshivers you need to delete you games save data. It corrupt and has nothing to do with revive, happened to me. If you google the issue how to delete your save file is explained on a steam discussion forum. Doing that fixed the game for me.

**Comment by SgtShivers** [comment]
@carrotsurvivor that worked, thanks!
