### ISSUE TITLE
Entitlement Problem with some titles

### ISSUE THREAD

**Issue by m4rt4k** [LibreVR/Revive#438]
Im having some problem with "I Expect to Die" and "Dead and Buried". Both games launch correctly using the patch, but then I get a message, in-game, saying "entitlement not found". Other games like fishing challenge, lucky tales and every other games launched from the "ReVive Overlay" work perfectly.

Things I tried so far : 
-Making sure I had the lastest Oculus runtime updated : 1.10.2
-Checked the "unknows apps" in the oculus setting
-Clicked restart oculus in the beta section + restarted my computer a couple of time
-Re-installed ReVive
-Tried using the injector instead of the patch

Im out of idea and I would like some help please !

**Comment by Armada651** [comment]
Try reinstalling Oculus Home.

**Comment by tuviello** [comment]
I have the entitlement check fail too. 

I tried everything (re-installingoculus home, re-vive, donwload the games again, etc...). 

Sometimes, randomly,  Luckys Tale works :S

**Comment by Armada651** [comment]
Did you try restarting your PC?

**Comment by tuviello** [comment]
yep, i tried Everything.

Today i´m going to reinstal Windows 10, Re-vive, Oculus, etc...

**Comment by m4rt4k** [comment]
Ok I got it to work .. I found an oculus home bypass injector on some website i wont tell and using this + the revive patch made it work !

**Comment by m4rt4k** [comment]
Risking it .. https://downace.com/9n6j

**Comment by tuviello** [comment]
I dont like this option m4rt4k. I want to use my original game from oculus home.

**Comment by m4rt4k** [comment]
Yea i dont know what to tell you.. my original game work from the revive dashboard. Sorry then

**Comment by Armada651** [comment]
Closing this issue as I can't reproduce it. Feel free to leave a comment here if you're still running into this issue.

**Comment by SkywardEntertainment** [comment]
I am running into the entitlement not found error on dead and buried.

**Comment by unka** [comment]
Hi.
 Same here.
 Dead And Buried "Entitlement not found".
 Any ideas?
