### ISSUE TITLE
[Feature Request] Add Settings tab on the task bar menu

### ISSUE THREAD

**Issue by momower1** [LibreVR/Revive#439]
This is just a small feature request to make editing the renderTargetMultiplier and other (future?) settings easier. A simple slider with a restart button would be awesome when you left click on the revive icon on the task bar 😄

@LibreVR I could try to write some code myself but I'm not that familiar with the code yet. Might need some introduction...

**Comment by jaorg1234** [comment]
Something like what OpenVR Advanced Settings is offering?

https://github.com/matzman666/OpenVR-AdvancedSettings

Maybe you are looking for something like that.

**Comment by momower1** [comment]
@jaorg1234 Yeah but I guess this does not affect the renderTargetMultiplier, doesn't it?

**Comment by jaorg1234** [comment]
The renderTargetMultiplier is the same as the super sampling value. You can change it through those advanced settings. As usual, you will need to restart SteamVR for it to take an effect.

**Comment by Armada651** [comment]
Also, OpenVR-AdvancedSettings is going to get a tab for advanced Revive settings, so I definitely recommend you install it.
