### ISSUE TITLE
psvr more trinus

### ISSUE THREAD

**Issue by aluflint** [LibreVR/Revive#442]
hi all people. i try use revive with psvr, and luckys tales work good. the truble is others games, for example hermobound or chronos. the game always show check the sensor, and not work.

any idea for this trouble? thanx! and a happy new year ^^

**Comment by Armada651** [comment]
Some games demand you use two sensors for some reason and PSVR only has one.

**Comment by cr4zyw3ld3r** [comment]
@aluflint You need to use a PSEye camera
