### ISSUE TITLE
New Hybrid Grip - Change hold duration for detection?

### ISSUE THREAD

**Issue by jaorg1234** [LibreVR/Revive#444]
Hey, just was testing out the new hybrid grip and generally love that feature. One thing I've noticed is that it sometimes doesn't try to hold something and instead simply toggles the grip function on.

Is there a way to change the duration needed to hold the grip button for the game to detect a non-sticky grip? E.g. instead of holding it for more than 1s, reducing that duration to just 0.6s.

You notice that when playing Dead and Buried and using the bow that it often toggles instead of just holds the grip button when quickly drawing the bow and letting go.

**Comment by Armada651** [comment]
Actually the default is already set to 0.5s. I was worried about going lower than that, because some people might miss that timeframe.

You can change it in your `steamvr.vrsettings` by setting the `ToggleDelay` property, which is set to 0.5 by default.

**Comment by jaorg1234** [comment]
Thank you! Can be marked as solved. Only noticed that problem when using a bow.
