### ISSUE TITLE
Chaperone Fade In - Delayed

### ISSUE THREAD

**Issue by jaorg1234** [LibreVR/Revive#445]
Hey, sorry for posting another issue I've noticed while demoing Superhot VR to a few friends. One of my friend punched one of the walls and when I asked him why he didn't stop moving towards it, he said that the chaperone appeared very late.

I tested the same thing in several games afterwards and it looks like the Chaperone grids only appear extremely late as if the fade in doesn't work and it only appears when it is fully opaque.

Limitation of Oculus SDK or a bug?

Edit: also tested the same thing within a SteamVR game and had no issues with the Chaperone. Only happens with Revive/Oculus Home games.

**Comment by Armada651** [comment]
I doubt it's a bug with Revive unless the Oculus game is constantly requesting the guardian system be turned off.

I'll look into it, but it's unlikely that it is Revive-specific.

**Comment by jaorg1234** [comment]
Tested it with both Dead and Buried + Superhot VR.

**Comment by jaorg1234** [comment]
Did a little bit more testing:

If you have a small room and usually activate the Chaperone grid when extending both of your arms, then try to do the same with Oculus Home games. You'll see that it won't trigger the chaperone at all. If you do the same with the HMD it does activate it earlier.

**Comment by Armada651** [comment]
@jaorg1234 Are you comparing Oculus Home games with other native Vive games or are you comparing it with not having any VR application running?

**Comment by jaorg1234** [comment]
I'm comparing it with both just in the SteamVR environment and in native Vive games. With Oculus Home games I can consistently observe that the Vive wands do not turn on the chaperone until you are almost touching the border of the play space. Additionally, there is no cross-fade transition and it only pops in with full opacity.

You can easily test it out yourself:

- Keep your hands close to your body and try to move only your head to the edge of your play space until the chaperone kicks in
- Move a few cm back and now try to approach the border with one of your controller
- You'll see that the chaperone WON'T activate within the same distance as before and that you have to come much much closer.

This makes playing some games with Revive pretty dangerous.

**Comment by jaorg1234** [comment]
Here 2 quick videos demonstrating the problem:

Normal behavior within the compositor: https://youtu.be/4ExCynRgogY
Buggy behaviour in Dead and Buried: https://www.youtube.com/watch?v=1ny4XtZtFMQ&

I am actually touching a wall in the second video without triggering the Chaperone boundaries.

**Comment by Armada651** [comment]
The compositor has different chaperone behavior. It's unlikely that Revive is delaying the chaperone bounds. This sounds like a bug in SteamVR.
