### ISSUE TITLE
Still getting fatal error in UE4 Games

### ISSUE THREAD

**Issue by Vivatokyo** [LibreVR/Revive#447]
gtx 1080 i5

**Comment by Armada651** [comment]
Please put more effort into describing the issue if you want help.

**Comment by Vivatokyo** [comment]
it s me

https://github.com/LibreVR/Revive/issues/347

https://github.com/LibreVR/Revive/issues/441

**Comment by Armada651** [comment]
Then why make duplicates? I'm notified about each and every comment on the tracker, so all you're doing is adding clutter.

**Comment by Vivatokyo** [comment]
Ok I fixed it!
If you have Fatal Error problem do this:
1-Uninstall Revive
2-Uninstall completely Oculus software
Follow this https://www.youtube.com/watch?v=2WWrQncMNqs&app=desktop

(3-Install "Vive Setup" if you don't have it) *This one I don't know if it helps but it is what I did, I had only SteamVR and basic Vive drivers installed

4-Install Oculus Setup 
Create an account/sign in

When you are asked for 
  Rift or Rift&Touch 
SELECT RIFT&TOUCH! 

When they say plug the cables, skip

Once it is installed download Bullet Train
(In Oculus settings you also check allow unknown, I don't know if it helps...)

-Download and Install Revive

-Back to Oculus check if the game is downloaded then, go to settings, beta, restart... wait
Once restart you can close Oculus.

-Launch Revive program(.exe) and It ll launch also steamvr 
Put on ur Hmd 
Select Revive tab and Lauch Bullet Train

I hope it helps

I have to check the other UE4 games that gave me Fatal Error/Crash... But I think It will work
