### ISSUE TITLE
Superhot VR controllers not mapped

### ISSUE THREAD

**Issue by Terabiter** [LibreVR/Revive#448]
I just downloaded revive so i could play superhot on my HTC Vive but when I started playing it none of the controller buttons were working. Oddly though all of the tracking was perfect. I was stuck at the starting point where you're supposed to pick up the gun.

**Comment by Armada651** [comment]
You need to use the grip buttons on the side of the Vive controllers, not the touchpad.

**Comment by Terabiter** [comment]
Cool, thanks!
