### ISSUE TITLE
Can not open Revive due to permission error

### ISSUE THREAD

**Issue by GalacticRover** [LibreVR/Revive#449]
I try and download the latest version of Revive, save it and run it, then an error message pops up that says I do not have the permission to open this file, also Norton security deletes the file. Either that happens or another window pops up saying I have to allow access to open this file, in that case, I hit Continue, but it keeps popping up again and again saying Try Again or Cancel and does not download. Any ideas? ALL I WANT TO DO IS PLAY SUPERHOT!

**Comment by Armada651** [comment]
Sounds like your Virus Scanner is generating a false positive, you need to disable your virus scanner during the installation.
