### ISSUE TITLE
Show correct IPD in Unity information screen

### ISSUE THREAD

**Issue by brianjonespfk** [LibreVR/Revive#45]
I had a feeling that the IPD seemed a bit off in Revive games (I first felt this way in Lucky's Tale, had some eye strain) Pressing spacebar in Technolust pulled up the Unity information screen and showed the IPD was set to 64.00 (But my IPD is set to 60.8 on the Vive) Is there a way to set our IPD for Oculus games?

**Comment by LibreVR** [comment]
Fixed in commit 806306c3c541c749dc5d7c860bb2d98b3fa6393a.
