### ISSUE TITLE
Lost & Henry has no controls?

### ISSUE THREAD

**Issue by trendol** [LibreVR/Revive#450]
Hi,

New here. It seems I can't "Start" the experiences **Lost** or **Henry**. It's saying I need to start the games when pressing some Oculus Touch-buttons. I try all buttons on my Vive-controllers but nothing happens..?

Thanks.

**Comment by jaorg1234** [comment]
I think the game is using only controllers or the Oculus Remote. Try only turning on one of the Vive wands and then I think it should act like the Oculus Remote.

**Comment by Armada651** [comment]
@jaorg1234 is correct, you need to turn off one of the Vive controllers so the other one can be used as a Remote.
