### ISSUE TITLE
Standalone Superhot

### ISSUE THREAD

**Issue by JamesMcCloud** [LibreVR/Revive#451]
Hey guys,

i have a problem with Revive. I can play the oculus games...all fine but i have a standalone version of Superhot and i want to know how i can play it with revive. When i use the standalone link in the FAQ 
( https://github.com/LibreVR/Revive#standalone-games ) i always get to the main page and i dont know what to do. (sry im new to github)

**Comment by Armada651** [comment]
Only Superhot VR has VR support, standard Superhot won't work.
