### ISSUE TITLE
Channel Island Suite

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#453]
According to the compatibility list, this should be working, however couldn't get it to run.
I tried from the Revive overlay,  then I tried injecting, then patching.  It starts and I hear sound for one second and then it just quits. No error message on the screen.

Anything I can do?  I'm using latest 1.0.4.0.

Thanks!

**Comment by npglambert** [comment]
It's been a while since I've used this experience, I'll re-download & test here on Friday. But I can confirm it was working.

**Comment by npglambert** [comment]
Downloaded & still working here. Ditto on 1.0.4.0 on Revive & launched from Revive overlay. The only thing I always do is start my VR session by launching Revive from Windows. But I don't think it'll make a difference.

**Comment by kvdv99** [comment]
How did you run it?

**Comment by npglambert** [comment]
Sorry, but runs perfectly. I only have the HP Envy bundled with the Vive in the UK, so Radeon 480 & i5, so nothing special. I just downloaded in Oculus Home & ran via the Revive tab in Steam.

**Comment by kvdv99** [comment]
Ok, it's working now.. thanks
