### ISSUE TITLE
Where is the Revive tray icon?

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#454]
I just bought Dirt Rally through Steam and read the Revive instructions to patch it by right clicking on the tray icon and locating the exe file.  I don't see the tray icon even when I click to show all of them.  Does it need to be enabled somewhere?  Is that the only way to patch games?

**Comment by Armada651** [comment]
You need to have SteamVR running.

**Comment by lghtanddrk** [comment]
Ah, maybe that's the issue.  I was looking for it without SteamVR running. Thanks.  I'll try that.
