### ISSUE TITLE
Potential Improved Touchpad Mapping Concept

### ISSUE THREAD

**Issue by MehStrongBadMeh** [LibreVR/Revive#456]
Depicted below is an idea I have been having for an alternate touchpad  mapping scheme that may improve the usability of the thumbsticks while also adding the functionality of the thumb rest area of the touch controllers.
![msbm_thumbpad_concept_left](https://cloud.githubusercontent.com/assets/1563179/21906232/76cb065a-d8d8-11e6-8a31-eb4bb53f4a14.png)![msbm_thumbpad_concept_right](https://cloud.githubusercontent.com/assets/1563179/21906234/79eb7360-d8d8-11e6-8e65-dc5361d31747.png)
The larger, round design of the stick areas could potentially allow for the use of absolute thumbstick positioning. The placement of the thumb rest areas is close to where my thumbs sit when resting off of the touchpad. The face buttons should remain easy enough to use, as they are still positioned so hitting the bottom edge will activate A or X and hitting the side edge will trigger B or Y.

Feel free to use, modify, or toss this concept as you please.

**Comment by Armada651** [comment]
The problem with this design is that the touchpad on the Vive controller don't track the finger position on the edge very well.

On absolute thumbstick positioning, from my personal tests you never want that even if you dedicate the entire touchpad to the stick. The reason for that is that you don't really have a good sense of the center of the touchpad while in VR.

**Comment by MehStrongBadMeh** [comment]
Fair enough. Reducing the size of the thumbstick circle a bit (thereby increasing the size of the face buttons and thumb rest area) could potentially overcome the edge sensitivity issue while still allowing for an improved area for relative stick movement.

**Comment by Armada651** [comment]
This has been addressed in commit b73a413518c2af017a9877b337f671b8b72df207.

By making use of the deadzone the entire touchpad surface can be used as the thumbstick.
