### ISSUE TITLE
Revive won't Open Games in VR

### ISSUE THREAD

**Issue by MisterFoxx** [LibreVR/Revive#458]
Hello,
so i did the installation exactly as described. I can also see my Games in the Revive Dashboard in VR, but when i try to start a game it opens up on my Monitor and freezes after roughly 10 seconds (Game:Superhot VR). In VR i only see the Revive Dashboard loading but not doing anything and Steam VR on PC is showing me that it tries to launch Superhot VR.

I made sure several times that im using the latest version and reinstalled everything twice.

 thanks for your help in advance

**Comment by itorrey** [comment]
I think something changed on the Oculus side because things worked fine for me until today when I bought and installed Medium and then when I went to play VR Sports Challenge I had the same issue as you. I get it displayed on my monitor and it just freezes up.

**Comment by LorkHang** [comment]
I don't think so. I was playing unspoken 15 mins ago.

**Comment by itorrey** [comment]
VR Sports was working fine until I installed Medium. During install it said it had to install something else in order to complete installation. Once I accepted that and it installed it, all revive games display on monitor for me and freeze up.

**Comment by MisterFoxx** [comment]
So i found out i was just to stupid to install revive in the correct folder. I had it installed in program files but not in program files (x86). No it all works just fine :)

**Comment by Armada651** [comment]
That's not the correct folder though? Revive is mostly a 64-bit application...

But if it works for you, then that's fine I guess.

**Comment by MisterFoxx** [comment]
Yeah i dunno. I watched a Youtube Video where the uploader said you have to install it in this specific folder and it worked.

**Comment by LorkHang** [comment]
Install Location shouldn't matter, I had Revive installed in my Oculus folder :P
Maybe It just works after you reboot your system.
