### ISSUE TITLE
Revive wants to update on every SteamVR launch

### ISSUE THREAD

**Issue by SimplexPL** [LibreVR/Revive#459]
Every time I start SteamVR, Revive finds new version 1.0.4, claiming that I have 1.0.3.1. I completely uninstalled revive and installed freshly downloaded 1.0.4 and it still happens. My revive installation folder is not default (C:\Games\Revive), maybe that is a problem?
![screenshot 2017-01-13 20 29 11](https://cloud.githubusercontent.com/assets/25101733/21942886/1b06dc2a-d9cf-11e6-9367-e8cbbf9c0df8.png)

**Comment by Armada651** [comment]
Sounds like you have two installations of Revive on your computer, these will conflict and only one will actually launch with SteamVR.

**Comment by SimplexPL** [comment]
You were right, I should have checked before.
However, I was not informed in any way that there are two installs, I did not know which "instance" or Revive is automatically starting when SteamVR starts - for some reason it was not the version that I installed using the installer, but a different, standalone version.

**Comment by SimplexPL** [comment]
I'm closing this, but perhaps there should be some kind of mechanism which can detect multiple versions of ReVive?
