### ISSUE TITLE
Launch games via command line

### ISSUE THREAD

**Issue by yegors** [LibreVR/Revive#461]
Is there a way to launch games through Revive via command line? 

Something along the lines of

ReviveInjector_x64.exe --launch "C:\Program Files\Oculus\Software\Software\superhot-superhot\superhotvr.exe"

**Comment by Armada651** [comment]
Yeah, it works just like that. Just without the `--launch`.

**Comment by yegors** [comment]
I tried that, I keep getting an error

"Failed to create process".

**Comment by Armada651** [comment]
Then the path is simply incorrect.

**Comment by yegors** [comment]
You're right about that, made a typo. Thanks.
