### ISSUE TITLE
Oculus Home Wont Download

### ISSUE THREAD

**Issue by DaDC709** [LibreVR/Revive#463]
So It Says Oculus Isn't Connected To It Servers. Do I Need To Unplug The Vive. Plz Help

**Comment by Armada651** [comment]
Can you provide a screenshot of the error message?

**Comment by DaDC709** [comment]
Its Not Really A Error Message It's Just A Probrlem Which Refuses To Go Away
![oculus failure](https://cloud.githubusercontent.com/assets/25136939/21964986/f5268200-db4d-11e6-81f0-81197dbdde35.png)
Also Sorry The Image Has Pixels

**Comment by Armada651** [comment]
Well that's just the installer that can't connect to the internet. Check your firewall or maybe you tried to block the Oculus servers?

If you can't get it to work, contact Oculus Support. This is not a Revive problem, this is a problem with their installer.

**Comment by DaDC709** [comment]
Ok Thanks :) Btw i installed Revive Easily And Nothing Bad Happend, So
Positive Review :)
