### ISSUE TITLE
Can't fin Superhot in Revive tab

### ISSUE THREAD

**Issue by davidbouche** [LibreVR/Revive#465]
Hello,

I've bought a SuperHot licence on Steam.
I'd play it in VR, HTC Vive, so I follow the revive install's steps.

When I open the Revive tab, I do not see SuperHot.
I can launch all the other games (4 titles) from the Revive tab without any problem.

Thanks for your support,
Willou

**Comment by npglambert** [comment]
I'm not 100% sure, but I think you'll find that SuperHot on Steam is not for VR. Also Revive is for Oculus applications, so it will not show up there.

**Comment by Armada651** [comment]
Only SuperHot VR has VR support.
