### ISSUE TITLE
Massive lag spike every 8 seconds - reproducible 

### ISSUE THREAD

**Issue by craigspree** [LibreVR/Revive#466]
Hi - first off Revive is AWESOME - thank you for making it!

**Issue**: Every 8 seconds when using Revive, I experience a massive lag spike (200ms).

**Impact**: Makes all VR multiplayer virtually unusable due to intermittent lag spikes (Smashbox, Raw Data, QuiVR, etc)

**Reproduction steps:**
1. Install PingTracer for monitoring, set host to iad.valve.net (Steam's east coast game server), and click Start. You can get PingTracer here: https://pingtracer.codeplex.com/ (To rule out an issue with iad.valve.net, you can also ping Google.com if you prefer).
2.  (Ensure Revive - 1.0.4 is installed) Start SteamVR.
3. Note that every 8 seconds you will receive a latency spike near 200ms (see the yellow bars in the graph here: http://imgur.com/J8VMiTR). This should start within 8 seconds of the Lighthouses detecting the HMD. The controllers do not need to be turned on for the lag spikes to happen.
4. Quit SteamVR - notice the graph in PingTracer returns to normal.
5. Uninstall Revive 1.0.4.
6. Launch SteamVR - notice there are no more lag spikes. As you can see here, at 3:44PM I uninstalled Revive, then opened SteamVR. No more latency spikes.
7. To make the lag spikes appear again, quit SteamVR, reinstall Revive 1.0.4, and restart SteamVR. Within 8 seconds the same lag spikes appear.

This issue has been testing my sanity for a week. I originally had a USB WiFi adapter, and thought that the network latency spike from the Vive was due to the USB WiFi adapter. Today I replaced the USB WiFi adapter, removing it completely, and installing a PCI WiFi adapter (TP-Link N900) and the same issue was happening. I stumbled onto this thread on Reddit which lead me to this solution. https://www.reddit.com/r/Vive/comments/5ctrtw/steamvr_ping_issue/

Note I tried many other solutions before realizing the issue was related to Revive, such as uninstalling the HTC Vive Home software, but that did not solve the issue. Following the steps above solved the issue.

**Comment by Armada651** [comment]
Can you send your logs from `%APPDATA%\Revive`?

I have no idea how Revive could cause latency spikes. The only networking capabilities that Revive has is when an Oculus Game is installed/uninstalled (detected by watching the filesystem). The only thing I could imagine is if Revive was in some sort of install/uninstall loop, but that should definitely turn up in the logs.

**Comment by craigspree** [comment]
Logs attached.

Were you able to try running through the reproduction steps above? From what I've been reading, this happens anytime **any** extension is added to the dashboard. Adding any extensions to the dashboard causes network issues when SteamVR is running. People have reported it when using Vive Home, Revive, and Advanced Settings. It's very odd that the two are related, but it's been consistently reproducible for me and that poster in the reddit thread above from 2 months ago.

[Revive_Logs.zip](https://github.com/LibreVR/Revive/files/709627/Revive_Logs.zip)

**Comment by Armada651** [comment]
`Generating manifest for oculus-oculus-medium-retail`

Looks like you recently installed Oculus Medium, but that's about it, no loops or anything. So like you said it's not an issue I can fix in Revive. Try reporting it to the OpenVR issue tracker: https://github.com/ValveSoftware/openvr/issues

Or the SteamVR developer forums (Valve emloyees read those thread regularly): http://steamcommunity.com/app/358720/discussions/
