### ISSUE TITLE
Through The Ages - Yosemite National Park in VR won't launch

### ISSUE THREAD

**Issue by Kabong** [LibreVR/Revive#467]
The program crashes immediately upon attempting to launch both via the revive dashboard interface and starting via injection. Also tried patching, but that didn't seem to do anything either. I was curious if anyone has been able to get this to work through Revive?

https://www.oculus.com/experiences/gear-vr/1093969387345142/

**Comment by Armada651** [comment]
This application performs very badly even when it does start. There is no known fix yet.
