### ISSUE TITLE
Superhot won't start after first try

### ISSUE THREAD

**Issue by michaelmsheen** [LibreVR/Revive#468]
Everything was great, I quit Superhot and opened VR Sports Challenge, everything still good. Then, when I opened Superhot again it won't load past a black screen. I've tried reinstalling it. Any help would be appreciated, thanks.

**Comment by ecnahc** [comment]
It took me a few tries before it worked. I haven't tried again, so I'm sorry I can't give technical advice yet, but when I was fiddling with it I remember it took a few tries before it started again.
