### ISSUE TITLE
Blaze Rush not running

### ISSUE THREAD

**Issue by KLWN** [LibreVR/Revive#47]
Hi Everybody,

I was wondering if somebody got Blaze Rush successfully running? I cant get mine to work with Injector.

cheers,
Alex

**Comment by Kaesemuffin** [comment]
Hey KLWN

I don't actually own that game, but are you sure that this game uses either Unity or Unreal Engine?
From the looks of it ^^ idk seems not to be the case :D

**Comment by LibreVR** [comment]
@Kaesemuffin Revive is in no way limited to Unity or Unreal.

**Comment by KLWN** [comment]
could you please add this game? Its the greatest game every :D its so addicting and fun to watch

**Comment by lchamp** [comment]
BlazeRush works for me, no problem at all.

**Comment by LibreVR** [comment]
@KLWN If you're still experiencing this issue, you should give more details of what you've tried and what kind of errors you get.

Closing this issue for now, but feel free to leave a comment if you need it reopened.
