### ISSUE TITLE
The Climb grips won't work

### ISSUE THREAD

**Issue by RwdFive** [LibreVR/Revive#470]
When I started The Climb tutorial it worked perfectly and I finished it. It brought me back to the level select menu. My dad tried doing the tutorial but whenever he tried to grip it wouldn't work.

**Comment by Armada651** [comment]
What else have you tried? Did you try doing it yourself again? Which buttons did you try? Is it only the tutorial, did you try any other level?

Please provide as much detail as you can when reporting issues.

**Comment by RwdFive** [comment]
Yes I tried the tutorial and one of the levels multiple times and the grips still wouldn't work. I tried using the side grips, the thumb pad, the trigger and a combination of those.

**Comment by Armada651** [comment]
Are you trying to grab a ledge or are you trying to re-chalk your hand?

**Comment by RwdFive** [comment]
I'm trying to grab the ledge, chalking works fine.

**Comment by Armada651** [comment]
I can't reproduce this problem at all and you're the only person to report this issue. Without any more evidence I don't believe there is an issue.

**Comment by MiniDigger** [comment]
I have to same problem. I can launch the game just fine but once I am in the tutorial I can't grab the first ledge by any combination of the buttons on the controllers. I also tried to play with the grib mode in the open vr advanced settings but with no success. I read somewhere that you can switch up the controls to something more friendly in the options, anyone happens to know how I can access those from the tutorial?

**Comment by RwdFive** [comment]
I found that iAd you reinstall the climb it the grips work again

**Comment by RwdFive** [comment]
*if*

**Comment by Armada651** [comment]
@RwdFive That's because that likely resets the `\user\options\default\attributes.xml` file.

**Comment by JustThatFoxKid** [comment]
the option name is
<Attr name="TouchGrabInverted" value="true"/>
