### ISSUE TITLE
ZeldaVR

### ISSUE THREAD

**Issue by OOLuigiOo** [LibreVR/Revive#475]
https://www.reddit.com/r/oculus/comments/58z8te/where_is_zelda_vr_beta_20_and_beyond/

https://www.google.com/search?client=opera&q=Legend+of+Zelda+with+the+Oculus+Rift&sourceid=opera&ie=UTF-8&oe=UTF-8#q=zelda+vr+beta+2.0+download&tbm=vid

Is this possible to run in Vive?

**Comment by Armada651** [comment]
DK1/DK2 games are not supported in Revive.
