### ISSUE TITLE
Launch oculus home game from command line

### ISSUE THREAD

**Issue by ni-jj** [LibreVR/Revive#476]
Is there any way to launch oculus home game from command line?
I tried inject,but it did not work.

**Comment by Armada651** [comment]
I don't think the command-line tools will help you. What are you trying to inject into? Do you have a virus scanner running other than Windows Defender?

**Comment by ni-jj** [comment]
For example,I can launch “bullet train” from revive dashboard in my headset,but when I use a command line,the log is below:
C:\Program Files\Revive\Revive
λ ReviveInjector_x64.exe "D:\OCULUS_APP\Software\epic-games-bullet-train-gdc\BulletTrain-GDC-1.8SDK\showup.exe "
Launched injector with: ReviveInjector_x64.exe  "D:\OCULUS_APP\Software\epic-games-bullet-train-gdc\BulletTrain-GDC-1.8SDK\showup.exe"
Creating process: D:\OCULUS_APP\Software\epic-games-bullet-train-gdc\BulletTrain-GDC-1.8SDK\showup.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xc8e2f610
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xc8e2f610
Injected dlls successfully

the game was launched successed,but nothing happend in my headset.I just want to know wheather I can use command line for oculus home game,thank u for ur reply.

**Comment by Armada651** [comment]
You're launching the wrong command-line arguments. Try launching it through the dashboard and then opening that log, it will show the correct command-line for you.

**Comment by ni-jj** [comment]
Thank u,I used wrong command-line arguments.But another problem,when I use alt+tab switch the game to background,and then switch it back,the headset will lost the game screen and go into blank.

**Comment by Armada651** [comment]
Sounds like an unrelated bug, I'll close this issue as it is solved. Please create a new issue for the alt+tab problem.
