### ISSUE TITLE
Adr1ft not working.

### ISSUE THREAD

**Issue by 6DB** [LibreVR/Revive#48]
Game is installed via Oculus home. Dragging ADR1FT-Win64-Shipping.exe onto ReviveInjector.exe will cause Adr1ft to begin loading and then very quickly closes. I have restarted pc and Adr1ft still doesn't work.

**Comment by LibreVR** [comment]
Sounds like a crash, I'd buy it on Oculus Home to test, but I heard it would get OpenVR support soon...

Maybe I can reproduce the crash on the Steam version?

**Comment by 6DB** [comment]
I was able to get an Oculus home version as I already own the Steam version, I can get neither version to work with my HDK 1.4. I'll just have to wait for the OpenVR support.

**Comment by LibreVR** [comment]
HDK 1.4? Are you using the OSVR headset?

Their OpenVR support is till in alpha, so that may very well be the issue. I don't support using this injection layer with headsets other than the Vive.

**Comment by gormanj** [comment]
I have Adr1ft from Steam and though it launches, it will not display on the Vive with Revive.
