### ISSUE TITLE
Landfall Open Beta

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#483]
Not yet supported I guess,  tried from Revive dashboard, inject and patch but I always see the messsage "please connect controller".  I'd love to try this game out..

**Comment by jaorg1234** [comment]
You have to use a controller, otherwise it is not working. (I'm using a PS3 controller acting as Xbox 360 controller).

Even on the Rift you have to have a controller connected, otherwise the Touch controllers won't work as regular gamepad.

**Comment by kvdv99** [comment]
Indeed, sorry, my bad..
