### ISSUE TITLE
Revive not working with Superhot through Steam

### ISSUE THREAD

**Issue by spiderworm** [LibreVR/Revive#487]
I purchased Superhot through Steam, and I have the latest Revive installed. I purchased Superhot today, and used the Revive right-click menu to patch the executable. When I do that, the game immediate launches, but always on my desktop only, in 2D mode, not in VR. It also doesn't show up in my Revive dashboard. Help?

**Comment by Werbel** [comment]
Superhot on Steam is not VR version. It's just old PC version of game. VR version was not yet released on Steam, it's only available through Oculus Home.

**Comment by spiderworm** [comment]
That... would explain it! Whoops! Thanks!
