### ISSUE TITLE
Robinson: The Journey

### ISSUE THREAD

**Issue by isequence** [LibreVR/Revive#489]
Hi 
I am wondering if Robinson: The Journey is working with Revive? 
It is made by Crytek who made The climb. So I assume it works too? 
Many thanks. 
Sam

**Comment by C-R-O-N-O-S** [comment]
I have problems.

"Platform error" User is not entitled.

Oculus service restart and revive patch cant help! (reboot also) :(

**Comment by kvdv99** [comment]
Oh yes,  I'd love to play this game too!

**Comment by Rojoyinc** [comment]
me too if it works

**Comment by LilMissJustine** [comment]
I just bought it on Oculus Home, and it works through revive through SteamVR overlay.  Works great for me, at least for the first 30 min.

**Comment by kvdv99** [comment]
> I just bought it on Oculus Home, and it works through revive through SteamVR overlay. Works great for me, at least for the first 30 min that I have played so far. Have to use game pad though for controls.

That's weird, because everyone is talking about an entitlement bug that prevents everyone (including Rift owners) from playing this game?...

**Comment by LilMissJustine** [comment]
> That's weird, because everyone is talking about an entitlement bug that prevents everyone (including Rift owners) from playing this game?...

Well, I bought it yesterday after work from the oculus store, then opened up steamvr, put on my headset, navigated to revive and was able to open up and play it.  Not sure why it didn't work for them, but it worked for me.  Maybe some kind of patch or something.   Anyways, just wanted to say that yes, it did work for me...purchasing from the Oculus store and then playing using SteamVr.  Not sure what kind of evidence you need from me.....  

The performance is...ok.  Playing on GTX 1070 with 1.4x SS.   At least it performs way better than the climb.  Can only use xbox controller though, as it doesn't seem like it supports touch controllers.

**Comment by kvdv99** [comment]
I think you answered the question..  the Oculus store version is working and the Steam version is (currently) not.  Thanks.

**Comment by kvdv99** [comment]
Oculus Store version is defintely working with Revive but you need to disable asynchronous reprojection, otherwise it crashes. At least with me it did.

**Comment by mrbelowski** [comment]
Async doesn't crash it for me (Oculus store version). It does crash quite a lot when changing gfx settings though (but it's more stable if you change settings from the in-game, rather than pre-game menu)

**Comment by kvdv99** [comment]
Weird, it constantly crashed (every 2 or 3 minutes), totally unplayable, until I disabled async reproj. in SteamVR settings, and it hasn't crashed once since I did that!  Loving this game btw.

**Comment by Armada651** [comment]
I've tested the Steam version, it works if you follow the patching instructions, but it requires some extra work. Namely after patching it you will need to go to the folder with the executable and rename `xinput1_3.dll` to `xinput9_1_0.dll`.

For some reason they decided to use a really old version of XInput, so the assumption that every VR games uses XInput 1.3 breaks down.

**Comment by Armada651** [comment]
In the next version of Revive both DLLs will be replaced: dee4a26645d364adc8d5f7b82ea1c8a6dae3ae0a

**Comment by Bonhovis** [comment]
Awesome. Thank you Armada651!

**Comment by peteostro** [comment]
THANK YOU!!

**Comment by gormanj** [comment]
Armada, thank you very much for your tip. It's a great game.

**Comment by franzbots** [comment]
Hello there !
I've just bought Robinson on steam, then updated Revive, and though, the game still doesn't work, with the warning message on screen "hardware issue : no VR headset available". 
Did I miss something ?
Thanks.

**Comment by gormanj** [comment]
Did you rename the xinput dll file as per Armada651 up above indicated in this thread? It did not work for me until I did that.

**Comment by franzbots** [comment]
Sorry for the newbie question, but where is that dll ? I looked into the game exe folder, and into the revive exe folder too, but I didn't see that dll.

**Comment by gormanj** [comment]
It's in bin/win_x64 in the game folder.

**Comment by franzbots** [comment]
That's what I though.
But in that folder, I don't have that dll.
Here is a screenshot of it :
![sans titre-1](https://cloud.githubusercontent.com/assets/26135816/23515119/893260d8-ff69-11e6-8a19-3b7419a18f1f.jpg)

**Comment by gormanj** [comment]
Okay, sorry about that. I think you need to run the patch from revive in your system tray (right click). Then select that .exe in the that folder. Then after you patch, you will have the file in the post that you can rename.

**Comment by Armada651** [comment]
@gormanj It's no longer necessary to rename it, Revive will use both DLL names since version 1.5

**Comment by franzbots** [comment]
Yes, excellent, it works now. Indeed, just patched it. Thanks guys !

**Comment by gormanj** [comment]
Thanks Armada651! I'm really looking forward to RoboRecall.
