### ISSUE TITLE
Worked yesterday, today all games say cant find headset?

### ISSUE THREAD

**Issue by robotica72** [LibreVR/Revive#49]
Was having no issues with Revive, but after 0.4 I downloaded a few more demos from the Oculus store and now nothing will detect the headset when I pull the exe to the executable....  Was working great since 0.2 - Luckys Tale wont Start, Dreamdeck, etc.... they all say you need an oculus to play or no headset detected... Any ideas?

**Comment by LibreVR** [comment]
Sounds like LibRevive failed to load or the ReviveInjector failed to inject. I'll make the next version of the injector more verbose in case of an error.

**Comment by KLWN** [comment]
had the same issue, back then i accidentally configured a remote and then the software checked for components and since then I received the same error as you. I tried to reinstall but the message popped up every time. Yesterday I setup Windows again and everything works again.

**Comment by robotica72** [comment]
Thanks for the quick replies - Yeah, reinstalling would be a pain for me, its my main gaming PC, just a nightmare if I can avoid it... LibreVR - Thanks, when you add some error logging Ill get some logs over to you...

**Comment by robotica72** [comment]
Think I got it - Didnt have to do this before, but each Oculus Game/Demo worked when I gave the revive executable run as admin.... So all cool now :)

**Comment by Cameronlreid** [comment]
Setting to run as admin did not solve the problem for me. Does this support 64 bit systems?

**Comment by robotica72** [comment]
Cool - Good to hear, at least others can read this thread if they have issues and it may help.

LibreVR - Awesome software .....  Im staying away from buying from the Oculus store for now, but the way you are progressing, Im sure Ill buy something there soon to test out.
