### ISSUE TITLE
Robinson: The Journey, steam edition

### ISSUE THREAD

**Issue by Tyrminaotr** [LibreVR/Revive#490]
I can buy it on Oculus home, but it is also available on Steam. I see on compatibility list that Oculus Home version works, but it's not listed on Steam Oculus gems list... 
Does the Steam version works also?

**Comment by mapotter99** [comment]
Right now, the Steam version has an entitlement bug preventing anyone (even Rift owners) from playing it.

I found this out the hard way. 

We won't know if it works with Revive until this bug is fixed. 

http://steamcommunity.com/app/579820/discussions/0/133256758575308671/

**Comment by LilMissJustine** [comment]
I bought it on Oculus home and it works for me.  I have heard of entitlement issues from Steam Version, which is why I bought it from Oculus home.   Works wells.

**Comment by Tyrminaotr** [comment]
But still if it will be possible - I prefer Steam version. There is (potential) possibility that they will add OpenVR support and (maybe) vive controllers. When I will buy in on Oculus Home I will not be able to update to that in the future.

**Comment by Rojoyinc** [comment]
right same here - and STEAM supports the VIVE. I prefer to buy from steam
instead of occulus - and then we get free updates to HTC version later.

**Comment by Armada651** [comment]
Duplicate of #489.
