### ISSUE TITLE
Failed to Launch 

### ISSUE THREAD

**Issue by BroHawk69** [LibreVR/Revive#492]
So I tried launching some games from Steam that I got from the Oculus store and it says "Failed to launch _______" The only thing that works is the character creator. I tried launching it from the Oculus client, and in the headset itself.

**Comment by Clothednblack** [comment]
Did you install revive?

**Comment by BroHawk69** [comment]
Yes. I have also tried launching from Steam, but same result.

**Comment by Clothednblack** [comment]
I'm assuming that the games you got are on the compatibility list and you did part of the setup for oculos (without finishing the hardware setup)? I had the same problem till I set up oculos then quit setup when it asked to confirm the actual hardware.

**Comment by Armada651** [comment]
Can you post your logs from `%APPDATA%\Revive`? Just enter that into the explorer address bar, rename them to .txt files and drag them in the comment box below.
