### ISSUE TITLE
The Town of Light (Steam)

### ISSUE THREAD

**Issue by leppermessiah1** [LibreVR/Revive#493]
This game isn't listed on the compatibility list, and I'm hearing mixed results as to its playability using Revive.  Have you had any experience getting this game functioning?

**Comment by Armada651** [comment]
If I recall correctly that game only has DK2 support? DK2 games are not supported in Revive.

**Comment by srt23** [comment]
Actually it works well enough. I played through the whole using revive back in June. Haven't tried it since though, so can't say for sure if it works now after all the updates to both revive and the game.
