### ISSUE TITLE
Minecraft: Windows 10 Edition not working

### ISSUE THREAD

**Issue by BroHawk69** [LibreVR/Revive#495]
Whenever I try to launch MCW10, it loads in the headset, checks for updates, then launches. The moment the launcher closes, it crashes and I can't launch it unless I restart SteamVR, no crash logs or anything.

**Comment by hyperseven** [comment]
never has worked, check the compatibility page:
https://github.com/LibreVR/Revive/wiki/Compatibility-list

**Comment by Armada651** [comment]
OpenVR doesn't support Windows Store apps, so it's not possible for Revive to support Minecraft. Try Vivecraft instead.
