### ISSUE TITLE
Install games without headet

### ISSUE THREAD

**Issue by SarahSmythe23** [LibreVR/Revive#496]
I have installed revive and the store/starter experiences are showing up and playable via the revive button on the SteamVR menu screen. However, I am unable to install a new game I bought from the OR app/store - it seems because I have no headset connected. So, I cannot see how to add the game(s) I want to play. Any advice? Perhaps I did something wrong?

Thanks in advance

**Comment by Armada651** [comment]
Once you download a game through the Oculus Store it will automatically be added to the SteamVR dashboard.

**Comment by SarahSmythe23** [comment]
The game is not downloading through the Oculus Store - that's the problem. In my library I have the silos "installed", "updates", and "not installed". The game is in the "not installed" silo. If I mouse over it, I get the option to install. Clicking that option causes a pop in message saying that they are unable to install, and to check support for help. I have, but no fixes there. I am just assuming that it won't install because I have not registered/connected a headset? Thanks for trying to help.

**Comment by hyperseven** [comment]
Nothing to do with ReVive?  
I suggest you contact Oculus support since you can purchase and install without needing a HMD.

**Comment by SarahSmythe23** [comment]
Thank you, I will do that :)
