### ISSUE TITLE
After exiting game, can't click on new revive game

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#499]
So after starting a game.... it works right when I launch revive... but when I close out of a game, in the revive Menu ... I can't click anything .. it's like stuck scrolling up and down when I move the blue laser selector.... only way to fix this is to restart revive from the dashboard and then I can click on and launch new games again in the steam VR revive menu... very annoying :(

**Comment by Armada651** [comment]
I can't completely fix this problem, since it's a problem in OpenVR itself. But this should at least make sure it doesn't happen as often: 91a2abc65060198eafbd3f1434980384b2ccc07e
