### ISSUE TITLE
Farlands launches and loads but you can't take a snapshot of the gray creature

### ISSUE THREAD

**Issue by mcassano** [LibreVR/Revive#5]
Something appears to be off in the compatibility layers communication of 3d position.  Load Farlands and after doing some basic tasks it asks you to take a snapshot of the gray creature.  When you move your head in and out the reticle changes but the "30" never changes.

**Comment by LibreVR** [comment]
Interesting, I wasn't even aware that Farlands was working at all, when I tested it I just got a crash and nothing else. I will get right on this one tomorrow.

**Comment by mcassano** [comment]
Maybe you tried injecting from the root oculus-farlands directory instead of the ww/binaries one?

Ok, I have been messing around with this photo issue for a half hour and I think it might be related to the controller mapping code.  I am using a wired X360 controller and the game wants you to use the D-pad.  But while the game is launched in HMD you can also control it with the keyboard.  No matter what I do releasing right d-pad won't take the photo but if I use the right arrow key on the keyboard it works right away.

I no longer think this is at all related to 3d position but more about the event that is triggered when you release the dpad or maybe specifically the right dpad.

**Comment by mcassano** [comment]
Sorry for the comment spam but this guy on Youtube using a Rift is exactly the same problem I am having in the Vive.

https://www.youtube.com/watch?v=TK-xy3WI6eQ&t=1m15s

He just randomly gets it to work, I could not.  I tried spamming the photo function for ten minutes and it won't trigger.  If I use the keyboard right key it works.  Maybe this is just purely a game issue?

**Comment by flynn23** [comment]
Having the exact same issue, and I'm using an Xbox One controller.

**Comment by miketucker** [comment]
Getting the non-trusted source error when attempting to drop "ww-Win64-Shipping" exe onto ReviveInjector. That method worked fine for Dreamdeck and LOST.

**Comment by vcshih** [comment]
I've played farlands on dk2 and I had problems with that first picture also. With enough head wiggling it ends up working and subsequent pictures are fine. I'll try it with vive later to see if the rest of the game also has this issue as it is only the first picture which needs the zoom in to proceed.

**Comment by saluk** [comment]
The entire game has this issue for me - I can only take pictures by using the arrow keys on my keyboard. Everything else seems to work OK.

**Comment by LibreVR** [comment]
Fixed, probably by commit fdb9b9d02782595a423a06572b08d6f1bfd96b9d. Will be part of the next release.
