### ISSUE TITLE
Chronos not working - "Please check that your headset and sensor are connected"

### ISSUE THREAD

**Issue by subcommander** [LibreVR/Revive#50]
Occulus app version 1.3.2.208104 (1.3.2.210591)
Chronos game version 1.1

I just downloaded Oculus desktop app and Chronos but was unable to get it working. 

At load up, the Vive never switches from Vive Home to Chronos, Instead the Oculus and then Gunfire opening animations appear on my desktop monitor in full screen mode. It then flashed to the Chronos title screen where I receive the message "Please check that your headset and sensor are connected". When I clicked OK on the message nothing happens and I am unable to close the message. I am stuck at this point on the title screen.

I was sure to drag Chronos onto the injector (if you do it vice versa you receive a "Failed Entitlement" message). I also set all files to run as admin. It tried the x86 file. I tried the Chronos-Win64-File in Chronos > Binaries > Win64.

**Comment by vraddict** [comment]
Hi Have no problem with Chronos working.... you need oculus store open and place the injector in C:\Program Files\Oculus\Software\gunfire-games-llc-chronos\Chronos\Binaries\Win64.. make sure you have VR Running. also sometimes to get it working you will need to reboot the system.... hope this helps... let me know

**Comment by lchamp** [comment]
Same here, my Chronos is working too.

I just had to change _C:\Program Files (x86)\Oculus\Redistributables\directx-june-2010--DirectXRedistJune2010_ to "run as administrator" (in rightClick>property>compatibility) otherwise I couldn't start a new game.

Also, you might need to have your Vive controllers turned on (even if you'll play with your 360 controller).

**Comment by LibreVR** [comment]
I can also confirm Chronos is working fine.

**Comment by baggyg** [comment]
I am not sure if OP has the same setup, however this problem might be related just to Quest via Virtual Desktop / ALVR. I can run this fine through Vive Pro but have exactly the same issue on Quest.
