### ISSUE TITLE
question on standalone games

### ISSUE THREAD

**Issue by NinFanBoyFTW** [LibreVR/Revive#502]
Hi. I just wanted to know, I have been using Revive with the vr virtual boy emulator "VBjin VR" and it works great but I was wondering if there was any way to have a feature where you can create a new shortcut of whatever program you are using that automatically launches with revive enabled. I currently use the revive injector and drag the program onto the injector to get it working but I would like it if I could just click one shortcut and have it do that for me. This is also so that I can launch it from steam as right now I just have a placeholder icon that work work with revive. Thanks

**Comment by Armada651** [comment]
1. Add the injector as a non-steam game
2. In the target box append the path to the standalone game at the end, separated by a space
3. Check "Include in VR Library"
