### ISSUE TITLE
Empty revive menu in steamVr

### ISSUE THREAD

**Issue by jmbihorel** [LibreVR/Revive#504]
Hi, 
First, thank you very much for your work, it is a game changer for vive.  
I installed my vive headset yesterday and right away tried to instal revive in order to work with oculus medium and Quill. I did all the required step (I quit before the installation of the oculus hardware but oculus home tells me the headset is missing) I installed the apps I wanted, I installed revive. I can see the revive logo in steamVr but it seems to be empty. Instead, I can see the apps showing up in the steam section. I can launch Lucky's tale, dreamdeck and first contact. But when I try to launch oculus medium, I see a window for a fraction of second then it disappear. Then when I try to launch one more time it gives me the error "failed to launch..." it is the same for oculus quill event though they are in the list of supported application and that I downloaded them form the oculus home. 
I'd be greatfull if someone could help me on this one! 
Many thanks!

**Comment by Armada651** [comment]
Can you post your logs from `%APPDATA%\Revive`? Just enter that into the explorer address bar, rename them to .txt files and drag them in the comment box below.

**Comment by jmbihorel** [comment]
Here is the Revive injector log : 

Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" /library "Software\oculus-oculus-medium-retail\bin\OculusMedium.exe"
Creating process: C:\Program Files\Oculus\Software\Software\oculus-oculus-medium-retail\bin\OculusMedium.exe 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x9585f610
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x9585f610
Injected dlls successfully



And here is the reviveOverlay : 

libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: C:\Program Files\Oculus\Software\
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-medium-retail.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-oculus-medium-retail_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-quill.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-quill_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/sanzaru-games-inc-recoil_assets.json
Found application oculus-oculus-medium-retail
Found assets bundle oculus-oculus-medium-retail_assets
Found application oculus-quill
Found assets bundle oculus-quill_assets
Found application playful-luckys-tale
Found assets bundle playful-luckys-tale_assets
Found assets bundle sanzaru-games-inc-recoil_assets

**Comment by Armada651** [comment]
Have you restarted the Oculus software and SteamVR? Try restarting your PC just to be sure.

**Comment by jmbihorel** [comment]
I've done it a few time. Let me do it once more.

**Comment by jmbihorel** [comment]
Well it is still not working. Even though I can see all the apps in the steam library, the revive panel is empty...

**Comment by Armada651** [comment]
I still don't understand why the dashboard panel would be empty, can you make a screenshot using the SteamVR Display Mirror?

**Comment by jmbihorel** [comment]
Sorry I crashed all my display trying to install an update on my graphic card. I'm trying to fix it and I'll post a snapshot. But basically it is emptu, I just have the bg environment showing up.

**Comment by jmbihorel** [comment]
Here is a screenshot of the empty revive menu. And a one of the error I get when I try to launch it from the steam panel. 

![vive](https://cloud.githubusercontent.com/assets/25881937/23104163/d24968ec-f6c8-11e6-8072-a3f9c5ad197e.jpg)
![revive](https://cloud.githubusercontent.com/assets/25881937/23104164/d24e006e-f6c8-11e6-800e-924bcd60b77e.jpg)

**Comment by jmbihorel** [comment]
The advanced setting tab is empty as well if it can give you an hint...

**Comment by Armada651** [comment]
Yeah it seems it failed to initialize, but there's nothing in the log indicating anything went wrong. Maybe there's something wrong with your installation of SteamVR?

**Comment by jmbihorel** [comment]
I tried to uninstall it but it always seems to be there. It never really uninstall it when I try...

**Comment by jmbihorel** [comment]
Ok, so I managed to re-install steamVR but there is still no changes...
Is it possible that the oculus home have been wrongly set up? I always get notification that the headset is not found when I hopen oculus home?

**Comment by jmbihorel** [comment]
I de-activated my second graphic card, and now it works perfectly! 
Thanks for your support!
