### ISSUE TITLE
Assetto Corsa still working?

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#506]
What's the right way to start this in VR?  I tried several things but can't get it to run in VR anymore...

**Comment by Armada651** [comment]
Did you patch the 64-bit executable?

**Comment by kvdv99** [comment]
Yes, I did

**Comment by Armada651** [comment]
Then you may want to try enabling Force 32-bit mode in the options.

**Comment by kvdv99** [comment]
"Force 32-bit mode in the options" -> that's somewhere n the game options?

**Comment by Armada651** [comment]
Assetto Corsa now has native Vive support.
