### ISSUE TITLE
Is it possible to run Robinson: The Journey using VRidge/RiftCat via Revive?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [LibreVR/Revive#507]
Just bought Robinson: The Journey on Steam and tried to run it using VRidge/RiftCat via Revive, because I have no Oculus Rift or HTC Vive, but no luck.

Can anyone confirm that it's possible?

Has Steam version of Robinson: The Journey game any DRM that prevents use of Revive or VRidge/RiftCat?

**Comment by Armada651** [comment]
Have you followed the instructions for Steam games on the wiki?

**Comment by FluorescentHallucinogen** [comment]
Yes, I've pathed the folder with the executable and rename `xinput1_3.dll` to `xinput9_1_0.dll`.

**Comment by FluorescentHallucinogen** [comment]
How should I run the game after patching?

**Comment by FluorescentHallucinogen** [comment]
Is it possible to run the game without Xbox controller? Can I use another gamepad, e.g. Defender Game Racer Turbo GT?

**Comment by Armada651** [comment]
You should run it through Steam. Only XInput controllers will work.

**Comment by FluorescentHallucinogen** [comment]
Must XInput controller be connected to run the game? I'll try to test XInput emulator.

**Comment by FluorescentHallucinogen** [comment]
I've tried https://github.com/x360ce/x360ce emulator, but still no luck.

Immediately after patching the folder with the executable and renaming `xinput1_3.dll` to `xinput9_1_0.dll`, I get the following error message window `You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected.` with `Hardware Issue: Flags:30c3-Hmd(ON) Trackers(0)` title during game start.

What is a sensor? Gamepad?

If I copy x360ce emulator to the folder with the executable and run it, it tries to update `xinput9_1_0.dll` file to emulator works. After that the title of error message window changes from `Hardware Issue: Flags:30c3-Hmd(ON) Trackers(0)` to `Hardware Issue: No VR Device available`.

Is it possible to use somehow both Revive XInput patch and x360ce emulator XInput patch simultaneously?

I know that VRidge/RiftCat is not officially supported by Revive, but, @Armada651, could you please try to run Robinson: The Journey using VRidge/RiftCat instead of real Oculus Rift or HTC Vive yourself and confirm that it works or not?

**Comment by FluorescentHallucinogen** [comment]
Actually I get 2 errors during the start of the game from Steam: one from Steam — `Robinson: The Journey does not support your currently active headset.` and the second from the game — `You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected.`

**Comment by Armada651** [comment]
> Hardware Issue: Flags:30c3-Hmd(ON) Trackers(0)

A sensor is a positional tracking camera. VRidge has no support for positional tracking and Robinson won't launch without positional tracking.

**Comment by FluorescentHallucinogen** [comment]
Is it possible to emulate the sensor somehow?

**Comment by Armada651** [comment]
It's possible, but that's not my responsibility. Revive is a compatibility layer, not an emulation layer.

If the people using VRidge want to act as if their headset has positional tracking then that should be implemented in the VRidge driver.

**Comment by FluorescentHallucinogen** [comment]
> It's possible, but that's not my responsibility.

I understand it. Do you know any sensor emulators?

**Comment by Armada651** [comment]
You should contact the VRidge team to implement that feature.

**Comment by FluorescentHallucinogen** [comment]
I've installed RiftCat Beta (1.2.0) and found "SteamVR Fake Sensor" option (checkbox), checked it and tried to run the game. All is ok, except VR Service crashs.

**Comment by Armada651** [comment]
What do you mean VR service crashes? Sounds like a problem with VRidge, not Revive.
