### ISSUE TITLE
The climb, still can't change graphics setting

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#509]
You closed the issue I had before, but I think you were frustrated with the climb or something. If you remember when I mention that haptics were not working in the oculus touch demo "first contact" well this must be a hard to too issue like that one because The games definitely not working and there graphics options have dissapeared there arrows to change them are there but the actual things to select with the arrows are not... graphics are stuck and I can't put the like I used to have them. I reinstalled the game since I had it originally working great a few months ago... please help as this games great but I can't play it when I can't adjust the settings what so ever.. thanks so much man

**Comment by Armada651** [comment]
Why didn't you just comment in the closed issue like I said? Even if it is closed you can still comment, I've reopened it now.
