### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [LibreVR/Revive#51]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in [the function "ovr_Shutdown"](https://github.com/LibreVR/Revive/blob/3015d7005a6e810d4ccf97f02559e577518c3041/REV_CAPI.cpp#L57 "Update candidate: ovr_Shutdown()").

**Comment by LibreVR** [comment]
I agree, but this library actually needs more null pointer checks atm.

If it bothers you, submit a Pull Request and I'll merge it.
