### ISSUE TITLE
AaaaaAAaaaAAAaaAAAAaAAAAA!!! for the Awesome

### ISSUE THREAD

**Issue by randybaton** [LibreVR/Revive#513]
Has anyone go this to work? I brought int on Steam not realizing it was Rift only.

If i open it within Steam using th theatre the game itself is shown on a screen in front of me as if its in an extended desktop display. 2images ona screen.

If I try to inject the exe directly via revive I only see the non VR version on my desktop, nothing in the headset.

**Comment by Armada651** [comment]
This is a DK2 game, only CV1 games are supported.
