### ISSUE TITLE
Oculus Dreamdeck Closes When Scene Selected 1.0.5.1

### ISSUE THREAD

**Issue by mapotter99** [LibreVR/Revive#514]
After installing Revive 1.0.5.1, I am not able to select a scene in Oculus Dreamdeck without the application closing out to the Vive home screen. The Dreamdeck program completely shuts down. 

I resinstalled 1.0.4, and Dreamdeck worked correctly, so it must be coming from something in 1.0.5.1.

**Comment by Armada651** [comment]
Is this about the version of Dreamdeck shipped with the Oculus Store or are you talking about the version downloaded separately?

I assume the latter version, as that is the only one with a scene select menu as far as I know.

**Comment by mapotter99** [comment]
Primarily the version downloaded separately.

I tried the other version as well, and it exhibited the same problem when going using the controller to skip to the next scene. 

This problem occurs with both the beta and release version of SteamVR.

**Comment by Armada651** [comment]
I would assume commit 1d849d27ad7306449b9bda835795c2e290659c85 would cause this behavior, but that was included in 1.0.4.

Are you completely sure 1.0.4 does work?

**Comment by mapotter99** [comment]
Yes. I specifically tried uninstalling Revive and installing 1.0.4 before posting.  That resolved the problem. 

The problem returned when I updated back to 1.0.5.1.

**Comment by mapotter99** [comment]
I just ran Dreamdeck again for the first time in a couple days with 1.0.5.1. Today it worked fine. No clue why it is working fine now when nothing has changed.  Hopefully it stays this way!

I'll close the thread.
