### ISSUE TITLE
Does Revive automatically update to latest version?

### ISSUE THREAD

**Issue by SandmaN666** [LibreVR/Revive#516]
...or do I need to manually install the new version every time?  Inquiring minds want to know!

**Comment by Armada651** [comment]
The second time you start up SteamVR, Revive will ask whether you want to check for update automatically.

**Comment by SandmaN666** [comment]
Is there a version number somewhere that I can check to make sure I'm running the latest?  I don't recall seeing a notice saying 'do you want to update automatically?'.

**Comment by Armada651** [comment]
There's a white triangle tray icon in your system tray, right-click it and select "check for updates".

**Comment by SandmaN666** [comment]
Roger that, thanks!
