### ISSUE TITLE
Edge of Nowhere atrocious resolution

### ISSUE THREAD

**Issue by Usurper1** [LibreVR/Revive#517]
Hey. Im revisiting Edge of Nowhere now that I have a serious beefy computer and have since downloaded and installed the Advanced Settings tab...

I have the resolution super sampled a bit (both for apps and the compositor)...but it doesnt seem to have an effect on Edge of Nowhere, and there also doesnt seem to be an internal graphical setting within the game. The resolution is really, really terrible. I can hardly make anything out at the title screen.

Thank you for everything...between playing oculus game on the vive, and super sampling without needing to alter text config files, my VR experience has fucking transformed amazingly. Thank you.

**Comment by Armada651** [comment]
Make sure you're not on the SteamVR beta, if you're not on the beta, then try enabling the "Render Target Override".

**Comment by Usurper1** [comment]
How do I know of I'm in the beta...?

And can you explain to me the target override? I saw it but wasn't sure what it was for...

**Comment by Armada651** [comment]
Check the Library > Tools window.

The target override is a bad name for it. It just means that Revive will ignore the resolution scale multiplier that the game indicates.

**Comment by Usurper1** [comment]
Thanks! It did work, but performance/framerate then became terrible. I scaled it down a little...didnt add too much. Anyway...it seems that Robinson: The Journey doesnt respond to either the regular Application supersampler...or the Revive target override...? The game has a resolution scale setting, but Id like to try and push for a little more. Thoughts...?

**Comment by Armada651** [comment]
You're on your own for that, it's difficult enough to get Oculus games running on OpenVR without supersampling.
