### ISSUE TITLE
Landfall

### ISSUE THREAD

**Issue by bigtroy1114** [LibreVR/Revive#518]
Bad frame rate drops

**Comment by Armada651** [comment]
Going to need some more information than that.

**Comment by bigtroy1114** [comment]
I have a 970 and it runs poorly, what info do you need?

**Comment by Armada651** [comment]
At least full specs including CPU and OS + a screenshot of your SteamVR Frame Timings window during the frame rate drops. (Go to Settings > Performance > Display Frame Timing)

**Comment by Chupacabra1989** [comment]
@bigtroy1114 wow dude u know that this guys here do that for free for everyone. the only poorly thing is your thread here without any information for the developers .

**Comment by Armada651** [comment]
@Chupacabra1989 I think "What info do you need?" was more of an honest question, I don't think he meant to say anything bad with it.

**Comment by bigtroy1114** [comment]
It was just a question.Haven't had time to send information yet because I'm
working.
