### ISSUE TITLE
Assetto Corsa + 1.0.5.1

### ISSUE THREAD

**Issue by octo1234** [LibreVR/Revive#519]
First off thank you so much for Revive.

Assetto Corsa has been developed to maximise CPU usage for physics and will use more CPU as long as the GPU keeps up.
Revive 1.0.4 made a big leap in releasing the cpu the game would run with 90 PC usage and the GPU could run flat out. This would give me solid 90 FPS with x2 super sampling.

With the latest revive 1.0.5.1 the CPU runs much lower and see lots of lag in VR dropped frames etc. I have switched back to 1.0.4 for now.

The Devs have just started coding for native Vive support and will probably have it ready for the next major release.?!

Probably not worth fixing but thought I would share.

**Comment by Armada651** [comment]
Interesting, it looks like Assetto Corsa benefited from the same hack as Dirt Rally: https://github.com/LibreVR/Revive/blob/master/Revive/SessionDetails.cpp#L7

I made this hack specific to Dirt Rally to prevent possible issues in other games. If Assetto Corsa acts the same way as Dirt Rally then I can just add Assetto Corsa to that list.

**Comment by octo1234** [comment]
Happy to test it

**Comment by octo1234** [comment]
Oops wrong button

**Comment by octo1234** [comment]
Hi did this make it into the new 1.0.6?

**Comment by Armada651** [comment]
No, my advice right now is to install Revive 1.0.4 and then patch Assetto Corsa. After that you can safely upgrade Revive and Assetto Corsa will still use the old version.

**Comment by Armada651** [comment]
Any reason why you closed the issue?

**Comment by octo1234** [comment]
I can't work out of it is a revive issue a game patch issue or a steamvr beta issue.
1.0.4 worked the graphics thread harder but I'm now not sure that was a good thing. I'll do some more testing.
