### ISSUE TITLE
Create fake Root CA and sign your DLLs

### ISSUE THREAD

**Issue by poma** [LibreVR/Revive#52]
> Unfortunately Oculus has implemented a Code Signing check on the Runtime DLLs, therefore the Revive DLLs cannot be used unless the application is patched.

To avoid patching you could generate a Root CA certificate and sign your DLLs. Fake root CA should be always randomly generated on client machine to avoid major security breach (it is still insecure but on relatively tolerable level).

**Comment by LibreVR** [comment]
It's an interesting idea and I have thought about it, but the Oculus Runtime checks the certificate against a known certificate chain.

I would have to add a fake private key to an existing CA, does that seem a good idea to you?

**Comment by poma** [comment]
Well this is a bit unexpected. Are you sure Oculus checks the whole chain?

Modifying existing CA sounds like a bad idea and also will probably trigger antivirus/protection software

**Comment by LibreVR** [comment]
Yes, all the way to the root CA. It makes sense, because if you didn't do that anyone could get a code signing certificate from a random CA and fool the Oculus Runtime.
