### ISSUE TITLE
Robo Recall

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#520]
??

**Comment by thechosencarrot** [comment]
I literally have the same question

**Comment by TomMann** [comment]
no, just tested it doesnt. headset error

**Comment by jaorg1234** [comment]
It works. You have to manually inject the Robo Recall exe, then it starts up as usual.

Right click on the Revive tray icon after having started SteamVR, then choose the Robo Recall .exe in the Oculus folder.

**Comment by Armada651** [comment]
Can you tell me what the correct path is to the executable? Then I can update the heuristics.

**Comment by thechosencarrot** [comment]
So jaorg1234, did you actually buy Robo Recall and play in successfully?  I really want to buy it asap (if it works) . thanks

**Comment by CarrotSurvivor** [comment]
just bought the game, installing now... Armanda ill give you .exe path... assuming that means the folder it is in? without the patch, revive was lauching the game via the modbranch.exe or something.... the devs have released all the files of this game for mods.... could help alot with making it work flawlessly in revive im assuming

**Comment by TomMann** [comment]
Can confirm with jaorg1234 steps it works fine, but the normal way as I mention doesn't work.

**Comment by TomMann** [comment]
E:\Rift\Software\epic-games-odin\RoboRecall\Binaries\Win64\RoboRecall-Win64-Shipping.exe

**Comment by Armada651** [comment]
Ok, the problem is currently Revive assumes there will only be one executable in `Binaries\Win64` which is incorrect. I could also check if it ends with `-Shipping.exe` but then there are games that don't have that either.

So the way to fix this is by prioritizing executables that end with `-Shipping.exe`

**Comment by TomMann** [comment]
not sure that is correct, I renamed the other exe to .txt and it still didnt work.

**Comment by Armada651** [comment]
@TomMann That's because Revive doesn't use the filesystem to detect it. Revive tries to find the main executable based on a manifest provided by the Oculus client.

**Comment by louvatb** [comment]
It works on my side. As @jaorg1234 said, you have to inject the "RoboRecall-Win64-Shipping.exe" manually via your desktop Revive icon!

**Comment by Chupacabra1989** [comment]
awesome the same FUCKING issue like in the climb and unspoken cant believe that. such a laggery shit -.-

**Comment by TomMann** [comment]
Chupacabra1989 feel free to learn to code and provide a fix, although it sounds more like an issue with your rig not coping than this project.

**Comment by Chupacabra1989** [comment]
this is not the fault from revive i said this before in another post. and no its not a problem with my rig got a i7 6700k and a gtx 1080. its not a revive problem its a open vr problem from valve software

**Comment by Armada651** [comment]
Can you guys test this version: https://github.com/LibreVR/Revive/releases/tag/1.0.6

It should fix the issue, but you may need to restart SteamVR after installing the update. (or just don't have SteamVR running during the update)

**Comment by jaorg1234** [comment]
@Chupacabra1989 for me it runs very fluidly and I only have a i5 4590 + R390.

@Armada651 launches fine now with the fix, thanks for the quick update!

**Comment by louvatb** [comment]
It works fine on my side @Armada651 !! Thanks for the update.

**Comment by Armada651** [comment]
Thanks for the feedback, I will push the fix to the update checker then.

**Comment by Baestinebun** [comment]
Thanks for all info I will try it when I get home in few hours

**Comment by louvatb** [comment]
Note that Robo Recall has been clearly developped for Oculus Touch and you will feel it. I think it's more difficult to play the game with our HTC controllers!

**Comment by Baestinebun** [comment]
I guess I have to wait then and see...

**Comment by lghtanddrk** [comment]
I'm hearing that it prompts you to turn around and face the sensors when you turn around because it is looking for a 3rd sensor.  And, if the game is like it's predecessor it will be slightly awkward to use Vive controls.

**Comment by Armada651** [comment]
As always, that means we just need to work on making it better.

**Comment by kvdv99** [comment]
I'm glad that Revive makes it possible to allow me to play Robo Recall!   Just hope there's some workaround for the awkward controls we now have to deal with.  I hope not all future Touch titles will use a control scheme like this, it's really annoying.  Thanks in advance for all your work on Revive!

**Comment by avancleef** [comment]
I cannot start the game, when I drag the "RoboRecall-Win64-Shipping.exe" file on to "ReviveInjector_x64.exe" I get an error message saying "Checking your privilege... entitlement not found!"

Does anyone know how to fix this?

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/wiki/Troubleshooting#im-getting-an-entitlement-error-or-oculus-rift-not-found

**Comment by avancleef** [comment]
tried all that of course, nothing worked :)

**Comment by Armada651** [comment]
Also tried restarting your PC?

**Comment by avancleef** [comment]
yeah did that as well :) im using latest revive version. I have to say, I downloaded the game from a skidrow website. so im not starting it from my "revive" dashboard. wanted to try the game before I buy it :)

**Comment by Armada651** [comment]
Then the game is functioning perfectly by denying to launch for you. Have a nice day.

**Comment by avancleef** [comment]
and since when does it matter if I want to try something before buying since they dont give out demo's? bet 90 of the people using revive do that so yeah... have a nice day as well sucker :)
