### ISSUE TITLE
Make robo recall think I have 3 rift sensors 

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#521]
The game has a built in functionality that tells the game you have 3-4 rift sensors, this disables the "please turn around to face sensors" UI that pops up when you turn around ... obviously with vive, we have 360 by defualt... any way to trick the game to think I have 3 sensors so this stops  popping up? It's quite annoying

**Comment by KenshiHH** [comment]
oh yeah please, its really annoying

**Comment by Armada651** [comment]
It might be possible, but I'd *really* rather not do that. I'll look into it when I have time.

**Comment by whit0r** [comment]
That would be great if you could turn it off in some way, as its really annoying and spoiling a lot of immersion...

**Comment by TheLANFan** [comment]
Please do if you can, it really is immersion breaking and annoying, as the tracking is perfect but the game still thinks I'm short a sensor and tries to have me face one direction. Not a deal breaker, but true 360 play is one of the advantages of Vive

**Comment by PJkeeh** [comment]
What would be the dissadvantage of doing this?

**Comment by Armada651** [comment]
@PJkeeh Because you'd have to fake information about a sensor that's not really there. That's a bit of a can of worms for a compatibility layer.

**Comment by PJkeeh** [comment]
Agreed. Only in this case, there is no such information sadly.

**Comment by Armada651** [comment]
Yeah, so I'll look into adding a game-specific hack when I have time.

**Comment by calibban** [comment]
there is a mod, i haven't try it.
https://forums.unrealengine.com/showthread.php?138390-Project-Turn-off-Turn-Around-Warning

**Comment by whit0r** [comment]
it does not work for me, it shows up in the mod list and you can activate it but the message still shows up...at least for me

**Comment by 04nd01** [comment]
Yes, there is a mod but that's no real solution since you won't get into the highscores and I think you can't play through the story.

Epic already announced an official update to take care of 360 setups within the month. So this might not be an issue for much longer.

**Comment by KenshiHH** [comment]
AFAIK it will only address the Rotation after a Teleportation with a 360 Setup, 360° Rift Owners don't have the turn to the sensor message in the first place

**Comment by 04nd01** [comment]
They mentioned only the teleportation but there are Oculus users who play 360° with two cameras so meybe they'll change that too.

**Comment by gormanj** [comment]
BTW, does anyone know if you can connect a third base station and will it fix the 3 sensor issue?

**Comment by KenshiHH** [comment]
no, as of right now steamvr only supports 2 lighthouse base stations

**Comment by Balderick** [comment]
That statement is simply not true.   Valve have been shipping steamvr tracking hdks for over one year now.   This means steamvr definitely supports extra base stations and has done for over twelve months.

Valve devs describe steamvr tracking as being limitlessly upscalable meaning that simply adding more vase stations adds "playroom" size.   Valve devs even suggested how much this rocks for mobile vr applications for vr/ar/mr user case scenarios at dev days 2016 steamvr hardware talk.

**Comment by ffrgtm** [comment]
In response to Balderick:

It is only possible to have 2 lighthouses working at once. Lighthouse A sweeps the x-axis laser and gives a position update, then Lighthouse B sweeps the y-axis laser and gives a position update, then Lighthouse A sweeps the y-axis laser... I think you probably see the pattern forming.

This is combined with the forward integration of the IMU's using a Kalman Filter to give pose information.

When valve talks about having tracking in multiple rooms, they are describing a scenario where there are two lighthouses in _each_ room. In fact I believe even in steamvr's current state you can set up 2 base stations in two separate rooms and walk between the rooms without having more than a moderate hiccup in tracking.

**Comment by Armada651** [comment]
Closing as it has been fixed by Epic, simply go to the settings to enable 360 tracking.
