### ISSUE TITLE
tracking issue with unspoken come back

### ISSUE THREAD

**Issue by calibban** [LibreVR/Revive#522]
hello,
unspoken have again the tracking issue, since the last update.
last week that was not perfect but i can handle it, now the game is not playable anymore.
thank you for your work.

**Comment by Chupacabra1989** [comment]
i know you are sad about that im really sad too. but its not a problem from revive its an open vr problem. i also wrote this problem to steam support maybe they take a look on it.

**Comment by Armada651** [comment]
@Chupacabra1989 Don't bother Steam Support with it, there's nothing they can do about it. Leave this problem to me please.

**Comment by Chupacabra1989** [comment]
still a chance to get this game running smooth :( ? hope u can fix this in future. thank u a lot.

**Comment by Armada651** [comment]
Closing as duplicate of issue #512.
