### ISSUE TITLE
why is it that revive games only perform well when i do this

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#526]
games run terrible when async or interleaved reprojection is turned on. turn Every one of those options off and game performs better yet not perfect.. but while the game is running, if i then tick off "always on reprojection" steam vr requires a restart for this to actually turn on ..... yet the performance jumps dramatically when its checked off without restarting anything... its so strange.  robo recall for example runs much better when i do this. So to clarfify, lauch game with no async, always on, nor interleaved reprojection... then, once game launches, without restarting steam VR, check off always on reprojection in advanced settings and then bam... games runs smooth ...... i guess the real question is why is it that reprojectiion does not work and causes frame drops in revive games .... because it absolutely does, its almost like revive doesnt allow reprojection to work properly, the game is stuck at 89 FPS or something... especially with async, if its on... it keep reprojecting frames... in steam vr games... it only reprojects frames when the games are actually not hitting 90

**Comment by Armada651** [comment]
This is a complicated issue that I've already explained in a lot of other threads. I will probably write up a complete section on how reprojection affects Revive after the next release.
