### ISSUE TITLE
Robo Recall - No vibration

### ISSUE THREAD

**Issue by MetalHut** [LibreVR/Revive#527]
I'm using the latest version of ReVive (1.0.6). Robo Recall is running fine but I don't have any vibration. I have check the in-game setting if I had enable controller vibration and I don't have any.

I tried to launch the game with Steam VR Beta and with no success. Did I miss something ?
When I launch Bullet Train, I got vibration.

**Comment by Armada651** [comment]
Can you try out [RoboRevive](https://github.com/LibreVR/RoboRevive)? Let me know if you get vibration using that mod.

Also please do not use the SteamVR Beta with Revive, that's just asking for trouble.

**Comment by MetalHut** [comment]
Well I got a friend who have also an HTC Vive and Robo Recall and he has vibration with Steam VR Beta. So I tried it.
I install RoboRevive but how does it work ? Does it work in the main campaign ?

**Comment by Armada651** [comment]
> I install RoboRevive but how does it work ?

That page explains both how to use it and what it does. So what exactly is your question?

**Comment by maestro72x** [comment]
Goto the settings and turn on Vibration in the game...

**Comment by Dragoboss** [comment]
Year old issue, original poster never returned further explaining their issues. Closing.
