### ISSUE TITLE
Affected Support?

### ISSUE THREAD

**Issue by JastermereelX** [LibreVR/Revive#53]
Will there be any support to run Affected?  I really want to play this with my Vive.  I love the work you have done, I hate the fact that Oculus has turned the PC into a console by making exclusives.  Thanks for your great work.

**Comment by LibreVR** [comment]
The ReviveInjector can patch any game for Vive support, so you should try it out yourself.

You can report your results [on the wiki](https://github.com/LibreVR/Revive/wiki/Compatibility-list).
