### ISSUE TITLE
robo recall not working

### ISSUE THREAD

**Issue by Antornth** [LibreVR/Revive#530]
i was reinstalling revive for the new superhot update and then decided to play some robo recall and when i opened it in the revive tab it put the file explorer and in the bottom right it said "robo recall mods (*.robo). and i have tried to reinstall revive and oculus and robo recall but nothing worked.

**Comment by Armada651** [comment]
Sounds like you might've installed an older version, try installing the latest one: https://github.com/LibreVR/Revive/releases/tag/1.0.6

**Comment by Antornth** [comment]
will just updating it work?

**Comment by Armada651** [comment]
Yes

**Comment by Antornth** [comment]
it worked thanks :)
