### ISSUE TITLE
Games not being displayed in vr

### ISSUE THREAD

**Issue by fredinator** [LibreVR/Revive#532]
I installed revive and button and games are showing up but when I start anything it just gets displayed on my monitor and nothing happens in vive

**Comment by Armada651** [comment]
Post your logs from `%APPDATA%\Revive`.

**Comment by fredinator** [comment]
From ReviveInjector.txt
Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe"  /base "Support/oculus-dreamdeck-nux/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe" -vr -dreamdeck=NUX
Creating process: C:\Program Files\Oculus\\Support/oculus-dreamdeck-nux/Dreamdeck/Binaries/Win64/Dreamdeck-Win64-Shipping.exe -vr -dreamdeck=NUX 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xa2cff610
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xa2cff610
Injected dlls successfully

From ReviveOverlay.txt:
libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: C:\Program Files\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: D:\Oculus\
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///d:/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle playful-luckys-tale_assets
Launching application: oculus-avatar-editor
Launching application: oculus-dreamdeck-nux

**Comment by Armada651** [comment]
You're not on the SteamVR Beta right?

**Comment by fredinator** [comment]
I guess not ... Got my vive yesterday and installed everything then

**Comment by Armada651** [comment]
Ok good, have you tried restarting your PC?

**Comment by fredinator** [comment]
No. Only restarted steam vr and stuff. I'll try that

**Comment by fredinator** [comment]
Lol I feel stupid ... restating worked. There was no mentioning anywhere I should do that though
Thanks

**Comment by Armada651** [comment]
Actually I think you skipped step 6 of the ReadMe, restarting your PC is just a sure-fire way to do it.

**Comment by fredinator** [comment]
Yeah I did not follow the link in step 6 to the error handling from the installation instruction because I got no error

**Comment by Armada651** [comment]
Yeah the two games you started don't seem to throw an error, but that is still probably the reason why they failed.

**Comment by fredinator** [comment]
Alright. Thank you
