### ISSUE TITLE
superhot after update launching to black screen. 

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#534]
i reinstalled the game, revive , retarted steam  vr .. everything.. its no longer working after the forever update :( pls help

**Comment by CarrotSurvivor** [comment]
? nothing i do is fixing it somethings wrong

**Comment by Armada651** [comment]
Are you on the SteamVR beta by any chance?

**Comment by CarrotSurvivor** [comment]
Hey man! And Nope I'm
Not using steam VR beta

**Comment by Armada651** [comment]
I'll see if I can reproduce it this weekend, but it's unlikely that I'll be able to reproduce it since no one else seems to experience the problem.

**Comment by CarrotSurvivor** [comment]
Thanks so much man, would it help if I send you my revive log files?

**Comment by Armada651** [comment]
Sure.

**Comment by CarrotSurvivor** [comment]
Hey,  so I had to go to my user files, <my name> , <app data> , <local low> ,< SUPERHOT_team>, super hot _ VR , then delete the VRsuoer.hot file . This was the save file for the game and must have been corrupted. This same issue happened on the 2D version of the game. The game now works, revie still works great! Maybe post this somewhere to let people know how to fix it if it happens to them? Thanks man it works now :)
