### ISSUE TITLE
Mission:ISS Entitlement Check Failed

### ISSUE THREAD

**Issue by whit0r** [LibreVR/Revive#535]
Hi, the just for free released ISS-Exp doesnt start up, it goes only to the Failed Status...

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/wiki/Troubleshooting#im-getting-an-entitlement-error-or-oculus-rift-not-found

**Comment by whit0r** [comment]
Holy macaroni...that was quick and it worked. Thanks bro.

**Comment by Armada651** [comment]
No problem.
