### ISSUE TITLE
Dirt Rally issue?

### ISSUE THREAD

**Issue by mechaniK-nz** [LibreVR/Revive#538]
hi all, the problem im having is a touch hard to explain, i should mention for the record that with Assetto i've had zero issues

however in Dirt Rally .... it almost feels like the game is constantly searching for my play space ... i can drive just fine it isnt totally game breaking, but it destroys most of the immersion. 

 i get continuous flashes of  light blue every 4 seconds or so, and square "play area" flashes white/grey and as this happens i am seeing the location of my base-stations pop up

any suggestions??? anyone else had issues like this

**Comment by godofdeathftw** [comment]
I would go into the steamvr settings and then off the play space warning whenever you want to play the game.

**Comment by godofdeathftw** [comment]
Turn, not then
