### ISSUE TITLE
Oculus Games on SteamVR on Rift CV1 + Code Signing bypass surgery

### ISSUE THREAD

**Issue by jfenton** [LibreVR/Revive#54]
Hi guys,

I'd like to get Alien:Isolation working on the Rift, which was originally written against the Oculus 0.7 SDK (Extended Mode) and never updated.

Your project seems like a good way to shim a compatibility layer in. First step, I wanted to get Revive working with Oculus games, through SteamVR, but on the Rift CV1. I've almost got that working, but running into an issue and hoping you could assist.

With stock setup + ReviveInjector, trying to run Henry (for example) results in a OnlineSubsystemOculus Error of:
	"Unable to launch app: App running from non-trusted source (1971039)"

This is due to the Code Signing issues that you ran into. We can bypass it, though it is a tad... invasive:

1. Shutdown the Oculus service. Use a HexEditor such as HxD to make the following changes (MAKE BACKUPS!) to files in c:\Program Files (x86)\Oculus\Support\oculus-runtime:

2. OVRServer_x64.exe
Set offset ranges 0x203B2-203B7 and 0x203BD-203C2 (inclusive) to 0x0C
From offset 0x203B0, you edit:
85 C0 0F 85 5A 01 00 00 48 39 7C 24 28 0F 84 4F 01 00 00 48 8D
to become:
85 C0 0C 0C 0C 0C 0C 0C 48 39 7C 24 28 0C 0C 0C 0C 0C 0C 48 8D

3. OculusAppFramework.dll
Set offset F9F4A from 0x74 to 0xEB

4. Build a new LibOVR using VS2015 but modify OVR_CAPIShim.c to add:
	verified = 1;
as line 641.

5. Use that new LibOVR to build your Revive solution.

6. Follow normal Revive instructions from this point, copy the Revive dir and injector executables into your particular game.

7. Start OVRServer_x64.exe manually from command line to check it still works (for some reason, the above does break the service - perhaps a check I missed - but running it manually you'll find Oculus Home and Steam VR both work fine). You can then start SteamVR in the usual way.

Whilst the above does get rid of the "non-trusted source" issue on running e.g. Henry, the game/app then just spins. I'll break out the debuggerer later, but do you know of a way to get SteamVR (or any of the apps) to emit debug logs?

(Of course, this is only a small stepping stone to getting Alien : Isolation working...)

**Comment by LibreVR** [comment]
Try restarting the Oculus Runtime service, [instructions in the ReadMe](https://github.com/LibreVR/Revive#installation).

If you still get the same error you're likely using symbolic links, which the injector doesn't account for. Hence you get the "non-trusted source" error.

**Comment by LibreVR** [comment]
Also if have any questions about how to implement certain older API functions, let me know. Here's my first tip, use [this function](https://github.com/ValveSoftware/openvr/blob/a6c91ef97302ce2abd852115682fb8726471c67b/headers/openvr.h#L971) to switch the Vive to extended mode.

Also, at some point we should look into how we can get these compatibility libraries combined into one project. But for now it's best to just implement it in a fork so we can get a viable solutions working first.

**Comment by LibreVR** [comment]
Looks like I read over the second part of your post, where you're trying to patch out the runtime check in the Oculus Server. That's not necessary and will not work.

The Oculus Server is pretty much ignored by Revive, the code signing check I was referring to happens in the actual game itself. But you don't need to patch it out, the ReviveInjector bypasses it completely.

I hope you have backups of the files you patched, you're going to need to restore all of them.

**Comment by Rejaku** [comment]
For error 1971039, just toggle the Unknown Sources setting off and back on again once.

**Comment by MattFiler** [comment]
@jfenton Did you get anywhere with this? Would be great if Revive worked with Isolation.
