### ISSUE TITLE
No ReVive on Dashboard

### ISSUE THREAD

**Issue by reenuwal** [LibreVR/Revive#541]
I use Vive and Windows 10 pro.
I don't see ReVive on the dashboard, and it isn't on the desktop either.
I installed it on my D drive.
Any idea where I may have went wrong with the install.

**Comment by Armada651** [comment]
Post your logs form `%APPDATA%\Revive`.

**Comment by godofdeathftw** [comment]
Armada, pls respond to my post. Thanks.

**Comment by reenuwal** [comment]
I ran a search and have no results for %APPDATA%\Revive

**Comment by NerioLab** [comment]
You must tick revive in SteamVR on Tab Application.

**Comment by Armada651** [comment]
@reenuwal You're supposed to enter that into the address bar of explorer or just in the run prompt `Win Key + R`. That will open the folder with the logs.

**Comment by reenuwal** [comment]
ReVive is not listed in the revive in SteamVR on Tab Application

**Comment by reenuwal** [comment]
after run it says: windows cannot find WinKey

**Comment by Armada651** [comment]
@reenuwal I know this may seem like rocket science to you, but I did not want you to enter `Windows Key + R` into the run dialog.

**Comment by reenuwal** [comment]
Armada651
I'm Sorry, I didn't read the post correctly.
I did as you said and ran %APPDATA%\Revive  and got a strange response: 
Windows cannot find C:\Users\My Name
Yet of course I am listed in file explorer:  C:\Users\My Name

**Comment by Armada651** [comment]
@reenuwal In that case try: `C:\Users\My Name\AppData\Roaming\Revive`

Ofcourse your account is probably not really "My Name", so remember to replace that with your real username.

**Comment by Villaman68** [comment]
in the cortana search box type RUN. The copy paste %APPDATA%\Revive into the dialog box that appears.
That will open up explorer with the 2 .txt documents you need.
