### ISSUE TITLE
Dirt Rally - Desktop Mirror Window Looks Way Off

### ISSUE THREAD

**Issue by cazman321** [LibreVR/Revive#542]
I've seen this question asked a few times on the Steam forums with no answers. Does anyone know how to fix the Desktop/Mirror View when it's angled too high? I've tried changing aspect ratio, resolution, FOV, switching to non-windowed, and even the non-horizon view setting (a VR setting that shakes your view with the car, instead of locking the view to the horizon). I was trying to Steam broadcast and all people could see was barely the top half of the windshield and the roof.  I'm not sure if it's Revive doing this, but figured I'd see if others had the same problem and fixed it.  Thanks!  Here's an example:
Apparently while sitting still it looks barely acceptable: http://i.imgur.com/jUDittq.jpg

But when driving it looks like this: http://imgur.com/FxxvGAO.jpg

**Comment by cazman321** [comment]
Who knows if this will help but I found some viewport values from the .exe

static const float g_fViewportWidth = 1920.0f;
static const float g_fViewportHeight = 1152.0f;

void VS_RenderStereoPixelID( VS_StereoPixelIDInput I, out float4 f4Pos : SV_Position, out float4 f4Diffuse : COLOR0 ){	

f4Pos.x = ( I.f3Pos.x / ( g_fViewportWidth * 0.5f ) ) - 1.0f;	
f4Pos.y = -( I.f3Pos.y / ( g_fViewportHeight * 0.5f ) ) + 1.0f;	
f4Pos.z = I.f3Pos.z;	f4Pos.w = 1.0f;

**Comment by Armada651** [comment]
This seems to be an issue for Oculus users too, so Revive is working fine.
