### ISSUE TITLE
Cross platform game Kingspray tries to launch through Oculus and Revive even though it was purchased for Vive

### ISSUE THREAD

**Issue by thedonquixotic** [LibreVR/Revive#546]
I purchased Kingspray on Steam for Vive but it tries to launch through Revive, which causes it to act like an Oculus game which screws up the controls some what. Any idea how to get around this issue? Has this already been addressed by ReVive and I'm just missing something obvious?

**Comment by Armada651** [comment]
I very much doubt it's being launched through Revive. How could that even happen if you don't launch it through the Revive dashboard?

Or did you at any point use Revive to patch the executable?

**Comment by thedonquixotic** [comment]
I got it working. I used task manager to shutdown revive stuff. It could be something actually to do with Kingspray. I'll comment again if I have any more problems but I think it might have just been a glitch I was experiencing with the program itself.

**Comment by Armada651** [comment]
`ReviveDashboard.exe` doesn't do any Oculus emulation it only displays the dashboard, it can't even inject into other applications. I very much doubt that you need to shut it down to get Kingspray to work.

**Comment by randomuser00** [comment]
for this kind of situation i delete ovrplugin.dll from the game folder so it prevent from launching in occulus and it launch in wmr headset instead. i've done it in a couple of games.
