### ISSUE TITLE
Can't start Revive dashboard

### ISSUE THREAD

**Issue by hnkessler** [LibreVR/Revive#547]
Hello, I have everything set up after following the instructions. When I start the Vive I can see the page that says ReVive but when I click it, there is nothing that pops up. I have installed games on the Oculus home that I checked were compatible but I still don't see anything.

**Comment by Armada651** [comment]
Please post your logs from `%APPDATA%\Revive`, just enter that into the address bar of any folder and drag-and-drop the two text files into the comment box here.

**Comment by hnkessler** [comment]
libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: C:\Program Files\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: D:\
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///d:/Manifests/oculus-oculus-video.json
Loading manifest: file:///d:/Manifests/oculus-oculus-video_assets.json
Loading manifest: file:///d:/Manifests/playful-luckys-tale_assets.json
Loading manifest: file:///d:/Manifests/sanzaru-games-inc-recoil_assets.json
Loading manifest: file:///d:/Manifests/superhot-superhot.json
Loading manifest: file:///d:/Manifests/superhot-superhot_assets.json
Found application oculus-oculus-video
Generating manifest for oculus-oculus-video
Found assets bundle oculus-oculus-video_assets
Found assets bundle playful-luckys-tale_assets
Found assets bundle sanzaru-games-inc-recoil_assets
Found application superhot-superhot
Generating manifest for superhot-superhot
Found assets bundle superhot-superhot_assets
Adding manifest: superhot-superhot
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest
Adding manifest: oculus-oculus-video
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest

**Comment by Armada651** [comment]
Can you try rebooting SteamVR and posting the new log?

**Comment by hnkessler** [comment]
I apologize for the late response. It gives me this message now.

libpng warning: iCCP: known incorrect sRGB profile
Failed to create the dashboard overlay (is it already running?)

**Comment by hnkessler** [comment]
Just checking that you saw my last post

**Comment by amerrin** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/853079/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/853080/ReviveOverlay.txt)

I am having the same issue.  I recently purchased a game through Oculus that I wanted to play through Revive.  I installed Oculus + the game, then I installed Revive.  I can launch Steam VR and see a Revive tab but when I click it, I do not see anything.  Also, now my desktop does not show anything either.

**Comment by Armada651** [comment]
@amerrin That is a different issue explained here: https://github.com/LibreVR/Revive/wiki/Troubleshooting#im-getting-an-entitlement-error-or-oculus-rift-not-found

**Comment by Armada651** [comment]
@hnkessler From the log it looks like you may have two installations of Revive in different locations. Could you post the contents of the file: `C:\Program Files (x86)\Steam\config\appconfig.json`

**Comment by hnkessler** [comment]
@Armada651 I tried to uninstall and reinstall ReVive, but it looks like I failed. I don't think that is the issue because it was the same problem before when I only had one. I can post the contents of the file in about an hour.

**Comment by amerrin** [comment]
I think I am having same exact issue that  hnkessler is having.  I can inject the game from Revive right click menu and browsing to the game location.  However, when I pull up Revive tab on my Vive home, it is empty.  None of the games are showing up.  This is my appconfig.json

{
   "manifest_paths" : [
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Dashboard\\viveoverlay.vrmanifest",
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Home\\home.vrmanifest",
      "C:\\Program Files (x86)\\Steam\\config\\steamapps.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\9347a360-c6ea-4e35-aaf1-9fab4f41cb79\\1487041090\\app.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\2518cf75-3ee1-442a-b863-2235e8f3b303\\1487771843\\app.vrmanifest",
      "C:\\Program Files\\Revive\\app.vrmanifest",
      "C:\\Program Files\\Revive\\support.vrmanifest",
      "C:\\Program Files\\Revive\\revive.vrmanifest"
   ]
}

**Comment by hnkessler** [comment]
Here is my config file.

{
   "manifest_paths" : [
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Dashboard\\viveoverlay.vrmanifest",
      "C:\\Program Files (x86)\\ViveSetup\\Updater\\App\\Home\\home.vrmanifest",
      "C:\\Program Files (x86)\\Steam\\config\\steamapps.vrmanifest",
      "C:\\ProgramData\\HTC\\Vive\\ViveApps\\5808cb6d-cbb8-49d5-821b-4295a2634697\\1482441097\\app.vrmanifest",
      "C:\\Program Files\\Revive\\app.vrmanifest",
      "C:\\Program Files\\Revive\\support.vrmanifest",
      "C:\\Program Files\\OpenVR-AdvancedSettings\\manifest.vrmanifest",
      "C:\\Program Files\\Revive\\revive.vrmanifest"
   ]
}

**Comment by amerrin** [comment]
@hnkessler do you have Vive desktop app running? I think that might have been my issue...Give it a shot

**Comment by hnkessler** [comment]
That wasn't the issue but I figured it out! thanks for all of the help, guys.

**Comment by Armada651** [comment]
Explain how you solved it so other people don't run into the same issue and have to figure out what you did.

**Comment by RFrags** [comment]
@hnkessler yes, please explain as I am having the same issue.

**Comment by amerrin** [comment]
@RFrags Make sure if you have dual-GPU that these programs are being output to dedicated GPU and not integrated GPU

**Comment by B0DZI0** [comment]
> 
> 
> That wasn't the issue but I figured it out! thanks for all of the help, guys.

I literally got this issue right now and I cannot solve it...
