### ISSUE TITLE
Edge of Nowhere ghosting/stutter when rotating the HMD

### ISSUE THREAD

**Issue by SimplexPL** [LibreVR/Revive#548]
This is my first issue report, so let me know if more info is needed.

I am playing Edge of Nowhere using Revive 1.0.6 and stable SteamVR (non beta) and when I look around (rotate) then I can see a weird artifact, sort of ghosting/trails of the previous frame, which is very distracting. If I do not move my head and just walk forward in game then the movement is fluid, but it comes back when I move the head. It can also be seen on the image displayed on the monitor but it is much less visible on a monitor.

It is especially visible when there is a dark and light object next to each other, like on this screenshot:
![edgeofnowhere_2017_03_19_17_23_10_915](https://cloud.githubusercontent.com/assets/25101733/24082618/f878dcd0-0cc8-11e7-89de-ddb9f18e17ec.png)

I checked framerate and gpu usage - frame counter reports 89.5 frames and gpu usage is below 50% (I have 1080 and 7700K), so it's not the problem of dropping frames (frame timing graph is not reporting missed frames). I also tried enabling and disabling Asynchronous reprojection but it not not change anything. If you need any more info let me know and I will try to provide it.

I tested Lucky's Tale and this problem does not occur.

[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/853349/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/853348/ReviveOverlay.txt)

**Comment by Armada651** [comment]
Probably related to issue #182.

**Comment by SimplexPL** [comment]
Maybe it is, I do not know how to confirm or debunk it. But it happens all the time, including the starting screen with logos, and also inside the caves where there is no flickering at all - but the ghosting is still on the same level. Also, someone in that thread wrote "Its very playable as it is, but will be nice when it is fixed." - I can assure you it is not "very playable" for me in its current state, quite the opposite. I tried playing but the ghosting is really distracting. Perhaps some bug was introduced in one of the versions of Revive and no one tested on Edge of Nowhere? Or something changed on Oculus/game side and that broke compatibility?

**Comment by Armada651** [comment]
My comment was simply a note to myself.

**Comment by SimplexPL** [comment]
Was anyone else able to reproduce the issue?

**Comment by LorkHang** [comment]
yes, it runs like it has serious frame drops but it is not (no missing frames at all), it happens whenever I rotate the HMD. Things is it runs fine couple months ago, not sure what breaks it.

**Comment by SimplexPL** [comment]
Thanks for quick confirmation. This is exactly what happens for me: there are no missing frames, but game is jerky when rotating HMD. I wish I played it when it was working instead of hoping that a flickering fix will come soon ( https://github.com/LibreVR/Revive/issues/138#issuecomment-230230260 ).

**Comment by Armada651** [comment]
@SimplexPL When I made that comment I wasn't aware that Edge of Nowhere would crash with nearly every graphics debugger that I have. Making something that should be relatively simple to debug nearly impossible. I can't even begin to fix the problem until I find a way to use graphics debuggers on Edge of Nowhere.

Anyway, the new release should at least solve a bit of the stuttering introduced in Revive 1.0.6.

**Comment by SimplexPL** [comment]
Thanks for all your efforts, they are appreciated! 
Sucks about the debugger crash, maybe the dev (Insomniac) would be willing to help you?

**Comment by SimplexPL** [comment]
> Anyway, the new release should at least solve a bit of the stuttering introduced in Revive 1.0.6.

The game works well now but supersampling can crush performance even on 1080Ti.
