### ISSUE TITLE
The Climb doesn't launch. 

### ISSUE THREAD

**Issue by axiumone** [LibreVR/Revive#55]
Currently The Climb won't launch using revive 0.4. You get an error telling you that you're not connected to the oculus store when trying to launch the game using revive.

**Comment by ChristianRosan** [comment]
I had the error as well right after installing the game. After rebooting the game runs fine! 

Performance wise I would like to see some improvements (there is some judder in complex mountain scenes).  Would be great to have forced reprojection (better to have 45fps judder free than 90fps with occasional judder).  My specs: 980ti, i7 2600k @ 4.7 GHz,  16 GB RAM

**Comment by axiumone** [comment]
Yep, worked fine after rebooting.Thanks for the tip! Closing.
