### ISSUE TITLE
Injecting shortcuts with command lines #2 (hl2vr mod with tracked controllers, native directions won't apply))

### ISSUE THREAD

**Issue by optimumbox** [LibreVR/Revive#551]
Sorry to create a new thread, but you closed my last one and I'm not sure you're understanding what I'm trying to run.

Reference thread: https://github.com/LibreVR/Revive/issues/550

I understand hl2 has native support, however "native" hl2 is not what is trying to be run here. I currently have a prototype build for the hl2vr mod. This is the mod that adds fully tracked controllers to hl2 and it is also the mod that originally was not supported on the consumer released headsets. (It's the mod that everyone is waiting to be finished right now.) Currently the build they have only works on oculus headsets, which is why I'm trying to run revive, but I'm running into a problem. Revive will not inject a shortcut properly. The shortcut is essential because it's the only way on windows to force the game to run with command lines to reference the source mod.

**Comment by Armada651** [comment]
Please don't open duplicate issues, there's nothing preventing you from commenting in a closed issue and they can be reopened if there's really a problem.
