### ISSUE TITLE
Network latency every 10 seconds with revive installed

### ISSUE THREAD

**Issue by kendoka15** [LibreVR/Revive#552]
Earlier today, every 10 seconds I would get a few second long lag spike. I confirmed this was happening only on my PC, then turned off steamvr and tried again. No lag spike. I found someone on reddit who said revive was the culprit so I uninstalled it and started steamvr, no lag spike.

**Comment by Armada651** [comment]
This is a known issue in SteamVR, it seems any VR dashboard app will cause this for some people, including Viveport

**Comment by kendoka15** [comment]
I just noticed after it happened with the advanced settings app. I hope it ends up fixed :/
