### ISSUE TITLE
Aim is off in Drop Dead

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#553]
Drop Dead looks great and plays on Revive.  Grabbing guns is a little odd for Vive though.  You point at objects in the distance and then press grip to grab them.  You use grip to grab objects from your holster too. Doesn't always work well.  Maybe because I have sticky grip on in Advanced OpenVR settings.

Aim is a little off.  It seems like it is too far down and maybe off center to the left.  Not sure if this can be addressed in Revive or only in Advanced OpenVR settings.

**Comment by Armada651** [comment]
It's hard to find an orientation that works in all games, I recommend you use OpenVR-AdvancedSettings to adjust the angles as you see fit.
