### ISSUE TITLE
Robo Recall

### ISSUE THREAD

**Issue by DowJohns** [LibreVR/Revive#555]
I recently downloaded Robo Recall and have read all of the posts concerning issues booting it up via Revive.  I have taken all steps and have succeeded in getting to the tutorial at RoboReady every time.  The problem is that the game either crashes before booting up the actual game or it crashes in the first level (as of now, I can't even get to the first level anymore).
I have used the injector and I have booted from the Revive dash.  I have erased and re-downloaded the game.  I have the latest release of Revive.  I have rebooted both SteamVR and my rig.  I boot up Oculus and restart it to clear licensing issues.  NOTHING SEEMS TO WORK.

I have a machine that can handle the game (1070 GTX, Intel I7, etc).  Any ideas?

**Comment by bernardb13** [comment]
I am gonna jump in here...I had the same problem.  I have installed RoboRevive and it plays flawlessly for me now.

**Comment by DowJohns** [comment]
@bernardb13 Where can I download RoboRevive?

**Comment by bernardb13** [comment]
Its here on this website:

https://github.com/LibreVR/RoboRevive

You have to make sure to run Robo Recall directly rather than through the Revive panel in SteamVR

**Comment by Armada651** [comment]
I'm going to focus on improving RoboRevive as it is obviously the better, more stable option as far as Robo Recall is concerned.

**Comment by DowJohns** [comment]
Thanks for the input!  I have now been playing Robo Recall and even got to the next level but now it is crashing again.  I am using the injector but it still happens.  Should I just click the exe file to launch?

**Comment by bernardb13** [comment]
I'm not the guy who created the software, he is the expert, but from my own personal experience - do not inject, start Robo Recall by directly starting the .exe file, do not run it from the Revive tab in Steam.  When inside the game go to the Mods tab and select individual missions you wish to play.  Thats what I have been doing and I have played all missions except 2 and have had no crashes.

**Comment by Armada651** [comment]
@DowJohns After installing the mod, do not launch Robo Recall through any other means than just starting the executable directly.

**Comment by DowJohns** [comment]
Thanks again @bernardb13 and @Armada651!  Working perfectly now.  Keep up the good work @Armada651!!!

**Comment by willp319** [comment]
Whenever I click Robo Recall on the revive menu I get stuck in the vive home screen and get the spinning circle o' death. Can someone help me? BTW I have gtx 1060, Intel i7-7700. Its an Ibuypower desktop.

**Comment by Armada651** [comment]
@willp319 Try this: https://github.com/LibreVR/RoboRevive
