### ISSUE TITLE
Disconnecting Revive from Ark

### ISSUE THREAD

**Issue by DuplicateData** [LibreVR/Revive#556]
Was trying to figure out how to get Ark to stop launching in Steam VR as it sucks in VR right now. I had uninstalled Revive which did not work and also have tried unplugging the Vive. With the Vive unplugged it will not boot the game up. Any help would be greatly appreciated as I just want it to go back to how it was before I installed Revive to it. Thanks

**Comment by Armada651** [comment]
You need to delete two files: `xinput1_3.dll` and `xinput9_1_0.dll`. These DLLs were copied next to the main executable when you used the `Patch...` function.

**Comment by DuplicateData** [comment]
Do you happen to know the file they were copied to?

**Comment by DuplicateData** [comment]
Found the xinput1_3.dll but not the other.

**Comment by Armada651** [comment]
That's no problem, just delete the xinput1_3.dll

**Comment by Armada651** [comment]
But only next the the game executable, don't start to delete that DLL in other locations.

**Comment by DuplicateData** [comment]
Okay I think it has worked, thank you so much. If I run into issues I will post here. It did launch the oculus store which it has never done but at least steam vr is not running.

**Comment by Armada651** [comment]
Haha, I think that's because removing Revive reactivated the Oculus support ;)
