### ISSUE TITLE
UE4 Games problem

### ISSUE THREAD

**Issue by ytdlder** [LibreVR/Revive#558]
So, I don't think there is a forum here(?), so I'll just post my problem here if that's ok...

I've tested several (free) "Experiences" from the Oculus Store and each UE4-Engine game (Dar Angelica, Farlands, Oculus Dreamdeck...) does not display anything in VR - even though they are listed in the compatibility list as working.
The game loads fine and I can see the content via Desktop mode (or when taking off the HMD^^), but I can see nothing in VR.
Except... light flashes... if that makes sense: like in Showdown at the beginning, where you hear the sirens, I can see the (colored) light flashing in VR, but not the whole content...

Am I doing something wrong? What could be the problem?

Thx in advance!

PS: I've got all software up2date (Steam, Oculus, ReVive, ...)

**Comment by Armada651** [comment]
You are using the SteamVR Beta, which currently has a known bug. Please revert back to the stable version.

**Comment by ytdlder** [comment]
Man, you are effin awesome!!

Here I was thinking VR was one of these tech you better have the very latest stuff :-)

Thanks!!
