### ISSUE TITLE
Failed entitlement check Robo Recall, some other games failing also

### ISSUE THREAD

**Issue by PixelSplitter** [LibreVR/Revive#559]
Robo Recall displays the" failed entitlement check" message, The Unspoken displays " A connection to the Oculus store could not be established" message. Pinball FX2 also fails. Dreamdeck and Superhot still function. I uninstalled/reinstalled new version of Oculus home and the latest Revive. Disabled my firewall and AV software, let Oculus Home start when Steam VR ran. Same issue.

**Comment by Armada651** [comment]
Duplicate of #557
