### ISSUE TITLE
Giant Cop Not working

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#560]
game launches on desktop, but not in headset, seems glitched out, no error messages, can hear the music. Tried patching/ injecting / maybe im doing it wrong? even from dashboard, the game just keeps doing the same thing, starts up, seems glitched, cant see in headset, -can- hear music. Anything i can do to help make it work?

**Comment by Armada651** [comment]
You are not on the SteamVR beta right?

**Comment by CarrotSurvivor** [comment]
Nope, ran steam as administrator, dragged .exe onto injector. It doesn't work, and launching the game from oculus home has the game behave in the exact same way. Revive doesn't seem to be having any effect on the game whatsoever :/

**Comment by CarrotSurvivor** [comment]
I have revive and oculus home on the c: drive .m, windows 10, all that stuff

**Comment by CarrotSurvivor** [comment]
I've been trying to get it to work for the last hour, reinstalled the game too. Anything else I could try? I'm here to do whatever I can to help you get it working for myself and  others :)

**Comment by CarrotSurvivor** [comment]
One more thing, there is no entitlement check error or anything like that, no error messages, not even when I launch the game from oculus home just to see how it would behave.

**Comment by CarrotSurvivor** [comment]
The game has a very long file name in the oculus folder / sowtware. I changed it to see what would happen and am -now- getting an entitlement error, but the game no longer emblem lauches from the dashboard. Now entitlement error occurs when I launch the game by dragging .exe onto the revive/injector file. I'm running steam as administrator.

**Comment by CarrotSurvivor** [comment]
Yea man, I've tried everything nothing is working.

**Comment by larzvegaz** [comment]
same here :-(

**Comment by CarrotSurvivor** [comment]
Should I try and launch the game and send my logs? How can I fix this, don't want my 30$ to go to waste :(

**Comment by AndreStadelmann** [comment]
Same for me, keep us updated if you find a solution.

**Comment by Armada651** [comment]
@CarrotSurvivor Sending logs won't help, you'll just need to wait until it's fixed in a future Revive release. Every game will work at some point, but if you buy something that's not on the compatibility list yet, then you run the risk of having to wait until Revive supports it.

**Comment by CarrotSurvivor** [comment]
Just wanted to be the first person to let people know if it didn't or diddnt work, now they know so I'll add to the compatibility list that it will work in a future update. Thanks man! Looking forward to a fix this game looks pretty fun

**Comment by SweViver** [comment]
Any update on this? Would be awesome if Giant Cop could get Vive support :) Thanks a lot guys!

**Comment by Armada651** [comment]
Can someone post the `output_log.txt` from their game directory? It's located in the folder that ends with `_Data`.

**Comment by AndreStadelmann** [comment]
@Armada651 I'm looking for it but can't find it. Ther is one in superhot as i should bot not in Giant Cop. Any thougts?

**Comment by Armada651** [comment]
Fixed in 94d2e6c0cdaebe7fce3db651b3b7154b7b4df284.

**Comment by AndreStadelmann** [comment]
@Armada651 Sweet, so excited! Any ETA on the new patch?
