### ISSUE TITLE
Robo Recall - crashing 

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#564]
Loved this game when it came out, but 180 tracking + the teleport system sucked.
I tried playing but couldn't get used to it.  The game worked without crashing though.

Then the update from Epic came : 360 tracking and normal teleport.
This is it I thought!   But then I had that known height problem (floating 2 metres int the air, unplayable).

People here suggested RoboRevive, so I installed this according to the procedure without any problems.
Started the game and I was in heaven : 360 + normal teleport + height issue fixed!

But then it crashed, UE crash,  just in the beginning of the first level, when I teleported around the first corner (when the two robots run at you).  So I rebooted my PC and tried again :  crash at the exact same moment.  :(

It's not meant to be I guess...?   :)

**Comment by Armada651** [comment]
I'm working on a new version of RoboRevive, hopefully the crash will be fixed in that version.

**Comment by kvdv99** [comment]
WIn10

**Comment by Armada651** [comment]
Okay, I'm not sure if the next version will fix that, but you can test it once it's out (should be out later today or this weekend). If you still have the problem with the new version, make an issue report on the RoboRevive page.

I'm going to close this issue as it's mostly about RoboRevive and the height problem already has a ticket.
