### ISSUE TITLE
super hot issue

### ISSUE THREAD

**Issue by teaguru22** [LibreVR/Revive#565]
I have used revive with super hot before but now i have a new issue.

today I can only launch through the injector, which is not ideal. When i did get it launched the height in game was way off, one time I was too short, the 2nd too tall.

Any help is appreciated. 

Thanks

**Comment by Maxoxpower** [comment]
this.. please , give us a fix this is my fav game :(

**Comment by jaorg1234** [comment]
I've just tested the game in the endless mode and the game started up as usual and there was no height issue.

Does a error message crop up when starting up the game with the SteamVR overlay? Is your game up to date?

**Comment by Maxoxpower** [comment]
me , i can start the game in steamvr.
But i got the height issue for the first time..and its the vr game i play the most.. :(
i really want to play again...its my favorite game.

**Comment by Maxoxpower** [comment]
i really want to show the game this friday but i cant now! :(

how this error can be possible? steamvr update? superhotvr? revive update?
revive did not get some update recently...

**Comment by Armada651** [comment]
You can try running the room setup again. I'll probably look at this issue tomorrow.

**Comment by Maxoxpower** [comment]
will try after work .
thanks for the fast answer

**Comment by Maxoxpower** [comment]
not working :(

**Comment by Armada651** [comment]
Please try the following workaround and let me know the results:

1. Put the headset on the ground
2. Load the game and wait for the game to finish loading
3. Put on the headset

**Comment by Maxoxpower** [comment]
nothing, same problem :(

**Comment by Armada651** [comment]
Well, I can't reproduce it on the current development build, so it's best to wait until the new release and see if you still have the issue then.

**Comment by CarrotSurvivor** [comment]
Itbs a corrupt save file guys, delete the save file and the game will work again.

**Comment by Armada651** [comment]
Please try the latest version of Revive: https://github.com/LibreVR/Revive/releases

If that doesn't work try @CarrotSurvivor's advice.
