### ISSUE TITLE
Dashboard gives system error (winsparkle.dll and openvr_api.dll) on startup

### ISSUE THREAD

**Issue by SimonPStevens** [LibreVR/Revive#568]
I get this error when starting the revive dashboard:

    ReviveOverlay.exe - System Error - The program can't start because WinSparkle.dll is missing from your computer. Try reinstalling the program to fix this problem.

It's then followed by this error:

    ReviveOverlay.exe - System Error - The program can't start because openvr_api.dll is missing from your computer. Try reinstalling the program to fix this problem. 

I've got Oculus Home and the latest SteamVR installed.

**Comment by Armada651** [comment]
Ah it looks like I forgot to copy over some dependencies, I'll fix the installer now.

**Comment by SimonPStevens** [comment]
@Armada651 Wow, talk about great support. 35 seconds from posting an issue to getting a response! Thanks.

**Comment by Armada651** [comment]
Should be fixed now, same download link: https://github.com/LibreVR/Revive/releases/tag/1.1

As long as I'm online I receive notifications about every github issue and usually respond right away.

**Comment by SimonPStevens** [comment]
Well thanks for fixing it so quick. I was about to give up and try another day, but I think I'll stay up and play now :-)

**Comment by jcjolley** [comment]
I'm seeing the winsparkle.dll problem on the Second Beta Version 1.2.0 release.

**Comment by Armada651** [comment]
@jcjolley Sorry for that, I had to re-upload the release from a computer I don't normally use for it and it looks like one of the dependencies wasn't included. It should now be fixed.

**Comment by jcjolley** [comment]
No worries.  Thanks for the quick response/resolution!
