### ISSUE TITLE
Sexy Beach Premium Resort not working (NSFW +18)

### ISSUE THREAD

**Issue by lhardcore** [LibreVR/Revive#57]
I tried to get sbpr working ( for science of course :D) to no avail :(

http://www.hongfire.com/forum/showthread.php/445562-ILLUSION-Sexy-Beach-Premium-Resort-%28Sexy%E3%83%93%E3%83%BC%E3%83%81-%E3%83%97%E3%83%AC%E3%83%9F%E3%82%A2%E3%83%A0%E3%83%AA%E3%82%BE%E3%83%BC%E3%83%88%29-Discussion-FAQ

Would be cool to have another eXperience :P

**Comment by billyboy12** [comment]
I tried to get it to work too, no avail.

**Comment by LibreVR** [comment]
This is a 0.8 runtime game, which is not supported by Revive.
