### ISSUE TITLE
Should I play Robo Recall using Revive or RoboRevive

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#570]
I noticed that there's a fix for Robo Recall's height issue in Revive ver 1.1.  Does this mean we no longer need the separate Robo Revive install and can run the game through Revive like normal?

I installed Robo Recall earlier this week and am using Robo Revive.  I currently launch it from my desktop as was recommended.

**Comment by Armada651** [comment]
You can use either one, whichever works best for you. I personally prefer RoboRevive as I think that's the technically superior solution. But RoboRevive has its own set of issues, so if you prefer playing it through the Revive compatibility layer that's fine too.

**Comment by SimplexPL** [comment]
So what issues RoboRevive has? I thought it's unequivocally better than using Revive.

**Comment by Armada651** [comment]
https://github.com/LibreVR/RoboRevive/issues

Neither is flawless, so which one you think is better just depends on which issues your run into.
