### ISSUE TITLE
Can't run Rockband VR

### ISSUE THREAD

**Issue by darkphoenixfox** [LibreVR/Revive#573]
When I click on the game from the Revive tab inside SteamVR I hear the steam sound when you clic on an empty space and nothing happens. All other Oculus games launch fine from there.

If I try to run the game from the Revive Icon nothing happens (inject). If I try to patch it and then run it, crashes to desktop (Rbvr.exe has stopped working).

Windows 10 Creator's update, latest Nvidia drivers

**Comment by Armada651** [comment]
Duplicate of issue #572.

**Comment by darkphoenixfox** [comment]
I saw that thread earlier today but the second response had not been added yet, so it did look like a different issue. Apologies
