### ISSUE TITLE
Custom OpenVR Controller

### ISSUE THREAD

**Issue by dashingstag** [LibreVR/Revive#576]
Is it possible to use a custom openvr controller to play oculus games using Revive?

Is there an additional mapping I need to do in my OpenVR driver for it to simulate a oculus touch? I currently send openvr controller updates so it works for steam games.
So far it seems that only my 
trigger,system,grip,
buttons work.
How can I map the other buttons since openvr only gives the following?
```
        k_EButton_System			= 0,
	k_EButton_ApplicationMenu	        = 1,
	k_EButton_Grip				= 2,
	k_EButton_DPad_Left			= 3,
	k_EButton_DPad_Up			= 4,
	k_EButton_DPad_Right		        = 5,
	k_EButton_DPad_Down			= 6,
	k_EButton_A			        = 7,
	
	k_EButton_ProximitySensor             = 31,

	k_EButton_Axis0				= 32,
	k_EButton_Axis1				= 33,
	k_EButton_Axis2				= 34,
	k_EButton_Axis3				= 35,
	k_EButton_Axis4				= 36,

	// aliases for well known controllers
	k_EButton_SteamVR_Touchpad	= k_EButton_Axis0,
	k_EButton_SteamVR_Trigger	= k_EButton_Axis1,

	k_EButton_Dashboard_Back	= k_EButton_Grip,

	k_EButton_Max				= 64
```

I have taken a look at InputManager.cpp in Revive source but think I need a little guidance here on how revive simulates vive(or is it openvr) button mappings.

In addition it seems like my custom HMD openvr driver is working while using Revive.

**Comment by dashingstag** [comment]
My thoughts is I should overwrite the revive dll with a new InputDevice and pushback the device into m_InputDevices? Is this the best way? or can I interface this through the openvr driver?

**Comment by Armada651** [comment]
@dashingstag Revive uses the `k_EButton_SteamVR_Touchpad` to simulate buttons, Revive queries where the touchpad is touched and uses that to determine which button should be pressed if the touchpad is pressed. Here's the mapping:

![mapping](https://cloud.githubusercontent.com/assets/18057864/20237490/bf4319b4-a8cb-11e6-8df6-767678c1b77b.png)

Also, swiping across the touchpad activates the thumbstick.

**Comment by Armada651** [comment]
By the way, if you are writing a custom OpenVR driver for a custom tracked controller that *does* The necessary extra buttons we could look into mapping those through either the unused buttons.

The DPad and Button A are unused on the Vive controller, but offer more than enough enums to map these buttons. So if you could map these to your physical buttons I could include those in Revive.

If you also have a physical thumbstick you could offer an axis with the `k_eControllerAxis_Joystick` type and I could have Revive look for axes with that type to use for the thumbstick.

**Comment by dashingstag** [comment]
Oh nice I got my controllers to work for the "Oculus Touch Basics". My issue was that I had set my properties wrongly, I had set to joystick instead of touchpad.

Does the oculus remote mapping work in a similar way? I assume it would also work for my controllers as well. Is there a good game I can use as a benchmark? I tried a few games listed on the compatability list but  some didn't really used the remote and there were others that I couldn't progress in but I wasn't sure if it was because I didn't know how to play the game or it was because my mapping was wrong.

**Comment by Armada651** [comment]
This is explained in the wiki, turn off one of your controllers, the
remaining one becomes the Oculus Remote. Oculus Farlands is a good test for
the remote.

Op 20 apr. 2017 5:08 a.m. schreef "dashingstag" <notifications@github.com>:

**Comment by dashingstag** [comment]
Oh, I thought turning off one controller was optional. Okay thanks for your help!

**Comment by Armada651** [comment]
I wish it was, the problem is that games very much expect these to be separate devices. And if the same device sends both Touch and Remote messages that will confuse some games.

**Comment by Armada651** [comment]
By the way, if you don't mind me asking, what kind of controller are we talking about?

**Comment by dashingstag** [comment]
I am playing around with a Ximmerse controller :)
