### ISSUE TITLE
Adr1ft--Advanced Settings

### ISSUE THREAD

**Issue by Usurper1** [LibreVR/Revive#579]
Heyyyy. Thank you guys again, and in advance, for bringing us Revive and Advanced Settings. 

Im just having an issue with the resolution scaling for Adr1ft. It seems that the scaling in Advanced Settings has no affect on the game...? The default resolution in the game is really terrible and I cant really enjoy playing it unless I can bump it up a bit. Thoughts?

**Comment by Armada651** [comment]
There are multiple settings that control supersampling in Revive, which one
are you using?

There is a chance that Adr1ft never queries the resolution from the Oculus
SDK. If that's the case there's nothing you can do.

Also, there is a Vive version of Adr1ft on the steam store, you might want
to contact the devs so you can get a Steam key to play the version with
native support.

**Comment by Usurper1** [comment]
Im an idiot. I wasnt thinking. I actually HAVE the steam/HTC version, which would explain why revive supersampling doesnt work. Haha. I still gotta find a work around. Thanks!

**Comment by Usurper1** [comment]
Actually wait...the Advanced Settings are seperate from Revive, but still have no affect.

**Comment by Armada651** [comment]
Well, Revive has its own on the Revive tab. But if the SteamVR tab doesn't work after restart, then Adr1ft is just not querying SteamVR for the recommended render target size.
