### ISSUE TITLE
Question about using Revive with Oculus Store

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#580]
I have been using Revive for months now and buy games from the Oculus store.  A message appeared at the top of the Oculus store saying "New drivers are required for Oculus. Update now."  I know during the original install of Revive Oculus setup wasn't run.  Should I accept this update or ignore it?

**Comment by Armada651** [comment]
It doesn't really matter, Revive completely bypasses the Oculus drivers. Everything is fine as long as you can download and start games.
