### ISSUE TITLE
Unable to run Dirt Rally (edit: solved)

### ISSUE THREAD

**Issue by Lafayetteproulx** [LibreVR/Revive#588]
I followed the steps, I installed the latest version (1.1.1.1) of revive, started Steam VR, did the right click and patch, went to my Dirt Rally directory and selected drt.exe. It did its thing, put the .dll files in, I disabled "use desktop theater" in the Dirt Rally properties in Steam. When I go to run Dirt Rally it says "Dirt Rally does not support VR..." I click ok and it starts on my desktop but nothing ever shows up on the headset.

Any idea what I could have possibly done wrong?

**Comment by Lafayetteproulx** [comment]
I fixed the issue by doing a verify game cache on the Dirt Rally folder and trying all the steps again, for some reason it worked fine!

**Comment by Armada651** [comment]
Good to hear you fixed it.
