### ISSUE TITLE
For me, Revive Injector cannot work around the Oculus DRM

### ISSUE THREAD

**Issue by cbuchner1** [LibreVR/Revive#59]
I drop the executables of the game onto ReviveInjector.exe (v0.4.1) as instructed by the manual, while SteamVR is running. I run Windows 10 Home (German language version).

So far I've tried unsuccessfully:

* The Climb ->  "A connection to Oculus Store could not be established. Please check your Internet connection and Firewall and ensure that you are signed into the Oculus Store with your account." (I translated this from a German langage dialog box that popped up)

* Henry -> Unable to launch app: App running from non-trusted source (1971039)

* Lucky's Tale (both v1.0.1 and v1.0.3)  -> Entitlement check failed

My Oculus Home software is version 1.3.2

I see these kinds of errors in my Oculus service log when I run any Oculus software through ReviveInjector:

14:02:48.403 {INFO}    [FastIpc] Connected clientID 7
14:02:48.403 {WARNING} [FastIpc] Unable to find appId for PID 8116
14:02:48.403 {!ERROR!} [OAF ERROR] library\LibraryManager.cpp(710) : App running from non-trusted source (1971039)
14:02:48.403 {!ERROR!} [IpcRouter] Command /library/auth/get_signature caused an error: App running from non-trusted source (1971039)
14:02:48.406 {!ERROR!} [IpcRouter] Client (Unknown) attempted to call API before fetching signature: /library/auth/get_app_viewer_id
14:02:48.406 {!ERROR!} [OAF ERROR] ipc\ipcRouter.cpp(94) : Must call get_signature first (1971051)
14:02:48.406 {!ERROR!} [IpcRouter] Client (Unknown) attempted to call API before fetching signature: /library/get_fbns_credentials
14:02:48.406 {!ERROR!} [OAF ERROR] ipc\ipcRouter.cpp(94) : Must call get_signature first (1971051)
14:02:48.406 {!ERROR!} [IpcRouter] Client (Unknown) attempted to call API before fetching signature: /rooms/get_and_clear_room_id
14:02:48.406 {!ERROR!} [OAF ERROR] ipc\ipcRouter.cpp(94) : Must call get_signature first (1971051)
14:02:49.569 {!ERROR!} [IpcRouter] Client (Unknown) attempted to call API before fetching signature: /library/set_fbns_credentials
14:02:49.570 {!ERROR!} [OAF ERROR] ipc\ipcRouter.cpp(94) : Must call get_signature first (1971051)
14:02:49.709 {!ERROR!} [IpcRouter] Client (Unknown) attempted to call API before fetching signature: /library/auth/get_scoped_token
14:02:49.709 {!ERROR!} [OAF ERROR] ipc\ipcRouter.cpp(94) : Must call get_signature first (1971051)

I still own a DK2, so my purchase of The Climb wasn't a loss.

Christian

**Comment by LibreVR** [comment]
Interesting log you posted there, it will probably come in handy. Anyway, to fix your problem just follow the instruction on the front page:

> Newly installed games will give you an Entitlement check failed error until you reboot the Oculus Runtime Service, quickest way to do that is opening a command prompt and entering these commands:
>
> OVRServiceLauncher -stop
> OVRServiceLauncher -start

**Comment by cbuchner1** [comment]
I tried restarting the OVR service as instructed, but this did not fix my problem. Also I had rebooted after installing The Climb.

"Allow unknown sources" was toggled on also.

There's probably something else that seems to be affecting my system.

**Comment by LibreVR** [comment]
@cbuchner1 Are you using symbolic links?

**Comment by cbuchner1** [comment]
I've indeed moved the Oculus "Software" folder, not the entire Oculus folder to my D:\ drive

I am using a directory symlink (not a Junction) as indicated below

 Verzeichnis von C:\Program Files (x86)\Oculus

30.04.2016  13:54    <DIR>          .
30.04.2016  13:54    <DIR>          ..
30.04.2016  13:54    <DIR>          Downloads
30.04.2016  13:54    <DIR>          Manifests
02.04.2016  03:24           112.166 Oculus.ico
02.04.2016  03:19         2.920.744 OculusSetup.exe
30.04.2016  13:54         2.384.075 OVRLibraryService.log
30.04.2016  12:18             7.717 OVRRedistributableInstaller.log
30.04.2016  00:19    <DIR>          Redistributables
07.04.2016  00:08    <SYMLINKD>     Software [D:\Oculus\Software]
19.04.2016  21:17    <DIR>          Support
               4 Datei(en),      5.424.702 Bytes
               7 Verzeichnis(se), 145.789.952.000 Bytes frei

**Comment by LibreVR** [comment]
That explains it, we don't support symlinks, simply because Oculus Home expects the game to be executed from `C:\Program Files (x86)\Oculus`. This doesn't happen for the ReviveInjector because it doesn't use the symlink.

To fix it, install Oculus home to your D drive, which is officially supported in version 1.3.2.

**Comment by cbuchner1** [comment]
Thank you - I will try to uninstall Oculus Home and reinstall it directly to D:\Oculus then.

**Comment by LibreVR** [comment]
@cbuchner1 Word of warning though, the Oculus uninstall procedure will try to remote all your installed games.

**Comment by cbuchner1** [comment]
I removed the symlink before doing that. ME <- Smart Guy ;)

**Comment by Razalom** [comment]
I can not get The Climb to run as keep getting the above error. I have not used Symlink and have installed it to F:\Oculus which is one of the default ones it gives you an option for.

I have rebooted a fair few times as this has been going on for a few days now. Both with 1.3.2 and 1.4 updates (have tried the latest revive as well released today)

Thoughts?
