### ISSUE TITLE
VR Performance Decrease Since 1.1.1 In Rock Band VR

### ISSUE THREAD

**Issue by light4speed** [LibreVR/Revive#593]
First, thanks so much for making and supporting this incredibly useful tool!

Since the latest oculus Driver changes it seems that some Oculus games have now had a performance significant performance decrease. 

Rock Band VR used to work fantastically about a week ago, prior to the oculus updates and driver changes. However, now the game really starts to struggle even after turning down the graphic settings three notches from what I used to run it at. It seems that the real jitter picks up right after starting to play any song and sadly it makes the game almost unplayable right now. **Plus it seems now that running Rock Band takes up a lot more RAM and occasionally causes an "out of memory error".**

_Chronos VR used to work on nearly maxed out settings but since this update there is significant jitter. Turning town the settings to NORMAL across the board fixes this but, it used to work on higher settings just fine._ **--FIXED in 1.1.2.1**

So far I've tried:
-Turning down Rock Band VR Resolution to NORMAL and Quality to HIGH, still lots of jitter
  (Running any resolution above NORMAL with Quality set to NORMAL causes jitter)
-Running revive 1.1 but, this is one of the games that crashes due to the recent change. 
-Running other games through revive (First Contact, Lucky's Tale, etc.), none seem to have been affected at all
-Turning Off Async Reprojection, seems to help a bit 

Any help is greatly appreciated.

**Comment by Armada651** [comment]
Please test this release: https://github.com/LibreVR/Revive/releases/tag/1.1.2

**Comment by light4speed** [comment]
After testing Rock Band VR with 1.1.2.1 the performance hit still remains. Still leaving Asynchronous off helps a bit but, anything above Quality HIGH and Resolution NORMAL causes jitter.

**Comment by Armada651** [comment]
Can you compare the performance in Chronos between version [1.0.4](https://github.com/LibreVR/Revive/releases/tag/1.0.4) and [1.0.5](https://github.com/LibreVR/Revive/releases/tag/1.0.5)?

**Comment by light4speed** [comment]
Well performance has improved from 1.1.1 to 1.1.2.1 for Chronos. The performance is now the same that it was back in 1.0.6.

**Comment by Armada651** [comment]
Still, please try 1.0.4, that is the last version that had an optimization heuristic that was reverted in 1.0.5

**Comment by light4speed** [comment]
Alright, let me see...

**Comment by light4speed** [comment]
1.0.4 basically the same as 1.1.2.1 just slightly more dropped frames.
1.0.5 objectively is exactly the same as 1.0.4, head rotation feels off VERY rarely (could just be me).

**Comment by Armada651** [comment]
Ok, well looks like Chronos isn't affected by that change.

**Comment by light4speed** [comment]
Yeah appears so but, Rock Band is a real head scratcher. I can say that the "Memory Leak" from Before seems fixed with 1.1.2.1. However, nothing else seems to have been improved. I have noticed that depending on the effects coming off the guitar keys some cause the game to stutter but, this is problem within the game not with Revive. But, the most interesting thing is that the overall GPU load is just much higher than it used to be, and this is just exacerbated as soon as the song map appears.

**Comment by light4speed** [comment]
Correction: the memory error still seems to be there. The game takes far over 4 GB of RAM when running. No clue why.

**Comment by light4speed** [comment]
**# UPDATE**
I may have figured the issue out: I always leave my SS setting on 1.3 in open VR advanced settings, (NOT under revive) just for steam VR and it appears that this recently started affecting Rock Band Greatly. Interestingly this effect only applies to this game. Right after turning it back to 1.0 Rock Band can now run nearly maxed out again.

**Comment by Armada651** [comment]
Just for the record, the slider under Revive applies on top of the one you set for SteamVR.

**Comment by light4speed** [comment]
Really? I've never noticed before. My SS has always been set to 1.3 with no noticeable effect to any oculus games besides Rock Band VR. It doesn't seem to affect the perceived quality, but the performance tanks. The in-game settings affect the quality so much more.
