### ISSUE TITLE
Oculus needs need drivers - do i Install?

### ISSUE THREAD

**Issue by randybaton** [LibreVR/Revive#595]
the oculus is stating new drivers are required, should i install them?

I haven't used revive in a while and went to plat superhot but it won't  start. So wondered if it could require new drivers?

From the steam menu an error is generated saying 'failed to  launch'

The Revive menu in steam just has a spinning circle, so presume something isn't right with my revive set up. Just wondering if #its the drivers?

**Comment by Balderick** [comment]
Yes.  You can install the drivers without running setup.

**Comment by Armada651** [comment]
You need to update or reinstall Revive.

**Comment by randybaton** [comment]
Cheers, just figured it out. I had to install new update for revive and then restart

thanks
