### ISSUE TITLE
Unable to see the tab after running overlay(source)

### ISSUE THREAD

**Issue by dashingstag** [LibreVR/Revive#596]
I am trying to build the source for the overlay. I have managed to built it. I can run the exe and steamvr is run but the revive tab does not show. 

As a side note, when I tried running the ReviveOverlay.exe(built from source) in the output folder installed from the installer, the tab is displayed. I haven't found the reason but I am still looking. 

There are other things I noticed:
I notice some Qt dependencies QtGamepad, scenegraph, platforminputcontexts are not produced in the Release. Even when I add these file the version in the release folder does not create the tab.

Any hints on what may be the issue? Also, what is the best way to debug reviveoverlay?

**Comment by dashingstag** [comment]
hmm I also noticed that I can't compile reviveoverlay with QT 5.8 ( i can compile wit 5.7.1) but the installer has QT 5.8 dlls ?

**Comment by Armada651** [comment]
I currently use 5.8 to compile the overlay without issues. I think you may not have cleared all the build files (moc_*.cpp is a generated file) before upgrading to 5.8.
