### ISSUE TITLE
Roborecall crash

### ISSUE THREAD

**Issue by freerunner8881** [LibreVR/Revive#597]
Robo recall will run level 1-1 but all other level crash while loading and I've tried roborevive but the same thing happened all my other games work it's just robo recall

**Comment by light4speed** [comment]
Did you buy the game from the Oculus or are you using the UNREAL MOD version?

**Comment by Dragoboss** [comment]
A year later, response was never given. On top of that the regular Robo Recall works fine with Revive.
For the Mod edition (for example the one from the Epic launcher RoboRevive can be used).
