### ISSUE TITLE
Games will not pass entitlement check from a symlink location

### ISSUE THREAD

**Issue by Rirath** [LibreVR/Revive#6]
I've checked the "unknown sources" and rebooted, but despite numerous attempts, this did not solve it.  What did solve it, however, was undoing my symlink and pasting the files back where they normally would be.

I had symlinked C:/Program Files (x86)/Oculus/Software to D:/games/Oculus/Software.
When I moved /Software/playful-luckys-tale back to C:/Program Files (x86)/Oculus/ the game started without any problems.

It's worth noting I played through the entire game on the DK2 this way with no problems, so I know my symlink is working correctly.

**Comment by Rirath** [comment]
The same thing is true with Dreamdeck.  From the symlink I get:
Unable to launch app: App is running from non-trusted source.

Moved back to its original location, no problems.  This too worked fine on my DK2 through Oculus Home.

**Comment by Kaesemuffin** [comment]
I still got this problem. Regardless of having it at c / d / e ... x86 x64 folder

**Comment by barronj** [comment]
Oh, so it is the symlink that is the problem! I got it to work, thanks to you. A bit of a pain, though.

**Comment by Creep23** [comment]
Did you place and run the Revive-Injector in the same location as the executables?
In your case "D:\games\Oculus\Software\oculus-dreamdeck\WindowsNoEditor\Dreamdeck\Binaries\Win64\ReviveInjector.exe"

**Comment by Rirath** [comment]
Yes, they are in the same folder.  I am 90% sure my setup is correct and the issue is entirely with the symlinked location not passing Oculus's check when used with ReVive. (But it DOES pass Oculus's check when used with the DK2.)

At least 3 other people have told me this has fixed their issue.

**Comment by LibreVR** [comment]
Oculus now officially supports installing Oculus Home on a different drive.
