### ISSUE TITLE
Unable to purchase items in GrooVR

### ISSUE THREAD

**Issue by Vlaphor** [LibreVR/Revive#600]
GrooVR is a VR music visualizer that's available on both the GearVR and the Rift.  I can run the Rift version in ReVive, but when I try to buy anything in the game, the screen goes black for a second and then pops back up with nothing changed.  Is there a way this can be fixed?  Thanks.

**Comment by Armada651** [comment]
No way to fix this yet unfortunately, since Revive bypasses Oculus Home it can't do in-app purchases.

**Comment by Dragoboss** [comment]
This will not and cannot be fixed for the time being.
Best you can do if you still want this is to ask the developer of this app if they can also offer their IAPs as DLC purchases on the Oculus Store, much like EchoVR has done for Echo Combat.
