### ISSUE TITLE
Revive overlay not showing

### ISSUE THREAD

**Issue by ethanj7** [LibreVR/Revive#601]
Ok so i have been trying to play Robo recall and i have everything that i need: Oculus home, revive, the game itself and i also have Viveport. i have the latest versions of everything. so i'm in VR and i click the home button on my Vive controller and i see the revive tab and the Viveport tab next to the desktop tab. but when i click on either of the two, nothing comes up, and it's not like a blank blue screen that comes up, i mean literally nothing happens and no overlay shows up. i have also tried running the revive overlay.exe. is there something that i need or something that i need to change?

i really need some help. ive been trying to play this for 3 days :(

and also the viveport tab is doing this aswell.

**Comment by CarrotSurvivor** [comment]
Dude just google "roborevive" and install that. Gives Roborecall native vive support. Read the instructions on the roborevive page it's the best way to play it

**Comment by ethanj7** [comment]
thanks man! i downloaded it and it starts running, but it comes up with this error: http://imgur.com/a/wVo6W

**Comment by Armada651** [comment]
Use the desktop shortcut.

**Comment by ethanj7** [comment]
i did

**Comment by Armada651** [comment]
Try rebooting your PC first.

**Comment by ethanj7** [comment]
thanks! that did the trick!

**Comment by ethanj7** [comment]
what about revive though? there will be other games on oculus that i may not be able to play without the revive overlay?

**Comment by Armada651** [comment]
All games from the overlay are also available in your Steam Library while
Revive is running.

Op 10 mei 2017 1:05 a.m. schreef "ethanj7" <notifications@github.com>:
