### ISSUE TITLE
Map Razer Hydra buttons to Oculus Touch buttons

### ISSUE THREAD

**Issue by duig0** [LibreVR/Revive#603]
I use a Razer hydra....I get rotational and positional movement. Grip and triggers are mapped and working.
Buttons don't seem to be mapped.

Steamvr overlay opens whenenu button is pressed....cannot bypass the screen in oculus game.

Any ideas?

Thanks in advance

**Comment by Armada651** [comment]
Button 4 on the Razer Hydra controller is the menu button.

**Comment by duig0** [comment]
Thank you Armada, I'll try that when I finish work.

I'm pretty sure I tried all buttons  in trial and error  but I might have missed that.

Is there somewhere on here or in the revive folder where the key binding's can be seen.

For instance, the Xbox buttons on the touch controller don't seem to be mapped to hydra buttons etc.

Thank you for your help.

After testing if successful I will go ahead and close the issue

**Comment by Armada651** [comment]
Revive is only intended for Vive systems. However as a special exception I'll consider adding support for the buttons on the Razer Hydra, mainly because I'd like to have a way for third-party controllers to map the Oculus Touch buttons directly.

However I do not plan to make further adjustments to Revive to accommodate non-Vive systems.

**Comment by duig0** [comment]
Thanks you so much Armada. Will absolutely donate.

:-)

**Comment by Armada651** [comment]
Fixed in commit 1b8ab3c2d9470f7cf30f900bef43d5c5b16af2b2.

Will be part of the next release.

**Comment by Armada651** [comment]
Please test this release: https://github.com/LibreVR/Revive/releases/tag/1.1.2

**Comment by Armada651** [comment]
Were you able to test the new version?

**Comment by duig0** [comment]
Hi Armada,

I updated but the hydras remain mapped as before

Am I supposed to manually map the buttons somewhere?

Thanks in advance....lovin revive :-)

**Comment by Armada651** [comment]
The A/X and B/Y buttons are now mapped to the 1 and 2 buttons on your hydra controllers. Also, the thumbstick no longer has multiple functions attached to it, it's now just a joystick.

**Comment by duig0** [comment]
Hi Armada, 

Tried Lucky's tail, Wilson's heart and touch tutorial....buttons are still mapped as before I.e buttons mapped to joysticks etc.

Mabey I need a clean install of revive?

**Comment by duig0** [comment]
On further inspection the mapping is as follows

Joypad - joypad X/A B/Y

Button 1 - X/A 
Button 2 - not mapped
Button 3 - joypad pressed
Button 4 - menu button (not mapped in touch tutorial)
Shoulder buttons - grip
Trigger - trigger

**Comment by Armada651** [comment]
I'll look into it further, I also have a Hydra lying around somewhere. But one thing I noticed is that the drivers available on Steam are different from the drivers available on Github. That should explain why it doesn't behave like I expected it to.

**Comment by duig0** [comment]
I have the hydra driver from steam. It was recommended elsewhere to delete the unofficial driver from Github....thank you for looking into this
