### ISSUE TITLE
1.1.2.0 - Unspoken still with tracking lag.

### ISSUE THREAD

**Issue by Werbel** [LibreVR/Revive#604]
Hi there!

I've just downloaded and tested new release, which should fix tracking for Unspoken and Climb.

I'm reporting that tracking is still broken!

**Comment by Armada651** [comment]
Nowhere in the changelog or in the relevant issue ticket does it mention this fixes tracking latency in The Unspoken and The Climb. Unfortunately these games inherently use more tracking prediction, so it is not something that can be fixed on the Revive side.

**Comment by Werbel** [comment]
Well, you are right, I just assumed it's related to the Unspoken - "  Reduce jitter in games with tracking prediction issues (#584)".

That's sad it won't be fixed anytime, it's my fav game but it makes me nauseous after a short time...

Thanks for update anyway!

**Comment by Armada651** [comment]
You're right that it does affect The Unspoken, but unfortunately this was specifically targeted at "jitter", not tracking latency.
