### ISSUE TITLE
Revive Game Matrix - Second Page?

### ISSUE THREAD

**Issue by gstraight** [LibreVR/Revive#605]
I bought Wilson's Heart from Oculus, installed the game and went to play it. Launched SteamVR and selected the Revive tab at the bottom. That brought up the grid of Oculus software + purchased games. Looking at the grid, Wilson's World was not there. Looking at the grid I wondered if there was only so much room in the Revive grid. I uninstalled one game and was surprised that Superhot now showed, a game I had almost forgotten about. So I uninstalled another game and sure enough Wilson's Heart showed in the list of games. Played the game and all was well. 

So is there a limit to the number of games one can purchase from Oculus and have show up in the Revive grid and that is managed by uninstalling certain games or is there a second, third etc page of the Revive grid that I do not know how to access.

**Comment by Armada651** [comment]
You can move your thumb across the touchpad to scroll the page.

**Comment by gstraight** [comment]
Dang I just knew it was something easy. Thanks
