### ISSUE TITLE
Dirt Rally simply won't get into my headset!

### ISSUE THREAD

**Issue by tomwchick** [LibreVR/Revive#606]
Since I haven't seen others bringing this up recently, I'm assuming it's a "me problem".  So I'm going to post the steps I've taken and hope someone can maybe tell me what I've done wrong, or at least how to troubleshoot whatever issue I'm having.

1. Steam VR installed (duh!), Oculus software installed, Oculus account set-up, Revive installed, working version of Dirt Rally on Steam, everything updated.

2. Start Steam VR (Revive icon appears in taskbar, Revive is an option from within Steam VR, alongside Steam and Desktop options), confirm Vive hardware is detected and ready. I have tried this with Steam VR and the current beta version of Steam VR.

2a. I have previously chosen the Patch... option from the Revive icon in the taskbar, and I've selected drt.exe from within its folder in steamapps/common.  It seems to have added the requisite *.dll files into the directory with drt.exe.

2b. I have unchecked "Use Desktop Game Theatre while Steam VR is active" under the Dirt Rally properties box in Steam.

2c. If I select the Revive icon from within Steam VR, the Steam interface brings up a screen showing four Oculus programs I never downloaded (I assume they're part of the Oculus software install?). I can't select any of them, and I can't even move the selection option.  At this point, I have to back up in order to interact with the Steam interface.  I wonder if this might be related to my inability to get Dirt Rally showing up in the Vive.  

3. I open Dirt Rally from my desktop.  I get this warning:

"Dirt Rally does not support VR. It will appear on your desktop and may affect VR performance."

I select OK to move past the warning, at which point Dirt Rally opens on my desktop. Stream VR shows only the empty whiteroom.

3a.  Alternatively, I've tried opening Dirt Rally from the Steam interface within Steam VR, even though I know that's the wrong way to do it.  But I've verified that when I do this, Dirt Rally opens on the desktop, but I'm still in the whiteroom in Steam VR.

Can anyone tell what I might be doing wrong?

**Comment by Armada651** [comment]
Are you running Windows 7 by any chance?

**Comment by Armada651** [comment]
Also, can you try installing the DirectX End-User Runtime? https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by tomwchick** [comment]
Armada651, you are my new favorite person.  That seems to have done the trick!  This was on Windows 10, and I have no idea why installing DirectX was an issue.  I play a ton of games on this computer and I've never had any problems like this.  So glad you were able to troubleshoot it for me!

**Comment by Armada651** [comment]
Well that explains a lot, this issue is related to #607 which I just solved, thank that guy for sending a crash log that brought this to my attention.

I've released a hotfix that fixes the crash when injecting Revive, but I'm still working on a proper fix. I'll mark this issue for the next milestone so I can fix it properly.

The reason why installing the old DirectX End-User Runtime fixes the issue is because that will install the *older* version of XInput (1.3) that Revive expects to be installed. A lot of people might have this already installed from other games they play.

**Comment by WesleyM77** [comment]
I'm having this issue for windows 7. Will installing that work for me?

**Comment by Houseman2032** [comment]
Hey I am also having this problem.

I have installed the runtime but it is still giving me the same message

"Dirt Rally does not support VR. It will appear on your desktop and may affect VR performance."

The only thing I haven't done is create an occlus store account (no intention of buying from there really)

**Comment by Armada651** [comment]
That is normal, just press OK and it will start in VR.

**Comment by Houseman2032** [comment]
It just started up in monitor but white room in headset, I'm going to try the older version base don another thread here. Will try it tomorrow.

Thanks for the reply man.

**Comment by Houseman2032** [comment]
The old version worked for me btw.

**Comment by Dragoboss** [comment]
Original and referenced tickets are solved.
If you are still having further issues please report in with a new ticket with the right details added.
