### ISSUE TITLE
Crash-Problems with Lucky Tales, Facebook VR and all except MEDIUM

### ISSUE THREAD

**Issue by daJhoony** [LibreVR/Revive#607]
Hi,

Because i got some problems with revive to get it working, i did a complete new windows 10 64bit installation to do a working revive environment.
I did all whats in the manual.
+ Install STEAM
+ Install STEAM VR
+ Activate BETA vor STEAM
+ Install newest Oculus Software (skipping setup)
 - Install MEDIUM, Avatare, Facebook, Oculus Tutorial
+ Install REVIVE (Newest version inkl. Update function which says its ok)
Start MEDIUM - works fine
Starts all other games like LUCKY TALES, Facebook VR, Avatare Making, etc.
Everything crashed after a short period of loading. 
I thought it had to do something with the windows 10 GAME environment, but i deactivated it and it dont work either. 
Some Games (Tutorial) are starting, but didn't recognize the HMD Vive. Many newstarts (Software and Hardware) did not help.
Any ideas what i could do?
Thanx for this great tool, by the way :)

**Comment by daJhoony** [comment]
Hio, thx for fast answer.
i really liked your solution. But to start STEAM with admin rights didn't work. 
I will drop you a screenshot from the error message and the crash log. Hope you will find time to look in it and give me a hint. I allready deactivate all kind of firewall.
Would be great to hear again from you. i love your tool. And its not only a tool. It's a movement!
Thanx for that!
[CrashMessageLog.zip.zip](https://github.com/LibreVR/Revive/files/994303/CrashMessageLog.zip.zip)

**Comment by Armada651** [comment]
Can you try an older version of Revive? Version 1.1.1 in particular: https://github.com/LibreVR/Revive/releases/tag/1.1.1

**Comment by daJhoony** [comment]
Ok, is it enough to reinstall revive or have i to reinstall all of the software (Steam, oculus, revive)?

**Comment by Armada651** [comment]
Just Revive is enough.

**Comment by daJhoony** [comment]
Hmm, it didn't work too. But i found out, that Steam VR has his OWN Beta Program, which i activate now, too. But same result. But dreamdeck wasnt working last time. so i will try to reinstall Lucky Tales in oculus, Maybe something happens between these two installations. I will try to reinstall Lucky Tales and will see. I will send you an update. thx so far.

**Comment by Armada651** [comment]
Ok, thanks to the crash dump you posted in the crash log zip file I've found the problem.

For some reason XInput 1.3 is not installed on your system, while Revive expects that it is present in your system folder. So instead Lucky's Tale uses the xinput1_3.dll that's shipped with the Oculus Runtime, but Revive doesn't look there.

I'll have to find a different solution for this problem. In the mean time you can fix this issue by installing the DirectX end-user runtime: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by daJhoony** [comment]
Oh great.
Lucky tales is allready history :) but loading again! thx i will try it now.

**Comment by daJhoony** [comment]
YOU ARE MY HERO! Its working! :)
THANX for great the support.
Where do i send the money to?

**Comment by Armada651** [comment]
I don't accept donations right now, I might start accepting donations in the future though.

**Comment by Armada651** [comment]
I've also released a hotfix for this problem, it shouldn't crash anymore even if you don't have the old DirectX End-User Runtime installed.
