### ISSUE TITLE
wilsons heart doesnt start for me with revive.

### ISSUE THREAD

**Issue by yanivtr** [LibreVR/Revive#609]
ANY suggestion ? The  loading wheel turns and nothing happens

**Comment by Armada651** [comment]
Can you post your logs from `%APPDATA%\Revive`? Just enter that into the explorer address bar and drag-and-drop the txt files into the comment field here.

**Comment by joeman719** [comment]
I have same problem.

Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe"  /library "Software\twisted-pixel-games-wilson-s-heart\WHVR.exe" null
Creating process: C:\Program Files\Oculus\Software\Software\twisted-pixel-games-wilson-s-heart\WHVR.exe null 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x73c6f550
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x73c6f550
Injected dlls successfully


libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: C:\Program Files\Oculus\Software\
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/ats-kurvet-mythos-of-the-world-axis_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/crytek-robinson-the-journey.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/crytek-robinson-the-journey_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/disney-online-disney-movies-vr.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/disney-online-disney-movies-vr_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/epic-games-odin.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/epic-games-odin_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/epic-games-showdown_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/fearless-fearless-vr.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/fearless-fearless-vr_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/felix-and-paul-studios-introduction-to-virtual-reality_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/frame-vr-diggers-vr_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/hammerhead-vr-abe-vr.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/hammerhead-vr-abe-vr_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/holospark-seance-the-unquiet-preview.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/holospark-seance-the-unquiet-preview_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/magnopus-ultra-iss-dev.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/magnopus-ultra-iss-dev_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-dreamdeck_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-farlands_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-first-contact_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-henry_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/oculus-lost_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/sanzaru-games-inc-recoil.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/sanzaru-games-inc-recoil_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/studio-transcendent-rapid-fire-a-brief-history-of-flight_assets.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/twisted-pixel-games-wilson-s-heart.json
Loading manifest: file:///c:/Program Files/Oculus/Software/Manifests/twisted-pixel-games-wilson-s-heart_assets.json
Found assets bundle ats-kurvet-mythos-of-the-world-axis_assets
Found application crytek-robinson-the-journey
Found assets bundle crytek-robinson-the-journey_assets
Found application disney-online-disney-movies-vr
Found assets bundle disney-online-disney-movies-vr_assets
Found application epic-games-odin
Found assets bundle epic-games-odin_assets
Found assets bundle epic-games-showdown_assets
Found application fearless-fearless-vr
Found assets bundle fearless-fearless-vr_assets
Found application felix-and-paul-studios-introduction-to-virtual-reality
Found assets bundle felix-and-paul-studios-introduction-to-virtual-reality_assets
Found assets bundle frame-vr-diggers-vr_assets
Found application hammerhead-vr-abe-vr
Found assets bundle hammerhead-vr-abe-vr_assets
Found application holospark-seance-the-unquiet-preview
Found assets bundle holospark-seance-the-unquiet-preview_assets
Found application magnopus-ultra-iss-dev
Found assets bundle magnopus-ultra-iss-dev_assets
Found assets bundle oculus-dreamdeck_assets
Found assets bundle oculus-farlands_assets
Found assets bundle oculus-first-contact_assets
Found application oculus-henry
Found assets bundle oculus-henry_assets
Found assets bundle oculus-lost_assets
Found application playful-luckys-tale
Found assets bundle playful-luckys-tale_assets
Found application sanzaru-games-inc-recoil
Found assets bundle sanzaru-games-inc-recoil_assets
Found assets bundle studio-transcendent-rapid-fire-a-brief-history-of-flight_assets
Found application twisted-pixel-games-wilson-s-heart
Found assets bundle twisted-pixel-games-wilson-s-heart_assets
Removing manifest: oculus-first-contact
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest
Launching application: twisted-pixel-games-wilson-s-heart

**Comment by joeman719** [comment]
I have same problem

Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe"  /library "Software\twisted-pixel-games-wilson-s-heart\WHVR.exe" null
Creating process: C:\Program Files\Oculus\Software\Software\twisted-pixel-games-wilson-s-heart\WHVR.exe null 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x73c6f550
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x73c6f550
Injected dlls successfully

**Comment by joeman719** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/997616/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/997617/ReviveOverlay.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/997619/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/997618/ReviveInjector.txt)

**Comment by Armada651** [comment]
I can boot Wilson's Heart without issues. Try rebooting your PC.

If that doesn't work, try installing the DirectX End-User Runtime: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by joeman719** [comment]
where should I extract files? and thank you for reply

**Comment by Armada651** [comment]
This link should be easier for you: https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by joeman719** [comment]
So after restarting several times and installing link provided still same issue all my other revive games work fine.

**Comment by joeman719** [comment]
Wilson's Heart got updated so revive will no longer support new download. $40.00 down the drain.

**Comment by Armada651** [comment]
You're overreacting, like I said it starts fine for me and I am running the latest version.

What happens if you try to start `C:\Program Files\Oculus\Software\Software\twisted-pixel-games-wilson-s-heart\WHVR.exe` manually, do you at least get the Oculus Rift not found prompt?

**Comment by joeman719** [comment]
yes it says "Please plug in a Rift headset to continue".

**Comment by joeman719** [comment]
uninstalled will reinstall to see if that helps.

**Comment by Armada651** [comment]
Ok, what happens if you try to use the Patch... feature in Revive? Just right-click the tray icon while SteamVR is running and select the Patch option,

**Comment by joeman719** [comment]
Reinstalled it same problem.Ran patch and tried to start manually nothing. running gtx 970 8 gig ram i5 core

**Comment by Armada651** [comment]
So not even the dialog box about a Rift not being connected?

**Comment by joeman719** [comment]
No it acts like I never launched game

**Comment by Armada651** [comment]
Sounds like an unknown crash or something, if you want to get it fixed we need to do some remote debugging. At my on Steam with the username "armada651", we can chat there and debug the issue.

**Comment by Armada651** [comment]
I've fixed the issue with @joeman719, turns out he had an old version of Revive installed. So @yanivtr you should make sure you're running the latest version. You can check for update by right-clicking the Revive tray icon and click "Check for updates" or just install the latest version from this page: https://github.com/LibreVR/Revive/releases

**Comment by Ganerumo** [comment]
I'm bumping this to say that I have the same issue.

Running the game outright gives me the expected "please plug in a Rift headset to continue" message.
Running the game with injection does nothing. Logs indicate the dlls are injected successfully, but nothing else happens. The game stays a while as a process but eventually disappears.
Patching the game then running the executable usually does nothing. On one occasion, I've had it work, but was greeted with the entitlement check message. Never worked since.

I tried running everything in administrator. Reinstalled Steam, Oculus Home and Revive (in that order). It works with both legal and pirated copies of Oculus games, I tried on Robo Recall and Superhot, both worked although Robo Recall (the legally owned of the two) gave me a headset error twice.

Revive is up to date. Since people had no issues running the game at release I think I'm going to chalk this up to an update that occurred since then, be it Steam, Oculus, Revive or even Win10's creator update. Maybe the version I've downloaded isn't fitting for VR, but seeing as the OP of this thread had the issue on a legal copy, I find that difficult to believe.

**Comment by Dragoboss** [comment]
Assuming no response in a year either means the issue was fixed or the user does no longer care, please try with newer versions and re-post a report if this is still an issue, we'll have another look.
