### ISSUE TITLE
Click on Steam-Oculus-Icons only gives an error sound

### ISSUE THREAD

**Issue by daJhoony** [LibreVR/Revive#611]
Hi,

i got to write again, because the last service was so great.

ich got the problem with the crashed, which were solved with the directX Updates. But i got my old windows, which i dont get run Oculus Revive. The problem was always, if i click on the icon in my steam menu it only sounds a error sound and nothing is loading. 
Yesterday i installed the update on the old computer too and it runs. But after the new steam upgrade it do not work again.
Any ideas?
Thats what i did:
-Disable Firewalls (Antivir, Windows)
-Start Steam as admin
- Install DirectX Files

It runs for 1 day, now its gone.
Any idea? :)
Thx for all.

**Comment by daJhoony** [comment]
You can close the case. Now its working after one day later new start of the computer.
I love your program. Hopefully its not only working on even day numbers :)
Thanx for all.

**Comment by Dragoboss** [comment]
Ticket has been solved for over a year, closing.
