### ISSUE TITLE
Robo Recall - Tracking issue

### ISSUE THREAD

**Issue by mikegomak** [LibreVR/Revive#613]
There seems to be a tracking issue with Robo Recall which makes the game judder just like The Unspoken. It does not seem quite as prevalent and the game itself is more playable than The Unspoken for me, maybe its better optimised? @Armada651 - The link to The Unspoken issue is here - Has performance issues, see issue #[512 ](https://github.com/LibreVR/Revive/issues/512)

**Comment by Armada651** [comment]
Have you tried RoboRevive? https://github.com/LibreVR/RoboRevive

**Comment by mikegomak** [comment]
I have tried both versions with exactly the same judder as I experience in The Unspoken - I noticed it immediately as it was so similar. Interestingly there are no dropped frames and whilst Im really sensitive to sickness in VR Im not suffering from this a lot in Robo Recall even with the juddering.

**Comment by Armada651** [comment]
Try using the desktop shortcut when launching RoboRevive.

**Comment by mikegomak** [comment]
OK, thats fixed it - Thank you - I was even able to change the settings to HIGH and wtill working brilliantly!!

**Comment by ecklipse** [comment]
I have the same issue with Robo Recall.  So its better to use the Robo Revive instead of the normal revive?
