### ISSUE TITLE
Revive no longer works for me.

### ISSUE THREAD

**Issue by Pipsquexk** [LibreVR/Revive#614]
I am trying to launch oculus games with revive but none of them launch except for Superhot VR. They give me errors like entitlement not found, please download through the Oculus store, or cant launch without Oculus Rift. It is really annoying, I have tried to restart Oculus AND my computer multiple times and it still doesn't work, and I need to prep for The Unspoken tournament which is in 5 days. Please fix it.

**Comment by Armada651** [comment]
Sounds like you haven't updated, make sure you're running the latest version: https://github.com/LibreVR/Revive/releases

**Comment by SkywardEntertainment** [comment]
I uninstalled and reinstalled Revive and it still doesn't work.

**Comment by Armada651** [comment]
Can you try starting Steam as admin before starting SteamVR?

**Comment by SkywardEntertainment** [comment]
Sure

**Comment by SkywardEntertainment** [comment]
It worked

**Comment by SkywardEntertainment** [comment]
Thank you so much

**Comment by Armada651** [comment]
Yeah, seems like some sort of permissions issue with the Creator's Update. I haven't had the update myself yet, so I haven't been able to reproduce the problem yet.

**Comment by Armada651** [comment]
And just as I posted that, Windows Update started notifying me to install the Creator's Update.
