### ISSUE TITLE
Cannot navigate games list after updating. Edit: Self-solved.

### ISSUE THREAD

**Issue by MisterIkkus** [LibreVR/Revive#617]
Hello. I just updated Revive by uninstalling the old version I had and installing the latest version. Now when I go to the Revive dashboard, I cannot move the selection cursor through the list of games. It appears on the top-left game, but will not move. Any help is greatly appreciated.

Edit: Forgot to mention that I cannot launch the initially selected game, either. Neither input is working.

Edit 2: I resolved this by reinstalling the old version of Revive, then installing the new version on top of it.

**Comment by hyperseven** [comment]
any other controllers connected (wheels, HOTAS etc) ?

**Comment by MisterIkkus** [comment]
None.
