### ISSUE TITLE
issues with several titles

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#619]
Hi,

I'm using Revive 1.1.2.2
Latest Advanced Settings (set to default Revive settings -> enable supersampling)
Latest SteamVR Beta
Latest nVidia driver

Currently, these Oculus titles are no longer working for me:
-  Dreamdeck (only flashing solid colors)
-  Showdown (only flashing solid colors)
-  First Contact (everything is black)
-  Dear Angelica (everything is black)
-  G2A Land (UE crash)

All my other titles seem to work perfectly.

Is there anything I can change or do?

Thanks!

**Comment by Armada651** [comment]
You are running the SteamVR Beta again. ;)

**Comment by kvdv99** [comment]
I know...  was hoping it would be okay this time :)

**Comment by kvdv99** [comment]
Okay, rolling back,  I'll let you know which issues are solved...

**Comment by Armada651** [comment]
There's a checkbox in either the performance or developer tab I think, beneath the supersampling slider, uncheck that and it should work around the issue.

**Comment by kvdv99** [comment]
Rolled back to SteamVR anyway.  Everything is working again.
I wonder why the SteamVR beta keeps breaking several applications every time?

The only title still not working is G2A Land, I'm still getting the same UE crash : something with the 'D3D device' ?

Anyway, I'm happy again!   :)

**Comment by Armada651** [comment]
SteamVR beta has a long-standing bug that will be fixed in the next version. But that is also the nature of a beta, it will contain bugs that break things. I always test using the beta so I can report these issue early, but as a user running the beta you should always remember to test it without the beta first, then you can report in your issue whether it is a beta issue or not.

**Comment by kvdv99** [comment]
Allright, agreed, won't be posting issues anymore if I'm running the beta.
Any idea for G2A Land?

**Comment by Armada651** [comment]
You can report issues for the beta, but you need to test first if rolling back to the stable fixes it.

**Comment by Armada651** [comment]
Latest SteamVR beta fixes the flashing colors bug.
