### ISSUE TITLE
Implement Revive dashboard integration.

### ISSUE THREAD

**Issue by LibreVR** [LibreVR/Revive#62]
This will make it much more user-friendly and convenient to use.

![2016-05-01-am_01_26_11-layer](https://cloud.githubusercontent.com/assets/18057864/14939181/25021574-0f2b-11e6-91b5-7f92c5262ccf.png)

**Comment by billyboy12** [comment]
Nice! Can't wait!

**Comment by paulcbetts** [comment]
Another option I was thinking about was to hook the Oculus Home app itself and intercept CreateProcess calls and rewrite them to point them to ReviveInjector, but ofc if you can pull it off, this idea is way better!

**Comment by LibreVR** [comment]
@paulcbetts I thought about that too, but Oculus Home won't even call CreateProcess if it doesn't detect the Rift. I'd have to intercept IPC communication with the OVRServer to work around that, so not worth the trouble.

Anyway, I already got this overlay working, you can view it in my branch: https://github.com/LibreVR/Revive/tree/overlay

I'm currently working on also interfacing with the OpenVR Applications API, which means that Oculus games would also show up in Steam.

**Comment by Neo-One** [comment]
I just wanted to say that you lads are doing a great job. Lot's of respect.  ;-)

**Comment by gormanj** [comment]
Yes, Bravo!!

**Comment by LibreVR** [comment]
Done, though needs a bit more polish before the release.

**Comment by paulcbetts** [comment]
:clap::clap::clap::clap:
