### ISSUE TITLE
RoboRecall no longer launching

### ISSUE THREAD

**Issue by R5R09** [LibreVR/Revive#623]
Was working fine, but all of a sudden no longer launches doesnt even error out, just forever loading on the revive icon for it. It shows up in the task manager under processes but not application.

Superhot however works. I installed the latests version, tried reinstalling revive, ran steam as admin.

**Comment by light4speed** [comment]
Use the RoboRevive, it runs natively and way better. Instead of through revive.

**Comment by CB3D** [comment]
I may have missed something with the RoboRevive install....but it still doesn't run for me.  I have never been able to get Robo Recall to launch on my Vive via Revive or RoboRevive!  @light4speed - any tips/tricks to get it working?!  Thx

**Comment by light4speed** [comment]
I assume you ran the installer from [https://github.com/LibreVR/RoboRevive](url). After doing so the game will only launch correctly if steamVR is running and you click on the desktop shortcut OR alternatively run: [OCULUS INSTALL LOCATION]\Software\epic-games-odin\RoboRecall\Binaries\Win64\RoboRecall-Win64-Shipping.exe

You can tell you're running the correct version if you see ROBOREVIVE activated under the mod section within the game.

**Comment by CB3D** [comment]
@light4speed thx for the response! I don't see the screens as you shared in the docs link! In fact, I have no idea how to get there (it crashes on launch)

**Comment by light4speed** [comment]
Did you by it from the oculus store? And when exactly does it crash?

**Comment by CB3D** [comment]
Yes I did buy it from Oculus Store.  It crashes once the Robo Recall menus come up, I select New Game....crash.  I never get passed selecting a new game.

**Comment by light4speed** [comment]
After installing Roborevive? Try making changes in options before launching the game (Like front facing mode/360 mode on off, lowering graphic settings)

Then I would try reinstalling the game and making sure your revive/oculus/steamvr are all upto date,

**Comment by zeeshanarshad** [comment]
I can confirm that Robo Recall is working fine with Revive. I play it with Revive. (played today too).

**Comment by Dragoboss** [comment]
Seems to be an old issue and seems to be resolved.
Robo Recall currently works fine with Revive.
