### ISSUE TITLE
dirt rally will not open in vr mode

### ISSUE THREAD

**Issue by taksuda** [LibreVR/Revive#625]
hi. i have purchased dirt rally on steam and would like to play in vr. Revive if got it working would be a wonderful solution. unfortunately for me dirt rally just would not open in vr mode only desktop. furthermore other oculas games that show up on steam with Revive works just fine. all i need is dirt rally. if you could help me it would be greatly appreciated.

**Comment by hyperseven** [comment]
manually patch the game from the revive icon.

**Comment by taksuda** [comment]
thank you hyperseven. works like a charm. psvr on trinus psvr on revive on steam vr on oculas games. F!@×. but hay who say it cant be done. well psvr was a good invesment. i can play PlayStation vive and oculas games on one headset.  suck on that digga (digga is my brother he bought a vive hah haaa☺)
