### ISSUE TITLE
Edge of Nowhere crashes on start, turns off Vive display

### ISSUE THREAD

**Issue by SimplexPL** [LibreVR/Revive#626]
Starting the game makes picture on the screen of the HMD to freeze, and then screen turn off (goes black).

Error message:
http://i.imgur.com/9mRWbQp.png
This may be caused by SteamVR beta, but other Oculus games work fine on the beta (e.g. Blazerush)

**Comment by SimplexPL** [comment]
It somehow fixed by itself, but the stuttering problem is still the same if not worse, so sadly the game is still unplayable. https://github.com/LibreVR/Revive/issues/548

**Comment by Armada651** [comment]
Have you tried turning off asynchronous reprojection to solve the stuttering problem?

**Comment by SimplexPL** [comment]
I just did - the stuttering is reduced (or it's a placebo effect), but still noticeable.

**Comment by Armada651** [comment]
Always-on reprojection on the developer page should get rid of the rest of the stutter, but only keep it enabled for seated games.

**Comment by SimplexPL** [comment]
I disabled asynchronous reprojection and enabled always-on reprojection but the stutter is still there. If noone else can reproduce it then maybe it's something on my side.

**Comment by Armada651** [comment]
I think that may be a regression on the side of Revive, there's a rare stutter that I've seen every now and then. I think it's a race condition between the tracking prediction and the frame counter. I'll probably address it in a future version.

**Comment by SimplexPL** [comment]
I am closing this, as the issue was one-off, also apart from the texture flickering the game works well when you disable asynchronous reprojection and enable always on reprojection
