### ISSUE TITLE
Custom Maid 3D 2 VR mode not quite working 

### ISSUE THREAD

**Issue by billyboy12** [LibreVR/Revive#63]
There's a VR patch for Custom Maid 3D released by the developer that adds Rift support to the game. With this game being a recent release and there being a "direct to Rift" launch option, it appears this patch was intended for use with the CV of the Rift, not the dev version so it likely uses a later version of the Rift SDK. This is just my unprofessional assumption based on the fact the dev Rift worked by appearing as a second screen like the Vive does with direct disabled, so I'm assuming that "direct" mode functions the same as the Vive and is only on the CV version.

The game runs on Unity, so you can add Revive plugins into the game to get it to load (after starting Windows in Japan region) and not complain it can't find a HMD. But that's about as far as I can get, the game doesn't appear on the Vive and no head control either. Let me know if you need some files from the game to experiment with!

**Comment by LibreVR** [comment]
Sounds like you're still trying to use the old `OVRPlugin.dll` patch. I recommend against doing that, the new injector method is much more versatile: https://github.com/LibreVR/Revive/blob/master/README.md#oculus-home-games

Anyway if that doesn't work this game is likely made for the 0.8 runtime, which is not supported by Revive.

**Comment by gormanj** [comment]
I have successfully gotten some 0.8 runtime games to work by using the current version of Revive AND replacing the OVRPlugin for Unity from Oculus, Note that the proper 32bit/64bit plugin needs to be used (usually 32bit), "I Expect You to Die" can work with the Vive this way.
