### ISSUE TITLE
dying light

### ISSUE THREAD

**Issue by duig0** [LibreVR/Revive#635]
Hi, Dying light has been updated to use oculus cv1....revive crashes the game though....any chance you can work some magic???

**Comment by duig0** [comment]
https://www.reddit.com/r/oculus/comments/6hz9qk/native_oculus_home_support_discovered_in_dying/

Food for thought

**Comment by KillaNista** [comment]
I'm pretty sure a lot of guys a really interested in this, me too.

**Comment by Armada651** [comment]
Please try the new release: https://github.com/LibreVR/Revive/releases/tag/1.1.7

One open question is that positional tracking is very broken in this game: You'll get a very strange head rotation if you move away from your seated position. I'll confirm this myself when I have a CV1 headset, but if anyone can confirm it beforehand that'd be great.

**Comment by peteostro** [comment]
>  I'll confirm whether this is a Revive bug when I have a CV1 headset, but if anyone can confirm it beforehand that'd be great.

There's a video in the games steam forum that seems to confirm this is a game bug, not revive 
https://steamcommunity.com/app/239140/discussions/0/2119355556492501081/

**Comment by Armada651** [comment]
Ok, well looks like everything is working then. If anyone is still wondering how to set this game up, refer to this post: https://www.reddit.com/r/Vive/comments/6logax/dying_light_on_htc_vive_in_vr_is_freakin_awesome/

**Comment by cholho2** [comment]
I'm using osvr hdk2. Because my height is too high in the game, zombies seem to be dwarfs.

**Comment by peteostro** [comment]
also be careful since the game is not made for VR the artificial locomotion can be a puke fest
