### ISSUE TITLE
Dirt Rally keep running on steam VR after uninstalling revive.

### ISSUE THREAD

**Issue by thefrozncity** [LibreVR/Revive#638]
I am oculus rift / Vive multi user but I just wanted to try DR (steam version) on steamVR mode.
so I patched game and I tried but I found that running oculus SDK is better so I want to role it back.

Kindly let me know how to do this. I cannot understand why there is no unpatch option.
I really don't want to uninstall the game for private reason.
In addition, can other oculus games on steam also be unpatched after revive patching?
kindly answer me too. 
Thanks

**Comment by Armada651** [comment]
You need to delete the `xinput1_3.dll` file next to `drt.exe` to undo the patch.

**Comment by thefrozncity** [comment]
omg, super big thanks to you!!! it works perfectly you are my hero!!
