### ISSUE TITLE
ppsspp vr

### ISSUE THREAD

**Issue by daveaustinsoton** [LibreVR/Revive#64]
Firstly, thanks for the amazing work

I've just tried ppsspp vr using the injector and it doesn't appear to work :(

I tried it not in the oculus folder and also in it 

F:\Oculus\Software\PPSSPP VR

I added the revive folder and the injector.exe into that folder and drag the executable onto it.

PPSSPP crashes via the injector but works fine without it, just not on the vive :(

Windows 10 here.

Thanks again for all the great work

Dave

**Comment by LibreVR** [comment]
As far as I know PPSSPP VR only supports the 0.8 runtime, which is unsupported by Revive.
