### ISSUE TITLE
(The Mages Tale) Turn off only one controller thumbstick

### ISSUE THREAD

**Issue by nightfiree** [LibreVR/Revive#640]
Hey, 

So ive spent about 4 hours in the mages tale.  And it actually ramps up in difficulty and is challanging and requires use of alll your spells.  The main issue is that i have to constantly hit the a and b buttons on the right hand in order to switch spells during combat (im right handed) but im also then constantly spinning in circles because the right thumbstick is bound to rotate.  If i could disable the right thumbstick only (aka turn up the deadspace to max) but keep the left thumbsticks sensativity, for movement, then it would be perfect.  But atm its such a pain in the ass to make work properly.  IDK if you could offer any more customization then you do but either this or the ability to rebind the a key to the menu button so its at least easier to push when i want to.

**Comment by Armada651** [comment]
Can you try if this version works better for you? https://github.com/LibreVR/Revive/releases/tag/1.1.4

**Comment by nightfiree** [comment]
Seems to help a lot.  Just tested it before heading to work.  It def makes it easier to just left click to open my spells now.  It was wierd it was like it was still doing thumbstick movement even at the outer edge of the trackpad. Not anymore.  So now i can just left click to open the menu.  Thank you SO MUCH for the assistance.  So rediculous how quickly you respond to this stuff. Will let you know more when i dive back into the game tonight for a few more hours.

**Comment by Armada651** [comment]
Fixed in 1.1.4.
