### ISSUE TITLE
Controller layout issue - Buttons A/B/X/Y not isolated from emulated joystick

### ISSUE THREAD

**Issue by jaorg1234** [LibreVR/Revive#641]
Hello!

I haven't been using Revive for a while but now am using it for "Mage's Tale" and somehow here I noticed that the buttons are not separate from the joysticks anymore and whenever I want to click on of those, the joystick gets activated as well. I don't remember that to happen when I played "I Expect You To Die" the last time I tried it.

https://i.imgur.com/5dg0siL.png

This is how I remember the mapping to be, but the stick doesn't seem to be confined to those trackpad areas, but instead is defined all over the trackpad.

Is this a new bug or a new "feature"?

**Comment by Armada651** [comment]
It may be a bug in the feature. What changed is that the joystick will now activate when you swipe your finger over any part of the trackpad. But it should not activate when you simply press a button.

Though I could see how this creates a problem if you regularly swipe your finger across the trackpad to reach the different buttons.

**Comment by jaorg1234** [comment]
I intentionally tried to only click as I assumed a swipe would cause the joystick to activate, but it still caused the virtual joystick to get activated.

**Comment by Armada651** [comment]
Did you change any of the Revive Thumbstick settings using OpenVR-AdvancedSettings?

**Comment by jaorg1234** [comment]
No, I left all settings at the default values.

**Comment by Armada651** [comment]
Try this version, I've reverted the change for now: https://github.com/LibreVR/Revive/releases/tag/1.1.4

**Comment by jaorg1234** [comment]
Yes, it's perfect now, thank you! I'll close this ticket.
