### ISSUE TITLE
Stutter when looking forward (180 degrees), while turning around fixes this entirely. (unsure if issue with base station or vive itself)

### ISSUE THREAD

**Issue by VenomFrog** [LibreVR/Revive#643]
Doesnt matter the game, or the content being displayed, but most ReVive games have an awful stuttering in the front "half" while "turning around" fixes it entirely and is smooth as butter. Not sure if its an issue with base station placement or ReVive itself, because I can be "facing forward" looking at a wall and getting stutter, while "turning around" towards the game is smooth. 

Ive noticed it doesn't matter what direction I face when starting the game, whatever direction the game starts in is the front, and turning around makes it smooth.

Im a new Vive owner (Started using ReVive within days of getting my Vive) so im unsure if this is an issue with my Base Station's or what. This DOES NOT happen in Steam games.

**Comment by CarrotSurvivor** [comment]
You should try to disable Async reprojection and enable "always on reprojection" in steam vr or advanced settings. 

This will almost certainly solve your problem :)

**Comment by VenomFrog** [comment]
@CarrotSurvivor This worked, but now it seems a tad "floaty". I have my floor bounds to always be showing, and moving my head around makes the floor bounds somewhat float around relative to my head location if that makes sense? 
Did infact remove my stutter, thank you for that!
