### ISSUE TITLE
Werewolves Within - Controller

### ISSUE THREAD

**Issue by stal2k** [LibreVR/Revive#650]
This is probably more of an issue for the game, but realistically a workaround is more likely to come here. Basically, The game restarts itself in such a way that it can't be 'caught' by revive from launching through dashboard, in order to make it work it needs to be right-click-->Patched. 

The problem is, in order to get past the opening you **HAVE** to recenter the view using the Xbox select button. The patch method either breaks or does not seem to allow that particular input. I tried both xbox controller and vive wands.

**Comment by Armada651** [comment]
Can you try installing this and see if it fixes the patch method? https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by stal2k** [comment]
Sure thing, doing it now.

**Comment by stal2k** [comment]
Unfortunately it did not.

**Comment by stal2k** [comment]
Closing this to help declutter board.
