### ISSUE TITLE
Echo Arena Beta crashes on launch

### ISSUE THREAD

**Issue by BoneHawk1** [LibreVR/Revive#651]
Hello all! I am attempting to play the Echo Arena Beta before it expires at 8:00 pm TODAY, however I cannot due to an error from Oculus (or so it seems) stating " Failed to initialize Oculus API (fffff431)". Does anyone know how to fix this? It would be a great help. 

`[ERROR] Oculus:
[ERROR]
Encountered an error:
[ERROR]  -
  - : Failed to initialize Oculus API (fffff431) -

            1) Is the service running?
            2) Do you have the proper runtime installed?
            3) Is your headset powered on and running?
            4) Can you run the demo scene in the configuration utility?
            5) Are your display drivers up to date?

  - :
  - : d:/projects/rad14/dev/src/engine/libs/vr/cvr_win.cpp
  - : 646
  - : -1671870939449924098`

**Comment by jaorg1234** [comment]
Have you checked if any other VR games/experiences like First Contact run via Revive?

**Comment by BoneHawk1** [comment]
I tested Revive on Oculus DreamDeck and it worked the same as usual.

**Comment by jaorg1234** [comment]
Do you have the latest Revive version installed?

**Comment by BoneHawk1** [comment]
I believe so. I just received and installed a new version about 3 days ago.

**Comment by jaorg1234** [comment]
A new version just released yesterday to fix Lone Echo specifically. Go to the releases tab and download the latest version.

**Comment by BoneHawk1** [comment]
Ok I'll try it out. Thank a lot!
