### ISSUE TITLE
How do you use Revive with SteamVR Beta?

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#653]
I don't see any way to pull up the old dashboard.  How do you use Revive with the SteamVR beta?  Are you panning to support it?

**Comment by jaorg1234** [comment]
With SteamVR home? I can pull up the dashboard fine. Is the Revive icon missing for you?

**Comment by lghtanddrk** [comment]
In SteamVR beta the entire home screen is different.  There is no dashboard where you click a button to pull up anymore.  The only popup menu is now for the social media, avatar and environment settings.The Revive and OpenVR icons are not there.  And they are not on the wall panels in SteamVR home.  In fact, all my Oculus games don't even show an image on the wall.  

If you are able to see the icons in the new SteamVR beta where are they and how do I access them.

**Comment by jaorg1234** [comment]
I'm in the beta and I can pull up the dashboard as usual. If only the settings cogwheel appears when using the lower menu button, then try to quit Steam and restart it as administrator.

The menu for the avatar gets pulled up with the upper menu button, not the lower one (or at least for me it works that way).

**Comment by Armada651** [comment]
Can't reproduce, I am on the beta and the dashboard works as normal.
