### ISSUE TITLE
Question about interleaved and asynchronous reprojection when using Revive

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#654]
I have an i7-6900, 64 GB of RAM and an GTX1080ti.  Should I have interleaved or asynchronous reprojection or both enabled when using Revive for the best results?  What about when not using Revive?  Your thoughts?

Lastly, I just had to do a reinstall of SteamVR because SteamVR was not appearing after unchecking SteamVR beta.  Just reinstalled without uninstalling and rebooted.  Revive and OpenVR Advanced Settings apps should be okay and not need top be reinstalled, correct?

**Comment by SimplexPL** [comment]
It all depends on each game but general rule of thumb is to disable Asynchronous Reprojection and enable Always On Reprojection.

**Comment by Armada651** [comment]
@SimplexPL That is not a general rule, refer to issue #577 for a detailed explanation.
