### ISSUE TITLE
Changing Control Scheme

### ISSUE THREAD

**Issue by Rogway** [LibreVR/Revive#655]
Hello. I recently started playing Robo Recall and having a blast.
However, I was wondering how easy it is to change the control scheme for the Vive controllers in Revive.
I hate the grip buttons to hold weapons and grab robots (even with hybrid grip).

I was wondering if there was anyway to change teleport to the grip buttons and pressing anywhere on the touch pad would activate grabbing, so basically swapping the controls.
I feel like that control scheme would work a lot better for me and be a lot easier to hold weapons and throw.

**Comment by SimplexPL** [comment]
Maybe this will help https://github.com/matzman666/OpenVR-InputEmulator

**Comment by Armada651** [comment]
Making controls customizable is a lot of boring work, I'll probably will not be doing that. Personally I'm just waiting for better controllers.
