### ISSUE TITLE
Eagle Flight

### ISSUE THREAD

**Issue by BareGeek** [LibreVR/Revive#656]
I am having issues with Eagle Flight in steam when Revive is installed.  When I launch the game, it either crashes at 80 % on the load screen or it goes past the load screen and I get the sound but never any video on either the Vive or my monitor, only a black screen.  When I close the game, it also opened the Oculus app behind the Eagle Flight window.  It is almost like the game is detecting Oculus and trying to run through that vs. on the Vive.  If I uninstall Revive, and relaunch the game, it runs correctly.

**Comment by Armada651** [comment]
The only way that could happen is if you have Eagle Flight installed through both Steam and Oculus Home.

**Comment by BareGeek** [comment]
It is not and never has been installed or purchased from Oculus.  However, I am guessing both install methods probably launch throrugh Uplay.  I am wondering if Uplay is detecting something through Revive and trying to run the game for Oculus.  I have a ticket open with Ubisoft as well.

**Comment by thibaultmol** [comment]
I have Revive too and experience issues sometimes (probably a coincidence). I launch the game trough uplay instead of trough steam everytime I want to play it. That seems to work fine.

**Comment by Armada651** [comment]
I would assume this happens when the Oculus Software is installed. I have no idea how only uninstalling Revive would fix it. The only thing that Revive does in the background is scan for Oculus Games and it does that by reading files directly, it doesn't communicate with any Oculus software and doesn't try to open the Oculus client either.

**Comment by BareGeek** [comment]
Correct, upon further testing, the correlation appears to be with the Oculus software and not revive itself.  I am still troubleshooting with Ubisoft.  You may close as a bug with Revive.

**Comment by randomuser00** [comment]
baregeek it's because the game is trying to load occulus instead of vive, delete OVrplugin.dll in the game /plugins folder

**Comment by BareGeek** [comment]
You are a hero!  I just gave up on this game last week.  I have been spending months with Ubisoft trying to get their support to understand that it is loading the wrong VR software.  This worked perfectly first shot!
