### ISSUE TITLE
Edge of Nowhere with Revive problem!

### ISSUE THREAD

**Issue by AbrahamZX** [LibreVR/Revive#657]
It displays the message "The tracker cord is disconnected" and proceeds to recenter my position if I keep looking to any side for a few seconds all the time.

**Comment by Armada651** [comment]
Are you using an HTC Vive?

**Comment by AbrahamZX** [comment]
I'm emulating the Vive using TrinusPSVR. I'm really using the PS VR.

**Comment by Armada651** [comment]
There's your problem, many third-party drivers don't properly report the activity level so if you keep your head still TrinusPSVR reports that you took the headset off.

**Comment by Armada651** [comment]
You can try this debug option to work around it for now: https://github.com/LibreVR/Revive/issues/616#issuecomment-302238620

**Comment by AbrahamZX** [comment]
That definitely fixed the re-centering, the "The tracker cord is disconnected" message doesn't leave the screen though, but I can play it just fine now. Many thanks, I am aware that I'm not using the intended HMD for this software, but I just wanted to see if any existing solution (such as the one given) existed. I did not intend you to come up with any new fixes.

**Comment by Armada651** [comment]
> Many thanks, I am aware that I'm not using the intended HMD

Then why did I have to guess for it?

**Comment by AbrahamZX** [comment]
Firstly I wanted to see if it was a problem that happened with the Vive as well. When you asked if I was using the Vive, I knew that it wasn't. Also, after I started the thread I checked a compatibility list of the revive and saw the known issues for the game too. I hadn't seen that before.

**Comment by Armada651** [comment]
I can't read your mind over the internet (yet), so you should've said: "I'm using a TrinusPSVR, does this happen on the Vive too?".

**Comment by AbrahamZX** [comment]
Yeah, I should have. I'll keep that in mind for future problems and threading. 
Just for the sake of sharing it, that's the message I get. Thanks again.
![19531987_1540043962714312_1558984247_o](https://user-images.githubusercontent.com/29734044/27597632-ea7a8636-5b30-11e7-954f-fc7a8a50769d.jpg)

**Comment by Armada651** [comment]
That's probably just the PS Move camera losing sight of the lights on the headset when you look to the side.

**Comment by AbrahamZX** [comment]
Hell yeah! I managed to fix it, I can now run it like it does on the Vive. Your last comment got me thinking and all I had to do was make Steam VR detect my "tracking camera". So I used PSMoveSteamVRBridge to make Steam detect the camera and kept the "IgnoreActivityLevel" : true. That eliminates the message and the re-centering. The thing is that I'm not really using camera tracking on the PSVR HMD, currently that doesn't work well with TrinusPSVR and even if I activate it, Steam doesn't detect my tracking camera, but PSMoveSteamVRBridge is detected by Steam.

**Comment by unkellsam** [comment]
Looks like the game is broken after the most recent update. Any solutions?

**Comment by cr4zyw3ld3r** [comment]
@AbrahamZX 
How did you get Steam to detect your camera? I can get a video feed from my PSEye but cannot get it to show up as a tracker in steam

**Comment by AbrahamZX** [comment]
@cr4zyw3ld3r
You have to run the PSMoveService while you're going to play the game. That's what makes Steam see the camera.
https://github.com/cboulay/PSMoveService/releases
That's the link to the software. Hope you can get it running. I haven't done it in months.

**Comment by cr4zyw3ld3r** [comment]
Looks like the issue is twofold. One I had outdated VC redists and two Need to use PSmovebridge ver 8.10  Will report back if I have it running.

Also interestingly enough I could not run the batch files until I manually CD'd into the directory they are in from CMD. Some kind of access error.
