### ISSUE TITLE
Crashing - Injecting to vive - let's play with nanai

### ISSUE THREAD

**Issue by StatelessRel** [LibreVR/Revive#658]
they left two revive .exe's (both 64 and 32) in their installation zip yet neither one works. the cmd pops up for a split second and goes away never initializing anything so i installed revive myself and all of the software for the vive. go to inject the games direct .exe and it loads the splash screen saying "made with unity" and it loads the character for a split second and crashes.. I have an output log, however this is the first time ive used this site so im not sure how you want me to give it to you, thanks for reading and the help!

**Comment by Armada651** [comment]
Why would you use Revive on an application that supports the HTC Vive?
