### ISSUE TITLE
Henry stuttering in some areas only

### ISSUE THREAD

**Issue by ibilab** [LibreVR/Revive#66]
Anyone having this issue? Beginning of the scene is ok but then when henry comes in on some areas stuttering is present. Tried it before with DK2 and it was smooth so no performance issue. Looks like it happens on complex lighting zones. Could it be going outside a different post process volume made for seated experience while walking with Vive or something?

**Comment by RJBaer** [comment]
same problem here aswell

**Comment by gormanj** [comment]
No problem here on 0.4.0 (with a gtx-980ti). Watched the whole thing, even walked around.

**Comment by MasterElwood** [comment]
Runs perfectly smooth on my GTX970 and 0.4.0

**Comment by ibilab** [comment]
@MasterElwood @gormanj @RJBaer  What Nvidia drivers are you using?

**Comment by RJBaer** [comment]
both

**Comment by MasterElwood** [comment]
@ibilab 362.00 on W10

**Comment by Armada651** [comment]
I can't reproduce the problem and no one else seems to run into it. Feel free to leave a comment here if you want to reopen the issue.
