### ISSUE TITLE
farlands snapshot issue

### ISSUE THREAD

**Issue by shse123** [LibreVR/Revive#660]
I have the same issue as in https://github.com/LibreVR/Revive/issues/5

I tried every button on my Xbox 360 controller and the keyboard arrow keys multiple times, and also injecting the file from ww/binaries but none of that worked.

(I'm using vridge with my mobile so I have to position tracking)

**Comment by Armada651** [comment]
Farlands needs the Oculus Remote which is only supported with tracked controllers. Revive is geared towards the HTC Vive, but you may be able to use this project to create a virtual controller that works for you: https://github.com/matzman666/OpenVR-InputEmulator
