### ISSUE TITLE
All Oculus games eventually become unplayable

### ISSUE THREAD

**Issue by Buttgoblin** [LibreVR/Revive#662]
Had a miserable time trying to get Wilson's Heart to play nicely but it just resulted in horrendous effect, like HMD and controller tracking all delayed by about 500~ms. It can take 2-3 minutes for the effect to kick in, not sure if bringing up the SteamVR dashboard can affect it.

Downgraded to 1.1.4 and no longer having this issue with all reprojection settings off in advanced settings, but can reproduce the exact same effects of later releases if I turn on Async Reprojection, bringing up SteamVR dashboard doesn't stop the game working properly.

**Comment by Buttgoblin** [comment]
Never mind, using 1.1.4 I can play for a much longer time with forced reprojection on, but eventually it just goes all out of wack like the newer versions.

Just to note, I'm using SteamVR beta, but that shouldn't have much if any bearing on it right?

Specs:
i7 7820x 4.6GHz
32GB 3733MHz DDR4
GTX 1080ti
Games installed to a Samsung 960 evo

**Comment by Armada651** [comment]
Can you try it without the beta?

**Comment by Buttgoblin** [comment]
Same results, 1.1.4 actually induced the problem the exact same time the latest version did for me this time.

**Comment by Armada651** [comment]
This issue will be part of a research into several performance and timing related issues in Revive, so it'll take a bit of time to fix.

**Comment by Buttgoblin** [comment]
No prob, cheers!

**Comment by Buttgoblin** [comment]
Update on this, I tried "Ripcoil" which actually started exhibiting the same behaviour as Wilson's Heart, so I have a feeling it is all revive games for me. Not a single clue as to what the issue could be though as every other native Vive game I have works flawlessly, anything I should provide to investigate this or?

**Comment by jaorg1234** [comment]
I have tried Ripcoil, the Oculus Touch tutorial, and First Contact and could not replicate your issues. This has been tested with both 1.1.6 and 1.1.4, on the latest SteamVR beta.

I think in Revive titles you should generally keep asynchronous reprojection on, and in some games having always-on reprojection helps with some jutter.

A few things to clarify: does this issue only crop up if you open the SteamVR dashboard? I opened it up several times and did not notice any new issues cropping up.

**Comment by Buttgoblin** [comment]
The issue seems to happen regardless of opening the dashboard or not, and no combination of the reprojection settings seems to help unless the game is actually jittery to start with, but eventually they all become super drunk-o-vision. I can get a video of it if you'd like?

**Comment by Buttgoblin** [comment]
https://www.youtube.com/watch?v=38TevPhwXeY well I still can't fix it, so here's a video demonstrating the issue. Any ideas? I'm flat out.

**Comment by Armada651** [comment]
I think I have an idea what is causing it, probably two frame counters used for tracking prediction get desynced. I'll look into addressing this in version 1.2.

**Comment by Buttgoblin** [comment]
Oh that's great, if you need any testing doing please just let me know. Thanks!

**Comment by Armada651** [comment]
Can you try a different driver version?

https://www.reddit.com/r/Vive/comments/6q604u/bestmost_stable_nvidia_drivers_for_vr/

**Comment by Armada651** [comment]
Please test this beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0

**Comment by Buttgoblin** [comment]
Sorry for the late reply, not had much time to VR lately. However, 1.2.0 seems to have solved all issues, been playing Wilson's Heart like a native Vive game for the last 2 hours, no issues. Thanks for all your hard work.
