### ISSUE TITLE
Dirt Rally - Never Loads in Headset

### ISSUE THREAD

**Issue by LittleFirework** [LibreVR/Revive#663]
Not sure why. Patched as per instructions. It loads on the PC, and my monitor, but I just get the empty room with the loading animation within Steam VR when looking at the headset. 

Any ideas what to do? This is the first time I've installed so no previous versions

**Comment by Armada651** [comment]
Can you try installing the DX end-user runtime? https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by SimplexPL** [comment]
I had similar issue just yesterday with another game. Try the trick that worked for me with The Wizards beta and Dying Light - close SteamVR and then run the game. There's a chance that the game will initialize SteamVR and it will work.

**Comment by LittleFirework** [comment]
Installed, now getting Error 308 in Steam VR (key component is missing)

**Comment by Armada651** [comment]
Try restarting Steam as admin.

**Comment by LittleFirework** [comment]
All done, thanks for your help!
