### ISSUE TITLE
Cannot get the 'Patch' or 'Inject' Window dialog to open.

### ISSUE THREAD

**Issue by TaL81** [LibreVR/Revive#664]
Hi there, as per title, I can get Revive appearing in HTC Vive, but when I want to patch a steam game 'Dirt Rally', and I right click the icon, no window dialog box appears. Nothing happens. Ive got the latest revive and Steam versions installed.

Any idea?

Thank you.

**Comment by Armada651** [comment]
You need to right-click the icon in the system tray on your desktop monitor.

**Comment by TaL81** [comment]
Thanks. I do this and I do bring up the patch and inject selections, but when I click on it, nothing happens..

**Comment by TaL81** [comment]
No dialog window appears to bring in the game I want to patch.

**Comment by Armada651** [comment]
You can patch it manually, go to `C:\Program Files\Revive\Revive\x86` and copy both DLLs to the Dirt Rally directory. Now in the Dirt Rally directory rename `LibRevive32_1.dll` to `xinput1_3.dll`.

**Comment by TaL81** [comment]
Thanks. Ive successfully patched it, but now no matter what I do, I can't launch Dirt Rally in VR.
Nothing happens in VR, and always just loads up and plays in desktop (theatre mode). I have already disabled the setting in properties within Steam for the game.

Any ideas?

**Comment by TaL81** [comment]
I have resolved the issue with installing Direct runtime. Thank you for your help.
