### ISSUE TITLE
Struggling to make Echo Arena Launch

### ISSUE THREAD

**Issue by AForrestfire** [LibreVR/Revive#665]
Hi I am desperately trying to get Echo arena to launch as today is the only day I'll get to play of the 2nd Open Beta.

I have never used revive before so am pretty new to how it works but I have done a fair bit of research online.

I've installed everything as required but when i load up the vive I have the icon in the VR Dashboard. when I select it nothing really appears. (See attached photo) 
![revive example](https://user-images.githubusercontent.com/29950856/27913627-a84db614-6258-11e7-8c8b-1cdcd756b9f5.jpg)

Isn't there supposed to be a list of games available on that tab? I have already installed Echo Arena and I think there's a few others that come free with oculus home. When I loaded up daydream through steam it worked fine. but when I try and do the same for Echo arena literally nothing happens, i get a quick flash white of the screen and then we go back to "play in VR" button through steam.

Apologies if this is a basic fix that I'm overlooking but I've never used this software before and am struggling to come up with any other solutions after 6 hours already.

**Comment by Armada651** [comment]
Can you post the logs from `%APPDATA%\Revive`? Just enter that into the run dialog (Win Key + R) and drag and drop the two text files into the comments box here.

**Comment by AForrestfire** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/1128070/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/1128069/ReviveOverlay.txt)

Thanks for your time

**Comment by Armada651** [comment]
That strange, it looks like you are missing some libraries. Can you try and re-download the Revive installer and re-install Revive?

**Comment by AForrestfire** [comment]
ack, I've already done that several times this morning, and the same with the Oculus Home app. Is there a way of downloading previous builds of revive? everytime i download the installer it is the latest version of revive that gets installed

**Comment by Armada651** [comment]
Strange, these are the libraries you're missing, try extracting them in the install directory: 
[OpenSSL-Win64.zip](https://github.com/LibreVR/Revive/files/1128100/OpenSSL-Win64.zip)

**Comment by AForrestfire** [comment]
so after a fresh install, (still not working in game) I tried extracting those libraries but it said that they are already in the install folder, weirdly some of them are very slightly different in size should i maybe try overwriting the old ones with these ones you gave?

**Comment by AForrestfire** [comment]
no that doesnt fix it either ;/

**Comment by Armada651** [comment]
Well, for now you can just go to the bottom-right system tray on your monitor and right-click the Revive icon. Select Inject... and browse manually to `C:\Program Files\Oculus\Software\Software\ready-at-dawn-r14-multiplayer\bin\win7\EchoArena.exe`.

**Comment by AForrestfire** [comment]
really bizarre as i haven't read of anyone else coming across this exact issue. I completely reformatted my comp last week so i cant see it being something corrupted in my system

**Comment by Armada651** [comment]
Damn, looks like Echo Arena needs some extra parameters from the Revive Dashboard.

You might be missing some Visual C++ libraries when you just reinstalled, let me check.

**Comment by Armada651** [comment]
Found it, you're missing this one: https://www.microsoft.com/en-us/download/details.aspx?id=40784

Install `vcredist_x64.exe`, I'll update the libraries with ones that depend on the same Visual C++ libraries as Revive installs.

**Comment by Armada651** [comment]
I've updated the installer to no longer depend on Visual C++ 2013. Revive now only needs Visual C++ 2015, which is shipped with the installer.

**Comment by AForrestfire** [comment]
as much as I would love to say this fixed it as i appreciate all your efforts, this hasn't changed anything.

**Comment by AForrestfire** [comment]
anybody else struggling with Echo Arena? as I said I can open up other Oculus games but Echo Arena has not worked once for me yet

**Comment by Armada651** [comment]
Ok, well just as a quickfix if you have everything installed in the default paths entering this in the Run Dialog should work: `"C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" "C:\Program Files\Oculus\Software\Software\ready-at-dawn-r14-multiplayer\bin\win7\EchoArena.exe" -nosymbollookup -fullscreen -mpmnu`

**Comment by Armada651** [comment]
Also, the installer was updated to fix the dashboard, not the Inject... menu. You *have* to start Echo Arena from the Revive Dashboard (or use the quick-fix above).

**Comment by AForrestfire** [comment]
nah, again it begins loading the game for all of a second then shuts down and leaves me hanging with no warning box or anything.
Thanks again for all of your help but I think I'm going to call it. It's a beautiful day outside and i've spent it all inside trying to resist punching a screen. Best of luck with this program man your reputation is well deserved, never had anyone get back to me about troubleshooting this quickly.

**Comment by Armada651** [comment]
All you probably need to do is restart Steam and SteamVR (or just reboot your PC).

**Comment by AForrestfire** [comment]
Have tried time and time again. Somewhere something along the line isn't sitting right.
