### ISSUE TITLE
SuperhotVR launches, but no longer outputs to Vive

### ISSUE THREAD

**Issue by CaptainWow110** [LibreVR/Revive#666]
It launches and plays just fine, but only on my desktop. It refuses to output to my headset, no matter what I try. I've rebooted the pc, reinstalled ReVive and SuperhotVR, I've tried injecting superhotvr.exe, and I futzed around with SteamVR's settings to no avail. I've tried running everything as an administrator, too. Nada.

The other Oculus games I have launch into the headset normally, so I'm inclined to believe it's a problem with Superhot, though the recent Revive update may have done something? The only other thing I can think of is that I just bought vanilla Superhot during the steam sale... I dunno. Any ideas? Is there any other info I can give to be helpful?

**Comment by jaorg1234** [comment]
I can't help with this specific issue, but if you're not aware, if you got the Oculus Home version, you're eligible for a free Superhot VR key on Steam.

For more information, check out this steam forum post:

http://steamcommunity.com/app/617830/discussions/0/1290690926863800921/?ctp=2#c1290691308576764275

**Comment by SimplexPL** [comment]
This helped me in Dying Light - Try closing steamvr first and then launching SuperhotVR.

**Comment by CaptainWow110** [comment]
Wow, I had no idea they were doing this! Thanks for the quick and helpful
response!

**Comment by dartg57** [comment]
Same problem with Disney Movies VR  :/

**Comment by jaorg1234** [comment]
Disney Movies VR is also available on Steam:

http://store.steampowered.com/app/469650/Disney_Movies_VR/

Why don't you use this version instead? Should make less problems.

**Comment by dartg57** [comment]
I am a complicated man ... lol

**Comment by dartg57** [comment]
Thank you, I will test this one

**Comment by dartg57** [comment]
It is not the same, it misses, Beauty and the beast experience

**Comment by jaorg1234** [comment]
Try the latest Revive release, 1.1.8. Maybe that one helps.

**Comment by dartg57** [comment]
Everything works now with this latest update !
Thanks

**Comment by CaptainWow110** [comment]
Uh hey, it's still not working for me, can we open this back up? Installing the new update didn't fix it for me. :(
