### ISSUE TITLE
Superhot VR thru ReVive still not outputting to headset

### ISSUE THREAD

**Issue by CaptainWow110** [LibreVR/Revive#668]
It launches and plays just fine, but only on my desktop. It refuses to output to my headset, no matter what I try. I've rebooted the pc, reinstalled ReVive and SuperhotVR, I've tried injecting superhotvr.exe, and I futzed around with SteamVR's settings to no avail. I've tried running everything as an administrator, too. Nada.

The other Oculus games I have launch into the headset normally, so I'm inclined to believe it's a problem with Superhot, though the recent Revive update may have done something? The only other thing I can think of is that I just bought vanilla Superhot during the steam sale... I dunno. Any ideas? Is there any other info I can give to be helpful?

**Comment by Armada651** [comment]
Are you sure you're using version 1.1.8? If you are certain you're using that version, then try version 1.1.6 instead.

You can find all the different versions on the releases page: https://github.com/LibreVR/Revive/releases

**Comment by CaptainWow110** [comment]
I'll give that a shot, thank you.

**Comment by CaptainWow110** [comment]
rebooted, re-patched, it's working now. Thank you very much for your help!
