### ISSUE TITLE
War thunder Work in Progress adds 1.3 support, breaks Revive.

### ISSUE THREAD

**Issue by Ossius** [LibreVR/Revive#67]
Getting Oculus not detected issue,  Oculus Home is installed and I've been running the game perfectly until I tried this update.  Its important that it works because WIP will go live soon, and will fix all the issues we have with War thunder like reticle rendering and lack of any HUD.

**Comment by a7610783** [comment]
So, War Thunder has been able to successfully use the Oculus CV1 run it?
I have always confused me with VIVE compatible picture is DK2 or CV1
HUD did not lead to any defense I must have been 6 o'clock to BOGEY
And often results in TK

**Comment by Ossius** [comment]
Gaijin has been working on implementing War thunder to work on Oculus 1.3 so the CV1 can work on it.  The Work in Progress client updated to now include that support.  People are reporting running their DK2s and I think CV1s on Reddit.com/r/warthunder, but using Revive Injector 4.0 is not working, it just states "Oculus not detected" then launches into normal mode.

**Comment by a7610783** [comment]
So now even the resurrection of the syringe is 4.1
But he is not a supported version of SDK1.3 but an older version?
I did not know how to download the update SDK1.3 .... back updates do not know in which folder to update to SDK1.3 and normal operation

**Comment by LibreVR** [comment]
Tested it works just fine, but you should only inject on `C:\WarThunder\win64\aces.exe` and refuse to use the launcher.
