### ISSUE TITLE
Echo Arena Beta Black Screen

### ISSUE THREAD

**Issue by Hydroxious** [LibreVR/Revive#670]
Read about that issue somewhere else before, but now I experience it as well each time
a game is about to start. Bummed out :(

**Comment by jaorg1234** [comment]
The black screen is not a Revive specific bug and plagues everyone right now, both Rift and Vive owners. They are going to push out an update to hopefully fix it.

**Comment by Hydroxious** [comment]
Yeah just read that now o Reddit :) Thanks for replying though and sorry for posting here.
