### ISSUE TITLE
Dying light with osvr hdk2

### ISSUE THREAD

**Issue by cholho2** [LibreVR/Revive#673]
I'm using osvr hdk2. Because my height is too high in the game, zombies seem to be dwarfs.

**Comment by jaorg1234** [comment]
Don't own this game, but does "Reset seated position" not fix this issue? If not, maybe in the meanwhile you could use [OpenVR Advanced-Settings](https://github.com/matzman666/OpenVR-AdvancedSettings) to change the height to a more reasonable level.

**Comment by cholho2** [comment]
@jaorg1234 I tried, but the problem was not solved. If I used advancesetting, the problem was not solved but rather the screen was shaky

**Comment by Dragoboss** [comment]
OSVR HDK2 is not support by default.

Its over a year later but if you still need I can look into this a bit deeper but I'll need more details.
Please post a new ticket with the new format and as many details as you can.
