### ISSUE TITLE
Oculus Touch emulation without using OpenVR. "LoadLibrary failed to return module handle"

### ISSUE THREAD

**Issue by fishirenee** [LibreVR/Revive#676]
Hi,

I need a tool that can emulate Oculus Touch without presenting the real devices. (Only emulate Touch. I will use all other Oculus devices instead of Vive.) Based on Revive I cleaned out all OpenVR related parts. I kept injector and rewrote REV_CAPI functions. And I added other feeding functions for Touch. But when I tried to inject LibRevive64_1.dll to TouchNUX-Win64-Shipping.exe under Oculus Touch tutorial, I got "LoadLibrary failed to return module handle" error. So basically the new dll I generated can't be injected correctly.

I'm wondering whether my original plan can be realize under Revive structure or not? I didn't change any of injector's code except for removing openvr_api.dll injection. I have no idea why injection itself would failed.

Any help is appreciated!

**Comment by fishirenee** [comment]
Now the LibRevive64_1.dll can hook into TouchNUX-Win64-Shipping.exe as well. However, since I'm still using Oculus HMD. I deleted all the functions that I don't need to rewrite such as "ovr_Initialize()" and hope that the original ovr_Initialize() function will be loaded. And I got error "Cannot run this application without an Oculus Rift." which may means that the initialization of Oculus failed?

So my question is can I just rewrite a subset of OVR_CAPI.h interfaces and hope the Oculus will load the other functions that I didn't touch as it is?

Thanks.

**Comment by Armada651** [comment]
No, that's not how DLLs work. You will need to provide your own proxy function for **every** function you don't need to intercept.

**Comment by fishirenee** [comment]
Hi Armada,

Thanks very much for the explanation! I implemented a solution: [https://github.com/fishirenee/Revive](url) to hook specific functions but not the whole library. So the Oculus runtime DLL will still be loaded. I'm still testing input functions. The position and orientation can be emulated now.
