### ISSUE TITLE
Medium fails to start with "Unable to initialize the Oculus Rift" error.

### ISSUE THREAD

**Issue by JennyY8S** [LibreVR/Revive#677]
I've purchased Medium, installed it, but have had no luck in getting it to run. It fails every time with an "Unable to initialize the Oculus Rift" error.

System:
Xeon X5660, 12GB RAM, GTX 1080 Ti, HTC Vive

Software:
Windows 10 Home Premium
Steam 
Revive 1.0.5

Everything in installed in the default locations.

To replicate:
1. Start Steam
2. Start Steam VR
3. Verify revive is working by using revive dashboard and opening dream deck or first contact.
4. Attempt to start medium from revive dashboard
5. Note that medium does not start
6. Look at Windows desktop
7. See small popup with "Unable to initialize the Oculus Rift" error.

Is this an issue at my end, has medium support broken or have I encountered a bug?

Thanks

**Comment by Armada651** [comment]
There should be an error code in the popup window, what is the error code?

**Comment by JennyY8S** [comment]
Popup window is small, has a title bar of "Error" the text "Unable to initialize the Oculus Rift" and an "OK" button.

Sorry, no error code.

![capture](https://user-images.githubusercontent.com/5442729/28191173-b3005278-6826-11e7-9809-59d030ad1765.PNG)

**Comment by Armada651** [comment]
And you did follow these instructions?

https://github.com/LibreVR/Revive/wiki/Troubleshooting#im-getting-an-entitlement-error-or-oculus-rift-not-found

**Comment by JennyY8S** [comment]
Yes, as far as possible. The 'Standalone games' link doesn't link to anything relevant.

Attempts to get it working:
- Reboots
- Uninstall/Reinstall revive
- Run steam as admin
- Use settings/beta/Restart Oculus option in oculus desktop app.

**Comment by Armada651** [comment]
I can reproduce the error. It's likely that Oculus has updated Oculus Medium to use Oculus SDK 1.16, while Revive currently only implements version 1.14.

You'll have to wait until Revive is updated to the latest SDK.

**Comment by JennyY8S** [comment]
Okay, thanks for that. Is there an ETA for when 1.16 support could be available?

**Comment by Armada651** [comment]
No ETA yet, 1.16 implements things like Vulkan support so preferably I'd want to wait until I complete a Vulkan implementation in Revive.

However, since Medium isn't using Vulkan I could potentially just implement some stubs to get a release out faster. But I'd rather implement 1.16 properly with full support.

**Comment by JennyY8S** [comment]
Okay thanks. That's a shame.

**Comment by aurialLoop** [comment]
I just wanted to chime in and say I've encountered the same error. Medium is one of my favourite programs, so it is a shame I can't use it while SDK 1.16 is implemented. Thank you for working on it!

**Comment by whoiskjl** [comment]
I just have pledged as a Laser Safety Officer (https://www.patreon.com/whoiskjl) so I can voice my opinion better. I believe many VIVE users including myself rely greatly on Medium to create 3D assets; it would be great for all of us if the future development can favour more on focusing on ensuring the compatibility of Oculus Medium along with other applications

**Comment by Armada651** [comment]
I can upload a stub patch here as a quick fix today, but like I said I really want to fully support 1.16 before I release it publicly.

**Comment by JennyY8S** [comment]
Thanks. That would be awesome!

**Comment by Armada651** [comment]
Extract the contents of this zip file into the Revive installation folder replacing the existing files and it should work again: 
[Revive.zip](https://github.com/LibreVR/Revive/files/1149584/Revive.zip)

**Comment by whoiskjl** [comment]
Tested and my issue has been resolved.

**Comment by rknudsen** [comment]
@Armada651 Thank you so much for taking the time to hot patch this. The one thing I wanted to do today when I came home from work was to hop into medium. Appreciate your efforts. Preserver!

**Comment by JennyY8S** [comment]
Okay, I have medium running, but the headset view is glitching. The chaperone lines are perfect but the visuals from medium are as if the tracking is unreliable, or it's sometimes displaying the image from where everything was a few frames ago.

If I keep the headset and controller stationary the image is stable, but movements introduce errors. The faster the movement the more pronounced the error. While the medium visuals glitch, the display of the chaperone / play area bounds are rock solid.

The 'Oculus Medium' mirror window is rock solid, but clearly for me something is breaking between software & headset.

As others are okay with the app, I'll search and look for a solution.

**Comment by daJhoony** [comment]
I did the same like the others, but your patch didn't work on my machine.
- Steam admin
- reinstall revive (start installer. Should i deinstall it with windows?)
- copy your patch files from this thread
- restart whole machine
Same error. Any other hints? Thanx for help.

**Comment by rknudsen** [comment]
@daJhoony make sure you placed the patch into the correct folder. The contents should be extracted into the following depending on where you installed revive:

drive://revive/revive

you'll see the x86 and 64 folders in there along will all the other things the hot fix includes.

**Comment by daJhoony** [comment]
I put the files inside the right folder and overwrite the old one. But the whole revive did not work after copying the files over it. i make a backup of the old files and copy them back. Now is revive working again, but i'll hope their will be the next Update for the new SDK very soon and i could work with my lovely oculus medium again. I am thinking about to buy a rift only for this. So @Armada651 you are my hero :)

Is the short patch only for injection? I'll tryied it, but it didnt work either.

**Comment by daJhoony** [comment]
@JennyY8S Sry, but i found no rest. I must think about your hints all day long. Could you tell me exactly where i have to put these hot fix files?
My revive is in C:\ProgramFiles\Revive\*.*
But there is noch 64 or 86 dir in it. So i will try to copy the 64files into the main C:\[ProFil]\Revive dir. Is this correct? 
Thanx for your help. have a nice day.

**Comment by rknudsen** [comment]
@daJhoony So you should have a folder in that path e.g. : My revive is in C:\ProgramFiles\Revive\revive
That will be where you extract all of the hot fix files to.

**Comment by daJhoony** [comment]
But how could a hotfix work, when none of the original files will be overwriten, because a revive\revive dir did not exist before. But anyway, illl tryed this one too and it didnt work yet. I will make a last reinstall now, but than i hope there will be an official patch of @Armada651 and all will be working again. But big thanx for your help :)

**Comment by daJhoony** [comment]
Thanx for all help from anybody. It's working now. And i don't know what i was doing wrong. Thanx for all that great support. Have a nice day.

**Comment by daJhoony** [comment]
@Armada651 I got now the patch_revive.zip file installed, which you uploaded in this thread. Now there are coming some updates from you for revive, special for lone echo. Could we install them or will it not work with medium? I skipped them now, but anytime will be coming the moment of truth to push the update button :).

**Comment by Armada651** [comment]
Versions since 1.1.9 contain the hotfix too.

**Comment by cupcakedreamer** [comment]
Does that mean Medium is a working title now? If so you might want to update the compatible list. It shows as not working.

**Comment by Armada651** [comment]
@cupcakedreamer Thanks for notifying me, I didn't know it was changed to not working.
