### ISSUE TITLE
Wilson's Heart - rotational latency and some lost frames

### ISSUE THREAD

**Issue by hundenmarvin** [LibreVR/Revive#679]
Hi
I have rotational latency and some lost frames in Wilson's Heart. I don't know if they are really lost frames but a lot of frames seem to be double frames. I have tried it with async reprojection on, allways-on-reprojection on and all reprojection options of. It happens on both a pretty old version of revive and the newest 118. I have a 1080ti card with the 382.05 nvidia-driver because I heard it was the last stable driver. I don't think this happens on any other revive games because I tried Chronos right after and it worked flawlessly.

**Comment by hundenmarvin** [comment]
Now that I think about it I have had the same rotational latency in Herobound: Spirit Champion as well but that was already about 6 to 12 months ago.

**Comment by Armada651** [comment]
Make sure you're not using supersampling.

**Comment by hundenmarvin** [comment]
Yep I am not supersampling :-)

**Comment by hundenmarvin** [comment]
Success! I updated to revive 1.1.12, enabled SteamVR beta and Wilson's Hearts tracking and framerate is now flawless. Not only that but Chronos, Herobound and Echo Arena now also works flawless, where I had similar issues with those games before.
