### ISSUE TITLE
 War Thunder is running, see the ground from wing becomes translucent

### ISSUE THREAD

**Issue by a7610783** [LibreVR/Revive#68]
翻譯
Since the update is compatible with version 4.0 after
Play no problem
But my wings and began to become part of a non-instrument translucent and you can see the trees the ground, but to see the sky or the sea is normal, which is compatible with the problem or the problem itself War Thunder?

**Comment by Ossius** [comment]
Try turning off all Anti aliasing in the launcher before starting up war thunder in revive.  It fixed any transparency issues.
