### ISSUE TITLE
If you run "damaged core", the height is incorrect.

### ISSUE THREAD

**Issue by c9709062** [LibreVR/Revive#683]
If you run "damaged core", the height is incorrect.
Whenever the scene changes, press the menu button again to adjust the height.
Could you review this issue?
thank you.

**Comment by Armada651** [comment]
I am not able to reproduce the issue. Try this: https://github.com/LibreVR/Revive/wiki/Troubleshooting#my-position-in-the-game-is-incorrect

**Comment by c9709062** [comment]
"Damage Core" is played with the game pad.
Press the button to return to the original position.
But when you move, it floats back in the air.
If you push the button again, it will return to its original position, and if you move again, it will float in the air.
Repeat this.
So I gave up playing this game.
Thank you.

**Comment by Armada651** [comment]
That is definitely not normal, sounds like something is wrong with your Vive.
