### ISSUE TITLE
Will Oculus Rift headset & store work on a computer with Vive and Revive installed?

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#684]
I saw the Rift is on sale for $400 and thought about picking one up.  Will the Revive and Vive conflict on a PC that has a Rift installed?  Should I uninstall Revive?  If so, how do you uninstall it?

If they don't conflict, I'm assuming that all I need to do is hook up the sensors for the Rift and then swap HDMI cables for the Vive and Rift for whatever one I want to play.

Just also wondering if SteamVR will launch correctly, if it detects both a Vive and Rift.

**Comment by Armada651** [comment]
Sure, why not?

**Comment by lghtanddrk** [comment]
So I don't need to uninstall Revive and I can launch games in Steam for either Rift or Vive depending on which one is currently hooked up?

**Comment by Armada651** [comment]
This is an issue tracker, if it doesn't work, then you report it here. General questions about the Vive and Rift are better asked on reddit.
