### ISSUE TITLE
Oculus Medium Update

### ISSUE THREAD

**Issue by rmcca** [LibreVR/Revive#686]
Hello - I'm finding that the latest update (last week) of Oculus Medium is not working through Revive. (I had been using Oculus Medium through revive successfully for the last 6months). Are you anticipating a revive update soon, which will solve this issue? Thanks

**Comment by jaorg1234** [comment]
See the issue mentioned here: https://github.com/LibreVR/Revive/issues/677

And this comment for a temporary fix in particular: https://github.com/LibreVR/Revive/issues/677#issuecomment-315456754

**Comment by Armada651** [comment]
Please do not open duplicate issues, there was an issue about this *three rows below yours* on the front page.
