### ISSUE TITLE
Lone Echo is juddery when using Revive

### ISSUE THREAD

**Issue by Left4pillz** [LibreVR/Revive#687]
Just a heads up if you get the chance, I got early review access to Lone Echo and when using Revive it's extremely juddery. Not sure if there's anything that you can do or if it's just an issue with the game, but it would be great if you could take a little look once the game is released as it looks really cool, but unplayable with the Vive judder.

**Comment by Armada651** [comment]
Try turning off Asynchronous Reprojection and let me know if it's better.

**Comment by SimplexPL** [comment]
Did you disable Asynchronous Reprojection?

**Comment by Left4pillz** [comment]
Just tried it and unfortunately that just seems to make the judder worse and even introduces a small tracking delay of a few milliseconds. I've tried messing around a bunch with the in game settings too which doesn't help either.

**Comment by Armada651** [comment]
I've already pre-ordered, so I'll be looking into this as soon as it is out.

**Comment by Left4pillz** [comment]
Alright thanks Armada :)

**Comment by Left4pillz** [comment]
One last note if it helps when you take a look: Turning on always-on reprojection helps to some extent by the way, but still some judder is present after doing so.

**Comment by Armada651** [comment]
I can't reproduce the judder unless Asynchronous Reprojection is turned on. What are your system specs?

**Comment by Left4pillz** [comment]
I'm using a Zotac GTX 1080 with an i7-6700k and 32GB ram. Turning on always-on reprojection and disabling both asynchronous and interleaved reprojection seems to fix it for the most part with only a small amount of noticeable judder left over. It was just that disabling only asynch for me made the game even worse, it had to be done in conjunction with the other 2 steps to make it run mostly okay with that small bit of judder left over.

**Comment by Armada651** [comment]
Please test this release and report back whether it improves the situation: https://github.com/LibreVR/Revive/releases/tag/1.1.10

**Comment by olemartinorg** [comment]
I'm having the same problem. Very noticeable in the menu when first starting up the game, luckily a little less noticeable in the game, but still uncomfortable.. I've only tried 1.1.10.

**Comment by jniedrauer** [comment]
Seeing the same thing here with 1.1.10. Also confirmed that always-on reprojection on, asynchronous and interleaved projection off, almost completely fixes this problem.

**Comment by Left4pillz** [comment]
After using 1.1.10 and doing my previous steps with the reprojection options, I can confirm that the judder is pretty much completely gone. In about an hour more of playing I only noticed a 2 or 3 small skips or mini judders which may have just been the game rendering new stuff, thanks for the work Armada :)
