### ISSUE TITLE
emulating oculus touch joystick with HTC Vive controller  in games it doesn't moove smoothly  it jumps..

### ISSUE THREAD

**Issue by theSe1f** [LibreVR/Revive#688]
Hi all

I'm new to VR/Revive- and very grateful for Revive- I have an HTC Vive and have Revive installed and have successfully run some Oculus home titles with my Vive and most of the Oculus touch controls 'translated' to my Vive controllers are pretty intuitive - the only issue I have is with emulating the Oculus touch 'joystick' - when emulating on the Vive controllers (eg. playing 'Mission: ISS' or 'Echo Arena', both games set in zero G)- instead of pitching/rolling/yawing in a smooth motion (as I expect it to respond with the actual Oculus touch joystick controller) the motion 'jumps' 90 degrees in that direction and is not smooth and is basically unusable/disorientating as it's so sensitive.. does anyone know of a solution to this at all to make that motion smooth?  Grateful for any feedback. Thank you in advance

**Comment by Martin-Oehler** [comment]
This is probably how the game wants you to turn to reduce motion sickness. You should check the in-game settings.

**Comment by theSe1f** [comment]
thanks for your reply- I can't see that being the way- it would make much more sense to move smoothly as as I say it's too sensitive/disorientating to 'jump' like this- it happens in the only two oculus games that I used the 'joystick' with (not just one)- both 'Echo Arena' and 'Mission: ISS'- do you know of another (free) game to test where the joystick movement is smooth? I don't see any (in game) options to change..anything in the game files' folder to change?

**Comment by Armada651** [comment]
This is as intended, smooth turning is a surefire way to make someone completely motion sick.

**Comment by theSe1f** [comment]
OK- no way to change that regardless of motion sickness- as other VR Zero G games like Homebound and Detached have full rotational control in smooth motion..?

**Comment by theSe1f** [comment]
what about if I change the settings of the thumbstick in Revive settings such as here- https://raw.githubusercontent.com/matzman666/OpenVR-AdvancedSettings/master/docs/screenshots/RevivePage.png

**Comment by Martin-Oehler** [comment]
You can't do anything about that, because it is game logic. If you want a different behavior, speak with the game devs.
