### ISSUE TITLE
Lone Echo and Echo Arena does not launch

### ISSUE THREAD

**Issue by Jonas-Mikkelsen** [LibreVR/Revive#689]
It shows no error messages

SteamVR thinks the software is starting for a couple of seconds and then it gives up.

I don't know if this is on SteamVR's side, Revive's side or oculus's side

**Comment by Martin-Oehler** [comment]
Can confirm. After it happens, I land back in SteamVR Home below the ground.

**Comment by ecobrie** [comment]
Also experiencing this.

**Comment by Armada651** [comment]
Fixed in the latest release: https://github.com/LibreVR/Revive/releases/tag/1.1.9

**Comment by Martin-Oehler** [comment]
Whoa, that was fast. The fix works, thank you.
