### ISSUE TITLE
Project Cars: Trouble reading toast messages during race

### ISSUE THREAD

**Issue by dudel** [LibreVR/Revive#69]
I don't know if this is actually a problem with the game itself and it is hard to describe but whenever there is a notification (e.g. "You made a fastest new lap", "Manual control" after leaving the box, etc) they appear to doubled as if the stereo vision is off and I have to close one eye if I want to read the message. Everything else seems to work though.

**Comment by LibreVR** [comment]
I've also noticed this, looks like these overlays are placed at the wrong depth.
