### ISSUE TITLE
full free release of Echo Arena (released todaY) not running at all despite beta version worked

### ISSUE THREAD

**Issue by theSe1f** [LibreVR/Revive#690]
they released the full version of Echo Arena today (available for free to keep forever but only if installed the next 3 months)- however, it is not running at all- trying to launch from steamvr it does not load- hope this can be fixed as the beta worked mostly fine and was excellent- thanks for any feedback

**Comment by Armada651** [comment]
Try updating to Revive 1.1.9 and restart SteamVR after the update: https://github.com/LibreVR/Revive/releases/tag/1.1.9

**Comment by theSe1f** [comment]
thank you- that worked!

**Comment by benz145** [comment]
A friend has updated to the latest version (including SteamVR) but is seeing this message: "Failed to initialize Oculus VR session. Please make sure you have the latest Oculus runtime. And that your headset is properly connected to your PC."

He also tried repairing his Oculus installation but no luck. Other games are launching with Revive with no problem.

**Comment by arepass** [comment]
Same here.

**Comment by theSe1f** [comment]
I'm also interested in knowing if Echo Arena's single player payware part of the game (Lone Echo) is also supported fully with revive as well before committing the money to it knowing Oculus home doesn't readily give refunds for any of their titles like steam does and didn't want to waste money if it's not yet supported.. Thanks for any feedback

**Comment by Armada651** [comment]
@benz145 Your friend is running into issue #702.
