### ISSUE TITLE
Lone Echo doesn't start

### ISSUE THREAD

**Issue by Vallutaja** [LibreVR/Revive#691]
When I run it on the dashboard the dashboard goes gray and the Oculus app gives an error that says a connection cant be made with the oculus store, please check your internet connection and firewall

**Comment by Armada651** [comment]
Try restarting your PC.

**Comment by Vallutaja** [comment]
Still the same thing...

**Comment by Armada651** [comment]
Have you tried any other games?

**Comment by Vallutaja** [comment]
I just tried Superhot and it works fine.

**Comment by CarrotSurvivor** [comment]
Disable antivirus?

**Comment by Vallutaja** [comment]
I only have Windows Defender.

**Comment by CarrotSurvivor** [comment]
Does it work now? I've had that issue before but I just restarted pc and stuff. Make sure oculus home is open when trying to play the game

**Comment by Vallutaja** [comment]
It works now. An update to Revive fixed it.
