### ISSUE TITLE
Revive can't launch games because I don't own an oculus 

### ISSUE THREAD

**Issue by InfiniteXV** [LibreVR/Revive#693]
Whenever I try to launch an oculus game with revive I get an error from oculus saying. You can't play this game without an Oculus headset.

**Comment by CarrotSurvivor** [comment]
Restart your PC. Problem solved.

**Comment by CarrotSurvivor** [comment]
Also make sure you are launching the games from the revive dashboard in steam vr (in the HMD) after you restart your pc
