### ISSUE TITLE
Lone echo outside performance

### ISSUE THREAD

**Issue by jippyuk** [LibreVR/Revive#696]
Firstly great job on this amazing cross vr. Without your work we wouldn't have had a chance to try this amazing new game. Hands down best experience I've played so far. 

Only issue i have is with outdoors. Games run perfectly until the airlock and outside the performance takes a huge hit. Reprojection always on with other two options off as recommended for revive but no go. Default settings no super sampling on a ryzen with gtx 980ti.

Somethings is off and can't figure out what. Several other people on reddit confirming same issues. 
Any thoughts mate?

**Comment by Armada651** [comment]
Can you post a screenshot of the SteamVR Frame Timing window during the performance issues?

**Comment by dariokan82** [comment]
Chipping in, I share the same sentiment - thanks, I'm a patreon, keep up the great work! 

1080ti, i56400, 16GB Ram. With 1.1.10 Lone Echo runs perfectly - I can even Supersample to 1.30, everything set to high (apart mesh). Looks beautiful and runs smoothly, AsyncOFF, Always-On ON.

When I get to the Airlock the game crashes. Multiple tries = multiple crashes. It just quits to windows with no bug warning.

I tried with SS 1.0 and everything medium, and it crashed. I tried Subsampling 0.8 and I get *almost* the airlock to open and it crashes.

**Comment by jippyuk** [comment]
Of course I can for ya. Unfortunately my controllers died now. Too much VR today and it's 1am over here. 
I'll get that sorted for you first thing and upload them. 

The frame timing window updates really fast. How am I going to get the frame rate drops and then screenshot that window quickly enough?

Or can I save those timings as a file or something?

**Comment by jaorg1234** [comment]
You can click on pause to freeze the frame timings. It's a checkbox in the left lower corner.

I've also noticed a very big dip in performance which makes the outside areas unplayable for me right now.

**Comment by dariokan82** [comment]
Apparently the Lone Echo developers have published a patch for the Airlock crash - my guess is that's related with the poor performance? I can't test right now but in 6/7 hours from now will try again and report back

**Comment by jippyuk** [comment]
Yeah I was just playing so I assume I am running the latest version from the store as it isn't showing any updates.

tried again and the CPU is nuts. On my 16 thread ryzen I was getting nearly 85-90% usage which to me seems crazy high. Wondering if the game usage is like that for native oculus users or if something funky is going on with openvr / crossvr.

**Comment by dariokan82** [comment]
What is your setting for Physics in the Nvidia control panel? AUTO or GPU?

**Comment by jippyuk** [comment]
AutoSelect

**Comment by Armada651** [comment]
I'm going to check the profiler data today, but it would help if someone posted a screenshot of the Frame Timing window.

**Comment by jaorg1234** [comment]
Latest Lone Echo update, latest Revive version, always-on reprojection on, async reprojection off; just outside the airlock:

http://imgur.com/1JDxOmu

**Comment by absoluticecold** [comment]
Hi guys! :)

I just donwloaded the latest revive update and the latest lone echo update. The tutorial works 
fine but when I jump out to start the mission the game crashes evertime. Sometimes after a few seconds, sometimes when I take a look at view. (after 3min gameplay) 
I tested with always on reprojection, async reprojection off. and also with async reprojection on.
Still crashes. 
When I set the graphic settings to low it seems it works better but of course I want to play it in High resolution.
Sometimes it says I have not enough RAM memory after the crash.

Is there anything I can do to fix that problem?


Geforce gtx 1080 
Intel core i5-4690K CPU
3,50 GHz 
RAM 16,0 GB
64-Bit

**Comment by jaorg1234** [comment]
"Jumping out" as in getting out of the space station? There have been some known issues with the game crashing and reporting "not enough RAM" even for Rift users and this doesn't seem to be a Revive specific issue.

**Comment by absoluticecold** [comment]
Thanks for the fast reply! 
The first thing after the tutorial, when you interrupt her talking to her boss than she hits the handle a view times in order to help you out of your "box" 

I hope my description is good enough 😅

**Comment by jaorg1234** [comment]
Yeah, that was a crash reported by several players regardless of platform. The new Lone Echo patch from today supposedly should have fixed this crash. If it's still happening, let the devs know in the Lone Echo discord:  https://discord.gg/bnZVvkw

**Comment by absoluticecold** [comment]
alright thanks :)

Yep it's still happening, i will let them know

**Comment by Armada651** [comment]
I can't reproduce the performance issue, this is my performance outside looking back at the station *without* always-on reprojection:

![clipboard01](https://user-images.githubusercontent.com/2028870/28495049-6dbc5b18-6f41-11e7-9022-388a8ddcdb42.png)

**Comment by SimplexPL** [comment]
Maybe disable HT in BIOS to see if it's CPU related.

**Comment by Armada651** [comment]
No I was able to reproduce it eventually by staying closer to the airlock. But I also get frame drops there on a Rift. I'm going to look into small performance gains that can be made on the side of Revive, but don't expect the jitter to go away completely until Async Reprojection is fixed.

**Comment by dariokan82** [comment]
Have you tried lowering the textures? Apparently textures on high result in memory overload (causing poor performance/crashes). That's most probably a game issue (the devs are aware of those performance issues on the Discord channel).

Also try to increase your pagefile to the same amount of your RAM - it might help while they fix it. 

This performance issue it's not ReVive related apparently.

**Comment by absoluticecold** [comment]
Hi guys! Thanks for your fast help :) I finally can play the game :). I increased the pagefile and now it works. 
I just get a stutter when the game usually crashed but most of the time it works fine without stuttering. Thanks you so much for your help  :))

**Comment by Armada651** [comment]
A little bit of stuttering is expected, because you don't have Asynchronous Reprojection.

**Comment by dariokan82** [comment]
You're welcome @absoluteicecold! Enjoy the game :)

**Comment by Kelthanas** [comment]
Hi :) I also have some issues with the game. I still get some stuttering in bigger rooms. Everything is fine in the tutorial sections or the oxygen room for example. But in the hub areas it doesn't work 100% fine. It's not unplayable but reduces my enjoyment of the game.

I already set the graphics quality to low and I have a GTX970. But my GPU should be able to handle the game, right? (at least according to some Reddit posts)
The Revive patch notes say that I should turn off Asynchronous Reprojection. However, if I do that the game becomes completely unenjoyable due to massive stuttering.

**Comment by SimplexPL** [comment]
This game has massive CPU and GPU requirements. 
https://www.oculus.com/experiences/rift/1368187813209608/
Recommended Processor
Intel i7-6000 equivalent or greater
Recommended Graphics Card
NVIDIA GTX 980 equivalent or greater

**Comment by Dragoboss** [comment]
User reported game is running now.
Whereas the Echo franchise still needs high resources, issues are expected from time to time.
Please re-report any further major issues with the new format. Also make sure that when running any Echo games the new SteamVR motion smoothing option is toggled off.
