### ISSUE TITLE
Echo Arena stuck on loading when starting through Lone Echo

### ISSUE THREAD

**Issue by petes117** [LibreVR/Revive#697]
Not sure if this is related to revive or a problem with the game itself, but I can't load Echo Arena when going through the menu in Lone Echo.
Cheers :)

edit: relevant reddit thread here: https://www.reddit.com/r/Vive/comments/6opu6b/anyone_else_having_trouble_getting_echo_arena_to/

**Comment by jaorg1234** [comment]
As seen in the reddit thread, it's a game specific bug and to fix it for now, you have to add Echo Arena to your library, starting Echo Arena via Lone Echo seems to be buggy right now.
