### ISSUE TITLE
Lone Echo - No audio in headphones

### ISSUE THREAD

**Issue by CyrusBlak** [LibreVR/Revive#698]
I am currently able to get the game started and on the menu screen. However from there there is no audio in the headphones. You can hear the game audio through my TV though. Audio source is set to HTC-VIVE in windows. Not sure what's wrong.

**Comment by hyperseven** [comment]
not really a revive issue since no one else is reporting this problem?

**Comment by CyrusBlak** [comment]
I'm guessing that is not.

**Comment by Armada651** [comment]
It could be Revive, since Revive us involved with audio device selection.
But Revive will just return whatever is set as the default audio device, so
it's more likely an audio config issue on your PC.

**Comment by CyrusBlak** [comment]
I finally got it working. It turns out that I have the HDMI audio set instead of the USB audio. When I switch to revive the audio would not play through the HDMI setting. After I switched it to USB audio I got it working just fine.

**Comment by Armada651** [comment]
That shouldn't be happening, can you try HDMI again just to be sure?

**Comment by CyrusBlak** [comment]
Tried today and it is working on the HDMI setting as well. Not sure what the issue was yesterday but it appears to be sorted. Thanks.
