### ISSUE TITLE
Chronos black flickering

### ISSUE THREAD

**Issue by DrizzleRaincloud** [LibreVR/Revive#7]
This issue comes and goes on a screen-by-screen basic. Launching using the Dreamdeck instructions, the game runs and is 100% playable excepting this one issue.

The problem is especially noticeable at the red crystal screen right before the sleeping giant (3rd or so crystal in the game.)

If this flicker goes away, then the game will be in a good spot.

**Comment by LibreVR** [comment]
Should be fixed in PR #16

**Comment by LibreVR** [comment]
Ok, that PR seems to cause issues for every game but Project Cars. Going to need to find a solution that works for every game.

**Comment by LibreVR** [comment]
Should be fixed in commit 27a069935fee94a06e60ac5de1962c4f361c789c. Will be part of the 0.4 release.
