### ISSUE TITLE
Lone Echo Crashes at first pressure chamber

### ISSUE THREAD

**Issue by AustinG147** [LibreVR/Revive#701]
The game shuts off with no errors or crash reports on the part of the game where you're suppose to leave the space station for the first time to investigate the anomaly. As soon as the chamber is depressurized and the door opens it crashes every time.

**Comment by jaorg1234** [comment]
Known issue with the game and not Revive specific. The devs are still trying to fix it. Temporarily putting the graphics setting to "low" seems to be sometimes help for this transition scene.

**Comment by Armada651** [comment]
Not a Revive issue.
