### ISSUE TITLE
Lone echo error and SuperHot VR not working anymore.

### ISSUE THREAD

**Issue by Lendud** [LibreVR/Revive#702]
Ok I have 2 issues.
Lone Echo shows up on Revive dashboard but when I click it, the revive dashboard goes gray and on my desktop it pops a message that looks like this. 
http://imgur.com/a/BEf22
I've tried everything to updating the most recent version of Revive to injecting it but it still pops this message.
Superhot VR also isn't working now. I run it and it doesn't show in the vive but on my desktop it is running but a frozen image of the game.

**Comment by Lendud** [comment]
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/1168105/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/1168106/ReviveOverlay.txt)

**Comment by sly3fr** [comment]
Ok, I had the same exact problem.  Close steam and right click on steam icon on your deskt and click on run as an admin. None of the oculus rift games worked for me even dreamdeck...

**Comment by Reeker94** [comment]
Same error in ReviveInjector.txt but in RoboRecall. Worked week ago. UAC disabled and i start steam as admin.

**Comment by Zebwen** [comment]
I believe this is the same issue as I am having here: https://github.com/LibreVR/Revive/issues/703

If so, reverting back to 1.1.8 should fix it.

Zeb

**Comment by Armada651** [comment]
Have you tried updating your graphics drivers? I think it's failing to load because a dependency on Vulkan was added. If you haven't update your drivers in a long while you may not have Vulkan on your system yet.

**Comment by Zebwen** [comment]
No I have not updated my GFX drivers in about 3 weeks. Will test this when I get home.

Zeb

**Comment by Lendud** [comment]
Testing now installing with GTX 980ti drivers. Will let you know the results.

**Comment by Lendud** [comment]
Anti virus just popped this message and coincidently look what it mentions -_- so annoying
Suspected file: ConfigureRT.exe

Risk: high
Path: C:\Program Files (x86)\VulkanRT\1.0.42.1\ConfigureRT.exe

Details
•    The program csgo.exe attempted to hijack (run itself as part of) another process.

Files modified
•    C:\PROGRAM FILES (X86)\VULKANRT\1.0.42.1\CONFIGURE_RT.LOG (created)
•    C:\Program Files (x86)\VulkanRT\1.0.42.1\ConfigureRT.exe
•    C:\WINDOWS\SYSTEM32\VULKAN-1.DLL (created)
•    C:\WINDOWS\SYSTEM32\VULKANINFO.EXE (created)
•    C:\WINDOWS\SYSWOW64\VULKAN-1.DLL (created)
•    C:\WINDOWS\SYSWOW64\VULKANINFO.EXE (created)

24/07/2017 11:54:05

**Comment by Armada651** [comment]
@Lendud I guess you installed a free AV like Avast or Panda AV? If you're going to run a free AV it's better to just use Windows Defender.

**Comment by Lendud** [comment]
Update, Thanks! Your fix works and i don't get the original error but i still get "couldn't connect to Oculus store".
PS I use Bullguard and it allowed me to restore Vulkan.

**Comment by Armada651** [comment]
@Lendud I still wouldn't recommend running a third-party AV, they do much more harm than good. Windows Defender is more than enough.

For that last error you probably just need to restart your PC.

**Comment by Lendud** [comment]
@Armada651 Ah, the third party Bullguard came with my PC and is pretty good. The error I had still happened before hand. I'll restart my computer and let you know. Steam VR kind hampens my internet connection but it still works.

**Comment by Armada651** [comment]
@Lendud That AV just had a false positive on system files, that makes it a *very bad* virus scanner.

**Comment by Lendud** [comment]
@Armada651 Yeah, I've turned it down to minimal security so hopefully it wont do that anymore, testing Lone Echo now.

**Comment by Armada651** [comment]
@Lendud Why not just uninstall it then?

**Comment by Lendud** [comment]
@Armada651 Ima disable it and try to launch Lone Echo. Brb

**Comment by Armada651** [comment]
Are you using USB Wifi or something like that?

**Comment by Lendud** [comment]
I DID IT :D I updated everything now it works :D TY
