### ISSUE TITLE
"Trigger as Grip" mode - cant find setting in OpenVR advanced settings revive tab

### ISSUE THREAD

**Issue by zzleezz** [LibreVR/Revive#704]
Very excited to try this. 

Updated to latest version, also latest version of OVRAS, no setting to switch to trigger as grip mode.

**Comment by Armada651** [comment]
Not added yet to OVRAS.

**Comment by zzleezz** [comment]
Ok, thanks for letting me know.

Out of curiosity is there a way to set this manually now?

**Comment by thenayr** [comment]
I noticed it was enabled by default in one commit, then reverted in a hotfix.  Is there issues with the new setting?

**Comment by Armada651** [comment]
Before the hotfix the trigger wasn't just the grip but also the index trigger. This worked well in most cases and thus could be a default, but had an unforseen downside in Echo Arena.

Thus the hotfix fixed the issue in Echo Arena by only binding the trigger to the grip trigger. But since that only works well in Echo Arena the setting was disabled by default again.

**Comment by thenayr** [comment]
Tested this out with Echo Arena and it works wonderfully, much more intuitive for me.

Enabled as follows in `steamvr.vrsettings` file:

```
"revive" : {
  ....
  "TriggerAsGrip": true
}
```

**Comment by zzleezz** [comment]
Yeah, I tried that. Not working here for me.

**Comment by Armada651** [comment]
@zzleezz You're probably just making a syntax error, you need to use commas in the right places.

**Comment by zzleezz** [comment]
`{
   "audio" : {
      "onPlaybackDevice" : "{0.0.0.00000000}.{f291d986-de3f-440a-b921-09da7802b92a}",
      "onPlaybackMirrorDevice" : "{0.0.0.00000000}.{9f2ab214-e62c-443c-96db-d27e40577225}",
      "onRecordDevice" : "{0.0.1.00000000}.{de87f2ec-db2e-4348-8c85-ff12be71f389}"
   },
   "collisionBounds" : {
      "CollisionBoundsCenterMarkerOn" : true,
      "CollisionBoundsPlaySpaceOn" : true
   },
   "revive" : {
		"GripAsTrigger" : true
		},
   "steamvr" : {
      "allowAsyncReprojection" : false,
      "mirrorViewGeometry" : "0 0 1080 600"
   }
}
`

Heres my config. I tried copying the code directly and also typing it manually.

**Comment by Armada651** [comment]
> "GripAsTrigger"

It's the other way around, `"TriggerAsGrip"`.

**Comment by zzleezz** [comment]
I actually love you! Thanks man. I am suitably ashamed.
