### ISSUE TITLE
Lone Echo FOV sways randomly periodically

### ISSUE THREAD

**Issue by theraineydaze** [LibreVR/Revive#705]
I just updated Revive and Nvidia so I'm not sure which is related. Today after updating I continued Lone Echo and noticed alot more judder with Asynchronous Reprojection off and every 5-10 minutes the whole game would sway back and forth, up and down at random and got worse if I moved my head. I messed with in game settings with no change and could only stop it by turning on Asynchronous Reprojection for a few moments and then turning it back off. Has anyone experienced this?

**Comment by SimplexPL** [comment]
Latest nvidia drivers have issues. Try rolling back to 382.05, use Display Driver Uninstaller.

**Comment by theraineydaze** [comment]
Sounds good I'll give it a shot
