### ISSUE TITLE
Have the Oculus game name show up as the game you're playing on Steam

### ISSUE THREAD

**Issue by thibaultmol** [LibreVR/Revive#706]
I'm not even sure if this is possible. But I'd like it when I'm playing Echo Arena with Revive. To show up as 'Echo Arena' instead of 'SteamVR' or 'Revive dashboard'.

Main reason behind it is. Is because Oculus home is a social disaster (can't even send messages). So Steam would work much better and that way I'd see if people in my friendslist are playing.

- Cheers
Thibault

**Comment by Armada651** [comment]
This was the case previously until a bug in SteamVR caused me to have to resort to the current method. It might already be fixed though, I'll probably look into re-enabling this function in version 1.2.

**Comment by jippyuk** [comment]
Sounds like a great thing to have back. Being able go find friends who are playing oculus games would be great!

**Comment by dafaithz81** [comment]
Hi, any news about this bug in SteamVR ?
Would love to have this feature back.

**Comment by Armada651** [comment]
It already works for the SteamVR status window if you launch the game through the Steam Library instead of the dashboard. Unfortunately it doesn't look like the Steam Friends list will show that.

**Comment by Armada651** [comment]
Mostly implemented in the new version. It won't show Revive Dashboard anymore, but it still might not show the game status correctly in Steam Friends.
