### ISSUE TITLE
Showdown suddenly stopped working

### ISSUE THREAD

**Issue by bernardb13** [LibreVR/Revive#707]
Showdown has worked flawlessly for me for months then all of a sudden three days ago I get this:
"Failed to open descriptor file '../../../ShowdownVRDemo/ShowdownVRDemo.uproject'
Any ideas what caused this?
I have reinstalled Showdown and still the same.
My other Oculus titles work as normal using Revive.

**Comment by Armada651** [comment]
Makes sense that this could break because of recent changes. Will be fixed in the next version.

**Comment by bernardb13** [comment]
Awesome!

**Comment by SimplexPL** [comment]
As a workaround you can use native Vive version. 
https://www.reddit.com/r/Vive/comments/4k57x8/epics_showdown_demo_built_for_steamvr/

**Comment by bernardb13** [comment]
Thanks SimplexPL....it works... the resolution of this version seems to be lower, blurry too, colors seem off....the Oculus version is much better quality.  But thank you for directing me to that link!

**Comment by Armada651** [comment]
Should be fixed in the new release: https://github.com/LibreVR/Revive/releases/tag/1.1.12
