### ISSUE TITLE
Echo Arena: "Failed to inialize Oculus VR session" when launching through SteamVR UI

### ISSUE THREAD

**Issue by Xodetaetl** [LibreVR/Revive#708]
I get this error when running the game normally from VR.
It works fine if I drop the game's .exe on revive's x64 .exe

Revive v1.1.11

**Comment by CarrotSurvivor** [comment]
Restart your pc.

**Comment by Xodetaetl** [comment]
I've restarted the services, the PC, updated the graphics driver, made sure Windows Defender was the only antivirus on this PC.

**Comment by RaxerXD** [comment]
Same issue for me

**Comment by Armada651** [comment]
You need to update your video drivers. This will be fixed for older drivers in the next release.

**Comment by Armada651** [comment]
@RaxerXD Do you also have this problem when injecting manually? If you do, then you need to update your video drivers.

**Comment by RaxerXD** [comment]
Yes i have my video drivers updated but the error hasn't desappeared and injecting manually has the same error

**Comment by Armada651** [comment]
@RaxerXD Have you tried the new release, version 1.1.12?

**Comment by RaxerXD** [comment]
i ve just downloaded but same

**Comment by Armada651** [comment]
You are using a Vive headset right?

**Comment by RaxerXD** [comment]
yep

**Comment by RaxerXD** [comment]
Error: Failed to initialize Oculus VR session. Please make sure that you have the latest Oculus Runtime, and that your headset is properly connected to your PC

**Comment by RaxerXD** [comment]
I solved it :D unistalling and install again oculus

**Comment by Xodetaetl** [comment]
Hey wait, I posted the issue and it wasn't the same as RaxerXD, as for me it works when directly injecting. I doubt reinstalling Home will fix it for me as it was a new installation already. I've got to sleep right now but I'll test tomorrow with 1.1.12

**Comment by Armada651** [comment]
@Xodetaetl Sure, test it with the new version and if you still run into the problem we can reopen the ticket.

**Comment by Xodetaetl** [comment]
Yes, issue still there with 1.1.12

**Comment by Armada651** [comment]
Try restarting Steam as admin before starting SteamVR.

**Comment by Dragoboss** [comment]
Original ticket was closed and EchoVr has been reported working fine.
With the newer SteamVR, make sure motion smoothing is off, EchoVR will work.
Closing ticket.
