### ISSUE TITLE
Can't see Oculus friends in Echo Arena

### ISSUE THREAD

**Issue by DiThi** [LibreVR/Revive#712]
As the title says, Oculus friends don't show in the lobby of Echo Arena even though we can see each other in the lobby. Not sure if it's a revive issue. We managed to enter the same lobby by entering at the same time, and to play a match by pressing the quick match button at the same time, but after the match we were sent to different lobbies.

Both of us use Vive. Will update the issue soon when I get the opportunity to try with Rift friends.

**Comment by Armada651** [comment]
This has been a problem in The Unspoken too, the social features are broken when using Revive, because the game wasn't started through the Oculus Store. This may get addressed in a future version, but it's a difficult problem so it'll take a while.

**Comment by GiantSox** [comment]
This isn't a Revive issue. Echo Arena has not implemented parties yet.

**Comment by DiThi** [comment]
@GiantSox Good to know. Does it show friends while using a Rift at least? In that case there's a revive issue in addition to lack of parties.

**Comment by GiantSox** [comment]
@DiThi No, the exact same issue occurs while playing Echo Arena on the Rift.

**Comment by DiThi** [comment]
@GiantSox I see. Then I'll close this and reopen if it's still a problem after parties are implemented.
