### ISSUE TITLE
Echo arena Stutter

### ISSUE THREAD

**Issue by VanderGaming** [LibreVR/Revive#714]
I have done everything to try and fix this. I turn off the allow asynchronous reprojection, I updated my Geforce experience, I updated my steam vr and my revive software. None of these worked. Now when I go in the main menu of echo arena flickers. It doesn't stutter or flicker when I do the tutorial. It only does it when I go into multiplayer lobby and in game in echo arena. Does anyone know how I could fix it?

**Comment by CarrotSurvivor** [comment]
You need to opt into the steam vr beta, and then ENABLE Async reprojection.

**Comment by Armada651** [comment]
Only if you use the SteamVR beta.

**Comment by kvdv99** [comment]
Same for Lone Echo. Enabling async reprojection does help, but not enough.  Weird thing is that the very first time after enabling async reproj, everything looks good when I look from left to right. but when I look at the same scene again, in the same way,  heaving ghosting/echo/reprojection (not sure about the right term) starts occurring, which makes the game unplayable outside the station in space.  I tried putting settings to minimum as well as supersampling in SteamVR and in the game,  it looked like an awful blur, and the ghosting/echo/reprojection STILL occurred? 
So,  Steam VR BETA would fix this ?
