### ISSUE TITLE
Lone echo stuttering

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#715]
Enabling async reprojection does help a bit (the only one from all the options I have in Advanced Settings), but not enough. Weird thing is that the very first time after enabling async reproj, everything looks good when I look from left to right. But when I immediately look at the same scene again, in the same way, heaving ghosting/echo/stuttering (not sure about the right term) starts occurring, which makes the game almost unplayable outside the station in space, or at least, less enjoyable almost to the point where I wonder if I should keep playing. I tried putting settings to the very minimum as well as supersampling in SteamVR and in the game both below 1.0 or something, and after that, the game looked like an awful blurry mess of course,  and guess what.. the ghosting/echo/stuttering STILL occurred!
Would Steam VR BETA fix this ?
Using a GTX1080 and I can play all other games in Revive with excellent performance.

**Comment by CarrotSurvivor** [comment]
Async reprojection doesn't work without the steam vr beta man. Yes it will solve your issue.

**Comment by kvdv99** [comment]
Yeah it does work with non-beta SteamVR, but causes that annoying stuttering/ghosting effect. The strange thing is that when I disable an re-enable Asynchr. Reproj. the problem is gone for 3 seconds before it returns?

Anyway, I tried SteamVR BETA like you suggested but I don't see any difference : exactly the same issue.

Then I saw an update for Revive mentioning the stuttering effect with Async. Reproj. so I downloaded it and installed it, but again, I didn't notice any difference :(

**Comment by Chupacabra1989** [comment]
are u using multi monitors ? i always have performance issues with my 3 monitors using revive. if i unplug all then it runs fine. maybe a bug ?

**Comment by Armada651** [comment]
There are a few different forms of judder and it is **crucial** that you correctly identify the form of judder you're seeing. The version 1.1.12 update fixed asynchronous reprojection, which fixes sudden "jumps" in the tracking. Another form of stutter is "ghosting" which you can see on the slide here:

![alexvlachosadvancedvrrenderingperformancegdc2016-27-638](https://user-images.githubusercontent.com/2028870/28753987-cf23ea64-753c-11e7-9315-f414a60b363d.jpg)

That is a performance issue where you simply don't get enough FPS, but reprojection is working correctly. One reason you don't get enough FPS in Lone Echo is your CPU, for Lone Echo you need at least an i7.

**Comment by euandrei** [comment]
I get the same with i7 3930k @ 3.2ghz. image is shaking a little bit

**Comment by Armada651** [comment]
Please read my comment above, you need to identify what kind of stutter you're seeing. I can't help otherwise.

**Comment by kvdv99** [comment]
I definitely have ghosting. Weird thing is, when I disable/enable async. reproj., the first 3 seconds everything is great, excellent performance and no ghosting! After that the ghosting starts. Until I disable/enable async. reproj. again : again first 3 sec no ghosting?

I have a i7-6700K, 16GB RAM, GTX1089

**Comment by Chupacabra1989** [comment]
@kvdv99 i got exactly the same problem i always have to switch off and on  async again :( its really annoying to play.

**Comment by Chupacabra1989** [comment]
i also tried to inject and its still the same. its feels more like that the async reprojection disabling itself after some minutes of playtime. when its activated the performance is awesome everything is great but after 5 min playing everytime starts ghosting and its unplayable. when i disable it and activate it again it holds on good for 5 minutes.

**Comment by gormanj** [comment]
I know it is not a revive question, but since it was mentioned... Does any one know if you can typically just swap out an i5 for an i7 or will I have to reinstall windows. I have a 1080 OC'd to 2100+ and still need to turn on reprojection (though it works great when I do).

**Comment by SimplexPL** [comment]
@gormanj Yes you can.

I don't know if this is the same problem, but on the newest revive (1.1.12) and SteamVR i also experience ghosting. Specifically, when I enable Asynchronous Reprojection, my hands leave trails when I move them. This is very noticeable on the blue light on the scanner.
If anyone wants to test it, it happens at the beginning of the game, at the entrance to this room:
http://i.imgur.com/yTInDjE.png

**Comment by gormanj** [comment]
Thanks! On my way to store, I will report back if I can run games without reprojection after processor upgrade.

**Comment by Armada651** [comment]
@gormanj Lone Echo will reproject even on an i7, even on an Oculus Rift. It is unavoidable, 3% reprojection is actually really good. The advice to upgrade the CPU is for people who experience constant reprojection, especially when they experience it outside the space station which is the most CPU-intensive area in the game.

**Comment by gormanj** [comment]
Thanks! I loved that game. Finished it last night. Thanks for making it possible!

**Comment by Dragoboss** [comment]
https://github.com/LibreVR/Revive/issues/696
Closing. Ticket over a year old and many have reported issues fixed.

Use newer versions, make sure motion smoothing is off on SteamVR and make sure you meet the requirements for any Echo games.
