### ISSUE TITLE
Controller based games not working? (gamepad override?)

### ISSUE THREAD

**Issue by slikk66** [LibreVR/Revive#716]
I've tried both luckys tale and now landfall, both of these games seem to disable the controller I have plugged in even though the Oculus app shows that I have an xbox360 controller plugged in.

Is there something else that needs to be done to allow gamepads to work through revive?

THANKS

**Comment by slikk66** [comment]
Read another comment online about needing to have the window in focus, it's definitely in focus.  I've tried fullscreen, windowed, nothing working yet.

**Comment by Armada651** [comment]
Try installing the DirectX End-User Runtime: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by slikk66** [comment]
Thanks Armada.
I did install that exe, and that didn't work.  But I found the issue.. I'm using the SCP drivers + PS3 controller for my gamepad.  Somehow I had 2 gamepads listed under the windows controllers.. I rebooted the PC to get rid of the weird orphaned one and then it worked.

Thanks for the help!  I'll close this.
