### ISSUE TITLE
Echo Arena - Inconsistent grip release events

### ISSUE THREAD

**Issue by eosrei** [LibreVR/Revive#718]
Extremely irregularly the grip release event does not fire. This never happens when I _try_ to do it. I'm able to grab and release a wall for 30 seconds straight without problem. Sorry, no steps to reproduce other than "Play many rounds." 😢 I've been trying to figure any way to make it consistent for two weeks. I even took a screenshot once the lobby with the disc stuck my hand, but that's no use for debugging. Grip is set to standard, not hybrid or toggle.

The two instances in the last 30 minutes were:
* Stuck in the launch tube until I pressed and released the grip button a second time.
* Winning the joust and trying to throw the disc. It swings across my body, but doesn't leave my hand. I managed to quickly grab it with my other hand and throw.

Is there any other debugging information I can provide?

Thanks for your work on this project!

**Comment by Armada651** [comment]
Is it always the same controller?

**Comment by eosrei** [comment]
I don't believe so. I'll keep track.

Going to try `TriggerAsGrip` tomorrow.

**Comment by jaorg1234** [comment]
This may not be a Revive related issue, I've seen this occasionally happen with native SteamVR games as well that heavily use the grip button (e.g Superhot VR on Steam).

**Comment by eosrei** [comment]
@jaorg1234 Good point. This is by far my heaviest use of the grip buttons.

:confounded: Endemic problem... :syringe: 
* https://www.reddit.com/r/Vive/comments/5dqwb4/grip_button_release_bug/
* https://answers.unrealengine.com/questions/658608/vive-controller-grip-buttons-doesnt-always-return.html
* https://forum.unity3d.com/threads/htc-vive-trigger-or-grip-button-keeps-being-pressed.450023/
* https://answers.unrealengine.com/questions/443860/vive-grip-axis-get-stuck-on.html

A friend suggested I buy a Rift. :laughing: I'd rather not just for this game. I will switch to `TriggerAsGrip` while waiting for Knuckles.
