### ISSUE TITLE
Dead and Buried

### ISSUE THREAD

**Issue by bigtroy1114** [LibreVR/Revive#734]
I have the latest version of Revive and running Steam Vr beta and I have alot of head judder whenever I turn my head.

**Comment by russwillis** [comment]
Same problem here although not running the SteamVR Beta.
Revive version 1.1.13.
Turned off supersampling and set to default 1.0.
Turned off Asyncronous reprojection.

**Comment by bigtroy1114** [comment]
Yea I tried every setting I could think of and nothing works, this is the only game I have this problem with .

**Comment by Armada651** [comment]
It's definitely a strange issue, it doesn't look like a performance issue. It's more of a timing issue probably due to a bug in Revive.

I won't be able to release a quick fix for this, so it will need to be addressed in the next version.

**Comment by bigtroy1114** [comment]
Thanks

**Comment by Armada651** [comment]
Fixed in commit 7b5812c18cde718014848121f33899e998e05a2b.

Will be part of the next release.

**Comment by galbers** [comment]
Awesome, thanks for the effort! Can't wait to test it

**Comment by bigtroy1114** [comment]
Is there a way to update the current version?

**Comment by Armada651** [comment]
While the change that fixed the problem is small, there are a lot of other performance improvements from which Dead and Burried benefits that aren't ready for release yet. It's better to wait until the next version is ready.

**Comment by galbers** [comment]
I recompiled the repo last night and have only tested dead and buried so far, but can confirm that the jitter is gone from that game at least.

**Comment by Armada651** [comment]
Please test this beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0

**Comment by russwillis** [comment]
Excellent work, all working fine now. Just had a quick play and no problems at all.
Using Beta 1.2.0
SteamVR beta.

**Comment by bigtroy1114** [comment]
Works great,thanks.

**Comment by russwillis** [comment]
Want to check if this is just me but after a match I end up in an empty 'ghost' room. Nothing extra loads in apart from my guns and floating rocks. I have to quit the game and reload to rejoin my friends.
Oh and my voice gets projected as slow and deep so to counteract it I have to apply a voice changer (specifically the chipmunk setting).

**Comment by MacbethAUT** [comment]
Hi there, I have the same problem as russwillis, once I finish a match I end up in the void. Nothing loads but guns and rocks.

Another issue I have is that I can't get the grip toggle working. Choosing Normal, Hybrid or Toggle seems to make no difference at all.

**Comment by dborosev** [comment]
Same issue

**Comment by Armada651** [comment]
@dborosev Use the latest beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

**Comment by dborosev** [comment]
Thanks I'll give it a try in a bit.  Great work btw!!

**Comment by Dragoboss** [comment]
No report back for a year since 1.2.0.
Assuming fixed, please re-post if there is still issues with this.
