### ISSUE TITLE
jitter and floating view

### ISSUE THREAD

**Issue by mikogibo** [LibreVR/Revive#736]
I have tried playing Superhot VR the past couple days and ive gotten lots of jitter and the headset tracking seems to wonder off or float off into no where. The jitter/floating is both in the headset view and the display mirrior view. I tried an earlier version of revive but that didnt work either. I also tried turning off different settings in the steamVR settings by reading past posts, nothing seemed to work.
Would purchasing Superhot Vr again in steam fix this problem? I am just looking for a quick fix i suppose.
Please keep in mind i have used revive for months with Superhot and havent had any problems until i played maybe 3-4 days ago. I appreciate the dedication and work of the people working on apps like Revive! I have enjoyed lots of hours of superhot VR lol but now i cant show it off to friends :(

**Comment by jaorg1234** [comment]
Just for your information: you can actually request a steam key if you have purchased Superhot VR on Oculus Home:

http://steamcommunity.com/app/617830/discussions/0/1290690926863800921/?ctp=2#c1290691308576764275

**Comment by mikogibo** [comment]
wow thank you!! im gonna email them asap!!!

**Comment by Armada651** [comment]
Please test this beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0

**Comment by marcocorriero** [comment]
@Armada651 
is happening to me too.

Is happening on I Expect you to Die.
