### ISSUE TITLE
How to use Rift control button(ABXY) on Vive ?

### ISSUE THREAD

**Issue by flaredl** [LibreVR/Revive#737]
Got the game Wilson's Heart on revive, it opens but stuck on the start title with "press the button A or X on rift control to get start"...  I press all the button on vive controll and even on xboxone controller but no button seems work or be projected as these 4 buttons, so if any solutions here please.

**Comment by Armada651** [comment]
Try starting the Oculus Touch Tutorial first, that'll show you how it works. The buttons are located in the same place on your Vive controller as the virtual Touch controller.
