### ISSUE TITLE
Starting position in Echo Arena

### ISSUE THREAD

**Issue by stal2k** [LibreVR/Revive#738]
The position you start during Echo Arena is sometimes really high and 45 degrees left facing. This is new since the latest update, and noticeable when first entering the game (Main Menu) and after your player resets/loads into the pod. 

It's reminiscent of the issue with Robo Recall that existed with loading into the elevator. Below is a twitch link where you can see it happening a decent bit (I'm not that tall). You can skip to around the 54-minute mark and there are plenty of goals before/after to scrub too. 

https://www.twitch.tv/videos/167525724

**Comment by sullit** [comment]
have you tried going through the setup for standing area for setting the floor offset to the headset again in SteamVR settings?

It didn’t work for me either but it’s not really noticeable when you get in-game is it

**Comment by stal2k** [comment]
Nope, it's not that big of a deal but I thought I'd want to know if I were the dev. 

I can try redoing the setup, but like you said it's fine otherwise. I often switch chaperone profiles using advanced open VR settings but the issue was new with the changes pushed to deal with the bounds not appearing. 
On Wednesday, August 16, 2017 at 8:14 PM Todd Sullivan <notifications@github.com> wrote:

have you tried going through the setup for standing area for setting the floor offset to the headset again in SteamVR settings?

It didn’t work for me either but it’s not really noticeable when you get in-game is it

**Comment by Armada651** [comment]
This is an issue due to the quick-fix for the chaperone in version 1.1.13 to prevent further accidents. I'll have a proper fix in version 1.2 without the re-centering issues.

**Comment by Armada651** [comment]
I thought of a fix that doesn't require waiting until version 1.2, therefore I released version 1.1.14 which should fix both the chaperone issues and this re-centering issue.
