### ISSUE TITLE
Revive issues getting a fix before we've had adequate time to complain

### ISSUE THREAD

**Issue by gormanj** [LibreVR/Revive#739]
I really enjoyed coming to this github and complaining about revive and talking with others about fixes. Now it seems Revive is getting fixes before I have had adequate chance to complain about them. I thought long and hard about the witty things I was going to say about this last issue with Revive changing the center point with the last chaperone fix, but I come here just one night later after discovering it and it's already fixed! Don't you want to hear from us any more?!

**Comment by gormanj** [comment]
I'll close the issue, but I see how desperate I am. Is there such a thing as being too good!?

**Comment by Armada651** [comment]
Actually you were just slow, it was reported in issue #738 . ;)
