### ISSUE TITLE
Any chance to make it work with IoMoon ?

### ISSUE THREAD

**Issue by swapps** [LibreVR/Revive#74]

**Comment by LibreVR** [comment]
Please explain your issue more in-depth? What is IoMoon? Have you actually tried if it works? What error did you get? What system are you running? Which version of Revive?

**Comment by swapps** [comment]
hi, i'm using last revive version.

But i have bought iomoon (i didn't notice it was not for the vive).

I tried to use it like oculus titles: dragging iomoon.exe (from Program Files (x86)\Steam\steamapps\common\iOmoon folder).

The game start in a window on my monitor, and nothing show in the headset.

**Comment by LibreVR** [comment]
Unfortunately Steam conflicts with the Injector, there is no workaround yet.

**Comment by Rojoyinc** [comment]
yeah it's probably the only TITLE worth running from the RIFT.   The stuff I can run has been like   YAWN.   IOMOON looks quite nice.

**Comment by Rojoyinc** [comment]
IOMOON will be released on VIVE in near future.

**Comment by LibreVR** [comment]
You can try the [RevivePatch that was released for Steam games](https://github.com/LibreVR/Revive#steam-games).

**Comment by gormanj** [comment]
iOMoon is working just fine when using the Steam patch (i am using Oculus runtime 1.3.2).
