### ISSUE TITLE
Touchpad does not work in any game using revive

### ISSUE THREAD

**Issue by HudsonBenoit** [LibreVR/Revive#740]
Previously when I was using revive, I was using the psmove service and everything worked fine. I have recently been using nolo vr for revive and the controllers work fine, except for anything that needs the touchpad. Ive tried just about everything and tried looking for answers, but nothing seems to work to get the touchpad working. Because of that I am incapable of playing the majority of my oculus library. The touchpads work perfectly when using them in steam vr so its not the controller thats the problem, If anyone has any ideas on how to fix this, i would greatly appreciate it.

**Comment by Armada651** [comment]
Vive controllers work fine, so this is a NoloVR issue. I'm not going to make workarounds for buggy drivers.
