### ISSUE TITLE
Horrible lag/drifting/delay

### ISSUE THREAD

**Issue by Cheesio** [LibreVR/Revive#741]
I've tried using Revive for the first time but in any game I run there seems to be about a 1 second delay between me moving my head and my view moving in game. It's very nauseating and unusable. Sometimes it snaps back to normal for a bit. I've tried messing with reprojection settings in SteamVR but no luck. Performance is otherwise smooth and fine. Anyone have any idea what's going on?

**Comment by Armada651** [comment]
I'll need more info than that, your system specs to start with. A screenshot of Frame Timings window from SteamVR is also very useful.

**Comment by Cheesio** [comment]
Thanks for responding! Specs are: AMD Ryzen 5 1600 @ 3.2GHz, GTX 1080, 16GB DDR4 2400MHz RAM. Let me know if there are any other specs that are relevant. I'll take a screenshot of the frame timings window asap tomorrow.

**Comment by Cheesio** [comment]
![frametiming](https://user-images.githubusercontent.com/31223234/29569790-7f2b05c0-874c-11e7-8ac2-fa4d00437325.jpg)
Here's the frame timings. Could using the latest nVidia drivers be causing the issue?

**Comment by Armada651** [comment]
Could you post a screenshot of the less detailed graph? The detailed graph is harder to read.

**Comment by Cheesio** [comment]
![frametiming2](https://user-images.githubusercontent.com/31223234/29570156-85c71404-874d-11e7-9a39-ec5b256f79ef.jpg)
Here you go

**Comment by Armada651** [comment]
Yeah, performance looks normal, though that spike at the beginning might've caused some kind of desync in Revive. I'll compile a debug version of Revive that can show that information.

**Comment by Armada651** [comment]
1. Extract this zip file into the installation directory of Revive, replacing the existing files: https://www.dropbox.com/s/v9yxl6h1cwrfye8/Revive-Debug.zip?dl=0
2. Play a VR game until you get the delay
3. Open a browser and visit http://localhost:1338/
4. Use your browser to save the page as an html file
5. Compress the html file in a zip and upload it into the comment box here

**Comment by Cheesio** [comment]
[MicroProfile Capture.zip](https://github.com/LibreVR/Revive/files/1242459/MicroProfile.Capture.zip)

**Comment by Armada651** [comment]
What game are you running btw? This looks like Dead and Burried which is a game with known performance issues. Have you tried other games?

**Comment by Cheesio** [comment]
It was Lucky's Tale. Never heard of Dead and Burried. I've also tried Henry, Bullet Train and Dream Deck and they all behave the same way.

**Comment by Armada651** [comment]
Ah okay, they're both Unity engine games, so they look a bit similar in the report.

**Comment by Cheesio** [comment]
I've fixed the problem by going back to nVidia driver 382.53

**Comment by Armada651** [comment]
Interesting, I still wonder why that driver problem only affects Revive.

**Comment by Armada651** [comment]
Just updated my drivers, I can reproduce the problem.

**Comment by Balderick** [comment]
Are the new oculus home features interfering?   The timing of oculus being updated to start up every time a vr game is started from steam seems to be around the 382 driver era.

**Comment by Armada651** [comment]
That's unrelated, that's a bug in the SteamVR oculus driver. Correlation does not imply causation.

**Comment by Krylke** [comment]
I have hade this problem too with Drop Dead and witchblood using nvidia driver 384.xx when i reverted to 382.53 the problem disappeared.

**Comment by Armada651** [comment]
Please test this beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0

**Comment by Dragoboss** [comment]
Ticket over a year old, no further responses since 1.2.0.
1.2.0 fixed jitter issues with several games.

I am assuming fixed, if it is not please re-post with the new ticket format.
