### ISSUE TITLE
Strange shortcuts appearing in Steam

### ISSUE THREAD

**Issue by petes117** [LibreVR/Revive#743]
I get some strange shortcuts showing up in Steam when I load up SteamVR (beta). The shortcuts are named things like 'K_Games_Steam_steamapps_common...'

It seems like maybe because Revive adds shortcuts for Oculus Store games and the Oculus Store has started adding shortcuts for Steam games... might be causing the issue? Not sure what a better solution might be though.

Relevant reddit thread I started here: https://www.reddit.com/r/SteamVR/comments/6vhxnf/anyone_know_how_to_get_rid_of_unwanted_steam/

Cheers

**Comment by Armada651** [comment]
Fixed in commit ea76aa0d2cdef71f05d562752c2fccb0edc74437.

It will be part of the next version.

**Comment by petes117** [comment]
Wow that was quick! Thanks :)

**Comment by Armada651** [comment]
Let's keep it open for now until the release is actually up, it helps informing people that it will be fixed.

**Comment by kvdv99** [comment]
I have this problem too with the shortcuts.  If I would install the latest Revive Beta, can I still use the Revive check for updates then?

**Comment by Dragoboss** [comment]
@kvdv99 
Is this still an issue? Please report back shortly.

**Comment by Dragoboss** [comment]
No response in 6 days after my last post, please provide a new ticket with more details in the new format if you still encounter this problem or a new one.
