### ISSUE TITLE
Trackpad not working correctly with steamvr beta

### ISSUE THREAD

**Issue by cartman999** [LibreVR/Revive#746]
With the latest steamvr beta the trackpad is not working with revive games. Instead of touching up to move forward I have to touch center of pad and swipe forward.

**Comment by Armada651** [comment]
> Instead of touching up to move forward

That hasn't been the case for Revive for a long time. You need to move your finger to move the joystick no matter where you touch it.

> I have to touch center of pad and swipe forward

Are you use you have to touch the center? You're supposed to be able to start swiping anywhere on the trackpad.

**Comment by cartman999** [comment]
It doesn't have to be the exact center of the trackpad but its more difficult to start moving.  The controls are completely different with steamvr beta 1503092085 that says "Fixed a bug that caused trackpad touch coordinates to jump to the center at the beginning of a swipe"  Its only affecting revive games, native vive games are still working normal.

**Comment by Armada651** [comment]
I'm on the SteamVR beta, I'll review the complete trackpad interaction before the next version.

**Comment by khouryart** [comment]
After some recent updates, the analog functionality of my trackpad no longer works in Revive;so no swipes. works with button presses. I'm using Medium and can't undo or increase / decrease size of a brush or change tools for that matter without the function the Joystick has in Rift controls, for example.

**Comment by Armada651** [comment]
Input system has been rewritten, should work correctly now. If not feel free to leave a comment so I can re-open this issue.
