### ISSUE TITLE
lone echo not working

### ISSUE THREAD

**Issue by danank92** [LibreVR/Revive#748]
I tried some revive version but nothing works for lone echo. ,the game always crashing

**Comment by Armada651** [comment]
Are you using an HTC Vive headset? Did you install the [latest release](https://github.com/LibreVR/Revive/releases/tag/1.1.14)? Did you start Lone Echo from the Revive Dashboard?

**Comment by danank92** [comment]
i use dk2 and nolo vr. Yes, I have tried start from the Revive Dashboard but the game still crash after white screeen

**Comment by danank92** [comment]
i use revive lates version

**Comment by CarrotSurvivor** [comment]
Dude you are not using a vive no wonder it's not working.

**Comment by Armada651** [comment]
NoloVR is currently not supported in Revive.
