### ISSUE TITLE
Nolo controls not working as intended with revive

### ISSUE THREAD

**Issue by duig0** [LibreVR/Revive#749]
Hi Not an issue, with revive, i realise you strickly deal with vive and not third party software/hardware, but maybe you could help shed some light on this?

...just a question

I am using revive to play Oculus games, which worked fine with Hydras, revive remapped them as touch controllers...

now I have Nolo Vr and touch games are virtually unusable

no input for A,X,Y,B

In revive this is mapped to touchpad quadrants....but sadly, it is not the case with Nolo

Also, it would appear that steam games such as Arazona sunshine, which can detect nolo as touch controllers, are also unusable as the trackpad behaves erratically?

I realise this may not be a revive issue but perhaps you might have some experience which could help?

Thank you in advance

**Comment by Armada651** [comment]
I do not provide technical support for NoloVR.

**Comment by duig0** [comment]
I realise that, i just thought since you had experience emulating oculus/touch with vive/wands you might have some insight.

Thank you for your time however.
