### ISSUE TITLE
Did not see on compatibility list. Is oculus raw data revive compatible for the vive? i did a search and saw revive users mention raw data. Does that mean its compatible?

### ISSUE THREAD

**Issue by liuste** [LibreVR/Revive#753]
Raw data was mentioned here: https://github.com/LibreVR/Revive/issues/466. I want to buy the rift essential pack for 50% off with raw data but owns a vive.

Is the raw data on oculus designed only for the touch and won’t work with the vive wand?

**Comment by Armada651** [comment]
It's always better to buy a vive-native version if it's available. None of the games on the Oculus store have native Vive support.
