### ISSUE TITLE
Is it possible to disable Revive on select programs?

### ISSUE THREAD

**Issue by ficarra1002** [LibreVR/Revive#754]
Whenever I open Ark, it opens SteamVR now that I have revive, how do I stop this from happening?

**Comment by Armada651** [comment]
This isn't caused by Revive, I think Ark recently got SteamVR support.

**Comment by ficarra1002** [comment]
Ark doesn't have SteamVR support, and it wasn't doing this before I installed revive.

**Comment by Armada651** [comment]
Did you buy Ark on the Oculus Store? Have you tried uninstalling Revive to confirm that actually fixes it?
