### ISSUE TITLE
Unable to run 1.2 beta

### ISSUE THREAD

**Issue by Cless-Aurion** [LibreVR/Revive#755]
Once installed. I get an error when trying to run "reviveoverlay.exe"

My computer is in Spanish so I'll put the error in Spanish and then I'll translate it as good as I can.
![untitled](https://user-images.githubusercontent.com/31065705/30038664-7af10b50-91c7-11e7-92d1-b9999cf6de25.png)

"ReviveOverlay.exe - Point of entry was not found"
"The point of entry for the process VR_InitInternal2 in the library link C:\Program Files\Revive\ReviveOverlay.exe was not found" 

PS. I tried installing it a few times, one of the mcompletely dissabling my antivirus, just in case.
I've restarted every time too. I have also uninstalled it everytime and made sure that there where no files left on  \Program Files\Revive

**Comment by Armada651** [comment]
Copy the DLL from `C:\Program Files\Revive\Revive\x64\openvr_api.dll` to `C:\Program Files\Revive`, that should fix it.

I've updated the installer to fix the problem.

**Comment by Cless-Aurion** [comment]
That fixed it yes. Thanks!
