### ISSUE TITLE
Rock Band VR black screen (unresponsive revive dashboard) 

### ISSUE THREAD

**Issue by YarikDuck** [LibreVR/Revive#757]
So, I have an issue where I launch Rock Band VR throught Revive (using HTC VIVE) and it says "unresponsive (revive dashboard). After that I have a black screen om my monitor with sound from the game, but I cant do anything. On my headset there is nothing but home menu. I`ve tried everything, and I dont know what to do.
I used the latest revive version.
PLEASSSEE HELP

**Comment by Armada651** [comment]
Which version of Revive are you using? The beta version 1.2.0 or the stable version 1.1.14?

**Comment by YarikDuck** [comment]
Beta 1.2.0 I guess. I just updated it to the latest one, so I guess it is 1.2.0 right? 
Anyway, I reinstalled whole Steam application deleted everything from AppData, and it seem to work now.
