### ISSUE TITLE
Luckys tale opens in desktop not HTC Vive

### ISSUE THREAD

**Issue by floydstime** [LibreVR/Revive#76]
When I drag the file onto lucky's tale, it just opens on the desktop, rather than opens in the Vive

**Comment by floydstime** [comment]
Also tried running as administrator

**Comment by gormanj** [comment]
Works for me if SteamVR is running, I install the injector file and folder and I drag the game .exe to the inject file. There is also an older zip just for Lucky's Tale.

**Comment by floydstime** [comment]
Yes, I had SteamVR running.

**Comment by floydstime** [comment]
Looks like I was doing it backwards...
