### ISSUE TITLE
1.2.0 Beta - Constant haptic feedback Echo Arena

### ISSUE THREAD

**Issue by stal2k** [LibreVR/Revive#760]
The new version actually resolved an issue I was having w/ Echo Arena in terms of latency or what could be described as really slow 1/2-1 second delays in action usually after lighting effects. The new issue is much less game breaking (for EA), but would not resolve after some basic troubleshooting. 

Once I enter the game one or both wands pretty much vibrate constantly. I thought it might have to do with the Advanced Settings Proximity stuff but that wasn't on

**Comment by Szoreny** [comment]
This is happening in Lone Echo as well, one or both wands will constantly vibrate - I couldn't tell if it was random or if haptic events were getting stuck...

On the other hand the ghosting I was getting when async reprojection was enabled on the last Revive release seems resolved which is nice.

This is on a 1080ti running 382.33 drviers -

**Comment by Armada651** [comment]
Thanks for the feedback, it's nice to see version 1.2.0 successfully addresses most of the performance/latency issues.

I'll address the haptics issues in the final version, I made some changes there that were not thoroughly tested yet.

**Comment by Armada651** [comment]
Fixed in commit 0149bb9b09972106088303676765bd8838afea9f.

Will be part of the next release.
