### ISSUE TITLE
Dirt rally UI stuck position

### ISSUE THREAD

**Issue by Deapper** [LibreVR/Revive#762]
I have latest revive 1.1.14.

I'm having an issue with UI being stuck and not adjusting with VR reset button. The Driving position adjust ok with VR reset. Even the HOLD HANDBRAKE is stuck in the UI position. 

Everything worked fine before. Anyone else having this issuse?

Thanks for any response

**Comment by Armada651** [comment]
Please try version 1.1.12, there are some known regressions for Dirt Rally in the subsequent versions: https://github.com/LibreVR/Revive/releases/tag/1.1.12

**Comment by Deapper** [comment]
That fixed it thx
