### ISSUE TITLE
Controller Button Mapping

### ISSUE THREAD

**Issue by hani910** [LibreVR/Revive#765]
How can  @I can map the Vive Hamburger Menu button to Y/B buttons depending on which controller is left/right

**Comment by Armada651** [comment]
Button remapping is planned for 1.2.0.

**Comment by hani910** [comment]
Where can we see future plans?

**Comment by Armada651** [comment]
Mainly the milestones, but some of the plans are only visible on the patreon discord server.

**Comment by Armada651** [comment]
Button remapping can now be done through input scripting: https://github.com/LibreVR/Revive/wiki/Input-Scripting
