### ISSUE TITLE
base stations stop working playing lone echo

### ISSUE THREAD

**Issue by neodd70** [LibreVR/Revive#769]
I have been playing lone echo on my system for about a month now and it was very jittery. Also there were times that the base stations would stop working for a short time and then start again. I just upgraded my system with a new mobo, CPU and memory. I tried picking up where I left off and now the jitter is gone and seems to be much smoother, but now a few minutes into the game the base stations lose sync and dont come back and I have to restart the whole system to get it to reconnect. This issue doesn't happen with any of my VIVE games. Any suggestions on what it could be that would cause this issue.
Here is my PC build for reference:
Asus ROG Strix Z270E MOBO
Intel I5 7600K overclocked to 4947MHz
Octua NH D15 CPU  cooler
16 GB Corsair DDR 4 3000 MHz memory running at 2197 MHz
Asus ROG Strix GTX1080 overclocked to 2021MHz

**Comment by Armada651** [comment]
Sounds like a SteamVR problem, have you tried other, native SteamVR games?

**Comment by neodd70** [comment]
yes...almost all my games are steam games and they all run fine
