### ISSUE TITLE
Lucks Tale Xbox Controllers  Wont Work

### ISSUE THREAD

**Issue by srlatinluvr** [LibreVR/Revive#77]
Once I start Luck's tale where it says "Press A". i connected both xbox one and xbox 360 controllers and noting seems to work. Even when restarting my pc and changing controller methods with the other one not connected.

**Comment by gormanj** [comment]
My Xbox 360 controller works as long as I have the controller on before I start Lucky's Tale. I am using a wireless dongle from amazon and I need to install the drivers once, but also need to assign the in system devices once for every additional usb port I want to use the dongle in:
http://www.amazon.com/Zettaguard-Wireless-Gaming-Receiver-Xbox-Compact/dp/B0076HD2W8?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_detailpage_o06_s01

**Comment by srlatinluvr** [comment]
Thank you for the advise. I do have the wireless Xbox dongle attached and I
have a wired one also. I tried all the controllers I have all possible ways
with them all on at the same time and them off and one at a time connected.
I have uninstalled the drivers and installed he drivers for the controllers
also. Still not working😭

**Comment by Neo-One** [comment]
That's odd, I don't have this problem when I play it. I would think it's something to do with the xbox controller software? Does it work with other games?

**Comment by gormanj** [comment]
I am on windows 8.1 and set up two different dongles with PCs. The one step that took me a while to figure out is to plug and unplug the controller until I saw which USB device it was in Windows System Devices control panel and then sign the appropriate drive to it by choosing the driver in properties from one already installed on my system (after I had installed it). Similar to this video, but my drivers appear under the letter 'x' and I choose wireless: https://www.youtube.com/watch?v=_wSTiQM1IKI. Also keep in mind, that you need to do this for every port that you will be using (if you do it for one USB port and switch to another, the driver needs to be assigned for that port as well). Once you have assigned the driver on all ports, you shouldn't need to have to do it again. There is one more thing, there have been times that to get drivers to work, I've had to set the installer to a compatibility mode for the system they were written. I am not sure if this last thing is the missing piece for you.

**Comment by AkTheVrGuy** [comment]
Im having the same problem and I REALLY want to play. Did you ever find a solution?

**Comment by gormanj** [comment]
I would be happy to exhaust all possibilities of getting an xbox 360 controller working with the title with anyone, If you want email me at jggorman@optonline.net. I am unsure of people's background with the controllers and don't mean to insult, I'm just happy to help if you think there is a chance it is something besides Revive, since many of us have this working fine with our controllers.

**Comment by LibreVR** [comment]
Every user who reports this problem is trying to use Revive 0.2 with Lucky's Tale 1.0.3, that doesn't work.

To play Lucky's Tale 1.0.3 you need the latest version of Revive, which you can get from the frontpage.

**Comment by AkTheVrGuy** [comment]
Big thanks to gormanj. He talked me through it and it ended up being that I was not dragging game into injector. I was just clicking the game. Which it did open up in vive. But anyways sorry for the noobness and again big thanks to gormanj.
