### ISSUE TITLE
ReVive-Tab won't show any software installed on an external harddrive

### ISSUE THREAD

**Issue by lucasdidthis** [LibreVR/Revive#771]
Hej!

I installed ReVive and it seems to work fine (I can open the ReVive-tab in the settings-window in the Vive Headset), but it won't show the Occulus-Apps installed on an external harddrive. The Occulus core software itself is installed on the internal harddrive (in other words on another harddrive) of course.

Is this a (known) Bug? 
Do I have to install ReVive on the external Harddrive where the Occulus-Apps are located, too?

Thanks for your amazing work,
Kind regards

Lucas

**Comment by Armada651** [comment]
I have all my Oculus Apps installed on a separate hard drive, it works fine as long as you used the functionality in the Oculus setup to actually change the drive.

If you used other tricks like symbolic links it won't work.

**Comment by lucasdidthis** [comment]
Yes, I used the functionality in the Oculus setup to actually change the drive. But I didn't change anything in the ReVive setup. Did I miss something there?

**Comment by lucasdidthis** [comment]
A little update;

The Oculus Apps now (suddenly) all apear in the VR software list within steam - with a small notation saying "Open-VR". They work perfectly fine, but the dedicated Revive tab still won't show any of the Oculus software, though.

I guess there might be a conflict with the advanced settings extension ([https://github.com/matzman666/OpenVR-AdvancedSettings]), because on another machine with pretty much the same environment (but without the advanced settings extension) the apps appear within the dedicated Revive tab.
