### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#774]
Observer has built-in VR support that can be enabled by starting with the -vr switch, but that's only for Oculus. I tried injecting and patching, but neither works.  Game shows up on my screen and the HMD only displays a loading screen.

Am I doing anything wrong?

**Comment by kvdv99** [comment]
official VR support has been announced, never mind my question

**Comment by Armada651** [comment]
Internally the revive injector does allow you to supply command-line switches, it's just not exposed in the interface yet. It's something to keep in mind for a future release.
