### ISSUE TITLE
'From Other Suns' still shows in SteamVR ReVive window

### ISSUE THREAD

**Issue by tsr22** [LibreVR/Revive#776]
Due to the unusual removal of the game, (oculus removed it from the store library at a certain time) the folder remained but after deletion there is still an entry in the Revive window for SteamVR. How can I remove the entry in SteamVR? The following:

https://github.com/LibreVR/Revive/issues/397#issuecomment-267981430

Did not work. It just recreated the 'from other suns' entry. Thanks.

**Comment by Armada651** [comment]
You need to delete the relevant manifests in `C:\Program Files\Oculus\Software\Manifests`.

**Comment by tsr22** [comment]
Dammit, of course I do. I was looking in the Oculus store manifest and not my games directory one. Thanks for the reminder, Armada
