### ISSUE TITLE
Is there a way to get this to work with non Oculus store titles?

### ISSUE THREAD

**Issue by floydstime** [LibreVR/Revive#78]
I was trying to play Affected, but I couldn't get it to work.  I tried all three releases that were available on the website with different run times, but none of them worked.

**Comment by Neo-One** [comment]
Some Oculus games don't work with Injector. Here's a link for compatibility list. - https://github.com/LibreVR/Revive/wiki/Compatibility-list

**Comment by floydstime** [comment]
I understand that.  Just wondering if anyone has tried or if there is a workaround.

**Comment by gormanj** [comment]
Affected 1.6.2 works perfectly with Revive 0.4.1. No offense meant, but please be sure to have steamVR running, your xbox controller on and drag the Affected .exe game app to the injector app to launch (not the injectorRevive.exe and the Revive folder need to be in the same folder as the game .exe. Again, no insult meant, but it is not uncommon for people to be missing a step here or there (myself included).
