### ISSUE TITLE
Revive panels showing unknown games

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#780]
Lately, Revive has been showing a number of unknown games, represented by different icons (sometimes Unreal icon, sometimes game icon), I don't know why but these are games that I didn't buy on the Oculus Store.  Is there a way to remove them from the Revive panels?

**Comment by tig3rmast3r** [comment]
+1 is it possible to have an option to hide unknown sources from the dashboard ? would be great thanks.

**Comment by FrankVendetta** [comment]
@kvdv99 In my experience these are games that are cross-platform that you already own on Steam and that the Oculus app identifies as valid Rift apps (Waltz of the Wizard, Nvidia VR Funhouse, SuperhotVR, etc.) and that appear in the Revive overlay with strange icons or no icons. You can just remove them from the Oculus app and they won't show up in Revive again.
