### ISSUE TITLE
Arktika 1 won't start

### ISSUE THREAD

**Issue by LLesGTU** [LibreVR/Revive#782]
After clicking the icon in revive dashboard, a message box appears with the statement "You have pending hardware issues that is preventing you from entering VR. Please check that your headset etc. is connected."

**Comment by CarrotSurvivor** [comment]
crossVR thinks its because the game uses a newer version of the oculus SDK. it should be a quick fix but he will only be able to test the latest development version of revive later tonight.

**Comment by Armada651** [comment]
Can you test this version? https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta2

**Comment by LLesGTU** [comment]
Ja, it worked...Thank you!!

**Comment by calibban** [comment]
thank you, but i can't use toggle or hybrid mod for the grip and change hands position in this version.

**Comment by optimumbox** [comment]
1.2.0-beta2 doesn't work for me. Still getting the same error as OP.

**Comment by Armada651** [comment]
@calibban Indeed on-the-fly reloading of the settings is disabled in the beta, but it should work if you restart the game after changing the settings.

**Comment by calibban** [comment]
don't work.
in steamvr.vrsettings i have
"revive" : {
      "ToggleGrip" : 1

but the beta version don't care

**Comment by calibban** [comment]
restart the game or steamvr don't have effects

**Comment by Armada651** [comment]
@calibban Fixed it, please re-download and install the latest release.

**Comment by calibban** [comment]
thanks

**Comment by optimumbox** [comment]
Uninstalled the last version and reinstalled the one you just released. I can confirm:
 "revive" : {
      "ThumbSensitivity" : 4.570000171661377,
      "ToggleGrip" : 1,
      "TouchPitch" : 0

This is in my vr settings and it doesn't work after a restart of steamvr.

**Comment by nels45** [comment]
me too same problem

**Comment by agorman** [comment]
I'm having the same issue. Latest version of revive. Other Oculus games work. The weird thing is that I played for about an hour yesterday and it was fine.

**Comment by Maxoxpower** [comment]
got the same problem. they updated the game yesterday thats why i suppoose

http://www.4a-games.com.mt/4a-dna/2017/11/2/arktika1-patch-notes

<img width="339" alt="capture" src="https://user-images.githubusercontent.com/26907483/33512612-b7d0e066-d701-11e7-90df-6d3310b9abea.PNG">

**Comment by Armada651** [comment]
Can you try this version? https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

**Comment by agorman** [comment]
That fixes it for me. Thank you!

**Comment by dave11674** [comment]
hi guys
im trying to run this too
ive downloaded B3 1.20 revive, tried inject and patch, but it still does now ##t work
i get "game failed entitlement check"

any help here greatly appreciated

thanks

**Comment by agorman** [comment]
Make sure the Oculus VR Runtime service is running. For some reason mine stopped at one point and I got that error trying to run any Oculus games.

**Comment by dave11674** [comment]
My ovulus i believe is running fine as i run other games through ok

Thanks for the response

Dave
