### ISSUE TITLE
connect headset

### ISSUE THREAD

**Issue by nels45** [LibreVR/Revive#783]
I try to download oculus game but now they ask me to connect the headset. of course I dont have oculus headset.
how to do the tricks?

**Comment by Armada651** [comment]
When do they ask you to connect the headset?

**Comment by nels45** [comment]
after buying the game. I can't download the file

**Comment by calibban** [comment]
i have just dowloaded artika1 without any issue but the game don't work.
Try to reinstall/repair oculus home.

**Comment by nels45** [comment]
ok I try it thanks

**Comment by nels45** [comment]
it's ok 
I just change my new credit card. that's was the issue thanks
