### ISSUE TITLE
Arktika.1 immediate crash upon launch using 1.2.0.2

### ISSUE THREAD

**Issue by GreenBeanMech** [LibreVR/Revive#788]
I know you guys are sick of hearing about Arktika issues but the newest patch doesn't do anything for me atm.

i7-4790k @4.5GHz
Titan X (Maxwell) w/ AIO
16GB 2400MHz DDR3

![uptodate](https://user-images.githubusercontent.com/19272886/31515981-b384418c-af5c-11e7-8d10-c18e6938d05d.PNG)
![f_crash](https://user-images.githubusercontent.com/19272886/31515988-b789ff4c-af5c-11e7-83a0-05843c3531a2.PNG)

**Comment by Armada651** [comment]
I just tested the latest patch, it works fine. Try re-installing arktika.
