### ISSUE TITLE
Chronos plays on monitor and not Htc Vive

### ISSUE THREAD

**Issue by srlatinluvr** [LibreVR/Revive#79]
Good Day to all. I took the chance and purchased chronos(oculus store) for play on the vive. When I place the exe file into the revive injector the game does start but on the monitor and not the vive. Then I get a message on the monitor in game stating To check and make sure head set and sensor are on. Does anybody have a fix for this? I reset my pc and reset VR in stream while game was on and off. any sugestions?? Thank you for your help =)

**Comment by vraddict** [comment]
Did you install the injector to : C:\Program Files\Oculus\Software\gunfire-games-llc-chronos\Chronos\Binaries\Win64 ?? you will also need the oculus store open in the background..
Should work just fine, let me know

**Comment by srlatinluvr** [comment]
Yes thank you I got it working just fine. Thanks for your feedback. Much
appreciated.

**Comment by wissper** [comment]
What version of revive did you use to get Chronos working? Are you downgraded to 1.3.2 or running 1.4? I've been stuck trying to get this one to load for a while now and keep hitting the same sensor issue you had.

**Comment by srlatinluvr** [comment]
At the moment I used revive6.0 or.6 Idk. I have not had any trouble since downloading. Also I am dragging the exe files from the binaries of each game into the new 64bit injector. I'm not in front of my PC to get correct names of files but it works. Also I disabled SLI.

**Comment by srlatinluvr** [comment]
Oh also on 1.4 I have not removed or updated any oculus anything. Just downloaded new revive injector and revive files.

**Comment by srlatinluvr** [comment]
Oh also on 1.4 I have not removed or updated any oculus anything. Just downloaded new revive injector and revive files.

**Comment by LibreVR** [comment]
@wissper Make sure you are using the Vive though, some people are using things like VRidge without positional tracking which won't work.
