### ISSUE TITLE
TheClimb button issue

### ISSUE THREAD

**Issue by krtzztz** [LibreVR/Revive#796]
Asking for help. My Vive wands are tracking when playing The Climb, but button presses aren't registering, thus rendering the game unplayable. Anyone with the same problem or a possible fix?

Thanks!

**Comment by cr4zyw3ld3r** [comment]
Have the same issue in Lone Echo. Can grip and move arms but cannot click.

**Comment by Armada651** [comment]
@cr4zyw3ld3r What do you mean you "can't click"? If you're wondering about the mapping you can find more info here: https://github.com/LibreVR/Revive/wiki#touch-controllers

**Comment by krtzztz** [comment]
I mean the triggers, grips or none of the revive mapped buttons don't work. I've tried every single emulated buttons in the menu and nothing registers. Thanks for the responses, I had already given up on the issue :)

**Comment by cr4zyw3ld3r** [comment]
@Armada651 I cannot get past the main menu at all. Literally cannot click on anything. Not credits, not singleplayer none of the options let me continue the game past the main menu. Even though clicks work fine in Revive dash and in Steam VR. I am really confused.

**Comment by Armada651** [comment]
@cr4zyw3ld3r It doesn't sound like you're using a Vive headset, this version of Revive is primarily intended to be used on the Vive. If you have issues on other headsets you're on your own unfortunately.

@krtzztz Have you tried any other Oculus games like the Oculus Touch demo?

**Comment by cr4zyw3ld3r** [comment]
@Armada651 
Issues resolved and fixed by using OpenVR Input emulator and remapping the touchpad down to Button A through OpenVR framework from the OpenVR emu menu in steam VR!

**Comment by krtzztz** [comment]
All the other revive games such as Lone echo work fine. It's just the climb that's an issue.

**Comment by krtzztz** [comment]
I haven't tried the game in a while, but I got it working with the openVRInput emulator as suggested. So at least it's working with it, haven't tried regular revive for it anymore. I never expressed my gratitude for resolving this issue for me, so thank you everybody. Try the openVRInput emulator if it's not working otherwise :)

**Comment by Dragoboss** [comment]
@krtzztz if you do ever try with the newer Revive versions, and you find new issues, please feel free to report back in a new ticket.

Since you're reporting you have fixed your issue I'll be closing this ticket..
