### ISSUE TITLE
How do I launch Dirt Rally with normally?

### ISSUE THREAD

**Issue by cscopis** [LibreVR/Revive#798]
can't launch the game normally now that Revive is installed... ? I wanna just go play iwth my ffb settings and now its gonna make me wear my headset to do that.. but i dont wanna

**Comment by Armada651** [comment]
Because you used the patch function, you'll have to delete the xinput libraries from the Dirt Rally folder manually.

**Comment by cscopis** [comment]
kk I tried removing the injections originally lol.  new to this.. thanks

**Comment by a7mag3ddon** [comment]
I cant get DR to launch in the headset, just appears on the computer screen, using V1.23 how do i launch it ?

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/wiki#steam-games

**Comment by a7mag3ddon** [comment]
I did read those instructions but I don't have a revive icon on my toolbar :-/
