### ISSUE TITLE
Confirmed Working and Non-working thread

### ISSUE THREAD

**Issue by miketucker** [LibreVR/Revive#8]
Just an FYI to everyone trying out other apps.

**Working:**
Dreamdeck: use "drag to injector" method described on instructions
LOST: Use the "drag to injector" method 
Lucky's Tale: with game-specific patch

**Not-working:**
Henry
Farlands
Invasion!

**Comment by LibreVR** [comment]
You can make a page on the wiki for this, like this: https://github.com/LibreVR/Revive/wiki/Compatbility-list

You should be able to edit it, feel free to make any changes.

**Comment by Kaesemuffin** [comment]
works also great with subnautica.(using unity revive patch)
but I do not own a xbox one wireless controller - so my old xbox controller seems not to be supported perfectly :)
