### ISSUE TITLE
Unable to see tray icon. White on White

### ISSUE THREAD

**Issue by a7mag3ddon** [LibreVR/Revive#800]
Unable to see tray icon because its white on white. Can you add a black border to the shape ?

![image](https://user-images.githubusercontent.com/20628018/31850881-d0f14966-b652-11e7-955f-77fa624ce5b7.png)

**Comment by qlyoung** [comment]
https://raw.githubusercontent.com/LibreVR/Revive/master/ReviveOverlay/revive_white.ico

:)
