### ISSUE TITLE
issue with Revive and "Windows MR SteamVR preview"

### ISSUE THREAD

**Issue by Gruguir** [LibreVR/Revive#801]
Not sure if i should post here as Revive is not "officially" compatible with Windows MR.
I can't open an app using Revive dashboard and Windows MR SteamVR preview, but i know of other people using it without trouble.
In my case, the HMD is not detected by the apps, so it runs in 2d or refuse to go further.
However, i've been able to launch an old app (VbJin) with legacy Revive injector method.

**Comment by Armada651** [comment]
Which version of Revive are you using? Make sure you aren't using the beta version.

**Comment by Gruguir** [comment]
@Armada651 v. 1.1.14.2, public version i guess, i'm not aware of the beta

**Comment by Armada651** [comment]
Try adding this to the "revive" section of you `steamvr.vrsettings`: `IgnoreActivityLevel: true`.

You'll need to edit that file by hand, it's located in `C:\Program Files (x86)\Steam\config`.

**Comment by Gruguir** [comment]
@Armada651 thanks i tried to add "IgnoreActivityLevel" : true in the right place but it seems to break (reset) the whole config file

**Comment by Gruguir** [comment]
Finally fixed it by reinstalling SteamVR.
