### ISSUE TITLE
Dirt Rally loads to a grey sphere and flat screen?

### ISSUE THREAD

**Issue by Conti** [LibreVR/Revive#804]
I have revive 1.1.14.2 installed, latest oculus, latest steam vr, latest dirt rally. DirectX end user runtime is also installed as mentioned on the revive game compatibility list for Dirt Rally. I have an AMD R9 390, latest drivers... 4k LG Display on the display port, HTC Vive on HDMI. Running windows 10 pro.

I have run the revive patch on dirt rally by pointing at the drt.exe.

When I launch Dirt Rally, SteamVR loads and displays the game in 2 dimensional screen inside a space which is a small grey 3d sphere that looks like this: https://i.imgur.com/01G1L07.jpg - The 2 dimensional dirt rally screen is visible within this grey sphere in the vive headset but it will not appear in a screenshot. The Dirt Rally window will also appear on the computer desktop.

I have rebooted the computer numerous times, I have attempted to reinstall dirt rally and re-patch it, I have reset oculus home, etc... Still the same result.

The 4 oculus demo's that come with oculus home (avatar editor, dreamdeck, first contact, etc) launch from the revive menu in SteamVR without problem. At first (prior to patching) Dirt Rally also showed up in the revive menu of SteamVR but if I clicked on it nothing would happen. After that I patched it and I have as yet been unable to get any result except the one described above. After patching it no longer shows up in the revive menu inside SteamVR. 

Any ideas?

**Comment by cazman321** [comment]
You have to start a race.  That sphere + menu is normal.  Start DiRT Rally from Steam.  I'll say "VR not supported" but just click OK.

**Comment by Conti** [comment]
That works, thanks cazman321... Is this the same on oculus? I find that pre-race environment to be incredibly disorienting.

**Comment by cazman321** [comment]
Yeah pretty sure it's the same on Oculus.  Never had much of a problem with it myself.  I guess it can't work for everyone.
