### ISSUE TITLE
Revive suddenly stopped working with all games

### ISSUE THREAD

**Issue by Quektis** [LibreVR/Revive#806]
the bypass used to work fine with all my games, now suddenly within the last month or two, it has stopped working. 

When I drop the game .exe onto the injector a black command line box opens and closes immediately and nothing happens. The games don't appear to try and load. I've tried running as admin, disabling the anti-virus and I've tried injecting the game through the revive dashboard. Nothing works. Help would be greatly appreciated. I'm running windows 10 64bits.

**Comment by Armada651** [comment]
> When I drop the game .exe onto the injector a black command line box opens and closes immediately and nothing happens.

Sounds like you're using a very old version, have you tried the [latest version](https://github.com/LibreVR/Revive/releases/latest)?

**Comment by Quektis** [comment]
Yes, I'm using the lastest version.

**Comment by Quektis** [comment]
I tried injecting the game through the dashboard with the latest version.

**Comment by Armada651** [comment]
Drag-and-drop the contents of `%APPDATA%\Revive` into the comment box here and post the comment.

**Comment by Quektis** [comment]
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/1419201/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/1419202/ReviveInjector.txt)

**Comment by Quektis** [comment]
that's from appdata/roaming/revive

**Comment by Quektis** [comment]
No, I had taken the game out of the oculus game folder. I just put it back in there and now I get a 'pending hardware' issue that makes the game crash as soon as it launches.

[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/1419361/ReviveInjector.txt)

**Comment by Quektis** [comment]
However, the other games that weren't working now work since I put them back in the oculus game folder. It's just Arktika.1 that seems to have a problem.

**Comment by Armada651** [comment]
You're not allowed to manually move the games. That would cause all kinds of issues even if you were using an Oculus Rift.

Also, for Arktika 1 you have to use the Revive beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta2

**Comment by Quektis** [comment]
Many thanks, works now.
