### ISSUE TITLE
Adding to game compatibility list

### ISSUE THREAD

**Issue by Turgrodan** [LibreVR/Revive#807]
I was trying to add Lone Echo to the game compatibility list.  I solved Lone Echo using Revive.   Its one of the best VR games out there so I'm surprised its not on the compatibility list.  Anyway, I used the wiki editor to add Lone Echo and then when I saved, it crashed.  When I try to go back to the Wiki editor, it just immediately crashes without pulling up the editor.   Not sure what's going on.  Somebody else might need to put Lone Echo on the list for me.

**Comment by Dragoboss** [comment]
This has been done ages ago, closing.
