### ISSUE TITLE
From Other Suns cant get past "Game failed entitlement check"

### ISSUE THREAD

**Issue by OJBGamin** [LibreVR/Revive#817]
i tried doing a bunch of other stuff from older posts, i ran revive as admin, i tried manually dragging and dropping the FoS-Win64-Shipping.exe on to the ReviveInjector_x64.exe i tried patching it, whatever that did, i tried restarting occulus and steam VR and opening from vr dashboard, to no avail, anyone have any idea what im doing wrong?

**Comment by Armada651** [comment]
Reboot your PC.

**Comment by OJBGamin** [comment]
Yeah I tried that too, also didn't work, I then also tried power cycling and that didn't work either

**Comment by Armada651** [comment]
Make sure you're running the beta of Revive, From Other Suns is a very recent release: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta2

**Comment by OJBGamin** [comment]
Yup got that one, 1.2.0.2 right? Iv just tried re-installing the game today to see if it was an installation thingy, I guess we'll see

**Comment by OJBGamin** [comment]
Ok seems for some reason deleting it and re-installing it caused it to work! dunno what that was about
