### ISSUE TITLE
Blade Runner 2049: Memory Lab [Free] not working

### ISSUE THREAD

**Issue by Kiefy** [LibreVR/Revive#818]
Tried Patch/Inject, x86/x64 in both stable 1.1.14 and latest 1.2.0.2 beta. also with controllers on/off.

It either crashes instantly with a UE4 debug screen, or it loads for a while and then just closes.

- GTX 1080 (Latest driver)

**Comment by greatxerox** [comment]
hi Kiefy !

Today, i just tried blade runner 2049 with Second Beta Version 1.2.0. i assure you that it works fine !
i use last drivers 388.31.  my rig : http://forum.hardware.fr/configuration.php?config=hardwarefr.inc&pseudo=greatxerox

**Comment by Kiefy** [comment]
Hmm. I tried again today after reading it works for you, and now it works for me too. 😕

My system must've been in some weird state and just needed a restart or something.
I'm using the patch dll's in the \Binaries\Win64\ dir since my Revive panel in SteamVR isn't working. I see all the games, but when I try to click one, it closes the panel and puts me into some kind of weird pseudo scrolling state. when I re-open the panel, it is already scrolling and I have to trigger just to stop scrolling.  Not sure what's up with that. it has always worked in the past.

**Comment by necros2k7** [comment]
After start female voice speaks "something is wrong" and process exits w/o error dialog - any idea what can be wrong?
