### ISSUE TITLE
None of the Oculus home games/apps work

### ISSUE THREAD

**Issue by TheTruelycon** [LibreVR/Revive#82]
After launching Dreamdeck, Erro prompt " cannot run this application without Oculus Rift is displayed. In case of Lucky Tale the game starts, however screen with error mewssage " No headset detected appears.

I tried everything administrator for both exe. resdtarting, unknown sources, Steam VR is running, I also executed commands which were provided in the instalation guideline in CMD. I cannot think of anything more that can be wrong except for compatibility issue. Windows 10 980 ti 3770k 8GB ram ddr 3.

**Comment by gormanj** [comment]
Assuming you are placing the revive folder and injector in correct place and dragging the game .exe file to the injector, then:
When once I made the mistake of trying to setup a Rift device that I do NOT have, the runtime was stuck trying to setup. I had to suspend the service, delete some driver files and reinstall Oculus runtime (being careful to skip the setup and never try to setup a device I don't have). You can search on "cannot reinstall Oculus runtime" to try to find how to do this. Outside of that, I am on system 8.1 and things are working very well with Revive.

**Comment by WyldeStile** [comment]
Try pressing the Win Key and typing "OVRServiceLauncher.exe -stop"  (no quotes) then hit enter.  
Click Yes. 
Press the Win Key and typing "OVRServiceLauncher.exe -start"  (no quotes) then hit enter.  
Click Yes.  
This is what worked for me.

**Comment by LibreVR** [comment]
Try the new version of Revive that was just released, it is much more user-friendly and has some stability improvements.
