### ISSUE TITLE
[1.1.14|1.2b2] Games on secondary drive only launchable when Steam is loaded as Admin.

### ISSUE THREAD

**Issue by Kiefy** [LibreVR/Revive#820]
Else, I can only scroll with the trigger. it never attempts to select anything.

Maybe because the Oculus Software is stored on my E: drive?

- Windows 10 with Fall Creators Update

**Comment by Armada651** [comment]
Is the Oculus Software stored on your secondary drive or just the Oculus Apps library?

**Comment by Kiefy** [comment]
Just the library.  Runtime is at `C:\Program Files\Oculus\Support\oculus-client`

**Comment by Armada651** [comment]
Don't use symlinks those don't play well with Revive. You should check the security settings on the Oculus folder on your E: drive. It's possible that your permissions are set so only admins can execute applications from it.

**Comment by Kiefy** [comment]
Just Full Control to `Everyone`, or is there a better group to use?

![](https://image.prntscr.com/image/77UjBWrTRY2SYl8r9H_KOg.png)

**Comment by Armada651** [comment]
I saw this screenshot from you in another issue:

![](https://image.prntscr.com/image/B2OVBYBCSk6WyXcIIeIiGQ.png)

It looks like you may have changed the compatibility options of the ReviveInjector to launch as admin. If you did that, then neither the Revive Dashboard nor Steam can use the injector anymore unless they are also launch as admin.

**Comment by Kiefy** [comment]
Oh damn. well spotted!  I don't know how/why I did that. Must've been recent though, the tray Inject was working a few days ago and yep. that was it!  Dashboard is working again! 

Thanks, and really really sorry for wasting your time with my stupid bs. Like you didn't have enough on your plate! 😆
