### ISSUE TITLE
Avira Antivirus detects installer and LibOVRProxy32_1.dll as adware

### ISSUE THREAD

**Issue by bgr** [LibreVR/Revive#822]
In the latest release 1.2.0-beta2 the installer file, and after ignoring it and successfully installing, the LibOVRProxy32_1.dll are detected as "ADWARE/ELEX.vctqf".

Here's the [VirusTotal results page](https://www.virustotal.com/#/file/3e51c3da8d7ab122e715a7bfa4c6d8645e73811b7cbafb0ed35ec14c13d92068/detection) for the dll.

After this I'm getting "Unable to set the auto-launch flag, please report this" and then Revive crashes, might be related, although it happens when Avira is disabled.

**Comment by Armada651** [comment]
Uninstall Avira.

**Comment by Armada651** [comment]
I updated the installer to no longer include that file, since it's not necessary for Revive to work correctly. Hopefully that satisfies Avira.
