### ISSUE TITLE
Installer infected with ADWARE/ELEX malware

### ISSUE THREAD

**Issue by LeeLorenzSr** [LibreVR/Revive#826]
Cursory search shows this is a pretty malicious bit of code. Was this intentional? Avira reported the infection upon downloading the installer and removed the file.

**Comment by Armada651** [comment]
Welcome to the world of false positives, today Revive is the lucky winner. This is something of a weekly raffle and virus scanner vendors like Avira don't give a shit.

There are two virus scanners that actually care about preventing false positives: Windows Defender and ESET NOD32. Those are the only two virus scanners that have zero false positives in the industry tests. Please do software developers a favor and switch to one of those two virus scanners.

**Comment by Armada651** [comment]
Here's the virus total report from another issue report: https://www.virustotal.com/#/file/3e51c3da8d7ab122e715a7bfa4c6d8645e73811b7cbafb0ed35ec14c13d92068/detection

As you can see only 4 out of 67 virus scanners think Revive is malware, not really a resounding consensus.

**Comment by Armada651** [comment]
Also, looking at it more closely, it even triggers on a file that is not even necessary for Revive to work. It triggers on a part of Revive that doesn't translate any calls to SteamVR and is just used for comparison tests with the Oculus Runtime.

Since there is no way for users to use this part of Revive I can just remove it from the installer and be done with it.

**Comment by Armada651** [comment]
I updated the installer to no longer include that file, so hopefully that satisfies Avira.

**Comment by LeeLorenzSr** [comment]
Thanks for the prompt response! I was aware that some applications trigger the false positives, due to signatures that exist in the binaries when using specific tools common with those used in malware. It just seemed a bit weird here, and in light of what happened with SourceForge injections, I just wanted to bring awareness to the problem, particularly if something similar was happening.

**Comment by Armada651** [comment]
It's probably triggering on some specific usage of [minhook](https://github.com/TsudaKageyu/minhook). It doesn't bode well for your virus scanner that it disagrees with 63 other virus scanners, so I definitely recommend switching to a different one.
