### ISSUE TITLE
Dirt does not start in SteamVR

### ISSUE THREAD

**Issue by sedau** [LibreVR/Revive#830]
I see Dirt in the Revive App List but when I try to launch it, nothing happens (did Patch and restart PC).

In 

..\Steam\logs\vrserver.txt I find this every time I enter SteamVR:

C:\Program Files\Revive\revive.vrmanifest - App key revive.app.C_ProgramFiles(x86)_Steam_steamapps_common_DiRTRally_drt is invalid. Valid characters are upper or lower case ASCII letters, numbers, or one of .-_

Any Idea how to get it working?

Thanks, Sebastian

**Comment by Armada651** [comment]
You shouldn't start it from the Revive App list, this is an invalid entry that was added by the Oculus app and will be ignored in future versions. You need to launch the original Dirt Rally application from your steam library.

**Comment by sedau** [comment]
Thanks Jules, that explains it.

I'm fairly new to SteamVR and Revive since I just got my Windows Mixed Reality Device recently. 
Any idea how I could tell how to invoke a particular steamVR  game?

**Comment by Armada651** [comment]
https://github.com/LibreVR/Revive/wiki#running-games

**Comment by sedau** [comment]
Thanks works now!
