### ISSUE TITLE
Touchpad Button Rebinding

### ISSUE THREAD

**Issue by Leo11504** [LibreVR/Revive#833]
Hi, I was wondering if the ability to rebind button locations is or could be enabled.

For some games like Lone Echo the Thumbstick isn't needed so it would be great to remove/shrink how much of the touchpad it uses and increase/reposition the locations of the ABXY buttons. Ideally in a Top/Bottom split or even a split, one controller Thumbstick, one controller ABXY cross split setup.

Thanks!

**Comment by gormanj** [comment]
I play Lone Echo and I find that using trigger as grip (OpenVR-AdvancedSettings) and touchpad touch as click (OpenVR-InputEmulator) work great. You can also rebind stuff using OpenVR-InputEmulator. I am not sure about the zones, but if you have not tried both these excellent dash apps for VR, I suggest give them a shot.
https://github.com/matzman666/

**Comment by Armada651** [comment]
The next version of Revive will have scriptable input, so there will be lot's of new input mapping options and users can make and share completely custom bindings tied to a specific game.

**Comment by gormanj** [comment]
Awesome!

**Comment by roblaplante** [comment]
Super hyper great !! Sharing custom profil for button remapping for specific game will be so helpful !!

**Comment by Dragon2781** [comment]
@Armada651 is the Button mapping already included in the Beta of V1.2?
Is there an How-To somewhere?
I'm despreadly need to remap the touch-touchpad-movement to a press-touchpad-movement for "From other Suns".... and then remap the inventory functions to the other controller.
Will this be possible?

**Comment by Armada651** [comment]
@Dragon2781 Not yet, it will be part of the stable version which should be out sometime this month.

**Comment by Dragon2781** [comment]
Hi @Armada651 thank you for your answer.
I just informed me agout the button rebinding function in SteamVR Beta and I tried it.
Sadly this is not working for what I want to do and I want to ask for help again.

I want to rebind the Rift-Thumbstick functions (move) from the touchpad-touch to a touchpad-click.
So I want to change analog to digital.
It is not possible to bind the 'lthumbstick' function to a [USE AS DPAD CLICK] button.
And the 'button_lthumb****' functions are no move functions in the game.

Can you please tell me how I can reach my goal with this lua stuff?

![thumbstick](https://user-images.githubusercontent.com/34264173/43408372-74f2aabc-9421-11e8-87eb-64889e6f98ab.png)

**Comment by silence48** [comment]
I am loosing my mind trying to figure this out. I HATE vive wands.
