### ISSUE TITLE
How to download demos/games from Oculus Home

### ISSUE THREAD

**Issue by ChrisRat81** [LibreVR/Revive#836]
I skipped detection and setup of Oculus hardware and after that I can't install anything in the library. Icons for downloading in Library are  active but nothing happen after clicking. How do you do that?

**Comment by Armada651** [comment]
I've heard about this problem before, but I've never been able to reproduce the problem. Do you have discord? If so you can add me as a friend so we can troubleshoot it in detail: Armada#2798

**Comment by ChrisRat81** [comment]
Ok, thanks. I'm going to create account on discord. I'll contact you.
