### ISSUE TITLE
error crash when open game arktika.1

### ISSUE THREAD

**Issue by Maxoxpower** [LibreVR/Revive#837]
hi all..been playing the game  for  2 weeks.
and now the game got a update i think that broke the game in revive

i got this error
<img width="339" alt="capture" src="https://user-images.githubusercontent.com/26907483/33512111-13fc6e9c-d6f7-11e7-9136-cbbac094e559.PNG">

**Comment by Maxoxpower** [comment]
and yes i got the latest revive and i played the game for at least 5 hours.... really want to play again :(

**Comment by Armada651** [comment]
Fixed in the new update: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3
