### ISSUE TITLE
Bullet Train not launching in headset. Launches to desktop.

### ISSUE THREAD

**Issue by andrewpbaer** [LibreVR/Revive#838]
I have been reading up on this issue in the past, but I cannot seem to fix it myself. When I launch Bullet Train from the dashboard it will not launch to the headset. It launches minimized to the desktop. 

I am running the most recent release of Revive. I have attempted uninstalling revive and oculus to fix this issue. I am not seeing any issues in the injector log. I cannot run the application standalone either. 

Any guidance would be appreciated.

**Comment by andrewpbaer** [comment]
The program running on the desktop throws:
"Failed to open descriptor file '../../../UE4Game-Win64-Test/UE4Game-Win64-Test.uproject'

**Comment by Armada651** [comment]
Looks like they changed the descriptor name? I'll make sure this is fixed in the next release.

**Comment by andrewpbaer** [comment]
It seems the install is nested inside "BulletTrain-GDC-1.8SDK". Thanks for the help
