### ISSUE TITLE
Arktika.1 

### ISSUE THREAD

**Issue by roblaplante** [LibreVR/Revive#844]
Hello, i'm playing arktika.1 on revive 1.2 bêta 3 with a lenovo explorer, and i'm above the jeep at the beginning of the game. 
The game works fine, very fine but i'm very very tall.  Very weird...

**Comment by Neutre89** [comment]
you must run the roomscale configuration and put the headphones a little lower

desolate translator

**Comment by boynet** [comment]
+1

**Comment by Dragoboss** [comment]
Ticket seems solved and/or gone stale, year old.
Please report back if you need further help within the new ticket format.
