### ISSUE TITLE
"Installed successfully" notification every time I launch SteamVR

### ISSUE THREAD

**Issue by axfelix** [LibreVR/Revive#846]
Is there a way to get the "Revive installed successfully" notification to stop appearing every time I launch SteamVR? I've dismissed it and it still comes back every launch.

**Comment by Armada651** [comment]
This was a mistake due to an older manifest accidentally being used. You can re-download and re-install the latest version to fix it.

**Comment by axfelix** [comment]
Thanks! BTW, what is the best practice for upgrading? Just install the newest build over the older ones?
