### ISSUE TITLE
Revive binary link on 'readme' is out-of-date and doesn't work with Lucky's Tale

### ISSUE THREAD

**Issue by erwincoumans** [LibreVR/Revive#85]
I recompiled it and latest works, here is my binary:
https://drive.google.com/file/d/0Bz3vEa19XOYGVG9VYXIxUWRYbTg/view

**Comment by LibreVR** [comment]
I'm gearing up for a new release, a lot has changed. But the current release should work for Lucky's Tale if you followed the instructions correctly.

**Comment by erwincoumans** [comment]
The current release does not work with latest versions, I followed instructions, while compiling from source works fine. Good that the out-of-date release will be updated soon!
