### ISSUE TITLE
From other suns not opening after update

### ISSUE THREAD

**Issue by IQstorm** [LibreVR/Revive#850]
I just opened the game for the first time yesterday, everything worked fine, even though i had to lower graphics and the locomotion was wierd, but it worked. But after i stopped playing i think the game updated and now it just says "Fatal error" when opening it

**Comment by neodd70** [comment]
i'm getting the same error.....anyone have any suggestions

**Comment by Armada651** [comment]
You need to use the latest beta version of Revive.

**Comment by LordTentacles** [comment]
Even with the last beta version (1.2.0.1) I get the fatal error every damn time I launch the game =/
I even tried patch and inject and still not working. Do we know when a fix will be push?

**Comment by MoxFr** [comment]
I got this "Fatal Error" on my laptop, but now when i launch it from my Pc it works nice with WMR & Thumbsticks (Full locomotion) SteamVR Stable version.

You need maybe a new install of 1.20 beta 3

**Comment by LordTentacles** [comment]
I tried, still the same =/

**Comment by neodd70** [comment]
I installed the new beta of revive and now I get the message that there is no headset or controllers present when I try to use the injector however now it opens from the revive library when I'm in VR like any other game does.

**Comment by Armada651** [comment]
> I get the message that there is no headset or controllers present when I try to use the injector however now it opens from the revive library

That is expected. You should always start Oculus Store games from either the Revive Dashboard or your Steam Library.

**Comment by neodd70** [comment]
Yes, I agree that games should be started from the Oculus store or the revive dashboard however until this latest revive beta update the only way I was able to run From other Suns was to drop the FOS exe file onto the reviveinjector app. Using injector from the systray didn't even work. Whatever was done in this latest beta fixed whatever it was that wasn't working....at least in my case. Thanks again for all the work you put into Revive.
