### ISSUE TITLE
Bitdefender sees revive as malware during instal

### ISSUE THREAD

**Issue by robertwerden** [LibreVR/Revive#851]
Even after I release the files from the virus scan quarantine, the virus scanner refuses to allow the program to inject.

**Comment by Armada651** [comment]
Which file is being detected as a virus?

**Comment by robertwerden** [comment]
reviveoverlay.exe
vrserver.exe
vrmonitor.exe
vrcompositor.exe

**Comment by Armada651** [comment]
Most of those executables are not part of Revive, but part of SteamVR. Your virus scanner is probably being triggered by OpenVR.

I recommend you uninstall BitDefender and switch to a better virus scanner. If you need a free one just use Windows Defender, which is good enough for most.

**Comment by robertwerden** [comment]
Reviveoverlay.exe is part of steam?

**Comment by Armada651** [comment]
I said most, that's the only exception.

**Comment by robertwerden** [comment]
So, does it matter that the specific file is being seen as a virus?

**Comment by Armada651** [comment]
You can upload it to VirusTotal to double-check, post a link to the results here.
