### ISSUE TITLE
Why is it so difficult to find controller mappings for Revive?

### ISSUE THREAD

**Issue by benz145** [LibreVR/Revive#857]
Been Googling for the last 20 minutes and looked through the wiki but I've only been able to find an old screenshot. Somebody should really add the controller mapping to the readme/wiki.

So, I'm looking for the controller mapping... specifically, how do I press the equivalent of the Menu and 'Oculus' (Home) buttons while using the Vive controllers or Windows VR controllers?

**Comment by Armada651** [comment]
The Oculus Menu button is bound to the Menu button on the Vive controller. I'm working on a new UI that will display the mapping in the dashboard while playing a game.

The Oculus Home button is not used, because it can only be used to go back to Oculus Home which isn't available through Revive.

**Comment by Armada651** [comment]
Here's another image of the Vive controller mapping in Revive:

![mapping](https://user-images.githubusercontent.com/2028870/34043679-5f458c20-e1a2-11e7-9fa8-d3cefaa6cc12.png)

The Menu button isn't explicitly indicated, because it's the same as the Vive controller menu button at the top of the controller.

**Comment by benz145** [comment]
Thanks @Armada651 that's really helpful. 

Using Windows MR controllers, I was unable to find a way to launch the Oculus Universal Menu and/or Oculus Dash (ie: the place you'd go to invite Oculus friends to games). How would I reach that menu on the Vive controllers or Windows MR controllers?

**Comment by Armada651** [comment]
You can't unfortunately, that is an ongoing issue. You might be able to accept it through the desktop Oculus application, more info in issue #382.
