### ISSUE TITLE
Bitdefender blocking Revive

### ISSUE THREAD

**Issue by ncrossy1980** [LibreVR/Revive#858]
As of recently (I've been using Revive and bitdefender for several months) Bitdefender is blocking the Revive install.  It's detecting Gen:Variant.Ursu.34689 in ReviveInjector_x86.exe and putting the exe into quarantine which obviously prevents Revive from functioning.  This must be due to a new Bitdefender signature as it's never previously found this.
I tried both the latest beta and production release, both got flagged.

**Comment by Armada651** [comment]
It doesn't really prevent Revive from working, as most Oculus games are 64-bit and the 64-bit injector isn't flagged even though it contains the very same code.

In conclusion, Bitdefender isn't a very good virus scanner, use a better one like Windows Defender which is free or ESET NOD32.

Here is the VirusTotal report: https://www.virustotal.com/#/file/253852e9f02c75119407a3850397f75c94a6654b89fe1e58726f29bf12a31d99/detection

**Comment by Armada651** [comment]
Also, I plan to do some refactoring in the ReviveInjector, I'll keep an eye on the VirusTotal report and see what exactly these virus scanners don't like about the 32-bit injector.
