### ISSUE TITLE
zr: zombie riot not working

### ISSUE THREAD

**Issue by boynet** [LibreVR/Revive#859]
I tried uninstall and install few times and tried restarting its never open up..
I can successfully start echo arena or first contact

**Comment by boynet** [comment]
got it to work on Version 1.1.14 in the latest beta its not working

**Comment by gleep52** [comment]
I am able to play Zombie Riot right now with third beta 1.2.

**Comment by boynet** [comment]
It worked out for me after installing 1.1.14 and after that the Beta Version 1.2.0, dont know why

**Comment by Armada651** [comment]
It's because you restarted the Oculus Runtime by restarting your PC since you posted this issue.

**Comment by boynet** [comment]
Hi great library, but its not true.. I restarted multiple times both the pc and the oculus runtime, also uninstalled and installed more than once
