### ISSUE TITLE
The unspoken not working

### ISSUE THREAD

**Issue by vrgamelab** [LibreVR/Revive#862]
Entering The Unspoken after the latest update, makes it unplayable through revive saying oculus headset and sensors are not connected.
I have Revive:1.2.0.2

Is this a temporary issue or long term?

PS: Other games like Racket NX work fine.

**Comment by gitfat** [comment]
Phew, I thought it was just me having the problem. I love confirmation bias.

**Comment by Armada651** [comment]
You need to run the latest version of Revive: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3
