### ISSUE TITLE
Oculus Library not detected

### ISSUE THREAD

**Issue by LunarBear** [LibreVR/Revive#868]
I installed Oculus Home, skipped the first time setup, then installed Revive. I can access the Oculus client without any issue. Here are my problems:

- I can't install any game from the Oculus Store. When I click on the "Free" button for example for free games I get the following error: "Sorry, something went wrong. Please try again later. (OVR98597979)" (Details: "Couldn't add entitlement to library for NAME-OF-THE-GAME (1971007)").

- When I launch SteamVR, Revive tells me that it can't detect the Oculus Library. I can see and access the Revive tab in SteamVR but it says "Make sure the Oculus software is installed". It is obviously installed.

I rebooted my computer multiple times, tried to restart the Oculus service, but nothing seems to work.

**Comment by Armada651** [comment]
Sounds like something went wrong when you installed Oculus, can you try re-installing?

**Comment by LunarBear** [comment]
Thanks, reinstalling it did the trick. I know that's was a pretty dumb issue and usually I always try reinstalling apps before asking for help but Oculus erase the install files from the hard drive after installing so you have to download everything again when you reinstall and it takes ~4h to download the 1.8GB installation files where I live...

Thanks again.
