### ISSUE TITLE
Cirque du soleil

### ISSUE THREAD

**Issue by roblaplante** [LibreVR/Revive#873]
Hello !
i can't buy any of the four videos in the "Cirque du Soleil".
I clic on the price then there is an another window that opens and when i click on "BUY" it doesn't respond.
Very weird and annoying because without these trades you only got short video...
Can anybody help with this thing PLEASE ?

**Comment by Armada651** [comment]
Is it an in-app-purchase? Do you purchase it in-game or from the Oculus Store application?

**Comment by roblaplante** [comment]
It's in app purchase Armada : The button work to choose but not to buy.

**Comment by Armada651** [comment]
In-App Purchases don't work with Revive unfortunately, there is no convenient workaround.

**Comment by roblaplante** [comment]
Ok then... Is it the same thing on Steam ?

**Comment by Armada651** [comment]
SteamVR games don't need Revive.

**Comment by roblaplante** [comment]
Oh f***. I feel stupid.  I'm on Lenovo explorer. Sorry it's another problem of compatibility on Steam with Microsoft MR,  not with revive. THANKS YOU FOR YOUR TIME AND ANSWER !!
