### ISSUE TITLE
Henry displaying in sepia colors on WMR

### ISSUE THREAD

**Issue by tamer82** [LibreVR/Revive#875]
On my Windows Mixed Reality headset, Henry is displaying in sepia colors.
It seems that this is how the game alerts players when they leave the recommended tracking area.
Since WMR doesn't have external sensors, I believe that the problem relies in the spoof fix below.
Maybe the sensor pose needs to be spoofed as well?

https://github.com/LibreVR/Revive/blob/f2fa1c0cca39b40429ab8d9b6d7023a34dae0743/Revive/REV_CAPI.cpp#L348

**Comment by Armada651** [comment]
> Maybe the sensor pose needs to be spoofed as well?

Perhaps, I probably don't have enough time to improve the spoof for the next stable release, but I'll keep it in mind for the subsequent release.

**Comment by tamer82** [comment]
Thanks @Armada651 
I managed to fix it locally on my machine. The problem was happening due to not calculating the frustum in the session details so spoofing this function did the trick. 
I'll clean up the code and try to submit a PR soon.
