### ISSUE TITLE
WMR: Lucky's tale controls broken

### ISSUE THREAD

**Issue by tamer82** [LibreVR/Revive#878]
This is working fine in the current binary release (beta 3), however, with the latest on Git, the control mapping is currently broken with WMR and Lucky's tale. You can no longer move the character.

It seems that this code has changed with the introduction on the Lua script mapping. I haven't tried to debug it on my side yet to see where the problem is exactly. Any thoughts?

**Comment by Armada651** [comment]
Thanks for the heads-up, I did account for the joystick in the LUA script, but I didn't test it yet.

**Comment by Armada651** [comment]
Fixed in commit 3629e20f1b2d1bc1a6a0526c51a05a946a4863f6.
