### ISSUE TITLE
IPD seems to be incorrect

### ISSUE THREAD

**Issue by StylusEcho** [LibreVR/Revive#88]
At the moment I have SteamVR configured for standing space, so I get a blue chaperone circle on the floor at all times. In games played with Revive I have double vision looking at this circle. Throughout Dreamdeck I noticed my eyes were straining and my depth perception seemed off. These are symptoms of an incorrect in-game IPD. My Vive is set to 63.0mm, if that helps at all.

**Comment by LibreVR** [comment]
I also noticed some issues with the IPD, I'll make this a top priority.

**Comment by LibreVR** [comment]
I just double-checked with a Rift, the same IPD issues I'm noticing are present there also. Revive reports your the IPD from your HMD to the Oculus game correctly.

The IPD issue you're seeing likely stems from the game itself, so please report which games you've tried and at which points you've noticed this problem. Then I can try to reproduce them and compare it between the Rift and the Vive.

Also note that double-vision on the chaperone bounds is normal when your eyes are converging on an object that is close to your face.

**Comment by StylusEcho** [comment]
Right, i'm back. I've tried all the free titles on the Oculus Store with the latest Revive and Oculus software. Lucky's Tale looked great with a proper sense of scale and depth. I however cannot say the same about Dreamdeck, Henry, Lost and Invasion. I'll remind you again that i'm using standing space. I would assume you have never tried it, because I don't get wireframe chaperone walls. I only get a simple circle on the floor. Under normal circumstances I would not get double vision on this unless I planted my face on the floor. 

This is what I see when I alternate between my two eyes while looking at the floor: https://imgur.com/0itdCyO
As you can see, there's some awful vertical difference between each eye. No wonder my eyes could never converge on it. The trend seems to be that UE4 titles have this issue and Unity ones are fine.

**Comment by LibreVR** [comment]
I've compared the Unity Engine output between Revive and OpenVR during my development, there is no difference. I've seen this vertical distance being present in Unity games too even with native support.

I'm pretty sure this is just due to a difference in vertical FOV between the lenses. This is not just guesswork, the FOV reported from OpenVR has slight vertical variations between the left and right eye.

**Comment by LibreVR** [comment]
Also, do note that the circle is being drawn by the compositor, it is not being controlled by Revive.

So that circle is in fact your reference point for the *correct* IPD.

**Comment by LibreVR** [comment]
Seems I've found the error, I flipped two field-of-view parameters which exaggerated the difference in vertical field-of-view between the right and left eye.

Fix in commit 9bfa1de8f0e2e8acb00f7fd8a0775f16568efb99.

**Comment by StylusEcho** [comment]
Hi, thanks for resolving the issue. You're doing a service to the community. I'll keep an eye out for any other issues. Thank you.

**Comment by LibreVR** [comment]
So you can confirm the issue is solved for you?

**Comment by StylusEcho** [comment]
I only tried Dreamdeck but it looked noticeably better to me. However, it was all downhill from there. I tried to run Henry and it seems that the compositor crashed. Had to restart SteamVR. Tried again and the same thing happened. Ditto for Lost IIRC. Didn't try Dreamdeck again.

**Comment by StylusEcho** [comment]
Hi, I tried again a month ago and I no longer experienced any crashing. Maybe an update to SteamVR resolved it. Sorry for that useless report. Anyway, I stumbled across this on r/oculus, might be of interest:
https://forums.oculus.com/community/discussion/comment/429847/#Comment_429847

**Comment by LibreVR** [comment]
No worries about a "useless" report, there have been some stability improvements on both the Revive and the SteamVR side, so it's likely your issue was resolved along the way.

I don't think the IPD issue will affect Revive, it seems to be purely an Oculus Runtime issue. If it affected Revive that would mean that it is an issue with the actual game and they wouldn't be able to solve it with a Runtime update.
