### ISSUE TITLE
Oculus touch support

### ISSUE THREAD

**Issue by TheDragonkeeper** [LibreVR/Revive#880]
Im wanting to use revive in conjuntion with another application i have that runs overlays to steamvr.
i am an oculus user and the oculus software wont allow mulitiple applications to run or overlays thus  forcing me to use steam for this purpose.

i am trying to use oculus touch controllers in my games but unfortunatly revive forces mapping to the htc vive controllers.

is there anyway we can turn this off or add an option for the type of controller being used?

**Comment by Armada651** [comment]
Why do you want to use Revive with an Oculus Rift?

**Comment by TheDragonkeeper** [comment]
For the reason stated above.

**Comment by Armada651** [comment]
I don't think SteamVR gives access to all the buttons that you'll need for a 1:1 mapping. But you're free to experiment in the [latest version of Revive.](https://github.com/LibreVR/Revive/releases/tag/1.2.0)

Download [this file](https://github.com/LibreVR/Revive/blob/master/Revive/default.lua) to your `Documents\Revive` folder and you can edit any part of the input. Documentation can be found here: https://github.com/LibreVR/Revive/wiki/Input-Scripting

**Comment by TheDragonkeeper** [comment]
this  was exactly what was needed.   Thanks for the update!

**Comment by electryic** [comment]
Any possible way to get that base input mapping file?  Link is currently dead.  Thanks

**Comment by TheDragonkeeper** [comment]
https://github.com/LibreVR/Revive/blob/steamvr-input/Revive/default.lua

**Comment by Armada651** [comment]
Be careful though, I will most likely replace LUA scripting by SteamVR Input in the near future. The capabilities are about the same, however SteamVR Input allows you to configure the mapping in a graphical interface.

**Comment by antuanos** [comment]
TheDragonkeeper,

I'm also a oculus user. How did you get it to work? I can't find any .lua files to edit at all. There's also no Documents/Revive/Input/ folder where to put those files.

I have much better performance in steamvr, they have the advanced openvr settings and I'd like to run all my vr games there for coherence sake as well.

**Comment by TheDragonkeeper** [comment]
> TheDragonkeeper,
> 
> I'm also a oculus user. How did you get it to work? I can't find any .lua files to edit at all. There's also no Documents/Revive/Input/ folder where to put those files.
> 
> I have much better performance in steamvr, they have the advanced openvr settings and I'd like to run all my vr games there for coherence sake as well.

I followed the guide that was provided, so unless revive has had an update which changed this, this method should still be the case.
i was only using revive because i could access the steam vr with other applications as well as the game (oculus is very strict with, one application only).  allowing me to put my phone screen on my wrist, so dont have to take headset off to check messages or a window to watch netflix while playing less intensive games..   i found that oculus software is better when using oculus rift, it also has advanced settings but you need to run the application from the install directory. 

just to import the games from oculus to steam, i dont see there being a benefit.
