### ISSUE TITLE
Arktika.1 - Firing Weapon

### ISSUE THREAD

**Issue by brucemac89** [LibreVR/Revive#883]
Hello!

With the Revive advance settings, I can overcome all of the issues most people are having (player height, toggle grip) however, the issue I'm having is, I can't fire the dang guns. It's almost like the trigger doesn't push down far enough. I do notice that when I release the grip, it fires the weapons. You end up dropping them but it's a pain. Makes it impossible to eliminate targets.

Can anyone provide any insight on how to get this working? Using Oculus Rift with latest updates of both Oculus Home, SteamVR, and Revive.

Thank you!

**Comment by Armada651** [comment]
Can you try the last beta version? https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

Just install it over the existing installation.

**Comment by brucemac89** [comment]
I will try this tonight!

Thank you!

**Comment by brucemac89** [comment]
@Armada651 when I use the beta version, I receive an entitlement check. I'm using a batch file to load the game.

When I use the Bypass folder attached that was taken from another game I have, the game works.
[Bypass.zip](https://github.com/LibreVR/Revive/files/1599253/Bypass.zip)

**Comment by Armada651** [comment]
@brucemac89 Try running the [Oculus Setup](https://www.oculus.com/setup/) again and selecting "repair".

**Comment by Armada651** [comment]
Please note, this only works if you actually bought the game. If you're trying to pirate the game then you won't find a solution here.

**Comment by brucemac89** [comment]
Ah. I will not lie, I did torrent the game. I'm very new to VR so I've been trying games before I buy them. Arktika was one that looked good but I wasn't quite sold on it.

Thanks for the info!

**Comment by Armada651** [comment]
Thank you for wasting my time.
