### ISSUE TITLE
star trek from oculus is not working with revive on WMR

### ISSUE THREAD

**Issue by sbalaciu** [LibreVR/Revive#884]
Star trek purchased from oculus is not working with revive in windows mixed reality, I get an error that the controllers are not recognized

**Comment by Armada651** [comment]
Star trek has a native SteamVR version, I recommend asking Oculus for a refund and purchasing this version: http://store.steampowered.com/app/527100/Star_Trek_Bridge_Crew/

**Comment by Rojoyinc** [comment]
buy buying VIVE versions instead of Occulus- we let the developers know the
actual numbers of VIVE vs RIFT users.
Otherwise, the data is tainted.

**Comment by WTFGamer** [comment]
I was wondering if this would end up being an issue. Is this why apps like Google Earth don't show up in Revive? I'm pretty new to all of this. I started with the Summer of Rift and just picked up a Windows MR headset to see if Inside out is worth it. Should I scale my Oculus Store purchases back to exclusives?

**Comment by Armada651** [comment]
Yes, you should only really use Revive for exclusives. The more wrappers you use on top of each other the less convenient it's going to be because the game is just not optimized to run that way.
