### ISSUE TITLE
Superhot VR not broadcasting to headset

### ISSUE THREAD

**Issue by Amusic10** [LibreVR/Revive#885]
I have redownloaded Oculus, Revive, and SuperhotVR, but still, even after running Steam as an admin, and injecting the game, It still only launches on the desktop and freeze frames right after the logo is displayed. Please advise

**Comment by Armada651** [comment]
Your save file is probably corrupted.

**Comment by Amusic10** [comment]
I already deleted the save file and let it recreate a new one, but that didn’t work, is there anyway to implant a pre-done save file to see if that is the case?

**Comment by Armada651** [comment]
Did you buy Superhot VR on the Oculus Store? If you bought it recently I suggest you refund it since Superhot VR has a native version on Steam: http://store.steampowered.com/app/617830/SUPERHOT_VR/

**Comment by Amusic10** [comment]
I bought it via oculus, but not too recently, it was before it came to the Vive

**Comment by Amusic10** [comment]
I don’t know what you did in this most recent update, but it works now so... Cheers
