### ISSUE TITLE
Revive Input Error

### ISSUE THREAD

**Issue by vukkub** [LibreVR/Revive#890]
Hi, when trying to start Touch Tutorial, or Bullet Train through Revive I get Revive Input Error message "[string "INPUT"]:29:bad argument #1 to 'match' (string expected, got nil)"
actually I'm using Oculus DK2 with pair of PS Move controllers through PSMoveSteamVRBridge to have tracked motion controllers in VR, so my config is not like native to Revive, but maybe there is some simple workaround on my case.
my config is working good for SteamVR games, but not for Oculus Home games so I thougt Revive can help me by tricking Oculus Home games to work through SteamVR with my tracked controllers available for SteamVR only.

**Comment by Armada651** [comment]
Sounds like the PSMoveSteamVRBridge isn't reporting the controller names correctly, as a temporary fix try extracting this file into your `Documents\Revive` folder: 
[Input.zip](https://github.com/LibreVR/Revive/files/1607500/Input.zip)

**Comment by vukkub** [comment]
thank you very much! now it works like a charm!

**Comment by Armada651** [comment]
It's still an issue that requires a permanent fix.
