### ISSUE TITLE
The Climb in game can't render stereo 3d on WMR

### ISSUE THREAD

**Issue by victorkin11** [LibreVR/Revive#891]
I suspect is interpupillary distance (IPD) problem.
Using revive WMR playing "The Climb" every thing is work except the game play look very flat, no depth, 
after research, It look like only happen in WMR, when the main menu come up, there is one moment in 3d, then jump to 2d, maybe revive can't report the right IPD in WMR to cryengine, so the game use zero IPD, it make every thing look 2D.

**Comment by Armada651** [comment]
WMR isn't officially supported in Revive. I'm working on a version optimized for WMR.
