### ISSUE TITLE
StreamVR Dashboard unresponsive.

### ISSUE THREAD

**Issue by 8thWonderUK** [LibreVR/Revive#895]
Hi,

1st of all thanks to all that have contributed to this excellent software. Really appreciated. I've had a vive for a week and had revive for about 3 days. I've been using revive for echo arena and it's been great but starting yesterday. After I launch revive, the steamvr dashboard becomes unresponsive. I can open settings but I can't close Echo Arena or SteamVR, through the power button. I have to walk to my PC and close in task manager. I can open revive and steam, but the pointer from the wands go through whatever I'm trying to select. Is this a known issue with revive? I also have advanced settings installed and have been adjusting many settings, not sure if this is contributing.

**Comment by mathieuvenot** [comment]
Hello,

I have the same issue. Now trying to reinstall all steamVR, oculus, revive, and openvr. We'll see

**Comment by Armada651** [comment]
@mathieuvenot Really? Because I can reproduce the problem here and I doubt that would solve it. I need to do some more research into the problem though.

**Comment by 8thWonderUK** [comment]
I've re installed oculus and revive but not steamvr or openVR advanced settings yet. I suspected it might be the advanced settings app, or something I changed within there as the problem only arose after installing it and changing many settings.

**Comment by fecheva** [comment]
I found the same problem here. On Jan 7 it was working OK. I can't remember changing anything but updating advanced settings sin then.
