### ISSUE TITLE
Robo Recall crashing using Revive at 8% on WMR 

### ISSUE THREAD

**Issue by Bocop** [LibreVR/Revive#898]
Greetings!  I just got the Lenovo headset and downloaded Revive to use with Robo Recall.  I had heard this was the best way to play it on WMR but it does not let me get to the first mission? 

I have tried Robo Revive but that feels super clunky in comparison.  Are there any fixes coming to Revive to make Robo Recall work properly? thank you!

**Comment by eggs91** [comment]
same for me with the acer headset 
crash at the first mission 

regards

**Comment by superisty** [comment]
Same for me with samsung headset.
However I can fix that.

I connected oculus headset(retail) and sensors, and played "RoboRecall" at once.
Then I disconnected oculus headset and sensors, and  I connected samsung headset.
After that "RoboRecall" works PERFECT with samsung headset by Revive !!!

Same way can fix for "Lucky's Tale".

**Comment by Fryson** [comment]
I had the same problem with my HP WMR but now can play the game (with many crash) because of the RoboRevive thing. But superisty may have the star of a real solution.

**Comment by Armada651** [comment]
Windows Mixed Reality is not yet supported in Revive.
