### ISSUE TITLE
Revive Dashboard crash on startup.

### ISSUE THREAD

**Issue by klave7** [LibreVR/Revive#90]
When opening Revive Dashboard via SteamVR launch or using the start menu shortcut Revive Dashboard immediately crashes.  Error logs can be found here. http://imgur.com/a/hEpQw
Currently experiencing issues on Windows 10 x64.  Nvidia 780, i7 4790, 16gb ram.

**Comment by LibreVR** [comment]
When I have time I will try and create a crash dump feature in the Revive Dashboard, then you can run that version and I can examine the crash.

**Comment by Daclivont** [comment]
Just wanted to pop in and say that I'm also having the exact same error.

**Comment by LibreVR** [comment]
Please try the [new release](https://github.com/LibreVR/Revive/releases/tag/0.5.1), it has a stability fix that may solve your problem.

**Comment by klave7** [comment]
I'm still having the same issue.  Thanks for following up!

**Comment by LibreVR** [comment]
@klave7 You can try uploading your log files, they may contain some useful information.

**Comment by klave7** [comment]
I ran the uninstaller, rebooted the computer, installed, rebooted again for good measure, and now it works!

**Comment by LibreVR** [comment]
It was probably fixed in 0.5.1 then.
