### ISSUE TITLE
WMR & Latest release of SteamVR : Revive temporary Fix

### ISSUE THREAD

**Issue by MoxFr** [LibreVR/Revive#900]
Hello

Since some days i noticed that SteamVR Beta or No beta doesnt work with Revive.

I have to use Steam VR OpenVR Input emulator beta version & Revive 1.3 (Reviveinjector_x64.exe on Oculus .exe app) to make it working with my WMR Headset.

Dont remember if worked with latest Revive, i believe i got crash on oculus app.

**Comment by Armada651** [comment]
Windows Mixed Reality is not yet supported in Revive.
