### ISSUE TITLE
From Other Suns Audio No Longer working

### ISSUE THREAD

**Issue by imFunney** [LibreVR/Revive#902]
Around 8 days ago (Jan 8th) the audio in game was working just fine. After playing without sound yesterday and trouble shooting for hours today, I couldn't find a solution. Audio works fine inside other Titles like Echo Arena and I can even listen to streams and music while playing From Other Suns. It specifically the game audio.

Things I Tried:
-Restarting PC
-Checking Playback Devices
-Reinstalling Revive Current Version
-Reinstalling From Other Suns
-Reinstalling SteamVR
-Installing Revive Previous Stable Build, Fatal Error on load
-Using SteamVR Beta and normal
-Playing with the in-game audio options
-Validating SteamVR

**Comment by jtrim1** [comment]
what ended up being the problem?  I have a friend who's having the exact same issue, and we went through the exact same set of troubleshooting that you did and so far nothing is working.  I sure hope we're just being dumb.   would love to know what you found to be the issue.

**Comment by imFunney** [comment]
My audio mixer got muted somehow.
