### ISSUE TITLE
I have a very specific problem - Rock Band VR

### ISSUE THREAD

**Issue by brodzowski** [LibreVR/Revive#903]
After hours of testing last night I ran into a strange problem that I MAY know the fix for, but not sure. 
I have the Samsung Odyssey headset and am attempting to use the XBOX one guitar (both the Jaguar and the Strat do the same thing) with the wireless adapter. They connect and before I place the headset on my head, they will work. As SOON as it recognizes that it's on my head or I cover the hole in the headset that sees it (same action) the little overlay that says Win+Y comes up and I lose button functionality. I can still move and see the guitar, but the buttons don't register. If I take the headset off and click to minimize and bring it back up - the buttons work again. The second I put it back on or cover that hole - boom - gone. 
I'm assuming that if I had the bluetooth PS4 controller it may work because it seems to be the case with what little information I can find, but I thought I'd bring it to other's attention because I couldn't find any information about the bug anywhere else. I'm going to try and find a PS4 controller and see if it reacts the same.

**Comment by Armada651** [comment]
Windows Mixed Reality is not yet supported in Revive.
