### ISSUE TITLE
From others suns fatal error on launch

### ISSUE THREAD

**Issue by MagikBubu** [LibreVR/Revive#905]
Hi,

FOS get a crash at launching. A box brings  up "fatal error" reading " FOS has crashed..."

I'm using the latest version of Revive.

(Sorry for my English)

**Comment by jimivey** [comment]
fwiw, I just started having the same problem. Worked fine Friday-Sunday for the FOS "free weekend". Purchased it and now getting a fatal error after the initial startup logo and gunslinger animation.

Any suggestions on where to start debugging the problem? Reinstall the app? Reinstall Revive?

Thanks.

**Comment by MagikBubu** [comment]
I found on internet that the problem is from some software like f.lux etc.
I'll try to format windows 10 and reinstal it. It's the easiest to do I think.

**Comment by Kiefy** [comment]
Good luck. I was looking to purchase this game. Will be interested to hear how you get on.

**Comment by Dragoboss** [comment]
Closing this as no new respsonse was posted in 8 days after my previous message.
If you re-encounter this problem please open a new ticket with the new format, provide as many details as you can and we'll have another look.
