### ISSUE TITLE
Revive dashboard only shows 15 items

### ISSUE THREAD

**Issue by fecheva** [LibreVR/Revive#906]
I hadn't used Revive since Jan 7th, and it was ok. Today I have found not only I am suffering issue #895, but also dashboard only shows 15 items (one whole page). Scroll seems to work, as it scrolls just a bit when selecting an item from 1st or 3rd row, but I cannot go further than 3rd row.

As stated in my comment for issue #895 I think the only thing I have changed these days is updating advanced settings.

**Comment by Armada651** [comment]
As a temporary workaround you should still be able to launch the applications from your SteamVR library.

**Comment by fecheva** [comment]
Thank you for your (extremely!) fast response. Unfortunately when doing so, revive does not inject. Some apps start a window on desktop asking to connect my oculus headset, but nothing happens in VR. On Jan the 7th, it was working ok, I was able to launch from SteamVR library but today I cannot.

**Comment by fecheva** [comment]
Update: I have uninstalled/installed revive several times, and reverted advanced sttings to 2.4.1, unsuccessfully. Sorry for not being precise, but I have seen some notes of mine and I am not sure whether what I updated last days was advanced settins or revive itself. Anyway, I have also tried to downgrade revive to 1.1.4 and behaviour is the same. I can only succesfully start Oculus apps from revive dashboard, but not from Steam VR library (so I cannot run now most of my Oculus library) and I suffer also issue #895. I am trying to avoid to reinstall steam and oculus as the last resource, as I have aroud 600+ games installed and around 50 oculus apps. Anyway, if I am the only one who has this problem, I think I will, as it should be something related to my computer.

**Comment by Armada651** [comment]
> So now my issue is as described (only one page in revive together with issue #895) and your suggested workaround does work. It would be great if revive entries in Steam VR library were permanent, in order to be assigned to categories.

These are both issues with Steam itself, I can't fix those issues.

**Comment by fecheva** [comment]
Fixed. Thank you.
