### ISSUE TITLE
WMR needs Oculus Head set.

### ISSUE THREAD

**Issue by superisty** [LibreVR/Revive#909]
With WMR Headset,Robo Recall crashed many times at first mission in clean installed windows.
After I connected and setup oculus headset (headset and two sensors) to my computer and disconnect it, and reconnect WMR headset ,Robo recall works Perfect with WMR headset!!
Is this a bug?

**Comment by Fryson** [comment]
And you need to do this each time you want to play with your WMR headset ?

**Comment by superisty** [comment]
I need only once.

**Comment by Armada651** [comment]
WMR is not supported in Revive yet.
