### ISSUE TITLE
I can't scroll between games in revive menu (vive)

### ISSUE THREAD

**Issue by hundenmarvin** [LibreVR/Revive#912]
I am swiping the touchpad but the menu doesn't move. I have to start another revive game and when I quit that one the the revive menu will be in another position which enables me to access the right game I actually want to play.

I also just installed the latest revive version but that didn't help either.

**Comment by tig3rmast3r** [comment]
same here probably something wrong with latest steamvr release

**Comment by Yobiwan29** [comment]
Same issue here. The touchpad is unresponsive in revive panel AND in steamvr virtual desktop. I can't do a right click... Game list is glitchy, it doesn't show the totallity of the oculus apps. As is unusable.

**Comment by tig3rmast3r** [comment]
there is a beta branch on steam vr about input, everything is back to normal with that beta.

**Comment by Kiefy** [comment]
It's now fixed in the main beta branch too.
