### ISSUE TITLE
Face Your Fears can't find the headset after oculus home & steamVR updated.

### ISSUE THREAD

**Issue by victorkin11** [LibreVR/Revive#914]
This week after both oculus home & steam VR auto updated, tried inject & patch both Method, Face you Fears can't find the vr headset anymore, 
Oculus App Version 1.22.0.520720.
SteamVR 1515522829.(I don't know how to check the version no.,  just check the update news)
Win10
Windows mixed reality headset.

**Comment by Armada651** [comment]
Can't reproduce using a Vive. I'm currently working on a Mixed Reality version of Revive.

**Comment by victorkin11** [comment]
Found the reason, since Oculus Home have new "Edit Library Locations", if you change it, the old app maybe won't work, after I change back the default location, it work.
