### ISSUE TITLE
Steam Oculus games not showing on Revive Dashboard, not working

### ISSUE THREAD

**Issue by flowerdealer** [LibreVR/Revive#917]
I'm on WindowsMR (I know it isn't officially supported, but would appreciate the help). Previous release worked fine. The latest release and betas, work for games installed through the Oculus Store. But games, like Dirt Rally, installed through Steam, do not appear on the dashboard, and don't launch directly from SteamVR. Any ideas on how to fix this? Thanks.

**Comment by Armada651** [comment]
The Revive Dashboard has never shown Dirt Rally when installed through Steam.
