### ISSUE TITLE
Only show 4 games in revive tab of steam VR, what happened ? (mixed reality headset)

### ISSUE THREAD

**Issue by jostse** [LibreVR/Revive#918]
Just brought mixed reality headset.  
It seem that Oculus have lock up all the games until you have setup the Oculus head set.
It there anyway to unlock the free game without setup the Oculus headset ?

**Comment by jostse** [comment]
Only have DreamDeck , touch basics , contact , avatars.   That's all  ,  cannot see any other just like all the tutorial in youtube.

**Comment by fecheva** [comment]
Same here. 11 more are just text names. No scroll, no thumnails.
Data: I have my library installed in E:\Oculus\Software

Thanks for support.

**Comment by Armada651** [comment]
@fecheva The scroll bug is a SteamVR bug, will be fixed by Valve soon.

The missing thumbnails are due to the fact that Oculus Home Classic is no longer supported. You will need to either update to the new version of Oculus Home or downgrade Revive to version 1.2.0.

**Comment by jostse** [comment]
Thanks Armada651, thanks for your work and reply .  Finally  , I solved my problem, I figured that the revive tab only display the game which I owned ( purchased )  but not all the contents of the store.
I can see the game after I purchased them .  sorry for the misleading bug report.

**Comment by Kiefy** [comment]
![](https://image.prntscr.com/image/DEnpvVrtTxeftf7pTjJpeA.png)

Is there something I'm missing?  Do I also need to join the public test channel?

**Comment by LorkHang** [comment]
Copy StoreAssets contents from old location to the new one should restore the icons in the lastest version of Revive. 
_Games_install_location\Oculus\Software\Software\StoreAssets_
to
_Oculus_client_install_location\Oculus\CoreData\Software\StoreAssets_

**Comment by Armada651** [comment]
@Kiefy You're still on the old version (doesn't matter if you select the test channel). Try running the Oculus Home setup and selecting "Repair". The update mechanism for Oculus Home is not very robust.

**Comment by fecheva** [comment]
Now everything working ok here again

**Comment by martlume** [comment]
I had been owning a Vive for a while, when at some point the Revive tab in Steam stopped showing my games bought in the Oculus store (I only saw the 4 "tutorial apps").

In the Oculus app, I had two "Library Locations" (under General). Making the other Library Location "Default" fixed it for me.

**Comment by Armada651** [comment]
@martlume Revive currently only supports a single game library, see issue #928.

**Comment by martlume** [comment]
Wonderful, thanks so much for writing!

I guess like several people I have no idea how I ended up with two Oculus
game libraries!

Cheers,
Märt

**Comment by Dragoboss** [comment]
Ticket has been solved. Closing.
#928 remains open until multiple library locations are supported.
