### ISSUE TITLE
Esper 2: "Connect a head tracker position to continue"

### ISSUE THREAD

**Issue by Aoris** [LibreVR/Revive#92]
Hi, this game launch on my headset with injector method, I can control the camera by moving my head but i'm stuck in the loading room with this message "Connect a head tracker position to continue"
Another thing: I see the game in the steamVR dashboard but can't select it with my gamepad so I can only use injector method

**Comment by Aoris** [comment]
This game is reported as "working" here https://github.com/LibreVR/Revive/wiki/Compatibility-list
Can someone help me ? :)

**Comment by LibreVR** [comment]
I was just trying it out, works fine for me. Can you try the [latest version](https://github.com/LibreVR/Revive/releases/tag/0.5.1) and upload your log files?

**Comment by Aoris** [comment]
Tryied with last version but still this screen http://img15.hostingpics.net/pics/601621Esper22016051821400622.jpg

[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/271270/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/271271/ReviveInjector.txt)

**Comment by LibreVR** [comment]
The injector seems to work fine, seems to be a problem with one of your base stations then. I take it you're using an HTC Vive?

**Comment by Aoris** [comment]
Nope, i'm using Vridge app but it works nice with your app on Lucky's Tale, Oculus video, Dreamdeck, etc. Esper 2 is the only game who doesn't work. 
You think the problem is Vridge and not Revive?

**Comment by LibreVR** [comment]
That's definitely the problem, this error is caused be the fact that you don't have any positional tracking.

**Comment by Aoris** [comment]
Ok sorry then :/
Great app anyway :)

**Comment by LibreVR** [comment]
No problem. You can report problems with other headsets, but please mention it beforehand that you're not using an HTC Vive.
