### ISSUE TITLE
lone echo only work in version 1.1.9

### ISSUE THREAD

**Issue by danank92** [LibreVR/Revive#927]
lone echo only work in version 1.1.9 
version above 1.1.9 nothing works for me . it say vr server not running .
i using nvidia gtx 970 support vulkan
please help

**Comment by Armada651** [comment]
I very much doubt this is Revive-related, sounds like something else is wrong. Try uninstalling Revive and then installing it from scratch.

**Comment by danank92** [comment]
still not work. i use dk2

**Comment by Armada651** [comment]
DK2 is not supported in Revive.
