### ISSUE TITLE
Version 1.2.1.0 librevive32_1.dll triggering Bitdefender Anti Virus for Variant.Razy.257299

### ISSUE THREAD

**Issue by Caviel000** [LibreVR/Revive#929]
Bitdefender is throwing a warning about my installed 1.2.1.0 release, as the title says it has put librevive32_1.dll into quarantine for a virus signature.

**Comment by Armada651** [comment]
This happens every so often with bad virus scanners. I suggest you uninstall bitdefender and just use Windows Defender which ships with Windows.

If you don't want to do that, Revive will function for most games without `LibRevive32_1.dll`.

Note that LibRevive32_1.dll contains *exactly* the same code as LibRevive64_1.dll, which doesn't trigger the virus scanner. A clear sign your virus scanner lies to you on a regular basis.

**Comment by boynet** [comment]
add revive to exclusions on all bitdefender modules settings

**Comment by Armada651** [comment]
I don't recommend adding exclusions to your virus scanner, why have it installed in the first place if you're just going to add an exclusion whenever it detects something?
