### ISSUE TITLE
Blank ReVive tab in dashboard (Win 10)

### ISSUE THREAD

**Issue by darrellspivey** [LibreVR/Revive#93]
revive.vrmanifest:

> { "applications": [ { "app_key": "revive.dashboard.overlay", "arguments": "", "binary_path_windows": "ReviveOverlay.exe", "image_path": "revive.png", "is_dashboard_overlay": true, "launch_type": "binary", "strings": { "en_us": { "description": "Revive Dashboard overlay", "name": "Revive Dashboard" } } } ] }

File homes:

- **Oculus** D: > Oculus
- **Revive** D: > Program Files > Revive
- **Steam** D: > Program Files (x86) > Steam
- **SteamVR** D: > Program Files (86) > Steam > steamapps > common > SteamVR

**Comment by LibreVR** [comment]
Try redownloading and reinstalling Revive, a few hotfixes were applied that may fix your issue. Please let me know whether it's fixed for you.
