### ISSUE TITLE
Subnautica

### ISSUE THREAD

**Issue by ConorKnoxx** [LibreVR/Revive#930]
not really the right place for this I guess, I just couldn't find anything more relevant. Subnautica is not on the "compatible games" list - probably because you can just buy the Steam version. However I'm using Windows MR and the Steam version doesn't work. Wondering if anyone's tried the Oculus version? Likely the same problems, but it would be nice to know first-hand. (got a refund from Steam on it)

**Comment by Armada651** [comment]
How did you try to start the Steam version?

**Comment by Armada651** [comment]
Why not report the problem to the developers of the SteamVR WMR driver? The developers are pretty active on the steam forums for the driver.

If you want to use Revive instead I recommend waiting until WMR is officially supported in Revive.
