### ISSUE TITLE
Enabling Revive Dashboard Turns off Vive Screen

### ISSUE THREAD

**Issue by sohm16** [LibreVR/Revive#931]
I've been using Revive for a while now without any issues, but ever since recently if I have the Revive dashboard enabled, my Vive's display gets turned off very soon after starting up SteamVR. If I have the framerate display enabled, as soon as it gets to a stable framerate it seems like the display just shuts off, but I can see in the display mirror that it's still tracking normally. There's also a red light on the headset. If I then disable Revive Dashboard and reboot my PC, the Vive works normally. It comes across first as an issue with the cables, but it works consistently until I try enabling Revive dashboard again, then the whole process repeats. Any ideas? Am I doing something stupid? Thanks.

**Comment by Armada651** [comment]
I've run into similar problems where a reboot indeed fixes the problem. I thought it was something associated with a recent Nvidia driver update.

Are you sure it's the moment that you enable the Revive Dashboard that it crashes again?

**Comment by sohm16** [comment]
Nothing really crashes, just the display turns off as soon as the framerate indicator goes solid green. I've tried on multiple occasions and this only seems to occur when I have Revive Dashboard enabled (just tried again, worked before I tried enabling revive dashboard, enabled, didn't work, disabled, rebooted, worked). I also noticed that the framerate indicator is solid green a lot earlier on if I don't have revive dashboard enabled, like there's something that's trying a couple times to make the dashboard work until it just gives up and turns off the display.

I'm not sure if its related to the Nvidia driver update. I am on an Nvidia card, but I've definitely had this issue since before I updated to the latest driver.

**Comment by sohm16** [comment]
A couple things I've tried with no success (all leaving revive dashboard enabled):
- Reinstalling Revive
- Removing all SteamVR USB Devices from SteamVR Developer pane
- Disabling Direct Mode
- Reseating Vive cables in the headset and with the box.
- Plugging HDMI and USB cables directly into my PC

Also I wish I paid closer attention to the circumstances, but I have had Revive work once since this issue started. If I'm guessing the process I probably had a fresh boot with revive disabled so VR worked, then enabled revive dashboard and did something to refresh the dashboard like playing a game? It then worked, and I was able to play oculus games, then when I was done I disabled revive dashboard again to avoid the issue for next time. I haven't been able to replicate this scenario since, however.

I should also be running the latest updates (non beta branch or similar) for Revive, SteamVR, Nvidia drivers, and Win10.

**Comment by Armada651** [comment]
I can reproduce this problem even on an Oculus Rift headset. I'm going to try rolling back to a driver version before 390 from December 2017.

**Comment by Armada651** [comment]
Downgrading fixed the issue for me and Nvidia has been confirming this issue in all drivers 390 and up.

https://forums.geforce.com/default/topic/1038299/geforce-drivers/official-391-01-game-ready-whql-display-driver-feedback-thread-released-2-26-18-/post/5296731/#5296731

https://forums.geforce.com/default/topic/1035590/geforce-drivers/official-390-77-game-ready-whql-display-driver-feedback-thread-released-1-29-18-/post/5281619/#5281619

This is definitely not Revive-related.
