### ISSUE TITLE
Oculus Medium broken

### ISSUE THREAD

**Issue by chrisbraeuer411** [LibreVR/Revive#932]
I don´t know if the Medium Update itself or the latest Revive Update caused it but Medium is broken again.
It always crashes on startup. No difference steamvr or steam vr beta. Thats so frustrating.

**Comment by chrisbraeuer411** [comment]
note that i read the other Post with people get it working. But whatever i do it always crashes on startup. 
Please help me and tell me what i need to do.

**Comment by cartoonmonkey** [comment]
@chrisbraeuer411 Having difficulties this morning as well. Are you on a Windows Mixed Reality headset?

**Comment by Armada651** [comment]
This is indeed a different crash, it's coming from the Steam Overlay now. Try going to your Steam settings, open the In-Game tab and disable the Steam Overlay.

**Comment by chrisbraeuer411** [comment]
@cartoonmonkey 
No i use it with the vive.
@Armada651 
No luck with disabling the Steam Overlay. Same crash as before. You hear it starting up. On the Desktop you see it starting up but as soon as it is in it says Medium has crashed.

**Comment by Armada651** [comment]
@chrisbraeuer411 You also need to be using the SteamVR beta.

**Comment by cartoonmonkey** [comment]
@Armada651 I am, and it was working just yesterday, although intermittently on the Steam Beta and Windows MR.

**Comment by Armada651** [comment]
@cartoonmonkey Did you try disabling the Steam Overlay?

**Comment by cartoonmonkey** [comment]
Trying it now...

**Comment by cartoonmonkey** [comment]
@Armada651 That did it! Thank you!

**Comment by chrisbraeuer411** [comment]
@Armada651 For me it was now the steam VR beta. The Overlay thing did it. Thank you very much. 
The first time it finally started i got the insane rumble bug. (controller rumbles like crazy the whole time). But after restarting it it worked like a charm. Again THANK YOU. You saved my day!
