### ISSUE TITLE
LibRevive x86 missing from 1.2.1

### ISSUE THREAD

**Issue by mkoponen** [LibreVR/Revive#935]
I installed 1.2.1 as new installation on this PC, and patch-feature didn't do anything to the .exe directory. Upon investigation, I found that there was only one dll in the x86 directory of Revive's installation. 64bit had both. I installed 1.2.0 instead, and correct dll appeared. Then I installed 1.2.1 on top of it, and dll remained. I suspect the bug hasn't been noticed because this is the way most people have done it. Updates, not new installations. Clearly the binary is trying to find the missing dll, and unfortunately crashes in such a way that if you have never used Revive before, you think it has done its job. And then you wonder why nothing works.

**Comment by Armada651** [comment]
It's not missing, your virus scanner is deleting it.

**Comment by mkoponen** [comment]
Yep, thanks. F-Secure's log said this is the case.

**Comment by mkoponen** [comment]
I submitted the file to F-Secure as a false positive, and they confirmed that it is in fact so, and from the next update onward this will no longer happen.
