### ISSUE TITLE
Dirt Rally issues

### ISSUE THREAD

**Issue by mamefan** [LibreVR/Revive#936]
I had 1.2.0 installed, so I uninstalled it. DR would only run in desktop mode with it. I then installed 1.1.11 and injected the drt.exe and had the same issue. It wouldn't show in my Vive. I have the game theater thing unchecked, have Oculus home installed and running, and have that DirectX runtime installed. I was able to run this many versions ago, but I don't know what happened.

**Comment by Armada651** [comment]
> injected the drt.exe

I vaguely remember telling you before that you should not inject into the Steam version of Dirt Rally, that hasn't worked for a long time. You need to patch it and then run it through Steam as normal.

Even then patching Steam games is a hack, Revive generally works better with games bought from the Oculus store instead.

**Comment by mamefan** [comment]
I'm a good listener. Thanks.

**Comment by mamefan** [comment]
In January, you told me to get 1.1.12, but it isn't there.

**Comment by Armada651** [comment]
Yeah that one got deleted by accident, it's too much work to rebuild it. Please use the latest version.

**Comment by mamefan** [comment]
Wait, the latest version works now?

**Comment by Armada651** [comment]
It always has worked for me. For me it's still a mystery who some people report that 1.2 and up don't work.
