### ISSUE TITLE
Xbox One Controller Question

### ISSUE THREAD

**Issue by newend** [LibreVR/Revive#941]
Is there a way to use an xbox one controller and not have the steamvr menu pop up when you press start or select?  It used to not do this and I was not sure if there is a way to disable this within revive.  Ex. When I play chronos everytime I press start it opens up the steamvr menu.

**Comment by Armada651** [comment]
And it doesn't happen in other SteamVR games that don't use Revive?

**Comment by newend** [comment]
I was just curious if this is just a new general feature that was recently added.  Some oculus games use the controller to reset camera angle so I was not sure if there is a way to turn off the ability to open up the steam dashboard/ revive somewhere

**Comment by Armada651** [comment]
Why ask here and not in the SteamVR forum?
