### ISSUE TITLE
Failed to Initialize LibOVR, CAPI Error -3001

### ISSUE THREAD

**Issue by etarm** [LibreVR/Revive#945]
Anyone know if Revive was affected by the Oculus bug? It was working fine for me with From Other Suns up until yesterday, when it wouldn't launch the game. After selecting the game in Revive, I receive an error window "Failed to initialize LibOVR, 
CAPI Error: -3001
<OK> <QUIT>"

Selecting "OK" returns "Please check that your headset & sensor are connected and restart the application." Tried rebooting. Same problem.

**Comment by Armada651** [comment]
Looks like they updated to the latest version of the Oculus SDK meaning Revive needs an update. I plan to release a new version somewhere next week.

**Comment by etarm** [comment]
OK. Thanks.

**Comment by Armada651** [comment]
Also, make sure you installed the Oculus update if you haven't: https://www.oculus.com/rift-patch/

Revive requires a valid certificate signature is present.

**Comment by etarm** [comment]
Installing the Oculus update fixed it for me. I'm running again. Thanks!
