### ISSUE TITLE
Kin not recognizing xbox controller

### ISSUE THREAD

**Issue by srt23** [LibreVR/Revive#947]
Not sure if it is a issue with revive or the game Kin, but if I start it with only Xbox 360 or Xbox One controller connected it gives the error "No gamepad and no touch controllers found, attatch gamepad or touch controllers and restart the game". If I start with the wands on I can play with them, but not with the Xbox controllers, and that is not a good way to play that game.

**Comment by Krylke** [comment]
Tried it today and had the same problem. really want to play this game with gamepad.

**Comment by mamefan** [comment]
Same. X360 controller not working.

**Comment by DeutschRitter** [comment]
Does it work now?

**Comment by Armada651** [comment]
The beta supports it theoretically when using the SteamVR beta, I haven't tested it though.

**Comment by brunomaros** [comment]
Thank you for your reply... iam afreid that it wont work and ill hve to
refund again :D

Dňa pi 15. 6. 2018, 20:17 Jules Blok <notifications@github.com> napísal(a):

**Comment by brunomaros** [comment]
Unfortunately i must confirm that xbox controller doesnt work even with steam vr home beta turned on...

**Comment by Armada651** [comment]
SteamVR Home beta has no relation to it, where did you get that idea?

You need the Revive beta and the SteamVR beta.

**Comment by brunomaros** [comment]
Thanks i tried it and the game freezes right after i press the KIN icon in revive library. Ive installed SteamVR beta and also Riveve beta both newest versions... :(

**Comment by Armada651** [comment]
Should be fixed in the latest release.
