### ISSUE TITLE
Echo Arena and Lost Echo displaying only on desktop

### ISSUE THREAD

**Issue by gormanj** [LibreVR/Revive#948]
Installed 1.2.1. Now Echo Area starts up fine in VR, but as soon as I enter the lobby or a game, the HMD goes black and the game only shows on the desktop. Other than black screen on HMD, controlls in game are functional. Entering tutorials are no problem. Only the lobby and games cause a black screen on HMD only. Now the problem persists even after a PC restart, reinstalling Oculus, different versions of Revive, Echo Arena, Steam/Steam VR and Steam/Steam VR beta. Problem still occurs if launch game .exe game manually with Revive 64 in folder.

Update: I was able to temporarily fix this issue by updating my Nvidia GPU driver to 391.01. Attempting to downgrade it to 382.53 reproduced the problem. So I am at 391.01 hoping that driver will be stable.

Update 2: Though my system was working on Nvidia driver 391.01, as soon as I tried Revive 1.2.1, the problem reappeared. Sometimes the game also starts up only on the desktop. I'm having trouble duplicating a fix at this point and even though I am at 391.01 I cannot get Echo Arena working again.

Update 3: Clean install of Nvidia drivers temporarily fixed it, but then installing a downgrade of the Nvidia broke it again. Expect to eventually have to live with 391.01.

Update 4: Having trouble getting it to work at all now. Even when Echo Arena was working, Lost Echo was not. So I am a bit stumped. I've tried Nvidia Drivers 390.01, 382.53 and 388.71. I am on Windows 8.1 64bit.

My preference is to get my system working again on 382.53 which people seem to indicate as stable. More recent versions seem get crashed drivers often for me.

**Comment by gormanj** [comment]
Finally got to the bottom of this. It was a dashboard app called V. Quit it and the games that weren't launching to the HMD started working again.

**Comment by Armada651** [comment]
I wouldn't have been able to help you with that, this is the first time I heard of "V".

But thanks for letting me know, I'll keep in mind that dashboard applications can potentially prevent Revive games from working.

**Comment by gormanj** [comment]
I am almost embarrassed that I didn't figure it our sooner. It was a cool dash, that allowed you to bring web apps into vr: http://www.hellov.io/. Maybe I would not have had the problem if I updated.
