### ISSUE TITLE
WarThunder "Headset not detected" using Revive injector 0.5

### ISSUE THREAD

**Issue by Bourin** [LibreVR/Revive#95]
Hello,

At this point, it is impossible for me to run warthunder using the revive injector last version.
The 0.4 is worcking when i use a .bat file to lunch it, if not I'm geting the "Headset not detected" message.

So, at this point I have to keep the reviveinjector 0.4 for warthunder.

Win 10 x64
GTX 970

**Comment by LibreVR** [comment]
Make sure you're running [version 0.5.1](https://github.com/LibreVR/Revive/releases/tag/0.5.1) and then post your log in this issue report.

**Comment by Bourin** [comment]
Ok, I'll try this after worck

**Comment by Bourin** [comment]
Ok,
0.5.1 is lunching in the vive corectly using this .bat  (only working this way for me)

start "" "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" "C:\WarThunder\win64\aces.exe"

The log : 
Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe"  "C:\WarThunder\win64\aces.exe"
Creating process: C:\WarThunder\win64\aces.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x53a774d0
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x53a774d0
Injected dlls succesfully


Ps : I still have very bad GPU usage and bad FPS 
https://github.com/LibreVR/Revive/issues/96
