### ISSUE TITLE
Revive 1.2.2 Lenovo MVR most Oculus games won't launch

### ISSUE THREAD

**Issue by KennyMenny** [LibreVR/Revive#950]
Hi,

I wanted to get into VR gaming with my Lenovo explorer but with the current version of Revive (1.2.2), games like Bullet Train, Echo arena and Oculus First Contact briefly flash a loading screen before becoming greyed out in steamvr. OTher games like Epic Rollercoaster and dreamdeck work fine though. I noticed that the non-working are fine for version 1.2.0 and 1.2.1 for me, but I'd like to know if there is anything else I can do from my end to fix this before waiting on a new patch?

**Comment by jonnypanic** [comment]
I have the same thing on a Pimax 4K. I updated to get one game working and then many others stopped working. Will try going back to previous version.

**Comment by Armada651** [comment]
I apologize for that, I didn't push 1.2.2 through the automatic updater because it was untested. I didn't expect so many people to notice the new release.

I've removed the 1.2.2 release and am currently working on a fixed version. I suggest downgrading to 1.2.1 for now.

**Comment by jonnypanic** [comment]
No problem, 1.2.1 is good for me. Thanks for all the hard work.

**Comment by Armada651** [comment]
1.2.2 has been re-uploaded, the problem should be fixed now.
