### ISSUE TITLE
Oculus Dreamdeck with Revive

### ISSUE THREAD

**Issue by pascalelou** [LibreVR/Revive#951]
I have an issue with the stock game that comes with the Oculus on my HTC Vive :

I downloaded Revive for my newly acquired HTC Vive this week,it works fine with oculus games like the climb etc... But i can't launch the 4 games that comes with the Oculus installer (i wanted to try First contact and Oculus Dreamdeck). I tried launching them from the revive Dashboard (from Windows or SteamVR) but nothing happens.

I only get an error message if i try to launch them from Steam on my desktop. "Unable to launch XXX"

Is there any solution to launch those 2 games ? 

I'm using the latest Revive version (1.2.2)
Windows 10

**Comment by Armada651** [comment]
Please downgrade to 1.2.1, update 1.2.2 was pulled back because it caused a lot of issues. It wasn't pushed through the automatic updater so only people who manually updated are affected.

A fixed version will be out soon.

**Comment by pascalelou** [comment]
Downgrading to 1.2.1 fixed my problem, thank you !
