### ISSUE TITLE
WMR - Error 0xc000007b

### ISSUE THREAD

**Issue by kariyann** [LibreVR/Revive#952]
Hello,
I know Remixed is on the way et Revive is not fully WMR "ready" and I apologize for this post, but I would like to know what's happening when I launch an Oculus games with Revive.
What I did ?
I've Windows installed on my C: partition (SSD Drive) ;
1- Installed Oculus soft on vhd due to Dynamic Drive issue and its March patch (partition I: - HDD drive) ;
2- Installed Steam, Steam Vr and Revive ;
3- Installed some Oculus games from store to another drive (partition E: - HDD Drive);
4- I injected games via Revive (task Bar) ;
5- Tried to launch games from Revive overlay ;
---> game won't launch

So I tried to put game executable directly "in" Revive_injector" executable and then a command window opened, said "Inject openvr_api.dll" and then another popup window "application don't start correctly - error 0xc000007b".

Does anybody know want could be my problem ?
Thanks

**Comment by Armada651** [comment]
Damn, I might need to pull down the update again. Can you try version 1.2.1?

**Comment by kariyann** [comment]
Yesterday I tried 1.2.1, I'm currently under this version but still didn't work. I did'nt try other previous releases.
I was wondering if my configuration with multiple drives and Oculus Soft running in VHD could be the cause of my problem.

**Comment by kariyann** [comment]
I solved my problem : 
 1) move downloaded games on the same virtual disk than Oculus soft folder 
 2) increase virtual memory allocation in the Windows parameters
Now it's OK.
