### ISSUE TITLE
Steam VR game only opening on desktop

### ISSUE THREAD

**Issue by cappaholic** [LibreVR/Revive#954]
I “patched” a Steam game that I’m beta testing. It’s made for Oculus, and I’m on a WMR, so I need the ReVive Oculus button assignments.
But, after patching the game it now only opens on the desktop, not in the headset.

Any idea on how to fix this? Thanks.

**Comment by cappaholic** [comment]
Some more info...

The game is called Arrowborn. Per the Dev, it’s supported on Vive and Oculus, however the menu uses  HI image of an Ocuclus controller when showing the controller mapping.

A and B buttons are used, so I’m trying ReVive so I can use A and B on the WMR controller. So, I used the “patch” on the game’s exe file. Now the game only opens on the desktop, not the headset. 

Thanks in advance for any help.

**Comment by Armada651** [comment]
Launching Steam games with Revive is generally badly supported. If the game is on Steam, use SteamVR please.

Perhaps it will be supported better in the future.
