### ISSUE TITLE
No more banner pics on steam

### ISSUE THREAD

**Issue by rxstud2011** [LibreVR/Revive#956]
I know this is a minor issue, but after I updated I no longer have the banner pics. The games still show up (Artika1, Lone Echo, etc) but no pic.

**Comment by Armada651** [comment]
You need to update the Oculus Software, you can force an update by downloading the Oculus setup and choosing "Repair": http://oculus.com/setup

**Comment by rxstud2011** [comment]
I did this and nothing. The games do show up in Steam (lone echo, etc) and work. They display image or banner is just a blue box though.

**Comment by Armada651** [comment]
Go to the Software folder where your games are installed (defaults to `C:\Program Files\Oculus\Software\Software`) and move the `StoreAssets` folder to the `C:\Program Files\Oculus\CoreData\Software` folder. So you end up with `C:\Program Files\Oculus\CoreData\Software\StoreAssets`.

Only do that after you've tried the Repair setup. This is only an issue for Oculus installations that have been updated from 1.0 to 2.0.

**Comment by rxstud2011** [comment]
I don't have a store assets folder in software/software. I do

**Comment by rxstud2011** [comment]
I don't have StoreAssets folder in **C:\Program Files\Oculus\Software\Software) ** . I tried completely uninstalling it and reinstall it and still nothing. In C:\Program Files\Oculus\CoreData\Software\StoreAssets. this folder is empty. In Software/ I have 4 games: 4a-games-project-citadel, playful-luckys-tale, ready-at-dawn-echo-arena, ready-at-dawn-lone-echo  . They show up in revivie with the folder name but in steamvr show up with the actual game name. No image though :-(

**Comment by Armada651** [comment]
Then try the other steps I explained in my comment.

**Comment by metronome85** [comment]
Hi mate, love your work. You're a legend for creating ReVive.

As above, I also Revive working perfectly but the icons in Steam VR are the generic grey ones. I have attempted all of the above steps, but the Storeassets folder simply doesn't exist for me. At a loss, not sure what else to do.
