### ISSUE TITLE
DS4 Controller not working on Chronos

### ISSUE THREAD

**Issue by MrFroho** [LibreVR/Revive#957]
I have tried using DS4Windows and Inputmapper programs. I am able to open Chronos and get to the main menu screen but my DS4 controller doesn't do anything. If I press the Playstation button the Xbox menu thing pops up and I can navigate that no problem, but the Chronos game itself is unresponsive.

I noticed that 1 of my Vive controllers was able to navigate the menus somewhat, is it possible that my vive controller is overriding my DS4 controller for input priority or something?

**Comment by MrFroho** [comment]
I just noticed something. While in game almost no buttons work on the controller except 'Share', for some reason Share makes the menu move down, each time I press it it moves the menu down until I get to Exit and then it stays there.

**Comment by Armada651** [comment]
Can you try a version of revive before 1.2.0?

**Comment by MrFroho** [comment]
Hey Armada,

Thanks for investigating this issue. I uninstalled revive and reinstalled Version 1.1.14. Initially most of my Revive games disappeared, even Chronos was blank but I just used the recently played shortcut in the Steam Home place.

Other things I noticed: 

In my Steam Status tray it shows 2 game controllers as being plugged in. When I unplug the DS4 both controllers turn off and in Chronos a pop-up comes saying 'please plug in gamepad or oculus controller' something to that effect. Now when I plug the DS4 back in only one of the 2 controllers in my steam Status turn but in-game the error doesn't go away, and nothing I do on any controller can make the pop-up go away.

I also noticed Vive controllers can navigate the menus pretty decently, I haven't gotten into the real game but I think its possible to play with the Vive controllers, though it seems like that may be a very frustrating experience.

If you would like me to test any other steps let me know, I'm happy to guinea pig.

**Comment by MrFroho** [comment]
I should have done this earlier, but controller is also not working on Luckys Tale, so this is not a game specific issue.

**Comment by MrFroho** [comment]
Took me about 4 hours of trouble shooting. I did many things but I think the main thing that fixed this was Hiding the DS4 controller in DS4Windows. I think Steam Big Picture was giving me Controller 1 and my DS4Windows Xbox controller was being set to Controller 2 and so it just wouldnt work for some reason. Anyways I hope this helps someone. Cheers.
