### ISSUE TITLE
Can you add SteamVR games to the revive overlay?

### ISSUE THREAD

**Issue by jonnypanic** [LibreVR/Revive#959]
This isn't really an issue, of course, so apologies. But I was wondering if I can also add SteamVR games to the overlay to use it as a simple launcher for all VR games. 

Cheers.

**Comment by Armada651** [comment]
I'm glad you like they overlay, but that isn't something I'm planning to do.

However anyone with the skill to do so can fork the overlay code. By using the OpenVR Applications API you can actually query a database of all installed SteamVR games, including the ones add by Revive.
