### ISSUE TITLE
ReMixed controllers don't work while in games.

### ISSUE THREAD

**Issue by Josh19002** [LibreVR/Revive#962]
While I use the newly released ReMixed beta controllers within the games are not detected and do not input any button presses pressed on the touchpads. 
The games that I have tested this with so far extend to that of, Lucky's tale, Oculus Dreamdeck, Oculus Touch Controller Basics, and Spider Man Homecoming VR (Which also has an even worse issue of the headset not tracking at roomscale and the gyroscope seems to be inverted. But the Controllers are working more effectively allowing button input and the tracking that's enabled when you cant see the controllers (approximated by gyroscope)) 
If it affects anything I am currently using the Acer Windows Mixed Reality Headset and controllers as well  as the Windows Insider Preview, but I doubt that would effect it as it hasn't caused issues in the past.

**Comment by Armada651** [comment]
This seems to be an issue related to window focus. Try Alt-Tabbing out of and into the game and the controllers should show up then.

**Comment by Josh19002** [comment]
I’ll try it when I am at home again, but which window do I switch to? Remixed or the game itself. Also is there any way to inject games into Remixed?

**Comment by Dragoboss** [comment]
Doesn't work.
Sometimes it does recognize the controller movement, but the game still gives its usual 'Hardware Error' Oculus screen.

Sometimes it simply doesn't track the controllers at all.

**Comment by Armada651** [comment]
Can you try the Oculus First Contact demo or the Touch Tutorial?

**Comment by Dragoboss** [comment]
I tested From other Suns just now. With this game indeed if Win+Y is on, and after launching the game you go back to cliffhouse / skylounge, then tap back into Remixed, controllers work.

FoS takes longer to lauch than other games I tested, I again have the feeling this plays a role.

**Comment by otichy** [comment]
For me, with alt+tabbing, First Contact also works fine, but Farlands (that requires remote rather than touch) does not work. Interestingly, it gets mapped to mouse and keyboard instead.

**Comment by Obi2000** [comment]
I'm still having problems with controllers not being detected on Win 1809, Revive 1.6.2. The in-game screen shows red controller outlines, while my desktop shows the black Oculus hardware error screen. With Echo VR sometimes the alt-tab trick works. But the game I really want to play, Lone Echo, never works.

**Comment by perfecteuphoria2** [comment]
I have an Odyssey+ and my hands don't work either but if I back out to WMR home and go back into Remixed i'm able to use my in game hands in the menu but I'm unable to start the game or press any of the menu buttons.

**Comment by JoePinapples** [comment]
I have very similar problem. I can load into the menu but I cannot get game to launch. I have Samsung Odyssey Plus headset and the controllers are not being recognized.
See my issue raised:
#1158 
This seems to be an outstanding issue for some time now. With many people experiencing it that own a Samsung Odyssey & Odyssey Plus. It would be really nice to get some feedback on a the progress for a solution, or to know if it is even something that is being worked on!! If not I will return the game and get a refund.

**Comment by appleguy** [comment]
Same problem here. Commented on #1152 with more details.

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
