### ISSUE TITLE
Sound switch to headset

### ISSUE THREAD

**Issue by Dragoboss** [LibreVR/Revive#963]
Remixed:

When starting a game without the WMR portal already running, the game doesn't switch to the headset-attached sound device.

I assume if a delay were to be put in between starting the portal before starting the actual game, this would be solved.

Reproduce:
1. Close WMR portal,
2. click a game (one that isnt extremely big and loads quick) like Echo Arena on the Revive dashboard
3. WMR portal will start but the game simultaneously
result: sound stays upon the computer's device and doesn't switch to HMD.

Thank you for putting time into a Mixed Reality version of your software. It is really appreciated.

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
