### ISSUE TITLE
No audio on one specific game : Chronos

### ISSUE THREAD

**Issue by triodusiecle** [LibreVR/Revive#965]
I am using latest Revive (1.3.0.1) with WMR, all games are working flawlessly except one: Chronos.
I can have everything workling except there is no Audio at all.
All other games/apps are working. Any ideas?

**Comment by Armada651** [comment]
Chronos has always worked with sound in my testing. You're the only one to report otherwise so far.

Have you looked in your volume mixer to check if you didn't accidentally mute it at some point? Volume mixer levels are saved even after you quit the application.

**Comment by triodusiecle** [comment]
strange because all other games are working fine, I also went into Chronos volume settings and set volume to 100%, still no luck

**Comment by Armada651** [comment]
No, not the Chronos volume settings, check the Windows Volume Mixer.

**Comment by triodusiecle** [comment]
ok so I played around and I found the problem. My PC is connected to my TV via HDMI.
I disabled HDMI sound and used PC speaker and now the sound is working.
So if I narrow my issue now, how can I make the sound to go out to my TV? looks like only Chronos is doing this as all other games output the sound correctly with the HDMI setup

**Comment by Armada651** [comment]
Your TV? You need to use the audio solution your headset came with. This is *not* an issue with Revive.
