### ISSUE TITLE
Remixed: Darker scenes in headset

### ISSUE THREAD

**Issue by Dragoboss** [LibreVR/Revive#969]
A new problem I discovered, while this may be related to how the games are programmed:

In some games, the in-game scenes are much darker than the on-screen scenes. When running the same game in SteamVR+Revive, this is not the case.
As if Revive translates the color schemes differently than Remixed does, translating in a different result in the HMDs.

Can someone shed some *light* on this?

**Comment by Armada651** [comment]
This sounds like Remixed failed to do the SRGB conversion correctly. Which games are you seeing this in?

**Comment by Dragoboss** [comment]
First one I noticed it at were Lone echo and Echo arena..... Those are my main games anyway.

I'll do some testing today and come up with a more comprehensive list. Then again I do not have a whole lot of oculus games.

**Comment by Dragoboss** [comment]
I should note I did find a temporary work around, but setting the video gamma settings higher in the Nvidia control panel by temporarily attaching another screen

**Comment by Armada651** [comment]
SRGB is used for gamma correction, so by changing your gamma you're essentially doing that manually.

**Comment by Armada651** [comment]
Anyway, it makes sense it doesn't work well with Lone Echo, it uses the R11G11B10 format. Which doesn't automatically convert between SRGB and RGB.

**Comment by Dragoboss** [comment]
I see
Well, guess that means I'll have to deal whenever playing those games.

**Comment by Dragoboss** [comment]
Any chance we could somehow set multiple pre-game profiles for the color schemes?

**Comment by Armada651** [comment]
I could just implement the proper conversion in Remixed, but your idea sounds insane and cumbersome, I like it.

**Comment by Armada651** [comment]
Should be fixed in the new beta: https://github.com/LibreVR/Revive/releases/tag/1.4.0

**Comment by Dragoboss** [comment]
Confirmed fixed.
