### ISSUE TITLE
Wont let me play echo arena its says I dont have hardware set up

### ISSUE THREAD

**Issue by KennyTheKennyPlease** [LibreVR/Revive#972]
Everytime I try launching echo arena it has an error and closes right after I start it. i try uninstalling and reinstalling both revive and oculus please help!

**Comment by AltVRat** [comment]
Same thing happened to me after the update to Echo VR and the latest Oculus. As a last ditch effort I did a direct injection from the revive app and it worked!! Revive library failed, Vive home failed, Oculus failed of course but then inject and go!!!

**Comment by Armada651** [comment]
Duplicate of issue #1015.
