### ISSUE TITLE
Echo arena not working

### ISSUE THREAD

**Issue by yy344** [LibreVR/Revive#973]
soo i injected revive to EchoArena.exe in the  oculus apps  folder. but when i launch, it says i need  to purchase  or  download even tho i already own it. how  to fix dis??

**Comment by Dragoboss** [comment]
If you're still trying this:
Don't manually inject Echo. Play it through Revive with SteamVR.
(or Remixed if you use WMR).
Worth another try with the new Echo Combat.

**Comment by Dragoboss** [comment]
No response given, assuming he either found the solution or no longer cares.
