### ISSUE TITLE
Screen Stuttering when in Use

### ISSUE THREAD

**Issue by Enzdude** [LibreVR/Revive#974]
I use the Remixed version of Revive for my Mixed Reality headset. When I play any game from the Revive Dashboard, the game has some sort of form of screen tearing (I'll just call it screen stuttering). What happens is when I turn or move in the game, the frames seem to overlap each other, which gets annoying.

**Comment by superisty** [comment]
I have same problem in some games (Robo Recall, Luckys Tale) for my WMR headset (samsung odyssey).
With SteamVR version of Revive , this problem dose not occur.

**Comment by Enzdude** [comment]
Noted. I'll wait for an update and use Revive until then.

**Comment by DawsSangio** [comment]
Noted. Indeed Revive works pretty well directly from SteamVR with thumbs stick support, even in Windows 17134. Remixed from clif house give me stutter too, wait for official support. Thanks

**Comment by Dragoboss** [comment]
Would these stutters be caused purely by lacking some of the rendering optimizations?

I am also being told in several online games that 'my character' is slightly 'shaking' when other players look at me. I am assuming this is a result with a similar cause.

I think it was a little better before I upgraded to the 'Spring update' build 1803.

**Comment by lepidecko** [comment]
+1 for Odyssey support in remixed ;)

Latest windows build (up to date on 10th of May 2018) left and right image separation seems too little in Odyssey causing image overlap and death by headache ;))

**Comment by Armada651** [comment]
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
