### ISSUE TITLE
Remixed: Controllers getting stuck

### ISSUE THREAD

**Issue by Dragoboss** [LibreVR/Revive#977]
Way more often than what it used to do with Revive, the Windows Mixed Reality controllers seem to get stuck on various positions when using Remixed.
Basically, as soon as I start moving around the controllers at an intense speed, I can see the controllers seeming to 'lock' into place until I push them out far enough for them to snap out of it again.

This is while the controllers are fully within the FOV of the cameras.
It is the same effect when the controllers are out of the FOV for a longer period they get stuck in their position but rotation/orientation still works, while position gets based on where the headset is.
This may be a cause of the latest windows build 1803 or not. It just seems curious, as if the software switches to its 'extrapolation mode' quicker than intended.

**Comment by janyses** [comment]
Afraid I can't help with your issue, but I did notice the same problem in the WMR version of Bigscreen versus the SteamVR version. In WMR, the controllers are constantly locking making it very difficult to control. I don't know how this behavior compares to Remixed, as I haven't really had a chance to test it.

**Comment by Dragoboss** [comment]
Might be a result in the latest Windows feature update then rather than in Remixed. I didn't notice it on ReVive before but if you say it's present there too maybe there is more to this than I thought.
