### ISSUE TITLE
Please don't touch anything not working with Revive

### ISSUE THREAD

**Issue by Xatulu** [LibreVR/Revive#98]
Hey guys,

i just bought Please Don't Touch Anything - big mistake. Game doesn't work with Revive, CTD immediately with no warning message or anything.

I'll try restarting the PC and will have a look if that fixes it.

**Comment by Xatulu** [comment]
My bad, restart fixed it.

**Comment by LibreVR** [comment]
Yeah Oculus Home actually has a convenient option for that. Go to `Settings > Beta > Restart Oculus` and then you can fix these issue without rebooting your PC.

You should do that every time you install a new game.
