### ISSUE TITLE
Can't launch games with revive

### ISSUE THREAD

**Issue by filmgeek47** [LibreVR/Revive#981]
Trying games that are verified as compatible, but nothing works. Launching most games causes the revive window to grey, without actually seeing a window pop up. Some unreal games show a window that immediately freezes and crashes. 

Running on a vive pro if that matters. Using version 1.3.1.0

**Comment by filmgeek47** [comment]
Tried 1.3.0, still having the same issue. 
To be clear, I used windows add/remove to uninstall the overlay, then ran the installer for 1.3.0. Assuming that should have done a clean install of the app?

Let me know if I you need a log file or anything, I'd love to get this working. Thanks!

**Comment by joshthejosher** [comment]
Yea i'm having the same issue. No matter the headset or machine even a clean install of Windows doesn't fix the issue. I'm not sure if its Oculus software but any games through the Oculus launcher including Dreamdeck crashes on load and or responds with a "Not an Oculus error message". This issue is consistent with 1.3.0 and 1.3.1.

**Comment by mgarrington** [comment]
I'm having the same experience. Games won't open through either Steam or the Windows Revive Dashboard. 

I went back to Version 1.2.2, and opening games via Steam worked like a charm.

**Comment by Paulconvey** [comment]
Same issue here too.  All games immediately crash on launch.  However, 1.2.2 is fine.

**Comment by rxstud2011** [comment]
Same here. I'm also running a Vive Pro and going back to 1.3.0 did nothing. I'll try 1.2.2 like others suggested.

**Comment by rxstud2011** [comment]
I tried and can confirm 1.2.2 works.

**Comment by filmgeek47** [comment]
Good call. 1.2.2 works here as well.

**Comment by filmgeek47** [comment]
Off topic, but is vibration not supported in any games, or just elven assassin? ( know it has a vive version but I'm trying to play with oculus friends...)

**Comment by killshotz** [comment]
Same issue here, reverting to 1.2.2 is not working, any suggestions? I just got my vive 2 days ago and this is the first time I've installed revive.

**Comment by filmgeek47** [comment]
@killshotz my first time too, so I can only guess. Did you uninstall 1.3 before installing 1.2.2 over it? Did you restart the oculus service after installing games (in the oculus app I went to beta>restart).

**Comment by killshotz** [comment]
I had 1.3.1 installed and when i saw there was an issue with it I uninstalled revive dashboard through my programs, and then reinstalled 1.2.2 with no luck. all games still broken. I then tried 1.2.1 and SOME games would work like dream deck, Avatars and First contact. but no luck with the game that ive really been wanting to play, Echo Arena. It shows up but crashes on launch

**Comment by ytdlder** [comment]
Just fyi:
Yesterday I started Arktika1 (totally sic game btw!^^) and today - even though there hasn't been a new release in over a month (!) - I got a Revive update notification (~61MB) which I downloaded and installed. I tried looking in Windows Programs, but there is no version information :-\

Anyway, since that update Arktika1 doesn't even start; "exe stopped working" error.
So I manually installed v1.3.0 and the same error occurrs.

I then tried the older 1.2.2 and Arktika works again!!

-> I'm pretty sure I had v1.3.0 installed before. Is it possible that 1.3.0.2 patch installs something that isn't removed via Uninstall and so every 1.3 installation fails on that point forward?

**Comment by Armada651** [comment]
Sorry about that, 1.3.0.2 was meant to fix a small issue with the dashboard overlay, but it looks like I compiled that release with the wrong version of the Oculus SDK. I'll release 1.3.0.3 using the correct version of the Oculus SDK.

**Comment by JorenRapini** [comment]
Just tried reinstalling 1.3, all games still broken for me. 1.2.2 did the trick, was able to run every game I tried except Robo Recall (opens it at least, just get a crash report though)

**Comment by Armada651** [comment]
@JorenRapini The fixed version of 1.3 has been up for a month, I'd expect more bug reports if it was still broken.

**Comment by JorenRapini** [comment]
Weird, I tried reinstalling 1.3 a couple of times. Don't know what could be wrong then, I have the latest steam VR beta and Oculus updates. No biggy though, I can wait until the next update, thanks.

**Comment by Armada651** [comment]
Version 1.3 is intended for the SteamVR stable though, have you tried opting out of the SteamVR beta?

**Comment by danvic7** [comment]
For me what solved the issue was opting out of SteamVR Beta (thanks @Armada651 ). Before that I had tried Version 1.4.0 Beta, Version 1.3.0, Version 1.2.2, Version 1.2.1 and they were all returning what the OP mentioned.

**Comment by JorenRapini** [comment]
Yup sorry, opting out of steamvr beta did it for me too.

**Comment by matheuslarcher20** [comment]
The latest versions do not work xbox control, only version 1.1.14.2 works. I also wanted to play minecraft on windows 10 edition on my pimax 4k.

**Comment by Dragoboss** [comment]
Original ticket was solved.
Not sure what to do with latest comment..
Please provide more info in a new support ticket if you still want this to be looked into, as detailed as you can in the new format.
