### ISSUE TITLE
Remixed: Headset is off signal

### ISSUE THREAD

**Issue by Dragoboss** [LibreVR/Revive#982]
What I have been playing with are some multiplayer games, some of which have spectator modes.

Now with the Rift, once you take off the headset, the little sensor in there tells the game that the headset is off.
Our Mixed Reality headsets have a similar sensor, which are currently used to turn the 'computer input' on and off. Which can then be reversed by pressing Windows+Y Button.
However, through Remixed, this signal is not being sent to the Oculus framework.

In games where this signal IS being sent and being picked up on by the game, when the headset is off they show a different view on the screen. A birds-eye spectator view.

It would be useful if Remixed were to send this signal as well, so we can use these kind of modes.

**Comment by Armada651** [comment]
Please try the beta release: https://github.com/LibreVR/Revive/releases/tag/1.4.0
