### ISSUE TITLE
Motion Latency in Games

### ISSUE THREAD

**Issue by Enzdude** [LibreVR/Revive#986]
I use a WMR Headset with Revive, not remixed. When I play Oculus game through revive and move/turn my head, the game responds a bit slow to this change in orientation. Why is this?

**Comment by Dragoboss** [comment]
I do not have this effect through Revive nor Remixed.
What are your computer specs?

**Comment by Enzdude** [comment]
@Armada651 I mainly play The Unspoken, and that's about it.
@Dragoboss i7-4578U (2-core/4-thread, behaves like a quad core), 8 GB RAM, and GTX 1050 Ti (soon 1070).

**Comment by Dragoboss** [comment]
I believe that the CPU there is just under the recommended specs of most VR Games.
The fact that you're going to be running WMR ---> SteamVR ---> Revive ---> Oculus games might add some trouble.

What level of settings are you running the games on?
Also see what resolution SteamVR is trying to make your pc run the games at.

I am pretty sure you can run the majority of games without too high settings if you manually optimize some settings, but with that said the CPU especially in combination with your current GPU might be the bottleneck.

Anyone may correct me if I am wrong....

**Comment by Armada651** [comment]
@Enzdude The Unspoken has a lot of inherent latency issues that require very careful optimization to work around. It's the worst-case game latency-wise and going through two compatibility layers (Revive and SteamVR for Mixed Reality) only makes it worse.

I'm currently working on optimizing Remixed, so try the new version of Remixed when it is out.

**Comment by Enzdude** [comment]
@Dragoboss I run The Unspoken at Ultra because it seems to zoom in when I run it on lower settings. I'm not sure what resolution SteamVR is running at.

**Comment by Dragoboss** [comment]
Until Armada implements said optimizations, which he is working on very hard, clearly... Check this imgur post to see the two pages in steamvr settings you might want to have a look at. If indeed steamvr has set a higher resolution, it could explain the zoom you're seeing when you lower it from the game settings, which would explain a bit. 

https://imgur.com/a/pu7R6nV

In my case steamvr tried to have me run 24~~ something when I was still running Revive ... 
I'm not sure if I even saw the difference when within the headset so I lowered it.

**Comment by Armada651** [comment]
Try the latest beta with native Mixed Reality support: https://github.com/LibreVR/Revive/releases/tag/1.4.0
