### ISSUE TITLE
Default Input Mapping File is a dead link... Anyway to still get it?

### ISSUE THREAD

**Issue by electryic** [LibreVR/Revive#988]
As per the title was trying to grab that file not sure if anyone can help.  Thanks

**Comment by electryic** [comment]
Hi Jules:

Thank you kindly for the link to the Default Input .lua file.    Is there
someway to download or copy that file as a .lua file directly?  I am seeing
the file but not a link to download it directly as a .lua.  I copied the
entire thing into a onto a .txt file and saved it as a .lua file but I
don't think it worked, most likely because of the missing line numbers.
Sorry if this is obvious and I'm missing it and thank you for the time you
put into this.   If there's anything I can do to help please let me know.

**Comment by Armada651** [comment]
I'd recommend switching to the SteamVR beta, then you can use the SteamVR input support in the beta version of Revive: https://github.com/LibreVR/Revive/releases/tag/1.4.0

This should be easier than editing a lua file.
