### ISSUE TITLE
Unable to Launch app: Unable to find the HMD (1971039)

### ISSUE THREAD

**Issue by gormanj** [LibreVR/Revive#99]
Recently I have been unable to run several Oculus home games. I am using Revive 0.5.1. Lucky's tale started giving either entitlement check fail or cannot find headset. Most others either get a can't find hmd or cannot run this application without an Oculus Rift (including Dreamdeck, Farlands, Henry, Lost). The Body VR just quits after a second. All of these title were working before (many with 0.5.1). The only thing I have working is Invasion and Oculus Introduction to Virtual Reality. I'm not sure what happened, I've tried reinstalling Oculus Hone, turning unknown sources off and then back on, restarting and running different combinations of controllers, SteamVR and Oculus Home running/being on or off.

**Comment by LibreVR** [comment]
You were first, but it has been correctly diagnosed in issue #100 so I'm closing this one as a duplicate.
