### ISSUE TITLE
Hi ! I bouth the game "RUSH" on oculus store and it doesn't detect my controllers . I tried all but it doesn't work. This game look cool but i can use it with my HTC VIVE

### ISSUE THREAD

**Issue by Skread30** [LibreVR/Revive#990]

**Comment by Armada651** [comment]
Don't use the beta version of Revive, use version 1.3.0: https://github.com/LibreVR/Revive/releases/tag/1.3.0

**Comment by Armada651** [comment]
Which headset are you using? Does SteamVR detect the controllers?

**Comment by Skread30** [comment]
Sorry i put a new post because with the 1.3.0 version in the game "RUSH" (race of wingsuit) i can't see & use my controlers. I made a ALT+TAB out in and it didn't fix it. :( do you have another suggestion for me?

I installed with reviveinstaller.exe  i didn't use other 2 folders named "SOURCE CODE" should i use it?

**Comment by Skread30** [comment]
i can play with all other games in oculus or steam vr
my controllers work . I see them when the game is loading but in the game my friend and i can't see or use controllers to "start" we can use to go in main menu steam but not in game

**Comment by Skread30** [comment]
i have a htc vive

**Comment by Skread30** [comment]
i run the dashbord revive before steam vr or into my steam room but nothing change

**Comment by Skread30** [comment]
Hey goodnight , did you see my messages? do you need more informations? my friend have the same probleme with the same headset

**Comment by Skread30** [comment]
Hi? i need to write a new issue?

**Comment by Skread30** [comment]
will it have some issue? should we sell the game definitively? Do i need a new post? 
thanks

**Comment by Armada651** [comment]
Don't spam, the issue is in the tracker, you'll just have to be patient.

**Comment by Skread30** [comment]
Hi 
I didn't spam anymore but i wrote 2 month ago and now i cant refund the game and it is available on steam... will you have a update? or i have to buy it twice?... once on oculus who doesn't run and the second on steam ...will i loose 20 €?

Thanks for answer.

**Comment by Armada651** [comment]
The goal is to eventually support all games, but that takes time. As such the instructions specifically state the following:

> Always check the [compatibility list](https://github.com/LibreVR/Revive/wiki/Compatibility-list) before making a purchase.

If you buy a game that is not in the compatibility list and you don't refund it if it doesn't work, then that is on you.
