### ISSUE TITLE
Remixed: Samsung Odyssey, Double Vision

### ISSUE THREAD

**Issue by LuckyGoodHeart** [LibreVR/Revive#993]
Some games using Remixed have double vision: Lucky's Tale, Coco VR, Heart of EmberStone, etc. using the Samsung Odyssey. Brass Tactics Arena works fine - much better graphics performance using Remixed versus Revive. Thanks for the amazing work.

**Comment by Armada651** [comment]
Thanks for the report, I'll look into these issues soon.

**Comment by AceHack** [comment]
@LuckyGoodHeart @Armada651 I can't get my Samsung to show anything in Remix, works awesome in Revive, but I just get a black screen in Remix.

Any suggestions?

**Comment by AceHack** [comment]
I'm running Windows 10 Pro Insider Build 17686.rs_prerelease.180603-1447.  This is part of the skip ahead ring.

**Comment by Armada651** [comment]
@AceHack Please do not hijack existing tickets, create new ones unless the ticket describes your issue exactly.

**Comment by Armada651** [comment]
Remixed has been replaced by ReviveXR: https://github.com/LibreVR/Revive/releases/tag/1.7.0
