### ISSUE TITLE
Steam VR Controls not Working in Many Games

### ISSUE THREAD

**Issue by SyntaxJO** [LibreVR/Revive#994]
Been a long while since I've played.

The controllers work in First Contact, but I can't get them to work in Lone Echo, Echo Area, Ripcoil, etc.

The game loads, the controllers are tracked well, none of the buttons work.

I'm sorry if there's a known solution for this.

Thanks!

**Comment by Armada651** [comment]
Sounds like you've downloaded the beta version without reading the instructions saying not to download the beta.

**Comment by SyntaxJO** [comment]
Wasn't working in Steam's Super Hot either (not even movement).

BUT I did a bunch of restarts again, and the controllers started working on everything.

I had restarted before, but for some reason it took finally.

Thanks for this great tool you've created! Really amazing.

**Comment by SyntaxJO** [comment]
Then when I tried Super Hot from steam, the controllers weren't working either; not even the movement.

BUT I restarted a couple more time, even though I had done it before, and the controllers started working on everything. So we're good.

Thanks for making this incredible tool. Really amazing!
