### ISSUE TITLE
Revive app not fulfilling primary function

### ISSUE THREAD

**Issue by HoneyBea** [LibreVR/Revive#999]
I have varying results when trying each item on my revive dashboard, but none of them are functional.

https://i.imgur.com/kN4FLEM.jpg

This is an image of my revive dashboard. The first three items from left to right all display the message "Cannot run this without an Oculus Rift" when I attempt to start them up. The avatars app will open on my computer, but will not display in the headset. And when I attempt to start damaged core, nothing happens.

Any suggestions or help with fixing this would be greatly appreciated, thanks so much.

**Comment by Dragoboss** [comment]
@HoneyBea Are you running SteamVR when attempting to use the dashboard?

Because just for the record, when SteamVR is NOT running and you click the dashboard shortcut icons, ever since 1.3.0 it defaults to attempting to run Windows Mixed Reality.
Whereas if SteamVR is running it defaults to Revive.

**Comment by Dragoboss** [comment]
Well, my last comment to this was over six months ago. Never got a reply.
I am simply assuming the user fixed their issue or moved on. Closing for now.
